// client/src/lib/coreAttributesData.js
// Core Counseling Attributes — foundational knowledge tested on NCMHCE

export const CA_SECTIONS = [
  {
    id: 'alliance',
    title: 'Therapeutic Alliance',
    icon: 'Heart',
    color: 'rose',
    summary: 'The single strongest predictor of outcome. The exam tests your ability to recognize alliance signals and repair ruptures before moving to technique.',
    topics: [
      {
        id: 'rogers',
        title: "Rogers' Core Conditions",
        opening: 'Meta-analyses consistently show that the therapeutic relationship accounts for more outcome variance than the specific technique used. Rogers argued that three counselor-provided conditions are both necessary and sufficient for change — and the NCMHCE tests every one of them by showing you a counselor response and asking which condition it demonstrates.',
        keyIdea: 'Three necessary and sufficient conditions for therapeutic change.',
        content: [
          { label: 'Unconditional Positive Regard (UPR)', detail: 'Valuing the client\'s personhood regardless of behavior, choices, or disclosures. Not approval — non-judgmental warmth. Violated when a counselor implies the client should feel differently or signals disapproval.' },
          { label: 'Empathy (Accurate Empathic Understanding)', detail: 'Tracking both content and underlying emotion, and communicating that understanding back. Not sympathy ("I feel sorry for you") and not agreement ("You\'re right, your boss is terrible"). It is: "I am with you in your experience."' },
          { label: 'Congruence (Genuineness)', detail: 'The counselor\'s internal experience, outward expression, and words align. Not performing warmth while feeling bored. Authenticity — sometimes includes naming what\'s happening in the room.' },
        ],
        examTip: 'When the exam asks which response "best demonstrates" a core condition, UPR = non-judgmental, empathy = reflects feeling, congruence = authentic self-expression.',
        dialogue: {
          setup: 'Client: "I\'ve been drinking every night. I know it\'s bad, but honestly? It\'s the only time I feel like myself."',
          good: 'Counselor (UPR): "That\'s worth understanding — what does feeling like yourself mean to you in those moments?"',
          bad: '"Have you considered what alcohol is doing to your body?" — This is evaluative, not UPR.',
        },
        closing: 'Bottom line: if the response evaluates, advises, or implies the client should feel differently, it violates UPR. If it tracks emotion, it demonstrates empathy. If it\'s authentically present, it\'s congruence. These three are your alliance foundation.',
      },
      {
        id: 'bordin',
        title: "Bordin's Working Alliance",
        opening: 'When treatment stalls, the question isn\'t always "is the technique wrong?" Often it\'s "which part of the alliance broke?" Bordin\'s model gives you a diagnostic framework for alliance ruptures — and the exam tests whether you can name the broken component and match it to the right repair.',
        keyIdea: 'Three components — bond, goals, tasks — that must all be intact for treatment to proceed.',
        content: [
          { label: 'Bond', detail: 'Emotional connection, trust, felt sense of being valued. Strained when the client feels judged, misunderstood, or unsafe.' },
          { label: 'Goals', detail: 'Mutual agreement on what treatment is for. Strained when the client doesn\'t believe the stated goals are their goals.' },
          { label: 'Tasks', detail: 'Agreement that the methods used will reach the goals. Strained when the client questions why they are doing an exercise or technique.' },
        ],
        examTip: 'Identify WHICH component is strained to know what repair to attempt. Task rupture → renegotiate methods. Goal rupture → re-explore what the client wants. Bond rupture → slow down and rebuild trust.',
        dialogue: {
          setup: 'Client doing behavioral activation for 3 weeks: "I don\'t see why I keep filling out these activity logs. My problem isn\'t that I don\'t do things — it\'s that nothing feels worth doing."',
          good: 'This is a task rupture. Explore her understanding, validate, collaboratively renegotiate the approach.',
          bad: 'Defending the technique or reassigning the homework ignores the rupture.',
        },
        closing: 'Remember: bond = "Do I feel safe here?", goals = "Are we working on MY problem?", tasks = "Does this method make sense to me?" Match the strain to the repair.',
      },
      {
        id: 'rupture',
        title: 'Rupture & Repair',
        opening: 'The exam rarely says "the alliance is rupturing." Instead, it shows a client who seems disengaged, pushes back on homework, misses appointments, or says counseling isn\'t helping. These are alliance signals in disguise — and the correct answer is almost always to address the relationship before returning to technique.',
        keyIdea: 'Ruptures are alliance breakdowns. Repair them before anything else.',
        content: [
          { label: 'Withdrawal Rupture', detail: 'Silence, vagueness, sudden compliance, emotional flatness — the client has pulled back without saying so.' },
          { label: 'Confrontation Rupture', detail: 'Direct disagreement, irritation, or challenging the counselor\'s approach.' },
          { label: 'Repair Sequence', detail: '(1) Notice the shift → (2) Name it without blame → (3) Explore the client\'s experience → (4) Acknowledge your contribution if relevant → (5) Re-contract.' },
        ],
        examTip: 'Alliance questions are often disguised as "what do you do next" items. The client seems disengaged, pushes back, misses appointments, or says counseling isn\'t helping. Recognize these as alliance signals — validate BEFORE technique.',
        dialogue: {
          setup: 'Client who usually speaks openly arrives and gives one-word answers, avoids eye contact.',
          good: '"I notice you seem different today — quieter, maybe more guarded." (Names observation tentatively.)',
          bad: 'Continuing the session agenda or asking directly "What\'s wrong?" misses the relational communication.',
        },
        closing: 'The takeaway: when a client\'s behavior shifts, your first clinical response is to name the shift and explore it — not to plow ahead with the plan. The exam consistently rewards noticing and naming over technique.',
      },
      {
        id: 'stages',
        title: 'Stages of Counseling',
        opening: 'Every counseling relationship moves through predictable stages, and the exam tests whether you know what to prioritize at each one. The most common mistake? Jumping to treatment planning in the initial stage before the client feels heard — or extending treatment when termination regression is actually normal.',
        keyIdea: 'The exam tests clinical priorities at each stage, not just the names.',
        content: [
          { label: 'Exploration / Initial Stage', detail: 'Safety assessment comes first. Alliance-building is the primary task. Do NOT move to goal-setting before the client feels heard. Jumping to treatment planning in the first session loses points.' },
          { label: 'Working / Middle Stage', detail: 'The treatment plan is active. Resistance and ruptures are most likely here because the work gets harder. The counselor moves between support and challenge.' },
          { label: 'Termination Stage', detail: 'Raise termination early enough for processing. Pre-termination regression is NORMAL and EXPECTED — not a sign of failure. Name the pattern, normalize it, continue the planned termination.' },
        ],
        examTip: 'A client who regresses near termination does NOT need extended treatment. The correct response is to name the pattern and connect it to the ending.',
        dialogue: {
          setup: 'Client who met all goals begins arriving late and canceling 3 weeks before final session.',
          good: '"I wonder if these changes might be connected to our approaching ending — that can bring up a lot."',
          bad: 'Extending treatment by 4 sessions without exploring the dynamic reinforces avoidance.',
        },
        closing: 'Know the stage, know the priority. Initial = safety + alliance. Working = support + challenge. Termination = name the regression, don\'t extend reactively.',
      },
      {
        id: 'cultural',
        title: 'Cultural Responsiveness',
        opening: 'Cultural responsiveness questions are among the most nuanced on the NCMHCE because the wrong answer often sounds clinically reasonable — it just applies the counselor\'s cultural framework instead of the client\'s. The exam consistently rewards humility (asking and learning) over competence (applying what you know about a group).',
        keyIdea: 'Cultural humility > cultural competence on the exam.',
        content: [
          { label: 'Cultural Humility', detail: 'The client is the expert on their own cultural experience. The counselor asks, learns, and remains curious rather than applying assumptions. Humility wins on the exam.' },
          { label: 'Cultural Competence', detail: 'Implies mastery — learning enough about a group to work with any member. Exam favors humility over this approach.' },
          { label: 'Countertransference', detail: 'The counselor\'s emotional reaction rooted in their own history or biases. Recognize it, contain it, use it as clinical data, seek consultation when unmanageable. Never act on it impulsively.' },
        ],
        examTip: '"I\'d like to understand how your family thinks about getting help" (humility) beats "I know that in many [cultural group] families, mental health carries stigma" (competence).',
        dialogue: {
          setup: 'Client from a collectivist culture is disengaging after counselor encouraged "setting limits with your family."',
          good: 'Re-explore what the client actually wants. The counselor\'s goal (individual autonomy) may conflict with the client\'s cultural values.',
          bad: 'Doubling down on boundary-setting or labeling the client as having "difficulty with assertiveness."',
        },
        closing: 'The rule: when in doubt, ask the client about their experience rather than applying your knowledge about their group. Humility is curiosity. Competence without humility is assumption.',
      },
    ],
  },
  {
    id: 'theories',
    title: 'Theories & Orientations',
    icon: 'Lightbulb',
    color: 'blue',
    summary: 'Every major theory has 1–2 signature techniques that appear on no other theory\'s menu. Learn the signatures and you can identify the orientation from the technique alone.',
    topics: [
      {
        id: 'psychodynamic',
        title: 'Psychoanalytic / Psychodynamic',
        opening: 'Psychodynamic questions on the NCMHCE follow a pattern: a vignette describes a counselor exploring the past, interpreting unconscious material, or working with the therapeutic relationship as data. Your job is to recognize the signature techniques — because no other theory uses them.',
        keyIdea: 'Unconscious conflicts and early attachment patterns shape present functioning. Change comes through insight.',
        content: [
          { label: 'Free Association', detail: 'Access unconscious material by removing censorship — client says whatever comes to mind.' },
          { label: 'Dream Analysis', detail: 'Examine manifest (surface) vs. latent (hidden) content of dreams.' },
          { label: 'Transference Interpretation', detail: 'Use the therapeutic relationship as a window into the client\'s relational patterns.' },
          { label: 'Defense Analysis', detail: 'Identify and gently challenge protective mechanisms (denial, projection, etc.).' },
        ],
        examTip: 'Look for stems about "exploring childhood experiences," "interpreting a dream," or the client "relating to the counselor as if they were a parent."',
        closing: 'If the stem mentions unconscious material, dreams, transference, or defenses — it\'s psychodynamic. No other theory lives in this territory.',
      },
      {
        id: 'adlerian',
        title: 'Adlerian (Individual Psychology)',
        opening: 'Adlerian therapy is often tested through its unique concepts — birth order, social interest, early recollections, and "The Question." These don\'t appear in any other orientation\'s toolkit, making Adlerian items relatively easy to identify once you know the signatures.',
        keyIdea: 'People are motivated by social interest and striving to overcome inferiority. Birth order, lifestyle, and fictional final goals shape behavior.',
        content: [
          { label: 'Lifestyle Assessment', detail: 'Understand the client\'s characteristic pattern of engaging the world.' },
          { label: 'Early Recollections', detail: 'Access the client\'s guiding life narrative through earliest memories.' },
          { label: '"The Question"', detail: '"What would be different if you were well?" — Distinguishes psychological from organic factors; reveals avoidance.' },
          { label: 'Encouragement', detail: 'Counteract discouragement, which Adler saw as the root of dysfunction.' },
        ],
        examTip: 'Birth order + early recollections + social interest = Adlerian. Goal-directed and often shorter-term than classical psychoanalysis.',
        closing: 'Spot the Adlerian item: birth order is mentioned, early memories are explored, or the counselor asks "What would change if the problem were gone?" That\'s your match.',
      },
      {
        id: 'humanistic',
        title: 'Humanistic / Person-Centered',
        opening: 'Person-centered therapy is the most-tested humanistic approach on the NCMHCE because its principles overlap with alliance-building — which the exam prioritizes above all else. The trap: confusing humanistic with existential. Both value authenticity, but humanistic is non-directive and relationship-focused; existential is more confrontational about avoidance.',
        keyIdea: 'People have an innate actualizing tendency blocked by conditions of worth. The therapeutic relationship IS the change mechanism.',
        content: [
          { label: 'Reflective Listening', detail: 'Communicate empathic understanding — follow, don\'t lead.' },
          { label: 'Non-directive Exploration', detail: 'Follow the client\'s lead; resist the expert role.' },
          { label: 'Congruent Self-disclosure', detail: 'Authentic presence when therapeutically relevant.' },
        ],
        examTip: 'Non-directive stems, emphasis on relationship over technique, Rogers\' three conditions. Pick the MOST empathic or LEAST directive response.',
        closing: 'The signal: no technique is named, the counselor follows rather than leads, and the relationship itself is the intervention. That\'s person-centered.',
      },
      {
        id: 'cbt',
        title: 'Cognitive-Behavioral Traditions',
        opening: 'CBT is actually a family of approaches, and the exam tests whether you can distinguish between them. The most common mistake: calling the ABC model "CBT" when it\'s REBT, or confusing DBT skills with general CBT techniques. Each sub-modality has its own target and its own signature tool.',
        keyIdea: 'Thoughts, feelings, and behaviors are interconnected. Changing distorted cognitions and maladaptive behaviors changes affect.',
        content: [
          { label: 'CBT (Beck)', detail: 'Thought records, Socratic questioning. Targets cognitive distortions.' },
          { label: 'REBT (Ellis)', detail: 'ABC model, disputation. Targets irrational beliefs (not just distortions).' },
          { label: 'DBT (Linehan)', detail: 'Skills training: TIPP, DEAR MAN, STOP, Wise Mind. Specifically for emotion dysregulation / BPD / chronic suicidality.' },
          { label: 'Behavioral (Skinner/Wolpe)', detail: 'Exposure, systematic desensitization, token economy. Targets conditioned responses. Pairs with anxiety disorders.' },
        ],
        examTip: 'ABC model = REBT, NOT CBT. Thought records = CBT. DBT = BPD / emotion dysregulation. "What evidence do you have?" = Socratic questioning (CBT).',
        closing: 'The cheat sheet: "What evidence?" = Beck\'s CBT. "What belief?" = Ellis\'s REBT. "What skill?" = Linehan\'s DBT. "What exposure?" = behavioral. Don\'t cross-contaminate.',
      },
      {
        id: 'systemic',
        title: 'Systemic / Family Systems',
        opening: 'Systemic approaches are tested through their most distinctive techniques — each one belonging to exactly one school. If you can match the technique to the school, you can answer the item without analyzing the vignette further. Five approaches, five signature moves.',
        keyIdea: 'Client\'s symptoms are expressions of a system\'s dynamics. Change the system, symptoms resolve.',
        content: [
          { label: 'Structural (Minuchin)', detail: 'Joining, enactment, boundary-setting. Focuses on subsystems, boundaries, hierarchy.' },
          { label: 'Strategic (Haley)', detail: 'Directives, paradoxical intention. Targets problem-maintaining sequences.' },
          { label: 'Bowenian', detail: 'Genogram, coaching differentiation. Focuses on differentiation, triangulation, emotional cutoff.' },
          { label: 'Solution-Focused (SFBT)', detail: 'Miracle question, scaling, exception-finding. Focuses on client strengths, brief therapy.' },
          { label: 'Narrative', detail: 'Externalization ("When did the anxiety first try to take over?"), re-authoring, unique outcomes. The problem is separate from the person.' },
        ],
        examTip: 'Miracle question = SFBT. Enactment = Structural. Genogram = Bowenian. Externalization = Narrative. These are the most-tested pairings.',
        closing: 'Five schools, five instant matches: enactment → Structural, paradox → Strategic, genogram → Bowenian, miracle question → SFBT, externalization → Narrative. Lock these in.',
      },
      {
        id: 'existential',
        title: 'Existential Therapy',
        opening: 'Existential therapy is the theory students most often confuse with humanistic — and the exam exploits this confusion. The key difference: humanistic is warm and non-directive; existential directly confronts the client\'s avoidance of life\'s ultimate concerns. If the stem mentions meaning, death, freedom, or isolation, it\'s existential.',
        keyIdea: 'Addresses ultimate concerns: freedom, death, isolation, meaninglessness. More confrontational about avoidance than humanistic.',
        content: [
          { label: 'Four Ultimate Concerns', detail: 'Death, freedom/responsibility, isolation, meaninglessness — the existential givens that create anxiety.' },
          { label: 'Authenticity', detail: 'Living in alignment with one\'s true values despite societal pressure.' },
          { label: 'Dereflection / Paradoxical Intention (Frankl)', detail: 'Stop fighting the symptom or redirect attention away from it.' },
        ],
        examTip: 'Existential is NOT the same as humanistic. Humanistic = non-directive, warmth. Existential = confronts avoidance, explores meaning and mortality.',
        closing: 'The distinguishing test: if the counselor is warm and follows the client\'s lead, it\'s humanistic. If the counselor challenges avoidance and names existential givens (death, freedom, isolation, meaninglessness), it\'s existential.',
      },
    ],
  },
  {
    id: 'skills',
    title: 'Microskills & Techniques',
    icon: 'MessageCircle',
    color: 'emerald',
    summary: 'Skills form a developmental sequence: Attend → Listen → Influence. You must earn the right to move up the hierarchy. "Validate before you challenge" is the exam\'s cardinal rule.',
    topics: [
      {
        id: 'hierarchy',
        title: 'Microskills Hierarchy',
        opening: 'Counseling skills are not a menu you pick from at random. They form a developmental sequence with a clinical logic: you must earn the right to move up the hierarchy by doing the lower levels well first. The exam tests this relentlessly — every time it tempts you to confront, interpret, or advise before the client feels heard, it\'s testing whether you know the hierarchy.',
        keyIdea: 'Attend → Listen → Influence. Lower skills must be established before higher skills are effective.',
        content: [
          { label: 'Attending Skills', detail: 'Nonverbal and physical presence. Eye contact, body posture, spatial distance. Must come first — a distracted counselor fails before speaking. Eye contact norms vary across cultures.' },
          { label: 'Listening Skills', detail: 'Paraphrase, reflection of feeling, reflection of meaning, summarization. These build the alliance and communicate understanding. The engine of every session.' },
          { label: 'Influencing Skills', detail: 'Confrontation, self-disclosure, interpretation, immediacy, information-giving. Require a solid alliance. A confrontation without alliance lands as an attack.' },
        ],
        examTip: 'The exam frequently tempts you to intervene (influence) before the listening foundation is laid. When in doubt, the lower-hierarchy skill wins.',
        closing: 'One rule covers nearly every microskills item on the exam: if the alliance isn\'t solid yet, go lower on the hierarchy. Listen before you influence. Reflect before you confront. Always.',
      },
      {
        id: 'listening',
        title: 'Listening Skill Discrimination',
        opening: 'Paraphrase, reflection of feeling, immediacy, and confrontation — these four skills are the most confused group on the NCMHCE. The exam gives you a counselor response and asks you to name the skill, or it gives you a client statement and asks which skill to use. Getting these wrong costs easy points. The fix: know exactly what each one does and does not do.',
        keyIdea: 'The four most-confused skills on the exam. Know the differences.',
        content: [
          { label: 'Paraphrase', detail: 'Restates CONTENT in your words. Does not name emotion. "You\'re telling her things are okay even though you\'re struggling."' },
          { label: 'Reflection of Feeling', detail: 'Names the EMOTION the client is experiencing. Does not summarize content. "There\'s something exhausting — and maybe lonely — about carrying all of this."' },
          { label: 'Immediacy', detail: 'Addresses the COUNSELOR-CLIENT RELATIONSHIP in the here-and-now. Not about the client\'s outside relationships.' },
          { label: 'Confrontation', detail: 'Points out an INCONGRUITY between two things the client said, or between words and behavior. Tone is gentle and curious, not attacking.' },
        ],
        examTip: 'When the client expresses distress, the first scored response reflects FEELING, not content. When the client is resistant, acknowledge the resistance, don\'t argue against it.',
        dialogue: {
          setup: 'Client: "I keep telling my wife I\'m fine, but honestly, I don\'t sleep, I can\'t concentrate, and I feel like I\'m carrying this weight I can\'t put down."',
          good: 'Reflection: "There\'s something exhausting about carrying all of this privately." Confrontation: "You say you\'re fine to your wife, but what you\'re describing sounds far from fine. What do you make of that?"',
          bad: 'Giving advice, psychoeducation, or a diagnosis label at this point skips the listening foundation.',
        },
        closing: 'The discrimination test: Does it restate content? Paraphrase. Does it name emotion? Reflection. Does it address the counselor-client relationship right now? Immediacy. Does it name an incongruity? Confrontation. Run this test on every option.',
      },
      {
        id: 'influencing',
        title: 'When to Use Influencing Skills',
        opening: 'Influencing skills are the most powerful tools in your repertoire — and the most dangerous if mistimed. The exam specifically tests whether you know WHEN each skill is appropriate, because using an influencing skill before the alliance is established is one of the most common clinical errors it assesses.',
        keyIdea: 'Each influencing skill has specific prerequisites and timing rules.',
        content: [
          { label: 'Confrontation', detail: 'Appropriate when: (1) alliance is strong, (2) a discrepancy exists between words and behavior, (3) the discrepancy maintains the problem. NEVER in the first session. NEVER when the client is acutely distressed.' },
          { label: 'Interpretation', detail: 'Appropriate when: sufficient data gathered, client is receptive, offered tentatively ("I wonder if..."), not as a pronouncement.' },
          { label: 'Self-Disclosure', detail: 'Appropriate when: it normalizes, strengthens alliance, or models coping. Must be brief and client-focused, NOT counselor-centered. Exam punishes lengthy self-disclosure that shifts focus.' },
          { label: 'Immediacy', detail: 'Appropriate when: the in-session relational dynamic is more clinically important than the content — e.g., client replicates a problematic pattern with the counselor.' },
        ],
        examTip: 'Appropriate self-disclosure: "When you describe your situation, I feel sadness for what you\'ve been carrying." Inappropriate: "I went through a divorce myself" (shifts focus to counselor).',
        closing: 'The timing rule: influencing skills require a strong alliance, sufficient data, and a receptive client. If any of these is missing, drop down the hierarchy and listen more. The exam rewards patience.',
      },
      {
        id: 'motivational',
        title: 'Motivational Interviewing (MI)',
        opening: 'MI appears across multiple NCMHCE domains — substance use, health behavior change, treatment compliance, and any scenario involving ambivalence. It\'s not a separate theory so much as a clinical spirit that can overlay any modality. The exam tests whether you can resist the "righting reflex" — the urge to argue for change — and instead draw out the client\'s own motivation.',
        keyIdea: 'Resolving ambivalence about change through collaborative, evocative, client-centered conversation.',
        content: [
          { label: 'Spirit of MI', detail: 'Partnership, acceptance, compassion, evocation. The counselor draws out the client\'s own motivation — doesn\'t install it.' },
          { label: 'OARS', detail: 'Open questions, Affirmations, Reflections, Summaries — the fundamental MI skills.' },
          { label: 'Change Talk vs. Sustain Talk', detail: 'Elicit and reinforce change talk (desire, ability, reasons, need, commitment). Roll with sustain talk — don\'t argue against it.' },
          { label: 'Readiness Ruler', detail: '"On a scale of 1–10, how important is it to you to make this change?" Then explore: "Why a 5 and not a 3?"' },
        ],
        examTip: 'MI appears in substance use, health behavior, and any ambivalence scenario. The "righting reflex" (arguing for change) is the #1 MI mistake tested.',
        closing: 'MI\'s golden rule: the client should be the one arguing for change, not you. If you\'re working harder than the client to make the case for change, you\'ve fallen into the righting reflex. The exam catches this every time.',
      },
    ],
  },
  {
    id: 'group',
    title: 'Group Counseling',
    icon: 'Users',
    color: 'amber',
    summary: 'The group is the client, not a collection of individuals. The leader tends the group as a living system — its norms, cohesion, stage, and safety.',
    topics: [
      {
        id: 'types',
        title: 'Group Types',
        opening: 'The NCMHCE expects you to match the group type to the clinical need — and to know that the leader\'s role changes dramatically depending on the type. A psychoeducational group leader teaches; a process group leader observes dynamics and catalyzes interaction. Using the wrong leader style for the group type is a scored error.',
        keyIdea: 'Different groups require different leader roles.',
        content: [
          { label: 'Psychoeducational', detail: 'Skill-building, information delivery. Leader acts as teacher/facilitator.' },
          { label: 'Skills-Training', detail: 'Practice specific skills (DBT groups, parenting groups). Leader acts as coach/trainer.' },
          { label: 'Support', detail: 'Normalize, provide peer support. Leader is low-directive facilitator.' },
          { label: 'Process / Interpersonal', detail: 'Uses group dynamics as the change mechanism. Leader is process observer — the most clinically demanding type.' },
          { label: 'Psychotherapy', detail: 'Deep personality and relational change. Leader is boundary-holder and clinician.' },
        ],
        examTip: 'If the question describes the group as a social microcosm where members learn about their relational patterns, it\'s a process/interpersonal group.',
        closing: 'Match the type to the role: teaching → psychoeducational, coaching → skills, facilitating → support, observing dynamics → process, holding boundaries → psychotherapy. The leader role is the giveaway.',
      },
      {
        id: 'tuckman',
        title: "Tuckman's Stages",
        opening: 'Tuckman\'s stages appear on the NCMHCE in a predictable way: a vignette describes group behavior and asks what the leader should do. The most-tested stage is storming — because the instinct to suppress conflict is exactly the wrong answer. A leader who deflects all conflict keeps the group permanently stuck in forming.',
        keyIdea: 'Forming → Storming → Norming → Performing → Adjourning. Know the leader\'s focus at each stage.',
        content: [
          { label: 'Forming', detail: 'Inclusion, safety, initial trust. Leader provides structure and establishes norms.' },
          { label: 'Storming', detail: 'Conflict, challenge, jockeying for position. Leader normalizes conflict and protects safety. Do NOT shut conflict down — navigating conflict IS the therapeutic work.' },
          { label: 'Norming', detail: 'Cohesion, established roles, deepened trust. Leader steps back, facilitates member-to-member interaction.' },
          { label: 'Performing', detail: 'Productive work, self-disclosure, insight. Leader is catalyst with minimal direction.' },
          { label: 'Adjourning', detail: 'Termination, integration, grief. Leader processes endings and transfer of learning.' },
        ],
        examTip: 'The exam trap: in storming, the instinct is to suppress conflict. The correct response is to name and normalize it while keeping it safe. Deflecting all conflict keeps the group in perpetual forming.',
        closing: 'The storming test: if conflict is happening and the leader shuts it down, that\'s the wrong answer. If the leader names it, normalizes it, and keeps it safe — that\'s the scored response. Trust the process.',
      },
      {
        id: 'yalom',
        title: "Yalom's Therapeutic Factors",
        opening: 'Yalom identified 11 curative factors that make group therapy uniquely powerful. The NCMHCE tests five of them repeatedly — and the most important is interpersonal learning, because it explains why group therapy does something individual therapy fundamentally cannot.',
        keyIdea: '11 curative factors unique to group therapy. Five are most tested.',
        content: [
          { label: 'Universality', detail: '"I\'m not alone in this" — the relief of shared human experience.' },
          { label: 'Cohesion', detail: 'The group\'s felt sense of connection and belonging. Group equivalent of the alliance.' },
          { label: 'Altruism', detail: 'Members gain from GIVING help, not just receiving it.' },
          { label: 'Instillation of Hope', detail: 'Seeing others improve provides evidence that change is possible.' },
          { label: 'Interpersonal Learning', detail: 'The group becomes a social microcosm — members learn about relational patterns through live interaction.' },
        ],
        examTip: 'Why is group therapy uniquely powerful for relational difficulties? Answer: interpersonal learning — the group provides live relational data that individual therapy cannot.',
        closing: 'When the exam asks "why group therapy specifically?" the answer is almost always interpersonal learning or universality. Group provides something individual therapy can\'t: live relational data and the relief of shared experience.',
      },
      {
        id: 'leadership',
        title: 'Leadership Skills',
        opening: 'Group leadership skills are tested through brief scenarios: a member dominates, a member is silent, two members argue. Your job is to name the correct leader intervention. Four skills cover nearly every scenario the exam presents — linking, blocking, drawing out, and cutting off.',
        keyIdea: 'Four key leader interventions that maintain group function.',
        content: [
          { label: 'Linking', detail: 'Connect what one member said to another\'s experience. Builds cohesion.' },
          { label: 'Blocking', detail: 'Stop behavior that harms the group: unsolicited advice, intrusive questions, domination.' },
          { label: 'Drawing Out', detail: 'Invite silent members to participate. "Jordan, you\'ve been quiet — I\'m curious what\'s coming up for you."' },
          { label: 'Cutting Off', detail: 'End a member\'s sharing when it\'s too lengthy or keeps the group stuck. Done respectfully but firmly.' },
        ],
        examTip: 'Leader priority under pressure: (1) Safety of all members → (2) Group cohesion → (3) Individual therapeutic progress → (4) Efficient use of time.',
        closing: 'Four scenarios, four skills: "These two experiences connect" = linking. "That behavior harms the group" = blocking. "You\'ve been quiet" = drawing out. "Let me pause you there" = cutting off.',
      },
      {
        id: 'groupethics',
        title: 'Group Ethics',
        opening: 'Group ethics questions center on one principle that candidates consistently get wrong: the counselor cannot guarantee confidentiality from other group members. This is the single highest-yield group ethics concept on the exam. If you remember nothing else about group ethics, remember this limitation.',
        keyIdea: 'The counselor can promise confidentiality from themselves but CANNOT guarantee it from other group members.',
        content: [
          { label: 'Confidentiality Limits', detail: 'Must be disclosed in pre-group screening and group agreement. The counselor establishes a confidentiality norm but cannot enforce it legally among members.' },
          { label: 'Pre-group Screening', detail: 'Required for therapy groups. Assess client appropriateness, explain group norms, obtain informed consent.' },
          { label: 'Dual Relationships', detail: 'Particularly complex in groups — members may know each other outside the group, especially in small communities.' },
        ],
        examTip: 'If a group member asks "Is what I share confidential?", the correct answer acknowledges the norm AND its limits — never simply says "yes."',
        closing: 'The one-sentence summary: you can set the expectation of confidentiality, but you cannot promise it on behalf of other members. Always disclose this limitation.',
      },
    ],
  },
  {
    id: 'priority',
    title: 'Clinical Priority Ladder',
    icon: 'Shield',
    color: 'purple',
    summary: 'One framework governs every scored decision. When two answers both seem correct, ask: which rung is higher? The higher-rung action wins.',
    topics: [
      {
        id: 'ladder',
        title: 'The Priority Ladder',
        opening: 'If you learn one framework from this entire guide, make it this one. The priority ladder governs every scored decision on the NCMHCE. When two answers both seem correct — and on this exam, they often do — the one at the higher rung wins. Every time.',
        keyIdea: 'Memorize this hierarchy. Apply it before you pick any answer.',
        content: [
          { label: '1. Imminent Safety', detail: 'Suicidality, homicidality, abuse, danger — NOTHING else happens first. Always assess safety before anything.' },
          { label: '2. Medical / Substance Rule-outs', detail: 'Could this be organic? Could substances explain it? Rule out before diagnosing a mental health condition.' },
          { label: '3. Stabilization', detail: 'Acute symptom relief, grounding, crisis reduction. Stabilize before processing.' },
          { label: '4. Alliance & Validation', detail: 'Before any intervention, the client must feel heard. Validate before you challenge.' },
          { label: '5. Clarify the Picture', detail: 'Assessment, history, collateral information. Gather enough to form a working hypothesis.' },
          { label: '6. Evidence-Based Treatment', detail: 'The right modality for the right diagnosis. Match treatment to the clinical picture.' },
          { label: '7. Ethics Throughout', detail: 'Confidentiality, mandated reporting, competence — woven into every rung, not a separate step.' },
        ],
        examTip: 'When two answers both seem correct, the answer at the HIGHER rung wins. Safety > medical rule-out > stabilization > validation > assessment > treatment.',
        closing: 'This ladder is your answer key. When stuck between two options: which rung is higher? Pick that one. It works on virtually every NCMHCE item.',
      },
      {
        id: 'traps',
        title: 'Common Exam Traps',
        opening: 'The NCMHCE is not a knowledge test — it\'s a clinical reasoning test. It rewards efficiency, not thoroughness. The most common traps are all versions of the same mistake: doing the right thing at the wrong time. Understanding these patterns can prevent dozens of lost points.',
        keyIdea: 'The exam rewards clinical efficiency, not thoroughness.',
        content: [
          { label: 'Jumping to Treatment', detail: 'Selecting a therapeutic technique before establishing alliance or completing assessment. Always validate first.' },
          { label: 'Skipping Safety', detail: 'ANY mention of suicidal ideation, self-harm, or danger means safety assessment is the ONLY correct first response.' },
          { label: 'Over-assessing', detail: 'Administering a comprehensive personality battery when the clinical picture already points to a specific diagnosis. Gather what changes your decision, nothing more.' },
          { label: 'Attractive Distractors', detail: 'Options that sound clinically reasonable but aren\'t the BEST choice for THAT stage. All four options may be defensible — the question is which a competent entry-level counselor would prioritize.' },
          { label: 'Ignoring Ruptures', detail: 'Moving forward with the session agenda when a client shows signs of disengagement, frustration, or resistance. Address the alliance first.' },
        ],
        examTip: 'Ask: "Would this information change my diagnosis or treatment plan RIGHT NOW?" If no, it\'s not the best answer.',
        closing: 'Every trap is a timing error: right action, wrong moment. Before you pick any answer, ask two questions: "Is there a safety concern?" and "Is the alliance intact?" If either answer is no, those must be addressed first.',
      },
      {
        id: 'ethics',
        title: 'Ethical Decision-Making',
        opening: 'Ethics questions on the NCMHCE test judgment in gray areas — not memorization of code sections. You won\'t be asked to recite ACA Code B.1.c. You\'ll be given a messy scenario where two ethical principles compete, and you\'ll need to pick the response that best protects the client while managing competing obligations.',
        keyIdea: 'Ethics questions test judgment in gray areas, not memorization of codes.',
        content: [
          { label: 'Duty to Warn / Protect', detail: 'When a client presents imminent danger to an identifiable third party. Tarasoff standard. Overrides confidentiality.' },
          { label: 'Mandated Reporting', detail: 'Suspected child abuse, elder abuse, or abuse of vulnerable adults. Not optional — failure to report is an ethics and legal violation.' },
          { label: 'Informed Consent', detail: 'Ongoing process, not a one-time form. Includes risks, benefits, alternatives, limits of confidentiality, fees, and theoretical orientation.' },
          { label: 'Scope of Competence', detail: 'Practice within your training and seek supervision or referral when a case exceeds your competence. The exam rewards knowing your limits.' },
          { label: 'Dual Relationships', detail: 'Not all dual relationships are prohibited — but they must be managed. The test: does this relationship risk exploitation or harm to the client?' },
        ],
        examTip: 'When in doubt on an ethics question, the answer that involves consultation, documentation, and protecting the client\'s welfare is usually correct.',
        closing: 'The ethics safety net: when you\'re unsure, the answer that consults, documents, and protects the client is almost always right. When principles compete, client welfare wins.',
      },
    ],
  },
];

// Tutor scenarios — used by the backend to generate practice rounds
export const TUTOR_SCENARIOS = [
  { id: 'ts1', domain: 'alliance', prompt: 'Your client has been making progress for 8 sessions. Today she sits down and says: "I don\'t think this is working anymore. Maybe I should try someone else." What is your best response, and why?', targetConcepts: ['rupture', 'withdrawal', 'alliance repair', 'validate before technique'] },
  { id: 'ts2', domain: 'alliance', prompt: 'A client from a collectivist culture tells you his family thinks therapy is shameful. He seems torn between continuing and stopping. How do you respond?', targetConcepts: ['cultural humility', 'ambivalence', 'goals rupture'] },
  { id: 'ts3', domain: 'theories', prompt: 'A counselor asks: "When did the depression first try to convince you that you were worthless?" Which theoretical orientation is this, and what is the technique called?', targetConcepts: ['narrative therapy', 'externalization'] },
  { id: 'ts4', domain: 'theories', prompt: 'A client says she feels like a fraud at work despite a recent promotion. The counselor asks: "What evidence do you have that your coworkers think you\'re incompetent?" Name the theory and technique.', targetConcepts: ['CBT', 'Socratic questioning', 'cognitive distortions'] },
  { id: 'ts5', domain: 'skills', prompt: 'Client: "I keep telling everyone I\'m fine but I haven\'t slept in weeks." Write a reflection of feeling response, then write a confrontation response. How are they different?', targetConcepts: ['reflection of feeling', 'confrontation', 'skill discrimination'] },
  { id: 'ts6', domain: 'skills', prompt: 'It\'s the second session. The client describes conflict with her boss. You want to point out that she\'s describing a pattern she also has with her mother. Should you use this interpretation now? Why or why not?', targetConcepts: ['interpretation timing', 'alliance prerequisite', 'microskills hierarchy'] },
  { id: 'ts7', domain: 'group', prompt: 'In the sixth session of a process group, two members begin arguing about whose problem is worse. Other members look uncomfortable. What do you do as the leader?', targetConcepts: ['storming stage', 'blocking', 'normalize conflict', 'group safety'] },
  { id: 'ts8', domain: 'group', prompt: 'A new group member asks you: "Will everything I say in here stay confidential?" What is your response?', targetConcepts: ['confidentiality limits', 'group ethics', 'informed consent'] },
  { id: 'ts9', domain: 'priority', prompt: 'A client discussing marital conflict casually mentions: "Sometimes I think everyone would be better off without me." What is your immediate next step?', targetConcepts: ['safety assessment', 'priority ladder rung 1', 'suicidal ideation'] },
  { id: 'ts10', domain: 'priority', prompt: 'A client presents with severe anxiety, insomnia, and racing thoughts. She also mentions she recently started a new thyroid medication. Before diagnosing GAD, what should you consider?', targetConcepts: ['medical rule-out', 'priority ladder rung 2', 'substance/medical causes'] },
  { id: 'ts11', domain: 'alliance', prompt: 'A client who met all treatment goals starts arriving late and canceling sessions 3 weeks before the planned final session. What is happening and how should you respond?', targetConcepts: ['termination regression', 'stages of counseling', 'name the pattern'] },
  { id: 'ts12', domain: 'skills', prompt: 'A client says: "My therapist before you used to give me advice. You just sit there and reflect everything back. When are you going to actually help me?" How do you respond?', targetConcepts: ['immediacy', 'task rupture', 'MI righting reflex'] },
  { id: 'ts13', domain: 'theories', prompt: 'The counselor asks: "On a scale of 1 to 10, how important is it to you to stop drinking? You said 6 — why a 6 and not a 3?" What approach is this?', targetConcepts: ['motivational interviewing', 'readiness ruler', 'change talk'] },
  { id: 'ts14', domain: 'theories', prompt: 'A family therapist asks the parents to re-enact an argument they had last week while the therapist observes. Name the technique and the theoretical school.', targetConcepts: ['enactment', 'structural family therapy', 'Minuchin'] },
  { id: 'ts15', domain: 'priority', prompt: 'A client with depression has been stable for months. She arrives and tells you she just discovered her husband is having an affair. She is sobbing and says: "I want to die." What do you do FIRST, SECOND, and THIRD?', targetConcepts: ['safety first', 'stabilization', 'validation before processing', 'priority ladder sequence'] },
];
