// tools/nce/seed/clinical-focus-3.js
// NCE seed items — Areas of Clinical Focus, blueprint topics 1–14 (batch 2).
// New angles that do not repeat clinical-focus-1.js: specifiers, differentials,
// grief and crisis models, and IPV frameworks.
module.exports = [
  // ── depressive disorders ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-060',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'hard',
    stem: 'A 44-year-old with major depressive disorder has had a depressive episode each of the last three winters, with full remission every spring. A counselor is considering the "with seasonal pattern" specifier. Which finding would argue MOST strongly AGAINST using it?',
    options: [
      { id: 'a', text: 'She sleeps more and craves carbohydrates in her episodes', isCorrect: false, rationale: 'Hypersomnia and carbohydrate craving are common in winter-pattern episodes and are consistent with the specifier.' },
      { id: 'b', text: 'She lives far north, where winter daylight is quite short', isCorrect: false, rationale: 'Higher latitude is associated with winter-pattern depression and does not argue against the specifier.' },
      { id: 'c', text: 'Her construction job lays her off each winter, without pay', isCorrect: true, rationale: 'DSM-5-TR excludes cases in which an obvious seasonal psychosocial stressor, such as regular seasonal unemployment, explains the timing.' },
      { id: 'd', text: 'Each episode has ended completely by the following April', isCorrect: false, rationale: 'Full remission at a characteristic time of year is one of the requirements for the specifier.' },
    ],
    rationale: 'The seasonal pattern specifier requires a regular temporal relationship between episode onset and a particular time of year, full remission (or a switch to mania or hypomania) at a characteristic time, two seasonal episodes in the last 2 years with no nonseasonal episodes in that period, and seasonal episodes substantially outnumbering nonseasonal ones over the lifetime. It does not apply when an obvious season-linked psychosocial stressor, such as being unemployed every winter, accounts for the pattern.',
    references: [{ source: 'DSM-5-TR', detail: 'Specifiers for Depressive Disorders: with seasonal pattern' }],
  },
  {
    id: 'nce-s-clf-061',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'depressive disorders',
    difficulty: 'easy',
    stem: 'A 29-year-old developed a major depressive episode during the second trimester of her first pregnancy. Her midwife assumed the "with peripartum onset" specifier could only be used after delivery. Which statement is accurate under DSM-5-TR?',
    options: [
      { id: 'a', text: 'It applies to onset in pregnancy or within 4 weeks after delivery', isCorrect: true, rationale: 'DSM-5-TR applies the peripartum onset specifier when mood symptoms begin during pregnancy or in the 4 weeks following delivery.' },
      { id: 'b', text: 'It applies only to episodes that begin after the baby is delivered', isCorrect: false, rationale: 'DSM-5 replaced the older "postpartum onset" specifier with "peripartum onset" to include onset during pregnancy.' },
      { id: 'c', text: 'It applies to any onset up to one year following the delivery date', isCorrect: false, rationale: 'One year is used in some research and screening, but the DSM-5-TR specifier window is 4 weeks after delivery.' },
      { id: 'd', text: 'It can be used only when the episode includes psychotic features', isCorrect: false, rationale: 'Psychotic features are not required; peripartum episodes may occur with or without psychosis.' },
    ],
    rationale: 'DSM-5-TR uses "with peripartum onset" when the onset of mood symptoms occurs during pregnancy or in the 4 weeks following delivery. A substantial share of postpartum major depressive episodes actually begin during pregnancy, which is why the earlier postpartum-only specifier was broadened. Peripartum episodes should be distinguished from the brief, milder "baby blues."',
    references: [{ source: 'DSM-5-TR', detail: 'Specifiers for Depressive Disorders: with peripartum onset' }],
  },
  {
    id: 'nce-s-clf-062',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'easy',
    stem: 'A client in a current major depressive episode also says she feels keyed up and tense most days and has a nagging fear that something awful is about to happen. She does not meet criteria for an anxiety disorder. Which specifier BEST captures these features?',
    options: [
      { id: 'a', text: 'With mixed features', isCorrect: false, rationale: '"With mixed features" refers to manic or hypomanic symptoms during a depressive episode, not anxiety.' },
      { id: 'b', text: 'With anxious distress', isCorrect: true, rationale: 'Feeling keyed up or tense and fearing that something awful may happen are two of the five anxious distress symptoms; two are required.' },
      { id: 'c', text: 'With melancholic features', isCorrect: false, rationale: 'Melancholic features center on near-total loss of pleasure, early-morning awakening, and marked psychomotor change.' },
      { id: 'd', text: 'With atypical features', isCorrect: false, rationale: 'Atypical features involve mood reactivity plus symptoms such as hypersomnia, leaden paralysis, and rejection sensitivity.' },
    ],
    rationale: 'The anxious distress specifier requires at least two of five symptoms during most days of the episode: feeling keyed up or tense, feeling unusually restless, difficulty concentrating because of worry, fear that something awful may happen, and feeling one might lose control. Anxious distress is linked to higher suicide risk, longer illness, and poorer treatment response, so it is worth assessing even when no separate anxiety disorder is present.',
    references: [{ source: 'DSM-5-TR', detail: 'Specifiers for Depressive Disorders: with anxious distress' }],
  },

  // ── bipolar disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-063',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'medium',
    stem: 'For about 3 years, a 34-year-old graphic designer has swung between stretches of high energy, talkativeness, and big plans and stretches of low mood and fatigue. Neither the highs nor the lows have ever met full criteria for a hypomanic, manic, or major depressive episode, and she is rarely symptom-free for more than a month. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Bipolar II disorder', isCorrect: false, rationale: 'Bipolar II requires at least one full hypomanic episode and at least one major depressive episode.' },
      { id: 'b', text: 'Persistent depressive disorder', isCorrect: false, rationale: 'Persistent depressive disorder involves chronic depressed mood without the recurring hypomanic symptoms she reports.' },
      { id: 'c', text: 'Bipolar I disorder, mild', isCorrect: false, rationale: 'Bipolar I requires at least one full manic episode, which has never occurred.' },
      { id: 'd', text: 'Cyclothymic disorder', isCorrect: true, rationale: 'Two or more years of numerous subthreshold hypomanic and depressive periods, with no gap over 2 months and no full episodes, fits cyclothymic disorder.' },
    ],
    rationale: 'Cyclothymic disorder requires at least 2 years (1 year in children and adolescents) of numerous periods with hypomanic symptoms and numerous periods with depressive symptoms that never meet full episode criteria. Symptoms are present at least half the time, the person is never symptom-free for more than 2 months, and criteria for a major depressive, manic, or hypomanic episode have never been met.',
    references: [{ source: 'DSM-5-TR', detail: 'Cyclothymic Disorder, Criteria A–C' }],
  },
  {
    id: 'nce-s-clf-064',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'hard',
    stem: 'Three weeks after starting an antidepressant for depression, a 38-year-old develops elevated mood, grandiosity, little need for sleep, and reckless spending. His prescriber stops the medication, but the full manic syndrome continues well beyond the drug\'s expected physiological effect. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'Mania that starts on an antidepressant is coded only as medication-induced', isCorrect: false, rationale: 'Onset during antidepressant treatment does not by itself settle the question; persistence beyond the drug effect matters.' },
      { id: 'b', text: 'Persisting at full level past the drug effect supports bipolar I disorder', isCorrect: true, rationale: 'DSM-5-TR states that a full manic episode persisting beyond the physiological effect of antidepressant treatment is sufficient evidence for bipolar I.' },
      { id: 'c', text: 'Bipolar II should be diagnosed because a medication triggered the mood', isCorrect: false, rationale: 'Bipolar II requires hypomanic, not manic, episodes; the trigger does not change a full manic syndrome into hypomania.' },
      { id: 'd', text: 'No bipolar diagnosis can be made until a medication-free year has passed', isCorrect: false, rationale: 'DSM-5-TR sets no medication-free waiting period; the criterion is persistence beyond the physiological effect.' },
    ],
    rationale: 'DSM-5-TR notes that a full manic episode emerging during antidepressant treatment (medication or electroconvulsive therapy) that persists at a fully syndromal level beyond the physiological effect of that treatment is sufficient evidence for a manic episode and therefore a bipolar I diagnosis. If the symptoms resolve as the drug effect wears off, a substance/medication-induced bipolar and related disorder is more appropriate.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar I Disorder, Manic Episode Criterion D note on antidepressant treatment' }],
  },

  // ── anxiety disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-065',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'For 8 months, a 47-year-old has avoided buses, crowded grocery stores, and long checkout lines. She fears that if she suddenly felt faint or lost bladder control, escape would be hard and no one would help. She has never had an unexpected panic attack and is not worried about being judged by others. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Specific phobia, situational type', isCorrect: false, rationale: 'Specific phobia centers on one circumscribed situation; fear across several situations for this escape-related reason points to agoraphobia.' },
      { id: 'b', text: 'Social anxiety disorder', isCorrect: false, rationale: 'Social anxiety centers on fear of scrutiny or negative evaluation, which she denies.' },
      { id: 'c', text: 'Agoraphobia', isCorrect: true, rationale: 'Fear in two or more agoraphobic situations because escape may be difficult or help unavailable if incapacitating symptoms occur fits agoraphobia.' },
      { id: 'd', text: 'Panic disorder', isCorrect: false, rationale: 'Panic disorder requires recurrent unexpected panic attacks, which she has never had.' },
    ],
    rationale: 'Agoraphobia requires marked fear or anxiety about at least two of five situations: public transportation, open spaces, enclosed spaces, standing in line or being in a crowd, and being outside the home alone. The fear is driven by thoughts that escape might be difficult or help unavailable if panic-like or other incapacitating or embarrassing symptoms occur. Since DSM-5, agoraphobia can be diagnosed without panic disorder, and it typically lasts 6 months or more.',
    references: [{ source: 'DSM-5-TR', detail: 'Agoraphobia, Criteria A–B' }],
  },
  {
    id: 'nce-s-clf-066',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'A 6-year-old has not spoken at school for 4 months, although she talks freely with her parents at home. Her teacher refers her for evaluation of selective mutism. Which additional finding would make selective mutism LESS likely as the explanation?',
    options: [
      { id: 'a', text: 'Her family moved recently and she is still learning the school language', isCorrect: true, rationale: 'DSM-5-TR excludes failure to speak that is due to lack of knowledge of, or comfort with, the language required in that setting.' },
      { id: 'b', text: 'She whispers to one close friend at recess but to no one else there', isCorrect: false, rationale: 'Limited speech with one trusted peer is common in selective mutism and does not argue against it.' },
      { id: 'c', text: 'Her silence has lasted well beyond the first month of the school year', isCorrect: false, rationale: 'Duration of at least 1 month, not limited to the first month of school, is a requirement and supports the diagnosis.' },
      { id: 'd', text: 'Her parents describe her as very shy and anxious in new situations', isCorrect: false, rationale: 'Shyness and social anxiety are commonly associated with selective mutism.' },
    ],
    rationale: 'Selective mutism is a consistent failure to speak in specific social situations where speech is expected, such as school, despite speaking in other situations. It must last at least 1 month (not limited to the first month of school), interfere with achievement or communication, and not be due to lack of knowledge of or comfort with the spoken language. Counselors working with newly arrived immigrant children should consider normal second-language "silent periods" before diagnosing.',
    references: [{ source: 'DSM-5-TR', detail: 'Selective Mutism, Criteria A–D' }],
  },

  // ── trauma- and stressor-related disorders ──────────────────────────────
  {
    id: 'nce-s-clf-067',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'Five weeks after being unexpectedly laid off from a job of 20 years, a 56-year-old reports sadness, frequent replaying of the termination meeting, poor sleep, and withdrawal from friends. His distress is out of proportion to what is typical and is affecting family life. Criteria for a major depressive episode are not met. Which diagnosis is MOST appropriate?',
    options: [
      { id: 'a', text: 'Posttraumatic stress disorder', isCorrect: false, rationale: 'PTSD requires exposure to actual or threatened death, serious injury, or sexual violence; a layoff does not meet Criterion A.' },
      { id: 'b', text: 'Acute stress disorder', isCorrect: false, rationale: 'Acute stress disorder has the same Criterion A trauma requirement as PTSD, which a layoff does not satisfy.' },
      { id: 'c', text: 'Major depressive disorder', isCorrect: false, rationale: 'The stem states that criteria for a major depressive episode are not met.' },
      { id: 'd', text: 'Adjustment disorder', isCorrect: true, rationale: 'Distressing symptoms beginning within 3 months of an identifiable, non-traumatic stressor, out of proportion and impairing, fit adjustment disorder.' },
    ],
    rationale: 'Adjustment disorder involves emotional or behavioral symptoms that begin within 3 months of an identifiable stressor, are out of proportion to the stressor or impair functioning, and do not meet criteria for another mental disorder. Unlike PTSD and acute stress disorder, the stressor need not involve death, serious injury, or sexual violence. Symptoms should resolve within 6 months after the stressor or its consequences end.',
    references: [{ source: 'DSM-5-TR', detail: 'Adjustment Disorders, Criteria A–E' }],
  },
  {
    id: 'nce-s-clf-068',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'A 4-year-old was adopted at age 2 after living in an understaffed orphanage. Her adoptive parents say she happily wanders off with strangers at the park, climbs onto unfamiliar adults\' laps, and does not look back to check on them. Which diagnosis BEST fits this pattern?',
    options: [
      { id: 'a', text: 'Reactive attachment disorder, persistent', isCorrect: false, rationale: 'Reactive attachment disorder involves an inhibited, emotionally withdrawn child who rarely seeks or responds to comfort.' },
      { id: 'b', text: 'Disinhibited social engagement disorder', isCorrect: true, rationale: 'Overly familiar behavior with strangers, wandering off without checking back, and a history of insufficient care define this disorder.' },
      { id: 'c', text: 'Attention-deficit/hyperactivity disorder', isCorrect: false, rationale: 'ADHD impulsivity is not specific to indiscriminate social approach and is not tied to a history of social neglect.' },
      { id: 'd', text: 'Autism spectrum disorder, level 1', isCorrect: false, rationale: 'Autism involves deficits in social communication and restricted interests, not eager, indiscriminate approach to strangers.' },
    ],
    rationale: 'Both reactive attachment disorder and disinhibited social engagement disorder follow a pattern of extremely insufficient care, such as neglect or institutional rearing. Reactive attachment disorder is an inhibited, withdrawn pattern with minimal comfort seeking, while disinhibited social engagement disorder is a pattern of culturally inappropriate, overly familiar behavior with unfamiliar adults and diminished checking back with caregivers. The child must have a developmental age of at least 9 months.',
    references: [{ source: 'DSM-5-TR', detail: 'Disinhibited Social Engagement Disorder, Criteria A–C' }],
  },

  // ── obsessive-compulsive and related disorders ──────────────────────────
  {
    id: 'nce-s-clf-069',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'medium',
    stem: 'A 22-year-old man who lifts weights daily is convinced his body looks small and weak, although friends describe him as very muscular. He checks mirrors for hours, wears baggy layers to hide his build, and skips social events. He is not focused on body fat or thinness. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Anorexia nervosa, restricting type', isCorrect: false, rationale: 'Anorexia nervosa involves significantly low body weight and fear of weight gain, not a belief of being too small.' },
      { id: 'b', text: 'Obsessive-compulsive disorder', isCorrect: false, rationale: 'When obsessions and rituals center only on perceived appearance flaws, body dysmorphic disorder is the more specific diagnosis.' },
      { id: 'c', text: 'Body dysmorphic disorder', isCorrect: true, rationale: 'Preoccupation with a perceived appearance flaw plus repetitive checking fits BDD; the belief that his build is too small calls for the muscle dysmorphia specifier.' },
      { id: 'd', text: 'Illness anxiety disorder', isCorrect: false, rationale: 'Illness anxiety disorder centers on fear of having a serious illness, not on perceived appearance flaws.' },
    ],
    rationale: 'Body dysmorphic disorder is preoccupation with perceived defects in appearance that are not observable or appear slight to others, along with repetitive behaviors such as mirror checking or comparing, causing distress or impairment. The "with muscle dysmorphia" specifier applies when the person believes his or her build is too small or insufficiently muscular. DSM-5-TR also specifies the degree of insight.',
    references: [{ source: 'DSM-5-TR', detail: 'Body Dysmorphic Disorder, Criteria A–D and muscle dysmorphia specifier' }],
  },
  {
    id: 'nce-s-clf-070',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'easy',
    stem: 'A 66-year-old describes himself as "a collector." Which finding MOST clearly points to hoarding disorder rather than ordinary collecting?',
    options: [
      { id: 'a', text: 'Clutter fills living areas, and parting with items causes distress', isCorrect: true, rationale: 'Persistent difficulty discarding, distress at parting with items, and clutter that blocks the use of living spaces are the core of hoarding disorder.' },
      { id: 'b', text: 'He owns several hundred items of one specific type in his home', isCorrect: false, rationale: 'A large number of items is common in collecting; what matters is whether clutter compromises living areas.' },
      { id: 'c', text: 'He spends a good share of his spare money on additions each year', isCorrect: false, rationale: 'Spending on a hobby is not diagnostic; collectors often budget substantial amounts.' },
      { id: 'd', text: 'He feels warm sentimental attachment to items that were gifts', isCorrect: false, rationale: 'Sentimental attachment to meaningful objects is normal and not in itself a sign of hoarding disorder.' },
    ],
    rationale: 'Hoarding disorder is persistent difficulty discarding or parting with possessions, regardless of their actual value, due to a perceived need to save them and distress associated with discarding. The result is an accumulation that congests and clutters active living areas and substantially compromises their intended use. Collecting, by contrast, tends to be organized and intentional and does not block the use of living space. A specifier notes whether excessive acquisition is present.',
    references: [{ source: 'DSM-5-TR', detail: 'Hoarding Disorder, Criteria A–C' }],
  },

  // ── substance use and addictive disorders ───────────────────────────────
  {
    id: 'nce-s-clf-071',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'substance use and addictive disorders',
    difficulty: 'medium',
    stem: 'Two days after stopping several weeks of heavy methamphetamine use, a client reports feeling deeply down and exhausted. He is sleeping for long stretches, has vivid unpleasant dreams, and is eating much more than usual. Which withdrawal syndrome do these symptoms MOST closely match?',
    options: [
      { id: 'a', text: 'Opioid withdrawal', isCorrect: false, rationale: 'Opioid withdrawal features flu-like signs such as tearing, runny nose, yawning, dilated pupils, muscle aches, and diarrhea.' },
      { id: 'b', text: 'Cannabis withdrawal', isCorrect: false, rationale: 'Cannabis withdrawal typically brings irritability, anxiety, restlessness, trouble sleeping, and decreased appetite.' },
      { id: 'c', text: 'Alcohol withdrawal', isCorrect: false, rationale: 'Alcohol withdrawal involves autonomic hyperactivity, tremor, insomnia, and possible seizures, not hypersomnia with increased appetite.' },
      { id: 'd', text: 'Stimulant withdrawal', isCorrect: true, rationale: 'Dysphoric mood with fatigue, vivid unpleasant dreams, sleep change, and increased appetite matches stimulant withdrawal.' },
    ],
    rationale: 'Stimulant withdrawal requires dysphoric mood plus at least two of: fatigue; vivid, unpleasant dreams; insomnia or hypersomnia; increased appetite; and psychomotor retardation or agitation, developing within hours to days after stopping. The "crash" can bring marked depression, so counselors should screen for suicidal thinking during early stimulant withdrawal.',
    references: [{ source: 'DSM-5-TR', detail: 'Stimulant Withdrawal, Criteria A–B' }],
  },
  {
    id: 'nce-s-clf-072',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'substance use and addictive disorders',
    difficulty: 'easy',
    stem: 'After losing a large sum at an online casino, a client logs back in the next morning, certain that a few more bets will win back what he lost. Which DSM-5-TR gambling disorder criterion does this behavior illustrate?',
    options: [
      { id: 'a', text: 'Tolerance', isCorrect: false, rationale: 'Tolerance in gambling disorder is needing to gamble with increasing amounts of money to achieve the desired excitement.' },
      { id: 'b', text: 'Chasing losses', isCorrect: true, rationale: 'Returning another day to get even after losing money is the "chasing" criterion of gambling disorder.' },
      { id: 'c', text: 'Relying on bailouts', isCorrect: false, rationale: 'This criterion refers to relying on others for money to relieve a desperate financial situation caused by gambling.' },
      { id: 'd', text: 'Withdrawal', isCorrect: false, rationale: 'Withdrawal refers to restlessness or irritability when attempting to cut down or stop gambling.' },
    ],
    rationale: 'Gambling disorder is the only behavioral (non-substance) addiction in the DSM-5-TR substance-related and addictive disorders chapter. It requires at least four of nine criteria within 12 months, including chasing losses, needing larger amounts to get the desired excitement, restlessness when cutting down, lying to conceal gambling, and relying on others for bailouts. Chasing is considered one of the hallmark features of problem gambling.',
    references: [{ source: 'DSM-5-TR', detail: 'Gambling Disorder, Criterion A6 (chasing losses)' }],
  },
  {
    id: 'nce-s-clf-073',
    reviewNote: 'Confirm that SAMHSA TIP 63 is the best approved citation for naloxone distribution as a harm reduction practice.',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'substance use and addictive disorders',
    difficulty: 'medium',
    stem: 'A 30-year-old with opioid use disorder says he is not ready to stop using but wants to keep seeing the counselor. Which counselor action BEST reflects a harm reduction approach?',
    options: [
      { id: 'a', text: 'Require a period of abstinence before further sessions are offered', isCorrect: false, rationale: 'Making abstinence a condition of care pushes away clients who are not ready and conflicts with harm reduction.' },
      { id: 'b', text: 'Confront his denial each session until he admits he needs to quit', isCorrect: false, rationale: 'Confrontational approaches tend to raise resistance and are not part of harm reduction or motivational work.' },
      { id: 'c', text: 'Help him get naloxone and plan not to use alone, while exploring change', isCorrect: true, rationale: 'Reducing overdose risk now, while keeping him engaged and exploring change, is the essence of harm reduction.' },
      { id: 'd', text: 'Refer him to a mutual-help group and end individual counseling for now', isCorrect: false, rationale: 'Mutual-help groups can help, but ending counseling removes support when he is open to engagement.' },
    ],
    rationale: 'Harm reduction meets clients where they are, aiming to reduce the health and social harms of substance use without requiring abstinence first. For opioid use, this includes naloxone access, not using alone, and sterile supplies, alongside offering medications for opioid use disorder. Staying engaged also leaves room for motivational work that may later lead to reduced use or recovery.',
    references: [{ source: 'SAMHSA TIP 63', detail: 'Medications for Opioid Use Disorder: overdose prevention and naloxone' }],
  },

  // ── neurodevelopmental disorders ────────────────────────────────────────
  {
    id: 'nce-s-clf-074',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurodevelopmental disorders',
    difficulty: 'easy',
    stem: 'Under DSM-5-TR, the severity level of intellectual developmental disorder (mild, moderate, severe, profound) is determined mainly by which factor?',
    options: [
      { id: 'a', text: 'Adaptive functioning in conceptual, social and practical areas', isCorrect: true, rationale: 'DSM-5-TR defines severity by adaptive functioning, because that determines the level of support needed.' },
      { id: 'b', text: 'The full-scale IQ score range obtained on standardized testing', isCorrect: false, rationale: 'IQ is part of assessing intellectual deficits, but DSM-5 moved severity away from IQ ranges.' },
      { id: 'c', text: 'The age at which the intellectual deficits were first observed', isCorrect: false, rationale: 'Onset during the developmental period is required, but age of onset does not set severity.' },
      { id: 'd', text: 'Whether a specific genetic or medical cause has been identified', isCorrect: false, rationale: 'Etiology may be noted, but it does not determine the severity level.' },
    ],
    rationale: 'Intellectual developmental disorder requires deficits in intellectual functions and in adaptive functioning, with onset during the developmental period. DSM-5-TR bases the severity specifiers on adaptive functioning across conceptual, social, and practical domains rather than IQ scores, because adaptive functioning determines the level of supports required. IQ scores remain part of the assessment but are less valid at the lower end of the range.',
    references: [{ source: 'DSM-5-TR', detail: 'Intellectual Developmental Disorder, severity specifiers' }],
  },
  {
    id: 'nce-s-clf-075',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'An 11-year-old has had eye blinking and shoulder shrugging since age 9, and over the past year he has also developed frequent throat clearing and sniffing. The tics wax and wane but have never stopped for long. He has never used obscene words. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Persistent (chronic) motor tic disorder', isCorrect: false, rationale: 'Persistent tic disorder involves motor or vocal tics, but not both; he has both.' },
      { id: 'b', text: 'Provisional tic disorder', isCorrect: false, rationale: 'Provisional tic disorder applies when tics have been present for less than 1 year.' },
      { id: 'c', text: 'Stereotypic movement disorder', isCorrect: false, rationale: 'Stereotypies are rhythmic, seemingly purposeless movements that begin earlier and lack the vocal tics described.' },
      { id: 'd', text: 'Tourette\'s disorder', isCorrect: true, rationale: 'Multiple motor tics and at least one vocal tic, present for more than 1 year with onset before 18, meet criteria for Tourette\'s disorder.' },
    ],
    rationale: 'Tourette\'s disorder requires both multiple motor tics and one or more vocal tics at some time during the illness, although not necessarily at the same time. Tics may wax and wane but must have persisted for more than 1 year since the first tic, with onset before age 18. Coprolalia (uttering obscenities) occurs in only a minority of cases and is not required.',
    references: [{ source: 'DSM-5-TR', detail: 'Tourette\'s Disorder, Criteria A–D' }],
  },

  // ── schizophrenia spectrum disorders ────────────────────────────────────
  {
    id: 'nce-s-clf-076',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'hard',
    stem: 'For 8 months, a 58-year-old accountant has been certain that a neighbor is poisoning his garden and reading his mail. He has filed police reports and installed cameras. He reports no hallucinations, his speech is organized, and he continues to work effectively. No mood episodes or substance causes are present. Which diagnosis is MOST appropriate?',
    options: [
      { id: 'a', text: 'Schizophrenia', isCorrect: false, rationale: 'Schizophrenia requires two or more Criterion A symptoms and usually marked functional decline; he has a single fixed delusion and functions well.' },
      { id: 'b', text: 'Delusional disorder', isCorrect: true, rationale: 'One or more delusions lasting 1 month or longer, without other Criterion A symptoms and with functioning not markedly impaired, fits delusional disorder (persecutory type).' },
      { id: 'c', text: 'Paranoid personality disorder', isCorrect: false, rationale: 'Paranoid personality disorder involves pervasive distrust and suspiciousness, not a fixed false belief held with delusional conviction.' },
      { id: 'd', text: 'Brief psychotic disorder', isCorrect: false, rationale: 'Brief psychotic disorder lasts at least 1 day but less than 1 month, and he has had symptoms for 8 months.' },
    ],
    rationale: 'Delusional disorder requires one or more delusions lasting at least 1 month, Criterion A for schizophrenia never having been met, and functioning that is not markedly impaired apart from the impact of the delusion. Behavior is not obviously bizarre. Subtypes include persecutory, jealous, erotomanic, grandiose, and somatic, and DSM-5-TR adds a "with bizarre content" specifier.',
    references: [{ source: 'DSM-5-TR', detail: 'Delusional Disorder, Criteria A–E and persecutory type' }],
  },
  {
    id: 'nce-s-clf-077',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'hard',
    stem: 'Over 2 years of illness, a 33-year-old has had major depressive episodes for most of the time, often with voices and persecutory beliefs. Between episodes there was a 3-week stretch when the voices and delusions continued while her mood was stable. She has never had mania, and substances are ruled out. Which diagnosis is MOST appropriate?',
    options: [
      { id: 'a', text: 'Major depressive disorder with psychotic features', isCorrect: false, rationale: 'In MDD with psychotic features, psychosis occurs only during mood episodes; here it persisted for weeks without one.' },
      { id: 'b', text: 'Schizophrenia with comorbid depressive episodes', isCorrect: false, rationale: 'Schizophrenia fits when mood episodes are present for only a minority of the illness; hers spanned most of it.' },
      { id: 'c', text: 'Schizoaffective disorder, depressive type', isCorrect: true, rationale: 'Psychosis for 2 or more weeks without a mood episode, with mood episodes present for most of the illness, fits schizoaffective disorder.' },
      { id: 'd', text: 'Bipolar I disorder with psychotic features', isCorrect: false, rationale: 'Bipolar I requires a manic episode, which has never occurred.' },
    ],
    rationale: 'Schizoaffective disorder requires an uninterrupted period of illness in which a major mood episode co-occurs with Criterion A of schizophrenia, plus delusions or hallucinations for 2 or more weeks in the absence of a major mood episode at some point in the lifetime illness. Mood episodes must be present for the majority of the total duration of the active and residual illness. The depressive type applies when only major depressive episodes have occurred.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizoaffective Disorder, Criteria A–C' }],
  },

  // ── personality disorders ───────────────────────────────────────────────
  {
    id: 'nce-s-clf-078',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'hard',
    stem: 'A 26-year-old seeks counseling for "bipolar mood swings." She describes intense anger, chronic emptiness, and fear of being left by her partner. A counselor is weighing borderline personality disorder against a bipolar disorder. Which finding MOST supports borderline personality disorder?',
    options: [
      { id: 'a', text: 'Impulsive spending sprees during periods of high distress', isCorrect: false, rationale: 'Impulsive spending occurs in both borderline personality disorder and manic or hypomanic episodes, so it does not discriminate.' },
      { id: 'b', text: 'Mood shifts lasting hours, set off by perceived rejection', isCorrect: true, rationale: 'Reactive mood shifts lasting hours and triggered by interpersonal events are typical of BPD, whereas bipolar episodes last days or longer.' },
      { id: 'c', text: 'Several past periods of low mood with fatigue and poor focus', isCorrect: false, rationale: 'Depressive periods occur in both conditions and do not distinguish them.' },
      { id: 'd', text: 'A biological parent with a documented bipolar I diagnosis', isCorrect: false, rationale: 'A family history of bipolar disorder raises the likelihood of a bipolar diagnosis rather than supporting BPD.' },
    ],
    rationale: 'Affective instability in borderline personality disorder involves marked reactivity of mood, with episodes usually lasting a few hours and rarely more than a few days, often triggered by interpersonal stress or perceived abandonment. Bipolar mood episodes are sustained, distinct periods (at least 4 days for hypomania, 1 week for mania) with changes such as decreased need for sleep that are not simply reactions to relationships. The two can co-occur, so careful history taking matters.',
    references: [{ source: 'DSM-5-TR', detail: 'Borderline Personality Disorder, Differential Diagnosis (bipolar disorders)' }],
  },
  {
    id: 'nce-s-clf-079',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'easy',
    stem: 'A 35-year-old has few close friends, dresses in an unusual way, and speaks in vague, odd phrases. She believes she can sense what strangers are thinking and that song lyrics on the radio carry special messages for her. Her social anxiety does not ease as she gets to know people. Which personality disorder BEST fits?',
    options: [
      { id: 'a', text: 'Schizoid personality disorder', isCorrect: false, rationale: 'Schizoid personality disorder involves detachment and restricted emotion without the odd beliefs and perceptual distortions described.' },
      { id: 'b', text: 'Avoidant personality disorder', isCorrect: false, rationale: 'Avoidant personality disorder (Cluster C) involves fear of rejection without magical thinking or ideas of reference.' },
      { id: 'c', text: 'Paranoid personality disorder', isCorrect: false, rationale: 'Paranoid personality disorder centers on distrust and suspicion of others\' motives rather than eccentric beliefs and speech.' },
      { id: 'd', text: 'Schizotypal personality disorder', isCorrect: true, rationale: 'Ideas of reference, magical thinking, odd speech and appearance, and persistent social anxiety define schizotypal personality disorder.' },
    ],
    rationale: 'Schizotypal personality disorder, in Cluster A, combines acute discomfort with close relationships and cognitive or perceptual distortions and eccentric behavior. Features include ideas of reference, odd beliefs or magical thinking, unusual perceptual experiences, odd speech, eccentric appearance, and excessive social anxiety that does not diminish with familiarity. Schizoid personality disorder shares the social detachment but lacks the cognitive and perceptual oddities.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizotypal Personality Disorder, Criterion A' }],
  },

  // ── eating disorders ────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-080',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'A 19-year-old reports recurrent binge-eating episodes followed by purging, along with an intense fear of gaining weight. Her physician notes that her body weight is significantly low for her age, sex, and developmental trajectory. Which diagnosis is MOST appropriate?',
    options: [
      { id: 'a', text: 'Anorexia nervosa', isCorrect: true, rationale: 'Significantly low body weight with fear of weight gain and recurrent binge-purge behavior fits anorexia nervosa, binge-eating/purging type.' },
      { id: 'b', text: 'Bulimia nervosa', isCorrect: false, rationale: 'Bulimia nervosa cannot be diagnosed when the disturbance occurs exclusively during episodes of anorexia nervosa.' },
      { id: 'c', text: 'Binge-eating disorder', isCorrect: false, rationale: 'Binge-eating disorder excludes regular compensatory behaviors such as purging.' },
      { id: 'd', text: 'Purging disorder', isCorrect: false, rationale: 'Purging disorder (an other specified presentation) involves purging without binge eating, and she does binge; she also meets full criteria for anorexia nervosa.' },
    ],
    rationale: 'The key feature separating anorexia nervosa from bulimia nervosa is significantly low body weight. Binge eating and purging can occur in both, but when they happen in a person with significantly low weight and fear of weight gain, the diagnosis is anorexia nervosa, binge-eating/purging type. Bulimia nervosa Criterion E states the disturbance does not occur exclusively during episodes of anorexia nervosa.',
    references: [{ source: 'DSM-5-TR', detail: 'Anorexia Nervosa subtypes; Bulimia Nervosa, Criterion E' }],
  },
  {
    id: 'nce-s-clf-081',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'A client in outpatient counseling for bulimia nervosa says her purging has increased over the past month. Today she mentions feeling dizzy and noticing her heart "fluttering" at times. What should the counselor do?',
    options: [
      { id: 'a', text: 'Teach slow breathing, since palpitations often reflect anxiety', isCorrect: false, rationale: 'Attributing cardiac symptoms to anxiety before medical evaluation risks missing a dangerous physical complication.' },
      { id: 'b', text: 'Keep the session focused on the binge triggers and revisit later', isCorrect: false, rationale: 'Delaying attention to new physical warning signs is unsafe in an eating disorder with frequent purging.' },
      { id: 'c', text: 'Arrange prompt medical evaluation of her physical warning signs', isCorrect: true, rationale: 'Frequent purging can cause electrolyte disturbances that affect heart rhythm, so dizziness and palpitations warrant prompt medical assessment.' },
      { id: 'd', text: 'Suggest she adjust her own fluid intake and recheck how she feels', isCorrect: false, rationale: 'Self-management advice is outside the counselor\'s scope and does not address possible electrolyte or cardiac problems.' },
    ],
    rationale: 'Bulimia nervosa carries significant medical risk; repeated purging can lead to fluid and electrolyte disturbances that may cause dangerous heart rhythm problems. Counselors should coordinate with medical providers and refer for prompt evaluation when clients report physical warning signs such as dizziness, fainting, or palpitations. Eating disorder care is best delivered by a team that includes medical monitoring.',
    references: [{ source: 'NICE guidelines', detail: 'NG69 Eating disorders: physical health assessment and monitoring' }],
  },

  // ── neurocognitive disorders ────────────────────────────────────────────
  {
    id: 'nce-s-clf-082',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'medium',
    stem: 'A 72-year-old has had a gradual decline in thinking over the past year. His wife reports that he is clear one day and very confused the next, often sees detailed images of children in the house who are not there, and shouts and kicks while dreaming. Mild stiffness and a shuffling gait appeared months after the cognitive changes. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Major NCD due to Alzheimer\'s disease', isCorrect: false, rationale: 'Alzheimer\'s disease usually begins with memory and learning decline; fluctuations, early visual hallucinations, and REM sleep behavior are not core features.' },
      { id: 'b', text: 'Major frontotemporal NCD', isCorrect: false, rationale: 'Frontotemporal disorder presents with early behavioral disinhibition, apathy, or language decline rather than these features.' },
      { id: 'c', text: 'Major vascular NCD', isCorrect: false, rationale: 'Vascular disorder is tied to cerebrovascular events and often shows stepwise decline in attention and executive function.' },
      { id: 'd', text: 'Major NCD with Lewy bodies', isCorrect: true, rationale: 'Fluctuating cognition, recurrent detailed visual hallucinations, and later parkinsonism are core Lewy body features; REM sleep behavior disorder is a suggestive feature.' },
    ],
    rationale: 'In DSM-5-TR, the core features of neurocognitive disorder with Lewy bodies are fluctuating cognition with marked variations in attention and alertness, recurrent well-formed and detailed visual hallucinations, and spontaneous parkinsonism beginning after cognitive decline. Suggestive features include REM sleep behavior disorder and severe sensitivity to antipsychotic (neuroleptic) medications, which is why accurate identification matters for care coordination.',
    references: [{ source: 'DSM-5-TR', detail: 'Major or Mild Neurocognitive Disorder With Lewy Bodies, Criteria C–D' }],
  },
  {
    id: 'nce-s-clf-083',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'easy',
    stem: 'Which presentation MOST suggests vascular neurocognitive disorder rather than neurocognitive disorder due to Alzheimer\'s disease?',
    options: [
      { id: 'a', text: 'Stepwise drops in attention and planning after small strokes', isCorrect: true, rationale: 'Onset tied to cerebrovascular events and prominent decline in complex attention and executive function point to vascular NCD.' },
      { id: 'b', text: 'Slow, steady loss of recent memory that began without warning', isCorrect: false, rationale: 'Insidious onset with gradual, early memory and learning decline is typical of Alzheimer\'s disease.' },
      { id: 'c', text: 'Early disinhibition and loss of empathy with intact memory', isCorrect: false, rationale: 'Early behavioral disinhibition and loss of empathy suggest the behavioral variant of frontotemporal NCD.' },
      { id: 'd', text: 'Recurrent visual hallucinations with alertness that fluctuates', isCorrect: false, rationale: 'Recurrent visual hallucinations with fluctuating alertness are core features of NCD with Lewy bodies.' },
    ],
    rationale: 'Vascular neurocognitive disorder is suggested when onset is temporally related to one or more cerebrovascular events, or when decline is prominent in complex attention (including processing speed) and frontal-executive function. Its course is often stepwise. Alzheimer\'s disease, by contrast, has an insidious onset and gradual progression, with memory and learning typically affected early.',
    references: [{ source: 'DSM-5-TR', detail: 'Major or Mild Vascular Neurocognitive Disorder, Criterion B' }],
  },

  // ── grief and loss ──────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-084',
    reviewNote: 'Verify that the cited Berk chapter covers Worden\'s four tasks; Worden\'s own text is not on the approved source list.',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'grief and loss',
    difficulty: 'medium',
    stem: 'Fourteen months after her husband died, a 67-year-old client accepts the death and has let herself feel its pain. Now she is struggling to manage the finances he always handled, to drive on the highway alone, and to think of herself as "single." Which of Worden\'s tasks of mourning is she MOST working on?',
    options: [
      { id: 'a', text: 'Accepting the reality of the loss', isCorrect: false, rationale: 'The stem states she already accepts that the death has happened.' },
      { id: 'b', text: 'Processing the pain of the grief', isCorrect: false, rationale: 'She has allowed herself to feel the pain; her current struggle is with new roles and identity.' },
      { id: 'c', text: 'Adjusting to a world without him', isCorrect: true, rationale: 'Taking on roles the deceased filled and redefining her sense of self are the external and internal adjustments of this task.' },
      { id: 'd', text: 'Finding an enduring connection', isCorrect: false, rationale: 'This task involves keeping a bond with the deceased while moving forward, not mastering new skills and roles.' },
    ],
    rationale: 'Worden described four tasks of mourning: accepting the reality of the loss, processing the pain of grief, adjusting to a world without the deceased, and finding an enduring connection with the deceased while embarking on a new life. Adjustment includes external changes (new roles and skills), internal changes (sense of self), and spiritual changes (beliefs about the world). Unlike stage models, tasks are active and can be revisited.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Ch. 19: Bereavement, the experience of grieving' }],
  },
  {
    id: 'nce-s-clf-085',
    reviewNote: 'Berk is cited as "Ch. 19"; confirm the chapter number for the edition in use.',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'grief and loss',
    difficulty: 'hard',
    stem: 'Six months after his teenage son died, a father has some days filled with looking at photos and crying, and other days focused on returning to work and learning to cook for his family. He worries that this "back and forth" means he is grieving the wrong way. Which framework BEST normalizes his experience?',
    options: [
      { id: 'a', text: 'Kübler-Ross\'s stages of dying, read as a fixed sequence', isCorrect: false, rationale: 'Kübler-Ross described reactions of dying patients; read as a fixed sequence, it would frame his back-and-forth as a problem.' },
      { id: 'b', text: 'Stroebe and Schut\'s dual process model of coping with loss', isCorrect: true, rationale: 'The dual process model describes healthy oscillation between loss-oriented and restoration-oriented coping.' },
      { id: 'c', text: 'Bowlby\'s phases of mourning, ending in reorganization', isCorrect: false, rationale: 'Bowlby\'s phases describe a general progression and do not center on alternating between two kinds of coping.' },
      { id: 'd', text: 'Caplan\'s crisis theory, with its time-limited disequilibrium', isCorrect: false, rationale: 'Crisis theory addresses short-term disequilibrium after an event, not the ongoing rhythm of bereavement coping.' },
    ],
    rationale: 'Stroebe and Schut\'s dual process model proposes that bereaved people oscillate between loss-oriented coping (grief work, yearning, reviewing the relationship) and restoration-oriented coping (attending to life changes, new roles, distraction). Moving back and forth, including taking breaks from grief, is considered adaptive. Kübler-Ross\'s stages (denial, anger, bargaining, depression, acceptance) came from work with dying patients and are not a required sequence for the bereaved.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Ch. 19: Bereavement, the dual-process model of coping with loss' }],
  },

  // ── crisis and disaster response ────────────────────────────────────────
  {
    id: 'nce-s-clf-086',
    reviewNote: 'Confirm Gladding\'s crisis counseling coverage of Caplan; no crisis-theory text (e.g., James & Gilliland) is on the approved list.',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'crisis and disaster response',
    difficulty: 'easy',
    stem: 'According to Caplan\'s crisis theory, which statement BEST describes a crisis?',
    options: [
      { id: 'a', text: 'A time-limited upset when usual coping fails, which may lead to growth', isCorrect: true, rationale: 'Caplan described crisis as a temporary disequilibrium when customary problem solving fails, with potential for growth or deterioration.' },
      { id: 'b', text: 'A lasting pattern of poor coping rooted in long-standing personality traits', isCorrect: false, rationale: 'Crisis is an acute, time-limited state, not an enduring personality pattern.' },
      { id: 'c', text: 'A mental disorder that calls for formal diagnosis and long-term therapy', isCorrect: false, rationale: 'A crisis is a normal human reaction, not a mental disorder, and calls for brief, focused intervention.' },
      { id: 'd', text: 'A reaction set by how severe the event is, apart from how it is perceived', isCorrect: false, rationale: 'Crisis theory stresses the person\'s perception of the event and coping resources, not the event alone.' },
    ],
    rationale: 'Gerald Caplan described a crisis as a state of psychological disequilibrium that occurs when a person faces an obstacle to important life goals that cannot be overcome with customary problem-solving methods. Crises are time-limited, typically resolving within weeks, and the outcome can be either growth and improved coping or deterioration. This is why early, brief intervention is emphasized.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis counseling: the nature of crises' }],
  },
  {
    id: 'nce-s-clf-087',
    reviewNote: 'Phase names follow the SAMHSA/Zunin and Myers disaster model; confirm the Gladding citation or substitute a SAMHSA disaster source if one is added.',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'crisis and disaster response',
    difficulty: 'medium',
    stem: 'Four months after a flood, the volunteers and news crews have left a small town. Residents who once worked side by side now voice anger at slow insurance payouts and agency red tape, and many feel forgotten. In the commonly used phases of community response to disaster, which phase is the town MOST likely in?',
    options: [
      { id: 'a', text: 'Heroic phase', isCorrect: false, rationale: 'The heroic phase occurs during and right after impact, when people act to save lives and property.' },
      { id: 'b', text: 'Honeymoon phase', isCorrect: false, rationale: 'The honeymoon phase brings community bonding and optimism as aid arrives, which has faded here.' },
      { id: 'c', text: 'Reconstruction phase', isCorrect: false, rationale: 'Reconstruction comes later, as residents take responsibility for rebuilding and find new meaning.' },
      { id: 'd', text: 'Disillusionment phase', isCorrect: true, rationale: 'As outside support withdraws and bureaucratic delays mount, frustration, anger, and feeling abandoned mark disillusionment.' },
    ],
    rationale: 'Disaster mental health models describe community phases: pre-disaster, impact, heroic, honeymoon, disillusionment, and reconstruction. The disillusionment phase can last months or longer, as optimism gives way to fatigue and anger when aid slows and the reality of losses sets in. Counselors can anticipate rising stress during this phase and increase outreach.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis and disaster counseling: phases of disaster response' }],
  },

  // ── intimate partner violence ───────────────────────────────────────────
  {
    id: 'nce-s-clf-088',
    reviewNote: 'Walker\'s cycle is cited via Gladding; confirm coverage, since no IPV-specific text is on the approved list.',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'intimate partner violence',
    difficulty: 'easy',
    stem: 'A week after her partner assaulted her, a client tells the counselor that he cried, brought flowers, promised it would never happen again, and has been "the man I fell in love with." She feels hopeful. In Walker\'s cycle of violence, which phase is this?',
    options: [
      { id: 'a', text: 'Tension-building phase', isCorrect: false, rationale: 'Tension building involves rising strain, minor incidents, and the victim trying to keep the peace.' },
      { id: 'b', text: 'Acute battering phase', isCorrect: false, rationale: 'The acute battering phase is the explosion of violence itself, which has already passed.' },
      { id: 'c', text: 'Honeymoon phase', isCorrect: true, rationale: 'Apologies, gifts, promises, and loving behavior after an assault mark the honeymoon (loving contrition) phase.' },
      { id: 'd', text: 'Resolution phase', isCorrect: false, rationale: 'Walker\'s cycle has no resolution phase; without intervention, the cycle tends to repeat.' },
    ],
    rationale: 'Lenore Walker\'s cycle of violence has three phases: tension building, an acute battering incident, and loving contrition (the honeymoon phase). The honeymoon phase reinforces hope that the abuse will end and helps explain why many survivors stay. Over time the honeymoon phase often shortens or disappears, so counselors should use this period to support safety planning.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Intimate partner violence: the cycle of violence' }],
  },
  {
    id: 'nce-s-clf-089',
    reviewNote: 'The Duluth model is cited via Sue & Sue; confirm coverage or substitute a better approved source.',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'intimate partner violence',
    difficulty: 'medium',
    stem: 'A client says her husband controls all their money, reads her messages, has cut her off from friends, and threatens to take the children if she leaves. She adds, "It isn\'t really abuse, because he has never hit me." Which framework would BEST help her see these behaviors as connected forms of abuse?',
    options: [
      { id: 'a', text: 'Walker\'s cycle of violence', isCorrect: false, rationale: 'The cycle of violence describes phases around violent episodes, and she reports no physical violence.' },
      { id: 'b', text: 'Duluth Power and Control Wheel', isCorrect: true, rationale: 'The wheel shows tactics such as economic abuse, isolation, and using children as parts of one pattern of coercive control.' },
      { id: 'c', text: 'Gottman\'s Four Horsemen', isCorrect: false, rationale: 'The Four Horsemen describe destructive communication in conflict, not coercive control or abuse.' },
      { id: 'd', text: 'Bowen\'s triangulation concept', isCorrect: false, rationale: 'Triangulation describes drawing a third party into a dyad\'s anxiety, not a pattern of abusive control.' },
    ],
    rationale: 'The Power and Control Wheel, developed by the Domestic Abuse Intervention Project in Duluth, Minnesota, shows abuse as a pattern of coercive control. Its spokes are tactics such as intimidation, isolation, economic abuse, using children, and threats, held together by a rim of physical and sexual violence. Coercive control can be dangerous even without physical assault, and conjoint couples counseling is generally contraindicated while it is ongoing.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling women: intimate partner violence and coercive control' }],
  },
];
