// tools/nce/seed/clinical-focus-5.js
// NCE seed items — Areas of Clinical Focus, blueprint topics 1–14 (batch 3).
// New angles that do not repeat clinical-focus-1.js or clinical-focus-3.js:
// PMDD, rapid cycling, panic attack specifier, complex trauma, PE vs CPT,
// ERP hierarchies, withdrawal risk, autism support levels, peripartum
// psychosis, ARFID, delirium on dementia, child grief, postvention, tech IPV.
module.exports = [
  // ── depressive disorders ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-119',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'medium',
    stem: 'A 31-year-old says that in the week before her period she becomes intensely irritable, tearful, and anxious and argues with her partner. The symptoms ease within a few days after menses begins and are gone the following week. She recalls this pattern for about a year. Under DSM-5-TR, what is needed to CONFIRM a diagnosis of premenstrual dysphoric disorder?',
    options: [
      { id: 'a', text: 'Prospective daily symptom ratings over at least two symptomatic cycles', isCorrect: true, rationale: 'DSM-5-TR requires confirmation by prospective daily ratings during at least two symptomatic cycles; the diagnosis may be made provisionally before then.' },
      { id: 'b', text: 'Blood tests showing hormone levels outside the expected range for her age', isCorrect: false, rationale: 'No laboratory test confirms PMDD; hormone levels are typically within normal limits.' },
      { id: 'c', text: 'Her partner\'s report confirming the same pattern over the previous year', isCorrect: false, rationale: 'Collateral reports can help, but the criterion calls for the client\'s own prospective daily ratings.' },
      { id: 'd', text: 'Evidence that she has no co-occurring depressive or anxiety disorders', isCorrect: false, rationale: 'PMDD may co-occur with other disorders; it must simply not be merely an exacerbation of another disorder.' },
    ],
    rationale: 'Premenstrual dysphoric disorder requires at least five symptoms, including at least one marked affective symptom, in the final week before menses in most cycles of the past year, improving within a few days after onset and becoming minimal or absent in the week after. Because retrospective recall overstates cyclic patterns, DSM-5-TR requires confirmation by prospective daily ratings during at least two symptomatic cycles, although a provisional diagnosis may be given first.',
    references: [{ source: 'DSM-5-TR', detail: 'Premenstrual Dysphoric Disorder, Criterion G (prospective daily ratings)' }],
  },
  {
    id: 'nce-s-clf-120',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'hard',
    stem: 'A 76-year-old is referred for "memory problems" after several months of low mood and withdrawal. During a cognitive screen, which observation MOST suggests that depression, rather than a neurodegenerative neurocognitive disorder, is driving her poor performance?',
    options: [
      { id: 'a', text: 'She works hard at each task and covers missed items with plausible guesses', isCorrect: false, rationale: 'Effortful attempts with confabulated or near-miss answers are more typical of a neurodegenerative disorder.' },
      { id: 'b', text: 'She quickly answers "I don\'t know" and stresses how poorly she is doing', isCorrect: true, rationale: 'Low effort, quick "don\'t know" answers and highlighting of her own failures are classic signs of depression-related cognitive impairment.' },
      { id: 'c', text: 'Her family dates a slow, steady decline back over the past several years', isCorrect: false, rationale: 'An insidious, gradual course over years points toward a neurodegenerative process such as Alzheimer\'s disease.' },
      { id: 'd', text: 'She seems unconcerned, and her daughter notices more lapses than she does', isCorrect: false, rationale: 'Reduced awareness of deficits, with family noticing more than the client, is more typical of neurocognitive disorder.' },
    ],
    rationale: 'Depression in later life can produce cognitive complaints (sometimes called pseudodementia). Clients with depression tend to report and emphasize their deficits, give up quickly with "I don\'t know" answers, and show a more recent onset tied to mood change, whereas clients with neurodegenerative disorders often try hard, minimize or are unaware of deficits, and have a gradual course. The distinction guides referral for both mood treatment and a medical workup.',
    references: [
      { source: 'DSM-5-TR', detail: 'Major or Mild Neurocognitive Disorder: differential diagnosis (major depressive disorder)' },
      { source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: depression and cognitive decline' },
    ],
    reviewNote: 'The effort/awareness contrasts are classic clinical teaching ("pseudodementia"), not DSM-5-TR criteria; SME to confirm the Berk chapter locator.',
  },
  // ── bipolar disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-121',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'easy',
    stem: 'Over the past 12 months, a client with bipolar I disorder has had one manic episode, two major depressive episodes, and one hypomanic episode, each separated by a period of remission. Which DSM-5-TR specifier applies?',
    options: [
      { id: 'a', text: 'With mixed features', isCorrect: false, rationale: 'Mixed features describes opposite-pole symptoms occurring within a single episode, not the number of episodes.' },
      { id: 'b', text: 'With seasonal pattern', isCorrect: false, rationale: 'Seasonal pattern requires a regular link between episodes and a time of year, which is not described.' },
      { id: 'c', text: 'With rapid cycling', isCorrect: true, rationale: 'Rapid cycling is specified when at least four mood episodes occur within 12 months.' },
      { id: 'd', text: 'With psychotic features', isCorrect: false, rationale: 'No delusions or hallucinations are described.' },
    ],
    rationale: 'The rapid cycling specifier applies to bipolar I or II disorder when at least four mood episodes (manic, hypomanic, or major depressive) occur in the previous 12 months. Episodes must be demarcated by partial or full remission of at least 2 months or by a switch to an episode of the opposite polarity. Rapid cycling is linked to a poorer prognosis and has treatment implications.',
    references: [{ source: 'DSM-5-TR', detail: 'Specifiers for Bipolar and Related Disorders: with rapid cycling' }],
  },
  {
    id: 'nce-s-clf-122',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'hard',
    stem: 'For 8 days, a 25-year-old has had elevated mood, little need for sleep, and racing thoughts. She still works her shifts, but she now believes a television news anchor is sending her coded messages. A colleague suggests hypomania because her work has not suffered. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'Hypomania fits, since her job performance has stayed largely intact', isCorrect: false, rationale: 'Preserved work functioning does not override the rule that psychotic features make an episode manic.' },
      { id: 'b', text: 'No diagnosis is possible until symptoms have lasted at least 2 weeks', isCorrect: false, rationale: 'Two weeks is the duration for a major depressive episode; mania requires 1 week, which is met.' },
      { id: 'c', text: 'Her beliefs point to schizophrenia rather than to any mood episode', isCorrect: false, rationale: 'Psychotic symptoms limited to a mood episode are part of the mood disorder, not evidence of schizophrenia.' },
      { id: 'd', text: 'Psychotic features mean the episode cannot be classed as hypomanic', isCorrect: true, rationale: 'DSM-5-TR states that if psychotic features are present, the episode is, by definition, manic.' },
    ],
    rationale: 'A hypomanic episode is not severe enough to cause marked impairment or require hospitalization, and it has no psychotic features. DSM-5-TR states that if psychotic features are present, the episode is by definition manic. Here the 1-week duration for mania is met and the delusion makes the episode a manic episode with psychotic features, supporting bipolar I disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar I Disorder: Manic Episode Criterion C; Hypomanic Episode Criterion E' }],
  },
  // ── anxiety disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-123',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'For 9 months, a 50-year-old has been convinced he has undiagnosed heart disease despite normal cardiac workups. He has few physical symptoms but checks his pulse many times a day and reads medical websites for hours. He reports little worry about other areas of life. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Illness anxiety disorder', isCorrect: true, rationale: 'Preoccupation with having a serious illness for at least 6 months, with absent or mild somatic symptoms and excessive checking, fits illness anxiety disorder.' },
      { id: 'b', text: 'Generalized anxiety disorder', isCorrect: false, rationale: 'GAD involves worry about many areas of life, whereas his worry is focused on having one serious disease.' },
      { id: 'c', text: 'Somatic symptom disorder', isCorrect: false, rationale: 'Somatic symptom disorder centers on distressing somatic symptoms; his symptoms are minimal.' },
      { id: 'd', text: 'Panic disorder', isCorrect: false, rationale: 'No recurrent unexpected panic attacks are described.' },
    ],
    rationale: 'Illness anxiety disorder involves preoccupation with having or acquiring a serious illness for at least 6 months, with somatic symptoms absent or only mild, high health anxiety, and excessive health-related behaviors (care-seeking type) or maladaptive avoidance (care-avoidant type). GAD is distinguished by worry spanning multiple events or activities, of which health may be only one.',
    references: [{ source: 'DSM-5-TR', detail: 'Illness Anxiety Disorder: criteria and differential diagnosis (GAD)' }],
  },
  {
    id: 'nce-s-clf-124',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'A client with PTSD has sudden surges of intense fear with a racing heart, sweating, and trembling whenever she encounters reminders of the assault. She does not worry about having attacks out of the blue and has not changed her routine to prevent them. How should these attacks be documented?',
    options: [
      { id: 'a', text: 'Add a separate diagnosis of panic disorder', isCorrect: false, rationale: 'Panic disorder requires recurrent unexpected attacks plus a month of worry or behavior change, neither of which is present.' },
      { id: 'b', text: 'Replace PTSD with panic disorder with agoraphobia', isCorrect: false, rationale: 'The attacks are cued by trauma reminders and agoraphobia is not described; DSM-5-TR also diagnoses panic disorder and agoraphobia separately.' },
      { id: 'c', text: 'Record PTSD with the "with panic attacks" specifier', isCorrect: true, rationale: 'DSM-5-TR allows "with panic attacks" as a specifier for any mental disorder in which panic attacks occur.' },
      { id: 'd', text: 'Leave them out, as expected attacks are not recorded', isCorrect: false, rationale: 'Expected panic attacks can be recorded through the specifier; they are clinically meaningful.' },
    ],
    rationale: 'In DSM-5-TR, panic attacks can be expected or unexpected and are not themselves a mental disorder. When they occur in the context of another disorder, the "with panic attacks" specifier may be added (for example, PTSD with panic attacks). Panic disorder is reserved for recurrent unexpected attacks followed by at least 1 month of persistent concern or maladaptive behavior change.',
    references: [{ source: 'DSM-5-TR', detail: 'Panic Attack Specifier' }],
  },
  {
    id: 'nce-s-clf-125',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'anxiety disorders',
    difficulty: 'easy',
    stem: 'For 5 weeks, a 9-year-old has refused sleepovers, had nightmares about her mother being hurt, and sobbed whenever her mother leaves for work. The symptoms are causing problems at home and school. Her father asks whether a diagnosis of separation anxiety disorder requires symptoms to last 6 months. What is the minimum duration for a child?',
    options: [
      { id: 'a', text: 'Six months, the same as for adults', isCorrect: false, rationale: 'Six months is the typical duration for adults; children need a shorter duration.' },
      { id: 'b', text: 'At least 4 weeks', isCorrect: true, rationale: 'DSM-5-TR requires at least 4 weeks of symptoms in children and adolescents.' },
      { id: 'c', text: 'At least 3 months', isCorrect: false, rationale: 'Three months is not the DSM-5-TR duration for separation anxiety disorder.' },
      { id: 'd', text: 'At least 2 weeks', isCorrect: false, rationale: 'Two weeks is the major depressive episode duration, not the separation anxiety duration.' },
    ],
    rationale: 'Separation anxiety disorder requires developmentally inappropriate and excessive fear about separation from attachment figures, shown by at least three of the listed symptoms, lasting at least 4 weeks in children and adolescents and typically 6 months or more in adults. DSM-5 removed the requirement that onset occur before age 18, so the disorder can also be diagnosed in adults.',
    references: [{ source: 'DSM-5-TR', detail: 'Separation Anxiety Disorder, Criterion B (duration)' }],
  },
  // ── trauma- and stressor-related disorders ──────────────────────────────
  {
    id: 'nce-s-clf-126',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'hard',
    stem: 'A 34-year-old who endured years of childhood abuse reports intrusive memories and avoidance, along with pervasive shame, a sense of being worthless, great difficulty calming strong emotions, and pulling away from close relationships. A colleague wants to give a DSM-5-TR diagnosis of "complex PTSD." Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'Complex PTSD is a DSM-5-TR subtype of PTSD that is recorded with a specifier', isCorrect: false, rationale: 'DSM-5-TR has no complex PTSD subtype or specifier; its PTSD specifiers are dissociative symptoms and delayed expression.' },
      { id: 'b', text: 'Shame and emotion dysregulation rule out PTSD, so another diagnosis is needed', isCorrect: false, rationale: 'Negative self-beliefs, persistent negative emotions, and detachment are part of PTSD Criterion D.' },
      { id: 'c', text: 'Borderline personality disorder must be diagnosed when these features appear', isCorrect: false, rationale: 'These features overlap with borderline personality disorder but do not require that diagnosis; a full assessment is needed.' },
      { id: 'd', text: 'Complex PTSD is an ICD-11 diagnosis; in DSM-5-TR, PTSD covers these features', isCorrect: true, rationale: 'ICD-11 includes complex PTSD; DSM-5-TR captures these features within PTSD, chiefly Criterion D.' },
    ],
    rationale: 'ICD-11 lists complex PTSD, which adds disturbances in self-organization (affect dysregulation, negative self-concept, relational difficulties) to core PTSD symptoms, usually after prolonged or repeated trauma. DSM-5-TR has no separate complex PTSD diagnosis; its broadened PTSD criteria, especially negative alterations in cognitions and mood, capture many of these features. Counselors should know both systems when reading records and research.',
    references: [
      { source: 'ICD-11', detail: '6B41 Complex post-traumatic stress disorder' },
      { source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder, Criterion D and specifiers' },
    ],
  },
  {
    id: 'nce-s-clf-127',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'A 40-year-old with PTSD after an armed robbery at her store is ready for trauma-focused treatment. She keeps telling herself, "It was my fault for staying open late," and says she would rather not retell the event in detail session after session. Which evidence-based approach BEST matches her needs and preferences?',
    options: [
      { id: 'a', text: 'Prolonged exposure, which centers on repeated imaginal retelling', isCorrect: false, rationale: 'PE is effective, but repeated imaginal exposure to the memory is its core, which she prefers to avoid.' },
      { id: 'b', text: 'Critical incident stress debriefing, held in a single group session', isCorrect: false, rationale: 'Single-session debriefing is not an evidence-based treatment for PTSD.' },
      { id: 'c', text: 'Cognitive processing therapy, which targets stuck points like self-blame', isCorrect: true, rationale: 'CPT focuses on identifying and challenging stuck points such as self-blame, and a written account is optional.' },
      { id: 'd', text: 'Psychological first aid, focused on early safety, comfort, and practical help', isCorrect: false, rationale: 'PFA is an early post-event support approach, not a treatment for established PTSD.' },
    ],
    rationale: 'Both prolonged exposure and cognitive processing therapy are strongly recommended for PTSD. PE uses repeated imaginal exposure to the trauma memory and in vivo exposure to avoided situations. CPT helps clients identify and challenge "stuck points," such as self-blame, and can be delivered without a written trauma account. Client preference is a legitimate factor in choosing among effective treatments.',
    references: [{ source: 'APA CPG', detail: 'Clinical Practice Guideline for the Treatment of PTSD (2017): CPT and PE recommendations' }],
  },
  {
    id: 'nce-s-clf-128',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'A paramedic reports intrusive images, avoidance, and constant hypervigilance after years of responding to fatal crashes, including the deaths of children. He was never in danger himself. A peer tells him he cannot have PTSD because his own life was never threatened. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'Repeated or extreme exposure to aversive details on the job can meet Criterion A', isCorrect: true, rationale: 'Criterion A4 includes repeated or extreme exposure to aversive details, as with first responders.' },
      { id: 'b', text: 'Only a direct threat to his own life or body can satisfy the stressor criterion', isCorrect: false, rationale: 'Criterion A also includes witnessing, learning about a close other\'s trauma, and repeated work exposure.' },
      { id: 'c', text: 'Secondary traumatic stress is the DSM-5-TR diagnosis that applies in its place', isCorrect: false, rationale: 'Secondary traumatic stress is a useful concept but is not a DSM-5-TR diagnosis.' },
      { id: 'd', text: 'His symptoms are better classed as adjustment disorder because of his job role', isCorrect: false, rationale: 'Occupational exposure does not shift the diagnosis to adjustment disorder when PTSD criteria are met.' },
    ],
    rationale: 'PTSD Criterion A can be met by direct exposure, witnessing, learning that a traumatic event happened to a close family member or friend, or experiencing repeated or extreme exposure to aversive details of traumatic events, as with first responders or police. Exposure through electronic media counts only when it is work related. First responders face cumulative exposure and should be assessed accordingly.',
    references: [{ source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder, Criterion A4' }],
  },
  // ── obsessive-compulsive and related disorders ──────────────────────────
  {
    id: 'nce-s-clf-129',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'easy',
    stem: 'A 23-year-old spends hours each day picking at small bumps on her face and arms, causing open sores. She has tried many times to stop, feels ashamed, and wears long sleeves to hide the marks. A physician found no skin condition, and she uses no stimulants. Which diagnosis is MOST likely?',
    options: [
      { id: 'a', text: 'Trichotillomania', isCorrect: false, rationale: 'Trichotillomania involves recurrent hair pulling, not skin picking.' },
      { id: 'b', text: 'Excoriation disorder', isCorrect: true, rationale: 'Recurrent skin picking causing lesions, with repeated attempts to stop and distress, fits excoriation disorder.' },
      { id: 'c', text: 'Body dysmorphic disorder', isCorrect: false, rationale: 'BDD picking aims to fix a perceived appearance flaw; no such preoccupation is described.' },
      { id: 'd', text: 'Nonsuicidal self-injury', isCorrect: false, rationale: 'NSSI involves intentional self-injury for relief or other functions, not a body-focused repetitive habit.' },
    ],
    rationale: 'Excoriation (skin-picking) disorder, in the obsessive-compulsive and related disorders chapter, requires recurrent skin picking resulting in skin lesions, repeated attempts to decrease or stop, and clinically significant distress or impairment. The picking must not be due to a substance, such as stimulants, or a dermatologic condition, and must not be better explained by another disorder, such as BDD.',
    references: [{ source: 'DSM-5-TR', detail: 'Excoriation (Skin-Picking) Disorder: criteria and differential diagnosis' }],
  },
  {
    id: 'nce-s-clf-130',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'medium',
    stem: 'A counselor and a client with contamination-focused OCD are building an exposure and response prevention (ERP) hierarchy. Which practice is MOST consistent with ERP?',
    options: [
      { id: 'a', text: 'Start with the most feared item so that change comes quickly', isCorrect: false, rationale: 'Beginning at the top of the hierarchy is flooding and can reduce willingness to continue; ERP usually starts lower.' },
      { id: 'b', text: 'Allow one quick wash after each exposure to keep distress low', isCorrect: false, rationale: 'Washing after exposure is a compulsion that undercuts response prevention.' },
      { id: 'c', text: 'End each exposure as soon as the client\'s distress starts to rise', isCorrect: false, rationale: 'Ending exposures when distress rises rewards escape and prevents new learning.' },
      { id: 'd', text: 'Begin with tasks rated as moderately distressing and work upward', isCorrect: true, rationale: 'Graded ERP typically starts with moderately distressing items and moves up the hierarchy.' },
    ],
    rationale: 'In ERP, the client rates feared situations (often with subjective units of distress) to build a graded hierarchy, then repeatedly confronts them while refraining from compulsions, including subtle or mental rituals. Exposures usually begin with moderately distressing items and progress upward. Remaining in the situation without ritualizing lets the client learn that feared outcomes do not occur and that distress can be tolerated.',
    references: [{ source: 'NICE guidelines', detail: 'CG31 Obsessive-compulsive disorder and body dysmorphic disorder: CBT including ERP' }],
    reviewNote: 'NICE CG31 supports ERP; the graded-hierarchy details are standard ERP practice rather than guideline text. No OCD-specific treatment manual is on the approved list.',
  },
  // ── substance use and addictive disorders ───────────────────────────────
  {
    id: 'nce-s-clf-131',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'substance use and addictive disorders',
    difficulty: 'easy',
    stem: 'A 48-year-old who has drunk heavily every day for years plans to quit "cold turkey" this weekend while home alone. He mentions morning shakes and sweats that go away once he has a drink. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Affirm his plan and schedule a check-in call for Monday', isCorrect: false, rationale: 'Affirming an unsupervised stop ignores the risk of dangerous withdrawal.' },
      { id: 'b', text: 'Start a relapse prevention plan focused on his triggers', isCorrect: false, rationale: 'Relapse prevention matters later; immediate medical safety comes first.' },
      { id: 'c', text: 'Refer him for medical evaluation before he stops drinking', isCorrect: true, rationale: 'Signs of physical dependence call for medical assessment and supervised withdrawal management.' },
      { id: 'd', text: 'Suggest he taper on his own by cutting back day by day', isCorrect: false, rationale: 'An unsupervised self-taper still carries withdrawal risk; the decision belongs with a medical provider.' },
    ],
    rationale: 'Alcohol withdrawal can progress to seizures and withdrawal delirium, which can be fatal. Morning tremor and sweating relieved by drinking suggest physical dependence, so the counselor should arrange medical evaluation to determine the appropriate withdrawal management setting before the client stops. ASAM Dimension 1 (acute intoxication and withdrawal potential) guides this decision.',
    references: [
      { source: 'ASAM Criteria', detail: 'Dimension 1: acute intoxication and/or withdrawal potential' },
      { source: 'DSM-5-TR', detail: 'Alcohol Withdrawal: features and complications' },
    ],
  },
  {
    id: 'nce-s-clf-132',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'substance use and addictive disorders',
    difficulty: 'medium',
    stem: 'A 16-year-old is referred after cannabis is found in his backpack. He uses most days and his grades are slipping. He says, "Weed is natural. It doesn\'t hurt anybody." Which counselor response BEST reflects a motivational rather than a confrontational approach?',
    options: [
      { id: 'a', text: '"Research shows cannabis harms the teen brain, so you need to stop now."', isCorrect: false, rationale: 'Leading with warnings and demands is the righting reflex and tends to increase resistance.' },
      { id: 'b', text: '"Until you admit you have a problem, counseling will not help you much."', isCorrect: false, rationale: 'Requiring the client to accept a label is a confrontational stance MI avoids.' },
      { id: 'c', text: '"It feels pretty harmless to you. What, if anything, concerns you about it?"', isCorrect: true, rationale: 'A reflection followed by an open question rolls with discord and invites the teen\'s own reasons for change.' },
      { id: 'd', text: '"Your parents and school are worried, so let\'s agree that you quit today."', isCorrect: false, rationale: 'Pressing for a commitment the teen has not voiced bypasses his ambivalence and autonomy.' },
    ],
    rationale: 'Motivational interviewing avoids arguing, labeling, and the righting reflex, which tend to provoke sustain talk, especially in adolescents sensitive to autonomy. Instead, the counselor reflects the client\'s view and asks open questions that evoke the client\'s own concerns and reasons for change. Research does not support confrontational approaches for substance use.',
    references: [
      { source: 'Miller & Rollnick (MI)', detail: 'The righting reflex; responding to sustain talk and discord' },
      { source: 'SAMHSA TIP 35', detail: 'Motivational approaches with adolescents' },
    ],
  },
  // ── neurodevelopmental disorders ────────────────────────────────────────
  {
    id: 'nce-s-clf-133',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'A 32-year-old seeks an ADHD evaluation for lifelong disorganization, forgetfulness, and trouble finishing tasks at work and home. Which statement about diagnosing ADHD in adults under DSM-5-TR is accurate?',
    options: [
      { id: 'a', text: 'Five symptoms in a domain are needed for those aged 17 and older', isCorrect: true, rationale: 'DSM-5-TR lowers the threshold to five symptoms in a domain for older adolescents and adults.' },
      { id: 'b', text: 'Six symptoms in a domain are needed at every age, adults included', isCorrect: false, rationale: 'Six symptoms are required for children up to age 16; five for those 17 and older.' },
      { id: 'c', text: 'Impairment from symptoms must be documented from before age 7', isCorrect: false, rationale: 'DSM-5 replaced age 7 with several symptoms present before age 12; impairment need not be documented then.' },
      { id: 'd', text: 'Symptoms need to appear in only one setting, such as the workplace', isCorrect: false, rationale: 'Several symptoms must be present in two or more settings.' },
    ],
    rationale: 'For ADHD, children up to age 16 need six or more symptoms of inattention and/or hyperactivity-impulsivity, while adolescents aged 17 and older and adults need five or more. Several symptoms must have been present before age 12 and in two or more settings. Adult presentations often show more inattention and inner restlessness than overt hyperactivity.',
    references: [{ source: 'DSM-5-TR', detail: 'Attention-Deficit/Hyperactivity Disorder, Criterion A (symptom thresholds by age)' }],
  },
  {
    id: 'nce-s-clf-134',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'An autistic 8-year-old speaks in full sentences but struggles with back-and-forth conversation and making friends. His insistence on sameness and great distress at small changes markedly interfere with functioning across settings. How should severity be recorded under DSM-5-TR?',
    options: [
      { id: 'a', text: 'Assign one overall level, based mainly on his measured IQ', isCorrect: false, rationale: 'Severity is not based on IQ; intellectual impairment is recorded with a separate specifier.' },
      { id: 'b', text: 'Rate social communication and restricted behaviors separately', isCorrect: true, rationale: 'DSM-5-TR rates the level of support needed separately for each of the two domains.' },
      { id: 'c', text: 'Assign a support level only if he has intellectual disability', isCorrect: false, rationale: 'Severity levels are recorded for all autistic individuals, with or without intellectual disability.' },
      { id: 'd', text: 'Use only the more impaired domain to set one combined level', isCorrect: false, rationale: 'The domains are rated separately, so a child may need different levels of support in each.' },
    ],
    rationale: 'DSM-5-TR asks clinicians to specify current severity of autism spectrum disorder separately for social communication and for restricted, repetitive behaviors, using levels 1 (requiring support), 2 (requiring substantial support), and 3 (requiring very substantial support). Severity can change across contexts and over time, and it is recorded alongside specifiers for intellectual and language impairment.',
    references: [{ source: 'DSM-5-TR', detail: 'Autism Spectrum Disorder: severity levels for each domain' }],
  },
  // ── schizophrenia spectrum disorders ────────────────────────────────────
  {
    id: 'nce-s-clf-135',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'medium',
    stem: 'Two weeks after giving birth, a 28-year-old suddenly develops delusions and disorganized speech. She has no manic or depressive symptoms. With treatment, she returns fully to her prior level of functioning after 10 days. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Schizophreniform disorder, with good prognostic features', isCorrect: false, rationale: 'Schizophreniform disorder requires symptoms lasting at least 1 month.' },
      { id: 'b', text: 'Major depressive disorder, with peripartum onset', isCorrect: false, rationale: 'No depressive episode is described.' },
      { id: 'c', text: 'Schizophrenia, first episode, currently in acute episode', isCorrect: false, rationale: 'Schizophrenia requires continuous signs for at least 6 months.' },
      { id: 'd', text: 'Brief psychotic disorder, with peripartum onset', isCorrect: true, rationale: 'Psychotic symptoms lasting at least 1 day but less than 1 month, beginning within 4 weeks postpartum, fit this diagnosis and specifier.' },
    ],
    rationale: 'Brief psychotic disorder requires at least one of delusions, hallucinations, or disorganized speech (plus possibly grossly disorganized behavior), lasting at least 1 day but less than 1 month, with full return to premorbid functioning. The "with peripartum onset" specifier applies when onset is during pregnancy or within 4 weeks postpartum. Postpartum psychosis is a psychiatric emergency, and clinicians should also consider an underlying bipolar disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Brief Psychotic Disorder: criteria and specifiers' }],
  },
  {
    id: 'nce-s-clf-136',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'easy',
    stem: 'Parents of a 17-year-old report that over 8 months he has pulled away from friends, his grades have dropped, he neglects hygiene, and he has become suspicious and voices odd ideas. He has no clear hallucinations or fixed delusions and does not use substances. What is the MOST appropriate action?',
    options: [
      { id: 'a', text: 'Refer for a full evaluation, as these may be early signs of psychosis', isCorrect: true, rationale: 'A decline in functioning with emerging odd beliefs can signal a prodrome; early evaluation and intervention improve outcomes.' },
      { id: 'b', text: 'Reassure the parents that these are typical changes during adolescence', isCorrect: false, rationale: 'A marked, sustained decline with suspiciousness goes beyond typical adolescent change.' },
      { id: 'c', text: 'Diagnose schizophrenia, since negative signs have lasted over 6 months', isCorrect: false, rationale: 'Schizophrenia requires an active phase of at least 1 month of Criterion A symptoms, which is not present.' },
      { id: 'd', text: 'Wait to act until hallucinations or delusions have clearly appeared', isCorrect: false, rationale: 'Waiting for frank psychosis delays care; a long duration of untreated psychosis worsens outcomes.' },
    ],
    rationale: 'Prodromal signs of schizophrenia often include social withdrawal, declining school or work performance, poor self-care, and attenuated positive symptoms such as unusual beliefs or suspiciousness. These signs do not establish a diagnosis, but they warrant prompt referral for comprehensive evaluation, because shorter duration of untreated psychosis is associated with better outcomes. DSM-5-TR lists attenuated psychosis syndrome as a condition for further study.',
    references: [
      { source: 'DSM-5-TR', detail: 'Schizophrenia: development and course (prodromal phase)' },
      { source: 'DSM-5-TR', detail: 'Conditions for Further Study: Attenuated Psychosis Syndrome' },
    ],
  },
  // ── personality disorders ───────────────────────────────────────────────
  {
    id: 'nce-s-clf-137',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'easy',
    stem: 'A 30-year-old cannot decide what to wear or what to order at a restaurant without reassurance from her mother. She agrees with others even when she disagrees, for fear of losing their support, feels helpless when alone, and quickly began a new relationship after a breakup. Which personality disorder BEST fits?',
    options: [
      { id: 'a', text: 'Avoidant personality disorder', isCorrect: false, rationale: 'Avoidant PD centers on fear of criticism and rejection leading to social avoidance, not a need to be taken care of.' },
      { id: 'b', text: 'Histrionic personality disorder', isCorrect: false, rationale: 'Histrionic PD involves attention seeking and shallow, shifting emotion.' },
      { id: 'c', text: 'Dependent personality disorder', isCorrect: true, rationale: 'Difficulty making everyday decisions, fear of disagreeing, and urgently seeking a new relationship fit dependent PD.' },
      { id: 'd', text: 'Borderline personality disorder', isCorrect: false, rationale: 'Borderline PD involves unstable identity, affect, and relationships, not submissive reliance for everyday decisions.' },
    ],
    rationale: 'Dependent personality disorder, in Cluster C, is a pervasive and excessive need to be taken care of that leads to submissive, clinging behavior and fears of separation. Criteria include difficulty making everyday decisions without excessive advice, difficulty expressing disagreement, feeling helpless when alone, and urgently seeking another relationship when one ends.',
    references: [{ source: 'DSM-5-TR', detail: 'Dependent Personality Disorder: criteria and differential diagnosis' }],
  },
  {
    id: 'nce-s-clf-138',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'hard',
    stem: 'A 45-year-old manager follows rules rigidly, misses deadlines because work is never perfect enough, will not delegate, is reluctant to spend money, and has let friendships lapse because of work. He sees his ways as simply "the right way." He reports no intrusive thoughts or rituals. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'OCD fits best, since his perfectionism counts as an obsession', isCorrect: false, rationale: 'Perfectionism that is experienced as correct is a trait, not an intrusive, unwanted obsession.' },
      { id: 'b', text: 'OCPD fits; his traits form a pattern without true obsessions', isCorrect: true, rationale: 'His pervasive, ego-syntonic perfectionism, rigidity, and miserliness, without obsessions or compulsions, fit OCPD.' },
      { id: 'c', text: 'OCPD can be diagnosed only when OCD is also present with it', isCorrect: false, rationale: 'OCPD does not require OCD; the two may co-occur but are distinct.' },
      { id: 'd', text: 'Narcissistic PD fits, since he sees his own way as superior', isCorrect: false, rationale: 'His focus is on order and control, not grandiosity or a need for admiration.' },
    ],
    rationale: 'Obsessive-compulsive personality disorder is a pervasive pattern of preoccupation with orderliness, perfectionism, and control at the expense of flexibility and efficiency, including excessive devotion to work, reluctance to delegate, and miserly spending. Unlike OCD, it involves no true obsessions or compulsions, and the traits are usually ego-syntonic. The two can co-occur, but neither requires the other.',
    references: [{ source: 'DSM-5-TR', detail: 'Obsessive-Compulsive Personality Disorder: differential diagnosis (OCD)' }],
  },
  // ── eating disorders ────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-139',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'Parents of a 7-year-old say he eats only a handful of familiar foods and refuses new textures. A pediatrician has ruled out a medical cause. Which finding would MOST support avoidant/restrictive food intake disorder (ARFID) rather than ordinary picky eating?',
    options: [
      { id: 'a', text: 'He refuses most vegetables and prefers plain pasta at dinner', isCorrect: false, rationale: 'Food preferences like this are common in young children and do not show clinical significance.' },
      { id: 'b', text: 'He eats more readily when meals are served in a favorite bowl', isCorrect: false, rationale: 'This is a typical childhood preference with no sign of nutritional or functional impact.' },
      { id: 'c', text: 'He complains that many new foods look strange or smell bad to him', isCorrect: false, rationale: 'Sensory dislikes occur in both picky eating and ARFID, so they do not distinguish them.' },
      { id: 'd', text: 'He now relies on nutritional supplements and growth has faltered', isCorrect: true, rationale: 'Faltering growth and dependence on supplements are among the consequences that define ARFID.' },
    ],
    rationale: 'ARFID requires an eating disturbance that leads to at least one of: significant weight loss or faltering growth in children, significant nutritional deficiency, dependence on enteral feeding or oral nutritional supplements, or marked interference with psychosocial functioning. Picky eating without these consequences is developmentally common. ARFID also differs from anorexia nervosa in lacking body image disturbance.',
    references: [{ source: 'DSM-5-TR', detail: 'Avoidant/Restrictive Food Intake Disorder, Criterion A' }],
  },
  {
    id: 'nce-s-clf-140',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'A 20-year-old in outpatient counseling for anorexia nervosa says her recent blood work was "totally normal," so she no longer needs to see her physician. Which counselor response is MOST accurate?',
    options: [
      { id: 'a', text: 'Normal labs do not rule out serious risk, so medical monitoring should continue', isCorrect: true, rationale: 'Laboratory results can be normal despite serious medical risk, so ongoing medical monitoring remains part of care.' },
      { id: 'b', text: 'Normal labs show she is medically stable and can pause physician visits for now', isCorrect: false, rationale: 'Normal labs do not establish medical stability in anorexia nervosa.' },
      { id: 'c', text: 'Medical monitoring is needed only if she begins to report purging behaviors', isCorrect: false, rationale: 'Restriction alone carries significant medical risk; monitoring is not limited to purging.' },
      { id: 'd', text: 'The counselor can track her physical health during sessions in place of a doctor', isCorrect: false, rationale: 'Medical monitoring is outside counseling scope and requires a qualified medical provider.' },
    ],
    rationale: 'Anorexia nervosa has one of the highest mortality rates among mental disorders, and laboratory values can remain normal even when risk is serious. Treatment is multidisciplinary: the counselor coordinates with a medical provider who monitors physical health throughout care, and helps the client see monitoring as part of recovery rather than a sign of failure.',
    references: [
      { source: 'NICE guidelines', detail: 'NG69 Eating disorders: recognition and treatment, physical health monitoring' },
      { source: 'DSM-5-TR', detail: 'Anorexia Nervosa: functional consequences and laboratory findings' },
    ],
  },
  // ── neurocognitive disorders ────────────────────────────────────────────
  {
    id: 'nce-s-clf-141',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'medium',
    stem: 'A nursing home resident with moderate Alzheimer\'s disease has, over the past 2 days, become much more confused, drowsy at times and agitated at others, and unable to keep her attention on a conversation. Staff say, "Her dementia is just getting worse." What should the counselor do?',
    options: [
      { id: 'a', text: 'Agree that this is expected decline and update her care plan', isCorrect: false, rationale: 'Alzheimer\'s disease progresses gradually; an abrupt change over days is not expected progression.' },
      { id: 'b', text: 'Begin reminiscence sessions to help reorient her to the past', isCorrect: false, rationale: 'Reminiscence does not address a possible acute medical cause of the change.' },
      { id: 'c', text: 'Alert medical staff promptly, as this may signal a delirium', isCorrect: true, rationale: 'Acute onset, fluctuating alertness, and inattention suggest delirium, which needs urgent medical evaluation.' },
      { id: 'd', text: 'Repeat a cognitive screen in a month to compare the scores', isCorrect: false, rationale: 'Waiting a month delays care for a potentially serious, treatable medical cause.' },
    ],
    rationale: 'Delirium is a disturbance in attention and awareness that develops over hours to days, fluctuates, and is caused by a medical condition, substance, or medication. People with major neurocognitive disorder are at higher risk, and delirium superimposed on dementia is often missed because staff attribute the change to the dementia. Any abrupt change in cognition calls for prompt medical evaluation.',
    references: [{ source: 'DSM-5-TR', detail: 'Delirium: criteria, risk factors, and differential diagnosis (major neurocognitive disorder)' }],
  },
  // ── grief and loss ──────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-142',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'grief and loss',
    difficulty: 'easy',
    stem: 'A month after her grandfather died, a 4-year-old keeps asking when he will be finished being dead and come home. Her parents worry that something is wrong. What BEST explains her questions?',
    options: [
      { id: 'a', text: 'Her questions show a denial that calls for treatment', isCorrect: false, rationale: 'This reflects normal cognitive development, not pathological denial.' },
      { id: 'b', text: 'Young children often do not yet see death as permanent', isCorrect: true, rationale: 'Preschoolers commonly view death as temporary or reversible; irreversibility is understood later.' },
      { id: 'c', text: 'She is showing early signs of prolonged grief disorder', isCorrect: false, rationale: 'Her questions are developmentally expected, and too little time has passed for that diagnosis.' },
      { id: 'd', text: 'She is too young to grieve, so the topic should wait', isCorrect: false, rationale: 'Young children do grieve and benefit from simple, honest explanations.' },
    ],
    rationale: 'Children gradually develop an understanding of death\'s components: irreversibility (permanence), nonfunctionality (the body stops working), universality (all living things die), and causality. Preschoolers often think of death as temporary, like sleep or a trip. Adults can help by using clear, concrete words such as "died" rather than euphemisms, answering repeated questions patiently, and including children in mourning rituals as appropriate.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Death, dying, and bereavement: children\'s understanding of death' },
      { source: 'Worden (Grief Counseling)', detail: 'Grieving children: developmental understanding of death' },
    ],
  },
  {
    id: 'nce-s-clf-143',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'grief and loss',
    difficulty: 'easy',
    stem: 'A 52-year-old\'s former husband, with whom she stayed close after their divorce, died suddenly. His family did not invite her to the funeral, coworkers seem puzzled that she is upset, and she says she has "no right" to grieve. Which concept BEST describes her experience?',
    options: [
      { id: 'a', text: 'Anticipatory grief', isCorrect: false, rationale: 'Anticipatory grief occurs before an expected death; this death was sudden.' },
      { id: 'b', text: 'Prolonged grief disorder', isCorrect: false, rationale: 'Nothing indicates the duration or impairment required for prolonged grief disorder.' },
      { id: 'c', text: 'Chronic grief', isCorrect: false, rationale: 'Chronic grief refers to excessively long mourning, not grief that lacks social recognition.' },
      { id: 'd', text: 'Disenfranchised grief', isCorrect: true, rationale: 'Grief that is not openly acknowledged, socially supported, or publicly mourned is disenfranchised grief.' },
    ],
    rationale: 'Disenfranchised grief, a term introduced by Doka, describes grief that is not openly acknowledged or socially supported, such as the death of a former spouse, an unrecognized partner, a pet, or a pregnancy loss. Lack of social recognition removes supports and rituals and can complicate mourning. Counselors can validate the loss and help clients create their own ways to mourn.',
    references: [{ source: 'Worden (Grief Counseling)', detail: 'Mediators of mourning: social mediators and socially unrecognized losses' }],
    reviewNote: 'The term is Doka\'s; Worden discusses socially unspeakable/negated losses among social mediators. SME to confirm the Worden locator wording.',
  },
  {
    id: 'nce-s-clf-144',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'grief and loss',
    difficulty: 'medium',
    stem: 'The husband of a woman with advancing ALS says he already grieves the losses of her voice and their plans for retirement. He feels guilty "mourning someone who is still here." Which counselor response is MOST helpful?',
    options: [
      { id: 'a', text: 'Normalize his anticipatory grief and help him face both loss and time left', isCorrect: true, rationale: 'Anticipatory grief is a normal response to expected loss; counseling can attend to it while supporting time together.' },
      { id: 'b', text: 'Advise him to set the grief aside until after she has died, to stay strong', isCorrect: false, rationale: 'Suppressing grief is not recommended and adds to his guilt and isolation.' },
      { id: 'c', text: 'Explain that grieving now shows a detachment that could harm her care', isCorrect: false, rationale: 'Anticipatory grief does not indicate harmful detachment and should not be pathologized.' },
      { id: 'd', text: 'Assure him that grieving now means he will grieve far less after she dies', isCorrect: false, rationale: 'Anticipatory grief does not reliably reduce grief after the death, so this promise is misleading.' },
    ],
    rationale: 'Anticipatory grief is mourning that begins before an expected death, often in response to a series of losses during a progressive illness. It is normal and may include guilt, sadness, and fatigue. Worden notes that it does not necessarily shorten or lessen grief after the death; counselors can normalize it, address the losses already occurring, and help the family make meaningful use of the time remaining.',
    references: [{ source: 'Worden (Grief Counseling)', detail: 'Anticipatory grief' }],
  },
  // ── crisis and disaster response ────────────────────────────────────────
  {
    id: 'nce-s-clf-145',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'crisis and disaster response',
    difficulty: 'easy',
    stem: 'A counselor returns from a meeting to four voicemails from clients. Which client should the counselor contact FIRST?',
    options: [
      { id: 'a', text: 'A client who reports her panic attacks are back and she cannot sleep', isCorrect: false, rationale: 'This is distressing and needs follow-up, but it shows no imminent danger.' },
      { id: 'b', text: 'A client who is furious about a custody ruling and wants to vent today', isCorrect: false, rationale: 'Anger about a court ruling warrants a call but shows no stated risk of harm.' },
      { id: 'c', text: 'A client who has written goodbye letters and given away her pet cats', isCorrect: true, rationale: 'Goodbye letters and giving away belongings are preparatory behaviors that signal acute suicide risk.' },
      { id: 'd', text: 'A client who missed his appointment and would like to reschedule it', isCorrect: false, rationale: 'A routine scheduling request has the lowest priority.' },
    ],
    rationale: 'Crisis triage puts imminent risk to life first. Preparatory behaviors, such as writing goodbye notes or giving away valued possessions, are among the strongest warning signs of suicide and call for immediate contact and risk assessment, for example with the C-SSRS. Other clients\' needs are real but can be addressed afterward.',
    references: [{ source: 'C-SSRS', detail: 'Suicidal behavior: preparatory acts or behavior' }],
  },
  {
    id: 'nce-s-clf-146',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'crisis and disaster response',
    difficulty: 'hard',
    stem: 'After a high school student dies by suicide, the principal asks the school counselor to lead the response. Which action BEST reduces the risk of suicide contagion among students?',
    options: [
      { id: 'a', text: 'Set up a lasting memorial on campus where students can gather and grieve', isCorrect: false, rationale: 'Permanent or prominent memorials can glamorize the death; postvention guidance favors time-limited, low-key options.' },
      { id: 'b', text: 'Share facts without method details and screen students most at risk', isCorrect: true, rationale: 'Safe messaging plus identifying and reaching out to vulnerable students are core postvention steps.' },
      { id: 'c', text: 'Avoid any mention of the death so that students do not become upset', isCorrect: false, rationale: 'Silence fuels rumors and leaves grieving students without support.' },
      { id: 'd', text: 'Explain that stress caused the death, so students have a simple answer', isCorrect: false, rationale: 'Attributing suicide to a single cause oversimplifies it and can lead others to identify with it.' },
    ],
    rationale: 'Postvention aims to support grief and prevent contagion. Recommended steps include sharing accurate information in small groups or classrooms without describing the method, avoiding glamorizing or simplifying the death, offering time-limited and low-key memorial options, and actively identifying and reaching out to students at elevated risk, such as close friends, those with prior suicidal behavior, and those exposed to the death.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis counseling in schools: responding after a suicide' }],
    reviewNote: 'Content follows AFSP/SPRC "After a Suicide: A Toolkit for Schools," which is not on the approved source list; the Gladding locator is a general crisis-counseling citation.',
  },
  // ── intimate partner violence ───────────────────────────────────────────
  {
    id: 'nce-s-clf-147',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'intimate partner violence',
    difficulty: 'hard',
    stem: 'A client who recently left an abusive partner says he keeps appearing wherever she goes and texts her details about her day. She plans to change all her passwords and delete her accounts tonight. Which counselor response is MOST appropriate?',
    options: [
      { id: 'a', text: 'Plan with her first, since sudden changes may alert him and raise risk', isCorrect: true, rationale: 'Abrupt loss of access can signal to an abuser that the victim is acting and may escalate danger, so changes are planned as part of safety planning.' },
      { id: 'b', text: 'Urge her to block him and delete every account tonight to cut off his access', isCorrect: false, rationale: 'This may feel protective but can provoke escalation and destroy evidence of stalking.' },
      { id: 'c', text: 'Reassure her that tracking her is unlikely unless he holds her phone', isCorrect: false, rationale: 'Shared accounts, spyware, location sharing, and tracking devices allow monitoring without physical access.' },
      { id: 'd', text: 'Suggest she meet with him in person to demand that he stop following her', isCorrect: false, rationale: 'Confronting a stalking ex-partner can increase risk; contact decisions belong in safety planning.' },
    ],
    rationale: 'Technology-facilitated abuse and stalking are common after separation, which is itself a high-risk period. Safety planning considers how the abuser may be monitoring the client (shared accounts, location sharing, spyware, trackers), uses a safer device for sensitive contacts, documents incidents for possible legal action, and times changes so they do not alert the abuser. Connecting the client with a domestic violence advocate adds specialized expertise.',
    references: [
      { source: 'SAMHSA TIP 57', detail: 'Trauma-informed principles: safety and client choice' },
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling survivors of intimate partner violence' },
    ],
    reviewNote: 'Technology-safety guidance comes from NNEDV Safety Net materials, which are not on the approved source list; citations are general.',
  },
  {
    id: 'nce-s-clf-148',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'intimate partner violence',
    difficulty: 'medium',
    stem: 'A mother says her 6-year-old was "asleep upstairs" during her partner\'s assaults on her and was never hit, so the girl has not been affected. Since the mother left, the child has had nightmares, startles easily, and clings to her at bedtime. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'Children who are not hit themselves seldom show lasting effects', isCorrect: false, rationale: 'Children exposed to IPV show emotional and behavioral effects comparable to those of directly abused children.' },
      { id: 'b', text: 'Her symptoms most likely reflect a normal phase at her age', isCorrect: false, rationale: 'Nightmares, startle, and clinging after exposure to violence are trauma-related signs, not a typical phase.' },
      { id: 'c', text: 'Young children forget such events, so focus on the mother', isCorrect: false, rationale: 'Young children are affected by violence they overhear, and they need their own assessment and support.' },
      { id: 'd', text: 'Hearing or seeing IPV can cause trauma reactions in children', isCorrect: true, rationale: 'Witnessing or overhearing violence against a caregiver is a traumatic exposure that can produce trauma symptoms.' },
    ],
    rationale: 'Children often see or hear IPV even when parents believe they are asleep or unaware. DSM-5-TR PTSD criteria for children 6 years and younger specifically include witnessing traumatic events occurring to others, especially primary caregivers. Exposed children may show sleep problems, hyperarousal, regression, and clinginess, and benefit from trauma-informed assessment and a strengthened caregiver relationship.',
    references: [
      { source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder for Children 6 Years and Younger, Criterion A2' },
      { source: 'SAMHSA TIP 57', detail: 'Trauma across the life span: children exposed to violence' },
    ],
  },
];
