// tools/nce/seed/clinical-focus-8.js
// NCE practice items, batch 4 — Areas of Clinical Focus (blueprint topics 15–28).
module.exports = [
  // ── aging and older adults ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-208',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'aging and older adults',
    difficulty: 'medium',
    stem: 'A 73-year-old retired teacher with no history of anxiety reports four months of constant worry, a racing heart, restlessness and poor sleep. She recently began two new medications and says, "I just feel keyed up all the time." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Begin weekly CBT for generalized anxiety and give a worry log', isCorrect: false, rationale: 'CBT may help later, but new-onset anxiety in late life needs a medical cause ruled out before a psychological plan is set.' },
      { id: 'b', text: 'Teach slow breathing and suggest she cut back on her caffeine', isCorrect: false, rationale: 'Coping tips are reasonable but skip the key step of checking for medical and medication causes of her symptoms.' },
      { id: 'c', text: 'Encourage a medical review of her health and new medications', isCorrect: true, rationale: 'Late-onset anxiety often has medical or medication contributors (e.g., thyroid, cardiac, drug effects), so medical review comes first.' },
      { id: 'd', text: 'Reassure her that worry is a normal response to growing older', isCorrect: false, rationale: 'Persistent anxiety is not a normal part of aging; dismissing it reflects ageist assumptions and delays care.' },
    ],
    rationale: 'Anxiety that first appears in later life is more often linked to medical illness, medication side effects or interactions, or early cognitive change than anxiety that began earlier. Older adults also tend to describe anxiety in somatic terms. Counselors coordinate a medical evaluation first, then provide evidence-based psychological treatment such as CBT, which is effective for older adults.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: physical health, medication use and mental health' }],
  },
  {
    id: 'nce-s-clf-209',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'aging and older adults',
    difficulty: 'hard',
    stem: 'A home-health aide refers an 83-year-old man who lives alone. His home has spoiled food, piled-up mail and no working heat, and he has missed his heart medication for weeks. No one else is involved in his care. He tells the counselor, "I\'m fine. Leave me be." Which response BEST fits the counselor\'s obligations?',
    options: [
      { id: 'a', text: 'Assess his safety and capacity and follow state rules on reporting to APS', isCorrect: true, rationale: 'Self-neglect that threatens health is reportable to Adult Protective Services in most states, and capacity shapes the response; both must be assessed.' },
      { id: 'b', text: 'Honor his stated wishes and close the case, since he is a competent adult', isCorrect: false, rationale: 'His capacity has not been assessed, and serious self-neglect may trigger reporting duties regardless of his preference.' },
      { id: 'c', text: 'Arrange for him to move to a nursing home before the cold weather comes', isCorrect: false, rationale: 'Counselors do not unilaterally relocate adults; least-restrictive options and his rights must be weighed through proper channels.' },
      { id: 'd', text: 'Ask the aide to keep watching and decide again at the next monthly visit', isCorrect: false, rationale: 'No heat and missed cardiac medication are current dangers; waiting a month risks serious harm.' },
    ],
    rationale: 'Elder self-neglect, an older adult\'s failure to meet his own basic needs in ways that threaten health or safety, is the most common type of case reported to Adult Protective Services, and most states treat it as reportable. Counselors balance respect for autonomy against safety by assessing decision-making capacity and immediate risk, following state reporting law, and favoring the least-restrictive supports.',
    references: [{ source: 'State law', detail: 'Adult protective services statutes: self-neglect and vulnerable-adult reporting' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
    reviewNote: 'Whether self-neglect is reportable, and who is a mandated reporter of vulnerable-adult maltreatment, varies by state; SME to confirm the "most states" framing.',
  },
  {
    id: 'nce-s-clf-210',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'aging and older adults',
    difficulty: 'easy',
    stem: 'During a community talk on aging, an attendee says, "Getting old means your mind goes and you end up lonely and miserable." Which statement BEST reflects life-span research on typical aging?',
    options: [
      { id: 'a', text: 'Memory and reasoning decline steeply for most people after age sixty', isCorrect: false, rationale: 'Some abilities slow, but steep, global decline is not typical of normal aging; it suggests a neurocognitive disorder.' },
      { id: 'b', text: 'Most older adults become more depressed as their social circles shrink', isCorrect: false, rationale: 'Smaller networks reflect chosen focus on close ties; depression is not a normal outcome of aging.' },
      { id: 'c', text: 'Crystallized knowledge and processing speed both fall sharply with age', isCorrect: false, rationale: 'Processing speed slows, but crystallized knowledge such as vocabulary is stable or grows into late life.' },
      { id: 'd', text: 'Emotional well-being is often stable or better, though processing slows', isCorrect: true, rationale: 'Older adults often report steady or improved emotional well-being, while fluid abilities like speed show gradual slowing.' },
    ],
    rationale: 'Research finds that emotional well-being tends to hold steady or improve in late adulthood. Carstensen\'s socioemotional selectivity theory explains that older adults focus on fewer, more meaningful relationships and positive emotional experience. Cognitively, processing speed and some fluid abilities slow, but crystallized knowledge stays stable, and severe decline is not a normal part of aging.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: socioemotional selectivity theory; fluid vs crystallized intelligence' }],
  },

  // ── self-injury ───────────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-211',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'medium',
    stem: 'A high school teacher tells the school counselor that a 15-year-old in her class has cuts on her arm. The teacher says, "She is just doing it for attention, so I plan to ignore it so I don\'t reward it." How should the counselor BEST respond to the teacher?',
    options: [
      { id: 'a', text: 'Agree that ignoring it is wise, since attention can reinforce cutting', isCorrect: false, rationale: 'Ignoring self-injury leaves the student without assessment or help and rests on a common myth about its purpose.' },
      { id: 'b', text: 'Explain cutting usually eases distress, and arrange to see the student', isCorrect: true, rationale: 'Self-injury most often regulates painful emotion, and the student needs a prompt, calm assessment that includes suicide risk.' },
      { id: 'c', text: 'Ask the teacher to tell the student to stop and to check her arms daily', isCorrect: false, rationale: 'Demands and body checks by staff tend to increase shame and secrecy and are not a substitute for assessment.' },
      { id: 'd', text: 'Suggest the teacher discuss self-injury with the whole class that day', isCorrect: false, rationale: 'Class discussion of self-injury can spread it through social contagion and exposes the student.' },
    ],
    rationale: 'Nonsuicidal self-injury is most often used privately to relieve intense negative emotion, not to gain attention. Even when it is not suicidal, it is a risk factor for later suicide attempts, so any student who self-injures needs an assessment that includes suicide risk. Counselors consult with staff to replace the "attention" myth with a calm, supportive referral pathway.',
    references: [{ source: 'DSM-5-TR', detail: 'Conditions for Further Study: Nonsuicidal self-injury disorder (functions and course)' }, { source: 'Linehan (DBT Skills Training Manual)', detail: 'Self-harm as an emotion-regulation behavior' }],
  },
  {
    id: 'nce-s-clf-212',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'medium',
    stem: 'A 16-year-old has cut herself repeatedly for a year and has made one suicide attempt. She has intense mood swings and frequent conflict with her parents. Which treatment approach has the STRONGEST research support for reducing self-harm in adolescents like her?',
    options: [
      { id: 'a', text: 'Dialectical behavior therapy adapted for teens, with family skills work', isCorrect: true, rationale: 'DBT for adolescents, which includes caregivers in skills training, has randomized trial support for reducing self-harm.' },
      { id: 'b', text: 'Client-centered therapy offered weekly in a supportive, open format', isCorrect: false, rationale: 'Supportive therapy builds rapport but has weaker evidence than DBT-A for reducing repeated self-harm.' },
      { id: 'c', text: 'Psychoeducation for her parents alone, with no individual sessions', isCorrect: false, rationale: 'Parent education helps but cannot replace skills training and individual treatment for a high-risk teen.' },
      { id: 'd', text: 'A peer support group where members discuss their self-harm stories', isCorrect: false, rationale: 'Groups that focus on sharing self-harm can increase contagion and are not an evidence-based first choice.' },
    ],
    rationale: 'Dialectical behavior therapy for adolescents (DBT-A) combines individual therapy, multifamily skills groups (mindfulness, distress tolerance, emotion regulation, interpersonal effectiveness, and walking the middle path), phone coaching and team consultation. Randomized trials show it reduces self-harm and suicide attempts in adolescents with repeated self-harm.',
    references: [{ source: 'Linehan (DBT Skills Training Manual)', detail: 'DBT skills modules; adaptation for adolescents and families' }],
    reviewNote: 'DBT-A trial evidence (Mehlum et al., 2014; McCauley et al., 2018) is not in the approved source list; SME to confirm the Linehan locator covers the adolescent adaptation.',
  },

  // ── sleep-wake concerns ──────────────────────────────────────────────────
  {
    id: 'nce-s-clf-213',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'sleep-wake concerns',
    difficulty: 'medium',
    stem: 'A 76-year-old widow goes to bed at 8 p.m., lies awake for hours, naps twice a day, and gets up at 7 a.m. feeling unrested. She asks the counselor whether she should ask her doctor for a sleeping pill. Which recommendation is MOST appropriate?',
    options: [
      { id: 'a', text: 'A sleeping pill, since medication works best for insomnia in later life', isCorrect: false, rationale: 'Sedative-hypnotics raise the risk of falls, confusion and dependence in older adults and are not first-line.' },
      { id: 'b', text: 'More time in bed and longer naps so that she can catch up on lost sleep', isCorrect: false, rationale: 'Extra time in bed and naps weaken sleep drive and fragment night sleep further.' },
      { id: 'c', text: 'CBT for insomnia, including less time in bed and fewer daytime naps', isCorrect: true, rationale: 'CBT-I is first-line for chronic insomnia at any age; limiting time in bed and naps builds sleep drive and consolidates sleep.' },
      { id: 'd', text: 'Acceptance that broken sleep is normal aging and needs no treatment', isCorrect: false, rationale: 'Sleep becomes lighter with age, but distressing insomnia with daytime effects is treatable and should not be dismissed.' },
    ],
    rationale: 'Cognitive behavioral therapy for insomnia is the recommended first-line treatment for chronic insomnia, including in older adults. Sleep restriction (or the gentler sleep compression) matches time in bed to actual sleep, and limiting naps strengthens sleep drive. Hypnotic medications carry added risks of falls and cognitive effects in later life.',
    references: [{ source: 'AASM Clinical Practice Guideline (Insomnia)', detail: 'CBT-I and sleep restriction therapy for chronic insomnia (strong recommendation)' }],
  },
  {
    id: 'nce-s-clf-214',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'sleep-wake concerns',
    difficulty: 'easy',
    stem: 'A factory worker was moved to a permanent overnight shift six months ago. He cannot stay asleep when he goes to bed at 9 a.m. and fights to stay awake at work around 4 a.m. His sleep was normal on his old day schedule. Which DSM-5-TR diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Hypersomnolence disorder', isCorrect: false, rationale: 'Hypersomnolence involves excess sleepiness despite adequate main sleep, not a mismatch with a work schedule.' },
      { id: 'b', text: 'Insomnia disorder', isCorrect: false, rationale: 'His sleep loss is explained by a circadian mismatch with his shift, which a circadian diagnosis better captures.' },
      { id: 'c', text: 'Delayed sleep phase type', isCorrect: false, rationale: 'Delayed sleep phase is a late internal clock, not a problem caused by night-shift work.' },
      { id: 'd', text: 'Circadian disorder, shift work type', isCorrect: true, rationale: 'Insomnia during the sleep period and sleepiness during work, tied to a night-shift schedule, defines shift work type.' },
    ],
    rationale: 'Circadian rhythm sleep-wake disorder, shift work type, involves insomnia during the major sleep period and/or excessive sleepiness during the major awake period, associated with a shift work schedule such as night work. Counseling supports sleep scheduling, light management and protecting daytime sleep.',
    references: [{ source: 'DSM-5-TR', detail: 'Circadian Rhythm Sleep-Wake Disorders: shift work type' }],
  },

  // ── school and academic concerns ─────────────────────────────────────────
  {
    id: 'nce-s-clf-215',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'school and academic concerns',
    difficulty: 'medium',
    stem: 'A new principal asks the high school counselor to serve as the full-time state testing coordinator and to handle discipline for tardy students. The counselor is concerned that these duties will leave little time for students. Which response BEST reflects the ASCA National Model?',
    options: [
      { id: 'a', text: 'Accept both duties, since the principal sets the counselor\'s role', isCorrect: false, rationale: 'The ASCA model expects counselors to advocate for an appropriate role rather than simply absorb noncounseling duties.' },
      { id: 'b', text: 'Use data on student needs to propose shifting noncounseling duties', isCorrect: true, rationale: 'The model calls for using data and an annual agreement with the principal to keep most time on direct and indirect student services.' },
      { id: 'c', text: 'Refuse both duties and file a complaint with the district office', isCorrect: false, rationale: 'Refusal and escalation damage collaboration; the model favors data-based advocacy with the principal first.' },
      { id: 'd', text: 'Take on discipline only, since it gives contact with at-risk students', isCorrect: false, rationale: 'ASCA lists handling discipline as inappropriate for counselors because it conflicts with the helping role.' },
    ],
    rationale: 'The ASCA National Model recommends that school counselors spend about 80% of their time in direct and indirect services to students. Coordinating schoolwide testing and administering discipline are listed as inappropriate duties. Counselors use data and an annual administrative conference to advocate for a role focused on academic, career and social/emotional development.',
    references: [{ source: 'ASCA National Model', detail: 'Appropriate vs inappropriate activities for school counselors' }, { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: the ASCA National Model' }],
  },
  {
    id: 'nce-s-clf-216',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'school and academic concerns',
    difficulty: 'easy',
    stem: 'An 11th grader studies hard and knows the material, but during exams her heart pounds, her mind goes blank, and she thinks, "If I fail this, my future is over." Her grades are dropping. Which intervention should the school counselor offer FIRST?',
    options: [
      { id: 'a', text: 'Relaxation training plus work on her catastrophic test thoughts', isCorrect: true, rationale: 'Test anxiety responds well to combined arousal-reduction and cognitive restructuring, which target both parts of her reaction.' },
      { id: 'b', text: 'A referral for psychoeducational testing for a learning disability', isCorrect: false, rationale: 'She knows the material; the pattern points to anxiety during tests, not a learning disability.' },
      { id: 'c', text: 'More hours of studying each night so she feels better prepared', isCorrect: false, rationale: 'She is already prepared; more study does not address the anxiety that blocks retrieval.' },
      { id: 'd', text: 'A request to excuse her from exams for the rest of the semester', isCorrect: false, rationale: 'Avoidance maintains anxiety and does not build the skills she needs.' },
    ],
    rationale: 'Test anxiety has physiological (arousal), cognitive (worry and catastrophic thinking) and behavioral parts. Cognitive behavioral approaches that combine relaxation or systematic desensitization with cognitive restructuring, plus test-taking skills when needed, are well supported. Avoidance tends to strengthen the anxiety.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: test anxiety interventions' }, { source: 'Corey (Theory & Practice)', detail: 'Cognitive behavior therapy: relaxation training and cognitive restructuring' }],
  },
  {
    id: 'nce-s-clf-217',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'school and academic concerns',
    difficulty: 'medium',
    stem: 'A 9-year-old in a gifted program reads at a high school level and debates ethics with adults, yet melts down when he loses a board game and struggles to make friends his age. His parents ask how he can be "so mature and so immature." Which concept BEST explains this?',
    options: [
      { id: 'a', text: 'A twice-exceptional profile that signals a hidden learning disability', isCorrect: false, rationale: 'Twice-exceptional means giftedness with a disability; nothing here indicates a disability.' },
      { id: 'b', text: 'Emotional immaturity caused by too much praise for his intellect', isCorrect: false, rationale: 'This blames parenting without evidence; uneven development is common in gifted children.' },
      { id: 'c', text: 'Asynchronous development across his intellectual and social growth', isCorrect: true, rationale: 'Gifted children often develop unevenly, with intellect far ahead of social and emotional skills that match their age.' },
      { id: 'd', text: 'Early signs of a disruptive mood dysregulation disorder pattern', isCorrect: false, rationale: 'DMDD requires severe, frequent outbursts and persistent irritability across settings; this is not described.' },
    ],
    rationale: 'Asynchronous development means a gifted child\'s intellectual abilities run well ahead of social, emotional or physical development. This uneven profile can produce frustration, perfectionism and difficulty finding peers. Counselors normalize the pattern for families, support social-emotional skills, and help the child find intellectual peers.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Middle childhood: giftedness, creativity and talent' }],
    reviewNote: 'The term "asynchronous development" comes from gifted-education literature (Columbus Group; Silverman); SME to confirm Berk covers it or swap the reference.',
  },

  // ── career and vocational concerns ───────────────────────────────────────
  {
    id: 'nce-s-clf-218',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 29-year-old Army veteran led a 12-person logistics team for six years. Applying for civilian jobs, his resume lists military job codes and unit titles, and he has had no interviews. He says, "Nobody out here values what I did." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Steer him toward entry-level roles until he gains civilian work history', isCorrect: false, rationale: 'This undervalues his experience and could lead to underemployment.' },
      { id: 'b', text: 'Give an interest inventory to find a field unrelated to his service', isCorrect: false, rationale: 'His issue is translating proven skills, not a lack of known interests.' },
      { id: 'c', text: 'Explore his anger at civilians as a possible sign of combat trauma', isCorrect: false, rationale: 'His frustration is an understandable response to rejection; nothing suggests a trauma reaction.' },
      { id: 'd', text: 'Help him translate his military duties into civilian skills and terms', isCorrect: true, rationale: 'Translating military roles into transferable civilian skills, using tools like the O*NET military crosswalk, is a key first step.' },
    ],
    rationale: 'Many veterans have strong leadership, logistics and technical skills that civilian employers do not recognize when described in military language. Career counselors help veterans identify transferable skills, translate job codes and titles into civilian terms (for example, with the O*NET military crosswalk), and connect with veteran employment resources.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Career counseling with special populations: transferable skills and occupational information' }],
    reviewNote: 'Veteran-specific content may not be covered directly in Sharf; SME to confirm the locator.',
  },
  {
    id: 'nce-s-clf-219',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'easy',
    stem: 'A career counselor is screening clients for a program that serves people who are underemployed. Which client BEST fits the definition of underemployment?',
    options: [
      { id: 'a', text: 'A nurse who left work by choice to care for her newborn twins', isCorrect: false, rationale: 'Leaving the labor force by choice is not underemployment.' },
      { id: 'b', text: 'An engineer stocking shelves part time who wants full-time work', isCorrect: true, rationale: 'Working part time involuntarily in a job well below his training fits underemployment.' },
      { id: 'c', text: 'A teacher on summer break who will return to her job in the fall', isCorrect: false, rationale: 'A planned seasonal break from a full-time job is not underemployment.' },
      { id: 'd', text: 'A laid-off welder who has been looking for a job for six months', isCorrect: false, rationale: 'Someone without a job who is seeking work is unemployed, not underemployed.' },
    ],
    rationale: 'Underemployment describes working fewer hours than desired (involuntary part-time work) or in a job that does not use one\'s education, skills or experience. It is associated with lower well-being and job satisfaction, much as unemployment is, so counselors address both the practical job search and its emotional toll.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Adult career crises and transitions: unemployment and underemployment' }],
  },
  {
    id: 'nce-s-clf-220',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 44-year-old woman with top performance reviews has been passed over three times for vice president. Each time, a man with a similar record was chosen. She tells her counselor, "I must not be leadership material." Which counselor response is BEST?',
    options: [
      { id: 'a', text: 'Focus on assertiveness training to correct her leadership weaknesses', isCorrect: false, rationale: 'This assumes a personal deficit and ignores the strong evidence of her performance.' },
      { id: 'b', text: 'Suggest she lower her goals to match what the company is likely to offer', isCorrect: false, rationale: 'Lowering goals accepts a barrier as fixed and undermines her career self-efficacy.' },
      { id: 'c', text: 'Help her weigh structural barriers to advancement, not just self-blame', isCorrect: true, rationale: 'The pattern fits a glass ceiling; exploring systemic barriers counters self-blame and opens options for action.' },
      { id: 'd', text: 'Advise her to file a discrimination lawsuit against the firm at once', isCorrect: false, rationale: 'Legal action is her decision to make after exploring options, not the counselor\'s directive.' },
    ],
    rationale: 'The glass ceiling is an invisible barrier that limits women\'s advancement to top leadership despite qualifications. Women may internalize such barriers as personal failings. Counselors help clients recognize contextual and systemic barriers, preserve career self-efficacy, and consider strategies such as mentoring, sponsorship, advocacy or a move to another organization.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Career development of women: barriers to advancement' }, { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling and advocacy interventions: addressing systemic barriers' }],
  },
  {
    id: 'nce-s-clf-221',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'hard',
    stem: 'A college sophomore has clear interests in health and science but has not declared a major. She says, "I\'m bad at making big choices; I don\'t trust myself to pick right." A counselor using social cognitive career theory wants to build her career decision self-efficacy. Which strategy would be MOST powerful?',
    options: [
      { id: 'a', text: 'Hand her more printed details on each major so she can study them', isCorrect: false, rationale: 'She already knows her interests; more information does not build confidence in deciding.' },
      { id: 'b', text: 'Tell her firmly that she has what it takes to make a strong decision', isCorrect: false, rationale: 'Verbal persuasion is a weaker source of self-efficacy than direct success experiences.' },
      { id: 'c', text: 'Have her watch peers describe how they each chose their own majors', isCorrect: false, rationale: 'Vicarious learning helps, but it is less powerful than her own successes.' },
      { id: 'd', text: 'Set graded decision tasks she can complete and succeed at herself', isCorrect: true, rationale: 'Mastery experiences, personal success at the task, are the strongest source of self-efficacy in Bandura\'s and SCCT\'s view.' },
    ],
    rationale: 'Social cognitive career theory (Lent, Brown and Hackett) draws on Bandura\'s four sources of self-efficacy: performance accomplishments (mastery), vicarious learning, verbal persuasion, and physiological and emotional states. Mastery experiences are the most powerful. For indecision rooted in low decision-making confidence, counselors structure small, achievable decision steps.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Social cognitive career theory: sources of self-efficacy; career decision self-efficacy' }],
  },

  // ── couples and family concerns ──────────────────────────────────────────
  {
    id: 'nce-s-clf-222',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'couples and family concerns',
    difficulty: 'medium',
    stem: 'A counselor trained in divorce mediation is helping a couple reach a parenting and property agreement. In the third session, the wife privately asks the counselor to also see her for individual therapy for depression after the divorce is final. What should the counselor do?',
    options: [
      { id: 'a', text: 'Stay in the neutral mediator role and refer her to another therapist', isCorrect: true, rationale: 'Taking one party as a therapy client would compromise mediator neutrality; a referral meets her need without a role conflict.' },
      { id: 'b', text: 'Agree, since therapy would begin only after the mediation has ended', isCorrect: false, rationale: 'Even later, the role change could appear to favor her and undermine the husband\'s trust in the agreement.' },
      { id: 'c', text: 'Begin individual sessions now so her depression does not slow progress', isCorrect: false, rationale: 'Concurrent therapy with one party creates a clear conflict of interest in mediation.' },
      { id: 'd', text: 'Ask the husband\'s permission and then see her alone if he agrees to it', isCorrect: false, rationale: 'Consent does not remove the conflict created when the mediator becomes one party\'s therapist.' },
    ],
    rationale: 'Divorce mediation is a neutral, task-focused process for reaching agreements; it is not therapy. When one party seeks a therapeutic relationship, the counselor clarifies roles and refers to avoid a conflict of interest that would compromise impartiality. The ACA Code addresses role changes and serving multiple clients whose interests may conflict.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.6.d Role Changes in the Professional Relationship; A.8 Multiple Clients' }],
  },
  {
    id: 'nce-s-clf-223',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'couples and family concerns',
    difficulty: 'easy',
    stem: 'Parents of a 13-year-old are alarmed that she now argues about clothes, chores and bedtime and rolls her eyes at their rules. She has good grades, close friends, and still talks with them about school. What should the counselor tell the parents?',
    options: [
      { id: 'a', text: 'The bickering may signal early oppositional defiant disorder', isCorrect: false, rationale: 'ODD involves a persistent, pervasive pattern of hostility; mild, everyday conflict with good functioning is not ODD.' },
      { id: 'b', text: 'Mild conflict over daily issues is common in early adolescence', isCorrect: true, rationale: 'Parent-teen conflict over everyday matters rises in early adolescence and usually reflects normal striving for autonomy.' },
      { id: 'c', text: 'Firm limits with no discussion will end the conflict quickest', isCorrect: false, rationale: 'An authoritarian style tends to escalate conflict; warmth with reasoned limits works better.' },
      { id: 'd', text: 'Letting her set her own rules will reduce tension at home', isCorrect: false, rationale: 'A permissive approach removes needed structure; teens still benefit from monitoring and clear limits.' },
    ],
    rationale: 'Parent-adolescent conflict over everyday issues typically increases in early adolescence as teens seek autonomy, and it usually declines later. Severe, constant conflict is not normal and warrants attention. Authoritative parenting, which pairs warmth with clear, explained limits and gradually expanded autonomy, is linked to the best adolescent outcomes.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Adolescence: parent-child relationships, autonomy and conflict' }],
  },
  {
    id: 'nce-s-clf-224',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'couples and family concerns',
    difficulty: 'medium',
    stem: 'A family lost their home and business in a wildfire. In counseling, they argue about what went wrong but also describe neighbors who helped and a shared faith that "we will rebuild." A counselor using Froma Walsh\'s family resilience framework would MOST likely focus on which task?',
    options: [
      { id: 'a', text: 'Finding the family member whose symptoms carry the family stress', isCorrect: false, rationale: 'Locating an identified patient fits other systems models, not Walsh\'s strengths-based resilience focus.' },
      { id: 'b', text: 'Tracing the family\'s patterns of fusion back over three generations', isCorrect: false, rationale: 'Multigenerational tracing is a Bowenian task, not the core of the resilience framework.' },
      { id: 'c', text: 'Strengthening shared meaning, connection and joint problem-solving', isCorrect: true, rationale: 'Walsh\'s key processes are belief systems, organizational patterns and communication/problem-solving, all built on family strengths.' },
      { id: 'd', text: 'Rearranging the family hierarchy so the parents hold firmer power', isCorrect: false, rationale: 'Restructuring hierarchy is a structural family therapy goal, not the main resilience focus.' },
    ],
    rationale: 'Walsh\'s family resilience framework views families facing adversity as challenged, not damaged. It strengthens three domains of key processes: belief systems (making meaning of adversity, a positive outlook, transcendence and spirituality), organizational patterns (flexibility, connectedness, social and economic resources) and communication/problem-solving (clarity, open emotional sharing, collaborative problem-solving).',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Family resilience (Walsh): key processes in family functioning' }],
    reviewNote: 'Walsh\'s framework is primary in Walsh (2016), Strengthening Family Resilience; SME to confirm the Goldenberg locator.',
  },

  // ── spiritual and religious concerns ─────────────────────────────────────
  {
    id: 'nce-s-clf-225',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'medium',
    stem: 'A 35-year-old client mentions that during worship at her Pentecostal church she speaks in tongues and sometimes feels the Holy Spirit move through her. She works, has close relationships, and shows no other unusual experiences. How should the counselor BEST understand these reports?',
    options: [
      { id: 'a', text: 'As possible psychotic symptoms that call for a psychiatric referral', isCorrect: false, rationale: 'Experiences accepted within the client\'s faith community, with intact functioning, are not evidence of psychosis.' },
      { id: 'b', text: 'As accepted religious practices within her own faith community', isCorrect: true, rationale: 'DSM-5-TR cautions that experiences sanctioned by a person\'s culture or religion should not be judged as symptoms.' },
      { id: 'c', text: 'As dissociative episodes that need a structured diagnostic interview', isCorrect: false, rationale: 'DSM-5-TR excludes trance states that are a normal part of broadly accepted religious practice.' },
      { id: 'd', text: 'As avoidance of her problems that should become a focus of treatment', isCorrect: false, rationale: 'Nothing suggests her faith practice is causing problems; treating it as avoidance imposes the counselor\'s values.' },
    ],
    rationale: 'Clinicians must judge unusual experiences in the context of the client\'s cultural and religious norms. Practices such as glossolalia are normative in some traditions and are not symptoms when they occur within accepted religious contexts and do not cause distress or impairment. DSM-5-TR notes that dissociative disorder diagnoses do not apply to states that are a normal part of broadly accepted cultural or religious practice.',
    references: [{ source: 'DSM-5-TR', detail: 'Cultural concepts and distinguishing culturally sanctioned experiences from psychopathology; dissociative disorders exclusion for religious practice' }, { source: 'ACA Code of Ethics', detail: 'E.5.b Cultural Sensitivity' }],
  },

  // ── chronic illness and disability ───────────────────────────────────────
  {
    id: 'nce-s-clf-226',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'chronic illness and disability',
    difficulty: 'easy',
    stem: 'A 27-year-old is referred eight months after a moderate traumatic brain injury from a car crash. He forgets what was discussed, tires quickly, and becomes irritable when sessions run long. Which adjustment to counseling is MOST appropriate?',
    options: [
      { id: 'a', text: 'Long open-ended sessions so he can explore at his own pace', isCorrect: false, rationale: 'Long, unstructured sessions tax attention and fatigue after brain injury.' },
      { id: 'b', text: 'Insight-focused talk therapy without memory aids or notes', isCorrect: false, rationale: 'Without memory supports, he is unlikely to retain or use session content.' },
      { id: 'c', text: 'Fewer sessions spaced far apart to reduce his frustration', isCorrect: false, rationale: 'Wide spacing weakens retention; short, frequent, structured sessions fit better.' },
      { id: 'd', text: 'Short, structured sessions with written summaries and aids', isCorrect: true, rationale: 'Shorter sessions, concrete structure, repetition and written notes compensate for memory and fatigue problems after TBI.' },
    ],
    rationale: 'Clients with traumatic brain injury often have deficits in memory, attention, processing speed and emotional regulation, along with fatigue. Counselors adapt by using shorter, structured sessions, repetition, written summaries and external aids, involving family when appropriate, and coordinating with rehabilitation and neuropsychology providers.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling clients with disabilities: adapting counseling to cognitive impairment' }],
  },
  {
    id: 'nce-s-clf-227',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'chronic illness and disability',
    difficulty: 'hard',
    stem: 'A 30-year-old client who was born deaf comes to counseling, with a sign language interpreter, for stress at work. She mentions proudly that she is active in the Deaf community. The counselor plans to begin by helping her grieve the loss of hearing. Why is this plan MOST problematic?',
    options: [
      { id: 'a', text: 'It imposes a loss frame on an identity she holds as cultural', isCorrect: true, rationale: 'Many culturally Deaf people view deafness as a linguistic and cultural identity, not a loss to grieve.' },
      { id: 'b', text: 'Grief work is not suitable when an interpreter is in the room', isCorrect: false, rationale: 'Interpreters do not rule out any type of counseling work; the problem is the counselor\'s assumption.' },
      { id: 'c', text: 'Stage models say grief over hearing ends by early adulthood', isCorrect: false, rationale: 'No such rule exists; the issue is that she does not experience her deafness as a loss.' },
      { id: 'd', text: 'Counselors should refer deaf clients to a deaf counselor only', isCorrect: false, rationale: 'Culturally competent hearing counselors can serve Deaf clients; automatic referral is not required.' },
    ],
    rationale: 'Disability identity varies. Many people who are culturally Deaf (capital D) see themselves as members of a linguistic and cultural minority with its own language, such as ASL, rather than as people with a deficit. Applying a medical or loss model without asking the client imposes the counselor\'s worldview. Counselors explore how clients define their own identity and focus on the presenting concern.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling individuals with disabilities: disability identity and Deaf culture' }],
  },

  // ── LGBTQ+ clients and minority stress ───────────────────────────────────
  {
    id: 'nce-s-clf-228',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'medium',
    stem: 'A 72-year-old transgender woman who transitioned in her forties must move into assisted living after a stroke. She says, "I fought my whole life to be myself. I\'m terrified the staff will misgender me or that I\'ll have to hide again." Which counselor response is BEST?',
    options: [
      { id: 'a', text: 'Reassure her that staff are trained, so her worries are probably unfounded', isCorrect: false, rationale: 'Her fears reflect real risks documented for LGBTQ+ older adults; dismissing them invalidates her.' },
      { id: 'b', text: 'Suggest she keep her history private until she knows the staff better', isCorrect: false, rationale: 'Advising concealment adds to minority stress and puts the burden of others\' bias on her.' },
      { id: 'c', text: 'Explore her fears and help her find and advocate for affirming facilities', isCorrect: true, rationale: 'Validating her fears and helping her identify affirming care and supports addresses both her distress and real barriers.' },
      { id: 'd', text: 'Focus on her stroke recovery, since gender identity is a settled matter', isCorrect: false, rationale: 'Her identity is settled, but her safety and dignity in care are urgent present concerns.' },
    ],
    rationale: 'Transgender older adults often carry histories of discrimination and may lack family support. Many fear mistreatment, misgendering or pressure to go back into the closet in long-term care. Counselors validate these fears, help clients locate LGBTQ+-affirming providers and aging resources, and advocate for respectful, competent care.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling and advocacy interventions at the institutional level' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ+ individuals; counseling older adults' }],
  },
  {
    id: 'nce-s-clf-229',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'hard',
    stem: 'A 26-year-old bisexual man in a relationship with a woman says his family calls his bisexuality "a phase," while gay friends tell him he is "really straight now." He feels he belongs nowhere. Which concept BEST describes this source of minority stress?',
    options: [
      { id: 'a', text: 'Internalized homonegativity that he holds about his own identity', isCorrect: false, rationale: 'Internalized stigma is a self-directed belief; here the invalidation comes from others.' },
      { id: 'b', text: 'Bisexual erasure from both straight and gay communities', isCorrect: true, rationale: 'Bisexual people often face invalidation from both heterosexual and gay or lesbian communities, sometimes called double discrimination.' },
      { id: 'c', text: 'Identity confusion, the first stage of Cass\'s identity model', isCorrect: false, rationale: 'Cass describes stages of gay and lesbian identity; it does not capture rejection from two communities.' },
      { id: 'd', text: 'Heterosexual privilege that protects him from any minority stress', isCorrect: false, rationale: 'Being in a different-gender relationship does not remove the stigma and invisibility bisexual people face.' },
    ],
    rationale: 'Bisexual people experience unique minority stressors, including bisexual erasure (denial that bisexuality is real or lasting) and binegativity from both heterosexual and gay or lesbian communities. This double marginalization can limit community support and is linked to higher rates of depression and anxiety than among gay and lesbian peers.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ+ individuals: bisexual invisibility and double discrimination' }],
    reviewNote: 'Confirm the Sue & Sue chapter discusses bisexual erasure/binegativity and double discrimination.',
  },

  // ── acculturation and immigration stress ─────────────────────────────────
  {
    id: 'nce-s-clf-230',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'hard',
    stem: 'A 38-year-old woman who entered the country without documentation seeks counseling for panic, poor sleep and constant fear that she will be separated from her children. At intake she hesitates and asks, "Will you tell anyone about my status?" What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Explain confidentiality and its limits, which do not include her status', isCorrect: true, rationale: 'Immigration status is not a mandated reporting category; explaining confidentiality and its true limits builds the safety she needs.' },
      { id: 'b', text: 'Record her status in detail so that the clinical file is fully complete', isCorrect: false, rationale: 'Counselors record what is clinically needed; detailed status notes add risk without clinical benefit.' },
      { id: 'c', text: 'Refer her to an immigration attorney before beginning counseling work', isCorrect: false, rationale: 'Legal referral may help later, but her immediate question is about confidentiality and her panic needs care.' },
      { id: 'd', text: 'Tell her you cannot discuss her legal status because of agency policy', isCorrect: false, rationale: 'Deflecting her question deepens fear and mistrust; she needs a clear answer about confidentiality.' },
    ],
    rationale: 'Undocumented clients live with chronic fear of detention and family separation, which can cause anxiety, depression and trauma symptoms. Fear of disclosure is a major barrier to care. Counselors clearly explain confidentiality and its actual limits (such as risk of harm or child abuse), note that immigration status is not a reportable matter, and document only what is clinically necessary.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.1.d Explanation of Limitations; A.2.b Types of Information Needed' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling immigrants and refugees: undocumented status and fear of disclosure' }],
    reviewNote: 'No general mandate requires counselors to report immigration status, but some funded programs or states may have specific rules; SME to confirm the general framing.',
  },
  {
    id: 'nce-s-clf-231',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'medium',
    stem: 'A 58-year-old woman who immigrated from rural China two years ago is brought in by her daughter. She reports headaches, fatigue and poor appetite, says her doctor found nothing wrong, and insists, "I am not crazy. I do not need to talk about feelings." Which approach is BEST?',
    options: [
      { id: 'a', text: 'Explain that her physical symptoms are really depression in disguise', isCorrect: false, rationale: 'Relabeling her experience early challenges her worldview and is likely to end engagement.' },
      { id: 'b', text: 'Ask her daughter to describe her mother\'s emotions on her behalf', isCorrect: false, rationale: 'This sidelines the client and may breach her preferences about what is shared within the family.' },
      { id: 'c', text: 'Tell her counseling can begin only once she accepts a diagnosis', isCorrect: false, rationale: 'Requiring acceptance of a diagnosis is a barrier and does not fit her cultural view of help-seeking.' },
      { id: 'd', text: 'Respect her view of the symptoms and offer practical, active help', isCorrect: true, rationale: 'Starting with her own framing and offering concrete, problem-focused help builds credibility with less acculturated clients.' },
    ],
    rationale: 'Less acculturated clients from many cultures underuse counseling, may express distress through somatic complaints, and may see emotional talk as stigmatizing. Sue and Sue describe culturally responsive engagement: accept the client\'s explanation of the problem, coordinate with medical care, and offer active, structured, practical help. An early, felt benefit (what Sue and Sue call gift giving) builds the counselor\'s credibility.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Asian Americans: somatic expression of distress; credibility and gift giving' }],
  },

  // ── psychopharmacology basics for counselors ─────────────────────────────
  {
    id: 'nce-s-clf-232',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'easy',
    stem: 'A client with schizophrenia has gained 25 pounds in the six months since starting a second-generation antipsychotic. He says he feels constantly hungry and is thinking of stopping the medication. What should the counselor do?',
    options: [
      { id: 'a', text: 'Support his plan to stop, since the weight gain is a serious problem', isCorrect: false, rationale: 'Stopping an antipsychotic abruptly risks relapse; medication changes belong to the prescriber.' },
      { id: 'b', text: 'Reassure him that the weight gain is cosmetic and will soon level off', isCorrect: false, rationale: 'Weight gain on these drugs signals metabolic risk and is not merely cosmetic.' },
      { id: 'c', text: 'Urge him to talk to his prescriber about the gain and metabolic checks', isCorrect: true, rationale: 'Second-generation antipsychotics carry metabolic risks, and prescribers monitor weight, glucose and lipids and can adjust treatment.' },
      { id: 'd', text: 'Recommend a specific medication change that has fewer side effects', isCorrect: false, rationale: 'Recommending specific drugs is outside the counselor\'s scope of practice.' },
    ],
    rationale: 'Several second-generation antipsychotics, notably olanzapine and clozapine, are associated with weight gain, insulin resistance, diabetes and lipid changes. Guidelines call for monitoring weight, waist size, blood pressure, glucose and lipids. Counselors recognize these concerns, encourage clients to raise them with the prescriber rather than stop medication, and support healthy lifestyle changes.',
    references: [{ source: 'APA CPG', detail: 'Treatment of patients with schizophrenia (2020): monitoring for metabolic side effects of antipsychotics' }],
  },
  {
    id: 'nce-s-clf-233',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'hard',
    stem: 'A father tells the counselor, "We gave our son a dose of his cousin\'s ADHD stimulant before a test, and he focused much better. So he must have ADHD, right?" Which response reflects an accurate understanding of stimulant medication?',
    options: [
      { id: 'a', text: 'Stimulants can sharpen focus in most people, so a response is not a diagnosis', isCorrect: true, rationale: 'Stimulants improve attention in people with and without ADHD, so a good response cannot confirm the diagnosis.' },
      { id: 'b', text: 'A calming effect from a stimulant is a reliable sign that ADHD is present', isCorrect: false, rationale: 'The idea of a "paradoxical" response unique to ADHD is a myth; stimulants act similarly in those without ADHD.' },
      { id: 'c', text: 'Because stimulants are addictive, a good response is a sign of misuse risk', isCorrect: false, rationale: 'One positive response does not indicate misuse risk; the issue is that response is not diagnostic.' },
      { id: 'd', text: 'A good response confirms ADHD only if the effect lasts more than a week', isCorrect: false, rationale: 'Duration of response does not make it diagnostic; ADHD is diagnosed by DSM-5-TR criteria and history.' },
    ],
    rationale: 'A common misconception holds that stimulants calm or focus only people with ADHD. In fact, stimulants improve attention and concentration in most people, so response to medication cannot establish a diagnosis. ADHD is diagnosed through a careful history and DSM-5-TR criteria across settings. The counselor should also address the safety concern of giving a child someone else\'s prescription.',
    references: [{ source: 'DSM-5-TR', detail: 'Attention-deficit/hyperactivity disorder: diagnostic criteria and differential diagnosis' }, { source: 'NBCC Study Supplement', detail: 'Psychopharmacology: stimulant medications' }],
    reviewNote: 'The fact (non-specific stimulant response; Rapoport et al., 1978) is well established, but neither cited source states it directly; SME to confirm or substitute a pharmacology reference.',
  },

  // ── military and veteran populations ─────────────────────────────────────
  {
    id: 'nce-s-clf-234',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'military and veteran populations',
    difficulty: 'hard',
    stem: 'A veteran completed prolonged exposure for PTSD. His fear when recalling a roadside ambush has dropped sharply, yet he still feels intense shame that he froze and a friend died, says he "doesn\'t deserve" good things, and avoids his family. What should the counselor focus on NEXT?',
    options: [
      { id: 'a', text: 'Repeat a full course of exposure, since fear must still be driving him', isCorrect: false, rationale: 'His fear has already habituated; repeating exposure does not target the guilt and shame that remain.' },
      { id: 'b', text: 'Address guilt and shame through meaning-making and self-forgiveness', isCorrect: true, rationale: 'Moral injury centers on guilt, shame and broken meaning, which call for work on appraisals, meaning and self-forgiveness.' },
      { id: 'c', text: 'Reassure him that freezing was not his fault and move toward ending', isCorrect: false, rationale: 'Quick reassurance rarely shifts deep guilt and leaves the moral-injury symptoms untreated.' },
      { id: 'd', text: 'Refer him for a medication to reduce his remaining startle response', isCorrect: false, rationale: 'His remaining problems are guilt, shame and withdrawal, not hyperarousal.' },
    ],
    rationale: 'Moral injury describes lasting guilt, shame and loss of meaning after acts that violate one\'s moral code, including perceived failures to act. Fear-based exposure can reduce fear without resolving these reactions. Treatment adds work on guilt appraisals (as in cognitive processing therapy), meaning-making, self-forgiveness and repair (as in approaches such as adaptive disclosure), often with spiritual or community resources.',
    references: [{ source: 'VA/DoD CPG', detail: 'Management of PTSD and acute stress disorder: trauma-focused psychotherapies (PE, CPT)' }],
    reviewNote: 'Moral injury is not a formal diagnosis and the VA/DoD CPG does not specifically address it; SME to confirm the citation or add a moral-injury source (e.g., Litz et al., Adaptive Disclosure).',
  },
  {
    id: 'nce-s-clf-235',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'military and veteran populations',
    difficulty: 'easy',
    stem: 'A 42-year-old retired Navy chief landed a well-paid civilian job after 20 years of service. Six months in, he says, "The work is fine, but I feel pointless. Nobody has each other\'s back here, and nothing feels urgent." What is the counselor\'s BEST initial focus?',
    options: [
      { id: 'a', text: 'Help him find a higher-paying job with greater responsibility', isCorrect: false, rationale: 'Pay and rank are not his concern; he describes loss of purpose and belonging.' },
      { id: 'b', text: 'Screen him for PTSD, since his distress began after service', isCorrect: false, rationale: 'Nothing he describes suggests trauma symptoms; his concern is transition-related.' },
      { id: 'c', text: 'Teach him to adopt a civilian mindset and leave the Navy behind', isCorrect: false, rationale: 'Dismissing his military identity ignores a valued part of who he is.' },
      { id: 'd', text: 'Explore his loss of military identity, mission and camaraderie', isCorrect: true, rationale: 'Leaving the military often means losing identity, purpose and close bonds, which are central transition tasks.' },
    ],
    rationale: 'Military-to-civilian transition involves more than finding a job. Veterans often lose a strong shared identity, a clear mission, structure and unit cohesion. Counselors explore these losses, help the veteran carry valued military strengths into civilian life, and support sources of purpose and belonging such as veteran organizations and service roles.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Adult career transitions; Schlossberg\'s model applied to job and role change' }],
    reviewNote: 'Veteran transition content may not appear in Sharf specifically; SME to confirm the locator.',
  },

  // ── child abuse and neglect ──────────────────────────────────────────────
  {
    id: 'nce-s-clf-236',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'child abuse and neglect',
    difficulty: 'hard',
    stem: 'An 8-year-old from a low-income family has had a painful, untreated dental abscess for months and cannot see the board without glasses. The school nurse has arranged free dental care and free glasses three times, and the parent has not followed through. Which detail MOST supports a concern of neglect rather than poverty alone?',
    options: [
      { id: 'a', text: 'The family\'s low income and lack of dental insurance coverage', isCorrect: false, rationale: 'Lack of resources alone is not neglect; poverty must be separated from failure to provide care.' },
      { id: 'b', text: 'The child\'s trouble seeing the board in her daily classroom work', isCorrect: false, rationale: 'This shows an unmet need but does not show why the need is unmet.' },
      { id: 'c', text: 'Repeated failure to use free care that was arranged for the child', isCorrect: true, rationale: 'When accessible care is offered and still not used for a serious need, the failure points to neglect rather than lack of means.' },
      { id: 'd', text: 'The length of time the abscess has gone without any treatment', isCorrect: false, rationale: 'Duration shows severity, but on its own could still reflect lack of access.' },
    ],
    rationale: 'Neglect is a failure to meet a child\'s basic needs, including medical and dental care, when the caregiver is able or has been offered reasonable means to do so. Many state definitions exclude conditions caused solely by poverty. Indicators include untreated medical or dental problems, chronic hunger, poor hygiene and frequent absence. Repeated refusal of accessible care for a serious need supports reasonable suspicion and a report.',
    references: [{ source: 'State law', detail: 'Child abuse and neglect statutes: definitions of neglect and poverty exclusions' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
];
