// tools/nce/seed/clinical-focus-7.js
// NCE seed items — Areas of Clinical Focus, blueprint topics 1–14 (batch 4).
// New angles that do not repeat clinical-focus-1.js, -3.js or -5.js:
// behavioral-variant frontotemporal NCD, the mild/major functional threshold,
// dementia caregiver guidance, hoarding treatment, BDD insight and cosmetic
// procedures, tic-related OCD, specific learning disorder, adaptive domains,
// ADHD presentations, negative symptoms, catatonia, expressed emotion,
// histrionic, avoidant PD vs social anxiety, the BPD treatment frame, BED
// treatment, atypical anorexia (OSFED), family-based treatment, atypical
// features, IPSRT, blood-injection-injury phobia, the dissociative subtype,
// MOUD, continuing bonds, the six-step crisis model, strangulation as a
// lethality marker, global developmental delay, early remission,
// performance-only social anxiety, and PTSD in young children.
module.exports = [
  // ── neurocognitive disorders ────────────────────────────────────────────
  {
    id: 'nce-s-clf-178',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'hard',
    stem: 'Over 2 years, a 57-year-old engineer has made crude remarks to strangers, lost interest in his grandchildren, shown little concern when his wife cries, and begun eating sweets compulsively. He still recalls recent events and finds his way around town without trouble. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Major neurocognitive disorder due to Alzheimer\'s disease', isCorrect: false, rationale: 'Alzheimer\'s disease typically begins with prominent decline in learning and memory, which is relatively spared here.' },
      { id: 'b', text: 'Major neurocognitive disorder with Lewy bodies, early stage', isCorrect: false, rationale: 'Lewy body NCD features fluctuating cognition, recurrent visual hallucinations, and parkinsonism, none of which are described.' },
      { id: 'c', text: 'Frontotemporal neurocognitive disorder, behavioral variant', isCorrect: true, rationale: 'Disinhibition, apathy, loss of empathy, and hyperorality with relatively spared memory and spatial skills fit the behavioral variant.' },
      { id: 'd', text: 'Bipolar I disorder, current episode manic, late onset', isCorrect: false, rationale: 'There is no elevated mood, decreased need for sleep, or episodic course; the change is gradual and progressive.' },
    ],
    rationale: 'The behavioral variant of frontotemporal neurocognitive disorder requires three or more of: behavioral disinhibition; apathy or inertia; loss of sympathy or empathy; perseverative, stereotyped, or compulsive behavior; and hyperorality or dietary change, along with prominent decline in social cognition or executive abilities. Learning, memory, and perceptual-motor function are relatively spared. Onset is often in midlife, so the presentation is easily mistaken for a psychiatric or "midlife" problem.',
    references: [{ source: 'DSM-5-TR', detail: 'Major or Mild Frontotemporal Neurocognitive Disorder, Criterion C1 (behavioral variant)' }],
  },
  {
    id: 'nce-s-clf-179',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'easy',
    stem: 'A 79-year-old with a known neurocognitive disorder now relies on her son to pay her bills and set out her daily medications because she makes repeated errors on her own. Under DSM-5-TR, what does this change MOST directly indicate?',
    options: [
      { id: 'a', text: 'Deficits now interfere with independence, so major NCD fits', isCorrect: true, rationale: 'Needing help with complex instrumental activities such as bills and medications marks the functional threshold for major NCD.' },
      { id: 'b', text: 'A delirium is now present on top of her existing disorder', isCorrect: false, rationale: 'Delirium is an acute, fluctuating disturbance in attention and awareness, which is not described.' },
      { id: 'c', text: 'Her cognitive test scores must now fall in the severe range', isCorrect: false, rationale: 'The mild/major distinction rests mainly on functional independence, not on a single test cutoff.' },
      { id: 'd', text: 'The cause of her disorder must have shifted to vascular', isCorrect: false, rationale: 'A change in functional level says nothing about a change in etiological subtype.' },
    ],
    rationale: 'DSM-5-TR separates mild from major neurocognitive disorder chiefly by function. In mild NCD the deficits do not interfere with independence in everyday activities, although greater effort or compensatory strategies may be needed. In major NCD they do, at minimum requiring assistance with complex instrumental activities such as paying bills or managing medications.',
    references: [{ source: 'DSM-5-TR', detail: 'Major Neurocognitive Disorder, Criterion B; Mild Neurocognitive Disorder, Criterion B' }],
  },
  {
    id: 'nce-s-clf-180',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'neurocognitive disorders',
    difficulty: 'medium',
    stem: 'A daughter caring for her father with moderate Alzheimer\'s disease says he asks several times each evening where his late wife is. Each time she reminds him that her mother died, he sobs as if hearing it for the first time. Which guidance should the counselor offer?',
    options: [
      { id: 'a', text: 'Keep reminding him of the death so that the fact is gradually relearned', isCorrect: false, rationale: 'Repeated reorientation to a painful fact he cannot retain causes fresh grief each time without lasting learning.' },
      { id: 'b', text: 'Ask his physician to raise his sedative dose for the evening hours', isCorrect: false, rationale: 'Medication is not the first response to distress that can be eased by changing how caregivers respond.' },
      { id: 'c', text: 'Avoid the subject entirely and leave the room whenever he raises it', isCorrect: false, rationale: 'Withdrawing leaves him alone with distress and does not meet the emotional need behind the question.' },
      { id: 'd', text: 'Respond to the feeling behind the question, then gently redirect him', isCorrect: true, rationale: 'Acknowledging the emotion (for example, that he misses her) and redirecting reduces distress without repeated re-traumatizing news.' },
    ],
    rationale: 'In moderate dementia, a person often cannot retain new information, so repeated correction brings repeated fresh grief. Caregivers are usually taught to respond to the emotion behind a question, offer comfort, and redirect to a soothing activity. Counselors also support caregivers with psychoeducation, skills training, and attention to their own strain, as dementia guidelines recommend.',
    references: [
      { source: 'NICE guidelines', detail: 'NG97 Dementia: supporting carers (psychoeducation and skills training)' },
      { source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: Alzheimer\'s disease and caregiving' },
    ],
    reviewNote: 'Validation-and-redirect is standard caregiver teaching rather than a quoted NICE recommendation; SME to confirm locators.',
  },
  // ── obsessive-compulsive and related disorders ──────────────────────────
  {
    id: 'nce-s-clf-181',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'medium',
    stem: 'A 63-year-old with hoarding disorder faces eviction because her apartment is blocked by stacked items. Her landlord has offered to send a crew to clear it out over one weekend. Which approach is MOST consistent with effective treatment of hoarding?',
    options: [
      { id: 'a', text: 'Support the weekend cleanout, since clearing the space ends the disorder', isCorrect: false, rationale: 'Forced cleanouts may solve an immediate crisis but are distressing and often followed by rapid reaccumulation.' },
      { id: 'b', text: 'CBT building sorting and decision skills with practice in discarding', isCorrect: true, rationale: 'CBT for hoarding targets motivation, organizing and decision-making skills, graded discarding, and reduced acquiring.' },
      { id: 'c', text: 'Insight-oriented talk about her childhood losses before any sorting', isCorrect: false, rationale: 'Exploring history alone does not change saving and acquiring behavior and delays needed work.' },
      { id: 'd', text: 'Have the counselor decide which items to discard to speed progress', isCorrect: false, rationale: 'Decisions made for the client undercut her own decision-making practice, which is central to treatment.' },
    ],
    rationale: 'Hoarding disorder involves persistent difficulty discarding possessions because of a perceived need to save them and distress at discarding, leading to clutter that compromises living areas. Cognitive-behavioral treatment for hoarding uses motivational work, skills training in organizing and decision-making, graded exposure to sorting and discarding, and practice resisting acquiring. Externally imposed cleanouts tend to be traumatic and rarely produce lasting change.',
    references: [
      { source: 'DSM-5-TR', detail: 'Hoarding Disorder: diagnostic features and functional consequences' },
      { source: 'Corey (Theory & Practice)', detail: 'Cognitive behavior therapy: skills training and exposure' },
    ],
    reviewNote: 'Hoarding-specific CBT (Steketee & Frost) is not in the approved source library; treatment content cited to general sources. SME to confirm.',
  },
  {
    id: 'nce-s-clf-182',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'hard',
    stem: 'A 27-year-old is completely certain that her nose is grotesquely misshapen, although others see nothing unusual. She checks mirrors for hours and has had two rhinoplasties, which left her more distressed. She is now seeking a third surgeon. Which conclusion is MOST accurate?',
    options: [
      { id: 'a', text: 'BDD with absent insight; more surgery is unlikely to ease her distress', isCorrect: true, rationale: 'Total conviction is coded as BDD with absent insight/delusional beliefs, and cosmetic procedures rarely relieve BDD.' },
      { id: 'b', text: 'Delusional disorder, somatic type, as her conviction is fixed and total', isCorrect: false, rationale: 'DSM-5-TR codes delusional appearance beliefs as BDD with absent insight rather than as delusional disorder.' },
      { id: 'c', text: 'BDD with good insight; a skilled surgeon will likely resolve her concern', isCorrect: false, rationale: 'Complete conviction is not good insight, and surgery typically fails to resolve or worsens BDD symptoms.' },
      { id: 'd', text: 'No disorder applies, because she has sought medical rather than mental care', isCorrect: false, rationale: 'Many people with BDD seek cosmetic rather than mental health treatment; the pattern fully meets BDD criteria.' },
    ],
    rationale: 'Body dysmorphic disorder involves preoccupation with perceived flaws not observable or slight to others, with repetitive behaviors such as mirror checking. Insight is specified as good or fair, poor, or absent insight/delusional beliefs; a person completely convinced of the flaw still receives BDD, not a psychotic diagnosis. Many people with BDD seek cosmetic procedures, which seldom improve and can worsen symptoms, so referral for CBT and medication evaluation is indicated.',
    references: [{ source: 'DSM-5-TR', detail: 'Body Dysmorphic Disorder: insight specifiers; associated features (cosmetic treatment)' }],
  },
  {
    id: 'nce-s-clf-183',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'medium',
    stem: 'A 14-year-old with OCD spends hours arranging objects and touching doorframes until things feel "just right." His parents mention that between ages 7 and 10 he had repeated eye blinking and grunting that have since stopped. Which DSM-5-TR specifier should be added to his OCD diagnosis?',
    options: [
      { id: 'a', text: 'With poor insight', isCorrect: false, rationale: 'Insight specifiers depend on his beliefs about the obsessions, which are not described.' },
      { id: 'b', text: 'With panic attacks', isCorrect: false, rationale: 'No abrupt surges of intense fear are described.' },
      { id: 'c', text: 'With absent insight', isCorrect: false, rationale: 'Nothing suggests he is fully convinced his obsessional beliefs are true.' },
      { id: 'd', text: 'Tic-related', isCorrect: true, rationale: 'The tic-related specifier applies to a current or past history of a tic disorder.' },
    ],
    rationale: 'OCD is specified as tic-related when the person has a current or past history of a tic disorder. Tic-related OCD is more common in males with childhood onset and often involves symmetry, ordering, and "just right" concerns rather than harm or contamination themes. Past tics count, so a careful developmental history matters.',
    references: [{ source: 'DSM-5-TR', detail: 'Obsessive-Compulsive Disorder: specify if tic-related' }],
  },
  // ── neurodevelopmental disorders ────────────────────────────────────────
  {
    id: 'nce-s-clf-184',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurodevelopmental disorders',
    difficulty: 'hard',
    stem: 'A 9-year-old with average intellectual ability reads slowly and makes many decoding errors. A school team is considering specific learning disorder with impairment in reading. Under DSM-5-TR, which requirement must be met?',
    options: [
      { id: 'a', text: 'A large gap between full-scale IQ and reading achievement scores', isCorrect: false, rationale: 'DSM-5 dropped the IQ-achievement discrepancy requirement; skills must instead be well below age expectations.' },
      { id: 'b', text: 'Difficulty persisting 6 months despite help aimed at that skill', isCorrect: true, rationale: 'Criterion A requires difficulties persisting at least 6 months despite interventions that target them.' },
      { id: 'c', text: 'A formal diagnosis made only after the child reaches age 12', isCorrect: false, rationale: 'Specific learning disorder is typically identified in the early school years; there is no age 12 threshold.' },
      { id: 'd', text: 'Proof that the difficulty also appears in mathematics and writing', isCorrect: false, rationale: 'Impairment may involve one domain only; reading, written expression, and mathematics are specified separately.' },
    ],
    rationale: 'DSM-5-TR requires difficulties learning and using academic skills that have persisted for at least 6 months despite targeted intervention, with skills substantially and quantifiably below those expected for age (confirmed by standardized achievement measures and comprehensive clinical assessment). Onset is in the school-age years, and the difficulties are not better explained by intellectual disability, sensory problems, or inadequate instruction. The older IQ-achievement discrepancy model is no longer required.',
    references: [{ source: 'DSM-5-TR', detail: 'Specific Learning Disorder, Criteria A and B' }],
  },
  {
    id: 'nce-s-clf-185',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'neurodevelopmental disorders',
    difficulty: 'easy',
    stem: 'In DSM-5-TR, deficits in adaptive functioning for intellectual developmental disorder are assessed in which three domains?',
    options: [
      { id: 'a', text: 'Verbal, perceptual, and processing speed', isCorrect: false, rationale: 'These resemble index scores from intelligence tests, not adaptive functioning domains.' },
      { id: 'b', text: 'Sensory, motor, and expressive language', isCorrect: false, rationale: 'These are developmental skill areas, not the three DSM-5-TR adaptive domains.' },
      { id: 'c', text: 'Conceptual, social, and practical', isCorrect: true, rationale: 'DSM-5-TR assesses adaptive functioning in the conceptual, social, and practical domains.' },
      { id: 'd', text: 'Cognitive, emotional, and behavioral', isCorrect: false, rationale: 'This is a general psychological triad, not the DSM-5-TR adaptive framework.' },
    ],
    rationale: 'Intellectual developmental disorder requires deficits in intellectual functions and in adaptive functioning, with onset during the developmental period. Adaptive functioning covers the conceptual (academic), social, and practical (self-management) domains. Severity is set by adaptive functioning in these domains rather than by IQ alone, because adaptive functioning determines the level of support needed.',
    references: [{ source: 'DSM-5-TR', detail: 'Intellectual Developmental Disorder, Criterion B and severity table' }],
  },
  {
    id: 'nce-s-clf-186',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurodevelopmental disorders',
    difficulty: 'easy',
    stem: 'For the past year, a 10-year-old girl has shown seven inattentive symptoms of ADHD, such as losing materials and drifting off during lessons, but only two hyperactive-impulsive symptoms. Symptoms began before age 12 and appear at home and school. Which presentation should be specified?',
    options: [
      { id: 'a', text: 'Predominantly inattentive presentation', isCorrect: true, rationale: 'Inattention criteria are met while hyperactivity-impulsivity criteria are not, which defines this presentation.' },
      { id: 'b', text: 'Combined presentation', isCorrect: false, rationale: 'Combined presentation requires both symptom criteria to be met for the past 6 months.' },
      { id: 'c', text: 'Predominantly hyperactive presentation', isCorrect: false, rationale: 'She has only two hyperactive-impulsive symptoms, below the threshold.' },
      { id: 'd', text: 'Other specified ADHD', isCorrect: false, rationale: 'Full criteria are met, so a specified presentation of ADHD applies.' },
    ],
    rationale: 'ADHD presentations reflect the past 6 months: combined (both inattention and hyperactivity-impulsivity criteria met), predominantly inattentive (inattention met, hyperactivity-impulsivity not), or predominantly hyperactive/impulsive (the reverse). Children need six or more symptoms in a domain; those 17 and older need five. Girls are more often seen with the inattentive presentation, which can delay recognition.',
    references: [{ source: 'DSM-5-TR', detail: 'Attention-Deficit/Hyperactivity Disorder: specify current presentation' }],
  },
  // ── schizophrenia spectrum disorders ────────────────────────────────────
  {
    id: 'nce-s-clf-187',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'easy',
    stem: 'Which of the following is a negative symptom of schizophrenia?',
    options: [
      { id: 'a', text: 'Persecutory delusions', isCorrect: false, rationale: 'Delusions are positive symptoms, an addition to normal experience.' },
      { id: 'b', text: 'Disorganized speech', isCorrect: false, rationale: 'Disorganized speech is a separate symptom domain, not a negative symptom.' },
      { id: 'c', text: 'Auditory hallucinations', isCorrect: false, rationale: 'Hallucinations are positive symptoms.' },
      { id: 'd', text: 'Avolition', isCorrect: true, rationale: 'Avolition, a decrease in self-initiated purposeful activity, is a core negative symptom.' },
    ],
    rationale: 'Negative symptoms reflect a loss or reduction of normal functions. DSM-5-TR highlights diminished emotional expression and avolition as especially prominent in schizophrenia; others include alogia, anhedonia, and asociality. Negative symptoms account for much of the long-term disability in schizophrenia and respond less well to antipsychotic medication than positive symptoms.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizophrenia Spectrum and Other Psychotic Disorders: key features (negative symptoms)' }],
  },
  {
    id: 'nce-s-clf-188',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'hard',
    stem: 'A 45-year-old in treatment for severe depression arrives with his wife, who says he has barely spoken or eaten for 3 days. In session he stays mute, holds a stiff, odd posture for long periods, and resists when the counselor gently offers him a cup of water. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Begin behavioral activation to restart his routine and appetite', isCorrect: false, rationale: 'Behavioral activation cannot address a possible medical emergency that needs urgent evaluation first.' },
      { id: 'b', text: 'Use silence and patience until he is ready to talk in session', isCorrect: false, rationale: 'Waiting delays care for catatonia, which can lead to dehydration and other serious complications.' },
      { id: 'c', text: 'Arrange urgent medical evaluation for possible catatonia today', isCorrect: true, rationale: 'Mutism, posturing, and negativism suggest catatonia, which needs urgent medical care and is often highly treatable.' },
      { id: 'd', text: 'Ask his wife to keep a food log and report back next week', isCorrect: false, rationale: 'A week of monitoring is far too slow when he is not eating or drinking and may be catatonic.' },
    ],
    rationale: 'Catatonia is diagnosed when three or more of twelve psychomotor features are present, such as stupor, mutism, posturing, catalepsy, and negativism. It can occur with depressive, bipolar, psychotic, or medical conditions and may become life-threatening through dehydration, malnutrition, or autonomic instability. It typically responds to medical treatment, so the counselor\'s first job is to get the client to urgent medical and psychiatric evaluation.',
    references: [{ source: 'DSM-5-TR', detail: 'Catatonia Associated With Another Mental Disorder (Catatonia Specifier)' }],
    reviewNote: 'Placed under schizophrenia spectrum because catatonia sits in that DSM-5-TR chapter; the client here has depression.',
  },
  {
    id: 'nce-s-clf-189',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'medium',
    stem: 'A 24-year-old has just been discharged after a first episode of schizophrenia and is moving back home. His parents are frightened and often criticize him for "lying around," and his mother has given up her job to watch him constantly. Which intervention is MOST likely to reduce his risk of relapse?',
    options: [
      { id: 'a', text: 'Family psychoeducation that lowers criticism and overinvolvement', isCorrect: true, rationale: 'High expressed emotion predicts relapse, and family interventions that reduce it lower relapse rates.' },
      { id: 'b', text: 'Advising the family to limit contact with him until he stabilizes', isCorrect: false, rationale: 'Reducing contact removes support and does not teach the family more helpful ways to respond.' },
      { id: 'c', text: 'Individual insight therapy exploring his early family relationships', isCorrect: false, rationale: 'Insight-oriented therapy is not an evidence-based relapse-prevention approach for schizophrenia.' },
      { id: 'd', text: 'Encouraging his parents to confront his low motivation more firmly', isCorrect: false, rationale: 'Firmer confrontation increases criticism, a component of high expressed emotion linked to relapse.' },
    ],
    rationale: 'Expressed emotion describes family attitudes of criticism, hostility, and emotional overinvolvement toward a member with a mental illness. High expressed emotion reliably predicts relapse in schizophrenia. Family psychoeducation and family intervention teach relatives about the illness, problem-solving, and calmer communication, and they reduce relapse and rehospitalization.',
    references: [
      { source: 'NICE guidelines', detail: 'CG178 Psychosis and schizophrenia in adults: family intervention' },
      { source: 'Goldenberg (Family Therapy)', detail: 'Psychoeducational family therapy and expressed emotion' },
    ],
  },
  // ── personality disorders ───────────────────────────────────────────────
  {
    id: 'nce-s-clf-190',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'easy',
    stem: 'A 34-year-old arrives in a flamboyant outfit and calls the counselor "my new best friend" at their first meeting. She is upset when attention shifts away from her, speaks dramatically but vaguely, and her emotions change quickly. This pattern has lasted since her late teens. Which personality disorder BEST fits?',
    options: [
      { id: 'a', text: 'Narcissistic personality disorder', isCorrect: false, rationale: 'Narcissistic personality centers on grandiosity, entitlement, and need for admiration rather than shallow, shifting emotion.' },
      { id: 'b', text: 'Histrionic personality disorder', isCorrect: true, rationale: 'Attention-seeking, rapidly shifting shallow emotion, impressionistic speech, and overestimating intimacy fit histrionic personality.' },
      { id: 'c', text: 'Borderline personality disorder', isCorrect: false, rationale: 'Borderline personality centers on abandonment fears, unstable identity, and self-harm, which are not described.' },
      { id: 'd', text: 'Dependent personality disorder', isCorrect: false, rationale: 'Dependent personality centers on needing others to make decisions and fear of being alone.' },
    ],
    rationale: 'Histrionic personality disorder is a pervasive pattern of excessive emotionality and attention-seeking beginning by early adulthood. Features include discomfort when not the center of attention, rapidly shifting and shallow emotions, use of appearance to draw attention, impressionistic speech lacking detail, theatrical expression, suggestibility, and viewing relationships as more intimate than they are. At least five of eight criteria are required.',
    references: [{ source: 'DSM-5-TR', detail: 'Histrionic Personality Disorder, diagnostic criteria' }],
  },
  {
    id: 'nce-s-clf-191',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'hard',
    stem: 'Since adolescence, a 29-year-old has avoided almost all new relationships and job promotions, believing she is inferior and certain to be rejected. She also has marked fear of being judged when eating or speaking in front of others. How does DSM-5-TR describe avoidant personality disorder in relation to social anxiety disorder?',
    options: [
      { id: 'a', text: 'Social anxiety disorder must be ruled out before avoidant PD is given', isCorrect: false, rationale: 'DSM-5-TR does not make social anxiety disorder an exclusion for avoidant personality disorder.' },
      { id: 'b', text: 'Avoidant PD is diagnosed only when fear is limited to one situation', isCorrect: false, rationale: 'Avoidant personality disorder is pervasive across contexts, not limited to a single situation.' },
      { id: 'c', text: 'The two are unrelated, as one is a mood state and the other a trait', isCorrect: false, rationale: 'DSM-5-TR describes heavy overlap between them; neither is a mood disorder.' },
      { id: 'd', text: 'They overlap heavily and both may be diagnosed if each is fully met', isCorrect: true, rationale: 'DSM-5-TR notes great overlap, possibly alternative conceptualizations, and both can be diagnosed when criteria are met.' },
    ],
    rationale: 'Avoidant personality disorder is a pervasive pattern of social inhibition, feelings of inadequacy, and hypersensitivity to negative evaluation beginning by early adulthood. DSM-5-TR notes so much overlap with social anxiety disorder that they may be alternative conceptualizations of the same or similar conditions. When criteria for both are met, both may be diagnosed; avoidant PD tends to reflect a broader, identity-level sense of inadequacy across most interpersonal settings.',
    references: [{ source: 'DSM-5-TR', detail: 'Avoidant Personality Disorder: differential diagnosis (social anxiety disorder)' }],
  },
  {
    id: 'nce-s-clf-192',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'personality disorders',
    difficulty: 'medium',
    stem: 'Early in counseling, a client with borderline personality disorder calls the counselor several times a week between sessions, often late at night, and feels rejected when calls are not returned at once. The counselor is growing frustrated. Which response BEST reflects an effective treatment frame?',
    options: [
      { id: 'a', text: 'Return every call at once so she does not feel abandoned in a crisis', isCorrect: false, rationale: 'Unlimited availability is unsustainable, can reinforce crisis behavior, and risks counselor burnout.' },
      { id: 'b', text: 'Tell her calls between sessions are not allowed under any condition', isCorrect: false, rationale: 'A blanket ban leaves her without coaching support and may feel like the rejection she fears.' },
      { id: 'c', text: 'Set clear, agreed limits on contact, with brief skills-coaching calls', isCorrect: true, rationale: 'A collaborative, consistent frame with planned coaching contact supports skill use while protecting the work.' },
      { id: 'd', text: 'Refer her elsewhere, since frequent calls show she is not yet ready', isCorrect: false, rationale: 'Frequent contact is a treatment target, not a reason to abandon the client.' },
    ],
    rationale: 'Evidence-based treatments for borderline personality disorder share a clear, consistent treatment frame agreed with the client. In dialectical behavior therapy, between-session phone coaching is brief and focused on applying skills, with limits the therapist observes and explains openly. A predictable frame reduces fears of abandonment, discourages reinforcement of crisis behavior, and is supported by consultation for the counselor.',
    references: [{ source: 'Linehan (DBT Skills Training Manual)', detail: 'DBT treatment modes: between-session phone coaching and observing limits' }],
  },
  // ── eating disorders ────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-193',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'eating disorders',
    difficulty: 'easy',
    stem: 'An adult client meets criteria for binge-eating disorder and asks which psychological treatment has the strongest evidence. Which approach should the counselor describe as first-line?',
    options: [
      { id: 'a', text: 'Eating-disorder-focused cognitive behavioral therapy', isCorrect: true, rationale: 'CBT focused on eating, including guided self-help, is the first-line psychological treatment for binge-eating disorder.' },
      { id: 'b', text: 'A strict diet plan aimed mainly at quick weight loss', isCorrect: false, rationale: 'Dieting is not a treatment for binge eating and rigid restriction can intensify the binge cycle.' },
      { id: 'c', text: 'Long-term psychodynamic therapy as the sole treatment', isCorrect: false, rationale: 'Psychodynamic therapy lacks the evidence base that CBT has for binge-eating disorder.' },
      { id: 'd', text: 'Hypnosis to suppress cravings for specific trigger foods', isCorrect: false, rationale: 'Hypnosis is not an evidence-based first-line treatment for binge-eating disorder.' },
    ],
    rationale: 'Clinical guidelines recommend eating-disorder-focused CBT for binge-eating disorder, often beginning with a guided self-help program and moving to group or individual CBT if needed. Treatment targets regular eating, the binge cycle, triggers, and the over-evaluation of shape and weight. Weight loss is not the primary aim, and restrictive dieting can maintain binge eating.',
    references: [{ source: 'NICE guidelines', detail: 'NG69 Eating disorders: treating binge eating disorder (guided self-help; group CBT-ED)' }],
  },
  {
    id: 'nce-s-clf-194',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'A 17-year-old has lost a significant amount of weight over a year through restrictive eating. She intensely fears weight gain and judges herself almost entirely by her shape. Her physician notes that, despite the loss, her weight remains within the normal range for her age and height. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Anorexia nervosa, restricting type, with mild severity', isCorrect: false, rationale: 'Anorexia nervosa requires significantly low body weight, which is not present here.' },
      { id: 'b', text: 'Other specified feeding or eating disorder (atypical AN)', isCorrect: true, rationale: 'Atypical anorexia nervosa is listed under OSFED when all AN criteria are met except low weight.' },
      { id: 'c', text: 'Avoidant/restrictive food intake disorder, adolescent onset', isCorrect: false, rationale: 'ARFID excludes restriction driven by concerns about body shape or weight.' },
      { id: 'd', text: 'Bulimia nervosa, low frequency and limited duration', isCorrect: false, rationale: 'No binge eating or compensatory behaviors are described.' },
    ],
    rationale: 'DSM-5-TR lists atypical anorexia nervosa as an example of other specified feeding or eating disorder: all criteria for anorexia nervosa are met except that, despite significant weight loss, weight is within or above the normal range. Medical risks can be serious despite a normal-appearing weight, so these clients need the same medical monitoring and specialized care as those with anorexia nervosa.',
    references: [{ source: 'DSM-5-TR', detail: 'Other Specified Feeding or Eating Disorder: atypical anorexia nervosa' }],
  },
  {
    id: 'nce-s-clf-195',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'Parents of a 14-year-old recently diagnosed with anorexia nervosa ask what treatment the eating disorder team will recommend. She is medically stable for outpatient care. Which description BEST fits family-based treatment (FBT) for adolescent anorexia?',
    options: [
      { id: 'a', text: 'The teen meets alone with a therapist to explore the roots of her illness', isCorrect: false, rationale: 'FBT is family based and does not focus on uncovering causes; individual insight work is a different model.' },
      { id: 'b', text: 'Parents step back from meals so that the teen regains a sense of control', isCorrect: false, rationale: 'FBT does the opposite in its first phase, placing parents in charge of restoring healthy eating.' },
      { id: 'c', text: 'The family first explores how parenting errors caused the eating disorder', isCorrect: false, rationale: 'FBT takes an agnostic stance on cause and explicitly avoids blaming parents.' },
      { id: 'd', text: 'Parents take charge of renourishment at first, then gradually hand it back', isCorrect: true, rationale: 'FBT empowers parents to lead renourishment first, then returns control to the teen as she recovers.' },
    ],
    rationale: 'Family-based treatment (the Maudsley approach) is a leading evidence-based treatment for adolescent anorexia nervosa and is reflected in guideline recommendations for eating-disorder-focused family therapy. It proceeds in phases: parents take charge of restoring healthy eating, control over eating is gradually returned to the adolescent, and then broader adolescent development is addressed. The model does not blame parents and separates the illness from the young person.',
    references: [{ source: 'NICE guidelines', detail: 'NG69 Eating disorders: anorexia nervosa in children and young people (eating-disorder-focused family therapy)' }],
  },
  // ── depressive disorders ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-196',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'hard',
    stem: 'A 26-year-old in a major depressive episode brightens noticeably when friends invite her out, then sinks again. She sleeps far more than usual, eats much more, describes her arms and legs as feeling "like lead," and has long been crushed by small hints of criticism. Which specifier BEST fits?',
    options: [
      { id: 'a', text: 'With melancholic features', isCorrect: false, rationale: 'Melancholic features involve loss of reactivity to pleasant events, early waking, and decreased appetite, the reverse of this picture.' },
      { id: 'b', text: 'With anxious distress', isCorrect: false, rationale: 'Anxious distress involves tension, restlessness, worry, and fear, which are not described.' },
      { id: 'c', text: 'With atypical features', isCorrect: true, rationale: 'Mood reactivity plus hypersomnia, increased appetite, leaden paralysis, and rejection sensitivity define atypical features.' },
      { id: 'd', text: 'With mixed features', isCorrect: false, rationale: 'Mixed features require manic or hypomanic symptoms during the episode, which are absent.' },
    ],
    rationale: 'The "with atypical features" specifier requires mood reactivity (mood brightens in response to positive events) plus at least two of: significant weight gain or increased appetite, hypersomnia, leaden paralysis, and a long-standing pattern of sensitivity to interpersonal rejection. Criteria for melancholic features or catatonia must not be met in the same episode. Despite its name, this pattern is common.',
    references: [{ source: 'DSM-5-TR', detail: 'Specifiers for Depressive Disorders: with atypical features' }],
  },
  // ── bipolar disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-197',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'bipolar disorders',
    difficulty: 'medium',
    stem: 'A 32-year-old nurse with bipolar I disorder, stable on medication, is about to switch to rotating night shifts. Her past manic episodes followed weeks of disrupted sleep. Which counseling focus is MOST consistent with interpersonal and social rhythm therapy (IPSRT)?',
    options: [
      { id: 'a', text: 'Keep daily routines and sleep-wake times as steady as she can', isCorrect: true, rationale: 'IPSRT stabilizes daily rhythms, especially sleep, because disruptions can trigger mood episodes.' },
      { id: 'b', text: 'Explore early memories to find the roots of her mood swings', isCorrect: false, rationale: 'Uncovering childhood roots is not the IPSRT focus on present rhythms and relationships.' },
      { id: 'c', text: 'Dispute the irrational beliefs that drive her elevated moods', isCorrect: false, rationale: 'Disputing irrational beliefs comes from REBT, not IPSRT.' },
      { id: 'd', text: 'Build a fear hierarchy for in-vivo exposure to her workplace', isCorrect: false, rationale: 'Exposure hierarchies treat anxiety disorders; they do not address rhythm disruption.' },
    ],
    rationale: 'Interpersonal and social rhythm therapy, developed by Ellen Frank, holds that disruptions to daily routines and sleep-wake cycles can trigger mood episodes in people with bipolar disorder. Clients track daily rhythms (for example, with a social rhythm metric), work to keep them regular, and address interpersonal problems and role transitions. A shift to night work is a classic rhythm disruption to plan for.',
    references: [{ source: 'IPSRT', detail: 'Social rhythm stabilization and the social rhythm metric' }],
  },
  // ── anxiety disorders ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-198',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'anxiety disorders',
    difficulty: 'hard',
    stem: 'A 22-year-old nursing student has fainted twice while watching blood draws and now avoids clinical rotations. She has specific phobia, blood-injection-injury type. When planning exposure, which added technique is MOST suited to this phobia type?',
    options: [
      { id: 'a', text: 'Progressive muscle relaxation before and during each exposure', isCorrect: false, rationale: 'Relaxation can deepen the drop in blood pressure behind fainting, so it is generally avoided for this type.' },
      { id: 'b', text: 'Applied tension, tensing large muscles to keep blood pressure up', isCorrect: true, rationale: 'Applied tension counters the vasovagal blood pressure drop that causes fainting in this phobia type.' },
      { id: 'c', text: 'Interoceptive exposure to dizziness by spinning in a chair first', isCorrect: false, rationale: 'Interoceptive exposure targets fear of bodily sensations in panic disorder, not vasovagal fainting.' },
      { id: 'd', text: 'Slow diaphragmatic breathing to lower her heart rate and arousal', isCorrect: false, rationale: 'Lowering arousal does not address, and may worsen, the vasovagal response.' },
    ],
    rationale: 'Unlike other specific phobias, the blood-injection-injury type often involves a vasovagal response: a brief rise in heart rate and blood pressure followed by a sharp drop that can cause fainting. Applied tension teaches the client to tense large muscle groups to raise blood pressure while being exposed to feared stimuli. Relaxation-based methods are generally avoided because they can make fainting more likely.',
    references: [{ source: 'DSM-5-TR', detail: 'Specific Phobia: blood-injection-injury type (vasovagal fainting response)' }],
    reviewNote: 'Applied tension (Öst) is not described in DSM-5-TR; no approved source names it directly. SME to confirm or add a citation.',
  },
  // ── trauma- and stressor-related disorders ──────────────────────────────
  {
    id: 'nce-s-clf-199',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'hard',
    stem: 'A 38-year-old meets full criteria for PTSD after a violent home invasion. She also reports that she often feels as though she is watching herself from outside her body and that the world seems dreamlike and unreal. These experiences are not caused by substances or a medical condition. How should this be diagnosed?',
    options: [
      { id: 'a', text: 'PTSD plus a separate diagnosis of depersonalization/derealization disorder', isCorrect: false, rationale: 'When these symptoms occur as part of PTSD, they are captured with the specifier, not a separate disorder.' },
      { id: 'b', text: 'Acute stress disorder, as dissociative symptoms are central to that diagnosis', isCorrect: false, rationale: 'Full PTSD criteria are already met, and acute stress disorder is limited to the first month after trauma.' },
      { id: 'c', text: 'PTSD with delayed expression, given the presence of dissociative symptoms', isCorrect: false, rationale: 'Delayed expression refers to full criteria not being met until at least 6 months after the event.' },
      { id: 'd', text: 'PTSD with dissociative symptoms, noting depersonalization and derealization', isCorrect: true, rationale: 'The dissociative specifier applies to persistent or recurrent depersonalization or derealization in PTSD.' },
    ],
    rationale: 'DSM-5-TR allows PTSD to be specified "with dissociative symptoms" when the person also has persistent or recurrent depersonalization (feeling detached from oneself, as an outside observer) or derealization (the world feels unreal, dreamlike, or distant), not attributable to substances or a medical condition. Recognizing this subtype matters because dissociation can affect pacing and stabilization in trauma-focused treatment.',
    references: [{ source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder: specify with dissociative symptoms' }],
  },
  // ── substance use and addictive disorders ───────────────────────────────
  {
    id: 'nce-s-clf-200',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'substance use and addictive disorders',
    difficulty: 'medium',
    stem: 'A 36-year-old with opioid use disorder has taken prescribed buprenorphine for 8 months and has not used illicit opioids. In a recovery group, peers tell him he is "not really clean" and urge him to stop the medication. He asks the counselor what to think. Which response is MOST consistent with best practice?',
    options: [
      { id: 'a', text: 'Agree that full recovery requires tapering off all opioid medicines soon', isCorrect: false, rationale: 'No fixed endpoint is required; stopping medication early raises the risk of relapse and overdose.' },
      { id: 'b', text: 'Suggest he follow the group\'s view, since peer support predicts recovery', isCorrect: false, rationale: 'Peer support is valuable, but the group\'s advice here conflicts with the evidence on medication for OUD.' },
      { id: 'c', text: 'Affirm that MOUD is effective treatment, and support talking to his prescriber', isCorrect: true, rationale: 'Medication for OUD is evidence-based treatment, and medication decisions belong with the client and prescriber.' },
      { id: 'd', text: 'Advise him to keep his medication secret from others in the recovery group', isCorrect: false, rationale: 'Encouraging secrecy does not address stigma or help him find supportive recovery settings.' },
    ],
    rationale: 'Medications for opioid use disorder, such as buprenorphine, methadone, and extended-release naltrexone, reduce illicit use, overdose deaths, and other harms. Taking prescribed medication as directed is treatment, not "substituting one addiction for another." Counselors should challenge stigma, support informed choices, coordinate with prescribers, and help clients find MOUD-friendly recovery supports; duration of medication is individualized, and discontinuing it raises relapse and overdose risk.',
    references: [{ source: 'SAMHSA TIP 63', detail: 'Part 1: MOUD effectiveness; Part 4: counseling and peer support for clients on MOUD' }],
    reviewNote: 'SME to confirm the TIP 63 part numbers in the locator.',
  },
  // ── grief and loss ──────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-201',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'grief and loss',
    difficulty: 'easy',
    stem: 'Two years after her husband died, a 70-year-old has returned to her volunteer work and made new friends. She still talks to him at his grave on their anniversary and keeps his watch on her nightstand. Her adult children ask the counselor to help her "finally let go." Which response BEST reflects current grief theory?',
    options: [
      { id: 'a', text: 'Agree that she must give up the attachment before she can heal', isCorrect: false, rationale: 'Older "letting go" models have given way to the view that healthy bonds with the deceased can continue.' },
      { id: 'b', text: 'Explain that a lasting bond with him can coexist with a full life', isCorrect: true, rationale: 'Continuing bonds, and Worden\'s fourth task of finding an enduring connection, describe adaptive grief.' },
      { id: 'c', text: 'Assess her for prolonged grief disorder due to the grave visits', isCorrect: false, rationale: 'She is functioning well; occasional rituals of connection are not signs of prolonged grief disorder.' },
      { id: 'd', text: 'Suggest she put his watch away to signal the grief has ended', isCorrect: false, rationale: 'Keeping meaningful objects can be part of a healthy continuing bond; removing them is not required.' },
    ],
    rationale: 'Contemporary grief theory views ongoing connection with the deceased as compatible with healthy adaptation. Worden\'s fourth task of mourning is to find an enduring connection with the deceased while embarking on a new life, and the continuing bonds perspective holds that memories, rituals, and inner conversations can support coping. Concern arises when connection prevents re-engagement in life, which is not the case here.',
    references: [{ source: 'Worden (Grief Counseling)', detail: 'Task IV: find an enduring connection with the deceased while embarking on a new life' }],
  },
  // ── crisis and disaster response ────────────────────────────────────────
  {
    id: 'nce-s-clf-202',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'crisis and disaster response',
    difficulty: 'easy',
    stem: 'Using James and Gilliland\'s six-step crisis model, a counselor has defined the problem with a client whose house burned down, ensured his safety, and offered support. The client is now calmer. Which step comes NEXT?',
    options: [
      { id: 'a', text: 'Obtaining his commitment to a plan', isCorrect: false, rationale: 'Commitment is the sixth and final step, after alternatives are explored and a plan is made.' },
      { id: 'b', text: 'Making a concrete plan with him', isCorrect: false, rationale: 'Planning is the fifth step and follows examining alternatives.' },
      { id: 'c', text: 'Redefining the core problem again', isCorrect: false, rationale: 'Defining the problem is the first step, which has already been completed.' },
      { id: 'd', text: 'Examining alternatives with him', isCorrect: true, rationale: 'After the three listening steps, the fourth step is examining alternatives.' },
    ],
    rationale: 'James and Gilliland\'s six-step model has three listening steps (defining the problem, ensuring client safety, providing support) followed by three acting steps (examining alternatives, making plans, obtaining commitment). Assessment runs throughout all six steps, and safety is monitored continuously, but the sequence guides the counselor from understanding to action.',
    references: [{ source: 'James & Gilliland (Crisis Intervention Strategies)', detail: 'Six-step model of crisis intervention' }],
  },
  // ── intimate partner violence ───────────────────────────────────────────
  {
    id: 'nce-s-clf-203',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'intimate partner violence',
    difficulty: 'medium',
    stem: 'During a risk assessment, a client experiencing partner abuse discloses several things about her partner. Which disclosure MOST strongly signals elevated risk of lethal violence and calls for urgent safety planning?',
    options: [
      { id: 'a', text: 'He has choked her until she could barely breathe in the past', isCorrect: true, rationale: 'Prior non-fatal strangulation is one of the strongest known predictors of later intimate partner homicide.' },
      { id: 'b', text: 'He often yells and calls her names when he gets home late', isCorrect: false, rationale: 'Verbal abuse is harmful but is a weaker predictor of lethality than strangulation.' },
      { id: 'c', text: 'He grew up in a home where his father hit his mother often', isCorrect: false, rationale: 'Childhood exposure to violence is a risk factor for perpetration but a weaker lethality marker.' },
      { id: 'd', text: 'He sulks and won\'t speak to her for days after arguments', isCorrect: false, rationale: 'Withdrawal after conflict does not signal elevated lethality.' },
    ],
    rationale: 'Lethality assessment in intimate partner violence focuses on factors linked to homicide, such as prior strangulation, access to firearms, threats to kill, escalating frequency or severity, extreme jealousy, and a recent or planned separation. Non-fatal strangulation markedly raises the risk of later homicide and may leave few visible injuries, so counselors should ask about it directly and respond with urgent safety planning and advocacy referrals.',
    references: [{ source: 'James & Gilliland (Crisis Intervention Strategies)', detail: 'Intimate partner violence: assessing lethality' }],
    reviewNote: 'The strangulation-lethality link comes from Campbell\'s Danger Assessment research, which is not in the approved library; SME to confirm the James & Gilliland locator.',
  },
  // ── additional new angles across topics 1–14 ────────────────────────────
  {
    id: 'nce-s-clf-204',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'A 3-year-old has delays in speech, motor skills, and self-care, but cannot yet complete standardized intellectual testing in a valid way. The evaluating team plans to reassess in a year. Which DSM-5-TR diagnosis BEST fits for now?',
    options: [
      { id: 'a', text: 'Intellectual disability, mild', isCorrect: false, rationale: 'Severity cannot yet be reliably assessed, so a specified level of intellectual disability is premature.' },
      { id: 'b', text: 'Global developmental delay', isCorrect: true, rationale: 'This diagnosis is reserved for children under 5 who miss milestones in several areas and cannot yet be reliably assessed.' },
      { id: 'c', text: 'Autism spectrum disorder, level 1', isCorrect: false, rationale: 'No social communication deficits or restricted, repetitive behaviors are described.' },
      { id: 'd', text: 'Language disorder, expressive type', isCorrect: false, rationale: 'Delays extend well beyond language to motor and self-care areas.' },
    ],
    rationale: 'Global developmental delay is diagnosed in children under age 5 when they fail to meet expected milestones in several areas of intellectual functioning and the clinical severity cannot be reliably assessed, often because the child is too young for standardized testing. It requires reassessment after a period of time.',
    references: [{ source: 'DSM-5-TR', detail: 'Global Developmental Delay' }],
  },
  {
    id: 'nce-s-clf-205',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'substance use and addictive disorders',
    difficulty: 'hard',
    stem: 'A 44-year-old previously met full criteria for alcohol use disorder. For the past 5 months he has met no criteria except strong cravings, which come mainly when he passes his old bar. He lives at home, not in a controlled setting. Which specifier applies?',
    options: [
      { id: 'a', text: 'In sustained remission, since he has gone months without drinking', isCorrect: false, rationale: 'Sustained remission requires 12 months or longer without meeting criteria other than craving.' },
      { id: 'b', text: 'No remission specifier, because his ongoing craving is a criterion', isCorrect: false, rationale: 'Craving is the one criterion explicitly allowed during remission, so it does not block the specifier.' },
      { id: 'c', text: 'In early remission, as only craving has been present for 5 months', isCorrect: true, rationale: 'Early remission applies after 3 months but less than 12 months with no criteria met except craving.' },
      { id: 'd', text: 'In early remission, in a controlled environment, given the time', isCorrect: false, rationale: 'He lives at home; the controlled-environment specifier is for settings where access is restricted.' },
    ],
    rationale: 'For substance use disorders, "in early remission" applies when, after full criteria were met, none have been met for at least 3 months but less than 12 months, with the exception of craving. "In sustained remission" requires 12 months or longer. "In a controlled environment" is added only when the person is in a setting where access to substances is restricted.',
    references: [{ source: 'DSM-5-TR', detail: 'Alcohol Use Disorder: remission specifiers' }],
  },
  {
    id: 'nce-s-clf-206',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'A 30-year-old violinist is comfortable at parties, in meetings, and on dates, but for a year has felt intense dread before solo recitals, fearing the audience will judge her shaking hands. She has started declining solo work. If criteria for social anxiety disorder are met, which specifier applies?',
    options: [
      { id: 'a', text: 'With panic attacks', isCorrect: false, rationale: 'No abrupt surges of intense fear are described, and this specifier does not capture the restricted context.' },
      { id: 'b', text: 'Generalized type', isCorrect: false, rationale: 'DSM-5 removed the generalized specifier for social anxiety disorder.' },
      { id: 'c', text: 'With poor insight', isCorrect: false, rationale: 'Social anxiety disorder has no insight specifier in DSM-5-TR.' },
      { id: 'd', text: 'Performance only', isCorrect: true, rationale: 'This specifier applies when the fear is restricted to speaking or performing in public.' },
    ],
    rationale: 'Social anxiety disorder may be specified "performance only" when the fear is restricted to speaking or performing in public. People with this pattern are often impaired mainly in professional or academic roles that require performing, while ordinary social interactions are comfortable. DSM-5 replaced the older "generalized" specifier with this narrower one.',
    references: [{ source: 'DSM-5-TR', detail: 'Social Anxiety Disorder: specify if performance only' }],
  },
  {
    id: 'nce-s-clf-207',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'A 4-year-old was in a serious car crash 3 months ago. Since then she repeatedly crashes toy cars together while making siren noises, cries when buckled into her car seat, and clings to her parents at bedtime. She shows no visible distress during the crash play. How should the counselor understand the repetitive play?',
    options: [
      { id: 'a', text: 'Play reenactment can express intrusion symptoms in young children', isCorrect: true, rationale: 'For children 6 and younger, intrusive memories may appear as play reenactment and need not look distressing.' },
      { id: 'b', text: 'The play is ordinary for her age and unrelated to the crash itself', isCorrect: false, rationale: 'Repetitive play that mirrors the trauma, alongside avoidance and clinging, points to a trauma response.' },
      { id: 'c', text: 'Because she seems calm during the play, PTSD can be ruled out here', isCorrect: false, rationale: 'DSM-5-TR notes that intrusive memories in young children may not appear distressing.' },
      { id: 'd', text: 'The play shows the trauma is resolved and needs no further attention', isCorrect: false, rationale: 'Ongoing reenactment with avoidance and distress at reminders suggests the trauma is not resolved.' },
    ],
    rationale: 'DSM-5-TR includes separate PTSD criteria for children 6 years and younger. Intrusion symptoms may take the form of play reenactment, and spontaneous intrusive memories may not appear distressing. The avoidance and negative-cognition clusters are combined, so only one symptom from that combined group is needed. Counselors should assess such play in context and involve caregivers in trauma-focused treatment.',
    references: [{ source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder for Children 6 Years and Younger, Criterion B' }],
  },
];
