// tools/nce/seed/clinical-focus-9.js — Areas of Clinical Focus, batch 5 (part 1)
// Hand-authored original items (nce-s-clf-237 … nce-s-clf-266).
module.exports = [
  // ── depressive disorders ──────────────────────────────────────────────────
  {
    id: 'nce-s-clf-237',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'depressive disorders',
    difficulty: 'hard',
    stem: 'A 46-year-old who drank heavily every day for two years developed low mood, poor sleep and hopelessness during that period. He stopped drinking and completed withdrawal six weeks ago. His depressive symptoms have not eased since then. Which conclusion is BEST supported?',
    options: [
      { id: 'a', text: 'Alcohol-induced depressive disorder fits, since the mood began while he drank', isCorrect: false, rationale: 'Onset during use raises the question, but symptoms that persist well past withdrawal argue against a purely induced disorder.' },
      { id: 'b', text: 'No depressive diagnosis fits until he stays abstinent for a full twelve months', isCorrect: false, rationale: 'DSM-5-TR does not require a year of abstinence; about one month after withdrawal is the usual benchmark.' },
      { id: 'c', text: 'An independent depressive disorder is likely, as it has lasted past one month', isCorrect: true, rationale: 'Persistence for a substantial period (about one month) after withdrawal ends is evidence of an independent depressive disorder.' },
      { id: 'd', text: 'His symptoms show a protracted alcohol withdrawal that will soon clear alone', isCorrect: false, rationale: 'Acute withdrawal resolves within days; six weeks of unchanged depression should not be assumed to be withdrawal.' },
    ],
    rationale: 'Substance/medication-induced depressive disorder is diagnosed when depressive symptoms develop during or soon after intoxication or withdrawal and are not better explained by an independent depressive disorder. DSM-5-TR names persistence of symptoms for a substantial period, about one month, after acute withdrawal or severe intoxication ends as evidence of an independent disorder. Ongoing reassessment after abstinence is key to the differential.',
    references: [{ source: 'DSM-5-TR', detail: 'Substance/Medication-Induced Depressive Disorder: Criterion C (evidence of an independent depressive disorder)' }],
  },
  {
    id: 'nce-s-clf-238',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'depressive disorders',
    difficulty: 'medium',
    stem: 'Parents of a 9-year-old say that since age 7 he has had severe temper outbreaks about four times a week at home and school, and is angry and irritable most of the day between outbursts. He has had no distinct periods of elevated mood or decreased need for sleep. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Disruptive mood dysregulation disorder, given the chronic irritability', isCorrect: true, rationale: 'Frequent severe outbursts plus persistently irritable mood for 12+ months in two settings, onset before 10, fits DMDD.' },
      { id: 'b', text: 'Bipolar I disorder, given his frequent rages and his very irritable mood', isCorrect: false, rationale: 'Pediatric bipolar disorder is episodic with distinct manic periods; he shows chronic, nonepisodic irritability.' },
      { id: 'c', text: 'Oppositional defiant disorder, as the outbursts occur in two settings', isCorrect: false, rationale: 'When DMDD criteria are met, ODD is not diagnosed separately; the severe persistent mood component points to DMDD.' },
      { id: 'd', text: 'Intermittent explosive disorder, due to his repeated angry outbursts', isCorrect: false, rationale: 'IED lacks the persistently irritable mood between outbursts, and it is not diagnosed when DMDD criteria are met.' },
    ],
    rationale: 'DMDD requires severe recurrent temper outbursts averaging three or more times per week, with persistently irritable or angry mood most of the day nearly every day between them, for 12 months or more in at least two settings. Onset is before age 10, and the diagnosis is not first made before age 6 or after age 18. It was added to the depressive disorders partly to reduce overdiagnosis of bipolar disorder in children with chronic, nonepisodic irritability.',
    references: [{ source: 'DSM-5-TR', detail: 'Disruptive Mood Dysregulation Disorder: Criteria A-K' }],
  },

  // ── bipolar disorders ─────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-239',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'easy',
    stem: 'A 23-year-old had one manic episode last year that led to a brief hospital stay. She has never had a major depressive episode. A classmate in her counseling program says she "cannot have bipolar disorder without depression." Under DSM-5-TR, what is required for bipolar I disorder?',
    options: [
      { id: 'a', text: 'At least one manic episode plus at least one major depressive episode', isCorrect: false, rationale: 'This describes a common course, but a major depressive episode is not required for bipolar I disorder.' },
      { id: 'b', text: 'At least one hypomanic episode plus at least one major depressive episode', isCorrect: false, rationale: 'These are the requirements for bipolar II disorder, which has no lifetime manic episode.' },
      { id: 'c', text: 'Two or more manic episodes separated by at least two months of remission', isCorrect: false, rationale: 'A single manic episode suffices; recurrence and remission intervals are not required for the diagnosis.' },
      { id: 'd', text: 'At least one manic episode, with or without any past depressive episodes', isCorrect: true, rationale: 'Bipolar I requires criteria for at least one manic episode; hypomanic or depressive episodes may occur but are not required.' },
    ],
    rationale: 'Bipolar I disorder is diagnosed when criteria have been met for at least one manic episode that is not better explained by a schizophrenia spectrum disorder. The manic episode may be preceded or followed by hypomanic or major depressive episodes, but these are not required. Bipolar II, in contrast, requires at least one hypomanic and at least one major depressive episode and no manic episode.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar I Disorder: Criterion A and text on manic, hypomanic and depressive episodes' }],
  },
  {
    id: 'nce-s-clf-240',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'bipolar disorders',
    difficulty: 'medium',
    stem: 'A 37-year-old meets full criteria for a current manic episode. During most days of the episode she also feels intensely sad, has lost interest in her usual hobbies, feels worthless, and has recurrent thoughts of death. Which specifier is MOST appropriate?',
    options: [
      { id: 'a', text: 'With anxious distress, because she shows marked emotional turmoil daily', isCorrect: false, rationale: 'Anxious distress requires symptoms like feeling keyed up, tense, restless or fearful, not depressive symptoms.' },
      { id: 'b', text: 'With mixed features, because of her concurrent depressive symptoms', isCorrect: true, rationale: 'Three or more depressive symptoms on most days of a manic episode meet the mixed features specifier.' },
      { id: 'c', text: 'With rapid cycling, because her mood moves between high and low', isCorrect: false, rationale: 'Rapid cycling requires four or more mood episodes in 12 months, not simultaneous symptoms in one episode.' },
      { id: 'd', text: 'With melancholic features, as she has lost interest in her hobbies', isCorrect: false, rationale: 'Melancholic features is a specifier for major depressive episodes, not for a current manic episode.' },
    ],
    rationale: 'The "with mixed features" specifier applies to a manic or hypomanic episode when at least three depressive symptoms (such as dysphoria, diminished interest, worthlessness or guilt, fatigue, psychomotor retardation, or thoughts of death) are present nearly every day during the episode. Mixed states carry elevated suicide risk, so counselors should assess safety closely. The specifier can also apply to major depressive episodes with concurrent manic or hypomanic symptoms.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar and Related Disorders specifiers: with mixed features (manic or hypomanic episode)' }],
  },

  // ── anxiety disorders ─────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-241',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'anxiety disorders',
    difficulty: 'hard',
    stem: 'A 29-year-old has, for the past 7 months, felt intense dread whenever his spouse travels, called her many times a day to check that she is safe, and refused overnight work trips. He worries mainly that an accident will take her from him, not about many topics. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Generalized anxiety disorder, since his worry has lasted over six months', isCorrect: false, rationale: 'GAD involves worry about many events or activities; his fear centers on separation from one attachment figure.' },
      { id: 'b', text: 'Separation anxiety disorder, since adult duration is typically 6 months', isCorrect: true, rationale: 'Excessive fear of harm befalling an attachment figure, with reluctance to be apart, lasting typically 6+ months in adults fits.' },
      { id: 'c', text: 'Agoraphobia, since he avoids travel and being away from home overnight', isCorrect: false, rationale: 'Agoraphobic avoidance stems from fear that escape or help will be unavailable, not fear of losing a loved one.' },
      { id: 'd', text: 'No anxiety disorder, as separation anxiety is diagnosed only in childhood', isCorrect: false, rationale: 'DSM-5-TR permits separation anxiety disorder at any age; onset in adulthood is recognized.' },
    ],
    rationale: 'Separation anxiety disorder is developmentally inappropriate, excessive fear or anxiety about separation from attachment figures. The duration is at least 4 weeks in children and adolescents and typically 6 months or more in adults. DSM-5-TR removed the earlier requirement of onset before age 18, so adults whose fears center on harm to a partner or child may meet criteria.',
    references: [{ source: 'DSM-5-TR', detail: 'Separation Anxiety Disorder: Criteria A and B (duration in children vs adults)' }],
  },
  {
    id: 'nce-s-clf-242',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'anxiety disorders',
    difficulty: 'medium',
    stem: 'For 7 months, a 10-year-old has worried more days than not about grades, storms, her family\'s money and being late. She finds the worry hard to control and has trouble sleeping, but no other physical or associated symptoms. How many associated symptoms does DSM-5-TR require for a child to meet GAD criteria?',
    options: [
      { id: 'a', text: 'Three of the six associated symptoms, the same number used for adults', isCorrect: false, rationale: 'Three symptoms are required for adults; DSM-5-TR lowers the threshold for children.' },
      { id: 'b', text: 'Two of the six associated symptoms, one physical and one cognitive', isCorrect: false, rationale: 'DSM-5-TR sets no two-symptom rule and does not require a physical and cognitive mix.' },
      { id: 'c', text: 'Only one of the six associated symptoms, such as disturbed sleep', isCorrect: true, rationale: 'For children, only one of the six associated symptoms is required, so her sleep problem can satisfy the criterion.' },
      { id: 'd', text: 'Four of the six associated symptoms, as worry in youth is so common', isCorrect: false, rationale: 'No criterion raises the threshold for youth; the requirement is lower for children, not higher.' },
    ],
    rationale: 'Generalized anxiety disorder requires excessive, hard-to-control worry about a number of events or activities on more days than not for at least 6 months. Adults need three or more of six associated symptoms (restlessness, fatigue, poor concentration, irritability, muscle tension, sleep disturbance), but children need only one. Children with GAD often worry about school performance, catastrophes and punctuality and may seek frequent reassurance.',
    references: [{ source: 'DSM-5-TR', detail: 'Generalized Anxiety Disorder: Criterion C (note: only one item required in children)' }],
  },

  // ── trauma- and stressor-related disorders ────────────────────────────────
  {
    id: 'nce-s-clf-243',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'medium',
    stem: 'A 3-year-old spent his first 2 years in a series of neglectful placements. Now with stable foster parents, he rarely seeks comfort when hurt and barely responds when they offer it. He shows little positive emotion and has unexplained bouts of fearfulness. He uses language and play typical for his age. Which diagnosis is MOST likely?',
    options: [
      { id: 'a', text: 'Reactive attachment disorder linked to his early social neglect', isCorrect: true, rationale: 'Rarely seeking or responding to comfort, limited positive affect and unexplained fearfulness after neglect fit RAD.' },
      { id: 'b', text: 'Disinhibited social engagement disorder from his early care setting', isCorrect: false, rationale: 'DSED involves overly familiar approach to unfamiliar adults, not withdrawal and failure to seek comfort.' },
      { id: 'c', text: 'Autism spectrum disorder based on his limited social response', isCorrect: false, rationale: 'His age-typical language and play and the clear history of neglect point away from autism and toward RAD.' },
      { id: 'd', text: 'Posttraumatic stress disorder for children six years and under', isCorrect: false, rationale: 'No intrusion or avoidance tied to a specific traumatic event is described; the core issue is absent attachment behavior.' },
    ],
    rationale: 'Reactive attachment disorder is a consistent pattern of inhibited, emotionally withdrawn behavior toward caregivers: the child rarely seeks or responds to comfort when distressed, with limited positive affect and unexplained irritability, sadness or fear. It follows extremes of insufficient care, appears before age 5, and requires a developmental age of at least 9 months. Unlike autism spectrum disorder, RAD does not involve restricted, repetitive behaviors, and language and play are not specifically impaired.',
    references: [{ source: 'DSM-5-TR', detail: 'Reactive Attachment Disorder: Criteria A-G; differential diagnosis with autism spectrum disorder' }],
  },
  {
    id: 'nce-s-clf-244',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'trauma- and stressor-related disorders',
    difficulty: 'hard',
    stem: 'A 51-year-old reports intrusive images, nightmares and avoidance since learning by phone that her brother died. Which detail would determine whether the death can meet PTSD Criterion A through learning about it?',
    options: [
      { id: 'a', text: 'Whether she had a close, loving relationship with her brother for years', isCorrect: false, rationale: 'A close relationship is needed, but closeness alone does not settle whether the event qualifies.' },
      { id: 'b', text: 'Whether she learned of the death within a day after it happened', isCorrect: false, rationale: 'DSM-5-TR sets no time window for learning about the event in Criterion A.' },
      { id: 'c', text: 'Whether her symptoms began within the first month after the death', isCorrect: false, rationale: 'Symptom timing bears on the delayed-expression specifier, not on whether the event qualifies under Criterion A.' },
      { id: 'd', text: 'Whether the death was violent or accidental rather than from illness', isCorrect: true, rationale: 'When learning of a close other\'s actual or threatened death, the event must have been violent or accidental.' },
    ],
    rationale: 'PTSD Criterion A can be met by learning that a traumatic event happened to a close family member or close friend. When the event involves actual or threatened death, it must have been violent or accidental; a death from natural causes such as illness does not qualify. Intense distress after an expected or natural death may instead be assessed as grief, prolonged grief disorder, adjustment disorder or a depressive disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Posttraumatic Stress Disorder: Criterion A3 (learning of violent or accidental death)' }],
  },

  // ── obsessive-compulsive and related disorders ────────────────────────────
  {
    id: 'nce-s-clf-245',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'medium',
    stem: 'A 41-year-old attorney insists that every memo follow her exact formatting rules, redoes her team\'s work, and works so many hours she has no hobbies. She sees her standards as correct and is puzzled that others complain. She has no intrusive, unwanted thoughts or rituals. Which feature MOST points to obsessive-compulsive personality disorder rather than OCD?',
    options: [
      { id: 'a', text: 'Her rigid perfectionism feels right to her and has no true obsessions', isCorrect: true, rationale: 'OCPD is an ego-syntonic, pervasive perfectionism without the intrusive obsessions and compulsions of OCD.' },
      { id: 'b', text: 'Her drive for order is so strong that it interferes with her work life', isCorrect: false, rationale: 'Impairment occurs in both OCD and OCPD, so it does not distinguish the two disorders.' },
      { id: 'c', text: 'She spends more than one hour a day on her work and her formatting', isCorrect: false, rationale: 'The one-hour marker is an OCD time-consuming example, and long work hours alone do not separate the disorders.' },
      { id: 'd', text: 'She is perfectionistic only at work and is relaxed with her friends', isCorrect: false, rationale: 'A personality disorder is pervasive across contexts; a work-limited pattern would argue against OCPD.' },
    ],
    rationale: 'Obsessive-compulsive personality disorder is a pervasive pattern of preoccupation with orderliness, perfectionism and control that the person usually experiences as reasonable (ego-syntonic). OCD is defined by intrusive, unwanted obsessions and compulsions performed to reduce distress. When both sets of criteria are met, both can be diagnosed, but the absence of true obsessions and compulsions points to OCPD.',
    references: [{ source: 'DSM-5-TR', detail: 'Obsessive-Compulsive Personality Disorder: differential diagnosis with obsessive-compulsive disorder' }],
  },
  {
    id: 'nce-s-clf-246',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'obsessive-compulsive and related disorders',
    difficulty: 'easy',
    stem: 'A 19-year-old pulls out her eyebrow hairs while studying, leaving visible bare patches. She feels relief as she pulls, has tried many times to stop, and is embarrassed by how her face looks. She has no concerns about a flaw in her appearance before pulling. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Body dysmorphic disorder, since she is upset about how her face looks', isCorrect: false, rationale: 'In BDD, hair removal aims to fix a perceived defect; her distress follows the pulling rather than driving it.' },
      { id: 'b', text: 'Excoriation disorder, since she has repeatedly tried to stop pulling', isCorrect: false, rationale: 'Excoriation disorder involves recurrent skin picking that causes lesions, not hair pulling.' },
      { id: 'c', text: 'Trichotillomania, given hair loss from pulling and attempts to stop', isCorrect: true, rationale: 'Recurrent hair pulling causing hair loss, with repeated efforts to stop and distress, meets trichotillomania criteria.' },
      { id: 'd', text: 'Obsessive-compulsive disorder, since pulling eases her inner tension', isCorrect: false, rationale: 'Her pulling is not driven by obsessions or rules, so a body-focused repetitive behavior disorder fits better.' },
    ],
    rationale: 'Trichotillomania (hair-pulling disorder) requires recurrent pulling out of one\'s hair resulting in hair loss, repeated attempts to decrease or stop, and clinically significant distress or impairment. Pulling is often preceded by tension or boredom and followed by relief or gratification. It is distinguished from BDD, where hair is removed to correct a perceived appearance flaw, and from OCD, where behavior responds to obsessions.',
    references: [{ source: 'DSM-5-TR', detail: 'Trichotillomania (Hair-Pulling Disorder): Criteria A-E and differential diagnosis' }],
  },

  // ── substance use and addictive disorders ─────────────────────────────────
  {
    id: 'nce-s-clf-247',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'substance use and addictive disorders',
    difficulty: 'medium',
    stem: 'A 27-year-old who smoked cannabis several times a day for two years stopped 4 days ago. She reports irritability, anxiety, trouble sleeping with vivid dreams, poor appetite and restlessness. She says, "Weed isn\'t addictive, so this must be something else." How should the counselor understand her symptoms?',
    options: [
      { id: 'a', text: 'As a new anxiety disorder, because cannabis has no withdrawal state', isCorrect: false, rationale: 'DSM-5-TR includes cannabis withdrawal; attributing her symptoms to a new disorder ignores the clear timing.' },
      { id: 'b', text: 'As likely cannabis withdrawal, which DSM-5-TR recognizes in heavy use', isCorrect: true, rationale: 'Three or more of these symptoms within about a week of stopping heavy, prolonged use meets cannabis withdrawal criteria.' },
      { id: 'c', text: 'As rebound mood symptoms, which only appear in people with depression', isCorrect: false, rationale: 'Withdrawal symptoms occur in people without depression; they reflect physiological adaptation to heavy use.' },
      { id: 'd', text: 'As symptoms that cannot be judged until she has two weeks of abstinence', isCorrect: false, rationale: 'Withdrawal is identified by symptoms that start within about one week; there is no two-week waiting rule.' },
    ],
    rationale: 'DSM-5-TR includes cannabis withdrawal, which follows cessation of heavy and prolonged use (daily or almost daily over at least a few months). Three or more symptoms develop within about one week, such as irritability or anger, anxiety, sleep difficulty or disturbing dreams, decreased appetite, restlessness, depressed mood or physical discomfort. Recognizing withdrawal helps counselors normalize symptoms and plan relapse prevention.',
    references: [{ source: 'DSM-5-TR', detail: 'Cannabis Withdrawal: Criteria A-B' }],
  },
  {
    id: 'nce-s-clf-248',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'substance use and addictive disorders',
    difficulty: 'hard',
    stem: 'A counseling intern drafts a report stating that a client who drinks six energy drinks daily has "caffeine use disorder, moderate." Her supervisor asks her to check DSM-5-TR. Which correction is accurate?',
    options: [
      { id: 'a', text: 'Caffeine use disorder exists but is only coded as mild in severity', isCorrect: false, rationale: 'DSM-5-TR has no official caffeine use disorder diagnosis, so no severity levels apply.' },
      { id: 'b', text: 'Caffeine use disorder is coded only if withdrawal has been observed', isCorrect: false, rationale: 'There is no official caffeine use disorder to code; observed withdrawal is a separate diagnosis.' },
      { id: 'c', text: 'Caffeine problems are coded as an other specified stimulant use disorder', isCorrect: false, rationale: 'Caffeine is not classed with stimulants such as amphetamine and cocaine for use disorder coding.' },
      { id: 'd', text: 'Caffeine use disorder is listed only as a condition for further study', isCorrect: true, rationale: 'DSM-5-TR places caffeine use disorder in Section III, though caffeine intoxication and withdrawal are diagnosable.' },
    ],
    rationale: 'In DSM-5-TR, caffeine intoxication and caffeine withdrawal are official diagnoses in the substance-related chapter, but caffeine use disorder appears only among the Conditions for Further Study in Section III. Counselors should not assign a diagnosis that is proposed for research rather than clinical use. Caffeine withdrawal, for example, involves headache plus symptoms such as fatigue, dysphoric mood, poor concentration or flu-like symptoms after abrupt cessation.',
    references: [{ source: 'DSM-5-TR', detail: 'Section III Conditions for Further Study: Caffeine Use Disorder; Caffeine-Related Disorders' }],
  },

  // ── neurodevelopmental disorders ──────────────────────────────────────────
  {
    id: 'nce-s-clf-249',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'For the past 5 months, a 7-year-old has had rapid eye blinking, facial grimacing and occasional grunting sounds that come and go. A medical cause and substance effects have been ruled out. Which diagnosis is MOST appropriate now?',
    options: [
      { id: 'a', text: 'Tourette\'s disorder, as he has both motor tics and a vocal tic', isCorrect: false, rationale: 'Tourette\'s disorder requires tics persisting more than 1 year since first onset; his tics began 5 months ago.' },
      { id: 'b', text: 'Persistent motor or vocal tic disorder, since tics recur daily', isCorrect: false, rationale: 'Persistent tic disorder needs more than 1 year of tics and either motor or vocal tics, not both.' },
      { id: 'c', text: 'Provisional tic disorder, as tics have lasted under one year', isCorrect: true, rationale: 'Motor and/or vocal tics present for less than 1 year since first onset, beginning before age 18, fit provisional tic disorder.' },
      { id: 'd', text: 'Stereotypic movement disorder, as the movements are repetitive', isCorrect: false, rationale: 'Stereotypies are rhythmic, often soothing movements starting earlier in childhood; sudden blinks and grunts are tics.' },
    ],
    rationale: 'Tic disorders are distinguished by tic type and duration. Provisional tic disorder covers single or multiple motor and/or vocal tics present for less than 1 year since first onset, beginning before age 18. Tourette\'s disorder requires both multiple motor tics and at least one vocal tic for more than 1 year, and persistent (chronic) tic disorder requires only motor or only vocal tics for more than 1 year.',
    references: [{ source: 'DSM-5-TR', detail: 'Tic Disorders: Provisional Tic Disorder Criteria A-D; comparison with Tourette\'s and persistent tic disorder' }],
  },
  {
    id: 'nce-s-clf-250',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'neurodevelopmental disorders',
    difficulty: 'medium',
    stem: 'A 7-year-old with average intelligence and normal vision is far behind peers in catching a ball, using scissors and writing legibly. His teachers say the clumsiness has been present since he was a toddler, and no neurological condition has been found. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Developmental coordination disorder affecting his motor skills', isCorrect: true, rationale: 'Motor skills well below age expectations, starting early and not due to intellectual, visual or neurological causes, fit DCD.' },
      { id: 'b', text: 'Specific learning disorder with impairment in written expression', isCorrect: false, rationale: 'His handwriting problem is part of a broader motor deficit, not a deficit in spelling, grammar or written organization.' },
      { id: 'c', text: 'Mild intellectual developmental disorder with motor slowness', isCorrect: false, rationale: 'He has average intelligence, so intellectual developmental disorder does not explain the motor deficits.' },
      { id: 'd', text: 'Attention-deficit/hyperactivity disorder, combined presentation', isCorrect: false, rationale: 'Clumsiness can co-occur with ADHD, but no inattention or hyperactivity symptoms are described.' },
    ],
    rationale: 'Developmental coordination disorder involves acquisition and execution of coordinated motor skills substantially below age expectations, interfering with daily life and school, with onset in the early developmental period. The deficits are not better explained by intellectual disability, visual impairment or a neurological condition. Because early motor development varies widely, DSM-5-TR notes that DCD is typically not diagnosed before age 5.',
    references: [{ source: 'DSM-5-TR', detail: 'Developmental Coordination Disorder: Criteria A-D and development and course' }],
  },

  // ── schizophrenia spectrum disorders ──────────────────────────────────────
  {
    id: 'nce-s-clf-251',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'hard',
    stem: 'For 8 months, a 25-year-old has shown marked avolition, flat affect and grossly disorganized behavior. A careful evaluation finds no delusions, hallucinations or disorganized speech at any point. Why does this presentation fail schizophrenia Criterion A?',
    options: [
      { id: 'a', text: 'Negative symptoms count toward Criterion A only after the first year', isCorrect: false, rationale: 'Negative symptoms can count toward Criterion A at any time; there is no one-year waiting rule.' },
      { id: 'b', text: 'One of the two must be delusions, hallucinations or disorganized speech', isCorrect: true, rationale: 'Criterion A requires two of five symptoms, and at least one must be delusions, hallucinations or disorganized speech.' },
      { id: 'c', text: 'Criterion A requires three or more of the five characteristic symptom groups', isCorrect: false, rationale: 'Only two of the five symptoms are needed; the problem is which symptoms are present, not how many.' },
      { id: 'd', text: 'Disorganized behavior is counted as a negative symptom, not a positive one', isCorrect: false, rationale: 'Grossly disorganized or catatonic behavior is its own Criterion A item and is not a negative symptom.' },
    ],
    rationale: 'Schizophrenia Criterion A requires two or more of five symptoms (delusions, hallucinations, disorganized speech, grossly disorganized or catatonic behavior, negative symptoms), each present for a significant portion of a 1-month period. At least one must be delusions, hallucinations or disorganized speech. A presentation limited to negative symptoms and disorganized behavior calls for further assessment of other causes, such as depression, catatonia or a medical condition.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizophrenia: Criterion A (at least one of items 1-3 required)' }],
  },
  {
    id: 'nce-s-clf-252',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'schizophrenia spectrum disorders',
    difficulty: 'easy',
    stem: 'A community educator preparing a talk for parents asks a counselor when schizophrenia most often first appears. Which statement BEST matches DSM-5-TR?',
    options: [
      { id: 'a', text: 'Most cases first begin in middle childhood, before puberty starts', isCorrect: false, rationale: 'Onset before adolescence is rare; childhood-onset schizophrenia is the exception, not the rule.' },
      { id: 'b', text: 'Onset peaks in the mid-40s, with similar ages for men and for women', isCorrect: false, rationale: 'Peak onset is in the 20s, and the timing differs by gender, with men tending to be earlier.' },
      { id: 'c', text: 'Onset typically occurs after age 60, mainly in women who live alone', isCorrect: false, rationale: 'Late-life onset is uncommon; new psychosis in older adults calls for a search for medical causes.' },
      { id: 'd', text: 'It usually starts in late teens to mid-30s, often earlier in men', isCorrect: true, rationale: 'Psychotic features typically emerge between the late teens and mid-30s, peaking in early-to-mid 20s for men, late 20s for women.' },
    ],
    rationale: 'DSM-5-TR describes typical onset of schizophrenia between the late teens and the mid-30s, with onset before adolescence rare. Peak age at onset is in the early-to-mid 20s for males and the late 20s for females. Many people show a prodromal phase of social withdrawal and declining functioning before psychotic symptoms appear, which is why early detection in adolescence and young adulthood matters.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizophrenia: Development and Course (age at onset and gender differences)' }],
  },

  // ── personality disorders ─────────────────────────────────────────────────
  {
    id: 'nce-s-clf-253',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'personality disorders',
    difficulty: 'medium',
    stem: 'A 38-year-old lab technician has always lived alone and spends free time on solitary hobbies. He says he has no wish for close relationships, gets little pleasure from social activity, and is unbothered by praise or criticism. He came to counseling only at his sister\'s urging. Which diagnosis is MOST consistent?',
    options: [
      { id: 'a', text: 'Avoidant personality disorder, given his long pattern of isolation', isCorrect: false, rationale: 'People with avoidant PD want relationships but avoid them from fear of rejection; he has no such desire.' },
      { id: 'b', text: 'Schizotypal personality disorder, as he is distant from other people', isCorrect: false, rationale: 'Schizotypal PD adds odd beliefs, perceptual distortions and eccentric behavior, none of which are described.' },
      { id: 'c', text: 'Social anxiety disorder, since he limits his social contact so much', isCorrect: false, rationale: 'Social anxiety centers on fear of scrutiny; he reports indifference to others, not fear of judgment.' },
      { id: 'd', text: 'Schizoid personality disorder, given his indifference to closeness', isCorrect: true, rationale: 'Neither desiring nor enjoying close relationships, choosing solitary activities and indifference to praise fit schizoid PD.' },
    ],
    rationale: 'Schizoid personality disorder is a pervasive pattern of detachment from social relationships and restricted emotional expression, with little desire for closeness and indifference to praise or criticism. The key differential is motivation: people with avoidant personality disorder long for connection but withdraw out of fear of rejection and inadequacy. Schizotypal personality disorder adds cognitive and perceptual distortions and eccentricity.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizoid Personality Disorder: Criterion A and differential diagnosis with avoidant and schizotypal PD' }],
  },
  {
    id: 'nce-s-clf-254',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'personality disorders',
    difficulty: 'hard',
    stem: 'A 16-year-old has shown chronic emptiness, unstable relationships, frantic efforts to avoid abandonment and impulsive self-harm across home, school and peer settings for 18 months. A colleague says personality disorders "cannot be diagnosed before 18." What does DSM-5-TR state?',
    options: [
      { id: 'a', text: 'No personality disorder at all may be diagnosed until the person turns 18', isCorrect: false, rationale: 'This overstates the rule; only antisocial personality disorder carries an age-18 minimum.' },
      { id: 'b', text: 'Most may apply under 18 if traits are pervasive and last at least 1 year', isCorrect: true, rationale: 'Personality disorders other than antisocial PD may be diagnosed in minors when features have lasted at least 1 year.' },
      { id: 'c', text: 'Borderline personality disorder alone may be diagnosed before age 18', isCorrect: false, rationale: 'The exception is not limited to borderline PD; other personality disorders may also be diagnosed in minors.' },
      { id: 'd', text: 'Personality disorders may apply under 18 after traits last 6 months', isCorrect: false, rationale: 'DSM-5-TR requires features to be present for at least 1 year, not 6 months, in individuals under 18.' },
    ],
    rationale: 'DSM-5-TR allows personality disorder diagnoses in children and adolescents when the maladaptive traits are pervasive, persistent and unlikely to be limited to a developmental stage or another mental disorder. Features must have been present for at least 1 year in someone under 18. Antisocial personality disorder is the exception: it requires age 18 or older, with conduct disorder evident before age 15.',
    references: [{ source: 'DSM-5-TR', detail: 'Personality Disorders: General Personality Disorder, development and course (diagnosis under age 18)' }],
  },

  // ── eating disorders ──────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-255',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'eating disorders',
    difficulty: 'easy',
    stem: 'An adult client meets criteria for anorexia nervosa, and her physician reports a current body mass index (BMI) of 16.4. Using DSM-5-TR severity ranges for adults, which specifier applies?',
    options: [
      { id: 'a', text: 'Moderate, since her BMI falls within 16 to 16.99', isCorrect: true, rationale: 'DSM-5-TR rates a BMI of 16 to 16.99 as moderate severity in adults.' },
      { id: 'b', text: 'Mild, since her BMI is still above the level of 16', isCorrect: false, rationale: 'Mild severity is a BMI of 17 or higher; 16.4 falls in the moderate range.' },
      { id: 'c', text: 'Severe, since her BMI is under the level of 17.5', isCorrect: false, rationale: 'Severe severity is a BMI of 15 to 15.99; 17.5 is not a DSM-5-TR cutoff.' },
      { id: 'd', text: 'Extreme, as any BMI under 18.5 is called extreme', isCorrect: false, rationale: 'Extreme severity is a BMI under 15; 18.5 marks the general underweight threshold.' },
    ],
    rationale: 'DSM-5-TR rates current anorexia nervosa severity in adults by BMI: mild is 17 or higher, moderate 16 to 16.99, severe 15 to 15.99, and extreme under 15. For children and adolescents, BMI percentiles are used instead. Severity may be raised to reflect clinical symptoms, functional disability and the need for supervision.',
    references: [{ source: 'DSM-5-TR', detail: 'Anorexia Nervosa: severity specifiers based on BMI' }],
  },
  {
    id: 'nce-s-clf-256',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'eating disorders',
    difficulty: 'medium',
    stem: 'Parents worry that their 18-month-old puts sand and paper in her mouth at the park. Their neighbor\'s 6-year-old has eaten paint chips and chalk daily for 2 months, which is not part of any family or cultural practice. Which conclusion about pica is MOST accurate?',
    options: [
      { id: 'a', text: 'Both children meet criteria, as each eats things that are not food', isCorrect: false, rationale: 'Mouthing objects is developmentally normal in toddlers; pica requires eating that is inappropriate for development.' },
      { id: 'b', text: 'Neither child can be diagnosed, as pica is a diagnosis for adults', isCorrect: false, rationale: 'Pica is diagnosed at any age, and it is often seen in childhood.' },
      { id: 'c', text: 'The 6-year-old may meet criteria; the toddler\'s mouthing is typical', isCorrect: true, rationale: 'Pica requires developmentally inappropriate eating of nonfood items for at least 1 month; a minimum age of 2 is suggested.' },
      { id: 'd', text: 'Only the toddler meets criteria, as such symptoms in older children fade', isCorrect: false, rationale: 'The toddler\'s behavior is developmentally expected, while the older child\'s persistent eating is not.' },
    ],
    rationale: 'Pica is persistent eating of nonnutritive, nonfood substances for at least 1 month that is inappropriate to the person\'s developmental level and not part of a culturally supported or socially normative practice. DSM-5-TR suggests a minimum age of 2 years to exclude normal mouthing of objects by infants and toddlers. Paint chips also raise concern for lead exposure, so medical evaluation is warranted.',
    references: [{ source: 'DSM-5-TR', detail: 'Pica: Criteria A-D and diagnostic features (minimum age of 2 years)' }],
  },

  // ── neurocognitive disorders ──────────────────────────────────────────────
  {
    id: 'nce-s-clf-257',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'hard',
    stem: 'A 74-year-old was diagnosed with Parkinson\'s disease 6 years ago after developing a tremor and slowed movement. Over the past year, he has developed gradual problems with attention, planning and memory that now interfere with paying bills. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Neurocognitive disorder with Lewy bodies, since he has parkinsonism', isCorrect: false, rationale: 'In Lewy body NCD, cognitive decline comes before or within about a year of motor signs, not years later.' },
      { id: 'b', text: 'Major frontotemporal neurocognitive disorder, given his poor planning', isCorrect: false, rationale: 'Frontotemporal NCD features early behavioral or language change, not decline years after established Parkinson\'s.' },
      { id: 'c', text: 'Major neurocognitive disorder due to Parkinson\'s disease', isCorrect: true, rationale: 'Decline that develops gradually in the setting of long-established Parkinson\'s disease fits NCD due to Parkinson\'s.' },
      { id: 'd', text: 'Delirium caused by his Parkinson\'s medications and motor symptoms', isCorrect: false, rationale: 'Delirium has an acute onset with fluctuating attention; his decline has been gradual over a year.' },
    ],
    rationale: 'Neurocognitive disorder due to Parkinson\'s disease is diagnosed when cognitive decline arises insidiously in the setting of established Parkinson\'s disease. When cognitive decline begins before, or within about one year of, the onset of parkinsonian motor signs, NCD with Lewy bodies is more likely. The timing of motor versus cognitive symptoms is therefore the key differential clue.',
    references: [{ source: 'DSM-5-TR', detail: 'Major or Mild Neurocognitive Disorder Due to Parkinson\'s Disease: criteria and differential diagnosis with Lewy bodies' }],
  },
  {
    id: 'nce-s-clf-258',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'neurocognitive disorders',
    difficulty: 'medium',
    stem: 'A 34-year-old construction worker lost consciousness briefly after a fall from scaffolding 5 months ago. Since regaining consciousness, he has had persistent problems with attention, slowed thinking and memory, and he struggles to follow work instructions. Which diagnosis should the counselor consider FIRST?',
    options: [
      { id: 'a', text: 'Neurocognitive disorder due to traumatic brain injury', isCorrect: true, rationale: 'Deficits beginning right after a head injury with loss of consciousness and persisting past the acute period fit NCD due to TBI.' },
      { id: 'b', text: 'Adjustment disorder with anxiety following his work fall', isCorrect: false, rationale: 'Adjustment disorder involves emotional or behavioral distress, not objective cognitive deficits after head injury.' },
      { id: 'c', text: 'Major depressive disorder causing his memory complaints', isCorrect: false, rationale: 'Depression can impair concentration, but no mood symptoms are described and a head injury explains the onset.' },
      { id: 'd', text: 'Mild neurocognitive disorder due to Alzheimer\'s disease', isCorrect: false, rationale: 'Alzheimer\'s disease shows insidious, gradual onset, usually in late life, not sudden deficits after an injury.' },
    ],
    rationale: 'Neurocognitive disorder due to traumatic brain injury requires evidence of a TBI with loss of consciousness, posttraumatic amnesia, disorientation or confusion, or neurological signs. The cognitive disorder must present immediately after the injury or after recovery of consciousness and persist past the acute post-injury period. Counselors should coordinate with medical providers for neuropsychological evaluation.',
    references: [{ source: 'DSM-5-TR', detail: 'Major or Mild Neurocognitive Disorder Due to Traumatic Brain Injury: Criteria A-C' }],
  },

  // ── sleep-wake concerns ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-259',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'sleep-wake concerns',
    difficulty: 'medium',
    stem: 'A 21-year-old falls asleep in class and at meals several times a day despite sleeping 8 hours a night, a pattern lasting 5 months. When she laughs hard, her knees suddenly buckle and her jaw goes slack for a few seconds, though she stays fully aware. Which condition do these features MOST suggest?',
    options: [
      { id: 'a', text: 'Hypersomnolence disorder with long sleep and daytime naps', isCorrect: false, rationale: 'Hypersomnolence disorder involves excessive sleepiness but not cataplexy triggered by laughter.' },
      { id: 'b', text: 'Narcolepsy, with episodes of cataplexy set off by laughing', isCorrect: true, rationale: 'Irresistible sleep episodes plus brief loss of muscle tone with laughter, consciousness intact, point to narcolepsy.' },
      { id: 'c', text: 'Panic disorder, with sudden weak spells during strong emotion', isCorrect: false, rationale: 'Panic attacks involve surges of fear with autonomic symptoms, not laughter-triggered loss of muscle tone.' },
      { id: 'd', text: 'A seizure disorder with brief absences when she gets excited', isCorrect: false, rationale: 'Absence seizures impair awareness; in cataplexy the person remains conscious throughout.' },
    ],
    rationale: 'Narcolepsy involves recurrent periods of irrepressible need to sleep, lapsing into sleep or napping within the same day, at least three times per week for 3 months. It also requires cataplexy, hypocretin deficiency, or characteristic REM findings on sleep studies. Cataplexy is brief, sudden bilateral loss of muscle tone with preserved consciousness, often set off by laughter or joking, and should prompt referral to a sleep specialist.',
    references: [{ source: 'DSM-5-TR', detail: 'Narcolepsy: Criteria A-B (cataplexy)' }],
  },
  {
    id: 'nce-s-clf-260',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'sleep-wake concerns',
    difficulty: 'easy',
    stem: 'Parents say their 6-year-old sits up screaming about an hour after falling asleep several nights a month. He is sweaty, wide-eyed and hard to comfort, then settles back to sleep. In the morning he remembers nothing. Which explanation BEST fits?',
    options: [
      { id: 'a', text: 'Nightmare disorder, since he wakes up afraid during the night', isCorrect: false, rationale: 'Nightmares occur later in the night in REM sleep, and the child wakes fully and recalls the dream.' },
      { id: 'b', text: 'Panic attacks at night, since he shows sweating and great fear', isCorrect: false, rationale: 'Nocturnal panic involves waking fully alert from sleep, not being unresponsive with amnesia.' },
      { id: 'c', text: 'Separation anxiety disorder, as he becomes upset at bedtime', isCorrect: false, rationale: 'He is not upset at bedtime about separation; the episodes arise from deep sleep.' },
      { id: 'd', text: 'Sleep terrors, a non-REM arousal pattern common in children', isCorrect: true, rationale: 'Screaming arousals early in the night with poor response to comfort and no recall fit sleep terrors.' },
    ],
    rationale: 'Sleep terrors are a type of non-rapid eye movement sleep arousal disorder: abrupt terrified arousals, usually in the first third of the night, often beginning with a scream, with autonomic arousal, poor response to comfort, and little or no recall. They are most common in childhood and usually decrease with age. Nightmares, by contrast, occur in REM sleep later in the night, and the person wakes fully and remembers the dream.',
    references: [{ source: 'DSM-5-TR', detail: 'Non-Rapid Eye Movement Sleep Arousal Disorders: sleep terror type; differential with nightmare disorder' }],
  },
  {
    id: 'nce-s-clf-261',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'sleep-wake concerns',
    difficulty: 'medium',
    stem: 'A 48-year-old in counseling for insomnia says that most evenings when she sits or lies down she feels a crawling, uncomfortable urge to move her legs. Walking around eases it, and it is far worse at night than in the morning. This has happened 4 nights a week for 6 months. Which condition should the counselor suspect?',
    options: [
      { id: 'a', text: 'Restless legs syndrome, given the evening urge eased by moving', isCorrect: true, rationale: 'An urge to move the legs that starts with rest, is relieved by movement and is worse at night defines restless legs syndrome.' },
      { id: 'b', text: 'Generalized anxiety disorder with restlessness during the day', isCorrect: false, rationale: 'GAD restlessness is tied to worry, not leg sensations that follow rest and are worst at night.' },
      { id: 'c', text: 'Akathisia from a medication, since she feels inner restlessness', isCorrect: false, rationale: 'Akathisia follows a medication start or change and lacks the clear evening pattern; none is described.' },
      { id: 'd', text: 'Insomnia disorder alone, since her leg discomfort is from fatigue', isCorrect: false, rationale: 'Insomnia is not diagnosed alone when another sleep-wake disorder, here RLS, better explains the sleep problem.' },
    ],
    rationale: 'Restless legs syndrome is an urge to move the legs, usually with uncomfortable sensations, that begins or worsens during rest, is partly or fully relieved by movement, and is worse in the evening or night. Symptoms occur at least three times per week for at least 3 months and cause distress or impairment. Because RLS often presents as trouble falling asleep, counselors should ask about leg sensations and refer for medical evaluation.',
    references: [{ source: 'DSM-5-TR', detail: 'Restless Legs Syndrome: Criteria A-C' }],
  },

  // ── self-injury ───────────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-262',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'medium',
    stem: 'A 22-year-old who burns herself when overwhelmed also reports passive thoughts of death. Her previous counselor had her sign a "no-harm contract" promising not to hurt herself. She asks whether they should sign one again. Which response BEST reflects current practice?',
    options: [
      { id: 'a', text: 'Sign a new contract, since a written promise reliably lowers her risk', isCorrect: false, rationale: 'No-harm contracts lack evidence of reducing self-harm or suicide and can discourage honest disclosure.' },
      { id: 'b', text: 'Sign one only if she agrees to call the counselor before each urge', isCorrect: false, rationale: 'Adding conditions does not fix the contract\'s weak evidence, and it shifts focus away from building her own coping.' },
      { id: 'c', text: 'Build a written safety plan with her triggers, coping and contacts', isCorrect: true, rationale: 'Collaborative safety planning names warning signs, coping steps, supports and crisis resources and has research support.' },
      { id: 'd', text: 'Skip planning for now, as her self-harm is not suicidal in its intent', isCorrect: false, rationale: 'Self-injury plus thoughts of death calls for active risk management, not delay.' },
    ],
    rationale: 'No-harm or no-suicide contracts are not supported by evidence and may give a false sense of security. A collaborative safety plan, such as the Stanley-Brown Safety Planning Intervention, lists warning signs, internal coping strategies, social contacts and settings for distraction, people to ask for help, professional and crisis contacts, and steps to make the environment safer. Because NSSI raises later suicide risk, ongoing risk assessment remains part of care.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Safety Planning Intervention components; contrast with no-suicide contracts' }],
  },
  {
    id: 'nce-s-clf-263',
    domain: 'clinical_focus',
    cacrep: 'assessment',
    topic: 'self-injury',
    difficulty: 'medium',
    stem: 'A counselor reviewing an intake form sees that a 20-year-old has several piercings, a large tattoo and ceremonial scarring from a coming-of-age ritual in her community. She denies any other injury to her body. How should the counselor classify these behaviors?',
    options: [
      { id: 'a', text: 'As nonsuicidal self-injury, since each one caused deliberate tissue harm', isCorrect: false, rationale: 'The proposed NSSI criteria exclude socially sanctioned behaviors such as piercing, tattooing and ritual scarring.' },
      { id: 'b', text: 'As socially sanctioned practices that the NSSI criteria exclude', isCorrect: true, rationale: 'Body modification and culturally sanctioned rituals are excluded from nonsuicidal self-injury.' },
      { id: 'c', text: 'As NSSI only if she reports feeling relief after each of the procedures', isCorrect: false, rationale: 'Relief does not convert a socially sanctioned practice into NSSI; the exclusion applies regardless.' },
      { id: 'd', text: 'As a warning sign that requires a full suicide risk assessment today', isCorrect: false, rationale: 'Cultural and cosmetic body modification is not itself a suicide warning sign; routine screening suffices.' },
    ],
    rationale: 'The DSM-5-TR proposed criteria for nonsuicidal self-injury disorder state that the behavior is not socially sanctioned, such as body piercing, tattooing or part of a religious or cultural ritual, and is not restricted to picking a scab or nail biting. Counselors assess the function and context of body changes with cultural humility rather than labeling all tissue damage as self-injury.',
    references: [{ source: 'DSM-5-TR', detail: 'Conditions for Further Study: Nonsuicidal Self-Injury Disorder, Criterion E (socially sanctioned behavior excluded)' }],
  },
  {
    id: 'nce-s-clf-264',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'self-injury',
    difficulty: 'easy',
    stem: 'A school district asks its counselors when to begin prevention programming about nonsuicidal self-injury. According to DSM-5-TR, at what point in development does NSSI MOST often begin?',
    options: [
      { id: 'a', text: 'In early childhood, before children start attending school', isCorrect: false, rationale: 'Self-injury in very young children is uncommon and often linked to developmental conditions, not typical NSSI.' },
      { id: 'b', text: 'In middle adulthood, often after job or relationship losses', isCorrect: false, rationale: 'Onset in midlife is uncommon; NSSI most often starts much earlier.' },
      { id: 'c', text: 'In later adulthood, often alongside chronic medical illness', isCorrect: false, rationale: 'Older adults who self-harm are a high-risk group, but late life is not the typical onset period.' },
      { id: 'd', text: 'In the early teen years, and it can go on for many years', isCorrect: true, rationale: 'DSM-5-TR notes NSSI most often begins in the early teen years and may continue for many years.' },
    ],
    rationale: 'DSM-5-TR text on nonsuicidal self-injury notes that it most often starts in the early teen years and can continue for many years. Hospital admissions for NSSI peak around ages 20 to 29 before declining. School-based prevention and staff training in the middle-school years therefore target the developmental window when NSSI typically begins.',
    references: [{ source: 'DSM-5-TR', detail: 'Conditions for Further Study: Nonsuicidal Self-Injury Disorder, Development and Course' }],
  },

  // ── psychopharmacology basics for counselors ──────────────────────────────
  {
    id: 'nce-s-clf-265',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'medium',
    stem: 'A 17-year-old began an antidepressant prescribed by his pediatrician 2 weeks ago. His mother asks the counselor what the FDA boxed warning on the medication means for her son. Which response is MOST accurate?',
    options: [
      { id: 'a', text: 'Watch for new or worse suicidal thinking, mainly early in treatment', isCorrect: true, rationale: 'The boxed warning notes increased suicidal thoughts and behaviors in youth, calling for close monitoring early on.' },
      { id: 'b', text: 'It means antidepressants cannot be given to anyone under age eighteen', isCorrect: false, rationale: 'The warning does not ban use in youth; some antidepressants are approved for adolescents with monitoring.' },
      { id: 'c', text: 'It is about weight gain, so his diet should be checked each week', isCorrect: false, rationale: 'The antidepressant boxed warning concerns suicidality in young people, not weight change.' },
      { id: 'd', text: 'It is about risk only for adults over 65, so it does not apply to him', isCorrect: false, rationale: 'The warning applies to children, adolescents and young adults under 25, not older adults.' },
    ],
    rationale: 'The FDA boxed warning on antidepressants states that, in short-term studies, they increased the risk of suicidal thinking and behavior in children, adolescents and young adults under age 25. It calls for close monitoring for worsening mood, agitation or suicidality, especially in the first months of treatment and after dose changes. Counselors educate families, encourage communication with the prescriber and monitor risk.',
    references: [{ source: 'APA CPG', detail: 'Depression across the lifespan: antidepressants in adolescents and suicidality monitoring' }, { source: 'FDA Antidepressant Boxed Warning', detail: '2007 labeling revision: suicidality warning extended through age 24; close monitoring early in treatment' }],
  },
  {
    id: 'nce-s-clf-266',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'easy',
    stem: 'A client who started a new antipsychotic last week arrives with a high fever, heavy sweating, very stiff muscles, a racing heart and confusion. Which action should the counselor take FIRST?',
    options: [
      { id: 'a', text: 'Help the client cut the dose in half until a prescriber can be reached', isCorrect: false, rationale: 'Counselors do not adjust medication, and these signs need emergency care, not a dose change.' },
      { id: 'b', text: 'Arrange emergency medical care for possible neuroleptic malignant syndrome', isCorrect: true, rationale: 'Fever, rigidity, autonomic instability and confusion after antipsychotic start suggest NMS, a medical emergency.' },
      { id: 'c', text: 'Treat the confusion as psychosis and schedule a session for later in the week', isCorrect: false, rationale: 'Fever, rigidity and confusion point to a medical crisis; delay could be fatal.' },
      { id: 'd', text: 'Suggest rest and fluids for a likely viral illness and check in tomorrow', isCorrect: false, rationale: 'Muscle rigidity with confusion after a new antipsychotic is not a routine illness and needs urgent evaluation.' },
    ],
    rationale: 'Neuroleptic malignant syndrome is a rare, potentially fatal reaction to dopamine-blocking agents, most often antipsychotics. Hallmarks are high fever, severe muscle rigidity, altered mental status and autonomic instability (sweating, fast heart rate, unstable blood pressure), usually within days of starting or raising the dose. Counselors recognize it as a medical emergency and arrange immediate care.',
    references: [{ source: 'DSM-5-TR', detail: 'Medication-Induced Movement Disorders and Other Adverse Effects of Medication: Neuroleptic Malignant Syndrome' }],
  },
];
