// tools/nce/seed/clinical-focus-6.js
// NCE practice items, batch 3 — Areas of Clinical Focus (blueprint topics 15–28).
module.exports = [
  // ── developmental life transitions ─────────────────────────────────────────
  {
    id: 'nce-s-clf-149',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'developmental life transitions',
    difficulty: 'medium',
    stem: 'A 53-year-old client says that since her youngest child left for college, she wanders the house feeling useless. Her husband, by contrast, is enjoying the extra time together. Based on life-span research on the empty nest, which factor MOST increases the risk that launching children will be a painful transition?',
    options: [
      { id: 'a', text: 'Having a spouse who adjusts to the change faster', isCorrect: false, rationale: 'A spouse adapting faster may highlight the contrast, but research does not identify it as the main risk factor.' },
      { id: 'b', text: 'An identity built mainly around the parenting role', isCorrect: true, rationale: 'Empty-nest distress is most likely when a parent has invested identity chiefly in parenting and has few other roles to turn to.' },
      { id: 'c', text: 'Launching the last child after the age of fifty', isCorrect: false, rationale: 'Timing that fits social expectations (on-time launching) is usually easier; age over fifty is not itself the risk factor.' },
      { id: 'd', text: 'Children who move to a college far from the home', isCorrect: false, rationale: 'Distance may add sadness, but most parents adjust well regardless; the key risk lies in how central parenting is to the self.' },
    ],
    rationale: 'Most parents adjust well to the empty nest, and many report relief and improved marital satisfaction. Distress is more likely when parenting has been the core of a person\'s identity, when other roles are thin, or when children leave off-time. Counseling can help the client build roles and meaning beyond active parenting.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Middle adulthood: launching children and the empty nest' }],
  },
  {
    id: 'nce-s-clf-150',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'developmental life transitions',
    difficulty: 'easy',
    stem: 'Parents worry that their 22-year-old son has "failed to launch." In two years he has moved apartments three times, switched jobs twice, and ended two relationships. He is curious and hopeful about his future. Within Arnett\'s theory of emerging adulthood, how is this pattern BEST understood?',
    options: [
      { id: 'a', text: 'Instability, a typical feature of emerging adulthood', isCorrect: true, rationale: 'Arnett names instability in love, work and residence as one of the defining features of emerging adulthood.' },
      { id: 'b', text: 'Identity diffusion that shows his development stalled', isCorrect: false, rationale: 'Diffusion (Marcia) means neither exploring nor committing; he is actively exploring, so the label does not fit.' },
      { id: 'c', text: 'Role confusion left over from an unresolved adolescence', isCorrect: false, rationale: 'Arnett frames these moves as normative for the age period, not as a failure of Erikson\'s adolescent stage.' },
      { id: 'd', text: 'Delayed launching caused by overinvolved, enmeshed parents', isCorrect: false, rationale: 'Nothing in the stem points to enmeshment; frequent change is expected in this period.' },
    ],
    rationale: 'Arnett describes emerging adulthood (roughly ages 18–25) by five features: identity explorations, instability, self-focus, feeling in-between, and possibilities. Frequent changes of residence, work and partners are expected. Counselors can reframe parents\' worry while still supporting the young adult\'s goal setting.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Emerging adulthood (Arnett): features of the period' }],
  },
  {
    id: 'nce-s-clf-151',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'developmental life transitions',
    difficulty: 'medium',
    stem: 'A 47-year-old client works full time, is raising two teenagers, and now helps her mother, who has early dementia, with meals, bills and appointments. She is exhausted, snaps at her children, and feels guilty that she is "failing everyone." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Urge her to move her mother into a memory care facility', isCorrect: false, rationale: 'Placement may become an option, but directing it first ignores her values and skips assessment.' },
      { id: 'b', text: 'Explore early conflicts with her mother that fuel the guilt', isCorrect: false, rationale: 'Family history may matter later, but her current overload and well-being take priority.' },
      { id: 'c', text: 'Assess her caregiving load and link her to respite support', isCorrect: true, rationale: 'For a "sandwich generation" caregiver, assessing strain and connecting her with respite, services and shared care is the practical first step.' },
      { id: 'd', text: 'Advise her to cut back her hours at work to free up time', isCorrect: false, rationale: 'Reducing work may add financial stress and is a decision for her after options are explored.' },
    ],
    rationale: 'Midlife adults who care for both children and aging parents (the "sandwich generation") face role overload that raises the risk of depression and burnout. Counselors first assess the demands and resources, then help the client mobilize respite, family sharing of tasks and community services, and address guilt and self-care.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Middle adulthood: caring for aging parents' }],
  },
  {
    id: 'nce-s-clf-152',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'developmental life transitions',
    difficulty: 'medium',
    stem: 'Four months after the birth of their first child, a couple seeks counseling. They argue about night feedings and chores, and both say they feel less close than before. Which statement BEST reflects research on the transition to parenthood?',
    options: [
      { id: 'a', text: 'Their conflict signals a poor match that a baby has exposed', isCorrect: false, rationale: 'A dip in satisfaction after a first birth is common and does not by itself show the couple is mismatched.' },
      { id: 'b', text: 'Satisfaction usually rises soon after a first child arrives', isCorrect: false, rationale: 'On average, relationship satisfaction declines modestly rather than rises after the first birth.' },
      { id: 'c', text: 'Strain mostly reflects postpartum mood in the birth parent', isCorrect: false, rationale: 'Postpartum mood should be screened, but strain on the couple is common even without a mood disorder.' },
      { id: 'd', text: 'Satisfaction often dips, less so when care is shared fairly', isCorrect: true, rationale: 'Research shows a common decline in satisfaction that is smaller when partners share caregiving and chores in a way both see as fair.' },
    ],
    rationale: 'Studies of the transition to parenthood find that relationship satisfaction often declines after a first child, driven by sleep loss, role change and disputes over the division of labor. Couples who share child care and household tasks fairly, and who hold realistic expectations, show less decline. Counseling can target these modifiable factors.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Early adulthood: transition to parenthood and marital satisfaction' }],
  },

  // ── chronic illness and disability ────────────────────────────────────────
  {
    id: 'nce-s-clf-153',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'chronic illness and disability',
    difficulty: 'hard',
    stem: 'A 39-year-old client with relapsing-remitting multiple sclerosis had seemed at peace with her diagnosis. After a new relapse, she is again angry, tearful and asking "why me?" Her counselor wonders if earlier progress was lost. Which understanding of adjustment to chronic illness BEST fits?',
    options: [
      { id: 'a', text: 'Adjustment is often cyclical, and reactions return as the illness changes', isCorrect: true, rationale: 'Contemporary adjustment models describe nonlinear, recurring reactions, especially when the illness course shifts.' },
      { id: 'b', text: 'Her anger shows she skipped a stage and must now go back and finish it', isCorrect: false, rationale: 'Rigid stage sequences are not supported; people do not need to complete stages in a fixed order.' },
      { id: 'c', text: 'Once a client reaches acceptance, a return of grief signals a new disorder', isCorrect: false, rationale: 'Renewed grief after a relapse is expected, not evidence of a new mental disorder.' },
      { id: 'd', text: 'Her distress points to a failed treatment that calls for a higher level of care', isCorrect: false, rationale: 'An expected emotional response to a relapse does not by itself warrant a higher level of care.' },
    ],
    rationale: 'Models of psychosocial adaptation to chronic illness and disability describe reactions such as shock, anxiety, depression, anger and acknowledgment as overlapping and recurring rather than a fixed sequence. Changes in the illness, such as a relapse, can bring earlier reactions back. Counselors normalize this cycling and help the client re-engage coping resources.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Rehabilitation counseling: psychosocial adaptation to chronic illness and disability' }],
    reviewNote: 'Confirm Gladding (8th ed.) covers nonlinear psychosocial adaptation (e.g., Livneh & Antonak); a rehabilitation counseling text may be a better citation.',
  },
  {
    id: 'nce-s-clf-154',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'chronic illness and disability',
    difficulty: 'medium',
    stem: 'A 50-year-old with chronic low back pain for three years also meets criteria for major depressive disorder. He tells the counselor, "Once the doctors fix my back, my mood will fix itself, so counseling can wait." Which response BEST reflects current understanding of chronic pain and depression?',
    options: [
      { id: 'a', text: 'Agree to pause counseling until medical treatment of the pain ends', isCorrect: false, rationale: 'Waiting leaves the depression untreated, and the two conditions reinforce each other.' },
      { id: 'b', text: 'Explain that his pain is likely psychological and needs no medical care', isCorrect: false, rationale: 'Chronic pain is real and needs medical care; implying it is "all in his head" damages trust.' },
      { id: 'c', text: 'Explain that pain and low mood feed each other and both can be treated', isCorrect: true, rationale: 'Pain and depression are linked in both directions; psychological care can lift mood and lessen pain\'s grip on daily life.' },
      { id: 'd', text: 'Refer him to a pain clinic and close his counseling case for now', isCorrect: false, rationale: 'Coordinating with a pain clinic can help, but closing the case abandons treatment of his depression.' },
    ],
    rationale: 'Chronic pain and depression are closely linked, each worsening sleep, activity, and outlook in a cycle. Guidelines for chronic pain recommend psychological approaches such as CBT or ACT alongside medical care to reduce distress and disability. Counselors treat the depression now and coordinate with the medical team rather than waiting for the pain to resolve.',
    references: [{ source: 'NICE guidelines', detail: 'NG193 Chronic pain (primary and secondary) in over 16s: psychological therapy (CBT, ACT)' }],
  },
  {
    id: 'nce-s-clf-155',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'chronic illness and disability',
    difficulty: 'easy',
    stem: 'A counselor works with a 68-year-old man who has cared for his wife with Parkinson\'s disease for six years. He reports feeling trapped, worn out and resentful, and the counselor wants a standard measure of how much strain caregiving places on him. Which instrument is designed for this purpose?',
    options: [
      { id: 'a', text: 'Mini-Mental State Examination', isCorrect: false, rationale: 'The MMSE screens cognitive impairment, not the strain caregiving places on a caregiver.' },
      { id: 'b', text: 'Zarit Burden Interview', isCorrect: true, rationale: 'The Zarit Burden Interview measures perceived caregiver burden across health, finances, social life and the relationship.' },
      { id: 'c', text: 'Geriatric Depression Scale', isCorrect: false, rationale: 'The GDS screens for depression in older adults; it does not measure caregiving strain.' },
      { id: 'd', text: 'Beck Hopelessness Scale', isCorrect: false, rationale: 'The BHS measures negative expectations about the future, not caregiver burden.' },
    ],
    rationale: 'Caregiver burden is the physical, emotional, social and financial strain of caring for an ill or disabled person. The Zarit Burden Interview is a widely used self-report measure of it. High burden predicts caregiver depression and poorer health, so counselors screen for it and link caregivers to respite, support groups and services.',
    references: [{ source: 'Hays (Assessment)', detail: 'Assessment with older adults and caregivers: caregiver burden measures' }],
    reviewNote: 'Confirm Hays (Assessment) names the Zarit Burden Interview; the fact is standard but the citation locator is uncertain.',
  },

  // ── spiritual and religious concerns ──────────────────────────────────────
  {
    id: 'nce-s-clf-156',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'easy',
    stem: 'A counselor uses the FICA tool to take a brief spiritual history at intake. The letters stand for Faith or belief, Importance or influence, a third element, and Address in care. What does the "C" ask about?',
    options: [
      { id: 'a', text: 'Conflict between faith and treatment', isCorrect: false, rationale: 'Conflicts may surface, but "C" in FICA does not stand for conflict.' },
      { id: 'b', text: 'Coping skills learned from faith', isCorrect: false, rationale: 'Faith-based coping may arise in the interview, but it is not what "C" names.' },
      { id: 'c', text: 'Commitment to religious practice', isCorrect: false, rationale: 'Level of practice may come up under importance, but "C" is not commitment.' },
      { id: 'd', text: 'Community the person belongs to', isCorrect: true, rationale: 'The "C" in FICA asks whether the client is part of a spiritual or religious community and whether it is a support.' },
    ],
    rationale: 'Puchalski\'s FICA is a brief spiritual history: Faith or belief (what gives meaning), Importance or influence (how beliefs shape life and health choices), Community (membership in and support from a spiritual community), and Address in care (how the client wants these addressed in treatment). It lets counselors assess spirituality respectfully without imposing values.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Spirituality in counseling: spiritual assessment' }],
    reviewNote: 'FICA (Puchalski) components are standard; confirm Gladding mentions FICA or substitute a spirituality-in-counseling source.',
  },
  {
    id: 'nce-s-clf-157',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'hard',
    stem: 'After a cancer diagnosis, a 61-year-old devout client says, "God is punishing me for my sins. Maybe this is what I deserve." She has stopped attending services and feels abandoned. In Pargament\'s research on religious coping, how is her response BEST classified, and what is it linked to?',
    options: [
      { id: 'a', text: 'Negative religious coping, tied to poorer adjustment', isCorrect: true, rationale: 'Punishing-God reappraisals and feeling abandoned by God are negative religious coping, which predicts more distress.' },
      { id: 'b', text: 'Positive religious coping, tied to better adjustment', isCorrect: false, rationale: 'Positive coping includes benevolent reappraisals and seeking spiritual support, not a punishing-God view.' },
      { id: 'c', text: 'A deferring coping style, tied to passive acceptance', isCorrect: false, rationale: 'Deferring means leaving problems to God; her statement is about punishment and abandonment.' },
      { id: 'd', text: 'Spiritual bypassing, tied to avoidance of emotion', isCorrect: false, rationale: 'Spiritual bypassing uses spiritual ideas to avoid feelings; she is expressing distress, not avoiding it.' },
    ],
    rationale: 'Pargament distinguished positive religious coping (benevolent reappraisal, seeking spiritual support, collaborative problem solving) from negative religious coping (punishing-God reappraisal, feeling abandoned by God, questioning God\'s power). Negative religious coping is associated with greater depression and poorer health outcomes. Counselors assess for it and may collaborate with clergy when the client wishes.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Spirituality in counseling: religious coping' }],
    reviewNote: 'Pargament\'s positive/negative religious coping (RCOPE) is well established; confirm the Gladding locator or cite a spirituality-specific source.',
  },
  {
    id: 'nce-s-clf-158',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'medium',
    stem: 'Eight months after her infant died, a client who has always been devout says she is furious at God and ashamed of feeling that way. She fears her anger means she has lost her faith. The counselor does not share her religion. Which response is MOST appropriate?',
    options: [
      { id: 'a', text: 'Suggest she set aside spiritual topics until her grief eases', isCorrect: false, rationale: 'Avoiding her spiritual struggle leaves a central part of her grief unaddressed.' },
      { id: 'b', text: 'Reassure her that a loving God would not want her to be angry', isCorrect: false, rationale: 'This imposes a theological view and may deepen her shame.' },
      { id: 'c', text: 'Normalize anger at God as a common struggle and explore it', isCorrect: true, rationale: 'Spiritual struggles such as anger at God are common after loss; exploring them openly reduces shame and supports meaning making.' },
      { id: 'd', text: 'Refer her to clergy since faith is outside the counselor\'s role', isCorrect: false, rationale: 'Clergy consultation may help with consent, but spiritual concerns are within a counselor\'s scope when they affect well-being.' },
    ],
    rationale: 'Spiritual struggles, such as anger at God, doubt, or conflict with a faith community, are common after trauma and loss and are linked to distress when unaddressed. Counselors respond within the client\'s own framework, normalize the struggle, and explore it without imposing beliefs. Collaboration with clergy is an option the client can choose.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Spirituality in counseling: addressing spiritual concerns' }, { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },

  // ── sleep-wake concerns ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-159',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'sleep-wake concerns',
    difficulty: 'easy',
    stem: 'A veteran with PTSD has the same trauma-related nightmare several nights a week. His counselor has him write down the dream, change the storyline in any way he chooses, and rehearse the new version in imagery for a few minutes each day. Which intervention is this?',
    options: [
      { id: 'a', text: 'Cognitive processing therapy', isCorrect: false, rationale: 'CPT targets stuck points in beliefs about the trauma; it does not rescript dreams.' },
      { id: 'b', text: 'Imagery rehearsal therapy', isCorrect: true, rationale: 'Imagery rehearsal therapy has clients change a recurring nightmare and rehearse the new version while awake.' },
      { id: 'c', text: 'Stimulus control therapy', isCorrect: false, rationale: 'Stimulus control re-links the bed with sleep; it does not change dream content.' },
      { id: 'd', text: 'Systematic desensitization', isCorrect: false, rationale: 'Systematic desensitization pairs relaxation with a fear hierarchy, not dream rescripting.' },
    ],
    rationale: 'Imagery rehearsal therapy (IRT) treats recurring nightmares, including PTSD-related ones. The client rewrites the nightmare in any way desired and rehearses the new script while awake, which often reduces nightmare frequency and distress. It can be used alongside trauma-focused therapy.',
    references: [{ source: 'VA/DoD CPG', detail: 'Management of PTSD: treatment of trauma-related nightmares (imagery rehearsal therapy)' }],
    reviewNote: 'Confirm the strength of the current VA/DoD PTSD CPG recommendation on IRT for nightmares; the item only asks for the definition.',
  },
  {
    id: 'nce-s-clf-160',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'sleep-wake concerns',
    difficulty: 'easy',
    stem: 'A 56-year-old client being treated for depression says he sleeps eight hours yet nods off while driving. His wife says he snores loudly and sometimes stops breathing and gasps at night. He also wakes with headaches and has high blood pressure. What should the counselor do?',
    options: [
      { id: 'a', text: 'Begin CBT-I with sleep restriction to consolidate sleep', isCorrect: false, rationale: 'Sleep restriction can worsen sleepiness and is not suited to a likely breathing disorder.' },
      { id: 'b', text: 'Teach sleep hygiene and review it again in two weeks', isCorrect: false, rationale: 'Sleep hygiene does not treat a possible breathing disorder, and the delay is unsafe given drowsy driving.' },
      { id: 'c', text: 'Treat the sleepiness as a symptom of his depression', isCorrect: false, rationale: 'Snoring, apneas and morning headaches point to a medical sleep problem, not only depression.' },
      { id: 'd', text: 'Refer him to his physician for a sleep apnea evaluation', isCorrect: true, rationale: 'Loud snoring, witnessed breathing pauses, sleepiness and hypertension suggest obstructive sleep apnea, which needs medical evaluation.' },
    ],
    rationale: 'Obstructive sleep apnea hypopnea is a breathing-related sleep disorder marked by snoring, gasping or breathing pauses during sleep, and daytime sleepiness despite adequate sleep time. It is confirmed by polysomnography and treated medically. Untreated apnea can worsen mood and raises accident risk, so counselors refer promptly and continue mental health care.',
    references: [{ source: 'DSM-5-TR', detail: 'Breathing-related sleep disorders: obstructive sleep apnea hypopnea' }],
  },

  // ── career: retirement and older workers ──────────────────────────────────
  {
    id: 'nce-s-clf-161',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 66-year-old retired engineer spent his first months of retirement traveling and finishing house projects. Now, about a year in, he feels let down, bored and unsure what his days are for. In Atchley\'s phases of retirement, which phase is he MOST likely in?',
    options: [
      { id: 'a', text: 'Honeymoon', isCorrect: false, rationale: 'The honeymoon phase is the early period of freedom and activity he has already moved past.' },
      { id: 'b', text: 'Reorientation', isCorrect: false, rationale: 'Reorientation follows disenchantment, as the retiree builds a realistic new routine.' },
      { id: 'c', text: 'Disenchantment', isCorrect: true, rationale: 'Disenchantment is the letdown that can follow the honeymoon, when retirement does not meet expectations.' },
      { id: 'd', text: 'Termination', isCorrect: false, rationale: 'Termination is the end of the retirement role, often through illness or a return to work.' },
    ],
    rationale: 'Atchley described retirement phases: preretirement, honeymoon, disenchantment, reorientation, stability (routine), and termination. Not every retiree passes through each phase. Counselors can normalize disenchantment and help the client find meaningful roles such as volunteering, part-time work or learning.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Late career and retirement: adjustment to retirement' }],
    reviewNote: 'Atchley\'s phases are standard NCE content; confirm Sharf (6th ed.) presents them or cite Berk (late adulthood: retirement).',
  },
  {
    id: 'nce-s-clf-162',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'easy',
    stem: 'A 63-year-old accountant plans to leave her full-time firm job next year. She does not want to stop working completely, so she is lining up part-time tax preparation work to ease the move into full retirement. What is this type of work called?',
    options: [
      { id: 'a', text: 'Bridge employment', isCorrect: true, rationale: 'Bridge employment is paid work after leaving a career job and before full retirement.' },
      { id: 'b', text: 'Career plateauing', isCorrect: false, rationale: 'A plateau is a point where advancement stalls within a career, not a step toward retirement.' },
      { id: 'c', text: 'Role disengagement', isCorrect: false, rationale: 'Disengagement theory describes withdrawal from roles; she is staying engaged in work.' },
      { id: 'd', text: 'Maintenance stage', isCorrect: false, rationale: 'Super\'s maintenance stage involves holding one\'s place in a career, not shifting to new part-time work.' },
    ],
    rationale: 'Bridge employment is part-time, temporary or self-employed work that links a career job and full retirement. It can provide income, structure and social contact, and it is linked to better adjustment for many older workers. Career counselors help older clients weigh bridge options alongside finances, health and values.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Late career: older workers and bridge employment' }],
    reviewNote: 'Confirm Sharf uses the term bridge employment; Berk (late adulthood, retirement) is an alternative locator.',
  },

  // ── child abuse and neglect ───────────────────────────────────────────────
  {
    id: 'nce-s-clf-163',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'child abuse and neglect',
    difficulty: 'medium',
    stem: 'A 9-year-old tells her school counselor, "My uncle does things to me at night that I don\'t like, but you can\'t tell anyone." She looks scared and stops talking. Which response BEST fits recommended practice for handling a sexual abuse disclosure?',
    options: [
      { id: 'a', text: 'Promise to keep her secret so she will feel safe telling more', isCorrect: false, rationale: 'The counselor is a mandated reporter and cannot promise secrecy; a broken promise harms trust.' },
      { id: 'b', text: 'Stay calm, thank her for telling, avoid leading questions, report', isCorrect: true, rationale: 'A calm, supportive response with minimal open questions protects the child and later investigation; reporting is required.' },
      { id: 'c', text: 'Ask if her uncle touched her private parts so the facts are clear', isCorrect: false, rationale: 'This is a leading question that can contaminate her account for any later forensic interview.' },
      { id: 'd', text: 'Gather a full, detailed account now so she will not need to retell', isCorrect: false, rationale: 'Detailed questioning is the role of trained forensic interviewers, not the school counselor.' },
    ],
    rationale: 'When a child discloses sexual abuse, counselors stay calm, believe and thank the child, use the child\'s own words, ask only minimal open-ended questions needed to establish reasonable suspicion, explain honestly that they must tell people who can help, and report promptly. Detailed or leading questioning can distress the child and compromise the investigation.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }, { source: 'State law', detail: 'Mandated reporting of suspected child abuse' }],
  },
  {
    id: 'nce-s-clf-164',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'child abuse and neglect',
    difficulty: 'hard',
    stem: 'A counselor has seen a 7-year-old for six months for anxiety. After a report of possible abuse, the CPS caseworker asks the counselor to conduct the investigative interview, since "she already trusts you." The counselor has no forensic interview training. What should the counselor do?',
    options: [
      { id: 'a', text: 'Agree, since an existing alliance will help her disclose more', isCorrect: false, rationale: 'Trust does not make a treating counselor a proper forensic interviewer; mixing roles harms both.' },
      { id: 'b', text: 'Agree if the caseworker watches and records the session live', isCorrect: false, rationale: 'Observation does not solve the dual role or the lack of forensic training.' },
      { id: 'c', text: 'Interview her alone first, then pass the notes on to the caseworker', isCorrect: false, rationale: 'Investigative questioning by the therapist risks contaminating evidence and the therapy relationship.' },
      { id: 'd', text: 'Decline the forensic role and support a trained interviewer\'s work', isCorrect: true, rationale: 'Treating counselors avoid forensic roles with their own clients; a trained interviewer, often at a child advocacy center, conducts it.' },
    ],
    rationale: 'Forensic interviews are fact-finding interviews conducted by trained interviewers using structured, nonleading protocols, often at a child advocacy center. A treating counselor\'s role is therapeutic, and the ACA Code bars counselors from evaluating their own current or former clients for forensic purposes. The counselor can support the child and cooperate within the law while keeping roles separate.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.13.c Client Evaluation Prohibited' }],
  },

  // ── military and veteran populations ──────────────────────────────────────
  {
    id: 'nce-s-clf-165',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'military and veteran populations',
    difficulty: 'medium',
    stem: 'A counselor in a small rural town sees a 34-year-old Army National Guard member just home from deployment. Compared with many active-duty service members, which stressor is MORE characteristic of Guard and Reserve members and their families?',
    options: [
      { id: 'a', text: 'Frequent moves between distant bases that uproot the children', isCorrect: false, rationale: 'Frequent permanent change of station moves are more typical of active-duty families.' },
      { id: 'b', text: 'Living in base housing within a closely knit military unit', isCorrect: false, rationale: 'Base housing and on-post community are features of active-duty life, not Guard life.' },
      { id: 'c', text: 'Distance from military supports and strain on civilian jobs', isCorrect: true, rationale: 'Guard and Reserve families often live far from installations and must leave and return to civilian jobs.' },
      { id: 'd', text: 'Fewer total deployments over the course of an enlistment', isCorrect: false, rationale: 'Fewer deployments would lessen stress; the distinct burden lies in the civilian-military shift and limited support.' },
    ],
    rationale: 'National Guard and Reserve members move rapidly between civilian and military life. Their families often live far from installations and military support services, may be surrounded by civilians who do not understand deployment, and face disruption to civilian employment and income. Counselors in community settings help connect them to resources and address these transition stressors.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling military populations: Guard and Reserve families' }],
    reviewNote: 'Content is standard; confirm Gladding addresses Guard/Reserve distinctions or cite a military counseling source.',
  },

  // ── couples and family concerns ───────────────────────────────────────────
  {
    id: 'nce-s-clf-166',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'couples and family concerns',
    difficulty: 'medium',
    stem: 'An 11-year-old lives with her father and stepmother on weekends. She enjoys baking with her stepmother but then feels guilty and turns cold toward her, saying, "Mom would be hurt if she knew I liked her." Which intervention BEST addresses this loyalty conflict?',
    options: [
      { id: 'a', text: 'Help her mother give clear permission to like her stepmother', isCorrect: true, rationale: 'Explicit permission from the biological parent eases the child\'s loyalty bind most directly.' },
      { id: 'b', text: 'Have her stepmother step in as her primary mother on weekends', isCorrect: false, rationale: 'Asking the stepmother to replace her mother intensifies the loyalty conflict.' },
      { id: 'c', text: 'Advise the father to limit contact between the two households', isCorrect: false, rationale: 'Cutting contact does not resolve her guilt and may harm her relationship with her mother.' },
      { id: 'd', text: 'Tell her the guilt is a sign the stepfamily is not yet working', isCorrect: false, rationale: 'Loyalty conflicts are common in stepfamilies and do not mean the family is failing.' },
    ],
    rationale: 'Children in stepfamilies often feel that caring for a stepparent betrays the absent biological parent. These loyalty conflicts ease when both biological parents explicitly permit the child to have a good relationship with the stepparent, and when the stepparent is presented as an additional adult rather than a replacement.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Remarried families: loyalty conflicts and stepfamily development' }],
  },

  // ── aging and older adults ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-167',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'aging and older adults',
    difficulty: 'medium',
    stem: 'A 64-year-old woman has taken custody of her two grandchildren because her daughter has a severe opioid use disorder. She loves them but says, "This was supposed to be my time." She is tired, short on money, and lies awake worrying about her daughter. Which concern is MOST characteristic of custodial grandparents?',
    options: [
      { id: 'a', text: 'A loss of interest in the grandchildren caused by aging', isCorrect: false, rationale: 'Nothing suggests lost interest; she loves the children and is stressed by the load.' },
      { id: 'b', text: 'An early sign of cognitive decline from added demands', isCorrect: false, rationale: 'Fatigue and worry do not indicate cognitive decline.' },
      { id: 'c', text: 'Rivalry with the grandchildren\'s other set of grandparents', isCorrect: false, rationale: 'Rivalry is not a characteristic theme for custodial grandparents.' },
      { id: 'd', text: 'Off-time role strain together with grief over her daughter', isCorrect: true, rationale: 'Raising grandchildren is an off-time role, often with financial strain and grief or anger about the adult child.' },
    ],
    rationale: 'Grandparents raising grandchildren in skipped-generation households take on an unexpected, off-time parenting role. They often face financial strain, health demands, legal and school hurdles, social isolation from peers, and grief, anger or worry about the adult child whose problems led to the arrangement. Counselors address both the practical load and the losses.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: grandparents rearing grandchildren (skipped-generation families)' }],
  },

  // ── LGBTQ+ clients and minority stress ────────────────────────────────────
  {
    id: 'nce-s-clf-168',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'hard',
    stem: 'A 20-year-old client says, "I\'m probably gay. I\'ve started going to an LGBTQ+ student group so I\'m not so alone, but I\'m not ready to say I like it about myself, and I haven\'t told my family." In Cass\'s model of homosexual identity formation, which stage BEST fits?',
    options: [
      { id: 'a', text: 'Identity comparison', isCorrect: false, rationale: 'In comparison the person first considers "I might be gay" and weighs the alienation; she has moved past this to seeking out community.' },
      { id: 'b', text: 'Identity tolerance', isCorrect: true, rationale: 'In tolerance the person accepts "I probably am gay" and seeks contact with gay communities, tolerating rather than fully accepting the identity.' },
      { id: 'c', text: 'Identity acceptance', isCorrect: false, rationale: 'Acceptance brings a more positive view of the identity and more contact; she still only tolerates it.' },
      { id: 'd', text: 'Identity pride', isCorrect: false, rationale: 'Pride involves strong immersion and often anger at heterosexist society, which she does not show.' },
    ],
    rationale: 'Cass described six stages: identity confusion, comparison, tolerance, acceptance, pride, and synthesis. In tolerance, the person acknowledges a probable gay identity and seeks out others to reduce isolation, while still merely tolerating the identity. Stage models are useful lenses but not every client follows them in order.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ+ individuals: sexual identity development (Cass model)' }],
  },
  {
    id: 'nce-s-clf-169',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'medium',
    stem: 'Religious parents of a 15-year-old who has come out as lesbian tell the counselor they cannot approve of her identity, but they love her and want to keep her safe. Which statement BEST reflects family acceptance research on LGBTQ+ youth?',
    options: [
      { id: 'a', text: 'Only her parents\' full agreement with her identity lowers risk', isCorrect: false, rationale: 'Research shows benefit from reducing rejecting behaviors even before full acceptance.' },
      { id: 'b', text: 'Parental views matter little once teens find support from peers', isCorrect: false, rationale: 'Family acceptance and rejection have strong effects on youth health even with peer support.' },
      { id: 'c', text: 'Reducing rejecting behaviors lowers risk, even without agreement', isCorrect: true, rationale: 'Family rejecting behaviors predict higher suicide, depression and substance risk; reducing them helps even without full agreement.' },
      { id: 'd', text: 'Teens facing rejection mainly benefit from moving out of the home early', isCorrect: false, rationale: 'Leaving home early raises risks such as homelessness; strengthening family support is preferred.' },
    ],
    rationale: 'Research from the Family Acceptance Project found that LGBTQ+ youth from highly rejecting families had far higher rates of suicide attempts, depression and substance use, while family acceptance was protective. Because even modest reductions in rejecting behaviors help, counselors can work with ambivalent families on specific behaviors, such as stopping slurs and supporting the teen at school, while respecting their values.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ+ individuals: family acceptance and rejection' }],
    reviewNote: 'Finding is from Ryan et al. (Family Acceptance Project); confirm Sue & Sue (9th ed.) discusses it or add a source with the original study.',
  },

  // ── acculturation and immigration stress ──────────────────────────────────
  {
    id: 'nce-s-clf-170',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'medium',
    stem: 'A 30-year-old woman resettled as a refugee three months ago after fleeing armed conflict. Through an interpreter she reports nightmares and poor sleep, and says she is worried about losing her apartment and about relatives still in a refugee camp. What should the counselor focus on FIRST?',
    options: [
      { id: 'a', text: 'Address safety and resettlement needs while building trust', isCorrect: true, rationale: 'Trauma-informed, phase-oriented care starts with safety, stability and trust, including practical resettlement needs.' },
      { id: 'b', text: 'Begin detailed trauma narration to process her war memories', isCorrect: false, rationale: 'Detailed trauma processing comes after stabilization, not at the start amid housing insecurity.' },
      { id: 'c', text: 'Encourage her to adopt local customs to speed her adjustment', isCorrect: false, rationale: 'Pushing assimilation ignores her culture and can raise acculturative stress.' },
      { id: 'd', text: 'Teach her to set aside thoughts of her relatives in the camp', isCorrect: false, rationale: 'Her worry is realistic; suppressing it is neither feasible nor helpful.' },
    ],
    rationale: 'Refugees carry pre-migration trauma, migration losses and ongoing post-migration stressors such as housing, finances and separated family. Trauma-informed care begins with safety, stabilization and trust, uses qualified interpreters, and attends to practical needs before any trauma-focused work. Current stressors often drive distress as much as past events.',
    references: [{ source: 'SAMHSA TIP 57', detail: 'Trauma-informed principles: safety and trustworthiness; refugee and immigrant populations' }],
  },
  {
    id: 'nce-s-clf-171',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'easy',
    stem: 'A Korean immigrant family has lived in the United States for six years. The 15-year-old son speaks mostly English, wants to date, and argues that his parents\' rules are "old-fashioned." His parents, who still speak mainly Korean, feel they are losing him. Which concept BEST describes this family conflict?',
    options: [
      { id: 'a', text: 'Typical adolescent rebellion unrelated to culture', isCorrect: false, rationale: 'Developmental strivings play a role, but the cultural gap is central to this conflict.' },
      { id: 'b', text: 'Marginalization of the son from both of his cultures', isCorrect: false, rationale: 'He is engaging with the host culture, not rejected by both cultures.' },
      { id: 'c', text: 'Cultural encapsulation of the parents\' worldview', isCorrect: false, rationale: 'Cultural encapsulation (Wrenn) describes counselors who view others only through their own culture.' },
      { id: 'd', text: 'An intergenerational acculturation gap in the family', isCorrect: true, rationale: 'Children often acculturate faster than parents, creating gaps in values and language that fuel conflict.' },
    ],
    rationale: 'An intergenerational acculturation gap arises when children adopt the host culture\'s language and values faster than their parents. The gap can strain communication, shift family roles, and heighten parent-child conflict. Counselors help family members understand each other\'s positions and find bicultural ground.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Immigrant and refugee families: acculturation conflicts between generations' }],
  },

  // ── self-injury ───────────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-172',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'hard',
    stem: 'Within two weeks, four ninth graders at a high school are found to be cutting after one student posted photos of her wounds online. The principal asks the school counselor how the school should respond. Which plan is MOST consistent with best practice for self-injury in schools?',
    options: [
      { id: 'a', text: 'Hold an assembly showing the warning signs and methods of cutting', isCorrect: false, rationale: 'Describing methods to large groups can spread self-injury through social contagion.' },
      { id: 'b', text: 'Meet each student alone, assess risk, inform parents, limit spread', isCorrect: true, rationale: 'Individual assessment, parent notification and steps to curb contagion are core to a school protocol.' },
      { id: 'c', text: 'Start a support group where the four students share their cutting', isCorrect: false, rationale: 'Groups focused on sharing self-injury can reinforce it and spread it among members.' },
      { id: 'd', text: 'Keep the cutting from parents so students keep trusting staff', isCorrect: false, rationale: 'Parents of minors at risk should be informed; secrecy leaves students without home support.' },
    ],
    rationale: 'School responses to self-injury emphasize individual risk assessment (including suicide risk), parent notification, referral for treatment, and limiting social contagion. Counselors avoid large-group presentations about methods and process groups centered on self-injury, and they may address related online sharing. Students are offered support in a calm, nonjudgmental way.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: responding to self-injury and contagion' }, { source: 'ACA Code of Ethics', detail: 'B.5.b Responsibility to Parents and Legal Guardians' }],
    reviewNote: 'Best-practice content is standard (e.g., Walsh; ASCA); confirm the Gladding locator or cite a school self-injury protocol source.',
  },

  // ── psychopharmacology basics for counselors ──────────────────────────────
  {
    id: 'nce-s-clf-173',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'hard',
    stem: 'A counselor coordinating care for a client with bipolar I disorder learns that the psychiatrist is switching her from lithium to valproate. To support her in keeping medical appointments, the counselor wants to understand the lab monitoring involved. Which monitoring is MOST closely tied to valproate rather than lithium?',
    options: [
      { id: 'a', text: 'Kidney function and thyroid hormone levels', isCorrect: false, rationale: 'Kidney and thyroid monitoring is a hallmark of long-term lithium treatment.' },
      { id: 'b', text: 'Hydration status and daily salt intake', isCorrect: false, rationale: 'Dehydration and salt changes affect lithium levels, not valproate.' },
      { id: 'c', text: 'Liver function tests and platelet counts', isCorrect: true, rationale: 'Valproate carries risks to the liver and blood platelets, so these are monitored.' },
      { id: 'd', text: 'Regular white blood cell counts for safety', isCorrect: false, rationale: 'Routine white cell monitoring is linked to clozapine, not valproate.' },
    ],
    rationale: 'Lithium has a narrow therapeutic range; monitoring includes blood levels, kidney and thyroid function, and attention to hydration and salt. Valproate monitoring focuses on liver function and blood counts, including platelets, and it carries serious risks in pregnancy. Counselors do not interpret labs but can encourage adherence to monitoring and communicate concerns to the prescriber.',
    references: [{ source: 'NICE guidelines', detail: 'CG185 Bipolar disorder: monitoring physical health with lithium and valproate' }],
  },
  {
    id: 'nce-s-clf-174',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'medium',
    stem: 'A client who takes sertraline started St. John\'s wort on her own last week. In session she is restless and sweating, with shivering, muscle twitching, a racing heart and diarrhea. She says the symptoms began yesterday and are getting worse. What should the counselor recognize and do?',
    options: [
      { id: 'a', text: 'Possible serotonin syndrome needing urgent medical care', isCorrect: true, rationale: 'Combining serotonergic agents can cause serotonin syndrome, which can become life-threatening and needs urgent care.' },
      { id: 'b', text: 'A panic attack to treat with breathing and grounding', isCorrect: false, rationale: 'Muscle twitching, diarrhea and sweating after adding a serotonergic herb point to a medical reaction, not panic.' },
      { id: 'c', text: 'SSRI discontinuation symptoms that will pass on their own', isCorrect: false, rationale: 'She has not stopped the SSRI; she added another serotonergic agent.' },
      { id: 'd', text: 'Neuroleptic malignant syndrome from her antidepressant', isCorrect: false, rationale: 'NMS is linked mainly to antipsychotics and features severe rigidity, not twitching after adding an herb.' },
    ],
    rationale: 'Serotonin syndrome results from excess serotonergic activity, often when an SSRI is combined with another serotonergic agent such as St. John\'s wort, tramadol, triptans or an MAOI. Signs include agitation, sweating, tremor or twitching, rapid heart rate, diarrhea and fever. Counselors do not manage medications but should recognize warning signs and direct the client to urgent medical care.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Psychopharmacology for counselors: antidepressant adverse effects' }],
    reviewNote: 'Clinical facts are standard; confirm Gladding covers serotonin syndrome or cite a psychopharmacology reference.',
  },
  {
    id: 'nce-s-clf-175',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'easy',
    stem: 'A client who has taken a prescribed benzodiazepine daily for six years tells her counselor she is "done with pills" and plans to stop it all at once this weekend. Why should the counselor urge her to talk with her prescriber before stopping?',
    options: [
      { id: 'a', text: 'Stopping will cause relapse of her anxiety in all cases', isCorrect: false, rationale: 'Anxiety may return, but that is not certain and is not the main safety concern.' },
      { id: 'b', text: 'Stopping suddenly will lower her tolerance to alcohol use', isCorrect: false, rationale: 'This is not the key risk of abrupt benzodiazepine discontinuation.' },
      { id: 'c', text: 'Stopping is unsafe only if she took more than prescribed', isCorrect: false, rationale: 'Dependence develops with long-term use at prescribed doses too.' },
      { id: 'd', text: 'Abrupt withdrawal can bring severe effects like seizures', isCorrect: true, rationale: 'Sedative withdrawal after long-term use can include seizures, so a supervised taper is needed.' },
    ],
    rationale: 'Long-term benzodiazepine use produces physiological dependence even at prescribed doses. DSM-5-TR sedative, hypnotic, or anxiolytic withdrawal can include autonomic hyperactivity, tremor, insomnia, anxiety, hallucinations and grand mal seizures. Counselors support the client\'s goal and urge a medically supervised taper.',
    references: [{ source: 'DSM-5-TR', detail: 'Sedative, hypnotic, or anxiolytic withdrawal: criteria' }],
  },

  // ── military: children of deployed parents ────────────────────────────────
  {
    id: 'nce-s-clf-176',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'military and veteran populations',
    difficulty: 'easy',
    stem: 'Two months into her husband\'s deployment, a mother says their 4-year-old has started wetting the bed again, clings to her at daycare drop-off, and asks every night when Daddy is coming home. What guidance should the counselor give?',
    options: [
      { id: 'a', text: 'These signs point to a likely trauma disorder needing intensive care', isCorrect: false, rationale: 'Regression and clinging are common reactions to a parent\'s absence and do not by themselves suggest a trauma disorder.' },
      { id: 'b', text: 'Brief regression is common; keep routines and give honest reassurance', isCorrect: true, rationale: 'Young children often regress during deployment; stable routines, simple honest answers and connection help.' },
      { id: 'c', text: 'Avoid mentioning her father so she is not reminded of his absence', isCorrect: false, rationale: 'Avoiding talk of the parent increases confusion; keeping him present through photos and messages helps.' },
      { id: 'd', text: 'Tell her Daddy will be home soon to calm her fears about his return', isCorrect: false, rationale: 'False reassurance can backfire; age-appropriate, honest information is better.' },
    ],
    rationale: 'Children\'s reactions to deployment vary by age. Preschoolers often show regression, clinginess and sleep problems; school-age children may show irritability or school problems; adolescents may take on adult roles or act out. Counselors help the at-home parent keep routines, give honest age-appropriate explanations, maintain connection with the deployed parent, and watch for persistent difficulties.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Early childhood: stress, separation and regression in young children' }],
    reviewNote: 'Content is standard deployment-cycle guidance; Berk does not address deployment directly, so a military family source may be preferable.',
  },

  // ── school and academic concerns ──────────────────────────────────────────
  {
    id: 'nce-s-clf-177',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'school and academic concerns',
    difficulty: 'medium',
    stem: 'A 14-year-old has missed 15 school days this term. Each morning he leaves home on time, then spends the day at a friend\'s house playing video games. He forged notes so his parents would not find out, and he shows no worry about school itself. Which pattern does this BEST fit?',
    options: [
      { id: 'a', text: 'School refusal due to anxiety about being away from home', isCorrect: false, rationale: 'School refusal involves emotional distress, often staying home with parents\' knowledge.' },
      { id: 'b', text: 'School refusal driven by fear of a specific school setting', isCorrect: false, rationale: 'He shows no fear of school; he is avoiding it to do something more appealing.' },
      { id: 'c', text: 'Truancy, hidden from parents and without school anxiety', isCorrect: true, rationale: 'Truancy is typically concealed from parents, lacks marked anxiety, and may involve conduct problems.' },
      { id: 'd', text: 'Avoidance linked to depression and loss of interest at school', isCorrect: false, rationale: 'Nothing points to depressed mood; he is actively seeking a rewarding activity elsewhere.' },
    ],
    rationale: 'School refusal involves emotional distress about attending, and the child usually stays home with the parents\' knowledge. Truancy involves absence concealed from parents, little anxiety about school, and often conduct or peer-related problems. The distinction guides intervention: anxiety-focused exposure for refusal, versus behavioral contracts, parental monitoring and school engagement for truancy.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: attendance problems, school refusal and truancy' }],
    reviewNote: 'Distinction follows Berg/Kearney; confirm the Gladding locator or cite a school-attendance source.',
  },
];
