// tools/nce/seed/clinical-focus-4.js — Areas of Clinical Focus, batch 2
// (blueprint clinical_focus topics 15-28). Hand-authored; original items.
module.exports = [
  // ── Career and vocational concerns ────────────────────────────────────────
  {
    id: 'nce-s-clf-090',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'hard',
    stem: 'A 46-year-old warehouse supervisor lost his job four months ago. A generous severance package covers his bills for the next year, yet he reports feeling aimless, sleeping late, missing his coworkers, and no longer knowing "who I am." Which framework BEST explains why his distress persists despite financial security?',
    options: [
      { id: 'a', text: 'Holland\'s congruence between personality type and setting', isCorrect: false, rationale: 'Congruence concerns fit between a person\'s type and a work environment; it does not explain distress from losing work altogether.' },
      { id: 'b', text: 'Krumboltz\'s planned happenstance and openness to chance', isCorrect: false, rationale: 'Planned happenstance is a stance for using unplanned events, not an account of why job loss is distressing.' },
      { id: 'c', text: 'Jahoda\'s latent deprivation model of unemployment', isCorrect: true, rationale: 'Jahoda argued that work supplies latent benefits such as time structure, social contact, purpose, status and activity; losing them causes distress even when income continues.' },
      { id: 'd', text: 'Gottfredson\'s compromise among sex type, prestige and field', isCorrect: false, rationale: 'Compromise describes how people give up preferred options when choosing; it does not address the psychological functions of employment.' },
    ],
    rationale: 'Jahoda\'s latent deprivation model holds that employment has a manifest function (income) and latent functions: time structure, regular social contact, shared purpose, status and identity, and regular activity. Unemployed people lose these latent benefits even when money is not a problem, which helps explain aimlessness and identity loss. Counselors can help clients rebuild structure, contact and purpose while job searching.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Career counseling for unemployment and job loss; Jahoda\'s latent deprivation model' }],
    reviewNote: 'Verify that the cited Sharf edition discusses Jahoda\'s latent deprivation model; the model itself (Jahoda, 1981-1982) is well established.',
  },
  {
    id: 'nce-s-clf-091',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 34-year-old client has completed several interest inventories, researched dozens of occupations, and shadowed workers in two fields, yet still cannot choose. She describes the same agonizing paralysis when picking an apartment, a car, or even a restaurant, and says any choice feels like it could ruin her life. Which approach BEST fits her concern?',
    options: [
      { id: 'a', text: 'Address the anxiety behind her pervasive indecisiveness', isCorrect: true, rationale: 'Indecision that spans life domains and persists despite ample information reflects chronic indecisiveness, which calls for work on anxiety and personal concerns, not more data.' },
      { id: 'b', text: 'Give more occupational information and a new inventory', isCorrect: false, rationale: 'More information helps a developmentally undecided client who lacks data; this client already has extensive information and remains stuck.' },
      { id: 'c', text: 'Treat her concern as normal, developmental undecidedness', isCorrect: false, rationale: 'Developmental undecidedness is situational and resolves with exploration; her paralysis is pervasive and long-standing.' },
      { id: 'd', text: 'Have her pick the highest-rated field and commit to it now', isCorrect: false, rationale: 'Pushing a fast commitment ignores the anxiety driving her indecisiveness and is likely to increase her distress.' },
    ],
    rationale: 'Career literature distinguishes career indecision (undecidedness), a common developmental state that usually responds to information and exploration, from indecisiveness, a chronic trait-like difficulty making decisions across many areas of life, often tied to anxiety, perfectionism or fear of commitment. Indecisive clients benefit from attention to these personal factors alongside career work.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Career indecision versus chronic indecisiveness in career counseling' }],
  },
  {
    id: 'nce-s-clf-092',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'An emergency room nurse works predictable shifts and is home every evening. She says the fatigue, tension and irritability she carries home from chaotic shifts leave her snapping at her children and too drained to enjoy family time. Which form of work-family conflict does this BEST illustrate?',
    options: [
      { id: 'a', text: 'Time-based conflict over hours that work takes from home', isCorrect: false, rationale: 'Time-based conflict occurs when hours spent in one role make it hard to meet another role\'s demands; her schedule leaves her home every evening.' },
      { id: 'b', text: 'Behavior-based conflict from work habits that misfit home', isCorrect: false, rationale: 'Behavior-based conflict involves role behaviors, such as a brisk clinical style, that are inappropriate at home; her problem is spillover of strain.' },
      { id: 'c', text: 'Family-to-work conflict in which home duties disrupt her job', isCorrect: false, rationale: 'This reverses the direction; here work is interfering with family life, not the other way around.' },
      { id: 'd', text: 'Strain-based conflict as work stress spills into home life', isCorrect: true, rationale: 'Strain-based conflict occurs when stress, fatigue or irritability from one role impairs functioning in another, as her work strain does at home.' },
    ],
    rationale: 'Greenhaus and Beutell described three forms of work-family conflict: time-based, strain-based and behavior-based, each of which can run work-to-family or family-to-work. Identifying the form guides intervention; strain-based conflict points toward recovery routines, stress management and boundary rituals between roles rather than schedule changes.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Work-family conflict and life roles: time-based, strain-based and behavior-based conflict' }],
    reviewNote: 'Confirm the cited Sharf edition covers the Greenhaus and Beutell (1985) three-form typology of work-family conflict.',
  },
  {
    id: 'nce-s-clf-093',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 27-year-old client with well-controlled epilepsy has a job interview next week. She asks her counselor whether she is required to tell the interviewer about her seizure disorder. Under the Americans with Disabilities Act, which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'She must disclose it at the interview so the employer can judge risk', isCorrect: false, rationale: 'The ADA does not require applicants to disclose a disability at an interview; employers may ask only about the ability to do job functions.' },
      { id: 'b', text: 'Disclosure is her choice; it is needed if she seeks accommodation', isCorrect: true, rationale: 'Disclosure under the ADA is generally voluntary; an employer needs to know about the disability only when an accommodation is requested.' },
      { id: 'c', text: 'Disclosure is only required if the job involves operating machinery', isCorrect: false, rationale: 'Job tasks do not create a duty to disclose at the interview; safety concerns are handled through job-related standards after an offer.' },
      { id: 'd', text: 'The employer may ask about any medical condition before an offer', isCorrect: false, rationale: 'Before a conditional job offer, the ADA bars disability-related questions and medical exams.' },
    ],
    rationale: 'The ADA prohibits disability-related inquiries and medical examinations before a conditional job offer and does not require applicants to disclose. Disclosure becomes necessary mainly when a person requests a reasonable accommodation. Career counselors help clients with disabilities weigh whether, when and how to disclose, and how to describe needed accommodations in terms of job performance.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Career development of people with disabilities; ADA disclosure and reasonable accommodation' }],
    reviewNote: 'Confirm the ADA pre-offer inquiry rules as stated and that the cited source covers disability disclosure; Sharf may not discuss ADA specifics.',
  },
  {
    id: 'nce-s-clf-094',
    domain: 'clinical_focus',
    cacrep: 'career',
    topic: 'career and vocational concerns',
    difficulty: 'medium',
    stem: 'A 19-year-old first-generation college student from a Filipino American family says her parents expect her to become a nurse, though she is drawn to graphic design. She values her family\'s sacrifices and wants their blessing. Her counselor is trained in a decision model that stresses individual choice. What is the MOST culturally responsive approach?',
    options: [
      { id: 'a', text: 'Encourage her to choose design and assert independence from family', isCorrect: false, rationale: 'This imposes an individualistic value and ignores that family harmony and approval matter to her.' },
      { id: 'b', text: 'Advise her to follow her parents\' wishes to keep peace in the family', isCorrect: false, rationale: 'This dismisses her own interests and is just as directive as pushing independence.' },
      { id: 'c', text: 'Explore her values and include family input in the decision process', isCorrect: true, rationale: 'Honoring collectivist values while exploring her interests, and inviting family into the process when she wishes, respects her worldview.' },
      { id: 'd', text: 'Use the standard model as written, since good models fit all clients', isCorrect: false, rationale: 'Career models built on Western individualism may not fit clients from collectivist backgrounds and need cultural adaptation.' },
    ],
    rationale: 'Many career theories assume individualistic decision making. With clients from collectivist backgrounds, career choice may be a family decision tied to obligation and gratitude. Culturally responsive counselors explore the client\'s own values, acknowledge family expectations, and may involve family in the process rather than framing autonomy as the goal.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Collectivism, family roles and culturally responsive career counseling' }],
  },

  // ── Couples and family concerns ───────────────────────────────────────────
  {
    id: 'nce-s-clf-095',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'couples and family concerns',
    difficulty: 'medium',
    stem: 'Parents of a 15-year-old argue constantly with their son about curfew, friends and privacy, while also arranging care for the father\'s ailing mother. In Carter and McGoldrick\'s family life cycle, which key emotional task does the family face in this stage?',
    options: [
      { id: 'a', text: 'Increasing the flexibility of family boundaries for independence', isCorrect: true, rationale: 'The families-with-adolescents stage calls for more flexible boundaries to allow teen independence and to absorb grandparents\' frailties.' },
      { id: 'b', text: 'Accepting new members into the system as the couple has children', isCorrect: false, rationale: 'Accepting new members is the task of families with young children.' },
      { id: 'c', text: 'Accepting many exits from and entries into the family system', isCorrect: false, rationale: 'Accepting exits and entries is the task of launching children and moving on.' },
      { id: 'd', text: 'Accepting the shifting of roles from one generation to the next', isCorrect: false, rationale: 'Accepting shifting generational roles is the task of families in later life.' },
    ],
    rationale: 'Carter and McGoldrick describe stages of the family life cycle, each with a key emotional process. In families with adolescents, boundaries must become more flexible so teens can move in and out of the system, while parents often begin caring for aging grandparents. Stress tends to rise when a family remains rigid at a transition point.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Family life cycle stages and key emotional tasks (Carter & McGoldrick)' }],
  },
  {
    id: 'nce-s-clf-096',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'couples and family concerns',
    difficulty: 'medium',
    stem: 'A divorcing couple with children aged 6 and 10 asks a counselor what will MOST affect how well their children adjust over the coming years. Based on research on divorce and child outcomes, which factor should the counselor highlight?',
    options: [
      { id: 'a', text: 'Whether the children are told about the divorce at the same time', isCorrect: false, rationale: 'How the news is shared matters, but a single conversation is not a major long-term predictor of adjustment.' },
      { id: 'b', text: 'Whether a sole or a joint legal custody arrangement is chosen', isCorrect: false, rationale: 'Custody type alone predicts outcomes less than the quality of parenting and the level of conflict children face.' },
      { id: 'c', text: 'Whether either parent remarries within the first year after', isCorrect: false, rationale: 'Remarriage brings its own adjustments, but it is not the strongest predictor of children\'s post-divorce adjustment.' },
      { id: 'd', text: 'How much ongoing conflict between parents the children see', isCorrect: true, rationale: 'Exposure to persistent, hostile interparental conflict is among the strongest predictors of poorer child adjustment after divorce.' },
    ],
    rationale: 'Research by Hetherington, Amato and others shows that most children of divorce adjust well within a few years. Poorer outcomes are most strongly linked to ongoing interparental conflict, especially when children are caught in the middle, along with declines in parenting quality and economic hardship. Counselors help parents shield children from conflict and keep warm, consistent parenting.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Divorce: factors in children\'s adjustment, interparental conflict and parenting quality' }],
  },
  {
    id: 'nce-s-clf-097',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'couples and family concerns',
    difficulty: 'easy',
    stem: 'During a heated discussion in couples counseling, a husband pauses, smiles, and says, "Okay, I\'m getting defensive. Can I try saying that again?" His wife\'s tone softens. In Gottman\'s research, what is the husband\'s statement called?',
    options: [
      { id: 'a', text: 'Stonewalling', isCorrect: false, rationale: 'Stonewalling is withdrawing from the interaction, one of the Four Horsemen; he is re-engaging, not shutting down.' },
      { id: 'b', text: 'A repair attempt', isCorrect: true, rationale: 'A repair attempt is any statement or action that de-escalates conflict and keeps negativity from spiraling.' },
      { id: 'c', text: 'A harsh startup', isCorrect: false, rationale: 'A harsh startup is opening a discussion with criticism or contempt; his comment de-escalates.' },
      { id: 'd', text: 'Flooding', isCorrect: false, rationale: 'Flooding is physiological overwhelm during conflict; his calm self-correction shows the opposite.' },
    ],
    rationale: 'Gottman found that stable couples argue too, but they make and accept repair attempts, such as humor, apologies or requests to start over, that stop negativity from escalating. Whether repairs succeed depends largely on the strength of the couple\'s friendship. Counselors teach partners to offer and recognize repair attempts.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Couples counseling: Gottman\'s research on repair attempts and the Four Horsemen' }],
    reviewNote: 'Gottman\'s own texts are not on the approved source list; confirm the cited Gladding edition covers repair attempts.',
  },

  // ── Spiritual and religious concerns ──────────────────────────────────────
  {
    id: 'nce-s-clf-098',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'medium',
    stem: 'A 20-year-old college student raised in a close-knit congregation tells her counselor she has begun questioning teachings she once accepted without thought. She is reading widely, testing beliefs against her own reasoning, and wants a faith she has chosen for herself. Which of Fowler\'s stages of faith does this BEST describe?',
    options: [
      { id: 'a', text: 'Synthetic-conventional', isCorrect: false, rationale: 'Synthetic-conventional faith conforms to the beliefs of one\'s group without critical examination, which she is now moving beyond.' },
      { id: 'b', text: 'Mythic-literal', isCorrect: false, rationale: 'Mythic-literal faith, typical of school-age children, takes stories and symbols literally.' },
      { id: 'c', text: 'Individuative-reflective', isCorrect: true, rationale: 'This stage involves critically examining inherited beliefs and taking personal responsibility for one\'s own commitments.' },
      { id: 'd', text: 'Conjunctive', isCorrect: false, rationale: 'Conjunctive faith, usually in midlife or later, embraces paradox and other traditions after the reflective stage.' },
    ],
    rationale: 'Fowler proposed stages of faith development: primal (undifferentiated), intuitive-projective, mythic-literal, synthetic-conventional, individuative-reflective, conjunctive and universalizing. The shift from synthetic-conventional to individuative-reflective often occurs in late adolescence or young adulthood, when people move from group-held belief to a self-examined faith. Counselors can normalize this questioning rather than treat it as a crisis.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Spirituality in counseling: Fowler\'s stages of faith development' }],
  },
  {
    id: 'nce-s-clf-099',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'spiritual and religious concerns',
    difficulty: 'hard',
    stem: 'After a long illness in his family, a 63-year-old deacon says he has lost his sense that God listens and feels unmoored from his faith. He is sad at times but sleeps, eats and works normally, and his distress is in proportion to his experience. He meets criteria for no mental disorder. How should the counselor document the focus of treatment?',
    options: [
      { id: 'a', text: 'Adjustment disorder with depressed mood after the stressor', isCorrect: false, rationale: 'Adjustment disorder requires distress out of proportion to the stressor or significant impairment; neither is present.' },
      { id: 'b', text: 'Persistent depressive disorder, given his low periods', isCorrect: false, rationale: 'He has occasional sadness with normal functioning, not depressed mood most days for two years.' },
      { id: 'c', text: 'No code, since spiritual concerns fall outside counseling', isCorrect: false, rationale: 'Spiritual concerns can be a legitimate focus of counseling and have a code for documentation.' },
      { id: 'd', text: 'Religious or spiritual problem as a focus of attention', isCorrect: true, rationale: 'DSM-5-TR lists religious or spiritual problem (Z65.8) for distress such as loss or questioning of faith that is a focus of care.' },
    ],
    rationale: 'DSM-5-TR includes Religious or Spiritual Problem (Z65.8) among Other Conditions That May Be a Focus of Clinical Attention. It covers distressing experiences such as loss or questioning of faith, conversion, or conflicts with a religious institution. It lets counselors document a legitimate focus of care without pathologizing a spiritual struggle that does not meet criteria for a mental disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Other Conditions That May Be a Focus of Clinical Attention: Religious or Spiritual Problem (Z65.8)' }],
  },

  // ── Child abuse and neglect ───────────────────────────────────────────────
  {
    id: 'nce-s-clf-100',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'child abuse and neglect',
    difficulty: 'medium',
    stem: 'A mother tells her counselor that her 11-year-old\'s new volunteer tutor is "amazing." He buys her daughter small gifts, offers rides so the mother can rest, texts the girl privately at night, and recently told her some of their talks are "just between us." Which feature MOST strongly suggests possible grooming?',
    options: [
      { id: 'a', text: 'Private contact paired with a request to keep secrets', isCorrect: true, rationale: 'Grooming typically moves toward private access and secrecy, which isolate the child and lower the chance of disclosure.' },
      { id: 'b', text: 'His popularity with the parents in the neighborhood', isCorrect: false, rationale: 'Groomers may win over parents, but being well liked is common among safe adults and is not a specific warning sign.' },
      { id: 'c', text: 'His strong interest in the girl\'s grades and reading', isCorrect: false, rationale: 'Academic interest is expected of a tutor and is not by itself a warning sign.' },
      { id: 'd', text: 'His volunteering without pay for a nonprofit program', isCorrect: false, rationale: 'Unpaid volunteering is ordinary and does not distinguish grooming from safe mentoring.' },
    ],
    rationale: 'Grooming is a gradual process in which an offender builds trust with a child and often the family, gives special attention or gifts, tests boundaries, increases private access and introduces secrecy. Secret-keeping and isolated contact are the most telling signs. Counselors educate parents about these patterns and follow mandated reporting law when abuse is reasonably suspected.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Child sexual abuse: grooming patterns and warning signs' }],
    reviewNote: 'Confirm the cited source covers grooming; the concept itself is standard in child-protection literature.',
  },
  {
    id: 'nce-s-clf-101',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'child abuse and neglect',
    difficulty: 'easy',
    stem: 'A school counselor notices bruises on an active 6-year-old who plays rough sports at recess. Which bruise location should raise the GREATEST concern about possible physical abuse?',
    options: [
      { id: 'a', text: 'Scattered bruises over both shins and knees', isCorrect: false, rationale: 'Shins and knees are bony areas that are commonly bruised in normal childhood play.' },
      { id: 'b', text: 'A bruise on the forehead after a playground fall', isCorrect: false, rationale: 'The forehead is a common site of accidental injury in falls, especially with a matching account.' },
      { id: 'c', text: 'Bruises on the ears, cheeks and the upper back', isCorrect: true, rationale: 'Ears, cheeks and the back are protected, soft areas rarely bruised by accident, so injuries there suggest inflicted harm.' },
      { id: 'd', text: 'Bruises on the elbows of both arms from falling', isCorrect: false, rationale: 'Elbows are bony prominences that often take the impact of accidental falls.' },
    ],
    rationale: 'Accidental bruises in children usually appear over bony prominences such as the shins, knees, elbows and forehead. Bruises on soft or protected areas such as the ears, cheeks, neck, torso, back, buttocks or upper arms, or bruises in the shape of an object or hand, are more concerning for abuse. Reasonable suspicion triggers a mandated report.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Recognizing physical indicators of child abuse' }, { source: 'State law', detail: 'Child abuse mandated reporting statutes: reasonable-suspicion standard' }],
    reviewNote: 'Confirm the cited Gladding edition lists physical indicators of abuse; the injury-location pattern is standard pediatric guidance.',
  },

  // ── School and academic concerns (bullying) ───────────────────────────────
  {
    id: 'nce-s-clf-102',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'school and academic concerns',
    difficulty: 'easy',
    stem: 'A middle school counselor is preparing a parent workshop on cyberbullying. Which feature MOST clearly sets cyberbullying apart from traditional in-person bullying?',
    options: [
      { id: 'a', text: 'It involves a real or perceived imbalance of power', isCorrect: false, rationale: 'A power imbalance is part of the definition of all bullying, not a distinguishing feature of cyberbullying.' },
      { id: 'b', text: 'It can reach the child at home, at any hour, by many', isCorrect: true, rationale: 'Online bullying follows children home around the clock and can be seen and shared by large audiences, often anonymously.' },
      { id: 'c', text: 'It is intentional and is repeated over a period of time', isCorrect: false, rationale: 'Intent and repetition define bullying in general, both online and in person.' },
      { id: 'd', text: 'It harms the target\'s mood and school performance', isCorrect: false, rationale: 'Both forms of bullying are linked to depression, anxiety and academic problems.' },
    ],
    rationale: 'Bullying is unwanted aggressive behavior that is intentional, repeated or likely to be repeated, and involves a power imbalance. Cyberbullying shares these features but differs in that it can occur at any time and place, reach a wide audience, persist as a permanent record, and allow anonymity, so home is no longer a refuge.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: bullying and cyberbullying' }],
  },
  {
    id: 'nce-s-clf-103',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'school and academic concerns',
    difficulty: 'medium',
    stem: 'For several weeks, two larger eighth graders have mocked a smaller classmate, taken his lunch, and posted edited photos of him. The principal asks the school counselor to hold a peer mediation session so the three boys can "work it out together." What is the counselor\'s BEST response?',
    options: [
      { id: 'a', text: 'Agree, and set clear ground rules so each boy can share equally', isCorrect: false, rationale: 'Ground rules do not remove the power imbalance that makes mediation unsafe and unfair for a bullied student.' },
      { id: 'b', text: 'Agree, but ask the target to suggest ways he could avoid the boys', isCorrect: false, rationale: 'This places responsibility on the target and implies he shares blame for being bullied.' },
      { id: 'c', text: 'Decline, and leave the matter to discipline by the administration', isCorrect: false, rationale: 'Discipline may be needed, but the counselor still has a role in supporting the target and working with the students who bully.' },
      { id: 'd', text: 'Explain why mediation fits poorly and meet with the boys separately', isCorrect: true, rationale: 'Because bullying involves a power imbalance, separate meetings that support the target and hold the others accountable are preferred.' },
    ],
    rationale: 'Peer mediation assumes two parties with roughly equal power and shared responsibility for a conflict. Bullying is repeated, intentional aggression with a power imbalance, so mediation can retraumatize the target and send the message that both are to blame. Recommended practice is to support the target, address the behavior of those who bully separately, and involve families and school-wide prevention.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'School counseling: responding to bullying; limits of peer mediation' }],
    reviewNote: 'Confirm the cited source states that peer mediation is not recommended for bullying (a position also taken by federal StopBullying guidance).',
  },

  // ── Aging and older adults ────────────────────────────────────────────────
  {
    id: 'nce-s-clf-104',
    domain: 'clinical_focus',
    cacrep: 'human_growth',
    topic: 'aging and older adults',
    difficulty: 'easy',
    stem: 'A counselor reviewing a new referral for a 77-year-old with low mood, poor sleep and withdrawal thinks, "Anyone her age would feel down. Therapy probably won\'t change much at this point." What does the counselor\'s reaction BEST reflect?',
    options: [
      { id: 'a', text: 'Ageist bias that risks undertreating treatable depression', isCorrect: true, rationale: 'Treating depression as a normal part of aging, and assuming older adults cannot change, is ageism and leads to undertreatment.' },
      { id: 'b', text: 'Sound clinical judgment about late-life treatment outcomes', isCorrect: false, rationale: 'Older adults respond well to psychotherapy for depression; the assumption is not supported.' },
      { id: 'c', text: 'Appropriate humility about his limits with older clients', isCorrect: false, rationale: 'Humility would lead to consultation or training, not a belief that therapy is futile.' },
      { id: 'd', text: 'A correct view of depression as part of normal aging', isCorrect: false, rationale: 'Depression is common in later life but is not a normal part of aging.' },
    ],
    rationale: 'Ageism includes stereotypes that older adults are rigid, unable to change, or naturally depressed. In clinicians it can show up as therapeutic nihilism and missed diagnoses. Depression is not a normal part of aging, and evidence-based therapies such as CBT and problem-solving therapy work well for older adults.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: ageism, stereotypes of aging and late-life depression' }],
  },
  {
    id: 'nce-s-clf-105',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'aging and older adults',
    difficulty: 'medium',
    stem: 'An 84-year-old client mentions that her nephew, who now manages her finances, has her sign blank checks, and that her utilities were shut off last month. She seems anxious when he is mentioned and asks the counselor not to "make trouble." What should the counselor do?',
    options: [
      { id: 'a', text: 'Wait to act until she gives proof that funds were taken', isCorrect: false, rationale: 'Reporting standards rest on reasonable suspicion; counselors do not need proof before acting.' },
      { id: 'b', text: 'Call the nephew to ask him to explain how he uses the money', isCorrect: false, rationale: 'Confronting a suspected abuser can raise the risk to the client and breaches confidentiality.' },
      { id: 'c', text: 'Follow state law and report suspected exploitation to APS', isCorrect: true, rationale: 'Financial exploitation of an older adult is reportable abuse in many states; counselors follow their state\'s law and report to Adult Protective Services.' },
      { id: 'd', text: 'Respect her wish and only document what she has disclosed', isCorrect: false, rationale: 'Her wishes matter, but many states mandate reports of suspected elder abuse regardless of consent.' },
    ],
    rationale: 'Elder abuse includes physical, emotional, sexual and financial abuse and neglect; perpetrators are often family members or trusted caregivers. Signs of financial exploitation include unpaid bills despite adequate income and unusual control of money. Reporting laws vary, so counselors know their state\'s requirements, report suspected abuse to Adult Protective Services when required, and involve the client as much as possible.',
    references: [{ source: 'State law', detail: 'Elder and vulnerable adult abuse reporting statutes (requirements vary by state)' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },

  // ── LGBTQ+ clients and minority stress ────────────────────────────────────
  {
    id: 'nce-s-clf-106',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'hard',
    stem: 'A 29-year-old nonbinary client, assigned male at birth, has lived in line with their gender identity for years and feels settled and content with it. They seek counseling for work stress after a promotion. Which statement about a gender dysphoria diagnosis is MOST accurate?',
    options: [
      { id: 'a', text: 'It applies, since gender identity differs from assigned sex', isCorrect: false, rationale: 'Incongruence alone is not a disorder; DSM-5-TR also requires clinically significant distress or impairment.' },
      { id: 'b', text: 'It does not apply without related distress or impairment', isCorrect: true, rationale: 'Gender dysphoria requires clinically significant distress or impairment linked to the incongruence, which this client does not report.' },
      { id: 'c', text: 'It applies, since the incongruence has lasted over 6 months', isCorrect: false, rationale: 'Duration is only part of the criteria; distress or impairment is also required.' },
      { id: 'd', text: 'It does not apply, since nonbinary identities are excluded', isCorrect: false, rationale: 'DSM-5-TR criteria include a desire to be or be treated as an alternative gender, which covers nonbinary identities.' },
    ],
    rationale: 'In DSM-5-TR, gender dysphoria requires a marked incongruence between experienced or expressed gender and assigned gender lasting at least 6 months, plus clinically significant distress or impairment. The diagnosis centers on distress, not identity; being transgender or nonbinary is not itself a mental disorder. Counselors avoid diagnosing identity and focus on the client\'s presenting concerns.',
    references: [{ source: 'DSM-5-TR', detail: 'Gender Dysphoria in adolescents and adults: Criterion A duration and Criterion B distress or impairment' }],
  },
  {
    id: 'nce-s-clf-107',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'LGBTQ+ clients and minority stress',
    difficulty: 'easy',
    stem: 'In the third session, a 17-year-old client tells the counselor that he is transgender, goes by Eli, and uses he/him pronouns. He has not told his parents. Which counselor response is MOST affirming?',
    options: [
      { id: 'a', text: 'Ask him to wait a few months before changing his name', isCorrect: false, rationale: 'Delaying use of his name invalidates his identity and can weaken trust in the relationship.' },
      { id: 'b', text: 'Use his legal name in session until his parents know', isCorrect: false, rationale: 'Withholding his name in session is not affirming; safety concerns apply to records and outside contacts, not to how the counselor addresses him.' },
      { id: 'c', text: 'Explore whether this is a phase before using his name', isCorrect: false, rationale: 'Treating his identity as a phase to be tested is not affirming practice.' },
      { id: 'd', text: 'Use Eli and he/him, and ask where it is safe to do so', isCorrect: true, rationale: 'Affirming care uses the client\'s name and pronouns and plans together where they are used, such as in records or with family, to avoid outing him.' },
    ],
    rationale: 'Affirming counseling with transgender clients means using their chosen name and pronouns, treating gender identity as valid, and collaborating on safety, including when names appear in records or communications that parents or others may see. This respects the client\'s autonomy and protects against unwanted disclosure.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.1.a Primary Responsibility; C.5 Nondiscrimination' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ+ individuals: affirming practice' }],
  },

  // ── Acculturation and immigration stress ──────────────────────────────────
  {
    id: 'nce-s-clf-108',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'hard',
    stem: 'A 45-year-old Somali refugee who resettled two years ago works steadily and cares for his children. He grieves the loss of his land, his community\'s rituals, and his parents\' graves, feels guilty for leaving, and sometimes dreams that his ancestors are calling him. Which concept BEST describes his experience?',
    options: [
      { id: 'a', text: 'Cultural bereavement after losing homeland and community', isCorrect: true, rationale: 'Cultural bereavement is grief over the loss of one\'s homeland, social structures and cultural identity, a normal response to uprooting.' },
      { id: 'b', text: 'Culture shock from early contact with an unfamiliar setting', isCorrect: false, rationale: 'Culture shock is the early disorientation of contact with a new culture; his grief centers on what was lost.' },
      { id: 'c', text: 'Prolonged grief disorder after the death of a close person', isCorrect: false, rationale: 'Prolonged grief disorder requires the death of someone close and impairing grief; his loss is of culture and place, and he functions well.' },
      { id: 'd', text: 'Posttraumatic stress disorder with prominent survivor guilt', isCorrect: false, rationale: 'He reports no intrusion, avoidance or arousal symptoms; guilt and longing alone do not indicate PTSD.' },
    ],
    rationale: 'Eisenbruch described cultural bereavement as the grief of uprooted people for lost land, culture and social bonds, which can include guilt over leaving, longing, and dreams or visits from ancestors. He cautioned that such experiences may be misread as pathology. Counselors validate the loss and draw on cultural and community resources for mourning.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Refugees and immigrants: cultural bereavement and migration-related loss' }],
    reviewNote: 'Verify the Eisenbruch (1991) attribution and that the cited Sue & Sue edition discusses cultural bereavement.',
  },
  {
    id: 'nce-s-clf-109',
    domain: 'clinical_focus',
    cacrep: 'social_cultural',
    topic: 'acculturation and immigration stress',
    difficulty: 'easy',
    stem: 'A 12-year-old regularly interprets for her Spanish-speaking parents at medical visits and the bank. At the start of a family counseling session about the father\'s job loss, the parents ask her to interpret for them. What should the counselor do?',
    options: [
      { id: 'a', text: 'Let her interpret, since the family trusts her the most', isCorrect: false, rationale: 'Trust does not offset the role reversal and exposure to adult concerns that interpreting places on a child.' },
      { id: 'b', text: 'Hold the session in English and simplify the language', isCorrect: false, rationale: 'Simplifying English does not give the parents full access to the session.' },
      { id: 'c', text: 'Arrange a qualified interpreter so she can be a child', isCorrect: true, rationale: 'A qualified interpreter gives the parents full access and frees the child from a parental role in adult matters.' },
      { id: 'd', text: 'Ask her to sum up each part instead of translating it', isCorrect: false, rationale: 'Summaries still make the child the gatekeeper of adult content and risk distortion.' },
    ],
    rationale: 'Language brokering, in which children of immigrants interpret for parents, can build skills but also brings role reversal, stress and exposure to adult worries. In counseling, using a child as interpreter compromises accuracy and confidentiality and burdens the child. The ACA Code directs counselors to arrange qualified interpreters when clients have difficulty understanding the language used.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.c Developmental and Cultural Sensitivity (qualified interpreters)' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Language barriers, language brokering and the use of interpreters' }],
  },

  // ── Self-injury ───────────────────────────────────────────────────────────
  {
    id: 'nce-s-clf-110',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'hard',
    stem: 'A 19-year-old with a three-year history of superficial cutting to "calm down" tells her counselor that last weekend she swallowed a bottle of pills because she "wanted to never wake up." She slept for 12 hours and woke without treatment. Which statement is MOST accurate?',
    options: [
      { id: 'a', text: 'The overdose is part of her NSSI pattern, given her history', isCorrect: false, rationale: 'NSSI is defined by the absence of suicidal intent; she clearly stated she wanted to die.' },
      { id: 'b', text: 'The overdose was a suicide attempt, and NSSI raises her risk', isCorrect: true, rationale: 'Intent to die makes the overdose a suicide attempt, and a history of NSSI is a known risk factor for suicidal behavior.' },
      { id: 'c', text: 'Her low-lethality outcome shows the act was mainly a gesture', isCorrect: false, rationale: 'Outcome does not define intent; calling it a gesture minimizes a real suicide attempt.' },
      { id: 'd', text: 'Her NSSI lowers suicide risk because it works as coping for her', isCorrect: false, rationale: 'NSSI may regulate emotion short term, but it is associated with higher, not lower, suicide risk.' },
    ],
    rationale: 'NSSI and suicidal behavior are distinguished mainly by intent: NSSI is self-inflicted harm without intent to die, usually to relieve distress, whereas a suicide attempt involves at least some intent to die. The two often co-occur, and NSSI history is a robust predictor of later suicide attempts. Each act should be assessed for intent, and safety planning updated.',
    references: [{ source: 'DSM-5-TR', detail: 'Conditions for Further Study: Nonsuicidal Self-Injury Disorder and Suicidal Behavior Disorder' }, { source: 'C-SSRS', detail: 'Distinguishing suicidal from non-suicidal self-injurious behavior by intent' }],
  },
  {
    id: 'nce-s-clf-111',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'self-injury',
    difficulty: 'easy',
    stem: 'The DSM-5-TR proposed criteria for nonsuicidal self-injury disorder, a condition for further study, require intentional self-inflicted injury without suicidal intent on how many days in the past year?',
    options: [
      { id: 'a', text: 'At least 2 days', isCorrect: false, rationale: 'Two days is below the proposed threshold.' },
      { id: 'b', text: 'At least 12 days', isCorrect: false, rationale: 'Twelve days exceeds the proposed threshold.' },
      { id: 'c', text: 'At least 30 days', isCorrect: false, rationale: 'Thirty days is far above the proposed threshold.' },
      { id: 'd', text: 'At least 5 days', isCorrect: true, rationale: 'The proposed criteria require self-injury on 5 or more days in the past year.' },
    ],
    rationale: 'In DSM-5-TR Section III, the proposed nonsuicidal self-injury disorder requires intentional self-inflicted damage to the body on 5 or more days in the past year, with the expectation of only minor or moderate harm. DSM-5-TR also added codes for current or past nonsuicidal self-injury among conditions that may be a focus of clinical attention.',
    references: [{ source: 'DSM-5-TR', detail: 'Conditions for Further Study: Nonsuicidal Self-Injury Disorder, Criterion A' }],
  },

  // ── Sleep-wake concerns ───────────────────────────────────────────────────
  {
    id: 'nce-s-clf-112',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'sleep-wake concerns',
    difficulty: 'medium',
    stem: 'A 16-year-old cannot fall asleep before 2 a.m. on school nights and is exhausted in morning classes. On weekends he sleeps soundly from 2 a.m. to 11 a.m. and wakes refreshed. Months of sleep hygiene tips such as no caffeine and a cool, dark room have not helped. Which explanation BEST fits?',
    options: [
      { id: 'a', text: 'A circadian rhythm disorder of the delayed sleep phase type', isCorrect: true, rationale: 'Sleep that is normal in quality but shifted later, causing conflict with required schedules, fits delayed sleep phase type.' },
      { id: 'b', text: 'An insomnia disorder needing more strict sleep hygiene rules', isCorrect: false, rationale: 'He sleeps well when allowed his own schedule, so the problem is timing, and sleep hygiene alone has not helped.' },
      { id: 'c', text: 'A hypersomnolence disorder marked by excessive sleep need', isCorrect: false, rationale: 'His total sleep is normal and he wakes refreshed on weekends, which argues against hypersomnolence.' },
      { id: 'd', text: 'Narcolepsy with sleep attacks in his early morning classes', isCorrect: false, rationale: 'Narcolepsy involves recurrent irresistible sleep episodes regardless of schedule, not a simple shift in timing.' },
    ],
    rationale: 'Circadian rhythm sleep-wake disorders arise from a mismatch between the internal clock and required schedules. Delayed sleep phase type, common in adolescents, causes trouble falling asleep and waking at conventional times, while sleep at the preferred time is normal. Sleep hygiene alone rarely fixes a timing problem; approaches such as a consistent wake time and morning light, coordinated with a medical provider, target the clock itself.',
    references: [{ source: 'DSM-5-TR', detail: 'Circadian Rhythm Sleep-Wake Disorders: delayed sleep phase type' }],
  },

  // ── Psychopharmacology basics for counselors ──────────────────────────────
  {
    id: 'nce-s-clf-113',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'medium',
    stem: 'A 58-year-old client with schizophrenia has taken a first-generation antipsychotic for many years. The counselor notices repetitive lip smacking, tongue thrusting and facial grimacing that the client does not seem aware of. Which side effect do these signs MOST likely reflect?',
    options: [
      { id: 'a', text: 'Akathisia, an inner restlessness and urge to keep moving', isCorrect: false, rationale: 'Akathisia is subjective restlessness with pacing or fidgeting, not involuntary oral and facial movements.' },
      { id: 'b', text: 'Acute dystonia, with sudden and sustained muscle spasms', isCorrect: false, rationale: 'Acute dystonia appears early in treatment as painful sustained contractions, not repetitive movements after years.' },
      { id: 'c', text: 'Tardive dyskinesia from long-term antipsychotic use', isCorrect: true, rationale: 'Involuntary repetitive movements of the mouth, tongue and face after long-term antipsychotic use are classic tardive dyskinesia.' },
      { id: 'd', text: 'Neuroleptic malignant syndrome, a fever-and-rigidity crisis', isCorrect: false, rationale: 'NMS is an acute emergency with high fever, severe rigidity and confusion, not chronic oral-facial movements.' },
    ],
    rationale: 'Tardive dyskinesia is a late-emerging, sometimes irreversible movement disorder linked to long-term dopamine-blocking medications, especially first-generation antipsychotics. Counselors who notice possible signs should promptly inform the prescriber. Second-generation antipsychotics carry lower TD risk but greater metabolic risks, such as weight gain, diabetes and lipid changes, which also warrant medical monitoring.',
    references: [{ source: 'DSM-5-TR', detail: 'Medication-Induced Movement Disorders: Tardive Dyskinesia' }],
  },
  {
    id: 'nce-s-clf-114',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'easy',
    stem: 'A client who takes phenelzine, a monoamine oxidase inhibitor, mentions he is planning a celebration dinner of aged cheeses, cured salami and draft beer. The counselor encourages him to check with his prescriber first. Which reaction is the main concern?',
    options: [
      { id: 'a', text: 'Agranulocytosis', isCorrect: false, rationale: 'Agranulocytosis is a blood disorder linked mainly to clozapine, not to diet with MAOIs.' },
      { id: 'b', text: 'Hypertensive crisis', isCorrect: true, rationale: 'Tyramine in aged, cured and fermented foods can trigger a dangerous blood pressure spike in people taking MAOIs.' },
      { id: 'c', text: 'Lithium toxicity', isCorrect: false, rationale: 'Lithium toxicity relates to lithium levels, not to tyramine or MAOIs.' },
      { id: 'd', text: 'Tardive dyskinesia', isCorrect: false, rationale: 'Tardive dyskinesia is a movement disorder from long-term antipsychotics, not a dietary reaction.' },
    ],
    rationale: 'MAOIs block the breakdown of tyramine, found in aged cheeses, cured meats, some tap or draft beers and other fermented foods. Tyramine buildup can cause a hypertensive crisis with severe headache, stiff neck and rapid blood pressure rise. MAOIs also interact dangerously with many drugs, including other antidepressants, raising the risk of serotonin syndrome. Counselors reinforce prescriber guidance rather than giving medical advice.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Psychopharmacology for counselors: MAOIs and tyramine dietary restrictions' }],
    reviewNote: 'Confirm the cited source covers MAOI dietary restrictions; the pharmacology is standard.',
  },
  {
    id: 'nce-s-clf-115',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'psychopharmacology basics for counselors',
    difficulty: 'medium',
    stem: 'A 20-year-old college student without an ADHD diagnosis tells her counselor she takes a friend\'s prescription stimulant before exams to "focus better." She says it is safe "because doctors prescribe it to kids." What is the counselor\'s BEST response?',
    options: [
      { id: 'a', text: 'Tell her she must stop now or the counselor will alert the school', isCorrect: false, rationale: 'Threats damage the alliance, and confidential disclosure of past use does not by itself permit a report.' },
      { id: 'b', text: 'Agree it is low risk if used only during the exam period', isCorrect: false, rationale: 'Nonmedical stimulant use carries real risks even when occasional, so this response gives false reassurance.' },
      { id: 'c', text: 'Advise her to seek her own prescription so she can use it safely', isCorrect: false, rationale: 'Steering her to obtain a stimulant without a clinical need endorses misuse and is outside the counselor\'s role.' },
      { id: 'd', text: 'Explore her use nonjudgmentally and discuss its health risks', isCorrect: true, rationale: 'A nonjudgmental, MI-consistent discussion of risks such as dependence and cardiac strain respects autonomy and invites change.' },
    ],
    rationale: 'Nonmedical use of prescription stimulants is common among college students and carries risks such as elevated heart rate and blood pressure, anxiety, insomnia and stimulant use disorder. Counselors respond with motivational interviewing: exploring the student\'s reasons, offering accurate information with permission, and addressing underlying academic stress, rather than lecturing or threatening.',
    references: [{ source: 'Miller & Rollnick (MI)', detail: 'Exchanging information with permission (elicit-provide-elicit) and avoiding the righting reflex' }, { source: 'DSM-5-TR', detail: 'Stimulant Use Disorder' }],
  },

  // ── Military and veteran populations ──────────────────────────────────────
  {
    id: 'nce-s-clf-116',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'military and veteran populations',
    difficulty: 'medium',
    stem: 'Two months after her husband returned from a 9-month deployment, a military spouse says he keeps overriding household routines she ran on her own, the children test his rules, and they feel like "strangers sharing a house." In the emotional cycle of deployment, which phase is the family in?',
    options: [
      { id: 'a', text: 'Post-deployment, as the family renegotiates its roles', isCorrect: true, rationale: 'Post-deployment (reintegration) involves renegotiating roles, routines and intimacy after the service member returns.' },
      { id: 'b', text: 'Sustainment, as the family settles into new routines', isCorrect: false, rationale: 'Sustainment occurs during deployment, when the family at home builds new routines and support.' },
      { id: 'c', text: 'Redeployment, as the family anticipates his return', isCorrect: false, rationale: 'Redeployment is the period just before return, marked by excitement and apprehension.' },
      { id: 'd', text: 'Pre-deployment, as the family prepares for the leave', isCorrect: false, rationale: 'Pre-deployment covers preparation and anticipatory loss before departure.' },
    ],
    rationale: 'The emotional cycle of deployment is often described in phases: pre-deployment, deployment, sustainment, redeployment and post-deployment. Post-deployment reintegration can take months as families renegotiate roles the at-home partner took on, rebuild intimacy and adjust parenting. Counselors normalize this friction and help families communicate about changed roles.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling military families: emotional cycle of deployment and reintegration' }],
    reviewNote: 'Verify the five-phase deployment cycle (Pincus et al.) and that the cited Gladding edition covers it.',
  },
  {
    id: 'nce-s-clf-117',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'military and veteran populations',
    difficulty: 'hard',
    stem: 'A 38-year-old Air Force veteran discloses that she was sexually assaulted by a fellow service member during her enlistment. She never reported it, has no VA disability rating, and assumes VA will not help her without proof. Which statement BEST guides the counselor\'s response?',
    options: [
      { id: 'a', text: 'She must first file a report so the assault can be verified', isCorrect: false, rationale: 'VA does not require that the assault was reported or documented to provide MST-related care.' },
      { id: 'b', text: 'She can get care only after a service-connection rating', isCorrect: false, rationale: 'MST-related care does not require a service-connected disability rating.' },
      { id: 'c', text: 'VA offers free MST care without a report or a rating', isCorrect: true, rationale: 'VA provides free care for mental and physical conditions related to military sexual trauma without requiring a prior report or a rating.' },
      { id: 'd', text: 'MST must first be diagnosed as a disorder to get services', isCorrect: false, rationale: 'MST is an experience, not a diagnosis; care addresses conditions related to it.' },
    ],
    rationale: 'Military sexual trauma (MST) is the VA term for sexual assault or threatening sexual harassment during military service. It is an experience, not a diagnosis. VA screens veterans for MST and provides free MST-related treatment even when the veteran never reported the event and has no service-connected rating. Knowing this helps counselors connect survivors to care and reduce barriers.',
    references: [{ source: 'VA/DoD CPG', detail: 'Management of PTSD and acute stress disorder: military sexual trauma and access to care' }],
    reviewNote: 'Verify current VA MST eligibility rules (free MST-related care without documentation or rating) and whether the VA/DoD CPG is the best citation; a VA program source may fit better.',
  },

  // ── Chronic illness and disability ────────────────────────────────────────
  {
    id: 'nce-s-clf-118',
    domain: 'clinical_focus',
    cacrep: 'helping_relationships',
    topic: 'chronic illness and disability',
    difficulty: 'medium',
    stem: 'The mother of a 9-year-old with cerebral palsy says she accepted her son\'s diagnosis long ago and loves their life, yet waves of sadness return each time his classmates reach milestones he cannot, such as riding a bike. She asks whether something is wrong with her. Which concept BEST frames her experience?',
    options: [
      { id: 'a', text: 'Prolonged grief disorder from an unresolved earlier loss', isCorrect: false, rationale: 'Prolonged grief disorder follows a death and involves persistent, impairing grief; her sadness is episodic and she functions well.' },
      { id: 'b', text: 'Chronic sorrow, a normal and recurring grief response', isCorrect: true, rationale: 'Chronic sorrow describes periodic, recurring grief triggered by milestones in parents of children with lasting disabilities; it is not pathological.' },
      { id: 'c', text: 'Denial, the first stage that she has not yet moved beyond', isCorrect: false, rationale: 'She openly acknowledges the disability; renewed sadness is not denial, and stage models are not strictly linear.' },
      { id: 'd', text: 'A major depressive episode with a seasonal recurring pattern', isCorrect: false, rationale: 'Brief, triggered waves of sadness with good functioning do not meet criteria for a depressive episode.' },
    ],
    rationale: 'Olshansky introduced chronic sorrow to describe the recurring sadness of parents of children with lifelong disabilities. Grief resurfaces at milestones, transitions and reminders of the gap between expected and actual life, while day-to-day functioning and love for the child remain intact. Counselors normalize this pattern instead of framing it as failed acceptance.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling families of people with disabilities: chronic sorrow' }],
    reviewNote: 'Confirm the cited Gladding edition discusses chronic sorrow (Olshansky, 1962).',
  },
];
