// tools/nce/seed/core-5.js — Core Counseling Attributes, batch 5
// Hand-authored original items (nce-s-cor-065 … nce-s-cor-080).
module.exports = [
  {
    id: 'nce-s-cor-065',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'counselor self-awareness and bias',
    difficulty: 'hard',
    stem: `A counselor in long-term recovery through a 12-step program works at an outpatient clinic. Reviewing her notes, she sees that she steers nearly every client toward meetings and describes clients who prefer SMART Recovery or medication for opioid use disorder as "not ready." Which step BEST reflects counselor self-awareness?`,
    options: [
      { id: 'a', text: `Keep recommending 12-step meetings, since her own recovery shows how well that path works`, isCorrect: false, rationale: `This generalizes from one personal experience to all clients and leaves the bias in place.` },
      { id: 'b', text: `Tell each client about her own recovery so they understand why she favors 12-step meetings`, isCorrect: false, rationale: `Self-disclosure here serves to justify the counselor's preference and adds pressure; it does not examine the bias.` },
      { id: 'c', text: `Recognize that her own path is shaping her advice, and explore each client's preferred route`, isCorrect: true, rationale: `Naming how her history colors her judgment, then centering each client's choice, is the core of self-awareness and avoids imposing values.` },
      { id: 'd', text: `Stop mentioning any mutual-help groups so that she cannot influence clients' choices at all`, isCorrect: false, rationale: `Withholding useful options overcorrects; the aim is to offer choices without bias, not to remove information.` },
    ],
    rationale: `Counselors' personal histories, including their own recovery, can quietly shape what they recommend and how they label clients. Self-awareness means noticing that pattern, examining it (often in supervision), and returning the choice to the client. ACA Standard A.4.b asks counselors to be aware of and avoid imposing their own values, attitudes and beliefs.`,
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' },
      { source: 'Corey (Theory & Practice)', detail: 'The counselor as a person: personal needs, values and their influence on counseling' },
    ],
  },
  {
    id: 'nce-s-cor-066',
    domain: 'core',
    cacrep: 'group',
    topic: 'counselor self-awareness and bias',
    difficulty: 'medium',
    stem: `A counselor leading a hospital support group for family caregivers reviews a session recording. She notices that she invites the two members who are nurses to speak more often and responds to them at length, while briefly thanking a member with little formal education. What should the leader do?`,
    options: [
      { id: 'a', text: `Reflect on the pattern in supervision and deliberately balance her attention among members`, isCorrect: true, rationale: `Examining the bias and then consciously equalizing attention addresses both the leader's self-knowledge and the group climate.` },
      { id: 'b', text: `Ask the two nurses to share less often so that the other members have more time to speak`, isCorrect: false, rationale: `This places the burden on members for a pattern the leader created and leaves her own bias unexamined.` },
      { id: 'c', text: `Tell the whole group she has been favoring some members, and apologize to all of them at once`, isCorrect: false, rationale: `A group-wide confession without first understanding the pattern may embarrass members and centers the leader.` },
      { id: 'd', text: `Continue as before, because members with clinical training contribute more useful information`, isCorrect: false, rationale: `This rationalizes the bias; every member's experience is valuable, and unequal attention signals unequal worth.` },
    ],
    rationale: `Group leaders communicate members' worth through whom they call on and how fully they respond. Unequal attention based on education or status is a form of bias that can silence members and weaken cohesion. Best practice asks group workers to know their own values and blind spots and to attend to diversity within the group.`,
    references: [{ source: 'ASGW Best Practice Guidelines', detail: 'Best practice in performing: self-knowledge and attention to diversity among members' }],
  },
  {
    id: 'nce-s-cor-067',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'counselor self-awareness and bias',
    difficulty: 'easy',
    stem: `A counselor in training asks her supervisor how to become more aware of her own cultural biases. Which activity MOST directly builds this kind of self-awareness?`,
    options: [
      { id: 'a', text: `Reading research summaries that describe the values of many different cultural groups`, isCorrect: false, rationale: `This builds knowledge about others, a different competency from awareness of one's own biases.` },
      { id: 'b', text: `Treating every client in exactly the same way so that cultural differences stop mattering`, isCorrect: false, rationale: `A "colorblind" stance ignores culture and leaves the counselor's own assumptions unexamined.` },
      { id: 'c', text: `Limiting her caseload to clients whose backgrounds closely match her own life experience`, isCorrect: false, rationale: `Avoiding difference prevents growth and does nothing to surface her assumptions.` },
      { id: 'd', text: `Examining how her upbringing shaped her values, through reflection and supervision`, isCorrect: true, rationale: `Looking inward at how her own cultural history formed her values and reactions is the essence of counselor self-awareness.` },
    ],
    rationale: `Self-awareness is the counselor's understanding of how their own cultural background, values and assumptions shape their perceptions of clients. It grows through deliberate self-reflection, such as journaling or a cultural genogram, and through supervision and feedback. Learning about other groups is valuable but builds knowledge rather than self-awareness.`,
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counselor awareness of own assumptions, values and biases' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counselor self-awareness domain' },
    ],
  },
  {
    id: 'nce-s-cor-068',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'hard',
    stem: `A perfectionistic 20-year-old engineering student has felt worthless since childhood. The counselor notices that she becomes animated and praises him when he reports top grades, but grows quiet when he describes setbacks. From a person-centered view, what is the MAIN concern?`,
    options: [
      { id: 'a', text: `Praising his achievements may slowly weaken his motivation to keep his grades high`, isCorrect: false, rationale: `Motivation is not the person-centered concern here; the issue is what her shifting warmth teaches him about his worth.` },
      { id: 'b', text: `Her responses may repeat the conditions of worth that feed his sense of worthlessness`, isCorrect: true, rationale: `Warmth that rises and falls with performance is conditional regard, echoing the conditions of worth that Rogers saw as the root of incongruence.` },
      { id: 'c', text: `He may come to depend on the counselor's approval more than on support from his peers`, isCorrect: false, rationale: `Dependence could follow, but the central problem is that her regard has become conditional on achievement.` },
      { id: 'd', text: `Talking about setbacks at length may reinforce a negative core belief about himself`, isCorrect: false, rationale: `This is a cognitive framing; person-centered theory sees exploring setbacks in an accepting climate as helpful.` },
    ],
    rationale: `Rogers proposed that people internalize conditions of worth when they are valued only for meeting others' standards, producing incongruence and fragile self-regard. Unconditional positive regard offers acceptance that does not depend on performance. A counselor whose warmth tracks the client's achievements can unintentionally recreate the very conditions that brought him to counseling.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: conditions of worth and unconditional positive regard' }],
  },
  {
    id: 'nce-s-cor-069',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'easy',
    stem: `Which counselor statement BEST illustrates unconditional positive regard?`,
    options: [
      { id: 'a', text: `I'll keep supporting you as long as you keep working on the goals we set together.`, isCorrect: false, rationale: `Support that depends on meeting goals is conditional regard.` },
      { id: 'b', text: `I care about you as a person, whether or not we see this choice the same way.`, isCorrect: true, rationale: `This separates acceptance of the person from agreement with a choice, which is the heart of unconditional positive regard.` },
      { id: 'c', text: `You're a model client. You do everything I suggest for you between our sessions.`, isCorrect: false, rationale: `Praise tied to compliance signals that the client is valued for doing what the counselor wants.` },
      { id: 'd', text: `I'm proud of you for making the right decision this week instead of the old one.`, isCorrect: false, rationale: `This evaluates the client's choice as right or wrong, implying regard depends on the "right" behavior.` },
    ],
    rationale: `Unconditional positive regard is Rogers' term for accepting and caring for the client as a person without conditions. It does not require approving of every behavior, but the counselor's valuing of the client does not rise or fall with the client's choices. Praise tied to compliance or "right" decisions conveys conditional acceptance.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance' }],
  },
  {
    id: 'nce-s-cor-070',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'medium',
    stem: `In the fifth session, a counselor refers to a grieving client's late son as "Marcus." The client stiffens and says quietly, "His name was Martin." Which counselor response BEST demonstrates congruence?`,
    options: [
      { id: 'a', text: `Of course, Martin. Let's go back to what you were saying about the funeral service.`, isCorrect: false, rationale: `Glossing over the error hides the counselor's real experience and leaves the client's hurt unacknowledged.` },
      { id: 'b', text: `I see many clients, and names sometimes get mixed up. I'm sorry that it happened.`, isCorrect: false, rationale: `The excuse is defensive and minimizes the mistake, shifting attention to the counselor's workload.` },
      { id: 'c', text: `I'm fairly sure the name was written that way in my notes, so I'll check them later.`, isCorrect: false, rationale: `This deflects responsibility to the paperwork rather than owning the error.` },
      { id: 'd', text: `I got his name wrong, and I'm sorry. Martin matters, and I want to get it right.`, isCorrect: true, rationale: `The counselor openly owns the mistake and conveys real care, so words and inner experience match.` },
    ],
    rationale: `Congruence means the counselor is genuine: what they express matches what they actually experience, without a professional facade. When a counselor makes a mistake, a congruent response owns it simply and honestly rather than hiding, excusing or deflecting it. Such moments, handled openly, often strengthen trust.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence, or genuineness' }],
  },
  {
    id: 'nce-s-cor-071',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'hard',
    stem: `A trainee tells her supervisor, "To be congruent, I should tell clients every reaction I have toward them as soon as I notice it." Which reply from the supervisor MOST accurately describes congruence in person-centered theory?`,
    options: [
      { id: 'a', text: `Congruence means your inner experience and outward expression match, not voicing every feeling`, isCorrect: true, rationale: `Rogers described congruence as awareness and genuineness, with no facade; it does not require impulsively sharing every reaction.` },
      { id: 'b', text: `Congruence is mainly about matching your body language to the client's posture and vocal tone`, isCorrect: false, rationale: `This describes mirroring, an attending technique, not genuineness.` },
      { id: 'c', text: `Congruence requires sharing your personal history so the client sees you as an equal partner`, isCorrect: false, rationale: `Self-disclosure of history is a separate skill and is not what congruence requires.` },
      { id: 'd', text: `Congruence is reached by keeping a calm, neutral manner no matter what you feel in a session`, isCorrect: false, rationale: `Hiding behind a neutral front is the professional facade that congruence rejects.` },
    ],
    rationale: `In person-centered theory, congruence means the counselor's inner experience, awareness and outward expression are consistent, so there is no false front. It does not mean impulsively sharing every feeling. Counselors use judgment about expressing persistent reactions that are relevant to the relationship, and they do so in a way that serves the client.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence does not mean impulsive sharing of all reactions' }],
  },
  {
    id: 'nce-s-cor-072',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'medium',
    stem: `A 45-year-old client seeking help with heavy weekend drinking says his goal is to cut back to two drinks a night, not to quit. He has no history of withdrawal. The counselor believes abstinence would be safer. Which approach BEST strengthens the working alliance?`,
    options: [
      { id: 'a', text: `Explain that moderation goals rarely succeed, and make abstinence the first treatment goal`, isCorrect: false, rationale: `Imposing the counselor's goal undermines agreement on goals, a core component of the alliance.` },
      { id: 'b', text: `Accept his goal without discussing it at all, so that he does not feel pressured or judged`, isCorrect: false, rationale: `Silently withholding a relevant concern is not genuine collaboration and skips mutual goal-setting.` },
      { id: 'c', text: `Share her concern with permission, then agree with him on a goal and tasks he will try`, isCorrect: true, rationale: `Offering her view respectfully while negotiating shared goals and tasks builds the agreement and bond the alliance depends on.` },
      { id: 'd', text: `Put off any goal setting until he has kept a drinking diary for several weeks on his own`, isCorrect: false, rationale: `Monitoring can help, but delaying all goal discussion leaves the alliance without shared direction.` },
    ],
    rationale: `Bordin described the working alliance as agreement on goals, agreement on tasks, and an emotional bond. When client and counselor see the goal differently, the counselor can share information with permission while respecting the client's autonomy and negotiating a goal both can work toward. Imposing a goal, or hiding a concern, weakens that collaboration.`,
    references: [
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'The working alliance: goals, tasks and bond' },
      { source: 'Miller & Rollnick (MI)', detail: 'Exchanging information with permission; supporting autonomy in goal choice' },
    ],
  },
  {
    id: 'nce-s-cor-073',
    domain: 'core',
    cacrep: 'group',
    topic: 'therapeutic alliance',
    difficulty: 'medium',
    stem: `At the first meeting of a 10-week court-mandated anger management group, several members say they are only there to get their paperwork signed. Which leader action is MOST likely to begin building a working alliance with the members?`,
    options: [
      { id: 'a', text: `Review the attendance rules and the consequences of missing sessions for each member`, isCorrect: false, rationale: `Rules need to be clear, but leading with consequences emphasizes control rather than shared purpose.` },
      { id: 'b', text: `Remind them that their anger brought them here, so they should take the group seriously`, isCorrect: false, rationale: `Lecturing increases defensiveness and does nothing to create agreement on goals.` },
      { id: 'c', text: `Show a video outlining the curriculum so that members know what the group expects of them`, isCorrect: false, rationale: `This presents tasks without the members' input, missing agreement on goals and the bond.` },
      { id: 'd', text: `Acknowledge the mandate and invite each member to name a goal worth working on for them`, isCorrect: true, rationale: `Validating the reality of the mandate while eliciting personal goals starts agreement on goals and builds the bond.` },
    ],
    rationale: `With mandated members, the alliance begins by acknowledging their situation honestly and finding goals that matter to them within the group's requirements. Bordin's components of goals, tasks and bond apply in groups as in individual work. Leading with rules or lectures tends to deepen resistance rather than engagement.`,
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Working alliance with reluctant and involuntary clients; goals, tasks and bond' }],
  },
  {
    id: 'nce-s-cor-074',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: `A 34-year-old client who uses a power wheelchair arrives for an intake with a personal care attendant. Which counselor behavior BEST conveys respect?`,
    options: [
      { id: 'a', text: `Speaking directly to the client and asking how they would like the room arranged`, isCorrect: true, rationale: `Addressing the client directly and inviting their preferences treats them as the expert on their own needs.` },
      { id: 'b', text: `Directing the intake questions to the attendant, who likely knows the client's needs`, isCorrect: false, rationale: `Talking past the client to a companion is disrespectful and undermines the client's autonomy.` },
      { id: 'c', text: `Moving the wheelchair closer to the desk so the client does not have to adjust it`, isCorrect: false, rationale: `A wheelchair is part of the client's personal space; moving it without asking is intrusive.` },
      { id: 'd', text: `Telling the client how inspiring it is that they still get out and come to counseling`, isCorrect: false, rationale: `Calling routine activity "inspiring" is patronizing and frames disability as the client's defining trait.` },
    ],
    rationale: `Respect means treating clients as capable adults and the experts on their own lives. With clients who have disabilities, that includes speaking to them directly rather than through companions, asking before offering help, and avoiding patronizing praise. These behaviors communicate that the client, not the disability, is the focus.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling individuals with disabilities: addressing the person directly and avoiding paternalism' }],
  },
  {
    id: 'nce-s-cor-075',
    domain: 'core',
    cacrep: 'group',
    topic: 'warmth and respect',
    difficulty: 'medium',
    stem: `In a school counseling group for 14-year-olds coping with family changes, a usually quiet member describes crying the night her father moved out. Another member snickers. Which leader response BEST conveys warmth and respect while protecting the group?`,
    options: [
      { id: 'a', text: `Ignore the snicker so that the attention stays on the member who just took a risk`, isCorrect: false, rationale: `Ignoring the behavior leaves the sharer exposed and implies that mocking is acceptable in the group.` },
      { id: 'b', text: `Calmly block the snicker, then thank the member for trusting the group with this`, isCorrect: true, rationale: `Blocking protects the vulnerable member, and the warm acknowledgment honors her risk and reinforces safety norms.` },
      { id: 'c', text: `Ask the member who snickered to leave the room until he is able to act respectfully`, isCorrect: false, rationale: `Removal is a heavy first response that shames the other teen and shifts focus away from the sharer.` },
      { id: 'd', text: `Ask the group to vote on whether laughing at another member should be against the rules`, isCorrect: false, rationale: `Putting safety to a vote in the moment leaves the sharer unprotected and makes respect negotiable.` },
    ],
    rationale: `Group leaders shape norms of safety and support, especially early and with adolescents. When a member takes a risk and is met with ridicule, the leader blocks the hurtful behavior promptly and then affirms the member who disclosed. Doing both conveys warmth to the individual and respect for the group as a safe place.`,
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'The therapist\'s basic tasks: culture building and shaping norms of safety and support' }],
  },
  {
    id: 'nce-s-cor-076',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'medium',
    stem: `A 52-year-old client tearfully says she has decided to move her mother, who has advanced dementia, into a memory care facility. The counselor grew up in a family where caring for aging parents at home was expected. Which response BEST reflects a nonjudgmental stance?`,
    options: [
      { id: 'a', text: `Did you look into all of the in-home care options before deciding on a facility for her?`, isCorrect: false, rationale: `The question implies the decision was not thought through and carries the counselor's own family values.` },
      { id: 'b', text: `Many families do find a way to keep a parent at home if they get enough outside help.`, isCorrect: false, rationale: `This subtly argues for the counselor's preferred choice and adds to the client's guilt.` },
      { id: 'c', text: `This decision is weighing on you. Tell me what went into it and how you're feeling.`, isCorrect: true, rationale: `The counselor reflects the client's feeling and invites her story without evaluating the choice.` },
      { id: 'd', text: `You made the right choice. Memory care is much better for her than staying at home.`, isCorrect: false, rationale: `Approval is still a judgment; it closes off the client's mixed feelings instead of exploring them.` },
    ],
    rationale: `A nonjudgmental stance withholds both disapproval and approval so that the client can explore her own decision and feelings. Here the counselor's family norms create a pull to question the choice, which ACA Standard A.4.b cautions against. Reflecting the emotional weight and inviting exploration keeps the focus on the client's values.`,
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-cor-077',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'hard',
    stem: `A counselor helping a client with job stress learns the client drinks six to eight beers most nights. Wanting to stay nonjudgmental, the counselor decides not to ask about the drinking because the client has not raised it as a concern. Which statement BEST evaluates this decision?`,
    options: [
      { id: 'a', text: `It is sound, because exploring an issue the client has not raised imposes counselor values`, isCorrect: false, rationale: `Assessing a clinically relevant behavior is not value imposition; ignoring it may leave a real risk unaddressed.` },
      { id: 'b', text: `It is sound, because asking about substance use is likely to damage the working alliance`, isCorrect: false, rationale: `Respectful, curious inquiry seldom harms the alliance; avoiding the topic sacrifices sound care.` },
      { id: 'c', text: `It is unsound, because the counselor should first warn the client about the health risks`, isCorrect: false, rationale: `Leading with a warning is directive and likely to provoke defensiveness; assessment and permission come first.` },
      { id: 'd', text: `It is unsound, because being nonjudgmental withholds moral judgment, not clinical inquiry`, isCorrect: true, rationale: `A nonjudgmental stance concerns how the counselor regards the person, not whether clinically important issues are explored.` },
    ],
    rationale: `Being nonjudgmental means suspending moral evaluation of the client, not suspending clinical judgment. Heavy nightly drinking may bear directly on job stress, health and safety, so the counselor should raise it, ideally by asking permission and exploring with curiosity. Acceptance and assessment work together.`,
    references: [{ source: 'Miller & Rollnick (MI)', detail: 'Acceptance in the spirit of MI; raising a concern with permission' }],
  },
  {
    id: 'nce-s-cor-078',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: `An intake form lists a 30-year-old client's background as "Puerto Rican and Irish." The client has come for help with work stress and uses they/them pronouns. Which approach BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Ask how the client describes their identity and which parts of it matter for this concern`, isCorrect: true, rationale: `Inviting the client to define their identity and its relevance treats them as the expert on their own culture.` },
      { id: 'b', text: `Review literature on Puerto Rican and Irish family values before the next session begins`, isCorrect: false, rationale: `Group knowledge can inform hypotheses, but it risks substituting generalizations for the client's own account.` },
      { id: 'c', text: `Avoid raising culture at all, since the client came in about work stress and not identity`, isCorrect: false, rationale: `Assuming culture is irrelevant forecloses exploration; identity may shape how work stress is experienced.` },
      { id: 'd', text: `Assume the client identifies mostly as Puerto Rican, since that heritage is listed first`, isCorrect: false, rationale: `Inferring identity from the order of words on a form is an assumption, not humility.` },
    ],
    rationale: `Cultural humility emphasizes openness and curiosity about how each client understands their own identities, rather than presuming. Multiracial and multiethnic clients in particular may identify in many ways, and those identities may matter more or less for a given concern. Asking, rather than assuming, keeps the client at the center.`,
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Multiracial individuals: self-identification and avoiding imposed labels' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Client worldview: understanding clients\' multiple identities' },
    ],
  },
  {
    id: 'nce-s-cor-079',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: `A White counselor suggests that a 24-year-old Black client ease evening anxiety by taking long walks through his suburban neighborhood after dark. The client pauses and says, "That's not as simple for me as it might be for you." Which response BEST shows awareness of privilege?`,
    options: [
      { id: 'a', text: `Walking really helps with anxiety, so let's find some ways to make it work for you anyway.`, isCorrect: false, rationale: `This pushes past the client's concern and keeps the counselor's experience as the default.` },
      { id: 'b', text: `You're right, I assumed. Help me understand what walking at night is like for you.`, isCorrect: true, rationale: `The counselor owns that the suggestion reflected her own experience and invites the client's reality.` },
      { id: 'c', text: `I didn't mean anything by it. I suggest walking to all of my clients who have anxiety.`, isCorrect: false, rationale: `Defending intent and claiming equal treatment overlooks that the same advice carries different risks.` },
      { id: 'd', text: `Let's skip walking, then. Breathing exercises are something you can do safely at home.`, isCorrect: false, rationale: `Switching techniques avoids the issue the client raised and misses the chance to repair and learn.` },
    ],
    rationale: `Privilege often shows up as assumptions about what is safe or easy, drawn from the counselor's own experience. When a client signals that a suggestion does not fit his reality, the counselor should acknowledge the assumption without defensiveness and explore the client's experience. This repairs trust and reduces the power imbalance in the relationship.`,
    references: [
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship: how privilege and oppression influence the counselor-client relationship' },
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'White privilege and counselor assumptions' },
    ],
  },
  {
    id: 'nce-s-cor-080',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'easy',
    stem: `A client says, "I finished my degree at 52, and none of my kids came to the graduation. I guess it's no big deal." The counselor replies, "Congratulations! What are your plans now that you've graduated?" On Carkhuff's empathy scale, this response is BEST classified as`,
    options: [
      { id: 'a', text: `Interchangeable (Level 3)`, isCorrect: false, rationale: `An interchangeable response would reflect both the pride and the hurt the client expressed.` },
      { id: 'b', text: `Additive (Level 4)`, isCorrect: false, rationale: `An additive response would go beyond the client's words to name deeper feelings, such as disappointment.` },
      { id: 'c', text: `Subtractive (below Level 3)`, isCorrect: true, rationale: `The reply ignores the hurt about the missing children and moves to a new topic, taking away from what the client expressed.` },
      { id: 'd', text: `Additive (Level 5)`, isCorrect: false, rationale: `Level 5 responses add significantly to the client's feelings and meaning; this one omits the main feeling.` },
    ],
    rationale: `On Carkhuff's five-level scale, Level 3 is interchangeable with the client's expressed feeling and meaning, Levels 4 and 5 are additive, and Levels 1 and 2 are subtractive. A response that attends to surface content while missing the core feeling, here the hurt behind "no big deal," falls below the minimally facilitative level.`,
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Carkhuff\'s scale of empathic understanding: subtractive, interchangeable and additive responses' }],
  },
];
