// tools/nce/seed/core-6.js — Core Counseling Attributes, batch 6
// Hand-authored original items (nce-s-cor-081 … nce-s-cor-096).
module.exports = [
  {
    id: 'nce-s-cor-081',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'hard',
    stem: `A supervisor notes that a counselor stays steady with highly distressed clients because she has a sound, intact character structure and keeps clear boundaries between her own needs and her clients' needs. In Gelso and Hayes's account of countertransference management, this capacity is called`,
    options: [
      { id: 'a', text: `self-integration`, isCorrect: true, rationale: `Self-integration refers to an intact, healthy character structure and the ability to differentiate self from client.` },
      { id: 'b', text: `self-insight`, isCorrect: false, rationale: `Self-insight is awareness of one's own feelings and their origins, not the stability of one's character structure.` },
      { id: 'c', text: `anxiety management`, isCorrect: false, rationale: `Anxiety management is the ability to tolerate and regulate one's anxiety so it does not drive behavior in session.` },
      { id: 'd', text: `conceptualizing skill`, isCorrect: false, rationale: `Conceptualizing skill is the use of theory to understand the client and the relationship, including one's reactions.` },
    ],
    rationale: `Gelso and Hayes describe five interrelated counselor qualities that help manage countertransference: self-insight, self-integration, anxiety management, empathy and conceptualizing skills. Self-integration is the most basic of these: a healthy, well-differentiated sense of self that lets the counselor recognize where they end and the client begins. Without it, the counselor's unresolved needs are more likely to spill into the work.`,
    references: [{ source: 'Gelso & Hayes (Countertransference)', detail: 'Managing countertransference: the five factors (self-insight, self-integration, anxiety management, empathy, conceptualizing skills)' }],
  },
  {
    id: 'nce-s-cor-082',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'hard',
    stem: `A 39-year-old client says early on that everyone eventually gives up on him. He arrives late, dismisses suggestions, and mocks the counselor's questions. The counselor notices she has become curt and is privately hoping he will drop out, much as his family and past employers did. Which view of countertransference BEST fits understanding her reaction as a response pulled by the client's interpersonal style?`,
    options: [
      { id: 'a', text: `The classical view`, isCorrect: false, rationale: `The classical view limits countertransference to the counselor's unconscious, unresolved conflicts reacting to the client's transference.` },
      { id: 'b', text: `The totalistic view`, isCorrect: false, rationale: `The totalistic view counts every counselor reaction as countertransference, without the specific focus on interpersonal pull.` },
      { id: 'c', text: `The complementary view`, isCorrect: true, rationale: `The complementary view sees the counselor's reaction as the response the client's style tends to evoke from others, here rejection.` },
      { id: 'd', text: `The intersubjective view`, isCorrect: false, rationale: `This is not one of the four conceptions Gelso and Hayes outline, and it does not specifically name the interpersonal pull.` },
    ],
    rationale: `Gelso and Hayes describe classical, totalistic, complementary and integrative conceptions of countertransference. The complementary view holds that clients' characteristic interpersonal styles pull predictable responses from others, including the counselor. Recognizing the pull lets the counselor avoid repeating the rejection the client expects and instead use it to understand his relational pattern.`,
    references: [{ source: 'Gelso & Hayes (Countertransference)', detail: 'Ch. 1: classical, totalistic, complementary and integrative conceptions; complementary view and interpersonal pull' }],
  },
  {
    id: 'nce-s-cor-083',
    domain: 'core',
    cacrep: 'group',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: `A leader of an adult grief group feels mounting irritation each time one member tells long stories that fill the session. She reminds herself that monopolizing often shields a member from painful feelings and from closeness with others, and her irritation turns to curiosity. Which countertransference management factor described by Gelso and Hayes is she MOST clearly using?`,
    options: [
      { id: 'a', text: `Self-integration, keeping a stable sense of self apart from members`, isCorrect: false, rationale: `Self-integration concerns an intact character structure; the leader's shift came from applying theory.` },
      { id: 'b', text: `Anxiety management, lowering her own tension so it does not leak out`, isCorrect: false, rationale: `Regulating anxiety helps, but what changed her reaction here was a theoretical understanding of the member.` },
      { id: 'c', text: `Empathy, feeling the member's grief as though it were her own grief`, isCorrect: false, rationale: `Empathy keeps the "as if" quality; merging with the member's grief is not what she did or what empathy means.` },
      { id: 'd', text: `Conceptualizing skills, using theory to make sense of the member's role`, isCorrect: true, rationale: `She drew on a theoretical understanding of monopolizing to interpret the behavior, which defused her reaction.` },
    ],
    rationale: `Conceptualizing skill is the counselor's ability to draw on theory to understand the client's dynamics and the relationship, including the counselor's own reactions. Framing a behavior that irritates the leader as a meaningful defense helps her respond therapeutically instead of acting out irritation. In groups, this lets the leader address the monopolizing in a way that serves both the member and the group.`,
    references: [
      { source: 'Gelso & Hayes (Countertransference)', detail: 'Managing countertransference: conceptualizing skills as a management factor' },
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Problem group members: the monopolist' },
    ],
  },
  {
    id: 'nce-s-cor-084',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'medium',
    stem: `A 28-year-old client with contamination fears says she likes her counselor and agrees that being able to ride the subway again is the right goal. When the counselor proposes exposure exercises, she says, "Touching handrails on purpose makes no sense to me." In Bordin's model, which part of the working alliance is MOST strained?`,
    options: [
      { id: 'a', text: `The goals, since she does not share the aim of returning to the subway`, isCorrect: false, rationale: `She explicitly agrees with the subway goal, so agreement on goals is intact.` },
      { id: 'b', text: `The tasks, since she does not accept the methods proposed to get there`, isCorrect: true, rationale: `Her objection is to the exposure exercises themselves, which is a disagreement about tasks.` },
      { id: 'c', text: `The bond, since her objection shows she does not trust the counselor`, isCorrect: false, rationale: `She says she likes the counselor; the objection concerns the method, not the emotional bond.` },
      { id: 'd', text: `Readiness for change, which Bordin listed as a fourth alliance component`, isCorrect: false, rationale: `Bordin's model has three components (goals, tasks, bond); readiness for change is not one of them.` },
    ],
    rationale: `Bordin defined the working alliance as agreement on goals, agreement on tasks and an emotional bond. A client can share the goal and like the counselor yet reject the methods, which strains the tasks component. Exploring the rationale for exposure collaboratively, and adjusting the steps with the client, helps restore agreement.`,
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Working alliance: goals, tasks and bond (Bordin)' }],
  },
  {
    id: 'nce-s-cor-085',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: `In a first family session, a father says the only problem is his 14-year-old's defiance. The mother says the real issue is the father's drinking, and the teen says nothing needs fixing. Each member is warm toward the counselor but dismisses the others' concerns. Using Friedlander and colleagues' SOFTA framework, which alliance dimension is MOST in need of attention?`,
    options: [
      { id: 'a', text: `Emotional connection to the counselor`, isCorrect: false, rationale: `Each member is warm toward the counselor, so this dimension is not the main concern.` },
      { id: 'b', text: `Engagement in the therapy process`, isCorrect: false, rationale: `Engagement concerns involvement in the work; the defining problem here is disagreement among members.` },
      { id: 'c', text: `Safety within the therapy system`, isCorrect: false, rationale: `Nothing indicates members feel unsafe in session; the issue is a lack of shared aims.` },
      { id: 'd', text: `Shared purpose within the family`, isCorrect: true, rationale: `Members disagree about what the problem is and whether change is needed, which defines a weak within-family alliance.` },
    ],
    rationale: `The System for Observing Family Therapy Alliances (SOFTA) has four dimensions: engagement in the therapeutic process, emotional connection to the therapist, safety within the therapeutic system and shared sense of purpose within the family. Shared purpose is unique to conjoint work because it concerns the alliance among family members, not just with the counselor. Building a common definition of the problem is often a priority before change work can begin.`,
    references: [{ source: 'Friedlander et al. (Alliances in Couple & Family Therapy)', detail: 'SOFTA dimensions: engagement, emotional connection, safety, shared sense of purpose within the family' }],
  },
  {
    id: 'nce-s-cor-086',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'medium',
    stem: `As a client describes a violent assault, a new counselor feels her own heart racing and a strong urge to change the subject so that she can feel calmer. In Davis's multidimensional model of empathy, this self-focused discomfort is BEST described as`,
    options: [
      { id: 'a', text: `personal distress`, isCorrect: true, rationale: `Personal distress is self-oriented anxiety and unease in response to another's suffering, which can push the helper to escape.` },
      { id: 'b', text: `empathic concern`, isCorrect: false, rationale: `Empathic concern is other-oriented warmth and compassion for the person suffering, not anxiety about oneself.` },
      { id: 'c', text: `perspective taking`, isCorrect: false, rationale: `Perspective taking is the cognitive ability to adopt another's viewpoint, not an emotional reaction.` },
      { id: 'd', text: `fantasy`, isCorrect: false, rationale: `The fantasy dimension is the tendency to identify with fictional characters in books or films.` },
    ],
    rationale: `Davis measured empathy with four dimensions: perspective taking, fantasy, empathic concern and personal distress. Empathic concern points the helper toward the other person, while personal distress is focused on the helper's own discomfort and can lead to avoidance. Counselors who notice personal distress can ground themselves and return attention to the client.`,
    references: [{ source: 'Davis (Multidimensional Empathy)', detail: 'Four dimensions: perspective taking, fantasy, empathic concern and personal distress' }],
  },
  {
    id: 'nce-s-cor-087',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'easy',
    stem: `A 20-year-old college student who uses a wheelchair says, "The elevator in my science building broke again, so I missed another lab. My professor just said to get the notes from someone." Which counselor response BEST conveys accurate empathy?`,
    options: [
      { id: 'a', text: `Elevators break down sometimes. Have you thought about asking a classmate for notes?`, isCorrect: false, rationale: `This minimizes the barrier and jumps to advice, so it misses the client's feelings.` },
      { id: 'b', text: `You should file a complaint with disability services right away about that building.`, isCorrect: false, rationale: `Advocacy may help later, but directing action first skips understanding the client's experience.` },
      { id: 'c', text: `You're frustrated, missing labs over something you can't control, and then brushed off.`, isCorrect: true, rationale: `This accurately reflects both the frustration and the sense of being dismissed by the professor.` },
      { id: 'd', text: `I know exactly how you feel. I hated it whenever I had to miss a class in college too.`, isCorrect: false, rationale: `Claiming identical experience shifts focus to the counselor and overlooks the access barrier.` },
    ],
    rationale: `Accurate empathy captures both the client's feeling and the situation that gives rise to it, in the counselor's own words. Here the client's frustration stems from repeated access barriers and a dismissive response, and an empathic reflection names both. Advice, minimizing and "I know exactly how you feel" statements pull away from the client's frame of reference.`,
    references: [{ source: 'Ivey et al. (Intentional Interviewing)', detail: 'Reflection of feeling and empathic understanding' }],
  },
  {
    id: 'nce-s-cor-088',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'easy',
    stem: `When a client begins describing his sexual history, the counselor says, "I'm completely comfortable with this topic." As she speaks, her voice tightens, she leans back, and she starts taking notes rapidly. The client grows guarded. Which core condition is MOST clearly lacking?`,
    options: [
      { id: 'a', text: `Unconditional positive regard`, isCorrect: false, rationale: `Nothing shows she values him less; the problem is the mismatch between her words and her state.` },
      { id: 'b', text: `Congruence`, isCorrect: true, rationale: `Her words deny discomfort that her voice and posture reveal, a clear mismatch between inner experience and expression.` },
      { id: 'c', text: `Concreteness`, isCorrect: false, rationale: `Concreteness is helping a client be specific; it does not explain the client's guardedness here.` },
      { id: 'd', text: `Accurate empathy`, isCorrect: false, rationale: `She has not yet misread his feelings; the breakdown lies in her own genuineness.` },
    ],
    rationale: `Congruence means the counselor's outward communication matches inner experience. Clients often read nonverbal cues more readily than words, so a counselor who claims comfort while showing tension can seem untrustworthy. A congruent counselor notices the discomfort, manages it, and, if relevant, acknowledges it honestly rather than covering it with a facade.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence or genuineness' }],
  },
  {
    id: 'nce-s-cor-089',
    domain: 'core',
    cacrep: 'group',
    topic: 'congruence and genuineness',
    difficulty: 'medium',
    stem: `In week five of a parenting skills group, three members again arrive 15 minutes late, and the leader has felt frustrated for weeks. One member says, "You seem annoyed with us today. Are you?" Which leader response BEST demonstrates congruence?`,
    options: [
      { id: 'a', text: `Not at all. I'm here to support all of you, so let's get back to the topic for today.`, isCorrect: false, rationale: `Denying a feeling the members can already sense is incongruent and models avoidance.` },
      { id: 'b', text: `Yes. Some of you clearly don't respect this group, and that needs to change right now.`, isCorrect: false, rationale: `This voices the feeling as blame and judgment, not as an owned reaction the group can explore.` },
      { id: 'c', text: `Yes, I've felt frustrated about the late arrivals. I'd like us to talk about it together.`, isCorrect: true, rationale: `The leader owns the feeling honestly and turns it into a here-and-now discussion that serves the group.` },
      { id: 'd', text: `What makes you ask? I'm curious what you're noticing, and how others see me today.`, isCorrect: false, rationale: `Deflecting the direct question keeps the leader's real reaction hidden behind a technique.` },
    ],
    rationale: `A congruent leader's words match their inner experience, and they share relevant feelings in an owned, nonblaming way when it helps the work. Acknowledging frustration and inviting discussion models honest communication and lets members examine a pattern that affects the whole group. Denial or deflection teaches members that real reactions are not welcome.`,
    references: [
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Therapist transparency and here-and-now focus' },
      { source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence or genuineness' },
    ],
  },
  {
    id: 'nce-s-cor-090',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'medium',
    stem: `A 31-year-old mother whose children were placed in foster care for neglect a year ago has completed her case plan and has regained custody. She says, "Everyone still looks at me like I'm a bad mother. I bet you do too." Which counselor response BEST conveys unconditional positive regard?`,
    options: [
      { id: 'a', text: `You did neglect them before, but what really matters most now is that you've changed.`, isCorrect: false, rationale: `This makes her worth depend on having changed, which is conditional regard.` },
      { id: 'b', text: `I don't see you that way. I value you as a person, including the hard parts of your story.`, isCorrect: true, rationale: `This affirms her worth without conditions and without denying or condemning her history.` },
      { id: 'c', text: `Other people's opinions shouldn't matter, so try not to worry about how they look at you.`, isCorrect: false, rationale: `This dismisses her pain and sidesteps her question about how the counselor sees her.` },
      { id: 'd', text: `You've done everything the court asked of you, so you have earned some respect from me.`, isCorrect: false, rationale: `Respect framed as earned by compliance is conditional, the opposite of unconditional regard.` },
    ],
    rationale: `Unconditional positive regard is the counselor's acceptance and valuing of the client as a person, not contingent on behavior or progress. It does not require approving of past actions, but it separates the client's worth from them. For clients who carry shame and expect judgment, this acceptance helps them examine their experience openly.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance' }],
  },
  {
    id: 'nce-s-cor-091',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: `During a telehealth session, a client's 4-year-old wakes from a nap crying, and the client says, "I'm so sorry, I have to go check on her." Which counselor response BEST conveys warmth?`,
    options: [
      { id: 'a', text: `Please try to arrange childcare for our sessions so we're not interrupted again.`, isCorrect: false, rationale: `This focuses on the inconvenience and adds pressure at a stressful moment.` },
      { id: 'b', text: `That's fine, but we'll need to end on time even if we lose some minutes now.`, isCorrect: false, rationale: `Leading with the time limit sounds cool and rule-focused rather than caring.` },
      { id: 'c', text: `We can just reschedule the rest. Message me later whenever things calm down.`, isCorrect: false, rationale: `Ending abruptly may feel like a dismissal and gives up the session without asking.` },
      { id: 'd', text: `Of course, no need to apologize. Go take care of her; I'll be right here.`, isCorrect: true, rationale: `This relieves her guilt, accepts her parenting role, and signals the counselor's steady availability.` },
    ],
    rationale: `Warmth is conveyed through acceptance, kindness and a relaxed, caring manner, especially when a client feels embarrassed. Telehealth brings clients' home lives into the session, and responding to interruptions with understanding protects the relationship. Logistics can be discussed later if interruptions become a pattern.`,
    references: [{ source: 'Ivey et al. (Intentional Interviewing)', detail: 'Empathic relationship: warmth and positive regard' }],
  },
  {
    id: 'nce-s-cor-092',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'easy',
    stem: `A 38-year-old client says, "My partner and I decided we're never having kids. My parents keep saying I'll regret it and that it's selfish." Which counselor response BEST reflects a nonjudgmental stance?`,
    options: [
      { id: 'a', text: `It sounds like you've made your decision, and their comments are weighing on you.`, isCorrect: true, rationale: `This accepts the decision as the client's and focuses on the client's experience of the pressure.` },
      { id: 'b', text: `Your parents might have a point. A lot of people do change their minds about this.`, isCorrect: false, rationale: `This sides with the parents and implies the client's choice is likely mistaken.` },
      { id: 'c', text: `Have you and your partner fully thought through what you might miss out on later?`, isCorrect: false, rationale: `This questions the soundness of the decision rather than exploring what the client brought.` },
      { id: 'd', text: `Good for you both. Honestly, having children isn't the right choice for most people.`, isCorrect: false, rationale: `Approval is still judgment, and it imposes the counselor's own view about having children.` },
    ],
    rationale: `A nonjudgmental stance means the counselor neither condemns nor endorses the client's life choices, staying with the client's own meaning and feelings. Both disapproval and enthusiastic approval insert the counselor's values. Here the client's concern is family pressure, so the counselor reflects that experience.`,
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-cor-093',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: `A hearing counselor working with a 34-year-old Deaf client through an ASL interpreter suggests they explore "grief about your hearing loss." The client signs that she was born Deaf, sees Deafness as her culture, and feels no loss about it. Which next step BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Explain that many people do grieve hearing loss, so it may still be worth exploring later on`, isCorrect: false, rationale: `This holds onto the counselor's frame and overrides the client's own view of her identity.` },
      { id: 'b', text: `Ask the client to spend the next session teaching her everything she should know about Deaf culture`, isCorrect: false, rationale: `This shifts the counselor's learning burden onto the client and takes over the client's session.` },
      { id: 'c', text: `Own the assumption, follow the client's view of Deafness, and learn about Deaf culture herself`, isCorrect: true, rationale: `This acknowledges the error, centers the client's identity, and accepts responsibility for ongoing learning.` },
      { id: 'd', text: `Refer the client to a Deaf counselor, since a hearing counselor cannot understand her experience`, isCorrect: false, rationale: `Referral may be an option the client chooses, but reflexive referral avoids the repair and the relationship.` },
    ],
    rationale: `Cultural humility involves an accurate view of one's own limits, openness to the client's perspective, and ongoing self-directed learning. Many Deaf people view Deafness as a linguistic and cultural identity rather than a medical loss, and a hearing counselor's deficit framing can feel invalidating. Owning the assumption repairs the relationship, while learning on one's own time avoids making the client the teacher.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling individuals with disabilities; Deaf culture and the medical vs cultural model' }],
  },
  {
    id: 'nce-s-cor-094',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'hard',
    stem: `A 27-year-old Mexican American client describes being followed by store security while shopping. Hoping to reassure her, the counselor says, "I don't really see color. To me, everyone is just a person." The client changes the subject. In Sue's taxonomy of microaggressions, the counselor's comment is BEST classified as a`,
    options: [
      { id: 'a', text: `microassault`, isCorrect: false, rationale: `Microassaults are explicit, usually deliberate attacks; the counselor meant to be reassuring.` },
      { id: 'b', text: `microinsult`, isCorrect: false, rationale: `Microinsults demean a person's heritage or ability, such as implying a client is less capable.` },
      { id: 'c', text: `microaffirmation`, isCorrect: false, rationale: `Microaffirmations are small acts of inclusion, not one of Sue's three forms of microaggression.` },
      { id: 'd', text: `microinvalidation`, isCorrect: true, rationale: `Color-blind statements negate the client's racialized experience and reality, the hallmark of a microinvalidation.` },
    ],
    rationale: `Sue described three forms of microaggression: microassaults, microinsults and microinvalidations. Color-blind remarks are a classic microinvalidation because they deny the relevance of race just as the client reports a racialized experience. Counselors' good intentions do not cancel the impact, which is why self-awareness of such reflexive reassurances matters.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Racial microaggressions: microinvalidations and color blindness' }],
  },
  {
    id: 'nce-s-cor-095',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'counselor self-awareness and bias',
    difficulty: 'medium',
    stem: `A 74-year-old widow tells her counselor she has a new partner and wants to talk about sexual intimacy, which feels different than it did decades ago. The counselor, in her thirties, finds herself steering back to the client's health appointments. What is the MOST appropriate response to this pattern?`,
    options: [
      { id: 'a', text: `Notice her possible age-related assumptions and return to the concern the client raised`, isCorrect: true, rationale: `Recognizing the bias and refocusing on the client's stated goal is the core of self-awareness.` },
      { id: 'b', text: `Refer the client to a medical provider, since sexual concerns in later life are medical`, isCorrect: false, rationale: `This treats the concern as purely medical and avoids the topic the client chose to bring to counseling.` },
      { id: 'c', text: `Keep the focus on health care, because that is more likely to be the client's real priority`, isCorrect: false, rationale: `This substitutes the counselor's assumption about older adults for the client's own stated priority.` },
      { id: 'd', text: `Tell the client she feels awkward about the subject and ask her to choose a different topic`, isCorrect: false, rationale: `Placing the counselor's discomfort on the client restricts the work instead of managing the reaction.` },
    ],
    rationale: `Ageist assumptions, such as viewing older adults as asexual, can lead counselors to avoid topics clients want to address. Self-awareness means noticing when one's own discomfort or stereotypes are steering the session, exploring that in supervision, and following the client's agenda. Sexuality remains an important part of well-being across the lifespan.`,
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' },
      { source: 'Berk (Development Through the Lifespan)', detail: 'Late adulthood: sexuality and intimate relationships' },
    ],
  },
  {
    id: 'nce-s-cor-096',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: `A heterosexual counselor at a rural clinic realizes that the agency's intake form offers only "husband" or "wife" for partner status. A gay client mentions he left the field blank and wondered whether he would be welcome. Which action BEST reflects awareness of privilege in the counseling relationship?`,
    options: [
      { id: 'a', text: `Reassure the client that the form is just paperwork and has no effect on how he is treated`, isCorrect: false, rationale: `This dismisses the message the form sends and the client's reasonable concern about safety.` },
      { id: 'b', text: `Acknowledge what the form signals, ask how he describes his relationship, and push to revise it`, isCorrect: true, rationale: `This names the impact, centers the client's terms and addresses the institutional barrier.` },
      { id: 'c', text: `Fill in "wife" so that the record is complete, and then move on to the presenting concern`, isCorrect: false, rationale: `This erases the client's identity and repeats the heteronormative assumption in the record.` },
      { id: 'd', text: `Avoid asking about his relationship in the future so that he is not made to feel uncomfortable`, isCorrect: false, rationale: `Avoidance withholds attention from a relevant part of his life and implies the topic is unwelcome.` },
    ],
    rationale: `Heterosexual privilege includes not having to notice that forms and routines assume one's own identity. Counselors who hold privilege can acknowledge how such systems affect clients, invite clients to describe themselves in their own terms, and advocate to change exclusionary practices. The MSJCC frame this as awareness of how privileged and marginalized statuses shape the relationship and the setting.`,
    references: [
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship and advocacy: privileged and marginalized statuses and institutional barriers' },
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ clients: heterosexism and heterosexual privilege' },
    ],
  },
];
