// tools/nce/seed/core-1.js — Core Counseling Attributes (core), items 001–016.
module.exports = [
  {
    id: 'nce-s-cor-001',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'medium',
    stem: 'A 34-year-old client says, "My boss praised my project in front of everyone, but then gave the promotion to someone else. I don\'t know what to think." Which counselor response is an interchangeable (Level 3) response on Carkhuff\'s empathy scale?',
    options: [
      { id: 'a', text: 'You should ask your boss directly why you were passed over this time.', isCorrect: false, rationale: 'Advice-giving ignores the client\'s feelings entirely; it is subtractive (Level 1 or 2), not interchangeable.' },
      { id: 'b', text: 'You feel confused because the praise and the promotion decision don\'t match.', isCorrect: true, rationale: 'This captures the feeling (confusion) and its stated cause at the same depth the client expressed, which is the definition of a Level 3 interchangeable response.' },
      { id: 'c', text: 'Underneath the confusion, you may fear that your hard work goes unrecognized.', isCorrect: false, rationale: 'This goes beyond what the client expressed to an underlying feeling and meaning, making it additive (Level 4), not interchangeable.' },
      { id: 'd', text: 'Lots of people get passed over at work, and it usually works out fine in the end.', isCorrect: false, rationale: 'Reassurance minimizes the experience and shifts away from the client\'s feelings, a subtractive response.' },
    ],
    rationale: 'Carkhuff\'s scale rates counselor responses from 1 to 5. Level 3 is the minimally facilitative, interchangeable level: the counselor reflects essentially the same feeling and meaning the client expressed, adding nothing and taking nothing away. Levels 1 and 2 subtract from the client\'s message, and Levels 4 and 5 add depth beyond it.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Carkhuff\'s scale of empathic understanding, Levels 1-5' }],
  },
  {
    id: 'nce-s-cor-002',
    reviewNote: 'Option A is rated Level 2 in its rationale; raters may disagree on the exact level (it is clearly not additive).',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'hard',
    stem: 'In a sixth session, a graduate student says, "I keep telling everyone I\'m fine with moving home after graduation. My parents are happy, so I guess I should be too." Which counselor response BEST illustrates additive (Level 4) empathy?',
    options: [
      { id: 'a', text: 'So you\'re moving home after graduation, and your parents are pleased with it.', isCorrect: false, rationale: 'This paraphrases the content but omits feeling; it is at best Level 2, slightly subtractive.' },
      { id: 'b', text: 'You feel fine about moving home, since your parents are happy with the plan.', isCorrect: false, rationale: 'This repeats the client\'s surface statement and misses the doubt in "I guess I should be"; it does not add depth.' },
      { id: 'c', text: 'Why do you think your parents\' happiness matters so much in this decision?', isCorrect: false, rationale: 'A why-question invites intellectualizing and does not communicate understanding of the feeling, so it is not an empathic response.' },
      { id: 'd', text: 'You sound unsure, as if your own wishes got set aside to keep your parents happy.', isCorrect: true, rationale: 'This names the implicit ambivalence and the meaning beneath it (setting aside one\'s own wishes), adding accurately to what the client said: Level 4.' },
    ],
    rationale: 'Additive empathy (Carkhuff Levels 4-5) goes beyond the client\'s explicit words to reflect feelings and meanings the client implied but did not fully state, which helps the client explore at a deeper level. To be additive rather than inaccurate, the reflection must stay grounded in cues the client gave, such as the hedged "I guess I should be."',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Advanced (additive) empathy, Carkhuff Levels 4-5' }],
  },
  {
    id: 'nce-s-cor-003',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'easy',
    stem: 'On Carkhuff\'s five-level scale of empathic understanding, a counselor response rated at Level 1 or Level 2 is described as which of the following?',
    options: [
      { id: 'a', text: 'Subtractive, detracting from what the client expressed', isCorrect: true, rationale: 'Levels 1 and 2 are subtractive: they ignore or only partly capture the client\'s feelings and meaning.' },
      { id: 'b', text: 'Interchangeable, matching the client\'s expressed feeling', isCorrect: false, rationale: 'Interchangeable, minimally facilitative responses are Level 3.' },
      { id: 'c', text: 'Additive, reflecting feelings below the client\'s words', isCorrect: false, rationale: 'Additive responses that reach underlying feelings are Levels 4 and 5.' },
      { id: 'd', text: 'Facilitative, the baseline goal for beginning counselors', isCorrect: false, rationale: 'Level 3 is the minimally facilitative baseline counselors aim to reach consistently; Levels 1-2 fall below it.' },
    ],
    rationale: 'Carkhuff\'s scale runs from Level 1 (the response ignores or contradicts the client\'s feelings) to Level 5 (the response adds significantly to the client\'s awareness). Levels 1-2 are subtractive, Level 3 is interchangeable and minimally facilitative, and Levels 4-5 are additive.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Carkhuff\'s scale of empathic understanding' }],
  },
  {
    id: 'nce-s-cor-004',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'easy',
    stem: 'A client tearfully describes the recent death of her dog. Which counselor response reflects empathy rather than sympathy?',
    options: [
      { id: 'a', text: 'I\'m so sorry; I lost my own dog last year and I still cry about it sometimes too.', isCorrect: false, rationale: 'This shifts the focus to the counselor\'s own loss and expresses pity or shared distress, which is sympathy and self-disclosure, not empathy.' },
      { id: 'b', text: 'That is such a sad thing to go through, and I feel terrible for you today.', isCorrect: false, rationale: 'Feeling sorry for the client is sympathy; it conveys the counselor\'s feeling rather than understanding of the client\'s.' },
      { id: 'c', text: 'Losing her has left a real emptiness in your days, and the grief feels heavy.', isCorrect: true, rationale: 'This communicates accurate understanding of the client\'s own experience from her frame of reference, which is empathy.' },
      { id: 'd', text: 'At least she had a long life with you, and you gave her a very good home.', isCorrect: false, rationale: '"At least" reassurance minimizes the loss and moves away from the client\'s feelings.' },
    ],
    rationale: 'Empathy is understanding the client\'s world as if it were one\'s own, without losing the "as if" quality, and communicating that understanding back. Sympathy centers on the helper\'s own feelings of sorrow or pity for the client, which can shift the focus away from the client.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: accurate empathic understanding' }],
  },
  {
    id: 'nce-s-cor-005',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'medium',
    stem: 'A 52-year-old client says, "I yelled at my teenage son last night and called him useless. I\'m ashamed to even tell you." Which counselor response BEST demonstrates unconditional positive regard?',
    options: [
      { id: 'a', text: 'That was harsh, but I\'m sure you are a good parent most of the time anyway.', isCorrect: false, rationale: 'Reassurance about being a "good parent" is conditional praise; it evaluates the client rather than accepting the client.' },
      { id: 'b', text: 'Calling him useless can do real damage, so let\'s plan what to say instead.', isCorrect: false, rationale: 'This jumps to evaluation and correction before the client feels accepted; it is not an expression of UPR.' },
      { id: 'c', text: 'It took courage to share that, and I\'m glad you trusted me with it here.', isCorrect: true, rationale: 'This accepts the client as a person, without approving or condemning the behavior, and values the client\'s openness, which is UPR.' },
      { id: 'd', text: 'Don\'t be ashamed, since all parents lose their temper and say things they regret.', isCorrect: false, rationale: 'Telling the client not to feel shame dismisses the feeling and normalizes too quickly; it is reassurance, not acceptance.' },
    ],
    rationale: 'Rogers described unconditional positive regard as a warm acceptance of the client as a person, without conditions of worth. UPR does not mean approving of every behavior; it means the client\'s worth is not contingent on what is disclosed, which lowers defensiveness and supports self-exploration.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance' }],
  },
  {
    id: 'nce-s-cor-006',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'medium',
    stem: 'Midway through a session, a client asks, "You look distracted. Are you even listening to me?" The counselor realizes her attention had drifted. Which response BEST demonstrates congruence?',
    options: [
      { id: 'a', text: 'You\'re right, my mind wandered for a moment. I\'m with you now; please go on.', isCorrect: true, rationale: 'The counselor\'s words match her inner experience, she owns it briefly, and she returns the focus to the client, which is congruence.' },
      { id: 'b', text: 'Of course I\'m listening, and I have been following everything you\'ve said.', isCorrect: false, rationale: 'Denying a lapse the counselor knows occurred is incongruent; outward words do not match inner experience.' },
      { id: 'c', text: 'It sounds like you worry people don\'t listen to you. Tell me more about that.', isCorrect: false, rationale: 'Reflecting the client\'s concern here deflects from the counselor\'s actual lapse and avoids genuineness.' },
      { id: 'd', text: 'I\'ve had a long, stressful day with other clients, so I\'m tired and distracted.', isCorrect: false, rationale: 'This is honest but over-discloses and shifts the focus to the counselor\'s needs rather than the relationship.' },
    ],
    rationale: 'Congruence (genuineness) means the counselor\'s outward behavior is consistent with inner experience, without a professional facade. Rogers viewed it as the most basic of the core conditions. Being genuine does not require disclosing every feeling; the counselor shares what is relevant to the relationship and keeps the focus on the client.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence or genuineness' }],
  },
  {
    id: 'nce-s-cor-007',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'easy',
    stem: 'Bordin\'s pantheoretical model of the working alliance consists of which three components?',
    options: [
      { id: 'a', text: 'Empathy, congruence, and positive regard', isCorrect: false, rationale: 'These are Rogers\' core conditions, not Bordin\'s alliance components.' },
      { id: 'b', text: 'Rapport, insight, and corrective feedback', isCorrect: false, rationale: 'These are general therapy processes, not the components Bordin named.' },
      { id: 'c', text: 'Trust, transference, and client motivation', isCorrect: false, rationale: 'Transference is a psychodynamic concept; Bordin\'s model was explicitly pantheoretical.' },
      { id: 'd', text: 'Agreement on goals, tasks, and the bond', isCorrect: true, rationale: 'Bordin defined the working alliance as agreement on goals, agreement on tasks, and the emotional bond between counselor and client.' },
    ],
    rationale: 'Bordin (1979) proposed that the working alliance has three parts: agreement on the goals of counseling, agreement on the tasks used to reach them, and the affective bond between counselor and client. Because it is pantheoretical, the model applies across approaches, and alliance strength is one of the most consistent predictors of outcome.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'The working alliance: goals, tasks, and bond' }],
  },
  {
    id: 'nce-s-cor-008',
    reviewNote: 'Rupture-repair evidence (Safran et al.) is cited to a general Gladding alliance reference.',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: 'In the fourth session, a client who has been completing CBT thought records says flatly, "I did the homework again, I guess. Whatever helps you." The client has arrived late twice. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Review the thought record in detail and praise the client for completing it', isCorrect: false, rationale: 'Proceeding with the task ignores the withdrawal cues and leaves a possible rupture unaddressed.' },
      { id: 'b', text: 'Invite the client to talk about how the work together is feeling so far', isCorrect: true, rationale: 'Openly exploring the relationship addresses a likely withdrawal rupture and checks agreement on tasks and goals before continuing.' },
      { id: 'c', text: 'Set a lateness policy so that attendance does not continue to slip further', isCorrect: false, rationale: 'Focusing on rules treats the lateness as a compliance issue and can deepen the rupture.' },
      { id: 'd', text: 'Switch to a different intervention, since thought records are not working', isCorrect: false, rationale: 'Changing tasks unilaterally skips collaboration; the counselor does not yet know what the client wants or is reacting to.' },
    ],
    rationale: 'Flat compliance ("whatever helps you") and lateness suggest a withdrawal rupture in the alliance, often reflecting disagreement about tasks or goals or strain in the bond. Research on rupture and repair supports raising the relationship directly and nondefensively, which lets the counselor renegotiate tasks and goals collaboratively. Successfully repaired ruptures are associated with better outcomes.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Working alliance: goals, tasks, bond; addressing alliance ruptures' }],
  },
  {
    id: 'nce-s-cor-009',
    reviewNote: 'Confirm the cited Sue & Sue edition discusses Hook et al.\'s cultural humility model.',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: 'A counselor who has completed many multicultural trainings begins work with a Hmong American client. According to Hook and colleagues\' model of cultural humility, which stance BEST reflects cultural humility?',
    options: [
      { id: 'a', text: 'Ask the client what their culture means to them and stay open to being corrected', isCorrect: true, rationale: 'Cultural humility is an other-oriented, curious stance that treats the client as the expert on their own cultural identity.' },
      { id: 'b', text: 'Draw on prior training about Hmong customs to anticipate the client\'s values', isCorrect: false, rationale: 'Applying general group knowledge as a template risks stereotyping; it reflects a knowledge-based, not humble, stance.' },
      { id: 'c', text: 'Set cultural issues aside unless the client raises them first in the session', isCorrect: false, rationale: 'Waiting for the client to raise culture places the burden on the client and can signal that culture is unwelcome.' },
      { id: 'd', text: 'Treat the training already completed as sufficient competence for this client', isCorrect: false, rationale: 'Viewing competence as a finished achievement contradicts the ongoing, lifelong nature of humility.' },
    ],
    rationale: 'Hook et al. (2013) described cultural humility as an interpersonal stance that is other-oriented rather than self-focused, marked by respect, openness, and lack of superiority regarding the client\'s cultural background. It is an ongoing process of self-reflection rather than a fixed body of knowledge, and clients\' perceptions of it are associated with a stronger alliance.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Cultural humility as an other-oriented stance' }],
  },
  {
    id: 'nce-s-cor-010',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'medium',
    stem: 'A counselor notices that she schedules a client who lives in public housing for shorter sessions and assigns fewer homework tasks, assuming the client "won\'t follow through." What is the MOST appropriate next step?',
    options: [
      { id: 'a', text: 'Refer the client to a counselor who has more experience with low-income clients', isCorrect: false, rationale: 'Referral based on the counselor\'s bias, rather than competence limits, abandons the client and avoids the counselor\'s own work.' },
      { id: 'b', text: 'Continue as planned, since shorter sessions may reduce the client\'s burden', isCorrect: false, rationale: 'This rationalizes the bias instead of examining it and keeps treating the client differently.' },
      { id: 'c', text: 'Examine the assumption in supervision and restore an equitable treatment plan', isCorrect: true, rationale: 'Recognizing an implicit bias, exploring it in supervision, and correcting its effect on care reflects counselor self-awareness.' },
      { id: 'd', text: 'Tell the client about the bias so the client can decide whether to continue', isCorrect: false, rationale: 'Disclosing the bias burdens the client with the counselor\'s issue; the counselor should first address it through supervision.' },
    ],
    rationale: 'Counselor self-awareness of attitudes, beliefs, and biases is the first dimension of multicultural competence. Biases about social class can shape clinical decisions without conscious intent. When a counselor notices differential treatment, the ethical response is to examine it, often through supervision or consultation, and correct its effect on services.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counselor awareness of own assumptions, values, and biases' },
      { source: 'ACA Code of Ethics', detail: 'C.5 Nondiscrimination' },
    ],
  },
  {
    id: 'nce-s-cor-011',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'easy',
    stem: 'A counselor notices he feels unusually irritated and impatient with an older male client who reminds him of his own critical father. This reaction is BEST described as',
    options: [
      { id: 'a', text: 'transference by the client', isCorrect: false, rationale: 'Transference is the client\'s projection of past relationships onto the counselor; here the reaction is the counselor\'s.' },
      { id: 'b', text: 'countertransference', isCorrect: true, rationale: 'The counselor\'s emotional reaction to the client, shaped by his own unresolved history, is countertransference.' },
      { id: 'c', text: 'resistance in the client', isCorrect: false, rationale: 'Resistance refers to client behavior that impedes change, not the counselor\'s feelings.' },
      { id: 'd', text: 'compassion fatigue', isCorrect: false, rationale: 'Compassion fatigue is cumulative exhaustion from trauma exposure, not a reaction tied to a specific personal history.' },
    ],
    rationale: 'Countertransference refers to the counselor\'s emotional reactions to a client, particularly those rooted in the counselor\'s own unresolved conflicts or past relationships. It is not inherently harmful, but unexamined countertransference can distort the counselor\'s perceptions and responses, so recognizing it is the first step to managing it.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: transference and countertransference' }],
  },
  {
    id: 'nce-s-cor-012',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: 'A counselor whose sister died by overdose finds herself giving extra session time and her personal cell number to a young adult client in early recovery. What is the BEST course of action?',
    options: [
      { id: 'a', text: 'Keep the extra contact, since it clearly helps the client stay engaged', isCorrect: false, rationale: 'This keeps a boundary crossing driven by the counselor\'s needs rather than the client\'s welfare.' },
      { id: 'b', text: 'Transfer the client right away to avoid any further personal reactions', isCorrect: false, rationale: 'Abrupt transfer is premature; countertransference can often be managed and abrupt referral may harm the client.' },
      { id: 'c', text: 'Disclose the sister\'s death so the client understands her strong concern', isCorrect: false, rationale: 'This self-disclosure serves the counselor\'s needs and burdens the client.' },
      { id: 'd', text: 'Seek supervision on the reaction and restore usual session boundaries', isCorrect: true, rationale: 'Recognizing the countertransference, processing it in supervision, and restoring boundaries protects the client and the work.' },
    ],
    rationale: 'Countertransference can show up as overinvolvement, rescuing, or boundary crossings that meet the counselor\'s needs. Effective management involves self-awareness, supervision or personal counseling, and returning to boundaries that serve the client. Referral is reserved for cases where the counselor cannot remain objective after these steps.',
    references: [
      { source: 'Corey (Theory & Practice)', detail: 'Countertransference and the counselor as a person' },
      { source: 'ACA Code of Ethics', detail: 'A.6.b Extending Conventional Boundaries' },
    ],
  },
  {
    id: 'nce-s-cor-013',
    reviewNote: 'Classical/totalistic/complementary views come from Gelso & Hayes; confirm Corey covers the totalistic view or swap the source.',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'hard',
    stem: 'A supervisor tells a trainee, "Every feeling you have toward a client, not just the conflicts from your own past, can be useful information about the client and the relationship." This statement reflects which view of countertransference?',
    options: [
      { id: 'a', text: 'Classical view, treating it as an obstacle to be eliminated', isCorrect: false, rationale: 'The classical (Freudian) view limits countertransference to the counselor\'s unresolved conflicts and treats it as interference.' },
      { id: 'b', text: 'Behavioral view, treating it as a learned response to extinguish', isCorrect: false, rationale: 'Countertransference is not framed as a conditioned response in behavioral theory; this distractor misattributes the concept.' },
      { id: 'c', text: 'Complementary view, limited to the client\'s projected roles', isCorrect: false, rationale: 'The complementary conception frames countertransference as the counselor\'s reaction to the interpersonal pull of the client\'s style, a narrower idea than all feelings toward the client.' },
      { id: 'd', text: 'Totalistic view, including all counselor reactions to clients', isCorrect: true, rationale: 'The totalistic view defines countertransference as all of the counselor\'s emotional reactions and sees them as potentially useful data.' },
    ],
    rationale: 'The classical view, rooted in Freud, defines countertransference narrowly as the counselor\'s unconscious, conflict-based reactions to the client\'s transference and treats it as an impediment. The totalistic view broadens it to all of the counselor\'s emotional responses and treats them as a source of understanding. Contemporary integrative views keep the focus on conflict-based reactions while stressing that, once understood, they can inform the work.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: countertransference and its therapeutic use' }],
  },
  {
    id: 'nce-s-cor-014',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'medium',
    stem: 'A college student says, "I\'ve been hooking up with different people most weekends, and my roommate thinks I\'m a mess." Which counselor response BEST reflects a nonjudgmental stance?',
    options: [
      { id: 'a', text: 'Your roommate may have a point, so let\'s look at the risks you\'re taking.', isCorrect: false, rationale: 'Siding with the roommate conveys the counselor\'s judgment before understanding the client\'s view.' },
      { id: 'b', text: 'Your roommate sees it one way. I\'m curious how you feel about these weekends.', isCorrect: true, rationale: 'This neither condemns nor endorses the behavior and invites the client\'s own perspective, which is nonjudgmental.' },
      { id: 'c', text: 'There\'s nothing wrong with that at all, and your roommate should not judge you.', isCorrect: false, rationale: 'Approval is also an evaluation; it imposes the counselor\'s values in the opposite direction.' },
      { id: 'd', text: 'What do you think is missing in your life that leads you to keep doing this?', isCorrect: false, rationale: 'This presumes the behavior signals a deficit, a judgment embedded in the question.' },
    ],
    rationale: 'A nonjudgmental stance means the counselor suspends both disapproval and approval and seeks to understand the client\'s experience from the client\'s frame of reference. Counselors avoid imposing their own values on clients, which allows clients to explore their choices without becoming defensive.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-cor-015',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: 'A 70-year-old widower arrives early for his first session and seems nervous. Which counselor behavior BEST conveys warmth and respect?',
    options: [
      { id: 'a', text: 'Greet him by name, ask how he prefers to be addressed, and offer him a seat', isCorrect: true, rationale: 'This shows genuine interest and respects his preferences and dignity, communicating warmth and respect.' },
      { id: 'b', text: 'Call him "sweetie" and speak slowly and loudly so he can follow along easily', isCorrect: false, rationale: 'Endearments and exaggerated speech are elderspeak; they are patronizing and disrespectful.' },
      { id: 'c', text: 'Hand him the intake forms and ask him to wait until his appointment time', isCorrect: false, rationale: 'This is procedural and distant, and it ignores his visible nervousness.' },
      { id: 'd', text: 'Tell him there is no need to be nervous because most clients feel fine later', isCorrect: false, rationale: 'This dismisses his feelings and offers reassurance in place of attunement.' },
    ],
    rationale: 'Warmth is conveyed through friendly, caring verbal and nonverbal behavior, and respect is shown by treating the client as a capable person with preferences and dignity. Asking how a client wishes to be addressed is a simple, culturally responsive way to communicate both, and avoiding ageist communication such as elderspeak is part of respect.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Building a counseling relationship: warmth and respect' }],
  },
  {
    id: 'nce-s-cor-016',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: 'A White counselor working with a Black client hears the client say, "I wasn\'t sure I could talk about racism at work with you." Which counselor response BEST shows awareness of power and privilege in the relationship?',
    options: [
      { id: 'a', text: 'I don\'t really see color, so you can talk to me about anything you need to here.', isCorrect: false, rationale: 'Color-blind statements deny the relevance of race and the client\'s concern, which is a microinvalidation.' },
      { id: 'b', text: 'I\'ve had many Black clients, so I understand a lot about what you face at work.', isCorrect: false, rationale: 'Claiming understanding based on experience with other clients overstates the counselor\'s knowledge and dismisses the concern.' },
      { id: 'c', text: 'As a White counselor I may miss things, and I\'d like to hear it if you\'re willing.', isCorrect: true, rationale: 'This names the racial difference and the limits of the counselor\'s perspective, and invites the client\'s experience without pressure.' },
      { id: 'd', text: 'Let\'s focus on what you can control at work, since we can\'t change the people there.', isCorrect: false, rationale: 'Redirecting away from racism minimizes a systemic experience and avoids the topic the client raised.' },
    ],
    rationale: 'Counselors from privileged groups hold both professional and social power. Broaching racial and cultural differences directly and nondefensively, and acknowledging the limits of one\'s own perspective, signals that the client\'s experiences of oppression are welcome. Color-blind or minimizing responses are common microaggressions that weaken trust.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Power, privilege, and microaggressions in counseling; color-blindness' }],
  },
];
