// tools/nce/seed/core-3.js — Core Counseling Attributes (core), items 033–048.
module.exports = [
  {
    id: 'nce-s-cor-033',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'medium',
    stem: 'A counselor who sincerely holds egalitarian values reviews her recorded sessions for supervision. She notices that with her Latino clients she offers fewer reflections, interrupts more often, and moves to advice sooner than with her White clients. She had not been aware of the difference. This pattern BEST illustrates',
    options: [
      { id: 'a', text: 'implicit bias operating outside her conscious awareness', isCorrect: true, rationale: 'Automatic, unintended differences in behavior toward a group, despite consciously held egalitarian beliefs, are the hallmark of implicit (unconscious) bias.' },
      { id: 'b', text: 'explicit prejudice that she consciously holds but conceals', isCorrect: false, rationale: 'Explicit prejudice is consciously endorsed. The counselor sincerely holds egalitarian values and was unaware of the pattern.' },
      { id: 'c', text: 'cultural encapsulation produced by a narrow training program', isCorrect: false, rationale: 'Wrenn\'s cultural encapsulation describes defining reality through one\'s own cultural lens. It does not specifically explain unaware, group-specific differences in her microskills.' },
      { id: 'd', text: 'countertransference rooted in conflicts from her own family', isCorrect: false, rationale: 'Countertransference stems from the counselor\'s personal history with significant others. Nothing suggests a family conflict; the pattern tracks client ethnicity.' },
    ],
    rationale: 'Implicit bias refers to attitudes and associations that operate automatically and outside awareness, so well-intentioned counselors can treat groups differently without meaning to. Sue and Sue stress that good intentions do not protect against unintentional bias; recorded sessions, supervision and ongoing self-examination are how counselors detect it.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Implicit bias and unintentional racism in well-intentioned helping professionals' }],
  },
  {
    id: 'nce-s-cor-034',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'medium',
    stem: 'A 47-year-old client in a larger body seeks counseling for grief after his mother\'s death. He has not raised any concern about his weight. Over three sessions, the counselor finds herself suggesting exercise plans and asking about his eating. Which action BEST reflects counselor self-awareness?',
    options: [
      { id: 'a', text: 'Add a weight-loss goal to the plan, since weight affects mood and grief', isCorrect: false, rationale: 'This imposes the counselor\'s agenda on a client who came for grief and acts on the bias rather than examining it.' },
      { id: 'b', text: 'Notice her assumptions about his weight and refocus on the grief he brought', isCorrect: true, rationale: 'Recognizing the counselor-driven assumption and returning to the client\'s own goal is self-aware, client-centered practice consistent with ACA A.4.b.' },
      { id: 'c', text: 'Refer him to a dietitian so his eating habits can be addressed by an expert', isCorrect: false, rationale: 'A referral the client did not request still acts on the counselor\'s assumption about his body rather than on his presenting concern.' },
      { id: 'd', text: 'Ask him directly whether his weight played a part in his mother\'s death', isCorrect: false, rationale: 'This question extends the counselor\'s weight focus into his grief and may shame him; it reflects the bias rather than awareness of it.' },
    ],
    rationale: 'Self-awareness means noticing when personal values or assumptions, including those about body size, are steering the work. ACA Standard A.4.b directs counselors to avoid imposing their own values and to respect the client\'s goals. The counselor should examine where the weight focus came from and return to the grief the client brought.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' },
      { source: 'Corey (Theory & Practice)', detail: 'The counselor as a person: self-awareness and personal values' },
    ],
  },
  {
    id: 'nce-s-cor-035',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'hard',
    stem: 'The week after a national election, a client spends several minutes praising a candidate the counselor strongly opposes. The counselor notices her jaw tightening. The client then asks, "You agree with me, right?" Which counselor response BEST reflects self-aware, ethical practice?',
    options: [
      { id: 'a', text: 'Honestly, I see it differently, but I respect your right to your own view.', isCorrect: false, rationale: 'Sharing political disagreement shifts focus to the counselor and risks imposing values; congruence does not require disclosing every opinion.' },
      { id: 'b', text: 'I do. A lot of people feel that way, so I can see why you are hopeful now.', isCorrect: false, rationale: 'Feigning agreement is incongruent and also brings the counselor\'s supposed politics into the session.' },
      { id: 'c', text: 'I keep my politics out of here, but I want to hear what this means for you.', isCorrect: true, rationale: 'This gently declines to disclose, keeps the focus on the client, and invites exploration, which manages the counselor\'s reaction without acting on it.' },
      { id: 'd', text: 'Since we differ on this, another counselor might be a better fit for you.', isCorrect: false, rationale: 'ACA A.11.b cautions against referral based solely on the counselor\'s personal values; a political difference is not grounds for referral.' },
    ],
    rationale: 'Counselors are expected to notice their own value reactions, including political ones, and keep them from steering the session (ACA A.4.b). Self-disclosure of opinions should serve the client, and a politically charged question is usually best met by declining warmly and exploring its meaning for the client. Referral solely because of a values difference is discouraged under A.11.b.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' },
      { source: 'ACA Code of Ethics', detail: 'A.11.b Values Within Termination and Referral' },
    ],
  },
  {
    id: 'nce-s-cor-036',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: 'At a community mental health center, a 36-year-old client referred by his caseworker glares at the counselor and says, "You\'re just another paid stranger. You don\'t actually care what happens to me." Which counselor response BEST conveys warmth and respect?',
    options: [
      { id: 'a', text: 'I have years of training, so you can trust that I know how to help you.', isCorrect: false, rationale: 'Defending credentials centers the counselor and argues with the client\'s experience rather than respecting it.' },
      { id: 'b', text: 'I can\'t work with you if you speak to me in that tone during sessions.', isCorrect: false, rationale: 'The client is distrustful, not abusive. An early limit on tone reads as punitive and confirms his expectation that no one cares.' },
      { id: 'c', text: 'Let\'s set that aside and get through the intake questions for today.', isCorrect: false, rationale: 'Ignoring the statement dismisses the client\'s concern and treats him as paperwork, the opposite of respect.' },
      { id: 'd', text: 'Sounds like people haven\'t earned your trust. I\'d like to, at your pace.', isCorrect: true, rationale: 'This reflects the meaning behind the hostility without defensiveness and communicates a respectful wish to earn trust over time.' },
    ],
    rationale: 'Warmth and respect are tested most when a client is hostile. A nondefensive response that reflects the client\'s distrust, treats it as understandable, and leaves the client in control of the pace communicates care. Defending oneself, setting premature limits, or ignoring the comment tend to confirm the client\'s expectations.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Warmth, respect and working with reluctant or resistant clients' }],
  },
  {
    id: 'nce-s-cor-037',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'warmth and respect',
    difficulty: 'medium',
    stem: 'A 60-year-old Vietnamese immigrant father comes to counseling about conflict with his teenage son. In the first session he says, "You are the expert. Please tell me what I should do." Which counselor approach BEST combines respect with responsiveness to his request?',
    options: [
      { id: 'a', text: 'Offer some concrete suggestions and structure, checking how each idea fits his family', isCorrect: true, rationale: 'Honoring his expectation of an active, expert helper while asking how ideas fit his family respects both his cultural frame and his autonomy.' },
      { id: 'b', text: 'Explain that counselors do not give advice and that he must find his own answers', isCorrect: false, rationale: 'A strictly nondirective stance may be experienced as unhelpful or as a lack of competence, and it dismisses his stated preference.' },
      { id: 'c', text: 'Tell him exactly what rules to set for his son, since he asked for clear direction', isCorrect: false, rationale: 'Directing without his input ignores his knowledge of his own family and values; structure should still be collaborative.' },
      { id: 'd', text: 'Ask him to first explore his deeper feelings about his son before any guidance', isCorrect: false, rationale: 'Insisting on emotional exploration before addressing his practical request disregards what he came for and may lead to early dropout.' },
    ],
    rationale: 'Sue and Sue note that many clients, especially those from cultures that value hierarchy and practical help, expect the counselor to take an active, directive role, and that a purely nondirective style can lead to early termination. Respect means meeting the client\'s expectations with structure and concrete input while still checking that suggestions fit the client\'s values.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Culturally appropriate helping styles: directive versus nondirective approaches' }],
  },
  {
    id: 'nce-s-cor-038',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: 'A 38-year-old Army veteran referred for military sexual trauma tells the counselor in her second session, "I\'m not ready to talk about what happened. I don\'t know if I ever will be." Which counselor response BEST respects the client\'s pace?',
    options: [
      { id: 'a', text: 'Avoiding it keeps symptoms going, so let\'s try to cover the details today.', isCorrect: false, rationale: 'Pressing for details before the client consents overrides her choice and can feel retraumatizing.' },
      { id: 'b', text: 'That\'s okay. You decide what we talk about and when, and we can go slowly.', isCorrect: true, rationale: 'This affirms her control over disclosure, a core trauma-informed principle, and conveys respect for her readiness.' },
      { id: 'c', text: 'Could you give me just a short outline so I know what we\'re working with?', isCorrect: false, rationale: 'Asking for an outline right after she declines still pressures disclosure and disregards her stated limit.' },
      { id: 'd', text: 'Unless you talk about it, I\'m not sure that counseling can help you much.', isCorrect: false, rationale: 'Making help conditional on disclosure is coercive and undermines safety and trust.' },
    ],
    rationale: 'Respecting a client\'s pace is especially important with trauma survivors. SAMHSA\'s trauma-informed principles emphasize safety, trustworthiness, and client voice and choice; counselors let clients control when and how much they disclose, building stabilization and trust first.',
    references: [{ source: 'SAMHSA TIP 57', detail: 'Trauma-informed principles: safety, choice and client control over disclosure' }],
  },
  {
    id: 'nce-s-cor-039',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'medium',
    stem: 'A 26-year-old client in outpatient treatment for opioid use returns after relapsing following 90 days of abstinence. He looks down and says, "You must be so disappointed in me." Which counselor response BEST demonstrates unconditional positive regard?',
    options: [
      { id: 'a', text: 'I\'m a bit disappointed, but I know you can do better than this next time.', isCorrect: false, rationale: 'This makes the counselor\'s regard contingent on his behavior, which is the opposite of unconditional positive regard.' },
      { id: 'b', text: 'Relapse is just part of recovery, so it\'s really not a big deal at all.', isCorrect: false, rationale: 'This minimizes a serious event and offers reassurance rather than acceptance of the person and his feelings.' },
      { id: 'c', text: 'My regard for you hasn\'t changed. I\'m glad you came back to talk about it.', isCorrect: true, rationale: 'This separates his worth from the relapse and welcomes him back, communicating acceptance that does not depend on his behavior.' },
      { id: 'd', text: 'Let\'s go over what you did wrong so this does not happen to you again.', isCorrect: false, rationale: 'Opening with what he did wrong frames the session around judgment; relapse review can come later from a stance of acceptance.' },
    ],
    rationale: 'Unconditional positive regard is acceptance of the client as a person, not approval of every behavior, and it does not rise and fall with the client\'s performance. After a relapse, communicating steady regard reduces shame and makes honest exploration of what happened more likely.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance' }],
  },
  {
    id: 'nce-s-cor-040',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'easy',
    stem: 'According to Carl Rogers, incongruence between a person\'s self-concept and actual experience develops primarily when the person',
    options: [
      { id: 'a', text: 'fails to resolve unconscious conflicts between the id and superego', isCorrect: false, rationale: 'This is a psychoanalytic explanation of conflict, not Rogers\'s account of incongruence.' },
      { id: 'b', text: 'learns maladaptive behavior patterns through repeated reinforcement', isCorrect: false, rationale: 'This is a behavioral explanation; Rogers focused on the self-concept and conditions of worth.' },
      { id: 'c', text: 'holds irrational beliefs that they must win approval from others', isCorrect: false, rationale: 'Irrational beliefs about needing approval belong to Ellis\'s REBT, not person-centered theory.' },
      { id: 'd', text: 'internalizes conditions of worth set by significant others', isCorrect: true, rationale: 'Rogers held that conditional regard from significant others leads people to internalize conditions of worth, which produces incongruence.' },
    ],
    rationale: 'Rogers proposed that when love and approval are conditional, people internalize conditions of worth and deny or distort experiences that do not fit them, creating incongruence. Unconditional positive regard in counseling counters this by allowing clients to accept all of their experience without losing the counselor\'s regard.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: conditions of worth and incongruence' }],
  },
  {
    id: 'nce-s-cor-041',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'easy',
    stem: 'In person-centered theory, a counselor who is congruent is one who',
    options: [
      { id: 'a', text: 'shares every thought and feeling with the client as soon as it arises', isCorrect: false, rationale: 'Congruence does not mean impulsively disclosing all reactions; expression should be appropriate and in the client\'s service.' },
      { id: 'b', text: 'is aware of inner experience and expresses it authentically when fitting', isCorrect: true, rationale: 'Congruence is the match between the counselor\'s inner experience, awareness of it, and outward expression, without a professional facade.' },
      { id: 'c', text: 'hides personal reactions to maintain a neutral and professional stance', isCorrect: false, rationale: 'Hiding behind a professional facade is the opposite of congruence in Rogers\'s view.' },
      { id: 'd', text: 'mirrors the client\'s emotional tone and posture to build rapport fast', isCorrect: false, rationale: 'Mirroring is a rapport technique; it can be done without any genuineness at all.' },
    ],
    rationale: 'Rogers described congruence, or genuineness, as the counselor being real: inner experience, awareness and communication are consistent, with no facade. Corey notes that this does not mean impulsively sharing every feeling; genuine expression is appropriate and serves the relationship.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence or genuineness' }],
  },
  {
    id: 'nce-s-cor-042',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'hard',
    stem: 'A 31-year-old client who says coworkers avoid her asks, "Be honest. Do you find me annoying? Everyone else does." In their sessions, the counselor has felt irritated when the client cuts her off mid-sentence. Which response BEST demonstrates congruence in the client\'s service?',
    options: [
      { id: 'a', text: 'Not at all. I truly enjoy every single minute of our time together in here.', isCorrect: false, rationale: 'This reassurance contradicts the counselor\'s actual experience, so it is incongruent and withholds useful feedback.' },
      { id: 'b', text: 'Honestly, yes. You can be pretty exhausting for most people to be around.', isCorrect: false, rationale: 'This is a global, hurtful judgment rather than a specific, caring observation; genuineness is not the same as bluntness.' },
      { id: 'c', text: 'At times I feel cut off when you jump in. I wonder if others feel that too.', isCorrect: true, rationale: 'This honestly shares a specific, behavior-based reaction in the here and now and links it to the client\'s concern, which is genuine and therapeutic.' },
      { id: 'd', text: 'What makes you want to ask me that question at this point in our work?', isCorrect: false, rationale: 'Exploring the question can be useful, but used here it sidesteps a direct, sincere request for honest feedback.' },
    ],
    rationale: 'Congruence means the counselor\'s responses match inner experience, but it is expressed with care and for the client\'s benefit. Sharing a specific, behavioral reaction in the moment (immediacy) gives the client accurate interpersonal feedback she may not get elsewhere. False reassurance is incongruent, and blunt global judgments are not genuineness but a failure of respect.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence; appropriate expression of counselor reactions' }],
  },
  {
    id: 'nce-s-cor-043',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'medium',
    stem: 'A clinic director wants an early indicator of which clients are likely to benefit from counseling, regardless of the counselor\'s theoretical approach. Based on psychotherapy outcome research, which measure is the MOST useful early predictor?',
    options: [
      { id: 'a', text: 'The specific theoretical orientation the counselor practices', isCorrect: false, rationale: 'Comparative outcome research finds that bona fide approaches produce broadly similar outcomes, so orientation is a weak predictor.' },
      { id: 'b', text: 'A demographic match between the counselor and the client', isCorrect: false, rationale: 'Demographic matching has shown inconsistent, generally small effects on outcome compared with the alliance.' },
      { id: 'c', text: 'The total length of the initial intake assessment session', isCorrect: false, rationale: 'Intake length is not an established predictor of counseling outcome.' },
      { id: 'd', text: 'The client\'s rating of the working alliance in early sessions', isCorrect: true, rationale: 'Meta-analyses find that the alliance, especially as rated by the client early in treatment, predicts outcome across approaches.' },
    ],
    rationale: 'The working alliance is one of the most consistently replicated predictors of counseling outcome. Meta-analyses (e.g., Horvath and colleagues; Flückiger and colleagues) show a moderate, reliable relationship between alliance and outcome across theoretical approaches, and alliance ratings taken early in treatment, often by the third to fifth session, already predict results.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'The working alliance and common factors in counseling outcome' }],
    reviewNote: 'Alliance-outcome meta-analytic findings (Horvath et al., 2011; Flückiger et al., 2018) are not themselves in the source library; SME should confirm the Gladding locator covers early alliance as an outcome predictor.',
  },
  {
    id: 'nce-s-cor-044',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: 'In the third session of couples counseling, Dana interrupts her wife and says to the counselor, "Every time she talks, you nod along. You\'re clearly on her side." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Acknowledge Dana\'s experience, invite her to say more, and check in with both partners', isCorrect: true, rationale: 'Taking the perceived split seriously and exploring it openly with both partners repairs the alliance with Dana without abandoning her wife.' },
      { id: 'b', text: 'Reassure Dana that counselors stay neutral, then return to where the session left off', isCorrect: false, rationale: 'Reassurance without exploration dismisses Dana\'s experience and leaves the split alliance unrepaired.' },
      { id: 'c', text: 'Explain to Dana that her wife\'s points have simply been clearer and more specific', isCorrect: false, rationale: 'This confirms Dana\'s perception that the counselor is siding with her wife and deepens the split.' },
      { id: 'd', text: 'Schedule separate sessions with Dana alone to rebuild her trust before joint work', isCorrect: false, rationale: 'Moving to private sessions before addressing the issue together can create new imbalances and secrets and delays repair in the room.' },
    ],
    rationale: 'In couple and family counseling the counselor holds an alliance with each member, and a split alliance, where one member feels less allied with the counselor, is linked to poorer engagement and dropout. The counselor should address the rupture openly and nondefensively in session, maintaining balanced (multipartial) alliances with all members.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Therapeutic alliance in couple and family therapy; balanced alliances with each member' }],
    reviewNote: 'Split-alliance research (Pinsof; Friedlander and colleagues, SOFTA) is not itself in the source library; SME should confirm the Goldenberg locator.',
  },
  {
    id: 'nce-s-cor-045',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: 'A 50-year-old Diné (Navajo) client being seen for anxiety mentions that her family is arranging a ceremony with a traditional healer next month. Which counselor response BEST reflects cultural humility?',
    options: [
      { id: 'a', text: 'Suggest she wait on the ceremony until counseling has had a chance to work', isCorrect: false, rationale: 'This ranks the counselor\'s approach above the client\'s healing tradition and imposes the counselor\'s worldview.' },
      { id: 'b', text: 'Describe what she has read about Navajo ceremonies to show her knowledge', isCorrect: false, rationale: 'Taking an expert stance on the client\'s culture is the opposite of humility and may be inaccurate for this client and family.' },
      { id: 'c', text: 'Ask what the ceremony means to her and how she wants it to fit with counseling', isCorrect: true, rationale: 'This positions the client as the expert on her culture and invites collaboration between traditional and counseling approaches.' },
      { id: 'd', text: 'Note it as possible magical thinking to explore further in the assessment', isCorrect: false, rationale: 'Pathologizing a culturally normative healing practice reflects cultural bias, not humility.' },
    ],
    rationale: 'Cultural humility is an other-oriented, lifelong stance of self-reflection in which the counselor treats the client as the expert on her own culture and attends to power differences. Sue and Sue encourage counselors to respect and, where the client wishes, collaborate with Indigenous healing practices rather than dismiss or pathologize them.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling Indigenous clients; respecting traditional and Indigenous healing' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship: client worldview and cultural healing practices' },
    ],
  },
  {
    id: 'nce-s-cor-046',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'easy',
    stem: 'A 19-year-old says, "I dropped out of college to stream video games full time. My parents keep calling me lazy." Which counselor response BEST reflects a nonjudgmental stance?',
    options: [
      { id: 'a', text: 'Dropping out this young could really limit your options later in life.', isCorrect: false, rationale: 'This evaluates the decision as a mistake and aligns the counselor with a negative judgment.' },
      { id: 'b', text: 'Your parents may have a point, since streaming is a hard way to earn money.', isCorrect: false, rationale: 'Siding with the parents judges the client\'s choice and is likely to harm trust.' },
      { id: 'c', text: 'Good for you. Following your passion is the right call at your age, I think.', isCorrect: false, rationale: 'Approval is also a judgment; a nonjudgmental stance neither condemns nor endorses the choice.' },
      { id: 'd', text: 'That\'s a big change. What drew you to streaming, and how is it going so far?', isCorrect: true, rationale: 'This acknowledges the change and invites the client\'s own perspective with curiosity, neither praising nor criticizing.' },
    ],
    rationale: 'A nonjudgmental stance means suspending evaluation of the client\'s choices, positive or negative, so the client can explore them openly. Curious, open-ended responses keep the focus on the client\'s experience; both criticism and praise place the counselor\'s values at the center.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-cor-047',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: 'A client who works two hourly jobs has missed two sessions after short-notice shift changes. She apologizes repeatedly and seems afraid of being dropped. The agency discharges clients after three missed sessions. Which counselor response BEST reflects awareness of power and privilege?',
    options: [
      { id: 'a', text: 'Name the shift-work barrier and explore flexible times or telehealth together', isCorrect: true, rationale: 'This recognizes a structural barrier rather than blaming the client and uses the counselor\'s power to adapt services with her.' },
      { id: 'b', text: 'Remind her of the attendance policy and that one more absence ends services', isCorrect: false, rationale: 'Leading with the policy uses institutional power punitively and ignores the economic constraints driving the absences.' },
      { id: 'c', text: 'Interpret the missed sessions as ambivalence about change to explore in session', isCorrect: false, rationale: 'Framing a work-schedule barrier as resistance pathologizes the client and overlooks her circumstances.' },
      { id: 'd', text: 'Suggest she ask her manager for a fixed schedule so she can attend reliably', isCorrect: false, rationale: 'This assumes a level of workplace control that hourly workers often lack, reflecting the counselor\'s own privileged frame.' },
    ],
    rationale: 'The MSJCC ask counselors to recognize how privileged and marginalized statuses, including socioeconomic status, shape the counseling relationship and access to services. Counselors hold institutional power and can use it to reduce barriers rather than interpret structural constraints as client resistance.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship; privileged and marginalized statuses and institutional barriers' }],
  },
  {
    id: 'nce-s-cor-048',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: 'A counselor working with a 68-year-old recently widowed man, with his permission, has begun calling his bank, drafting his letters, and booking his appointments. She thinks warmly, "He would be lost without me." Which risk does this pattern MOST directly create?',
    options: [
      { id: 'a', text: 'Turning the client\'s gratitude into hostile negative transference', isCorrect: false, rationale: 'Nothing in the scenario points to hostility; the more direct risk lies in what the client stops doing for himself.' },
      { id: 'b', text: 'Fostering dependence that undermines the client\'s own competence', isCorrect: true, rationale: 'Rescuing driven by the counselor\'s need to be needed takes over tasks the client could learn to do, encouraging dependence and eroding self-efficacy.' },
      { id: 'c', text: 'Making termination easier because the alliance is so strong', isCorrect: false, rationale: 'Dependence typically makes termination harder, not easier.' },
      { id: 'd', text: 'Causing the counselor to grow emotionally detached from him', isCorrect: false, rationale: 'The pattern reflects overinvolvement, not detachment.' },
    ],
    rationale: 'Countertransference can be positive as well as negative. Corey describes the counselor\'s need to be needed and rescuing as countertransference that leads counselors to do for clients what clients can do for themselves. The result is dependence and reduced client self-efficacy, which supervision can help the counselor recognize.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Countertransference: the need to be needed and rescuing clients' }],
  },
];
