// tools/nce/seed/core-4.js — Core Counseling Attributes (core), items 049–064.
module.exports = [
  {
    id: 'nce-s-cor-049',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: `A counselor tells a 45-year-old Mexican American client, "It must help to have your big family around you right now." The client replies, "Actually, my family is part of the stress. My friends from work are who I lean on." Which counselor response BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Families can be complicated, but they usually come through in a real crisis.`, isCorrect: false, rationale: `This holds on to the counselor's assumption about family support and quietly dismisses the client's correction.` },
      { id: 'b', text: `I'm sorry to hear that. Maybe we can work on repairing things with them.`, isCorrect: false, rationale: `This sets a family-repair goal the client did not ask for and still treats family closeness as the expected norm.` },
      { id: 'c', text: `Thank you for correcting me; I assumed. Tell me about who supports you.`, isCorrect: true, rationale: `The counselor owns the assumption without defensiveness, thanks the client, and lets the client define her own support system.` },
      { id: 'd', text: `That surprises me, since family is so central in Mexican American culture.`, isCorrect: false, rationale: `This applies a group generalization over the individual's own account, which is stereotyping rather than humility.` },
    ],
    rationale: `Cultural humility treats the client as the expert on how culture shows up in her life. When a client corrects an assumption, the humble response is to accept the correction openly, acknowledge the error, and get curious about the client's actual experience. Group-level knowledge can inform hypotheses but cannot override what an individual client says about herself.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Within-group differences; avoiding stereotyping in culturally responsive practice' }],
  },
  {
    id: 'nce-s-cor-050',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'hard',
    stem: `A Filipina American counselor begins working with a 58-year-old White, heterosexual, Christian man who owns a hardware store in a small farming town and is struggling after his business partner died. The counselor thinks, "His culture is the mainstream one, so there isn't much cultural material to explore." Which stance BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Explore how his faith, rural roots, class and ideas of manhood shape his grief`, isCorrect: true, rationale: `Everyone has a culture. Inviting him to describe how faith, place, class and gender norms shape his loss applies humility to a client from dominant groups.` },
      { id: 'b', text: `Focus on grief alone, because culture matters mainly for marginalized clients`, isCorrect: false, rationale: `This treats dominant-group identity as culture-free, the very assumption the counselor should be questioning.` },
      { id: 'c', text: `Rely on her knowledge of small-town life to anticipate his values and beliefs`, isCorrect: false, rationale: `Presuming to know his values from group knowledge is the opposite of the other-oriented, open stance humility requires.` },
      { id: 'd', text: `Begin by discussing her own ethnic identity so he sees what culture involves`, isCorrect: false, rationale: `Centering the counselor's identity at the outset shifts focus away from the client and does not explore his worldview.` },
    ],
    rationale: `Cultural humility is not reserved for clients from marginalized groups. Members of dominant groups also hold cultural identities, such as religion, regional and rural culture, social class and gender-role norms, that shape how they experience distress and help-seeking. Treating the majority culture as a neutral default is a form of cultural encapsulation; a humble counselor stays curious about every client's worldview.`,
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Everyone has a culture; Whiteness as an invisible default and cultural encapsulation' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Client worldview: privileged and marginalized client identities' },
    ],
  },
  {
    id: 'nce-s-cor-051',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'easy',
    stem: `Which description BEST captures cultural humility as distinct from cultural competence?`,
    options: [
      { id: 'a', text: `A body of knowledge about specific groups that a counselor masters in training`, isCorrect: false, rationale: `Mastering group-specific knowledge is closer to the knowledge component of cultural competence, not humility.` },
      { id: 'b', text: `A credential earned after completing a set number of multicultural CE hours`, isCorrect: false, rationale: `Humility is an ongoing stance, not an endpoint that can be certified by hours of training.` },
      { id: 'c', text: `A technique of matching clients with counselors who share their background`, isCorrect: false, rationale: `Matching may help some clients, but it is a service-delivery choice, not the counselor's own stance of humility.` },
      { id: 'd', text: `A lifelong process of self-reflection, openness, and attention to power`, isCorrect: true, rationale: `Cultural humility is defined as an ongoing commitment to self-reflection and self-critique, openness to the client's view, and redressing power imbalances.` },
    ],
    rationale: `Cultural humility, a term introduced by Tervalon and Murray-Garcia, emphasizes lifelong self-evaluation and critique, an other-oriented openness to the client's cultural identity, and attention to power imbalances. It complements competence: rather than an endpoint of mastery, it is a continuing way of being with clients that keeps the counselor learning.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Cultural humility versus cultural competence; lifelong self-reflection' }],
    reviewNote: `Tervalon & Murray-Garcia (1998) originated the term; confirm the cited Sue & Sue edition discusses cultural humility in these terms.`,
  },
  {
    id: 'nce-s-cor-052',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'medium',
    stem: `A 44-year-old man says, "I've been seeing someone else for six months. My wife has no idea. You probably think I'm a terrible person now." Which counselor response BEST reflects a nonjudgmental stance?`,
    options: [
      { id: 'a', text: `I don't think that, but you'll need to tell your wife before we can go on.`, isCorrect: false, rationale: `Making disclosure a condition of counseling imposes the counselor's values and sets an agenda the client has not chosen.` },
      { id: 'b', text: `You expected me to judge you. I'd like to understand what's happening for you.`, isCorrect: true, rationale: `This reflects his fear of judgment and conveys acceptance and curiosity without endorsing or condemning the affair.` },
      { id: 'c', text: `Affairs are very common, so you really shouldn't feel bad about this at all.`, isCorrect: false, rationale: `Normalizing and reassuring takes a stance on the behavior and dismisses whatever guilt or conflict he may feel.` },
      { id: 'd', text: `How do you think your wife would feel if she found out about all of this?`, isCorrect: false, rationale: `Though phrased as a question, it implies moral evaluation and shifts focus from his experience to an imagined accusation.` },
    ],
    rationale: `A nonjudgmental stance means suspending moral evaluation so the client can explore his experience openly. It neither condemns nor approves the behavior. ACA Standard A.4.b asks counselors to avoid imposing their own values; responding to the client's fear of judgment and inviting exploration keeps the focus on his goals.`,
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-cor-053',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'medium',
    stem: `A 62-year-old client laid off from a factory job says, "Immigrants took all the jobs around here. People like that are ruining this country." The counselor, herself the daughter of immigrants, feels a flash of anger. Which response BEST reflects a nonjudgmental stance while staying ethical?`,
    options: [
      { id: 'a', text: `Losing that job hit hard. Tell me what these months have been like for you.`, isCorrect: true, rationale: `This attends to the loss and fear beneath the statement, neither endorsing nor attacking his view, and keeps the focus on his experience.` },
      { id: 'b', text: `I need to tell you that my own parents were immigrants, and that remark hurt.`, isCorrect: false, rationale: `Disclosing her hurt at this point centers the counselor's reaction and is likely to rupture the relationship before it forms.` },
      { id: 'c', text: `The research shows immigrants don't really take jobs away from local workers.`, isCorrect: false, rationale: `Debating the facts turns the session into an argument and signals judgment rather than understanding.` },
      { id: 'd', text: `It sounds like you're right that outsiders are causing a lot of your problems.`, isCorrect: false, rationale: `Agreeing with the generalization abandons neutrality and reinforces a blaming belief rather than exploring it.` },
    ],
    rationale: `Nonjudgmental does not mean agreeing. The counselor sets aside her reaction in the moment, monitors it, and responds to the client's underlying experience of loss. Consistent with ACA A.4.b, she avoids imposing her values; she can process her own anger in supervision and later explore how his beliefs affect his goals.`,
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' },
      { source: 'Corey (Theory & Practice)', detail: 'The counselor as a person: personal values and dealing with difficult client views' },
    ],
  },
  {
    id: 'nce-s-cor-054',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'easy',
    stem: `A 67-year-old woman meeting by telehealth after eight months of sobriety says, "I drank at my granddaughter's wedding. I blew everything. I'm back at zero." Which counselor response BEST reflects a nonjudgmental stance?`,
    options: [
      { id: 'a', text: `A wedding was a risky place to be. Why didn't you use your coping plan there?`, isCorrect: false, rationale: `The "why didn't you" question carries blame and is likely to deepen her shame.` },
      { id: 'b', text: `Well, eight months is good, but you'll need to start counting from day one.`, isCorrect: false, rationale: `This confirms her all-or-nothing view of the lapse and minimizes the progress she has made.` },
      { id: 'c', text: `You're being hard on yourself. Let's look at what led up to it, together.`, isCorrect: true, rationale: `This acknowledges her self-criticism without blame and invites shared, curious review of the lapse as something to learn from.` },
      { id: 'd', text: `I'm a little disappointed, but I know you can get back on track this week.`, isCorrect: false, rationale: `Voicing disappointment adds the counselor's evaluation to her shame, even with encouragement attached.` },
    ],
    rationale: `A nonjudgmental response to a lapse counters the abstinence violation effect, the guilt and "I've blown it" thinking that can turn a single lapse into a full relapse. Treating the lapse as information about high-risk situations, rather than as moral failure, keeps the client engaged and supports recovery.`,
    references: [{ source: 'Marlatt & Donovan (Relapse Prevention)', detail: 'Abstinence violation effect; lapse versus relapse' }],
  },
  {
    id: 'nce-s-cor-055',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: `A middle school counselor receives a 13-year-old sent by the assistant principal after a hallway fight. The student slumps in the chair and says, "Just write me up already. You all work for the office." Which counselor response BEST reflects awareness of power in this setting?`,
    options: [
      { id: 'a', text: `Remind the student that cooperating now will help keep the consequences lighter`, isCorrect: false, rationale: `Using discipline as leverage confirms that the counselor is an arm of the office and uses institutional power coercively.` },
      { id: 'b', text: `Wait silently until the student is ready to explain what happened in the fight`, isCorrect: false, rationale: `Silence without explanation leaves the student's assumption about the counselor's role unaddressed.` },
      { id: 'c', text: `Tell the student that everything said here will stay strictly between the two of them`, isCorrect: false, rationale: `Promising absolute confidentiality is inaccurate in a school setting and could later break trust.` },
      { id: 'd', text: `Explain her role apart from discipline, what she would share, and offer choices`, isCorrect: true, rationale: `Clarifying her role and the limits of confidentiality, and giving the student some control, directly addresses the power imbalance the student names.` },
    ],
    rationale: `In schools, courts and other mandated settings, clients often see counselors as agents of the institution. Naming the counselor's role honestly, explaining what will and will not be shared, and offering real choices reduces the power differential and builds trust. Overpromising confidentiality or leveraging consequences each misuse the counselor's position.`,
    references: [
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship: power, privilege and oppression influencing the relationship' },
      { source: 'ACA Code of Ethics', detail: 'B.1.d Explanation of Limitations' },
    ],
  },
  {
    id: 'nce-s-cor-056',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'hard',
    stem: `A 55-year-old Haitian Creole-speaking woman comes to an intake for depression with her adult son, who offers to interpret. As the session goes on, he answers some questions without asking her and gives brief summaries of her longer replies. What is the BEST course of action?`,
    options: [
      { id: 'a', text: `Continue with the son, since he knows her history and she seems comfortable`, isCorrect: false, rationale: `Comfort does not offset the filtering already happening; her voice and privacy are being shaped by a family member.` },
      { id: 'b', text: `Arrange a trained interpreter, explaining it protects her privacy and voice`, isCorrect: true, rationale: `A trained interpreter renders her words fully and neutrally, restoring her voice and confidentiality that family interpreting compromises.` },
      { id: 'c', text: `Ask the son to translate word for word and to stop adding his own answers`, isCorrect: false, rationale: `Instructions do not remove the family role, power dynamics, or limits on what she can disclose in front of her son.` },
      { id: 'd', text: `Rely on her limited English so that no third party needs to be in the room`, isCorrect: false, rationale: `Forcing her to use a language she does not command well silences emotional content and deepens the power imbalance.` },
    ],
    rationale: `Language carries power: a client who cannot speak for herself in her own language loses control over her story. Family interpreters, however willing, may filter, edit or answer for the client, and their presence limits disclosure of sensitive material. Using a trained professional interpreter is the standard of practice that protects accuracy, confidentiality and the client's voice.`,
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Language barriers; problems with using family members as interpreters' },
      { source: 'ACA Code of Ethics', detail: 'A.2.c Developmental and Cultural Sensitivity' },
    ],
  },
  {
    id: 'nce-s-cor-057',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: `A 50-year-old Black man who was once hospitalized involuntarily says at intake, "You've got all those letters after your name. The last one decided what was wrong with me and never asked me a thing." Which counselor response BEST addresses the power differential?`,
    options: [
      { id: 'a', text: `My training is extensive, so you can trust that I'll get the diagnosis right.`, isCorrect: false, rationale: `Leaning on credentials reasserts the expert power the client distrusts and dismisses his past experience.` },
      { id: 'b', text: `That provider was probably following protocol, so try not to take it personally.`, isCorrect: false, rationale: `Defending the system invalidates his experience and aligns the counselor with the institution he distrusts.` },
      { id: 'c', text: `Let's not focus on the past; what matters is the work we're going to do now.`, isCorrect: false, rationale: `Redirecting away from his experience avoids the trust issue he has raised and quietly silences it.` },
      { id: 'd', text: `That sounds like it left you unheard. You know your life best; let's work together.`, isCorrect: true, rationale: `This validates his experience, names him as the expert on his life, and invites a collaborative relationship that shares power.` },
    ],
    rationale: `Credentials give counselors real institutional power, including the power to diagnose and document. Clients with histories of coercive or dismissive care, often compounded by systemic racism, may reasonably distrust that power. Acknowledging the experience and positioning the client as a collaborator and the expert on his own life helps balance the relationship.`,
    references: [
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship: counselor and client privileged and marginalized statuses' },
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Cultural mistrust and the credibility of the helping professional' },
    ],
  },
  {
    id: 'nce-s-cor-058',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'medium',
    stem: `A 78-year-old man tells his 27-year-old counselor, "You're young enough to be my granddaughter. What could you know about burying a wife of 55 years?" Which counselor response BEST conveys empathy?`,
    options: [
      { id: 'a', text: `Age doesn't matter much here; I've been trained to work with grief at any age.`, isCorrect: false, rationale: `Citing training defends the counselor and sidesteps the doubt and loss the client is expressing.` },
      { id: 'b', text: `You're right, I haven't lived that. I want to understand what losing her is like.`, isCorrect: true, rationale: `This honestly acknowledges the generational gap and communicates a sincere wish to enter his world of loss.` },
      { id: 'c', text: `I lost my grandmother last year, so I do know a little of what you're feeling.`, isCorrect: false, rationale: `This self-disclosure equates different losses and shifts the focus to the counselor's experience.` },
      { id: 'd', text: `Would you feel more comfortable seeing a counselor who's closer to your age?`, isCorrect: false, rationale: `Offering a transfer at the first sign of doubt avoids the relationship rather than responding to his feelings.` },
    ],
    rationale: `Empathy does not require shared experience; it requires trying to understand the client's world from his frame of reference. With a client of a different generation, the counselor can honestly acknowledge the difference and convey genuine interest in learning his experience, which often strengthens credibility more than defending one's qualifications.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: accurate empathic understanding of the client\'s frame of reference' }],
  },
  {
    id: 'nce-s-cor-059',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'hard',
    stem: `A counselor at a refugee resettlement agency tells her supervisor that she cries alongside clients as they describe their losses, then feels drained and has trouble thinking clearly in session. The supervisor suggests she shift the balance of her empathy. Which shift is the supervisor MOST likely recommending?`,
    options: [
      { id: 'a', text: `More affective empathy, so that clients can see how deeply she shares their pain`, isCorrect: false, rationale: `She is already highly affectively attuned; adding more emotional sharing would deepen the overwhelm she reports.` },
      { id: 'b', text: `Expressing sympathy and pity instead, since they are less taxing to the counselor`, isCorrect: false, rationale: `Sympathy feels for the client from outside their frame of reference and is not a substitute for empathy.` },
      { id: 'c', text: `More cognitive empathy, grasping the client's view while keeping her own footing`, isCorrect: true, rationale: `Cognitive empathy, accurate perspective-taking with emotional separateness, keeps the "as if" quality and protects clear thinking.` },
      { id: 'd', text: `Emotional detachment, keeping reflections of feeling to an absolute minimum in session`, isCorrect: false, rationale: `Detachment would abandon empathy altogether and damage the relationship rather than rebalance it.` },
    ],
    rationale: `Affective empathy is feeling with the client; cognitive empathy is accurately understanding the client's perspective. Rogers described empathy as sensing the client's world "as if" it were one's own without losing the "as if" quality. When affective resonance turns into personal distress, strengthening the cognitive side helps counselors stay present and effective while reducing burnout and vicarious trauma risk.`,
    references: [
      { source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: accurate empathic understanding and the "as if" quality' },
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Empathy; counselor burnout and compassion fatigue' },
    ],
    reviewNote: `The cognitive/affective empathy labels come from empathy research (e.g., Davis, 1983; Decety); confirm the cited texts use this framing or treat them as supporting the "as if" concept only.`,
  },
  {
    id: 'nce-s-cor-060',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'easy',
    stem: `In person-centered counseling, offering unconditional positive regard means the counselor`,
    options: [
      { id: 'a', text: `values the client as a person without requiring approval of every behavior`, isCorrect: true, rationale: `UPR is acceptance of the person's worth that does not depend on the client's behavior; it is not approval of all actions.` },
      { id: 'b', text: `agrees with the client's decisions so the client feels supported and safe`, isCorrect: false, rationale: `UPR does not require agreeing with choices; acceptance of the person is distinct from endorsement of decisions.` },
      { id: 'c', text: `offers frequent praise to raise the client's self-esteem in each session`, isCorrect: false, rationale: `Praise is conditional by nature, tied to things the counselor approves of, which is the opposite of unconditional regard.` },
      { id: 'd', text: `keeps a neutral blank screen so that clients project feelings onto it`, isCorrect: false, rationale: `The blank screen is a psychoanalytic stance used to foster transference, not person-centered acceptance.` },
    ],
    rationale: `Rogers described unconditional positive regard as a nonpossessive caring and acceptance of the client as a person of worth, without conditions. It allows clients to explore feelings and behaviors without fearing the loss of the counselor's regard. Acceptance of the person does not mean approval of every behavior.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance' }],
  },
  {
    id: 'nce-s-cor-061',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'medium',
    stem: `A 23-year-old client starting treatment for panic attacks asks, "Just tell me straight. Is this going to fix me?" The counselor believes the approach is likely to help but cannot be certain it will work for him. Which response BEST demonstrates congruence?`,
    options: [
      { id: 'a', text: `Yes, this approach works for nearly everyone, so you'll be panic-free soon.`, isCorrect: false, rationale: `Overpromising misrepresents what the counselor actually believes and could undermine trust if progress is slow.` },
      { id: 'b', text: `What do you think it would mean for you if this didn't end up working out?`, isCorrect: false, rationale: `Deflecting a direct question with a question avoids being genuine with a client who asked for honesty.` },
      { id: 'c', text: `It's too early in our work for me to give you any kind of answer about that.`, isCorrect: false, rationale: `This withholds the counselor's honest, informed view, which she does in fact have.` },
      { id: 'd', text: `I can't promise that, but many people improve, and we'll track how it goes.`, isCorrect: true, rationale: `This matches what the counselor genuinely believes, offering honest hope without false certainty.` },
    ],
    rationale: `Congruence means the counselor's outward communication matches inner experience. When a client asks a direct question, a genuine counselor answers honestly, which here means conveying realistic hope while admitting uncertainty. False reassurance and evasion are both incongruent and can erode the trust that genuineness is meant to build.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: congruence or genuineness' }],
  },
  {
    id: 'nce-s-cor-062',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: `A 48-year-old client with marked paranoid features stiffens when the counselor mentions his former employer. "How do you know where I worked? Have you been talking to people about me?" The detail came from the intake form he completed. Which response is MOST likely to protect the working alliance?`,
    options: [
      { id: 'a', text: `Reassure him warmly that she is on his side and that he is completely safe here`, isCorrect: false, rationale: `Effusive warmth and reassurance tend to raise suspicion in clients with paranoid features rather than ease it.` },
      { id: 'b', text: `Gently note that his reaction may reflect a pattern of mistrust worth exploring`, isCorrect: false, rationale: `Interpreting his suspicion in this moment feels accusatory and is likely to deepen the rupture.` },
      { id: 'c', text: `Calmly say it came from his intake form and offer to show him the form itself`, isCorrect: true, rationale: `A plain, factual and transparent answer respects his concern and demonstrates that nothing is being hidden.` },
      { id: 'd', text: `Apologize for bringing it up and move the conversation on to another subject`, isCorrect: false, rationale: `Dropping the topic without explanation leaves his suspicion intact and can look like evasion.` },
    ],
    rationale: `Clients with paranoid features are highly sensitive to hidden motives. A straightforward, consistent and transparent style, explaining exactly where information came from and how it is used, builds trust better than warmth, interpretation or avoidance. Repairing a moment of suspicion this way strengthens the bond component of the alliance.`,
    references: [
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Working alliance: building trust and repairing ruptures' },
      { source: 'DSM-5-TR', detail: 'Paranoid personality disorder: pervasive distrust and suspiciousness of others' },
    ],
    reviewNote: `The recommendation of a matter-of-fact, transparent (not effusively warm) style with paranoid clients is standard clinical guidance but is not stated in DSM-5-TR itself; DSM is cited for the feature only.`,
  },
  {
    id: 'nce-s-cor-063',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: `A counselor in a community reentry program, herself a mother of young children, is assigned a 35-year-old man who served a sentence for physically abusing a child. She notices she is curt with him, ends sessions early, and dreads his appointments. What is the MOST appropriate action?`,
    options: [
      { id: 'a', text: `Refer him to a colleague right away, since her values conflict with his past`, isCorrect: false, rationale: `ACA A.11.b cautions against referral based solely on the counselor's personal values; she should first examine and manage the reaction.` },
      { id: 'b', text: `Explore her reaction in supervision and watch how it is affecting his care`, isCorrect: true, rationale: `Supervision helps her understand and manage negative countertransference so it stops shaping her behavior toward him.` },
      { id: 'c', text: `Tell him her feelings openly so he understands the impact of his offense`, isCorrect: false, rationale: `Disclosing her reaction this way would be punitive and serve her needs rather than his treatment.` },
      { id: 'd', text: `Keep the shorter sessions, since his offense limits what counseling can do`, isCorrect: false, rationale: `Continuing reduced care acts out the countertransference and denies him equitable treatment.` },
    ],
    rationale: `Negative countertransference toward clients who have caused harm can show up as coldness, shortened sessions and avoidance. The counselor's task is to recognize the reaction, explore it in supervision, and keep it from compromising care. ACA A.11.b asks counselors to refrain from referring prospective and current clients based solely on personally held values; referral is for genuine lack of competence after efforts to manage the reaction.`,
    references: [
      { source: 'Corey (Theory & Practice)', detail: 'Countertransference: recognizing and managing negative reactions to clients' },
      { source: 'ACA Code of Ethics', detail: 'A.11.b Values Within Termination and Referral' },
    ],
  },
  {
    id: 'nce-s-cor-064',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'warmth and respect',
    difficulty: 'easy',
    stem: `At his first session, a 26-year-old graduate student from Ghana whose name is Kwabena says, "Most people here just call me Kevin. It's easier." Which counselor response BEST conveys respect?`,
    options: [
      { id: 'a', text: `I'm happy to use whichever you prefer. If Kwabena, will you help me say it?`, isCorrect: true, rationale: `This leaves the choice with him and shows willingness to learn his name, conveying respect without pressure.` },
      { id: 'b', text: `Kevin is fine with me, then. It will keep things simple for both of us here.`, isCorrect: false, rationale: `Accepting the anglicized name for convenience skips asking what he prefers and centers ease over his identity.` },
      { id: 'c', text: `I'll call you Kwabena, because it's important to honor your true heritage.`, isCorrect: false, rationale: `Insisting on his birth name overrides his choice; respect means honoring his preference, whatever it is.` },
      { id: 'd', text: `Do you feel people here haven't respected your culture since you arrived?`, isCorrect: false, rationale: `Jumping to a probing question about discrimination presumes a problem before learning what he wants to be called.` },
    ],
    rationale: `Respect includes honoring how clients wish to be addressed. Rather than defaulting to convenience or imposing a choice, the counselor asks for his preference and offers to learn correct pronunciation. Small acts like this signal that the client's identity matters and that he directs how it is represented.`,
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Building a counseling relationship: warmth and respect' }],
  },
];
