// tools/nce/seed/core-7.js — Core Counseling Attributes, batch 7
// Hand-authored original items (nce-s-cor-097 … nce-s-cor-112).
module.exports = [
  {
    id: 'nce-s-cor-097',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'empathy and its levels',
    difficulty: 'easy',
    stem: `A 46-year-old hospice nurse says, "I hold it together for every family all day, and then I cry the whole drive home." The counselor replies, "You keep it together for the families all day, and then the tears come once you're alone in the car." On Carkhuff's five-level empathy scale, this response is BEST rated as`,
    options: [
      { id: 'a', text: `Level 2, subtractive`, isCorrect: false, rationale: `A Level 2 response drops noticeable feeling or meaning; this reply keeps both the strain and the release she described.` },
      { id: 'b', text: `Level 3, interchangeable`, isCorrect: true, rationale: `The reply returns essentially the same feeling and content the client expressed, neither adding nor subtracting, which defines Level 3.` },
      { id: 'c', text: `Level 4, additive`, isCorrect: false, rationale: `An additive response names a deeper feeling or implied meaning the client has not voiced; this one stays with what she said.` },
      { id: 'd', text: `Level 1, irrelevant or hurtful`, isCorrect: false, rationale: `Level 1 responses ignore or misread the client; this reply is accurate and respectful.` },
    ],
    rationale: `Carkhuff's scale rates responses from Level 1 (hurtful) to Level 5 (deeply additive). Level 3 is the interchangeable, minimally facilitative level: the response captures the feeling and content the client expressed at about the same depth. Additive responses (Levels 4 and 5) go further by reflecting implied feelings or meanings the client has not stated.`,
    references: [{ source: 'Ivey et al. (Intentional Interviewing)', detail: 'Empathic understanding: subtractive, interchangeable (basic) and additive responses, adapted from Carkhuff' }],
  },
  {
    id: 'nce-s-cor-098',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'unconditional positive regard',
    difficulty: 'easy',
    stem: `Carl Rogers used which term interchangeably with unconditional positive regard to describe a counselor's warm, nonpossessive caring for the client as a separate person?`,
    options: [
      { id: 'a', text: `mirroring`, isCorrect: false, rationale: `Mirroring is a self psychology concept from Kohut describing a selfobject need, not Rogers's term for acceptance.` },
      { id: 'b', text: `holding`, isCorrect: false, rationale: `The holding environment is Winnicott's object relations concept, not a Rogerian term.` },
      { id: 'c', text: `prizing`, isCorrect: true, rationale: `Rogers described unconditional positive regard as acceptance, caring or prizing of the client as a person.` },
      { id: 'd', text: `attunement`, isCorrect: false, rationale: `Affect attunement comes from Stern's work on infant development and is not Rogers's term for this condition.` },
    ],
    rationale: `Rogers described unconditional positive regard as a warm acceptance, or prizing, of the client as a separate person with permission to have their own feelings and experiences. This caring is nonpossessive and does not depend on the client meeting conditions. It is one of the three counselor-offered core conditions, alongside congruence and accurate empathic understanding.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: unconditional positive regard and acceptance (prizing) as a core condition' }],
  },
  {
    id: 'nce-s-cor-099',
    domain: 'core',
    cacrep: 'human_growth',
    topic: 'unconditional positive regard',
    difficulty: 'medium',
    stem: `After months of person-centered counseling, a 35-year-old architect who used to feel worthless after any mistake says, "I can mess up a design and still feel okay about who I am." In Rogers's theory, this change BEST reflects the client developing`,
    options: [
      { id: 'a', text: `unconditional positive self-regard`, isCorrect: true, rationale: `Valuing himself regardless of performance shows he has internalized the counselor's unconditional regard as self-regard.` },
      { id: 'b', text: `stronger conditions of worth`, isCorrect: false, rationale: `Conditions of worth make self-value depend on performance; his new stance is the opposite.` },
      { id: 'c', text: `a greater need for positive regard`, isCorrect: false, rationale: `Rogers saw the need for positive regard as universal; therapy does not increase it, and his statement shows less reliance on approval.` },
      { id: 'd', text: `a more idealized self-concept`, isCorrect: false, rationale: `A more idealized self would widen the gap between ideal and actual self; he is accepting his real, imperfect self.` },
    ],
    rationale: `Rogers held that conditions of worth, learned when regard from others depends on meeting their standards, lead people to value themselves only when they perform. When a counselor consistently offers unconditional positive regard, the client can internalize it as unconditional positive self-regard. The client then values himself even when he falls short, and his self-concept becomes more congruent with his experience.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: conditions of worth and the development of unconditional positive self-regard' }],
  },
  {
    id: 'nce-s-cor-100',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'congruence and genuineness',
    difficulty: 'medium',
    stem: `In Rogers's necessary and sufficient conditions for therapeutic change, the counselor is described as congruent, or integrated, in the relationship. By contrast, the client is described as being in a state of`,
    options: [
      { id: 'a', text: `readiness to change, prepared to act`, isCorrect: false, rationale: `Readiness and preparation are Transtheoretical Model concepts, not one of Rogers's conditions.` },
      { id: 'b', text: `transference toward the counselor`, isCorrect: false, rationale: `Transference is a psychodynamic concept; Rogers did not make it a condition of change.` },
      { id: 'c', text: `resistance to the counselor's aims`, isCorrect: false, rationale: `Rogers did not describe the client as resistant; his conditions describe vulnerability, not opposition.` },
      { id: 'd', text: `incongruence, vulnerable or anxious`, isCorrect: true, rationale: `Rogers's second condition states that the client is in a state of incongruence, being vulnerable or anxious.` },
    ],
    rationale: `Rogers (1957) listed six conditions: two persons in psychological contact; a client who is incongruent, vulnerable or anxious; a counselor who is congruent in the relationship; the counselor's unconditional positive regard; the counselor's empathic understanding; and the client's perception, at least to a minimal degree, of that regard and empathy. Congruence in the counselor is set deliberately against incongruence in the client, whose self-concept and experience do not match.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: Rogers\'s necessary and sufficient conditions for personality change' }],
  },
  {
    id: 'nce-s-cor-101',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: `In a first family session, a 15-year-old answers in a few words, glances at her stepfather before each reply, and says nothing when asked what she would like to change at home. In Friedlander and colleagues' SOFTA model, the counselor's choice to spend part of the session with her alone MOST directly targets which alliance dimension?`,
    options: [
      { id: 'a', text: `Engagement in the therapeutic process`, isCorrect: false, rationale: `Engagement concerns taking part in setting goals and doing the work; her guardedness centers on whether it is safe to speak.` },
      { id: 'b', text: `Safety within the therapeutic system`, isCorrect: true, rationale: `Checking with a family member before speaking signals she does not feel safe to be open; individual time addresses that safety.` },
      { id: 'c', text: `Emotional connection to the therapist`, isCorrect: false, rationale: `Emotional connection is the bond with the counselor; nothing suggests she dislikes or distrusts the counselor in particular.` },
      { id: 'd', text: `Shared sense of purpose in the family`, isCorrect: false, rationale: `Shared purpose is family members' agreement and collaboration with each other, which a meeting apart does not directly build.` },
    ],
    rationale: `The System for Observing Family Therapy Alliances (SOFTA) has four dimensions: engagement in the therapeutic process, emotional connection to the therapist, safety within the therapeutic system, and shared sense of purpose within the family. Safety refers to feeling comfortable taking risks and being open in front of other family members. When a member seems to monitor another before speaking, the counselor can build safety by meeting separately, setting ground rules or protecting the member from blame.`,
    references: [{ source: 'Friedlander et al. (Alliances in Couple & Family Therapy)', detail: 'SOFTA dimensions: engagement, emotional connection, safety within the therapeutic system, shared sense of purpose' }],
  },
  {
    id: 'nce-s-cor-102',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'therapeutic alliance',
    difficulty: 'hard',
    stem: `A counselor and a long-term client share a warm, genuine connection in which each perceives the other fairly accurately, apart from any transference and apart from their collaboration on goals and tasks. In Gelso's tripartite model of the therapy relationship, this component is called the`,
    options: [
      { id: 'a', text: `working alliance`, isCorrect: false, rationale: `The working alliance is the collaboration on goals and tasks with a bond, which the stem sets aside.` },
      { id: 'b', text: `holding environment`, isCorrect: false, rationale: `The holding environment is Winnicott's term and is not one of the three components in Gelso's model.` },
      { id: 'c', text: `real relationship`, isCorrect: true, rationale: `The real relationship is the personal bond marked by genuineness and realistic perception of each other.` },
      { id: 'd', text: `corrective experience`, isCorrect: false, rationale: `A corrective emotional experience is Alexander's term for a therapeutic event, not a component of Gelso's model.` },
    ],
    rationale: `Gelso's tripartite model describes every therapy relationship as having three parts: the working alliance, the transference-countertransference configuration, and the real relationship. The real relationship is defined by genuineness (being authentic with each other) and realism (perceiving each other as they actually are). Research links a stronger real relationship to better outcomes, apart from the alliance.`,
    references: [{ source: 'Gelso & Hayes (Countertransference)', detail: 'Tripartite model of the therapy relationship: working alliance, transference-countertransference configuration, real relationship' }],
  },
  {
    id: 'nce-s-cor-103',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: `A 27-year-old Indian American client says she has agreed to meet a man her parents found through family networks, with marriage as the shared goal. The counselor, who personally values choosing a partner on one's own, notices a flicker of unease. Which counselor response BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Ask what this path means to her and what she hopes for, while holding her own values lightly`, isCorrect: true, rationale: `Exploring the client's meaning and hopes puts her worldview first and keeps the counselor's preference out of the lead.` },
      { id: 'b', text: `Gently remind her that she has the right to choose a partner without her parents' involvement`, isCorrect: false, rationale: `This presumes the counselor's individualistic value is the right one and implies her choice is not truly hers.` },
      { id: 'c', text: `Explore whether she feels pressured, since family introductions tend to limit a woman's choice`, isCorrect: false, rationale: `Starting from an assumption of coercion stereotypes a consensual practice she has described as her own choice.` },
      { id: 'd', text: `Share that the counselor also grew up with strong family expectations about whom to marry`, isCorrect: false, rationale: `This self-disclosure shifts the focus to the counselor before the client's own experience is understood.` },
    ],
    rationale: `Cultural humility is an other-oriented stance in which the counselor recognizes the limits of her own worldview and lets the client define what a practice means to her. Family-arranged or family-assisted introductions are a consensual and valued tradition for many people and are distinct from forced marriage. The counselor notes her own reaction, explores the client's hopes, and stays open to concerns only if the client raises them.`,
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Collectivistic versus individualistic values; family role in decision making among Asian Americans' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counselor self-awareness and client worldview domains' },
    ],
  },
  {
    id: 'nce-s-cor-104',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'cultural humility',
    difficulty: 'medium',
    stem: `A 72-year-old Chinese immigrant referred by his physician for depression describes poor sleep, low energy and "a heavy feeling in my chest," but says he does not feel sad. Which counselor approach BEST reflects cultural humility?`,
    options: [
      { id: 'a', text: `Explain that chest heaviness is a common sign of depression so he can accept the diagnosis`, isCorrect: false, rationale: `Imposing the counselor's framework before learning his understanding can feel dismissive and weaken engagement.` },
      { id: 'b', text: `Note that he is minimizing his mood and gently confront the denial of sadness in session`, isCorrect: false, rationale: `Treating his description as denial pathologizes a culturally common way of expressing distress.` },
      { id: 'c', text: `Refer him back to his physician, since the concerns he presents are mainly physical ones`, isCorrect: false, rationale: `The physician already referred him; somatic expression of distress is within the counselor's work.` },
      { id: 'd', text: `Ask what he thinks is causing the heaviness and what might help, using his words for it`, isCorrect: true, rationale: `Exploring his own explanation of the problem respects his worldview and builds a shared understanding.` },
    ],
    rationale: `Many clients, including some older Chinese immigrants, express psychological distress through bodily symptoms rather than mood words. A culturally humble counselor asks about the client's own explanatory model, meaning his view of what is wrong, why, and what would help, instead of correcting or confronting it. Using the client's language helps engagement and lets treatment fit his understanding.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling Asian Americans: somatic expression of psychological distress and culturally responsive assessment' }],
  },
  {
    id: 'nce-s-cor-105',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'hard',
    stem: `A counselor realizes she tends to see clients' problems as the result of their own choices and believes anyone who works hard can change their circumstances. She wonders how this view lands with clients who face discrimination. In D. W. Sue's worldview model, her outlook is BEST described as`,
    options: [
      { id: 'a', text: `external locus of control, internal locus of responsibility`, isCorrect: false, rationale: `EC-IR describes people who feel little control yet blame themselves, a pattern Sue linked to marginality.` },
      { id: 'b', text: `internal locus of control, internal locus of responsibility`, isCorrect: true, rationale: `Believing people control their fate (IC) and cause their own problems (IR) is the IC-IR worldview typical of mainstream U.S. culture.` },
      { id: 'c', text: `internal locus of control, external locus of responsibility`, isCorrect: false, rationale: `IC-ER holds that people can shape their lives when given a chance but that barriers are often systemic, which she does not endorse.` },
      { id: 'd', text: `external locus of control, external locus of responsibility`, isCorrect: false, rationale: `EC-ER sees both control and blame as lying in the system, the opposite of her view.` },
    ],
    rationale: `Sue's worldview model crosses locus of control (internal or external) with locus of responsibility (internal or external) to form four quadrants. The IC-IR quadrant reflects the individualistic values of mainstream U.S. culture and much of counseling theory. Counselors who hold this view without examining it may blame clients facing systemic barriers, so self-awareness of one's own worldview is a core multicultural competence.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Worldview: locus of control and locus of responsibility, four quadrants (IC-IR, EC-IR, EC-ER, IC-ER)' }],
  },
  {
    id: 'nce-s-cor-106',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'counselor self-awareness and bias',
    difficulty: 'easy',
    stem: `Reviewing her case notes, a counselor sees she described a 45-year-old client who identifies as bisexual and is married to a man as "formerly bisexual, now in a heterosexual marriage." The client has never described herself that way. What does this wording MOST likely reveal?`,
    options: [
      { id: 'a', text: `Accurate shorthand, since the marriage shows what the client's orientation is now`, isCorrect: false, rationale: `A partner's gender does not define a person's orientation; the client still identifies as bisexual.` },
      { id: 'b', text: `A clinical clue that the client may be uncertain about her own sexual orientation`, isCorrect: false, rationale: `Nothing the client said suggests uncertainty; the label came from the counselor, not from her.` },
      { id: 'c', text: `The counselor's assumption that a partner's gender defines the client's orientation`, isCorrect: true, rationale: `Relabeling her identity from her marriage reflects the counselor's own bias, a form of bisexual erasure.` },
      { id: 'd', text: `A reasonable summary, since case notes need to record only current relationship status`, isCorrect: false, rationale: `The note does more than record status; it overrides the identity the client herself claims.` },
    ],
    rationale: `Sexual orientation is self-defined and is not determined by the gender of a current partner. Describing a bisexual client as "formerly bisexual" because she married a man reflects a common bias that erases bisexual identity. Counselor self-awareness includes catching how such assumptions surface in notes and language, correcting the record, and using the client's own terms.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling LGBTQ individuals: bisexual invisibility and counselor heterosexist assumptions' }],
  },
  {
    id: 'nce-s-cor-107',
    domain: 'core',
    cacrep: 'professional_orientation',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: `A 34-year-old counselor notices that she looks forward to sessions with a charming male client, dresses with more care on those days, and has started daydreaming about him. What should she do FIRST?`,
    options: [
      { id: 'a', text: `Seek supervision to explore the attraction and keep firm professional boundaries in session`, isCorrect: true, rationale: `Supervision helps her understand and contain the feelings while she continues to protect the client and the work.` },
      { id: 'b', text: `Tell the client about her feelings so the attraction is out in the open and can be processed`, isCorrect: false, rationale: `Disclosing attraction burdens the client, serves the counselor's needs and risks a boundary violation.` },
      { id: 'c', text: `Refer him to another counselor at once without explanation, to remove the risk completely`, isCorrect: false, rationale: `An abrupt, unexplained referral can harm the client; feelings alone do not require ending the work.` },
      { id: 'd', text: `Wait to see whether the feelings fade, since attraction to clients tends to pass on its own`, isCorrect: false, rationale: `Waiting alone leaves the feelings unexamined and free to shape her behavior in session.` },
    ],
    rationale: `Sexual attraction to a client is a common form of countertransference and is not unethical in itself; acting on it is. The ACA Code of Ethics prohibits sexual or romantic relationships with current clients, so the counselor's task is to recognize, understand and manage the feelings. Supervision or consultation is the first step, and a referral is considered only if the feelings cannot be managed in the client's interest.`,
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.5.a Sexual and/or Romantic Relationships Prohibited' },
      { source: 'Gelso & Hayes (Countertransference)', detail: 'Managing countertransference: self-insight and the use of supervision' },
    ],
  },
  {
    id: 'nce-s-cor-108',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'countertransference',
    difficulty: 'medium',
    stem: `Three months after her own father died, a counselor realizes that whenever a grieving client starts talking about his late father, she shifts the conversation to coping strategies or scheduling. This pattern is BEST understood as`,
    options: [
      { id: 'a', text: `empathic pacing that protects the client from being flooded`, isCorrect: false, rationale: `Pacing follows the client's readiness; here the shift follows the counselor's discomfort, not the client's cues.` },
      { id: 'b', text: `projective identification arising from the client's grief`, isCorrect: false, rationale: `Nothing suggests the client is inducing these feelings; the source is the counselor's own recent loss.` },
      { id: 'c', text: `overinvolvement from overidentifying with the client's loss`, isCorrect: false, rationale: `Overinvolvement draws the counselor closer to the material; she is moving away from it.` },
      { id: 'd', text: `avoidant countertransference rooted in her own recent loss`, isCorrect: true, rationale: `Steering away from material that touches her unresolved grief is a classic avoidant countertransference behavior.` },
    ],
    rationale: `Countertransference can show up as overinvolvement or as underinvolvement, such as avoiding, withdrawing from or changing the subject when material touches the counselor's unresolved issues. Here the counselor's recent loss leads her away from the very grief the client needs to explore. Recognizing the pattern and taking it to supervision lets her return to the client's material.`,
    references: [{ source: 'Gelso & Hayes (Countertransference)', detail: 'Countertransference behavior: avoidance and underinvolvement versus overinvolvement' }],
  },
  {
    id: 'nce-s-cor-109',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'nonjudgmental stance',
    difficulty: 'easy',
    stem: `A 22-year-old client who is seven months pregnant says she has chosen to place the baby for adoption. "People at my church say I'm abandoning my child." Which counselor response BEST reflects a nonjudgmental stance?`,
    options: [
      { id: 'a', text: `Have you thought about whether you might regret this later, once the baby is actually born?`, isCorrect: false, rationale: `The question implies her decision is likely mistaken and signals the counselor's doubt.` },
      { id: 'b', text: `Your church community cares about you, so their concerns might be worth weighing carefully.`, isCorrect: false, rationale: `This sides with the church members' view and nudges her to reconsider.` },
      { id: 'c', text: `It sounds like a decision you've thought hard about. How are their comments landing for you?`, isCorrect: true, rationale: `It respects her decision without evaluating it and invites her to explore the impact of others' judgment.` },
      { id: 'd', text: `You're doing a brave and selfless thing, and anyone who judges you just doesn't understand.`, isCorrect: false, rationale: `Praise is still a judgment; it approves the choice and dismisses others instead of exploring her experience.` },
    ],
    rationale: `A nonjudgmental stance means neither condemning nor approving the client's choice, and instead seeking to understand her experience of it. Both doubt and praise place the counselor's values at the center. Reflecting the client's own process and exploring how others' reactions affect her keeps the focus on her.`,
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Person-centered therapy: acceptance without evaluation of the client\'s choices' }],
  },
  {
    id: 'nce-s-cor-110',
    domain: 'core',
    cacrep: 'helping_relationships',
    topic: 'warmth and respect',
    difficulty: 'medium',
    stem: `In a first session, a 63-year-old client looks down while he talks, speaks softly and leaves long pauses before answering. The counselor is used to steady eye contact and a quicker pace. Using Ivey's attending behavior framework, which adjustment BEST conveys warmth and respect?`,
    options: [
      { id: 'a', text: `Soften her own eye contact and allow silences, matching the client's comfortable pace`, isCorrect: true, rationale: `Adapting eye contact and pacing to the client's style shows respect and helps him feel at ease.` },
      { id: 'b', text: `Hold steady eye contact to show interest, since looking away suggests disengagement`, isCorrect: false, rationale: `Eye contact norms vary across people and cultures; looking down does not by itself mean disengagement.` },
      { id: 'c', text: `Fill pauses with encouraging prompts so that the client does not feel the silence is awkward`, isCorrect: false, rationale: `Filling his pauses can rush him and suggests the silence is uncomfortable for the counselor.` },
      { id: 'd', text: `Ask the client directly why he avoids eye contact, so that she can understand the behavior`, isCorrect: false, rationale: `Questioning his eye contact early on can feel critical and puts him on the spot.` },
    ],
    rationale: `Ivey's attending behavior covers culturally appropriate eye contact, vocal qualities, verbal tracking and attentive body language. Norms for eye contact, pace and silence differ across individuals and cultures, so attending well means adapting to the client rather than holding to one standard. Allowing silence gives the client room to think and communicates patience and respect.`,
    references: [{ source: 'Ivey et al. (Intentional Interviewing)', detail: 'Attending behavior: eye contact, vocal qualities, verbal tracking, body language, and cultural differences; use of silence' }],
  },
  {
    id: 'nce-s-cor-111',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'easy',
    stem: `At the end of an intake, a counselor tells a 58-year-old client, "You meet criteria for GAD with comorbid MDD, so we'll start a CBT protocol with an exposure hierarchy." The client nods but looks confused and says nothing. Which counselor action BEST addresses the power difference in this moment?`,
    options: [
      { id: 'a', text: `Give the client printed handouts on each diagnosis to read at home before the next session`, isCorrect: false, rationale: `Handouts can help later, but they leave the confusion and one-way communication in the room unaddressed.` },
      { id: 'b', text: `Proceed with the plan, since the client nodded and can bring any questions to a later session`, isCorrect: false, rationale: `A nod from a confused client is not understanding or agreement; the counselor keeps all the control.` },
      { id: 'c', text: `Repeat the diagnoses more slowly so the client can write the clinical terms down to look up`, isCorrect: false, rationale: `Slower jargon is still jargon; the client remains outside the professional language.` },
      { id: 'd', text: `Restate the findings in plain language, ask what the client makes of them and plan together`, isCorrect: true, rationale: `Plain language and an invitation to respond share power and make the plan a joint decision.` },
    ],
    rationale: `Clinical jargon signals expertise and can silence clients, who may nod along rather than question a professional. The ACA Code of Ethics asks counselors to communicate in clear, understandable language that fits the client's development and culture. Translating findings and inviting the client's view turns a one-way pronouncement into collaborative treatment planning.`,
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.2.c Developmental and Cultural Sensitivity' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship domain: addressing power differences between counselor and client' },
    ],
  },
  {
    id: 'nce-s-cor-112',
    domain: 'core',
    cacrep: 'social_cultural',
    topic: 'awareness of power and privilege in the counseling relationship',
    difficulty: 'medium',
    stem: `A counselor has been asked to write a letter supporting a 27-year-old transgender woman's gender-affirming surgery. At their first meeting, the client seems guarded and gives answers that sound rehearsed. Which counselor action BEST addresses the power dynamic in this relationship?`,
    options: [
      { id: 'a', text: `Reassure her that the letter is a formality and that she need not worry about the outcome`, isCorrect: false, rationale: `This offers false reassurance and glosses over the real influence the counselor holds.` },
      { id: 'b', text: `Name the counselor's role in the letter and invite her to say how it shapes what she shares`, isCorrect: true, rationale: `Openly naming the gatekeeping role makes the power difference discussable and invites collaboration.` },
      { id: 'c', text: `Postpone any talk of the letter until she has built enough trust to open up in sessions`, isCorrect: false, rationale: `Avoiding the topic leaves the power difference unspoken, which can deepen her guardedness.` },
      { id: 'd', text: `Explain the assessment criteria in detail so that she knows which answers will qualify her`, isCorrect: false, rationale: `Framing it as right answers keeps the evaluative stance and invites more rehearsed replies.` },
    ],
    rationale: `When a counselor controls access to something the client needs, such as a letter for surgery, the power difference can lead the client to present a guarded, rehearsed version of herself. Naming the role openly and inviting the client's view brings the dynamic into the relationship where it can be addressed. This reflects the MSJCC counseling relationship domain, which asks counselors to attend to how privilege and power shape the work.`,
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling relationship domain: addressing power and privilege between counselor and client' }],
  },
];
