// tools/nce/seed/counseling-3.js
// NCE seed — Counseling Skills and Interventions, batch 2: group work
// (screening, formats, roles, leader skills, cohesion, Bion), career theories
// (Parsons through Savickas, O*NET) and human development (Freud, Marcia,
// Levinson, Bronfenbrenner, Vygotsky, Gilligan, resilience).
module.exports = [
  // ---------------------------------------------------------------- group work
  {
    id: 'nce-s-cou-061',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'A counselor is interviewing applicants for a 10-week interpersonal process group. Under the ACA Code of Ethics, the main purpose of this pre-group screening is to:',
    options: [
      { id: 'a', text: 'confirm that each applicant has a diagnosis that the group can be billed for', isCorrect: false, rationale: 'Billing eligibility is an administrative matter; the Code frames screening around fit, group process and member welfare.' },
      { id: 'b', text: 'collect a detailed history so the leader can interpret members in session', isCorrect: false, rationale: 'Some history may be gathered, but screening exists to select suitable members, not to prepare interpretations.' },
      { id: 'c', text: 'select members whose goals fit the group and who will not be harmed by it', isCorrect: true, rationale: 'A.9.a directs counselors to select members whose needs and goals are compatible with the group, who will not impede it and whose well-being will not be jeopardized.' },
      { id: 'd', text: 'make sure that every member shares the same cultural background and age range', isCorrect: false, rationale: 'Homogeneity can be useful for some groups, but it is not the ethical purpose of screening, and diversity often enriches a group.' },
    ],
    rationale: 'ACA Code A.9.a requires counselors to screen prospective group members and, to the extent possible, select those whose needs and goals are compatible with the group\'s goals, who will not impede the group process and whose well-being will not be jeopardized by the experience. The ASGW Best Practice Guidelines likewise treat screening and orientation as part of group planning.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.9.a Screening' },
      { source: 'Corey (Theory & Practice)', detail: 'Group work: pre-group screening and selection of members' },
    ],
  },
  {
    id: 'nce-s-cou-062',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A counselor on an acute inpatient psychiatric unit, where the average stay is five days, is designing a daily coping-skills group. Which group format is MOST appropriate?',
    options: [
      { id: 'a', text: 'An open group that admits new members as patients arrive', isCorrect: true, rationale: 'With rapid turnover, an open group lets patients join and leave as they are admitted and discharged, and each session can stand alone.' },
      { id: 'b', text: 'A closed group that keeps the same members for eight weeks', isCorrect: false, rationale: 'A closed eight-week group is impossible when patients stay about five days; most would be discharged after a few sessions.' },
      { id: 'c', text: 'A closed group with a waiting list for the next full cycle', isCorrect: false, rationale: 'A waiting list would keep most short-stay patients from attending at all before discharge.' },
      { id: 'd', text: 'A marathon group that meets once for a full weekend session', isCorrect: false, rationale: 'A single marathon session does not fit a daily skills program or the unpredictable timing of admissions.' },
    ],
    rationale: 'Open groups replace members as they leave, which suits settings with high turnover such as inpatient units, though new arrivals can slow the growth of cohesion. Closed groups keep the same members from start to finish, which supports stability and cohesion but requires members who can commit for the full duration.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group work: open versus closed groups' }],
  },
  {
    id: 'nce-s-cou-063',
    reviewNote: 'Verify the recommended size range for young children\'s groups in the current Corey or Gladding edition (commonly cited as about 3 to 5).',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'An elementary school counselor is forming a counseling group for 7-year-olds whose parents recently divorced. Which group size is generally recommended for a group of children this age?',
    options: [
      { id: 'a', text: '8 to 10 members', isCorrect: false, rationale: 'Eight to ten is closer to the size often suggested for adult counseling groups; young children need more individual attention.' },
      { id: 'b', text: '3 to 5 members', isCorrect: true, rationale: 'Young children have short attention spans and need frequent leader attention, so very small groups are recommended.' },
      { id: 'c', text: '12 to 15 members', isCorrect: false, rationale: 'A group this large would leave young children little time to talk and make the group hard to manage.' },
      { id: 'd', text: '20 to 25 members', isCorrect: false, rationale: 'This is a classroom guidance size, suited to psychoeducation lessons rather than a counseling group.' },
    ],
    rationale: 'Group size depends on members\' age, the leader\'s experience and the type of group. Groups for young children are kept small (often about 3 to 5) and sessions short; adolescent groups are somewhat larger, and an ongoing adult counseling group of about 8 members with one leader is often cited as workable.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group work: practical considerations, group size and composition' }],
  },
  {
    id: 'nce-s-cou-064',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'Two co-leaders of an adult support group notice that members have begun bringing complaints about one leader to the other, and the leaders have started to feel competitive with each other. Which step BEST addresses this co-leadership problem?',
    options: [
      { id: 'a', text: 'Divide the members so that each leader is responsible for half of the group', isCorrect: false, rationale: 'Splitting the group between leaders formalizes the division and leaves the competition unaddressed.' },
      { id: 'b', text: 'Let the more experienced co-leader run the sessions while the other observes', isCorrect: false, rationale: 'Sidelining one leader avoids the conflict instead of resolving it and wastes the benefits of co-leadership.' },
      { id: 'c', text: 'Agree to hide any differences of opinion from the members during sessions', isCorrect: false, rationale: 'Respectfully voiced differences can model healthy conflict; concealing them tends to feed the splitting.' },
      { id: 'd', text: 'Meet regularly between sessions to talk openly about their working relationship', isCorrect: true, rationale: 'Regular meetings to process their relationship let co-leaders address rivalry and present a united, coordinated approach.' },
    ],
    rationale: 'Co-leadership offers shared perspective, modeling of a healthy relationship, coverage for absences and mutual support. Its main risks are poor communication, competition and members splitting the leaders. Corey stresses that co-leaders should meet before and after sessions to plan and to process their own relationship.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group leadership: advantages and disadvantages of co-leadership' }],
  },
  {
    id: 'nce-s-cou-065',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'In the fourth session of a men\'s support group, one member has again taken most of the time telling long stories about his week, while others glance at the clock. Which leader response is MOST appropriate?',
    options: [
      { id: 'a', text: '"You\'ve given us a lot to think about. I\'d like to hear how others are reacting to what you said."', isCorrect: true, rationale: 'This acknowledges the member without attacking him, blocks the monopolizing and opens the floor to the rest of the group.' },
      { id: 'b', text: '"Let\'s keep listening, since he clearly needs the group\'s time today more than anyone else does."', isCorrect: false, rationale: 'Letting the pattern continue reinforces monopolizing and ignores the frustration building among other members.' },
      { id: 'c', text: '"You talk too much in here, and it is unfair to the others. Please stay quiet for the rest of today."', isCorrect: false, rationale: 'A harsh, shaming confrontation can humiliate the member and makes others fear the same treatment.' },
      { id: 'd', text: '"I\'ll speak with you privately after group about whether this group is a good fit for your needs."', isCorrect: false, rationale: 'Raising removal ignores a workable in-group intervention and treats a common group behavior as grounds for exclusion.' },
    ],
    rationale: 'Monopolizing is one of the most common problem behaviors in groups. Leaders intervene early and respectfully, blocking the behavior while protecting the member\'s dignity, and they often invite the group to share reactions so members learn to address the pattern directly.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group work: problem behaviors, the monopolizing member' }],
  },
  {
    id: 'nce-s-cou-066',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'In a teen group, several members begin blaming one boy for the group\'s lack of progress, citing his lateness and jokes, and they bring him up whenever the discussion becomes tense. Which leader response is BEST?',
    options: [
      { id: 'a', text: 'Ask the boy to explain to the group why he keeps arriving late and making jokes', isCorrect: false, rationale: 'Putting him on the spot joins the group\'s blaming and deepens his role as the scapegoat.' },
      { id: 'b', text: 'Allow the criticism to continue, since honest feedback helps him change his conduct', isCorrect: false, rationale: 'Collective blaming is not constructive feedback, and letting it continue fails the leader\'s duty to protect members.' },
      { id: 'c', text: 'Block the blaming and ask the group to look at what is happening among them now', isCorrect: true, rationale: 'The leader protects the targeted member and turns attention to the group process, including the feelings members may be displacing onto him.' },
      { id: 'd', text: 'Move the boy to a different group so that the others can resume productive work', isCorrect: false, rationale: 'Removing the scapegoat leaves the underlying dynamic in place, and the group often finds a new target.' },
    ],
    rationale: 'Scapegoating occurs when a group displaces its tension onto one member. The leader blocks the attack to protect that member and then explores what the group is avoiding, which usually involves members\' own anxieties or conflicts with the leader or one another.',
    references: [
      { source: 'Corey (Theory & Practice)', detail: 'Group work: scapegoating and protecting members' },
      { source: 'ACA Code of Ethics', detail: 'A.9.b Protecting Clients (group work)' },
    ],
  },
  {
    id: 'nce-s-cou-067',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: 'A group leader says, "I notice that each time someone starts to talk about anger, the group quickly shifts to joking. What do you make of that?" This statement is an example of which leader focus?',
    options: [
      { id: 'a', text: 'A content focus on the topic under discussion', isCorrect: false, rationale: 'A content focus addresses what is being discussed, such as the anger itself, rather than how the group handles it.' },
      { id: 'b', text: 'A process focus on how the members interact', isCorrect: true, rationale: 'The leader is commenting on the pattern of interaction in the room, which is a process observation.' },
      { id: 'c', text: 'An educational focus on the facts about anger', isCorrect: false, rationale: 'An educational focus would teach information about anger rather than reflect a pattern back to the group.' },
      { id: 'd', text: 'An individual focus on one member\'s history', isCorrect: false, rationale: 'The observation is about the group as a whole, not about any one member\'s background.' },
    ],
    rationale: 'Content is what the group talks about; process is how members relate to one another while they talk, including patterns of avoidance, alliances and shifts in mood. Process comments help members see their here-and-now behavior and are central to interpersonal group work.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Ch. 6: The here-and-now and process illumination' }],
  },
  {
    id: 'nce-s-cou-068',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: 'A leader says, "Amara, what you just described about feeling invisible at work sounds a lot like what Dev shared last week about his family. Dev, how does Amara\'s story land for you?" Which group leadership skill is the leader using?',
    options: [
      { id: 'a', text: 'Cutting off', isCorrect: false, rationale: 'Cutting off stops a member who is rambling or going off track; nothing is being stopped here.' },
      { id: 'b', text: 'Drawing out', isCorrect: false, rationale: 'Drawing out invites a quiet member to participate; the main move here is connecting two members\' concerns.' },
      { id: 'c', text: 'Summarizing', isCorrect: false, rationale: 'Summarizing pulls together the main points of a discussion rather than connecting two members.' },
      { id: 'd', text: 'Linking', isCorrect: true, rationale: 'Linking connects what one member says or feels to another member\'s concerns, promoting member-to-member interaction.' },
    ],
    rationale: 'Linking builds cohesion and universality by pointing out common themes between members and encouraging them to speak to each other rather than only to the leader. Related skills include drawing out quieter members and cutting off, or redirecting, members who stray from the group\'s focus.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group leadership skills: linking' }],
  },
  {
    id: 'nce-s-cou-069',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: 'Which statement about group cohesiveness is MOST consistent with Yalom\'s account of it?',
    options: [
      { id: 'a', text: 'Highly cohesive groups can express and work through more conflict and hostility.', isCorrect: true, rationale: 'Yalom notes that members of cohesive groups feel secure enough to voice anger and disagreement, which can then be worked through.' },
      { id: 'b', text: 'Cohesiveness is mostly fixed by the end of the first session and changes little later.', isCorrect: false, rationale: 'Cohesion develops and fluctuates over the life of a group; it is not set in the first meeting.' },
      { id: 'c', text: 'Cohesive groups tend to have poorer attendance because members feel less accountable.', isCorrect: false, rationale: 'Cohesion is linked to better attendance, greater participation and lower dropout, not poorer attendance.' },
      { id: 'd', text: 'Cohesion is a distinct outcome rather than a condition for other therapeutic factors.', isCorrect: false, rationale: 'Yalom treats cohesiveness as a precondition for other factors, comparable to the relationship in individual therapy.' },
    ],
    rationale: 'Yalom describes cohesiveness as the group analogue of the therapeutic relationship: the members\' sense of belonging and acceptance. It is associated with better attendance, more self-disclosure, greater risk-taking and better outcomes, and cohesive groups can tolerate open conflict because members trust the group to survive it.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Ch. 3: Group cohesiveness' }],
  },
  {
    id: 'nce-s-cou-070',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'Midway through a closed 12-week counseling group, a member emails the leader that she has decided to quit the group and will not return. What is the BEST response from the leader?',
    options: [
      { id: 'a', text: 'Tell her she agreed to finish all 12 weeks and must attend until the group ends', isCorrect: false, rationale: 'Members have the right to leave a group; the leader can encourage but not compel continued attendance.' },
      { id: 'b', text: 'Accept her decision and avoid mentioning her absence so the others stay focused', isCorrect: false, rationale: 'Unexplained departures affect remaining members, who may wonder whether they caused it; silence leaves this unprocessed.' },
      { id: 'c', text: 'Respect her right to leave while encouraging her to talk it over with the group', isCorrect: true, rationale: 'Corey advises leaders to respect members\' freedom to leave while encouraging them to discuss the decision with the group rather than simply disappear.' },
      { id: 'd', text: 'Replace her at once with a new member from the waiting list to keep the size stable', isCorrect: false, rationale: 'Adding a member midway changes the closed format and does nothing to address the departure itself.' },
    ],
    rationale: 'Members have the right to leave a group, but an abrupt exit can leave both the departing member and the remaining members with unfinished business. Leaders explain this during orientation and, when a member wants to leave, encourage discussion of the decision in the group and process the loss with those who remain.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group work ethics: freedom to leave a group' }],
  },
  {
    id: 'nce-s-cou-071',
    reviewNote: 'Verify that the cited Yalom & Leszcz chapter (group-as-a-whole/Tavistock discussion) covers Bion\'s basic assumptions; Corey or Gladding may be a better reference.',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'hard',
    stem: 'In a training group, members persistently treat the leader as all-knowing, wait passively for direction and become resentful when the leader does not supply answers. In Bion\'s theory of group functioning, this pattern BEST reflects which basic assumption?',
    options: [
      { id: 'a', text: 'Fight-flight', isCorrect: false, rationale: 'Fight-flight is shown when the group attacks something or escapes the task, for example through hostility or changing the subject.' },
      { id: 'b', text: 'Dependency', isCorrect: true, rationale: 'In basic assumption dependency the group acts as if a strong leader will provide for and protect it, and members become passive.' },
      { id: 'c', text: 'Pairing', isCorrect: false, rationale: 'Pairing is a shared hope that two members will produce a future savior or solution, not reliance on the leader.' },
      { id: 'd', text: 'Work group', isCorrect: false, rationale: 'The work group is Bion\'s term for the rational, task-focused mode of functioning, not a basic assumption.' },
    ],
    rationale: 'Wilfred Bion, working at the Tavistock Clinic, proposed that groups alternate between a work group focused on the task and three unconscious basic assumptions: dependency, fight-flight and pairing. Recognizing a basic assumption lets the leader interpret the group-as-a-whole behavior instead of simply meeting the demand.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Group-as-a-whole approaches: Bion\'s basic assumptions (Tavistock)' }],
  },
  // ------------------------------------------------------------ career theories
  {
    id: 'nce-s-cou-072',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'easy',
    stem: 'Frank Parsons described wise vocational choice as resting on a clear understanding of oneself, knowledge of the requirements and conditions of different jobs, and which third element?',
    options: [
      { id: 'a', text: 'Exploration of chance events that may reshape one\'s path', isCorrect: false, rationale: 'Using chance events is central to Krumboltz\'s planned happenstance, not to Parsons\' model.' },
      { id: 'b', text: 'Implementation of the self-concept through a series of roles', isCorrect: false, rationale: 'Implementing the self-concept in work roles is Super\'s idea, developed decades after Parsons.' },
      { id: 'c', text: 'Resolution of early parent-child needs through one\'s work', isCorrect: false, rationale: 'Linking occupational choice to early parent-child relations is Anne Roe\'s theory.' },
      { id: 'd', text: 'True reasoning on the relations between these two groups', isCorrect: true, rationale: 'Parsons\' third step was "true reasoning" about how the person\'s traits match the requirements of occupations.' },
    ],
    rationale: 'In Choosing a Vocation (1909), Parsons set out three steps: understand yourself, know the world of work and use true reasoning to match the two. This matching approach became trait-factor theory and underlies later person-environment fit models such as Holland\'s.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Trait and factor theory: Parsons\' three-part model' }],
  },
  {
    id: 'nce-s-cou-073',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A client\'s interest inventory shows a very high Investigative score, while her other five RIASEC scores are all low and close together. In Holland\'s theory, this profile is BEST described as showing a high degree of:',
    options: [
      { id: 'a', text: 'Differentiation', isCorrect: true, rationale: 'Differentiation is the degree to which a profile has clear peaks and valleys; one high score above flat low scores is well differentiated.' },
      { id: 'b', text: 'Consistency', isCorrect: false, rationale: 'Consistency concerns how close a person\'s top types sit on the hexagon, which needs at least two high types to judge.' },
      { id: 'c', text: 'Congruence', isCorrect: false, rationale: 'Congruence is the fit between a person\'s type and the work environment, which a profile alone does not show.' },
      { id: 'd', text: 'Calculus', isCorrect: false, rationale: 'Calculus is Holland\'s assumption that hexagon distances reflect type relationships, not a property of one profile.' },
    ],
    rationale: 'Holland\'s secondary constructs include differentiation (how distinct the profile is), consistency (how related the top types are on the hexagon), congruence (person-environment fit), identity (clarity and stability of goals) and calculus. A flat profile is undifferentiated and is often associated with less clear career direction.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Holland\'s theory: differentiation, consistency and congruence' }],
  },
  {
    id: 'nce-s-cou-074',
    reviewNote: 'Confirm attribution: Super proposed career adaptability for adults (early 1980s), later developed by Savickas.',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'Super used career maturity to describe an adolescent\'s readiness to make age-appropriate career decisions. Because adults recycle through stages rather than progress in a fixed order, which term did Super propose for readiness to cope with changing work and working conditions in adulthood?',
    options: [
      { id: 'a', text: 'Career salience', isCorrect: false, rationale: 'Salience refers to the importance a person gives to the worker role relative to other life roles.' },
      { id: 'b', text: 'Vocational identity', isCorrect: false, rationale: 'Vocational identity, the clarity and stability of one\'s goals and interests, is associated with Holland.' },
      { id: 'c', text: 'Career adaptability', isCorrect: true, rationale: 'Super introduced career adaptability as the adult counterpart of career maturity; Savickas later made it central to career construction theory.' },
      { id: 'd', text: 'Career crystallizing', isCorrect: false, rationale: 'Crystallizing is a developmental task of the exploration stage, not an index of adult readiness.' },
    ],
    rationale: 'Career maturity, measured by tools such as the Career Development Inventory, compares a young person\'s coping with developmental tasks to that of peers. Because adult careers involve recycling and transitions, Super suggested career adaptability for adults, a concept Savickas expanded into the adapt-abilities of concern, control, curiosity and confidence.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Super\'s theory: career maturity and career adaptability' }],
  },
  {
    id: 'nce-s-cou-075',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'According to Anne Roe\'s theory, an adult who grew up in a cold, rejecting or neglectful family climate would be MOST likely to gravitate toward which kind of occupation?',
    options: [
      { id: 'a', text: 'Person-oriented fields such as service and business contact', isCorrect: false, rationale: 'Roe linked warm, accepting or overprotective climates, not cold ones, with orientation toward people.' },
      { id: 'b', text: 'Non-person-oriented fields such as technology and science', isCorrect: true, rationale: 'Roe proposed that avoidant (rejecting or neglecting) climates lead toward work that does not center on people.' },
      { id: 'c', text: 'Highly creative fields chosen to win approval from parents', isCorrect: false, rationale: 'Roe did not tie avoidant climates to approval-seeking creative work; arts and entertainment is a field, not this mechanism.' },
      { id: 'd', text: 'Any field at all, since family climate predicts only level', isCorrect: false, rationale: 'In Roe\'s model, family climate shapes orientation toward or away from people; level depends on ability and status factors.' },
    ],
    rationale: 'Roe classified occupations into eight fields and six levels and proposed that early parent-child relations (emotional concentration, avoidance or acceptance) create needs that steer people toward or away from person-oriented work. Research gave her theory limited support, but her field-and-level classification influenced later occupational systems.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Roe\'s personality theory of career choice: parent-child relations' }],
  },
  {
    id: 'nce-s-cou-076',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'easy',
    stem: 'A 14-year-old who once wanted to be an astronaut now talks about whether she has the grades and abilities for engineering and whether the work fits what she values. In Ginzberg\'s theory, she is in which period?',
    options: [
      { id: 'a', text: 'Fantasy period', isCorrect: false, rationale: 'The fantasy period (to about age 11) involves play-based choices made without regard to ability or reality.' },
      { id: 'b', text: 'Realistic period', isCorrect: false, rationale: 'The realistic period (about 17 into early adulthood) involves exploration, crystallization and specification of a choice.' },
      { id: 'c', text: 'Crystallization', isCorrect: false, rationale: 'Crystallization is a substage of the later realistic period, when a clear occupational pattern emerges.' },
      { id: 'd', text: 'Tentative period', isCorrect: true, rationale: 'The tentative period (about 11 to 17) moves through interest, capacity, values and transition substages.' },
    ],
    rationale: 'Ginzberg, Ginsburg, Axelrad and Herma described three periods: fantasy, tentative (interest, capacity, values, transition) and realistic (exploration, crystallization, specification). Ginzberg later revised the theory to view career choice as a lifelong, open-ended process rather than one fixed by early adulthood.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Ginzberg\'s developmental theory: fantasy, tentative and realistic periods' }],
  },
  {
    id: 'nce-s-cou-077',
    reviewNote: 'Gottfredson\'s 1996/2002 revision makes the order depend on how severe the compromise is; verify the key against the current Sharf wording.',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'A client must make a major compromise because her preferred occupations are not available locally. According to Gottfredson\'s theory of circumscription and compromise, which aspect of her self-concept is she likely to protect MOST when compromising?',
    options: [
      { id: 'a', text: 'Sextype, how suitable the job seems for her gender', isCorrect: true, rationale: 'Gottfredson proposed that sextype, the earliest and most core element to be circumscribed, is the last to be given up in major compromises.' },
      { id: 'b', text: 'Interest field, how well the work matches her likes', isCorrect: false, rationale: 'Interests develop later and are more peripheral, so they tend to be sacrificed before prestige or sextype in major compromises.' },
      { id: 'c', text: 'Prestige, the social standing of the occupation', isCorrect: false, rationale: 'Prestige is protected over interests but is given up before sextype when the compromise is severe.' },
      { id: 'd', text: 'Pay level, the salary that the job typically offers', isCorrect: false, rationale: 'Salary is not one of the self-concept dimensions in Gottfredson\'s model of circumscription and compromise.' },
    ],
    rationale: 'Gottfredson described circumscription in four stages: orientation to size and power, to sex roles, to social valuation and to the internal, unique self. Because sextype is incorporated earliest, it is the most protected aspect; in major compromises people tend to give up interest fit first, then prestige, and sextype last.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Gottfredson\'s theory of circumscription and compromise' }],
  },
  {
    id: 'nce-s-cou-078',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A counselor helps a client set a career goal, clarify her values, generate several alternatives and gather occupational information. In Krumboltz\'s social learning theory of career decision making, the counselor is building which factor?',
    options: [
      { id: 'a', text: 'Genetic endowment and special abilities', isCorrect: false, rationale: 'Genetic endowment covers inherited qualities such as physical traits and talents, which counseling does not build.' },
      { id: 'b', text: 'Environmental conditions and events', isCorrect: false, rationale: 'Environmental conditions, such as job markets and policies, are largely outside the individual\'s control.' },
      { id: 'c', text: 'Task-approach skills', isCorrect: true, rationale: 'Task-approach skills are the learned skills, such as goal setting, values clarification and information seeking, used to approach career tasks.' },
      { id: 'd', text: 'Associative learning experiences', isCorrect: false, rationale: 'Associative learning links neutral stimuli with positive or negative ones; it is not the set of decision skills described.' },
    ],
    rationale: 'Krumboltz identified four influences on career decisions: genetic endowment and special abilities, environmental conditions and events, learning experiences (instrumental and associative) and task-approach skills. Their interaction produces self-observation generalizations, worldview generalizations and the actions people take.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Krumboltz\'s social learning theory: task-approach skills' }],
  },
  {
    id: 'nce-s-cou-079',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A college senior knows her strengths and has researched several occupations, but each time she nears a choice she tells herself, "I always make the wrong decision," and stalls. In the cognitive information processing (CIP) approach, the counselor should focus FIRST on which domain of the pyramid?',
    options: [
      { id: 'a', text: 'Self-knowledge domain', isCorrect: false, rationale: 'She already knows her strengths; her difficulty is not a lack of self-knowledge.' },
      { id: 'b', text: 'Executive processing domain', isCorrect: true, rationale: 'Executive processing covers metacognitions such as self-talk and self-monitoring; her negative self-talk is blocking the process.' },
      { id: 'c', text: 'Occupational knowledge domain', isCorrect: false, rationale: 'She has already researched occupations, so information about options is not the main barrier.' },
      { id: 'd', text: 'Decision-making skills domain', isCorrect: false, rationale: 'The CASVE cycle may need work later, but the dysfunctional self-talk at the top of the pyramid is what stalls her.' },
    ],
    rationale: 'Peterson, Sampson, Reardon and Lenz describe a pyramid with knowledge domains (self and occupations) at the base, decision-making skills (the CASVE cycle: communication, analysis, synthesis, valuing, execution) in the middle and executive processing at the top. Negative career thoughts, measured by the Career Thoughts Inventory, operate at the executive level.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Cognitive information processing: pyramid and executive processing' }],
  },
  {
    id: 'nce-s-cou-080',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A first-generation college student is confident she can master the coursework for an engineering degree, but she doubts that the degree will lead to a good job for someone without family connections in the field. In social cognitive career theory, her doubt BEST reflects low:',
    options: [
      { id: 'a', text: 'Self-efficacy beliefs', isCorrect: false, rationale: 'Self-efficacy is belief in one\'s ability to perform; she is confident she can do the work.' },
      { id: 'b', text: 'Personal goals', isCorrect: false, rationale: 'Goals are intentions to pursue an activity or outcome; her doubt concerns expected results, not intentions.' },
      { id: 'c', text: 'Interest development', isCorrect: false, rationale: 'In SCCT interests grow from efficacy and outcome expectations; the stem describes a belief about results.' },
      { id: 'd', text: 'Outcome expectations', isCorrect: true, rationale: 'Outcome expectations are beliefs about the consequences of an action, such as whether a degree will pay off.' },
    ],
    rationale: 'Lent, Brown and Hackett\'s social cognitive career theory builds on Bandura and centers on self-efficacy, outcome expectations and personal goals. Contextual supports and barriers, such as lack of professional networks, shape these beliefs and help explain why capable people may avoid a field.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Social cognitive career theory: self-efficacy, outcome expectations and goals' }],
  },
  {
    id: 'nce-s-cou-081',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'An accountant consistently receives excellent performance reviews, but he tells his counselor that the job offers none of the autonomy or variety he values and he dreads going to work. In the theory of work adjustment, his situation is BEST described as:',
    options: [
      { id: 'a', text: 'high satisfactoriness and low satisfaction', isCorrect: true, rationale: 'His employer is pleased with his performance (satisfactoriness), but his own needs and values are not being met (satisfaction).' },
      { id: 'b', text: 'high satisfaction and low satisfactoriness', isCorrect: false, rationale: 'This reverses the terms; satisfaction is the worker\'s view of the job and satisfactoriness is the employer\'s view of the worker.' },
      { id: 'c', text: 'low satisfaction and low satisfactoriness', isCorrect: false, rationale: 'His excellent reviews show that the employer finds him satisfactory.' },
      { id: 'd', text: 'high satisfaction and high satisfactoriness', isCorrect: false, rationale: 'His dread and unmet values show that he is not satisfied with the job.' },
    ],
    rationale: 'Dawis and Lofquist\'s theory of work adjustment holds that tenure depends on correspondence between person and environment. Satisfaction reflects whether the job\'s reinforcers meet the worker\'s needs and values; satisfactoriness reflects whether the worker\'s abilities meet the job\'s requirements. Low satisfaction predicts that the worker may leave even when performance is strong.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Theory of work adjustment: satisfaction and satisfactoriness' }],
  },
  {
    id: 'nce-s-cou-082',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A 24-year-old has interests and options but says his parents should decide his career, and he puts off every decision he could make himself. In Savickas\'s career construction theory, which career adapt-ability is MOST in need of development?',
    options: [
      { id: 'a', text: 'Concern', isCorrect: false, rationale: 'Concern is orientation toward and planning for the future; the main problem described is lack of ownership of decisions.' },
      { id: 'b', text: 'Curiosity', isCorrect: false, rationale: 'Curiosity is exploring self and options; he already has interests and options to choose from.' },
      { id: 'c', text: 'Control', isCorrect: true, rationale: 'Control is taking personal responsibility for one\'s career; deferring decisions and indecision signal a control deficit.' },
      { id: 'd', text: 'Confidence', isCorrect: false, rationale: 'Confidence is belief in one\'s ability to solve problems; the stem points to handing decisions to others rather than self-doubt.' },
    ],
    rationale: 'Savickas identifies four career adapt-abilities: concern (future orientation), control (decisiveness and ownership), curiosity (exploration) and confidence (self-efficacy for problem solving). Career construction counseling also uses the Career Construction Interview to identify life themes that give meaning to career choices.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Savickas\'s career construction theory: career adapt-abilities' }],
  },
  {
    id: 'nce-s-cou-083',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'easy',
    stem: 'A counselor wants a free online database, sponsored by the U.S. Department of Labor, that replaced the Dictionary of Occupational Titles and describes occupations by tasks, skills, knowledge, work context and interest codes. Which resource fits this description?',
    options: [
      { id: 'a', text: 'Occupational Outlook Handbook', isCorrect: false, rationale: 'The Bureau of Labor Statistics handbook focuses on job outlook, pay and training, and it did not replace the DOT.' },
      { id: 'b', text: 'Occupational Information Network', isCorrect: true, rationale: 'O*NET replaced the DOT and describes occupations with detailed descriptors, including RIASEC interest profiles.' },
      { id: 'c', text: 'Standard Occupational Classification', isCorrect: false, rationale: 'The SOC is a federal coding system for classifying jobs in statistical data, not a descriptive career database.' },
      { id: 'd', text: 'Guide for Occupational Exploration', isCorrect: false, rationale: 'The GOE grouped occupations by interest area and was a DOT companion, not its replacement.' },
    ],
    rationale: 'O*NET, the Occupational Information Network, is the Department of Labor\'s primary source of occupational information and replaced the DOT. It links occupations to Holland codes and pairs with labor market information, such as the Occupational Outlook Handbook\'s projections and wage data.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Career counseling: occupational information sources (O*NET, OOH)' }],
  },
  // ------------------------------------------------------------ human development
  {
    id: 'nce-s-cou-084',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A 9-year-old spends his energy on school, sports and friendships with same-sex peers, and sexual interests seem quiet. In Freud\'s psychosexual theory, he is in which stage?',
    options: [
      { id: 'a', text: 'Phallic stage', isCorrect: false, rationale: 'The phallic stage (about 3 to 6) centers on the Oedipal conflict and identification with the same-sex parent.' },
      { id: 'b', text: 'Genital stage', isCorrect: false, rationale: 'The genital stage begins at puberty, when sexual impulses reawaken and turn toward mature relationships.' },
      { id: 'c', text: 'Anal stage', isCorrect: false, rationale: 'The anal stage (about 1 to 3) centers on toilet training and control.' },
      { id: 'd', text: 'Latency stage', isCorrect: true, rationale: 'In latency (about 6 to puberty) sexual drives are dormant and energy goes into skills, school and same-sex friendships.' },
    ],
    rationale: 'Freud\'s psychosexual stages are oral (birth to 1), anal (1 to 3), phallic (3 to 6), latency (6 to 11) and genital (adolescence). Erikson\'s industry vs. inferiority covers the same school-age years, with emphasis on competence rather than sexual drives.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Freud\'s psychosexual theory: latency stage' }],
  },
  {
    id: 'nce-s-cou-085',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A 19-year-old says he will take over his family\'s restaurant, as his parents always planned, and that he has never seriously considered any other path. In Marcia\'s framework, his identity status is:',
    options: [
      { id: 'a', text: 'Identity foreclosure', isCorrect: true, rationale: 'Foreclosure is commitment without exploration, often accepting goals and values chosen by parents.' },
      { id: 'b', text: 'Identity moratorium', isCorrect: false, rationale: 'Moratorium is active exploration without commitment yet; he has committed without exploring.' },
      { id: 'c', text: 'Identity achievement', isCorrect: false, rationale: 'Achievement is commitment that follows a period of exploration, which he has not had.' },
      { id: 'd', text: 'Identity diffusion', isCorrect: false, rationale: 'Diffusion is neither exploring nor committed; he holds a firm commitment.' },
    ],
    rationale: 'Marcia extended Erikson\'s identity stage by crossing two dimensions, exploration and commitment, to form four statuses: achievement (explored, committed), moratorium (exploring, not committed), foreclosure (committed, not explored) and diffusion (neither). Statuses can change over time, and foreclosure is not unhealthy in every cultural context.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Marcia\'s identity statuses' }],
  },
  {
    id: 'nce-s-cou-086',
    reviewNote: 'Levinson\'s period ages are approximate; confirm the midlife transition is given as about 40 to 45.',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: 'A 42-year-old architect is questioning whether the youthful vision he built his career around is worth pursuing, reappraising his marriage and wondering what legacy he will leave. In Levinson\'s seasons of life, he is MOST likely in the:',
    options: [
      { id: 'a', text: 'early adult transition', isCorrect: false, rationale: 'The early adult transition (about 17 to 22) involves leaving adolescence and forming a first sense of the Dream.' },
      { id: 'b', text: 'midlife transition', isCorrect: true, rationale: 'The midlife transition (about 40 to 45) involves reappraising the Dream and the life structure built in early adulthood.' },
      { id: 'c', text: 'age 30 transition', isCorrect: false, rationale: 'The age 30 transition (about 28 to 33) involves adjusting the first adult life structure, not midlife reappraisal.' },
      { id: 'd', text: 'late adult transition', isCorrect: false, rationale: 'The late adult transition (about 60 to 65) involves facing aging and moving into late adulthood.' },
    ],
    rationale: 'Levinson described adulthood as alternating periods of building a life structure and transitions that question it. Key concepts include the Dream, a vision of one\'s adult future, and the mentor; at the midlife transition, people reappraise the Dream and rework the polarities of young-old, destruction-creation, masculine-feminine and attachment-separateness.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Levinson\'s seasons of life: the midlife transition' }],
  },
  {
    id: 'nce-s-cou-087',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'hard',
    stem: 'An 8-year-old\'s mother is moved to night shifts by her employer, and the child now spends evenings with less supervision and less help with homework. The child has never been to the workplace. In Bronfenbrenner\'s ecological systems theory, the employer\'s decision operates at which level?',
    options: [
      { id: 'a', text: 'Microsystem', isCorrect: false, rationale: 'The microsystem includes settings the child directly takes part in, such as home and school.' },
      { id: 'b', text: 'Mesosystem', isCorrect: false, rationale: 'The mesosystem is the connections between the child\'s microsystems, such as home-school links.' },
      { id: 'c', text: 'Exosystem', isCorrect: true, rationale: 'The exosystem includes settings the child does not take part in, such as a parent\'s workplace, that still affect the child.' },
      { id: 'd', text: 'Macrosystem', isCorrect: false, rationale: 'The macrosystem is the broad cultural values, laws and customs that shape all the other levels.' },
    ],
    rationale: 'Bronfenbrenner nested the child within the microsystem, mesosystem, exosystem and macrosystem, with the chronosystem adding change over time. A parent\'s workplace policy is a classic exosystem influence: it shapes the child\'s daily life even though the child never enters that setting.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Bronfenbrenner\'s ecological systems theory: the exosystem' }],
  },
  {
    id: 'nce-s-cou-088',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A tutor gives a first-grader step-by-step hints on a puzzle he cannot yet solve alone, then gradually withdraws the hints as he becomes able to solve it himself. This adjustment of support is BEST described as:',
    options: [
      { id: 'a', text: 'Accommodation', isCorrect: false, rationale: 'Accommodation is Piaget\'s term for changing a mental scheme to fit new information.' },
      { id: 'b', text: 'Private speech', isCorrect: false, rationale: 'Private speech is a child\'s self-directed talk used to guide thinking, not the adult\'s support.' },
      { id: 'c', text: 'Centration', isCorrect: false, rationale: 'Centration is the preoperational tendency to focus on one aspect of a situation.' },
      { id: 'd', text: 'Scaffolding', isCorrect: true, rationale: 'Scaffolding adjusts the level of support to the child\'s current performance and fades it as competence grows.' },
    ],
    rationale: 'Vygotsky\'s zone of proximal development is the range of tasks a child cannot yet do alone but can do with help from a more skilled partner. Scaffolding, a term introduced by Wood, Bruner and Ross and applied to Vygotsky\'s theory, describes how that help is fine-tuned and withdrawn as the child masters the task.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Vygotsky\'s sociocultural theory: zone of proximal development and scaffolding' }],
  },
  {
    id: 'nce-s-cou-089',
    reviewNote: 'Confirm Gilligan\'s level names (orientation to individual survival, goodness as self-sacrifice, morality of nonviolence) as given in Berk.',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'hard',
    stem: 'A woman who has long put everyone else\'s needs ahead of her own comes to believe that caring responsibly must include caring for herself, and that avoiding harm applies to her as well as to others. In Gilligan\'s ethic of care, this reasoning BEST reflects which level?',
    options: [
      { id: 'a', text: 'Morality of nonviolence', isCorrect: true, rationale: 'The third level integrates care for self and others, with a principle of not hurting anyone, including oneself.' },
      { id: 'b', text: 'Goodness as self-sacrifice', isCorrect: false, rationale: 'This second level equates goodness with meeting others\' needs at one\'s own expense, which she is moving beyond.' },
      { id: 'c', text: 'Orientation to survival', isCorrect: false, rationale: 'The first level focuses on the self and its survival, without concern for responsibility to others.' },
      { id: 'd', text: 'Social contract reasoning', isCorrect: false, rationale: 'Social contract reasoning is Kohlberg\'s stage 5, based on justice and rights rather than care.' },
    ],
    rationale: 'Gilligan argued that Kohlberg\'s justice-based stages underrepresented an ethic of care. Her levels move from orientation to individual survival, through goodness as self-sacrifice, to the morality of nonviolence, with transitions from selfishness to responsibility and from goodness to truth about one\'s own needs.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Gilligan\'s ethic of care and critique of Kohlberg' }],
  },
  {
    id: 'nce-s-cou-090',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: 'A school counselor is planning supports for children growing up with poverty and parental substance use. Longitudinal research on resilience, such as Werner and Smith\'s Kauai study, MOST consistently identifies which protective factor?',
    options: [
      { id: 'a', text: 'Avoiding all stressful experiences throughout early childhood', isCorrect: false, rationale: 'Resilience develops through coping with manageable stress; complete avoidance of stress is neither possible nor protective.' },
      { id: 'b', text: 'A warm, stable relationship with at least one caring adult', isCorrect: true, rationale: 'A close bond with a competent, caring adult, who need not be a parent, is among the most consistent protective factors.' },
      { id: 'c', text: 'An above-average IQ score as measured in the preschool years', isCorrect: false, rationale: 'Good cognitive skills can help, but a high IQ alone is not the most consistent protective factor.' },
      { id: 'd', text: 'Living in a family that has no history of mental illness', isCorrect: false, rationale: 'This describes the absence of a risk factor rather than a protective factor that buffers existing risk.' },
    ],
    rationale: 'Resilience research identifies protective factors at several levels: personal traits such as an easygoing temperament, a warm relationship with a caring adult, and community supports such as schools and mentors. Werner and Smith found that high-risk children who thrived usually had at least one stable, supportive adult in their lives.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Resilience: protective factors in high-risk children' }],
  },
];
