// NCE seed — counseling domain, batch 4 (group, career, development,
// multicultural, play therapy, attachment). Ids nce-s-cou-211 … nce-s-cou-240.
module.exports = [
  // ── GROUP ────────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-211',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'A counselor holds individual pre-group interviews for a 12-week interpersonal process group. She spends each interview asking about symptoms, history and current stressors, then tells applicants whether they have been accepted. Her supervisor says an essential element of screening is missing. Which element is it?',
    options: [
      { id: 'a', text: 'Requiring a formal DSM-5-TR diagnosis before any applicant joins', isCorrect: false, rationale: 'A diagnosis is not required for most counseling groups, and it says little about fit with a particular group.' },
      { id: 'b', text: 'Letting applicants ask questions and judge whether the group fits', isCorrect: true, rationale: 'Screening is a two-way process: applicants learn about the group and leader and decide whether it meets their needs.' },
      { id: 'c', text: 'Ranking applicants by a personality inventory to pick the strongest group', isCorrect: false, rationale: 'Selection rests on fit with group goals and readiness, not on ranking applicants by a test score.' },
      { id: 'd', text: 'Asking applicants to agree to meet socially with members between sessions', isCorrect: false, rationale: 'Outside socializing is not encouraged in therapy groups and is not a screening goal.' },
    ],
    rationale: 'Pre-group screening selects members whose needs and goals fit the group, who will not impede the process and whose well-being will not be jeopardized by it. It is also a chance for prospective members to interview the leader, learn about the group\'s purpose and procedures and decide for themselves whether to join. A one-sided interview that only gathers clinical data misses that mutual decision.',
    references: [
      { source: 'ASGW Best Practice Guidelines', detail: 'Planning: group and member preparation (screening and orientation)' },
      { source: 'ACA Code of Ethics', detail: 'A.9.a Screening' },
    ],
  },
  {
    id: 'nce-s-cou-212',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A counselor is preparing the informed consent discussion for a new adult therapy group. Which statement BEST belongs in that discussion?',
    options: [
      { id: 'a', text: 'The leader guarantees that every member will keep what is said confidential.', isCorrect: false, rationale: 'Leaders cannot guarantee that other members will keep confidentiality, and consent must state this limit.' },
      { id: 'b', text: 'Once you join, you are expected to attend until the final group session ends.', isCorrect: false, rationale: 'Members keep the right to leave; consent explains how to leave, not that leaving is barred.' },
      { id: 'c', text: 'You may feel pressure to share, but you decide what and how much to disclose.', isCorrect: true, rationale: 'Naming the risk of group pressure and affirming the member\'s control over disclosure is core group consent content.' },
      { id: 'd', text: 'The leader will decide how much personal material each member shares weekly.', isCorrect: false, rationale: 'Members, not the leader, decide what they disclose; leaders protect members from coercion.' },
    ],
    rationale: 'Informed consent for a group covers its purpose, procedures and leader qualifications, the limits of confidentiality among members, and the psychological risks of participation, such as pressure to disclose, confrontation and changes that affect outside relationships. Members are told that they control their own disclosures and how to leave the group if they choose.',
    references: [
      { source: 'ASGW Best Practice Guidelines', detail: 'Planning: group and member preparation (informed consent)' },
      { source: 'ACA Code of Ethics', detail: 'A.2.b Types of Information Needed; B.4.a Group Work' },
    ],
  },
  {
    id: 'nce-s-cou-213',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'A counselor in a community clinic is planning an open-ended outpatient interpersonal therapy group for adults. Which plan for size and session length is MOST consistent with Yalom\'s recommendations?',
    options: [
      { id: 'a', text: 'About 3 members, meeting weekly for 30 minutes', isCorrect: false, rationale: 'Three members is too few for rich interaction, and 30 minutes leaves no time to warm up and work.' },
      { id: 'b', text: 'About 15 members, meeting weekly for 45 minutes', isCorrect: false, rationale: 'Fifteen members is too many for interaction-focused work, and 45 minutes is too short.' },
      { id: 'c', text: 'About 12 members, meeting weekly for 3 hours', isCorrect: false, rationale: 'Twelve is above the usual range, and sessions beyond about 2 hours tend to tire members.' },
      { id: 'd', text: 'About 7 members, weekly for 80-90 minutes', isCorrect: true, rationale: 'Yalom places the ideal interactional group near 7 or 8 members, with sessions of about 80 to 90 minutes.' },
    ],
    rationale: 'Yalom suggests that an interactional therapy group works best with about 7 or 8 members, within an acceptable range of roughly 5 to 10. Sessions need time for a warm-up period and for working through themes, so most groups meet for 80 to 90 minutes; beyond about 2 hours members tend to become weary. Groups for children or for highly impaired inpatients are usually smaller and shorter.',
    references: [
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Creation of the group: group size and duration of meetings' },
    ],
  },
  {
    id: 'nce-s-cou-214',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'In the sixth session of a process group, members keep switching topics whenever anyone mentions loneliness. The leader is considering a self-disclosure. Which disclosure is MOST consistent with Yalom\'s guidance on leader transparency?',
    options: [
      { id: 'a', text: '"I went through a lonely divorce years ago, so let me tell you how I got through it."', isCorrect: false, rationale: 'A detailed personal history shifts the focus to the leader and rarely helps members with their own here-and-now work.' },
      { id: 'b', text: '"I feel a bit shut out as we keep changing topics. I wonder what others feel now."', isCorrect: true, rationale: 'A brief here-and-now disclosure of the leader\'s reaction models openness and invites members to examine the process.' },
      { id: 'c', text: '"I have struggles of my own lately, so I am one more member of the group tonight."', isCorrect: false, rationale: 'Presenting oneself as a member blurs the leader role and burdens the group with the leader\'s problems.' },
      { id: 'd', text: '"I keep my reactions private so that you can project onto me more freely here."', isCorrect: false, rationale: 'A blank-screen stance is not what Yalom advises; judicious transparency aids the interactional group.' },
    ],
    rationale: 'Yalom favors leader self-disclosure that is focused on the here-and-now and offered in the service of members\' work, such as sharing a reaction to what is happening in the room. Lengthy disclosure of the leader\'s past or current personal problems tends to redirect attention, burden members and blur the leader role, while total opacity deprives the group of useful modeling.',
    references: [
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'The therapist: transparency and the use of the self' },
    ],
  },
  {
    id: 'nce-s-cou-215',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: 'Near the end of a co-led depression group, a member quietly says she has stockpiled pills and "probably won\'t be around next week." Other members look stunned. What should the leaders do?',
    options: [
      { id: 'a', text: 'Note her comment and plan to raise it with her at the start of next week\'s session', isCorrect: false, rationale: 'Waiting a week ignores an imminent risk statement; risk must be assessed immediately.' },
      { id: 'b', text: 'Ask members to share reasons to live so the group can talk her out of the plan now', isCorrect: false, rationale: 'Peer persuasion is not a risk assessment and puts members in a role they cannot safely fill.' },
      { id: 'c', text: 'Remove her from the group and give her a referral for individual counseling instead', isCorrect: false, rationale: 'Removal without assessing and managing her immediate safety abandons her at a moment of risk.' },
      { id: 'd', text: 'Acknowledge it, have one leader assess her risk privately now, and help the group process', isCorrect: true, rationale: 'Her safety comes first through an immediate individual assessment, while the other leader helps members with their reactions.' },
    ],
    rationale: 'A disclosure of suicidal intent during group calls for immediate action. The leaders acknowledge what was said, one leader (or the leader right after the group) conducts a private risk assessment and safety planning, and the group is helped to process its reactions now and in later sessions. Co-leadership makes it possible to attend to the individual without abandoning the group.',
    references: [
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Group work: handling a member in crisis; co-leadership' },
      { source: 'C-SSRS', detail: 'Suicidal ideation with intent and plan: immediate risk assessment' },
    ],
    reviewNote: 'Best-practice consensus rather than a single named standard; SME to confirm the Gladding locator.',
  },
  {
    id: 'nce-s-cou-216',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'Three members of an interpersonal group have begun meeting for coffee before each session. In group they sit together, trade knowing glances and fall silent when one of them is challenged. Following Yalom, how should the leader BEST respond?',
    options: [
      { id: 'a', text: 'Ban all contact between members outside of group sessions for the rest of the group', isCorrect: false, rationale: 'Outside contact is not itself the problem, and a ban tends to drive it underground.' },
      { id: 'b', text: 'Invite the members to talk openly in group about their outside meetings and their effect', isCorrect: true, rationale: 'Bringing the subgroup into the open turns a threat to cohesion into here-and-now material.' },
      { id: 'c', text: 'Meet privately with the three members and ask them to sit apart from each other in group', isCorrect: false, rationale: 'A private meeting adds secrecy and leaves the rest of the group out of the work.' },
      { id: 'd', text: 'Let the subgroup run its course, since cohesive pairs tend to strengthen the whole group', isCorrect: false, rationale: 'Secret subgroups whose loyalty outweighs the group\'s goals tend to undermine cohesion.' },
    ],
    rationale: 'Subgrouping becomes destructive when members\' loyalty to the subgroup outweighs their commitment to the group\'s goals and when what happens outside stays secret. Yalom advises that extragroup contact be brought back into the group and discussed openly, so that it can be understood rather than forbidden.',
    references: [
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Problem group members and subgrouping; extragroup socializing' },
    ],
  },
  {
    id: 'nce-s-cou-217',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: 'In a long-term group, Theo bristles at every comment from Ines, an assertive older member, and accuses her of "always looking down on me," though others see her remarks as mild. He later realizes she reminds him of his critical older sister. Drawing on Sullivan, Yalom calls Theo\'s distorted perception of Ines:',
    options: [
      { id: 'a', text: 'Parataxic distortion', isCorrect: true, rationale: 'Parataxic distortion is perceiving another person through the lens of past relationships rather than as they are.' },
      { id: 'b', text: 'Consensual validation', isCorrect: false, rationale: 'Consensual validation is the corrective process of checking one\'s view against others\' views, not the distortion.' },
      { id: 'c', text: 'Projective identification', isCorrect: false, rationale: 'This object relations term involves inducing one\'s projected feelings in another; Yalom uses Sullivan\'s term here.' },
      { id: 'd', text: 'Family recapitulation', isCorrect: false, rationale: 'Corrective recapitulation of the family group is a therapeutic factor, not the term for one member\'s distortion of another.' },
    ],
    rationale: 'Yalom borrows Sullivan\'s term parataxic distortion for the tendency to perceive others in the group through the template of earlier relationships, a form of transference that can occur between members as well as toward the leader. Feedback from other members, a process Sullivan called consensual validation, helps the member see the distortion and test it against reality.',
    references: [
      { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Interpersonal learning: parataxic distortion and consensual validation' },
    ],
  },
  {
    id: 'nce-s-cou-218',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A counselor wants to know whether her 10-week anxiety management group actually reduced members\' symptoms. Which evaluation approach BEST answers that question?',
    options: [
      { id: 'a', text: 'Hand out a satisfaction survey at the last session of the group', isCorrect: false, rationale: 'Satisfaction tells whether members liked the group, not whether symptoms changed.' },
      { id: 'b', text: 'Record her own impressions of each member\'s progress each week', isCorrect: false, rationale: 'Leader impressions are subjective and open to bias; they do not measure symptom change.' },
      { id: 'c', text: 'Count how many members attended at least eight of ten sessions', isCorrect: false, rationale: 'Attendance shows engagement, not whether the group reduced symptoms.' },
      { id: 'd', text: 'Give a standardized anxiety measure before and after the group', isCorrect: true, rationale: 'A valid symptom measure given at pre- and post-test directly assesses change in the target outcome.' },
    ],
    rationale: 'Outcome evaluation asks whether the group achieved its goals. Administering a reliable, valid measure of the target problem before and after the group (and, ideally, at points during it) provides evidence of change; satisfaction, attendance and leader impressions are process indicators, not outcome data.',
    references: [
      { source: 'ASGW Best Practice Guidelines', detail: 'Performing and processing: evaluation of group outcomes' },
      { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Program evaluation: outcome evaluation with pretest-posttest measures' },
    ],
  },
  {
    id: 'nce-s-cou-219',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'A counselor is launching a video-based support group for caregivers who live across her state. Which step is MOST specific to the safe running of this telehealth group?',
    options: [
      { id: 'a', text: 'Ask members to keep their cameras turned off to protect each other\'s identities', isCorrect: false, rationale: 'Cameras off removes nonverbal cues and makes it harder to verify who is present and to monitor distress.' },
      { id: 'b', text: 'Skip pre-group screening, since online members can simply log off if it is a poor fit', isCorrect: false, rationale: 'Screening is as necessary for online groups as for in-person groups.' },
      { id: 'c', text: 'Get each member\'s location and emergency contact and set privacy rules for joining', isCorrect: true, rationale: 'Knowing where members are, having emergency contacts and agreeing on privacy and no-recording rules address telehealth risks.' },
      { id: 'd', text: 'Use any free video app members already know, since familiarity improves attendance', isCorrect: false, rationale: 'Platforms must meet security and privacy requirements; convenience alone is not sufficient.' },
    ],
    rationale: 'Distance group work adds risks: members may join from places where others can overhear, could record sessions, and may be far from the counselor in a crisis. Counselors address these in informed consent and planning by verifying identity and location, collecting emergency contacts, using secure platforms and setting norms such as joining from a private space and not recording.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'H.2.a Informed Consent and Disclosure; H.3 Client Verification' },
      { source: 'ASGW Best Practice Guidelines', detail: 'Planning: trends and technological changes' },
    ],
  },

  // ── CAREER ───────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-220',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'For her first months as a hospital social worker, Amina followed every unit norm and sought her colleagues\' approval. Now, secure in the role, she is pushing the team to adopt her ideas for discharge planning and asserting her own views. In Tiedeman and O\'Hara\'s decision-making model, Amina is in which stage?',
    options: [
      { id: 'a', text: 'Crystallization', isCorrect: false, rationale: 'Crystallization is part of anticipation, when options are clarified before any choice is made.' },
      { id: 'b', text: 'Induction', isCorrect: false, rationale: 'Induction describes her earlier months, when she sought acceptance and conformed to the group.' },
      { id: 'c', text: 'Reformation', isCorrect: true, rationale: 'In reformation the person, now accepted, acts assertively to change the group toward her own views.' },
      { id: 'd', text: 'Integration', isCorrect: false, rationale: 'Integration follows reformation, when individual and group goals are balanced into a stable sense of self.' },
    ],
    rationale: 'Tiedeman and O\'Hara divided career decision making into anticipation (exploration, crystallization, choice and clarification) and implementation or adjustment (induction, reformation and integration). In induction the new member seeks acceptance; in reformation she becomes assertive and tries to change the group; in integration she achieves a balance between her own goals and the group\'s.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Tiedeman and O\'Hara: anticipation and implementation stages of decision making' },
    ],
  },
  {
    id: 'nce-s-cou-221',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A counselor uses Krumboltz\'s happenstance learning theory with a 30-year-old who wants to "figure out the one right career." According to this theory, how should the success of their counseling be judged?',
    options: [
      { id: 'a', text: 'By whether the client names one final occupation by the last session', isCorrect: false, rationale: 'The theory explicitly rejects a single career decision as the goal of counseling.' },
      { id: 'b', text: 'By the match between the client\'s interest code and a chosen field', isCorrect: false, rationale: 'Matching traits to occupations is a trait-factor goal; the theory uses assessments to spark learning.' },
      { id: 'c', text: 'By what the client accomplishes in the real world outside sessions', isCorrect: true, rationale: 'Krumboltz held that success is assessed by the actions and learning the client achieves outside counseling.' },
      { id: 'd', text: 'By how certain the client reports feeling about future job choices', isCorrect: false, rationale: 'Certainty is not the aim; Krumboltz reframed open-mindedness and indecision as useful.' },
    ],
    rationale: 'Krumboltz\'s happenstance learning theory (2009) holds that the goal of career counseling is to help clients learn to take actions toward more satisfying lives, not to make a single decision. Assessments stimulate learning rather than match traits to jobs, clients learn exploratory actions that generate beneficial unplanned events, and success is judged by what the client accomplishes in the real world.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Krumboltz: happenstance learning theory and its four propositions' },
    ],
  },
  {
    id: 'nce-s-cou-222',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A 47-year-old engineer has cut back his hours to care for his aging father, coaches his daughter\'s soccer team and is taking an evening course. He says work "matters less right now than it did five years ago." Which concept from Super\'s life-career rainbow BEST describes this?',
    options: [
      { id: 'a', text: 'Role salience, the shifting weight of concurrent life roles', isCorrect: true, rationale: 'The rainbow shows several roles held at once across theaters, with their importance changing over the life span.' },
      { id: 'b', text: 'Career maturity, readiness for age-appropriate career tasks', isCorrect: false, rationale: 'Career maturity concerns readiness for developmental tasks, mainly in adolescence, not the balance of life roles.' },
      { id: 'c', text: 'Circumscription, the narrowing of acceptable occupations', isCorrect: false, rationale: 'Circumscription is Gottfredson\'s concept of eliminating occupations by sex type and prestige.' },
      { id: 'd', text: 'Congruence, the fit between personality and work setting', isCorrect: false, rationale: 'Congruence is Holland\'s concept of person-environment fit, not the weight of life roles.' },
    ],
    rationale: 'Super\'s life-career rainbow pictures the life span as arcs of roles such as child, student, leisurite, citizen, worker and homemaker, played in theaters such as home, community, school and workplace. Several roles are active at once, and their salience rises and falls over time, so a worker role can recede while caregiving, parenting and student roles grow.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Super: life-career rainbow, life roles and role salience' },
    ],
  },
  {
    id: 'nce-s-cou-223',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'easy',
    stem: 'A college sophomore scores very low on the Vocational Identity scale of Holland\'s My Vocational Situation. What does this score MOST likely indicate?',
    options: [
      { id: 'a', text: 'Her interests clash with the setting of her current campus job', isCorrect: false, rationale: 'This describes incongruence between person and environment, not vocational identity.' },
      { id: 'b', text: 'Her picture of her goals, interests and talents is unclear', isCorrect: true, rationale: 'Holland defined vocational identity as having a clear and stable picture of one\'s goals, interests and talents.' },
      { id: 'c', text: 'She has a highly consistent code of adjacent types on the hexagon', isCorrect: false, rationale: 'Consistency describes how closely related a person\'s top types are, a different Holland concept.' },
      { id: 'd', text: 'She doubts her ability to finish the math courses for her major', isCorrect: false, rationale: 'Doubts about specific tasks reflect self-efficacy, a social cognitive career theory construct.' },
    ],
    rationale: 'Holland defined vocational identity as the possession of a clear and stable picture of one\'s goals, interests and talents. The My Vocational Situation measures vocational identity along with needs for occupational information and perceived barriers; low identity scores suggest a client who would benefit from clarifying self-knowledge before choosing among options.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Holland: vocational identity and the My Vocational Situation' },
    ],
  },
  {
    id: 'nce-s-cou-224',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'A counselor follows Fouad and Bingham\'s culturally appropriate career counseling model with a Somali American client. They have built a culturally appropriate relationship and identified her career issues. What is the NEXT step in the model?',
    options: [
      { id: 'a', text: 'Choose and apply culturally appropriate interventions', isCorrect: false, rationale: 'Interventions come after the impact of culture has been assessed and goals are set.' },
      { id: 'b', text: 'Set career counseling goals with the client together', isCorrect: false, rationale: 'Goal setting follows the assessment of cultural variables so that goals reflect them.' },
      { id: 'c', text: 'Support decision making, then plan implementation', isCorrect: false, rationale: 'Decision making and implementation are the final steps of the model.' },
      { id: 'd', text: 'Assess the impact of cultural variables on the issues', isCorrect: true, rationale: 'After the relationship and the career issues, the model calls for assessing how cultural variables shape those issues.' },
    ],
    rationale: 'Fouad and Bingham\'s culturally appropriate career counseling model has seven steps: establish a culturally appropriate relationship, identify career issues, assess the impact of cultural variables on those issues, set counseling goals, make culturally appropriate interventions, support decision making, and implement and follow up. Placing cultural assessment before goals keeps goals and interventions grounded in the client\'s worldview.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Career counseling with culturally diverse clients: Fouad and Bingham\'s culturally appropriate model' },
    ],
    reviewNote: 'Seven-step sequence from Fouad & Bingham (1995); SME to confirm that Sharf (6th ed.) presents the model and its step order.',
  },
  {
    id: 'nce-s-cou-225',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'For more than a year a client has swung back and forth between staying in nursing and returning to art school, each time convincing herself the other path is right. In Pryor and Bright\'s chaos theory of careers, this pattern reflects which attractor?',
    options: [
      { id: 'a', text: 'Point attractor', isCorrect: false, rationale: 'A point attractor is movement toward a single fixed goal, not oscillation between two.' },
      { id: 'b', text: 'Torus attractor', isCorrect: false, rationale: 'A torus attractor is a complex but repeating routine that screens out change and chance.' },
      { id: 'c', text: 'Pendulum attractor', isCorrect: true, rationale: 'A pendulum attractor describes swinging between two options or roles without resolution.' },
      { id: 'd', text: 'Strange attractor', isCorrect: false, rationale: 'The strange attractor is an open system that embraces complexity and chance, the pattern the theory favors.' },
    ],
    rationale: 'Pryor and Bright view careers as complex, dynamic systems shaped by nonlinear change and chance. They describe closed-system attractors (point, pendulum and torus) that represent attempts to control and simplify, and the strange attractor, an open-system pattern that combines stability with openness to change. A pendulum attractor is oscillation between two poles, such as two occupations.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Chaos theory of careers (Pryor and Bright): attractors' },
    ],
    reviewNote: 'SME to confirm the chaos theory of careers is covered in the cited Sharf edition; attractor definitions follow Pryor & Bright (2011).',
  },
  {
    id: 'nce-s-cou-226',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'Duc, 18, tells his counselor he will study pharmacy because his parents and grandparents decided it is best for the family, and he seems at ease with this. His family holds strongly collective social values. From the standpoint of Brown\'s values-based theory, how should the counselor view this choice?',
    options: [
      { id: 'a', text: 'As identity foreclosure that should be challenged so he chooses alone', isCorrect: false, rationale: 'Labeling a values-consistent family decision as pathology imposes an individualist norm.' },
      { id: 'b', text: 'As a sign of low career maturity needing decision-skills training', isCorrect: false, rationale: 'Deferring to family is consistent with collective values, not a deficit in maturity.' },
      { id: 'c', text: 'As secondary, since interests drive choice more than values do', isCorrect: false, rationale: 'Brown placed values, not interests, at the center of occupational choice.' },
      { id: 'd', text: 'As consistent with collective values, where family shares the choice', isCorrect: true, rationale: 'Brown proposed that people with collective social values often make career decisions with, or in deference to, the family.' },
    ],
    rationale: 'Brown\'s values-based theory treats work values as central to occupational choice and recognizes that cultural values shape the decision process itself. People holding individualistic values tend to decide independently, while those with collective values tend to involve or defer to family or group. Counselors are urged to understand and work within the client\'s value system rather than impose an individualistic model.',
    references: [
      { source: 'Sharf (Career Development Theory)', detail: 'Brown\'s values-based theory of occupational choice: cultural and work values' },
    ],
  },
  {
    id: 'nce-s-cou-227',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'A counselor is redesigning a career-choice workshop and wants to include the components that Brown and Ryan Krane\'s meta-analysis linked to the largest effects. Which set should she build in?',
    options: [
      { id: 'a', text: 'Written exercises, individual feedback, work information, modeling and support building', isCorrect: true, rationale: 'These are the five critical ingredients Brown and Ryan Krane identified in career choice interventions.' },
      { id: 'b', text: 'Aptitude testing, computer guidance alone, job fairs, résumé drills and interview practice', isCorrect: false, rationale: 'Computer guidance used alone showed smaller effects, and the rest are not among the identified ingredients.' },
      { id: 'c', text: 'Group discussion, relaxation training, dream analysis, personality typing and goal rewards', isCorrect: false, rationale: 'These components were not among the ingredients linked to stronger career choice outcomes.' },
      { id: 'd', text: 'Interest inventories, self-scored results, labor statistics, cold calls and job shadowing', isCorrect: false, rationale: 'Self-interpreted inventories lack the individualized interpretation and feedback found to matter.' },
    ],
    rationale: 'Brown and Ryan Krane (2000) found five critical ingredients in effective career choice interventions: written exercises, individualized interpretation and feedback, information about the world of work, modeling opportunities, and attention to building support for choices in the client\'s social network. Interventions including more of these ingredients produced larger effects.',
    references: [
      { source: 'Brown & Ryan Krane (Career Interventions)', detail: 'Five critical ingredients of effective career interventions' },
      { source: 'Sharf (Career Development Theory)', detail: 'Effectiveness of career counseling: critical ingredients (Brown & Ryan Krane, 2000)' },
    ],
  },

  // ── HUMAN DEVELOPMENT ────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-228',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'Parents of a 16-year-old worry because over one school year he has tried out different friend groups, clothing styles, music and political views. He is otherwise doing well. From Erikson\'s perspective, how should the counselor understand this?',
    options: [
      { id: 'a', text: 'As normal exploration within the identity vs. role confusion stage', isCorrect: true, rationale: 'Erikson saw adolescent experimentation with roles and values as a healthy part of forming an identity.' },
      { id: 'b', text: 'As a delayed crisis of the industry vs. inferiority stage of school age', isCorrect: false, rationale: 'Industry vs. inferiority concerns mastery and competence in middle childhood, not trying out identities.' },
      { id: 'c', text: 'As an early sign of the intimacy vs. isolation crisis of young adults', isCorrect: false, rationale: 'Intimacy vs. isolation follows identity and centers on close committed relationships.' },
      { id: 'd', text: 'As a warning sign that he lacks a self and needs intensive treatment', isCorrect: false, rationale: 'Role experimentation in a well-functioning teen is expected, not a sign of disorder.' },
    ],
    rationale: 'In Erikson\'s fifth stage, identity vs. role confusion, adolescents try out roles, values and commitments as they work toward a coherent sense of who they are. Erikson described a psychosocial moratorium, a period of permitted experimentation, as healthy; role confusion becomes a concern only when the young person cannot form any stable sense of self.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Adolescence: Erikson\'s identity vs. role confusion' },
    ],
  },
  {
    id: 'nce-s-cou-229',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'While talking with her grandmother on the phone, a 4-year-old nods in answer to questions and holds up a new toy, saying, "Look at this one!" Which feature of Piaget\'s preoperational stage does this show?',
    options: [
      { id: 'a', text: 'Animistic thinking', isCorrect: false, rationale: 'Animism is giving lifelike qualities to objects, which is not shown here.' },
      { id: 'b', text: 'Egocentrism', isCorrect: true, rationale: 'She assumes her grandmother sees what she sees, failing to take another\'s viewpoint.' },
      { id: 'c', text: 'Lack of object permanence', isCorrect: false, rationale: 'Object permanence develops in the sensorimotor stage and is not what this shows.' },
      { id: 'd', text: 'Failure to conserve', isCorrect: false, rationale: 'Conservation concerns amounts that stay the same despite changes in appearance.' },
    ],
    rationale: 'Piaget described preoperational children as egocentric: they have difficulty distinguishing others\' viewpoints from their own, as in the three-mountains task. A child who nods on the phone or holds up a toy for a listener who cannot see it assumes the other person shares her perspective.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Piaget\'s preoperational stage: egocentrism and the three-mountains problem' },
    ],
  },
  {
    id: 'nce-s-cou-230',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: 'A woman resolves a moral dilemma by focusing on preserving relationships and avoiding harm to everyone involved. Under Kohlberg\'s scoring she would likely be placed at Stage 3, below the postconventional level. Which critique, associated with Carol Gilligan, addresses this?',
    options: [
      { id: 'a', text: 'Kohlberg ignored the role of logical thought in moral judgment', isCorrect: false, rationale: 'Kohlberg built his stages on Piaget\'s account of cognitive development; logic was central.' },
      { id: 'b', text: 'Kohlberg\'s stages describe behavior rather than moral reasoning', isCorrect: false, rationale: 'Kohlberg studied reasoning about dilemmas, not behavior, and Gilligan did not argue otherwise.' },
      { id: 'c', text: 'Kohlberg built a justice bias from male samples, undervaluing care', isCorrect: true, rationale: 'Gilligan argued that a theory based on males privileged justice and rated an ethic of care as less mature.' },
      { id: 'd', text: 'Kohlberg\'s stages must be completed fully before anyone advances', isCorrect: false, rationale: 'This restates Kohlberg\'s invariant sequence; it is not Gilligan\'s critique.' },
    ],
    rationale: 'Kohlberg\'s stages were derived from longitudinal interviews with boys and place reasoning based on abstract justice and rights at the postconventional level. Gilligan argued that this framework undervalues an ethic of care, which emphasizes relationships and responsibility, so care-oriented reasoning is often scored at Stage 3. Later research found smaller gender differences than Gilligan proposed, but the critique broadened the study of moral reasoning.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Moral development: Kohlberg\'s theory and Gilligan\'s ethic of care' },
    ],
  },
  {
    id: 'nce-s-cou-231',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: 'Parents of a 10-year-old set many strict rules, rarely explain them beyond "because I said so," and show little warmth or responsiveness to his feelings. Which parenting style in Baumrind\'s framework is this, and which outcome does research MOST often link to it?',
    options: [
      { id: 'a', text: 'Permissive; impulsive behavior and poor self-control in children', isCorrect: false, rationale: 'Permissive parents are warm but make few demands, the opposite of this pattern.' },
      { id: 'b', text: 'Uninvolved; the poorest outcomes across nearly all measured areas', isCorrect: false, rationale: 'Uninvolved parents are low in both demands and warmth, but these parents are highly demanding.' },
      { id: 'c', text: 'Authoritative; high self-esteem and strong social competence', isCorrect: false, rationale: 'Authoritative parents pair high demands with warmth and explanation, which is missing here.' },
      { id: 'd', text: 'Authoritarian; anxiety, withdrawal and lower self-esteem', isCorrect: true, rationale: 'High demands with low warmth and no explanation is authoritarian parenting, linked to anxious, withdrawn children.' },
    ],
    rationale: 'Baumrind classified parenting by demandingness and responsiveness. Authoritative parents are high in both; authoritarian parents are high in demands but low in warmth and explanation; permissive parents are warm but undemanding. Maccoby and Martin later added the uninvolved style, low in both. Authoritarian parenting is associated with anxiety, withdrawal, lower self-esteem and, in some children, defiance.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Early childhood: child-rearing styles (Baumrind)' },
    ],
  },
  {
    id: 'nce-s-cou-232',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: 'After a breakup, a 15-year-old tells her school counselor, "Nobody has ever hurt like this. My mom could never understand, because what I feel is completely different from anything she went through." In Elkind\'s account of adolescent egocentrism, this reflects:',
    options: [
      { id: 'a', text: 'The imaginary audience', isCorrect: false, rationale: 'The imaginary audience is the belief that everyone is watching and judging, not that one\'s feelings are unique.' },
      { id: 'b', text: 'The personal fable', isCorrect: true, rationale: 'The personal fable is the belief that one\'s experiences and feelings are unique and that one is special.' },
      { id: 'c', text: 'Apparent hypocrisy', isCorrect: false, rationale: 'Apparent hypocrisy is voicing ideals without seeing that one\'s own behavior contradicts them.' },
      { id: 'd', text: 'Identity foreclosure', isCorrect: false, rationale: 'Foreclosure is Marcia\'s status of commitment without exploration, not an egocentric belief.' },
    ],
    rationale: 'Elkind described two forms of adolescent egocentrism. The imaginary audience is the sense of being constantly observed and evaluated by others; the personal fable is the belief that one is unique, so that no one else could understand one\'s feelings, and sometimes that one is invulnerable to harm. Both reflect the new capacity for formal operational thought turned back on the self.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Adolescence: imaginary audience and personal fable (Elkind)' },
    ],
  },

  // ── MULTICULTURAL ────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-233',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: 'After a case presentation, a White supervisor tells a Black counseling intern, "You are so articulate. I wasn\'t expecting that." The supervisor means it as praise. In Sue\'s taxonomy of racial microaggressions, this remark is BEST classified as a:',
    options: [
      { id: 'a', text: 'Microassault', isCorrect: false, rationale: 'Microassaults are explicit, often deliberate attacks such as slurs, not well-meant comments.' },
      { id: 'b', text: 'Microinvalidation', isCorrect: false, rationale: 'Microinvalidations negate a person\'s experiences, as with color-blind statements.' },
      { id: 'c', text: 'Microinsult', isCorrect: true, rationale: 'An ascription of intelligence that conveys surprise at competence is a classic microinsult.' },
      { id: 'd', text: 'Stereotype threat', isCorrect: false, rationale: 'Stereotype threat is a target\'s performance worry, not a type of microaggression.' },
    ],
    rationale: 'Sue described three forms of microaggression. Microassaults are explicit, usually conscious attacks. Microinsults are often unconscious communications that demean a person\'s heritage, such as expressing surprise that a person of color is articulate. Microinvalidations exclude or negate the thoughts, feelings or reality of people of color, such as claiming not to see race.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Racial microaggressions: microassaults, microinsults and microinvalidations' },
    ],
  },
  {
    id: 'nce-s-cou-234',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'easy',
    stem: 'Working with a Cambodian refugee, a counselor learns the client\'s own terms for her distress, asks how her community explains such symptoms and frames goals within those meanings. This approach reflects which perspective?',
    options: [
      { id: 'a', text: 'An etic perspective', isCorrect: false, rationale: 'An etic view applies concepts assumed to be universal across cultures.' },
      { id: 'b', text: 'An emic perspective', isCorrect: true, rationale: 'An emic view seeks to understand the client from within her own culture\'s concepts and meanings.' },
      { id: 'c', text: 'An assimilation stance', isCorrect: false, rationale: 'Assimilation is an acculturation strategy of adopting the dominant culture.' },
      { id: 'd', text: 'A universalist stance', isCorrect: false, rationale: 'Universalism, like the etic view, emphasizes what is common across cultures.' },
    ],
    rationale: 'An etic (universal) perspective assumes that concepts and methods apply across cultures, while an emic (culture-specific) perspective seeks to understand behavior and distress through the meanings of the client\'s own culture. Culturally responsive counselors balance the two, using emic understanding to avoid imposing outside frameworks.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Etic (universal) and emic (culture-specific) perspectives' },
    ],
  },
  {
    id: 'nce-s-cou-235',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: 'Linh, 17, was born in the United States to Vietnamese parents. At home and at her temple she has been taught to speak Vietnamese, honor her elders and keep Tet traditions, and she embraces these norms. The process by which she has been socialized into and kept her heritage culture is called:',
    options: [
      { id: 'a', text: 'Acculturation', isCorrect: false, rationale: 'Acculturation refers to changes from contact with a different, often dominant, culture.' },
      { id: 'b', text: 'Assimilation', isCorrect: false, rationale: 'Assimilation is an acculturation strategy of adopting the dominant culture over one\'s heritage.' },
      { id: 'c', text: 'Marginalization', isCorrect: false, rationale: 'Marginalization is low connection to both the heritage and the dominant culture.' },
      { id: 'd', text: 'Enculturation', isCorrect: true, rationale: 'Enculturation is socialization into, and retention of, the norms of one\'s own heritage culture.' },
    ],
    rationale: 'Enculturation is the process of being socialized into and maintaining the norms, values and practices of one\'s heritage culture. Acculturation is the process of change that results from contact with another culture, usually the dominant one. For second-generation clients the two processes run side by side, and each can be assessed separately.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Acculturation and enculturation in culturally diverse clients' },
    ],
    reviewNote: 'Enculturation definition follows Kim & Abreu (2001); SME to confirm the Sue & Sue locator.',
  },
  {
    id: 'nce-s-cou-236',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: 'A Black woman tells her counselor that she is repeatedly passed over at her firm. Her complaint was dismissed because the firm promotes many White women and several Black men. Which framework BEST helps the counselor understand her experience?',
    options: [
      { id: 'a', text: 'An additive model, summing her separate race and gender barriers', isCorrect: false, rationale: 'Adding single-axis barriers misses the distinct form of exclusion created where they meet.' },
      { id: 'b', text: 'Minority stress theory, applied to her single most salient identity', isCorrect: false, rationale: 'Minority stress concerns chronic stress from stigma; focusing on one identity misses the overlap.' },
      { id: 'c', text: 'Crenshaw\'s intersectionality, in which overlapping identities interact', isCorrect: true, rationale: 'Intersectionality explains how race and gender combine into discrimination invisible to single-axis analysis.' },
      { id: 'd', text: 'Internalized oppression, seeing her concerns as self-blame to correct', isCorrect: false, rationale: 'Nothing suggests self-blame; recasting systemic exclusion as internal invalidates her experience.' },
    ],
    rationale: 'Kimberlé Crenshaw coined intersectionality to explain how Black women\'s discrimination claims fell through the cracks when courts examined race and sex separately. Overlapping identities interact to produce distinct experiences of privilege and oppression that single-axis or additive views miss, so counselors attend to the whole person and the systems acting on her.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Multiple identities and intersectionality' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Intersection of identities; privileged and marginalized statuses' },
    ],
  },
  {
    id: 'nce-s-cou-237',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: 'In a multicultural course, a White student says, "I worked hard for everything I have, so I don\'t have privilege." The instructor introduces Peggy McIntosh\'s concept of White privilege. Which statement BEST captures that concept?',
    options: [
      { id: 'a', text: 'Unearned advantages granted by systems, often invisible to those holding them', isCorrect: true, rationale: 'McIntosh described privilege as unearned, systemic and largely invisible to those who have it.' },
      { id: 'b', text: 'Advantages held only by White people with wealth or high-status occupations', isCorrect: false, rationale: 'Racial privilege operates across class lines, although class shapes it.' },
      { id: 'c', text: 'Benefits that exist only when a White person holds conscious racial prejudice', isCorrect: false, rationale: 'Privilege operates through systems regardless of an individual\'s intent or beliefs.' },
      { id: 'd', text: 'Proof that White people\'s achievements reflect no individual effort or merit', isCorrect: false, rationale: 'Privilege does not deny effort; it describes advantages that exist apart from effort.' },
    ],
    rationale: 'McIntosh likened White privilege to an invisible knapsack of unearned assets, such as being able to assume one will not be followed in a store. Privilege is conferred by social systems regardless of intent or effort and is often invisible to those who hold it. Recognizing it is part of the counselor self-awareness called for in the multicultural and social justice competencies.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'White privilege and the invisible knapsack (McIntosh)' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counselor self-awareness: privileged and marginalized statuses' },
    ],
  },

  // ── PLAY THERAPY ─────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-238',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'easy',
    stem: 'A counselor offers a 10-year-old a tray of sand and shelves of miniature figures, invites her to "make a world," and quietly witnesses the scene she builds. Dora Kalff developed this sandplay approach from which theoretical tradition?',
    options: [
      { id: 'a', text: 'Adlerian theory', isCorrect: false, rationale: 'Adlerian play therapy is Kottman\'s approach, built on lifestyle and mistaken beliefs.' },
      { id: 'b', text: 'Behavioral theory', isCorrect: false, rationale: 'Behavioral approaches target observable behavior through reinforcement, not symbolic worlds.' },
      { id: 'c', text: 'Person-centered theory', isCorrect: false, rationale: 'Child-centered play therapy (Axline, Landreth) is person-centered, not sandplay.' },
      { id: 'd', text: 'Jungian analytical theory', isCorrect: true, rationale: 'Kalff built sandplay on Jung\'s ideas of symbols, the unconscious and the self.' },
    ],
    rationale: 'Margaret Lowenfeld created the World Technique, in which children build scenes in a sand tray with miniatures. Dora Kalff, a Swiss Jungian, adapted it into sandplay, viewing the tray as a "free and protected space" in which symbols from the unconscious emerge and the self can be expressed and healed.',
    references: [
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: play therapy and sandplay' },
    ],
    reviewNote: 'SME to confirm Gladding locator for sandplay; facts (Lowenfeld World Technique; Kalff Jungian sandplay) are standard.',
  },

  // ── ATTACHMENT ───────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-239',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'hard',
    stem: 'In the Adult Attachment Interview, a mother describes a childhood with a harsh, rejecting father. She recounts painful memories in a coherent, balanced way, reflects on how they affected her and shows some understanding of her father\'s struggles. Her interview is MOST likely classified as:',
    options: [
      { id: 'a', text: 'Dismissing', isCorrect: false, rationale: 'Dismissing interviews minimize attachment and offer idealized but unsupported or sparse memories.' },
      { id: 'b', text: 'Preoccupied', isCorrect: false, rationale: 'Preoccupied interviews are entangled and angry or vague, with long, incoherent passages.' },
      { id: 'c', text: 'Unresolved', isCorrect: false, rationale: 'Unresolved interviews show lapses in reasoning when discussing loss or trauma.' },
      { id: 'd', text: 'Autonomous', isCorrect: true, rationale: 'A coherent, reflective account of adverse experiences is classified autonomous (secure), often called earned security.' },
    ],
    rationale: 'The Adult Attachment Interview, developed by George, Kaplan and Main, classifies adults by the coherence of their narrative about childhood rather than by how positive the experiences were. A coherent, reflective account of a difficult childhood is classified autonomous (secure), sometimes called earned security. Parents\' AAI classifications predict their infants\' Strange Situation classifications.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Attachment: continuity across generations and the Adult Attachment Interview' },
    ],
  },
  {
    id: 'nce-s-cou-240',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'easy',
    stem: 'Harlow raised infant rhesus monkeys with two surrogate mothers: one made of bare wire that held a feeding bottle and one covered in soft cloth without food. What did the monkeys\' behavior show?',
    options: [
      { id: 'a', text: 'Attachment rests mainly on contact comfort, not feeding', isCorrect: true, rationale: 'The monkeys clung to the cloth mother and ran to her when frightened, even though the wire mother fed them.' },
      { id: 'b', text: 'Attachment forms to whichever surrogate supplies food', isCorrect: false, rationale: 'This drive-reduction view is what Harlow\'s results contradicted.' },
      { id: 'c', text: 'Infants form no attachment to either surrogate mother', isCorrect: false, rationale: 'The monkeys formed a clear attachment to the cloth surrogate.' },
      { id: 'd', text: 'Imprinting occurs only in a narrow window after birth', isCorrect: false, rationale: 'Imprinting in a critical period is Lorenz\'s finding with geese, not Harlow\'s.' },
    ],
    rationale: 'Harlow\'s surrogate-mother studies showed that infant monkeys spent most of their time clinging to the soft cloth mother and sought her out when frightened, visiting the wire mother only to feed. The results challenged drive-reduction views that attachment arises from feeding and supported the importance of contact comfort.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Ethological theory of attachment; Harlow\'s contact comfort studies' },
    ],
  },
];
