// tools/nce/seed/counseling-12.js — Counseling Skills and Interventions, batch 6 (part 2)
// Hand-authored original items (nce-s-cou-331 … nce-s-cou-360).
const GL = 'Gladding (Counseling: A Comprehensive Profession)';
const IV = 'Ivey et al. (Intentional Interviewing)';
const YL = 'Yalom & Leszcz (Group Psychotherapy)';
const SH = 'Sharf (Career Development Theory)';
const BK = 'Berk (Development Through the Lifespan)';
const SS = 'Sue & Sue (Counseling the Culturally Diverse)';
const JB = 'J. Beck (CBT: Basics and Beyond)';

module.exports = [
  // ── BASIC ATTENDING AND LISTENING SKILLS ─────────────────────────────────
  {
    id: 'nce-s-cou-331',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'easy',
    stem: `A 62-year-old client pauses while describing her first week of retirement. The counselor nods, says "Mm-hm," and then repeats one key word she used: "Restless?" In Ivey's basic listening sequence, what is the counselor doing?`,
    options: [
      { id: 'a', text: `Paraphrasing`, isCorrect: false, rationale: `A paraphrase restates the main content of what the client said in fresh words; a single word and a nod do not.` },
      { id: 'b', text: `Encouraging`, isCorrect: true, rationale: `Encouragers such as head nods, "uh-huh" and repeating a key word prompt the client to keep talking and expand.` },
      { id: 'c', text: `Summarizing`, isCorrect: false, rationale: `Summarizing pulls together several themes over a longer stretch of the session, not one word.` },
      { id: 'd', text: `Interpreting`, isCorrect: false, rationale: `Interpreting offers a new frame of reference; repeating the client's own word adds no new meaning.` },
    ],
    rationale: `Ivey places encouraging in the basic listening sequence along with questioning, paraphrasing, reflecting feeling and summarizing. Encouragers include nods, minimal verbal prompts and the repetition of key words, and they invite the client to elaborate on what matters to them. Repeating a key word often leads the client to explore the feeling or meaning behind it.`,
    references: [{ source: IV, detail: 'Encouraging, paraphrasing and summarizing: encouragers and key-word restatement' }],
  },
  {
    id: 'nce-s-cou-332',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'medium',
    stem: `During an intake, a client has spoken at length and in general terms about "always" feeling tired. The counselor now needs to know whether the client has started any new medication in the past month. Which statement BEST describes the role of a closed question here?`,
    options: [
      { id: 'a', text: `It should be avoided, since closed questions damage rapport in intake sessions`, isCorrect: false, rationale: `Closed questions are a normal part of intake; overuse, not use, is what harms rapport.` },
      { id: 'b', text: `It should be rephrased as a "why" question so the client explains their habits`, isCorrect: false, rationale: `"Why" questions can sound accusatory and would not efficiently obtain the specific fact needed.` },
      { id: 'c', text: `It should replace open questions for the rest of the interview to save time`, isCorrect: false, rationale: `Relying only on closed questions puts the counselor in charge of content and limits the client's story.` },
      { id: 'd', text: `It fits well, because closed questions gather specific facts and narrow focus`, isCorrect: true, rationale: `Closed questions are useful for obtaining specific information and focusing a broad or wandering account.` },
    ],
    rationale: `Open questions invite clients to elaborate, while closed questions can usually be answered in a few words. Closed questions are appropriate for gathering specific facts, such as recent medication changes, and for bringing focus to a diffuse account. The skill lies in balancing the two so that the client keeps ownership of the story.`,
    references: [{ source: IV, detail: 'Questions: uses of open and closed questions' }],
  },
  {
    id: 'nce-s-cou-333',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'hard',
    stem: `A supervisor reviewing a trainee's recordings notices that clients often mention family and faith, yet sessions keep returning to work stress. The trainee responds warmly whenever work comes up and gives brief, flat replies to everything else. Which concept from Ivey's microskills BEST explains this pattern?`,
    options: [
      { id: 'a', text: `Selective attention, since clients tend to talk about what the counselor attends to`, isCorrect: true, rationale: `Ivey notes that counselors reinforce certain topics by attending to them, and clients then talk more about those topics.` },
      { id: 'b', text: `Resistance, since the clients are avoiding the material that matters most to them`, isCorrect: false, rationale: `The clients do raise family and faith; the narrowing comes from the trainee's responses, not client avoidance.` },
      { id: 'c', text: `Transference, since the clients are repeating early relationship patterns in session`, isCorrect: false, rationale: `Nothing suggests the clients are reliving past relationships with the trainee.` },
      { id: 'd', text: `Mirroring, since the trainee is matching the clients' body language and pace well`, isCorrect: false, rationale: `Mirroring nonverbal behavior builds rapport; it does not explain why the topics narrow.` },
    ],
    rationale: `Ivey describes selective attention as the tendency of counselors to listen and respond more to some topics than others, often without awareness. Because clients follow the counselor's lead, they end up talking mostly about what the counselor reinforces. Reviewing recordings helps trainees notice what they attend to and what they ignore.`,
    references: [{ source: IV, detail: 'Attending behavior: selective attention and verbal tracking' }],
  },

  // ── REFLECTION, PARAPHRASING AND SUMMARIZING ─────────────────────────────
  {
    id: 'nce-s-cou-334',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: `A counselor says to a young adult client, "It sounds like moving back home has left you feeling both grateful and a little trapped. Am I hearing that right?" What is the main purpose of the final question?`,
    options: [
      { id: 'a', text: `To shift the session toward a new topic now that the feeling has been named`, isCorrect: false, rationale: `The question invites the client to stay with the reflection, not to move on to new material.` },
      { id: 'b', text: `To test whether the client is being honest about how they feel at home`, isCorrect: false, rationale: `The question checks the counselor's accuracy, not the client's honesty.` },
      { id: 'c', text: `To check the accuracy of the reflection and invite the client to correct it`, isCorrect: true, rationale: `A checkout (perception check) lets the client confirm, refine or correct the counselor's understanding.` },
      { id: 'd', text: `To signal that the counselor is unsure and wants the client to lead instead`, isCorrect: false, rationale: `The checkout is a deliberate part of good reflection, not a sign of counselor uncertainty.` },
    ],
    rationale: `Ivey recommends ending many paraphrases and reflections with a checkout, such as "Is that close?" or "Did I get that right?" The checkout keeps the reflection tentative, gives the client power to correct the counselor and often leads to a more precise description of the experience. It also signals that the client, not the counselor, is the expert on their feelings.`,
    references: [{ source: IV, detail: 'Reflecting feelings and paraphrasing: the checkout (perception check)' }],
  },
  {
    id: 'nce-s-cou-335',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: `A client says calmly, "I was a little irritated when my roommate ate my leftovers again." The counselor responds, "You were furious with him." What is the MAIN weakness of this reflection?`,
    options: [
      { id: 'a', text: `It overstates the intensity of the feeling the client expressed`, isCorrect: true, rationale: `"Furious" is far stronger than "a little irritated," so the reflection misses the client's actual level of feeling.` },
      { id: 'b', text: `It reflects a feeling rather than the content of what happened`, isCorrect: false, rationale: `Reflecting feeling is a legitimate skill; the problem is the inaccurate intensity, not the choice to reflect affect.` },
      { id: 'c', text: `It uses the past tense instead of focusing on the present moment`, isCorrect: false, rationale: `Past-tense reflection is acceptable when the client describes a past event.` },
      { id: 'd', text: `It repeats the client's own words too closely to add anything`, isCorrect: false, rationale: `The counselor substituted a new and much stronger word, so this is not parroting.` },
    ],
    rationale: `An accurate reflection of feeling matches both the type and the intensity of the emotion the client expresses. Overshooting the intensity can leave the client feeling misunderstood or pushed, while undershooting can minimize the experience. A better response might be "It bothered you that it happened again."`,
    references: [{ source: IV, detail: 'Reflecting feelings: matching the type and intensity of emotion' }],
  },

  // ── CONFRONTATION AND IMMEDIACY ──────────────────────────────────────────
  {
    id: 'nce-s-cou-336',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: `A practicum student wants to use supportive confrontation with a client whose words and actions seem to conflict. According to Ivey's model, what should the student do FIRST?`,
    options: [
      { id: 'a', text: `Name the contradiction directly so the client cannot avoid looking at it`, isCorrect: false, rationale: `Pointing out the discrepancy is the second step and should follow careful listening.` },
      { id: 'b', text: `Listen and observe closely to identify the mixed messages and conflicts`, isCorrect: true, rationale: `Supportive confrontation begins by listening, observing and clearly identifying the discrepancy.` },
      { id: 'c', text: `Rate the client's response on the Client Change Scale for the session`, isCorrect: false, rationale: `Evaluating change with the Client Change Scale comes after the discrepancy has been pointed out.` },
      { id: 'd', text: `Offer an interpretation of the unconscious reasons behind the conflict`, isCorrect: false, rationale: `Interpretation is a separate influencing skill and is not the first step of confrontation.` },
    ],
    rationale: `Ivey describes supportive confrontation as a sequence. The counselor first listens and observes to identify incongruities, mixed messages and conflicts; next points them out and helps the client work through them in a nonjudgmental way; and then evaluates the client's response, for example with the Client Change Scale. Starting with listening keeps the confrontation accurate and grounded in the relationship.`,
    references: [{ source: IV, detail: 'Confrontation: the three steps of supportive confrontation' }],
  },
  {
    id: 'nce-s-cou-337',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'easy',
    stem: `A client has been describing a conflict with a coworker. Which counselor statement shows the HIGHEST level of immediacy?`,
    options: [
      { id: 'a', text: `"Last month you also had trouble speaking up with your brother."`, isCorrect: false, rationale: `This links past events and stays in the past tense, so it has little immediacy.` },
      { id: 'b', text: `"Right now, as you talk about him, I notice your voice getting quiet."`, isCorrect: true, rationale: `Present-tense attention to what is happening between counselor and client in the moment is immediacy.` },
      { id: 'c', text: `"Next week you could try telling him how his comments affect you."`, isCorrect: false, rationale: `This is a future-oriented suggestion, not a here-and-now response.` },
      { id: 'd', text: `"Your coworker sounds like he has been difficult for a long time."`, isCorrect: false, rationale: `This comments on a third party outside the session and stays in the past.` },
    ],
    rationale: `Immediacy refers to the counselor's present-tense, here-and-now responses about what is happening in the session or between counselor and client. Statements about the past or future have less immediacy than those that name what is occurring right now. Used well, immediacy brings hidden feelings and relational patterns into the room where they can be explored.`,
    references: [{ source: IV, detail: 'Immediacy: past, present and future tense in counselor responses' }],
  },

  // ── TERMINATION SKILLS ───────────────────────────────────────────────────
  {
    id: 'nce-s-cou-338',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'easy',
    stem: `A counselor in an employee assistance program offers each client up to six sessions. When is it BEST to begin discussing the end of counseling with a new client?`,
    options: [
      { id: 'a', text: `At the fifth session, so the client is not distracted earlier`, isCorrect: false, rationale: `Waiting until the next-to-last session leaves little time to plan and may feel abrupt.` },
      { id: 'b', text: `Only after the client reports that the main goal has been met`, isCorrect: false, rationale: `With a fixed session limit, the end date does not depend on when goals are reached.` },
      { id: 'c', text: `In the first session, as part of setting goals and expectations`, isCorrect: true, rationale: `In time-limited work, raising the ending at the start shapes goals and helps clients use each session well.` },
      { id: 'd', text: `When the counselor notices the client becoming too dependent`, isCorrect: false, rationale: `Termination planning should not wait for a problem; in brief work it is built in from the outset.` },
    ],
    rationale: `In brief and time-limited counseling, the ending is known from the start, so it should be discussed during informed consent and goal setting. This lets the client and counselor choose realistic goals, track progress and prepare for the end together. Raising termination early also reduces the chance that the final session feels like an abrupt loss.`,
    references: [{ source: GL, detail: 'Termination in counseling: timing and preparation for ending' }],
  },
  {
    id: 'nce-s-cou-339',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'medium',
    stem: `In the next-to-last session of CBT for depression, a 41-year-old client says, "You fixed me. I don't know what I'll do without you telling me what to do." Which counselor response BEST supports the gains lasting after counseling ends?`,
    options: [
      { id: 'a', text: `Review the specific skills the client used and credit them for the change`, isCorrect: true, rationale: `Helping clients attribute progress to their own efforts builds self-efficacy and supports self-therapy after ending.` },
      { id: 'b', text: `Accept the thanks graciously and add more sessions to ease the transition`, isCorrect: false, rationale: `Extending sessions because of dependence reinforces the belief that the client cannot cope alone.` },
      { id: 'c', text: `Explain that relapse is unlikely now that the depression has fully lifted`, isCorrect: false, rationale: `Depression often recurs; relapse prevention prepares clients for setbacks rather than denying them.` },
      { id: 'd', text: `Suggest the client call the counselor whenever a hard decision comes up`, isCorrect: false, rationale: `This keeps the counselor in charge of decisions and works against the goal of client independence.` },
    ],
    rationale: `J. Beck describes preparing for termination from the start of CBT, with the aim of clients becoming their own therapists. Near the end, the counselor reviews which skills the client used and helps them attribute improvement to their own work rather than to the counselor. This attribution strengthens self-efficacy and supports relapse prevention and booster planning.`,
    references: [{ source: JB, detail: 'Termination and relapse prevention: attributing progress to the client' }],
  },
  {
    id: 'nce-s-cou-340',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'hard',
    stem: `A community clinic finds that many new clients drop out after one or two sessions without saying why. The director asks counselors for one change most likely to reduce this premature termination. Which change is BEST supported?`,
    options: [
      { id: 'a', text: `Assigning homework from the first session so that clients feel more invested`, isCorrect: false, rationale: `Homework can help later, but early demands without shared understanding can increase dropout.` },
      { id: 'b', text: `Scheduling first sessions less often so clients who stay are more motivated`, isCorrect: false, rationale: `Longer gaps early in counseling weaken engagement and tend to increase dropout.` },
      { id: 'c', text: `Moving clients who miss a session to a waitlist until they recommit to care`, isCorrect: false, rationale: `This penalizes clients who are already disengaging and makes premature termination more likely.` },
      { id: 'd', text: `Clarifying expectations about counseling and agreeing on goals at the start`, isCorrect: true, rationale: `Role induction and early agreement on goals and methods address mismatched expectations, a key cause of dropout.` },
    ],
    rationale: `Premature termination is often linked to a mismatch between what clients expect and what counseling offers, along with a weak early alliance. Preparing clients for counseling (role induction), discussing how long it may take and agreeing on goals and tasks early reduce dropout. Monitoring the alliance and progress in early sessions also helps counselors notice clients at risk of leaving.`,
    references: [{ source: GL, detail: 'Termination in counseling: premature termination and how to reduce it' }],
  },

  // ── GROUP: STAGES AND DYNAMICS ───────────────────────────────────────────
  {
    id: 'nce-s-cou-341',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: `A school counselor leads a parent-teacher committee planning a new homework policy. One parent objects to every proposal with a different reason each week. The counselor later learns this parent's child was recently suspended and the parent fears the policy will single the child out. What group dynamic is operating?`,
    options: [
      { id: 'a', text: `Scapegoating, in which the group blames one member for its lack of progress`, isCorrect: false, rationale: `Scapegoating is the group turning on one member; here one member is blocking the group.` },
      { id: 'b', text: `A hidden agenda, an unstated personal goal that steers a member's behavior`, isCorrect: true, rationale: `The parent's unspoken concern about the child is a hidden agenda that drives the repeated objections.` },
      { id: 'c', text: `Subgrouping, in which several members form an alliance against the group`, isCorrect: false, rationale: `Subgrouping involves an alliance of several members, not one member acting alone.` },
      { id: 'd', text: `Groupthink, in which members suppress dissent to reach quick agreement`, isCorrect: false, rationale: `Groupthink suppresses disagreement; this parent is expressing a great deal of it.` },
    ],
    rationale: `A hidden agenda is a goal or concern a member holds but does not state, which shapes how that member acts in the group. Hidden agendas are common in task groups and can stall progress because the stated arguments are not the real issue. Leaders help by attending to process and creating safe ways for members to voice underlying concerns.`,
    references: [{ source: GL, detail: 'Groups in counseling: group dynamics and hidden agendas' }],
  },
  {
    id: 'nce-s-cou-342',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: `A counselor is forming an eight-week group for new parents adjusting after the birth of their first child. She decides to include only members who share this life transition. According to Yalom, what is the main advantage of this homogeneous composition?`,
    options: [
      { id: 'a', text: `Deeper long-term character change through exposure to many conflict styles`, isCorrect: false, rationale: `Yalom links deep interpersonal change to heterogeneous, long-term groups, not homogeneous ones.` },
      { id: 'b', text: `Less need for screening, since shared problems make members interchangeable`, isCorrect: false, rationale: `Screening is still needed; a shared concern does not make members alike in readiness or fit.` },
      { id: 'c', text: `Faster cohesion and mutual support, which suits a brief group's aims well`, isCorrect: true, rationale: `Homogeneous groups gel quickly, offer immediate support and suit short-term, focused goals.` },
      { id: 'd', text: `More conflict in early sessions, which speeds up the group's working stage`, isCorrect: false, rationale: `Homogeneous groups tend to have less conflict, not more.` },
    ],
    rationale: `Yalom notes that homogeneous groups become cohesive quickly, provide immediate support, have better attendance and less conflict, and produce faster symptom relief. Their drawback is that they may stay at a more superficial level. Heterogeneous composition is preferred for long-term interpersonal groups that aim at deeper change.`,
    references: [{ source: YL, detail: 'Composition of therapy groups: homogeneous versus heterogeneous groups' }],
  },
  {
    id: 'nce-s-cou-343',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: `In a partial hospitalization program, a counselor leads a long-term group for adults with severe, long-standing personality and mood problems. The aim is in-depth personality change and remediation of serious dysfunction. Under the ASGW classification, which type of group is this?`,
    options: [
      { id: 'a', text: `Task and work group`, isCorrect: false, rationale: `Task groups exist to complete a work product, such as a committee goal.` },
      { id: 'b', text: `Psychoeducation group`, isCorrect: false, rationale: `Psychoeducation groups teach skills and information, often to prevent problems.` },
      { id: 'c', text: `Counseling group`, isCorrect: false, rationale: `Counseling groups address normal-range personal and interpersonal problems of living.` },
      { id: 'd', text: `Psychotherapy group`, isCorrect: true, rationale: `Psychotherapy groups treat serious, long-standing problems and aim at in-depth personality change.` },
    ],
    rationale: `ASGW describes four group work specializations: task and work, psychoeducation, counseling and psychotherapy. Psychotherapy groups serve members with serious or chronic psychological problems and aim at reconstructive, in-depth change, often in clinical settings. Counseling groups, by contrast, address problems of living for members who function in the normal range.`,
    references: [{ source: GL, detail: 'Group work: ASGW types of groups (psychotherapy groups)' }],
  },

  // ── GROUP LEADERSHIP SKILLS AND THERAPEUTIC FACTORS ──────────────────────
  {
    id: 'nce-s-cou-344',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: `In an assertiveness group, a 26-year-old member watches another member calmly decline an unfair request in a role-play. The next week, she reports using the same words and tone with her landlord. Which of Yalom's therapeutic factors does this BEST illustrate?`,
    options: [
      { id: 'a', text: `Imitative behavior`, isCorrect: true, rationale: `Adopting behaviors modeled by other members or the leader is imitative behavior.` },
      { id: 'b', text: `Universality`, isCorrect: false, rationale: `Universality is the relief of learning that others share one's problems.` },
      { id: 'c', text: `Catharsis`, isCorrect: false, rationale: `Catharsis is the release of strong emotion, not the copying of a skill.` },
      { id: 'd', text: `Altruism`, isCorrect: false, rationale: `Altruism is the benefit of helping other members, not learning from them.` },
    ],
    rationale: `Yalom lists imitative behavior among the therapeutic factors of groups. Members learn by watching how others, including the leader, handle situations and then try those behaviors themselves. Even when imitation is brief, it can help members experiment with new ways of acting.`,
    references: [{ source: YL, detail: 'Ch. 1: The therapeutic factors, imitative behavior' }],
  },
  {
    id: 'nce-s-cou-345',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: `In a long-term interpersonal group, several members tell Kofi that his habit of joking whenever someone becomes emotional leaves them feeling brushed off. Kofi is surprised and says, "I thought I was helping." Which therapeutic factor is MOST directly at work?`,
    options: [
      { id: 'a', text: `Instillation of hope from watching other members improve`, isCorrect: false, rationale: `Hope comes from seeing others get better; Kofi is learning how he affects people.` },
      { id: 'b', text: `Imparting information through direct advice and teaching`, isCorrect: false, rationale: `Members are describing their reactions to him, not offering advice or instruction.` },
      { id: 'c', text: `Interpersonal learning from feedback on his effect on others`, isCorrect: true, rationale: `Learning how one is seen and how one's behavior lands on others is interpersonal learning.` },
      { id: 'd', text: `Existential factors as he faces full responsibility for his life`, isCorrect: false, rationale: `Existential factors involve life's givens, such as death and ultimate responsibility.` },
    ],
    rationale: `Yalom considers interpersonal learning one of the most powerful therapeutic factors in long-term groups. Through here-and-now feedback, members discover how their behavior affects others and how they are perceived, which they often cannot see on their own. They can then try new ways of relating within the safety of the group.`,
    references: [{ source: YL, detail: 'Interpersonal learning: feedback and the group as social microcosm' }],
  },
  {
    id: 'nce-s-cou-346',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: `In the first sessions of a new outpatient group, the leader often asks members to respond to one another rather than to her, thanks members who give honest feedback and models nonjudgmental acceptance herself. Which of Yalom's basic tasks of the group therapist is she MAINLY carrying out?`,
    options: [
      { id: 'a', text: `Creating and maintaining the group by selecting members and preventing dropout`, isCorrect: false, rationale: `This task covers forming the group and keeping it intact, such as screening and handling absences.` },
      { id: 'b', text: `Culture building, shaping the norms that let the group act as a helping agent`, isCorrect: true, rationale: `Shaping norms such as member-to-member interaction and honest feedback, explicitly and by modeling, is culture building.` },
      { id: 'c', text: `Process illumination, explaining the meaning of an interaction just completed`, isCorrect: false, rationale: `Process illumination reflects on an interaction after it occurs; she is mainly setting norms.` },
      { id: 'd', text: `Interpretation of transference, linking members' reactions to their families`, isCorrect: false, rationale: `Yalom's group therapist emphasizes here-and-now norms, and she is not interpreting family patterns.` },
    ],
    rationale: `Yalom describes three basic tasks of the group therapist: creating and maintaining the group, culture building, and activating and illuminating the here-and-now. In culture building, the leader shapes norms such as self-disclosure, direct interaction among members and nonjudgmental acceptance, acting both as a technical expert and as a model-setting participant. These norms make the group itself the main agent of change.`,
    references: [{ source: YL, detail: 'The therapist: basic tasks, culture building and norm shaping' }],
  },

  // ── CAREER DEVELOPMENT THEORIES ──────────────────────────────────────────
  {
    id: 'nce-s-cou-347',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: `Super's Archway Model shows personal factors such as needs, values and aptitudes in one pillar and societal factors such as family, school and the labor market in the other, joined by an arch of developmental stages. What sits in the keystone of the arch?`,
    options: [
      { id: 'a', text: `The labor market, which sets the jobs available to the person`, isCorrect: false, rationale: `The labor market is part of the societal pillar, not the keystone.` },
      { id: 'b', text: `Career maturity, the readiness to make decisions at each age`, isCorrect: false, rationale: `Career maturity is a separate construct in Super's theory, not the keystone of the archway.` },
      { id: 'c', text: `Interests, which link a person's values with available jobs`, isCorrect: false, rationale: `Interests sit in the personal pillar alongside needs, values and aptitudes.` },
      { id: 'd', text: `The self, which integrates personal and societal influences`, isCorrect: true, rationale: `Super placed the self, the person as decision maker and self-concept, in the keystone that unites both pillars.` },
    ],
    rationale: `Super's Archway Model is a visual summary of the factors in career development. One pillar holds personal characteristics such as needs, values, interests and aptitudes, and the other holds societal influences such as the economy, community, school, family and labor market. The arch represents developmental stages and role self-concepts, and the keystone is the self, which brings these influences together in career decisions.`,
    references: [{ source: SH, detail: 'Super\'s life-span theory: the Archway Model' }],
  },
  {
    id: 'nce-s-cou-348',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: `As a child, Mateo spent many happy weekends at his aunt's bakery, where the smell of bread came to mean warmth and family. Now 19, he feels drawn to culinary school without ever having been praised for cooking. In Krumboltz's social learning theory, this influence is BEST described as:`,
    options: [
      { id: 'a', text: `an associative learning experience pairing the setting with positive feelings`, isCorrect: true, rationale: `Associative learning links a previously neutral stimulus, here the bakery, with positive emotional experiences.` },
      { id: 'b', text: `an instrumental learning experience shaped by rewards for his own cooking`, isCorrect: false, rationale: `Instrumental learning follows consequences of one's own actions; he was never rewarded for cooking.` },
      { id: 'c', text: `a genetic endowment, an inborn special ability that limits career choice`, isCorrect: false, rationale: `Genetic endowment refers to inherited qualities and abilities, not emotional associations.` },
      { id: 'd', text: `a task-approach skill he uses to gather information and make a decision`, isCorrect: false, rationale: `Task-approach skills are decision-making and work habits, not emotional associations.` },
    ],
    rationale: `Krumboltz identified four influences on career decision making: genetic endowment and special abilities, environmental conditions and events, learning experiences and task-approach skills. Learning experiences are instrumental, when behavior is shaped by its consequences, or associative, when a neutral stimulus becomes paired with positive or negative experiences. Mateo's attraction comes from pairing the bakery with warmth, an associative experience.`,
    references: [{ source: SH, detail: 'Krumboltz\'s social learning theory: instrumental and associative learning experiences' }],
  },
  {
    id: 'nce-s-cou-349',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: `A 15-year-old had little interest in computer science until a summer coding camp, where she built a working app and learned that coding jobs pay well and help people. Her interest is now strong. According to the interest model in social cognitive career theory (SCCT), what MOST directly produced this interest?`,
    options: [
      { id: 'a', text: `Her Holland code, which fixed her interests before she attended the camp`, isCorrect: false, rationale: `SCCT treats interests as learned and changeable, not set in advance by a personality type.` },
      { id: 'b', text: `Her career maturity, which rose as she moved through the growth stage`, isCorrect: false, rationale: `Career maturity is Super's construct and does not explain this sudden rise in interest.` },
      { id: 'c', text: `Rising self-efficacy and positive outcome expectations for the field`, isCorrect: true, rationale: `SCCT holds that interests grow where people feel capable and expect valued outcomes.` },
      { id: 'd', text: `Chance events alone, which shape interests apart from beliefs and skills`, isCorrect: false, rationale: `The camp mattered because it changed her beliefs about her ability and the work's rewards.` },
    ],
    rationale: `In Lent, Brown and Hackett's social cognitive career theory, interests develop from self-efficacy beliefs and outcome expectations. When learning experiences lead people to feel capable at an activity and to expect valued results, interest grows, which then shapes goals and actions. This makes interests a target for intervention through mastery experiences and accurate information.`,
    references: [{ source: SH, detail: 'Social cognitive career theory: the interest model (self-efficacy and outcome expectations)' }],
  },
  {
    id: 'nce-s-cou-350',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'easy',
    stem: `A 34-year-old client describes herself as ambitious, persuasive and energetic. She enjoys leading teams, selling ideas and taking business risks, and dislikes detailed scientific work. Which Holland type is MOST dominant for her?`,
    options: [
      { id: 'a', text: `Social`, isCorrect: false, rationale: `Social types prefer helping, teaching and caring for others more than persuading or selling.` },
      { id: 'b', text: `Enterprising`, isCorrect: true, rationale: `Enterprising types like leading, persuading, selling and taking risks to reach organizational goals.` },
      { id: 'c', text: `Conventional`, isCorrect: false, rationale: `Conventional types prefer orderly, detailed work with data and clear procedures.` },
      { id: 'd', text: `Investigative`, isCorrect: false, rationale: `Investigative types enjoy scientific, analytical work, which she dislikes.` },
    ],
    rationale: `Holland's six types are Realistic, Investigative, Artistic, Social, Enterprising and Conventional. Enterprising people tend to be ambitious, sociable and persuasive and are drawn to leading, managing and selling. Investigative work sits opposite Enterprising on the hexagon, which fits her dislike of scientific tasks.`,
    references: [{ source: SH, detail: 'Holland\'s theory of types: the Enterprising type' }],
  },
  {
    id: 'nce-s-cou-351',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: `A college junior refuses to consider any business major, saying, "I'm just not a numbers person. I've always been bad at math." Her transcripts show solid math grades. In Krumboltz's social learning theory, her statement is BEST described as:`,
    options: [
      { id: 'a', text: `a self-observation generalization that may be inaccurate`, isCorrect: true, rationale: `Self-observation generalizations are learned self-appraisals of ability or interest, which can be mistaken.` },
      { id: 'b', text: `an environmental condition that blocks her from the field`, isCorrect: false, rationale: `Environmental conditions are outside events such as the job market, not her beliefs about herself.` },
      { id: 'c', text: `a genetic endowment that sets a ceiling on her math skills`, isCorrect: false, rationale: `Her good grades contradict an inborn limit; the barrier is her learned belief.` },
      { id: 'd', text: `a task-approach skill she uses to rule out career options`, isCorrect: false, rationale: `Task-approach skills are decision-making and work skills, not self-evaluations.` },
    ],
    rationale: `In Krumboltz's theory, learning experiences produce self-observation generalizations, which are overt or covert statements people make about their own abilities, interests and values. These generalizations guide career choices but can be inaccurate or overgeneralized. Counselors help clients examine such beliefs against evidence and test them through new learning experiences.`,
    references: [{ source: SH, detail: 'Krumboltz\'s social learning theory: self-observation generalizations' }],
  },

  // ── HUMAN DEVELOPMENT THEORIES ───────────────────────────────────────────
  {
    id: 'nce-s-cou-352',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: `An 81-year-old retired violinist has given up teaching and touring to focus on a few favorite pieces. She practices them more often than before, and she plays slower passages just before fast ones so the fast ones seem quicker by contrast. Which developmental model BEST explains her approach?`,
    options: [
      { id: 'a', text: `Baltes's selective optimization with compensation`, isCorrect: true, rationale: `She selects fewer goals, optimizes them with practice and compensates for losses with new strategies.` },
      { id: 'b', text: `Cumming and Henry's disengagement theory of aging`, isCorrect: false, rationale: `Disengagement describes mutual withdrawal from society, not active strategies to maintain skill.` },
      { id: 'c', text: `Erikson's stage of generativity versus stagnation`, isCorrect: false, rationale: `Generativity concerns guiding the next generation in midlife, which is not the focus here.` },
      { id: 'd', text: `Levinson's model of the midlife transition period`, isCorrect: false, rationale: `Levinson's midlife transition concerns reappraisal around age 40, not late-life adaptation.` },
    ],
    rationale: `Baltes proposed that successful aging involves selective optimization with compensation. Older adults select a smaller set of personally valued goals, optimize their resources and practice in those areas, and compensate for losses with new means of reaching the same ends. The model views late life as a time of active adaptation rather than simple decline.`,
    references: [{ source: BK, detail: 'Late adulthood: selective optimization with compensation (Baltes)' }],
  },
  {
    id: 'nce-s-cou-353',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'hard',
    stem: `A 9-month-old watches a parent hide a toy under a blue cloth and finds it several times. The parent then hides it under a red cloth while the baby watches, and the baby searches under the blue cloth again. According to Piaget, what does this error indicate?`,
    options: [
      { id: 'a', text: `The infant has no sense that hidden objects continue to exist`, isCorrect: false, rationale: `Searching for the toy at all shows that some object permanence is already present.` },
      { id: 'b', text: `The infant has a vision problem and needs to be screened soon`, isCorrect: false, rationale: `The A-not-B error is typical at this age and does not suggest a sensory problem.` },
      { id: 'c', text: `Object permanence is emerging but is not yet fully developed`, isCorrect: true, rationale: `Searching for hidden objects but at the old location (A-not-B) marks incomplete object permanence.` },
      { id: 'd', text: `The infant has reached mental representation and pretend play`, isCorrect: false, rationale: `Mental representation emerges near the end of the sensorimotor stage, around 18 to 24 months.` },
    ],
    rationale: `In Piaget's sensorimotor stage, infants of about 8 to 12 months begin to search for hidden objects, showing emerging object permanence. They often make the A-not-B search error, looking where the object was previously found rather than where they saw it hidden last. This error fades as object permanence becomes more complete in later sensorimotor substages.`,
    references: [{ source: BK, detail: 'Piaget\'s sensorimotor stage: object permanence and the A-not-B search error' }],
  },
  {
    id: 'nce-s-cou-354',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: `A 52-year-old electrician has begun training apprentices and volunteering with a youth program. He says, "I want to leave something behind that helps the next generation." Which of Erikson's psychosocial stages does this concern reflect?`,
    options: [
      { id: 'a', text: `Intimacy versus isolation`, isCorrect: false, rationale: `This early adult stage centers on forming close, committed relationships.` },
      { id: 'b', text: `Integrity versus despair`, isCorrect: false, rationale: `This late-life stage involves reviewing one's life and accepting it as meaningful.` },
      { id: 'c', text: `Industry versus inferiority`, isCorrect: false, rationale: `This school-age stage concerns competence at tasks and comparisons with peers.` },
      { id: 'd', text: `Generativity versus stagnation`, isCorrect: true, rationale: `Midlife generativity centers on guiding and contributing to the next generation.` },
    ],
    rationale: `Erikson described generativity versus stagnation as the central task of middle adulthood. Generativity involves caring for and guiding the next generation through parenting, mentoring, teaching or community contribution. Adults who do not find such outlets may feel stagnant or self-absorbed.`,
    references: [{ source: BK, detail: 'Middle adulthood: Erikson\'s generativity versus stagnation' }],
  },

  // ── ATTACHMENT THEORY ────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-355',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'medium',
    stem: `A 10-month-old cries and crawls after his father when he leaves the room, and when the father returns the baby explores the playroom while checking back with him. In Bowlby's phases of attachment development, this infant is MOST likely in which phase?`,
    options: [
      { id: 'a', text: `Preattachment`, isCorrect: false, rationale: `In this phase, from birth to about 6 weeks, infants do not yet object to being left with strangers.` },
      { id: 'b', text: `Clear-cut attachment`, isCorrect: true, rationale: `From about 6 to 8 months, infants show separation anxiety and use the caregiver as a secure base.` },
      { id: 'c', text: `Attachment in the making`, isCorrect: false, rationale: `Infants in this phase respond differently to familiar people but do not yet protest separation.` },
      { id: 'd', text: `Reciprocal relationship`, isCorrect: false, rationale: `This later phase, from about 18 to 24 months, involves language and negotiating with the caregiver.` },
    ],
    rationale: `Bowlby described four phases: preattachment, attachment in the making, clear-cut attachment and formation of a reciprocal relationship. In the clear-cut phase, beginning around 6 to 8 months, infants show separation anxiety and use the familiar caregiver as a secure base for exploration. As language and representation grow, toddlers enter the reciprocal phase and can negotiate with caregivers about comings and goings.`,
    references: [{ source: BK, detail: 'Bowlby\'s ethological theory: phases of attachment (clear-cut attachment)' }],
  },
  {
    id: 'nce-s-cou-356',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'hard',
    stem: `In the Adult Attachment Interview, a father describes his parents as "great, totally normal, very loving." When asked for specific memories, he says he cannot recall any, then mentions being sent to his room alone whenever he cried. He adds that childhood "doesn't really affect who you are." How is this interview MOST likely classified?`,
    options: [
      { id: 'a', text: `Dismissing`, isCorrect: true, rationale: `Idealized but unsupported descriptions, poor recall and downplaying attachment's importance mark a dismissing interview.` },
      { id: 'b', text: `Preoccupied`, isCorrect: false, rationale: `Preoccupied interviews are long, entangled and angry or vague, not brief and idealizing.` },
      { id: 'c', text: `Autonomous`, isCorrect: false, rationale: `Autonomous interviews are coherent and balanced, with specific memories that support general descriptions.` },
      { id: 'd', text: `Unresolved`, isCorrect: false, rationale: `Unresolved interviews show lapses in reasoning when the speaker discusses loss or trauma.` },
    ],
    rationale: `The Adult Attachment Interview classifies adults by the coherence of their account of childhood. Dismissing adults idealize their parents in general terms, cannot supply supporting memories or offer memories that contradict the ideal, and minimize the importance of attachment. Their infants are more likely to show avoidant attachment in the Strange Situation.`,
    references: [{ source: BK, detail: 'Attachment: continuity across generations and the Adult Attachment Interview' }],
  },

  // ── MULTICULTURAL COUNSELING COMPETENCIES ────────────────────────────────
  {
    id: 'nce-s-cou-357',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: `A Korean American client born and raised in Ohio tells her counselor that coworkers often ask, "But where are you really from?" and praise her "excellent English." In Sue's taxonomy of racial microaggressions, these comments are BEST classified as which type?`,
    options: [
      { id: 'a', text: `Microassault, an explicit and deliberate racial attack`, isCorrect: false, rationale: `Microassaults are conscious, overt attacks such as slurs; these comments are not deliberate insults.` },
      { id: 'b', text: `Microinsult, conveying that she must be unintelligent`, isCorrect: false, rationale: `Microinsults demean a person's heritage or ability; these comments mainly deny that she belongs.` },
      { id: 'c', text: `Macroaggression, a policy that excludes her from work`, isCorrect: false, rationale: `The comments are interpersonal remarks, not an institutional policy or system.` },
      { id: 'd', text: `Microinvalidation, treating her as foreign in her own land`, isCorrect: true, rationale: `"Alien in own land" remarks negate her experience as an American and are microinvalidations.` },
    ],
    rationale: `Sue described three types of microaggression: microassaults, microinsults and microinvalidations. Microinvalidations exclude, negate or nullify the thoughts, feelings or reality of people of color. Treating Asian Americans and Latinx Americans as perpetual foreigners, the "alien in own land" theme, is a common microinvalidation.`,
    references: [{ source: SS, detail: 'Racial microaggressions: microinvalidations and the "alien in own land" theme' }],
  },
  {
    id: 'nce-s-cou-358',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: `A counselor believes that healthy adults should make decisions independently of their families and judges clients who consult elders as "enmeshed." He assumes his own training's view of mental health applies equally to every client and sees no need to examine it. Which term BEST describes his stance?`,
    options: [
      { id: 'a', text: `Cultural humility`, isCorrect: false, rationale: `Cultural humility involves ongoing self-reflection and openness, the opposite of his stance.` },
      { id: 'b', text: `Acculturation`, isCorrect: false, rationale: `Acculturation is the change that occurs when cultures come into contact, not a counselor's bias.` },
      { id: 'c', text: `Cultural encapsulation`, isCorrect: true, rationale: `Wrenn's cultural encapsulation means treating one's own cultural assumptions as universal truths.` },
      { id: 'd', text: `Cultural relativism`, isCorrect: false, rationale: `Cultural relativism judges behavior within its own cultural context, which he fails to do.` },
    ],
    rationale: `Wrenn introduced the term cultural encapsulation to describe counselors who substitute their own cultural assumptions for reality and ignore cultural variation among clients. Encapsulated counselors define normal behavior by their own culture and may pathologize clients whose values differ, such as collectivistic decision making. Developing awareness of one's own cultural values and biases is the first multicultural competency for this reason.`,
    references: [{ source: SS, detail: 'Multicultural counseling competence: cultural encapsulation of the counselor (Wrenn)' }],
  },

  // ── RACIAL AND CULTURAL IDENTITY MODELS ──────────────────────────────────
  {
    id: 'nce-s-cou-359',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'medium',
    stem: `After a diversity workshop left him feeling guilty and confused, a White graduate student now says that people of color "bring most of their problems on themselves" and that White people are unfairly blamed. He avoids the classmates of color he had begun to befriend. In Helms's White racial identity model, which status does this reflect?`,
    options: [
      { id: 'a', text: `Contact`, isCorrect: false, rationale: `Contact involves naive obliviousness to race, before the guilt and confusion he has experienced.` },
      { id: 'b', text: `Reintegration`, isCorrect: true, rationale: `Retreating from guilt into idealizing Whites and blaming people of color marks reintegration.` },
      { id: 'c', text: `Pseudo-independence`, isCorrect: false, rationale: `Pseudo-independence involves an intellectual rejection of racism, not blaming people of color.` },
      { id: 'd', text: `Autonomy`, isCorrect: false, rationale: `Autonomy reflects a secure, nonracist White identity and openness to difference.` },
    ],
    rationale: `Helms's statuses are contact, disintegration, reintegration, pseudo-independence, immersion/emersion and autonomy. In reintegration, a person resolves the discomfort of disintegration by retreating into beliefs that favor Whites and blame people of color for their problems. Counselors can help by gently challenging these beliefs while supporting the person through the guilt that triggered them.`,
    references: [{ source: SS, detail: 'White racial identity development: Helms\'s reintegration status' }],
  },
  {
    id: 'nce-s-cou-360',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: `A 16-year-old with a Filipino mother and a Black father decided last year to identify only as Black among friends. She now tells her counselor she feels guilty and disloyal when she avoids her mother's relatives and hides her Filipino heritage at school. According to Poston's biracial identity model, which stage is she in?`,
    options: [
      { id: 'a', text: `Personal identity`, isCorrect: false, rationale: `Personal identity is the early childhood stage, when identity rests on personal traits rather than group.` },
      { id: 'b', text: `Appreciation`, isCorrect: false, rationale: `In appreciation, she would begin to value and explore both heritages instead of hiding one.` },
      { id: 'c', text: `Integration`, isCorrect: false, rationale: `Integration involves recognizing and valuing all of her racial and ethnic identities.` },
      { id: 'd', text: `Enmeshment/denial`, isCorrect: true, rationale: `Guilt, confusion and disloyalty after choosing one heritage over the other define enmeshment/denial.` },
    ],
    rationale: `Poston's model of biracial identity runs from personal identity through choice of group categorization, enmeshment/denial and appreciation to integration. In enmeshment/denial, a person who has chosen one group feels guilt, confusion or self-hatred about not being able to express the other part of their heritage. Counselors can help resolve this guilt so the person moves toward appreciating and integrating both identities.`,
    references: [{ source: 'Poston (Biracial Identity)', detail: 'Stage 3, enmeshment/denial' }, { source: SS, detail: 'Racial/cultural identity development: biracial and multiracial identity (Poston\'s model)' }],
  },
];
