// tools/nce/seed/counseling-10.js — Counseling Skills and Interventions, batch 5 (part 2)
// Hand-authored original items (nce-s-cou-271 … nce-s-cou-300).
const GL = 'Gladding (Counseling: A Comprehensive Profession)';
const YL = 'Yalom & Leszcz (Group Psychotherapy)';
const SH = 'Sharf (Career Development Theory)';
const BK = 'Berk (Development Through the Lifespan)';
const SS = 'Sue & Sue (Counseling the Culturally Diverse)';

module.exports = [
  // ── GROUP: STAGES AND DYNAMICS ───────────────────────────────────────────
  {
    id: 'nce-s-cou-271',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'In the first two sessions of a closed group for adults coping with job loss, members talk politely about safe topics, look to the leader for direction and quietly test whether it is safe to share. According to Corey\'s model of group development, which stage is this group MOST likely in?',
    options: [
      { id: 'a', text: 'Transition stage', isCorrect: false, rationale: 'The transition stage is marked by open anxiety, defensiveness, conflict and challenges to the leader, not polite caution.' },
      { id: 'b', text: 'Working stage', isCorrect: false, rationale: 'The working stage features trust, cohesion and deep self-disclosure, which this group has not yet reached.' },
      { id: 'c', text: 'Initial stage', isCorrect: true, rationale: 'Orientation, tentative and superficial sharing, reliance on the leader and testing of trust define the initial stage.' },
      { id: 'd', text: 'Final stage', isCorrect: false, rationale: 'The final stage involves consolidating learning and preparing to end, which does not fit a group in its first sessions.' },
    ],
    rationale: 'Corey describes groups moving from a pregroup stage through initial, transition, working and final stages. In the initial stage members orient themselves, share cautiously, look to the leader for structure and test whether the group is a safe place. Leaders help by clarifying norms and goals and modeling openness so that trust can develop.',
    references: [{ source: GL, detail: 'Groups in counseling: stages of group development (initial stage)' }],
  },
  {
    id: 'nce-s-cou-272',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'After several tense sessions in which members argued and challenged the leader, a workplace communication group begins agreeing on how to give feedback. Members start supporting each other and speak of the group as "we." According to Tuckman, which stage has the group entered?',
    options: [
      { id: 'a', text: 'Norming', isCorrect: true, rationale: 'Norming follows storming: the group settles on shared rules, cohesion grows and members begin to support one another.' },
      { id: 'b', text: 'Performing', isCorrect: false, rationale: 'Performing comes after norming, when roles are flexible and the group\'s energy goes mainly into productive work.' },
      { id: 'c', text: 'Forming', isCorrect: false, rationale: 'Forming is the opening stage of orientation and dependence on the leader, which this group has passed.' },
      { id: 'd', text: 'Adjourning', isCorrect: false, rationale: 'Adjourning, added later by Tuckman and Jensen, concerns ending the group and is not described here.' },
    ],
    rationale: 'Tuckman\'s sequence is forming, storming, norming and performing, with adjourning added later with Jensen. After the conflict of storming, a group that works through its disagreements develops shared norms, cohesion and a sense of "we" in the norming stage. Performing follows, when the group can focus its energy on its task.',
    references: [{ source: GL, detail: 'Groups in counseling: Tuckman\'s stages of group development' }],
  },
  {
    id: 'nce-s-cou-273',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'A closed 10-week counseling group for college students has two sessions left. Which leader focus BEST fits Corey\'s description of the tasks of the final stage?',
    options: [
      { id: 'a', text: 'Introducing deeper confrontation so that members can open up new core issues to work on', isCorrect: false, rationale: 'Opening major new issues near the end leaves members with work they cannot finish in the time left.' },
      { id: 'b', text: 'Reviewing ground rules and helping each member define personal goals for the coming weeks', isCorrect: false, rationale: 'Setting ground rules and goals are initial-stage tasks, not tasks for the last two sessions.' },
      { id: 'c', text: 'Encouraging members to challenge the leader\'s authority so that hidden conflict can surface', isCorrect: false, rationale: 'Challenges to the leader are typical of the transition stage and are not a final-stage aim.' },
      { id: 'd', text: 'Helping members consolidate learning, voice feelings about ending and plan to apply gains', isCorrect: true, rationale: 'Consolidating learning, dealing with feelings about separation and planning transfer to daily life are core final-stage tasks.' },
    ],
    rationale: 'In the final stage, the leader helps members review what they have learned, express feelings about the group ending, finish unfinished business and plan how to carry changes into their lives. Leaders avoid opening major new issues that cannot be worked through. Follow-up after the group can support transfer of learning.',
    references: [{ source: GL, detail: 'Groups in counseling: termination of a group and the final stage' }],
  },
  {
    id: 'nce-s-cou-274',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A hospital counselor chairs a committee of nurses, chaplains and social workers that meets monthly to develop a new discharge-planning protocol. Under the Association for Specialists in Group Work (ASGW) classification of groups, this is BEST described as which type?',
    options: [
      { id: 'a', text: 'Psychoeducation group', isCorrect: false, rationale: 'Psychoeducation groups teach information and skills to members to prevent problems or build coping.' },
      { id: 'b', text: 'Task and work group', isCorrect: true, rationale: 'Task and work groups, such as committees and planning teams, exist to accomplish a defined work goal.' },
      { id: 'c', text: 'Counseling group', isCorrect: false, rationale: 'Counseling groups address members\' personal and interpersonal concerns, not an organizational product.' },
      { id: 'd', text: 'Psychotherapy group', isCorrect: false, rationale: 'Psychotherapy groups treat members with more serious or long-standing psychological problems.' },
    ],
    rationale: 'ASGW identifies four group work specializations: task and work groups, psychoeducation groups, counseling groups and psychotherapy groups. A committee meeting to produce a protocol is a task group, because its purpose is to complete work rather than to change members personally. Leaders of task groups attend to both the task and the group\'s process.',
    references: [{ source: GL, detail: 'Groups in counseling: types of groups (task/work, psychoeducational, counseling, psychotherapy)' }],
  },
  {
    id: 'nce-s-cou-275',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: 'A counselor runs an open-ended outpatient therapy group. A new member will join next week, and several veteran members worry that "starting over" will slow the group down. What is the BEST way to bring the newcomer in?',
    options: [
      { id: 'a', text: 'Prepare the newcomer beforehand and let veteran members convey the group\'s norms and work', isCorrect: true, rationale: 'Pre-group preparation plus the veterans\' modeling lets the newcomer learn the culture while the group keeps working.' },
      { id: 'b', text: 'Pause the group\'s ongoing themes for several weeks so the newcomer can catch up on its history', isCorrect: false, rationale: 'Halting the group\'s work to review history frustrates veterans and is not needed for the newcomer to join.' },
      { id: 'c', text: 'Ask the newcomer to stay silent and only observe for the first few sessions before taking part', isCorrect: false, rationale: 'Enforced silence isolates the newcomer and delays the engagement that helps a new member settle in.' },
      { id: 'd', text: 'Tell the veterans their worry is unfounded and move straight back to the planned session topic', isCorrect: false, rationale: 'Dismissing the veterans\' reactions misses useful here-and-now material about change in the group.' },
    ],
    rationale: 'In open groups, new members are prepared individually before joining, and veteran members usually transmit the group\'s norms quickly by example. The group does not need to stop its work, and members\' reactions to a newcomer, such as worry or rivalry, can be explored as here-and-now material.',
    references: [{ source: YL, detail: 'Problems of membership: adding new members to an ongoing group' }],
  },

  // ── GROUP: LEADERSHIP AND THERAPEUTIC FACTORS ────────────────────────────
  {
    id: 'nce-s-cou-276',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: 'In a substance use recovery group, a new member says, "Hearing Rosa talk about two years sober makes me think I might actually get there too." Which of Yalom\'s therapeutic factors is MOST evident?',
    options: [
      { id: 'a', text: 'Universality', isCorrect: false, rationale: 'Universality is relief at learning others share one\'s problems, not optimism drawn from another\'s progress.' },
      { id: 'b', text: 'Imitative behavior', isCorrect: false, rationale: 'Imitative behavior means copying another\'s behaviors; the member describes hope, not modeling a skill.' },
      { id: 'c', text: 'Instillation of hope', isCorrect: true, rationale: 'Seeing a member who has improved with the same problem builds belief that one\'s own recovery is possible.' },
      { id: 'd', text: 'Development of socializing techniques', isCorrect: false, rationale: 'This factor concerns learning basic social skills, which is not what the member describes.' },
    ],
    rationale: 'Instillation of hope is the belief that the group can help, and it grows when members see others further along in recovery. Yalom notes that self-help and recovery groups lean heavily on this factor by featuring members who have succeeded. Hope keeps members in treatment long enough for other factors to work.',
    references: [{ source: YL, detail: 'The therapeutic factors: instillation of hope' }],
  },
  {
    id: 'nce-s-cou-277',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'A retired teacher in a depression group says the best part of the group was learning that her encouragement helped another member apply for a job: "For the first time in months, I feel useful to someone." Which of Yalom\'s therapeutic factors does this BEST illustrate?',
    options: [
      { id: 'a', text: 'Universality', isCorrect: false, rationale: 'Universality is discovering that others share one\'s problems; she is describing the value of helping.' },
      { id: 'b', text: 'Altruism', isCorrect: true, rationale: 'Being able to help another member raises self-worth and pulls the helper out of self-absorption.' },
      { id: 'c', text: 'Catharsis', isCorrect: false, rationale: 'Catharsis is the release of strong feeling, which is not the source of her sense of usefulness.' },
      { id: 'd', text: 'Imparting information', isCorrect: false, rationale: 'Imparting information is didactic teaching or advice received, not the benefit of giving help to others.' },
    ],
    rationale: 'Yalom\'s altruism factor holds that members benefit from giving as well as receiving: offering support, insight and encouragement shows them they have something of value to others. This is especially powerful for people with depression or low self-esteem who see themselves as a burden.',
    references: [{ source: YL, detail: 'The therapeutic factors: altruism' }],
  },
  {
    id: 'nce-s-cou-278',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: 'Late in a cancer survivors\' group, a member says the group taught him that however much support he receives, he must still face his own mortality and take ultimate responsibility for how he lives. Which of Yalom\'s therapeutic factors does this BEST reflect?',
    options: [
      { id: 'a', text: 'Universality', isCorrect: false, rationale: 'Universality is the relief that others share one\'s problems; his insight is about facing life alone and choosing.' },
      { id: 'b', text: 'Catharsis', isCorrect: false, rationale: 'Catharsis is emotional release; his statement describes an insight about mortality and responsibility.' },
      { id: 'c', text: 'Interpersonal learning', isCorrect: false, rationale: 'Interpersonal learning is about how one affects and is seen by others, not about existential givens.' },
      { id: 'd', text: 'Existential factors', isCorrect: true, rationale: 'Recognizing mortality, aloneness and ultimate responsibility for one\'s life defines the existential factors.' },
    ],
    rationale: 'Yalom\'s existential factors include recognizing that life can be unfair, that pain and death cannot be escaped, that one faces life alone however close one is to others, and that one is ultimately responsible for how one lives. Members of groups facing serious illness often rank these factors highly. The distractors name other factors with a different focus.',
    references: [{ source: YL, detail: 'The therapeutic factors: existential factors' }],
  },
  {
    id: 'nce-s-cou-279',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: 'In the fifth session of a support group for new parents, one member has said little since the first meeting, though she listens closely and nods often as others talk. Which leader response is BEST?',
    options: [
      { id: 'a', text: 'Note her nonverbal reactions and invite her, without pressure, to share what is resonating', isCorrect: true, rationale: 'Drawing out a quiet member gently, using what the leader observes, invites participation while respecting her pace.' },
      { id: 'b', text: 'Ask the other members to wait in silence until she takes a turn and speaks to the group today', isCorrect: false, rationale: 'Putting her on the spot in front of the group creates pressure and can increase her withdrawal.' },
      { id: 'c', text: 'Tell her privately after the session that she must speak up more if she wants to stay in the group', isCorrect: false, rationale: 'A coercive ultimatum violates members\' right to decide what they share and damages trust.' },
      { id: 'd', text: 'Leave her alone, since a quiet member is unaffected by the group and unlikely to benefit from it', isCorrect: false, rationale: 'Silent members can be deeply engaged; ignoring her misses a chance to include her and learn what silence means.' },
    ],
    rationale: 'Silence can reflect anxiety, cultural norms, deep engagement or feeling unwelcome, so leaders explore it rather than assume. Drawing out is a leadership skill that invites a quiet member to participate, often by noting observable reactions, while respecting the member\'s right to choose what to share. Pressuring or ignoring the member are both unhelpful.',
    references: [{ source: GL, detail: 'Groups in counseling: leadership skills and problem behaviors (silent members, drawing out)' }],
  },
  {
    id: 'nce-s-cou-280',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: 'In a high school counseling group, a member starts describing in detail what an absent member\'s boyfriend supposedly did at a party, and other members lean in to hear more. Which leader skill is MOST needed right now?',
    options: [
      { id: 'a', text: 'Linking', isCorrect: false, rationale: 'Linking connects members\' shared concerns; it would not stop harmful talk about an absent member.' },
      { id: 'b', text: 'Drawing out', isCorrect: false, rationale: 'Drawing out invites quieter members to speak, which would add to the gossip rather than stop it.' },
      { id: 'c', text: 'Summarizing', isCorrect: false, rationale: 'Summarizing pulls themes together; it does not intervene in a counterproductive behavior.' },
      { id: 'd', text: 'Blocking', isCorrect: true, rationale: 'Blocking stops counterproductive behavior such as gossip or invading an absent member\'s privacy.' },
    ],
    rationale: 'Blocking is the leader\'s intervention to stop behavior that harms members or the group, such as gossiping, breaking confidentiality, scapegoating or pressuring disclosure. The leader blocks the behavior, not the person, and can redirect the speaker toward her own feelings in the here and now.',
    references: [{ source: GL, detail: 'Groups in counseling: group leadership skills (blocking)' }],
  },

  // ── CAREER DEVELOPMENT THEORIES ──────────────────────────────────────────
  {
    id: 'nce-s-cou-281',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'An 11-year-old tells his counselor he has crossed hairstylist and bus driver off his list because "people in my family go to college and get important jobs." In Gottfredson\'s theory of circumscription and compromise, this reasoning reflects which stage?',
    options: [
      { id: 'a', text: 'Orientation to size and power', isCorrect: false, rationale: 'This first stage (about ages 3 to 5) involves seeing jobs as adult roles, not ranking them by status.' },
      { id: 'b', text: 'Orientation to sex roles', isCorrect: false, rationale: 'At about ages 6 to 8 children rule out jobs as wrong for their gender, which is not his reason here.' },
      { id: 'c', text: 'Orientation to social valuation', isCorrect: true, rationale: 'At about ages 9 to 13 children rule out jobs seen as too low in prestige for their social class or ability.' },
      { id: 'd', text: 'Orientation to internal unique self', isCorrect: false, rationale: 'From about age 14, youth weigh interests, values and personality within the options left, a later stage.' },
    ],
    rationale: 'Gottfredson proposed that children progressively eliminate (circumscribe) occupations: first by size and power, then by sex type, then by prestige and social valuation, and finally by fit with the internal, unique self. Around ages 9 to 13, children become aware of social class and set a floor of acceptable prestige, ruling out jobs seen as beneath their family\'s expectations.',
    references: [{ source: SH, detail: 'Gottfredson\'s theory of circumscription and compromise: stages of circumscription' }],
  },
  {
    id: 'nce-s-cou-282',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'Using the CASVE cycle from the cognitive information processing approach, a counselor has helped a client understand her values, skills and the options open to her. They now expand her list of possible occupations and then narrow it to three or four realistic choices. Which phase are they in?',
    options: [
      { id: 'a', text: 'Analysis', isCorrect: false, rationale: 'Analysis, the step already completed, builds understanding of self and options.' },
      { id: 'b', text: 'Synthesis', isCorrect: true, rationale: 'Synthesis elaborates options and then crystallizes them into a short list of realistic choices.' },
      { id: 'c', text: 'Valuing', isCorrect: false, rationale: 'Valuing comes next, weighing each short-listed option\'s costs and benefits for self and others.' },
      { id: 'd', text: 'Communication', isCorrect: false, rationale: 'Communication is the first phase, when a person recognizes a gap between where they are and want to be.' },
    ],
    rationale: 'The CASVE cycle of Sampson, Peterson, Lenz and Reardon moves through Communication, Analysis, Synthesis, Valuing and Execution. In Synthesis, the person first elaborates possible options and then crystallizes them into a manageable set of about three to five. Valuing then ranks those options, and Execution turns the first choice into an action plan.',
    references: [{ source: SH, detail: 'Cognitive information processing approach: the CASVE cycle' }],
  },
  {
    id: 'nce-s-cou-283',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'hard',
    stem: 'In Savickas\'s career construction interview, a counselor asks a client whom she admired when she was growing up, other than her parents. According to career construction theory, what do her answers MOST directly reveal?',
    options: [
      { id: 'a', text: 'The occupations her parents expected her to enter and how she has met those expectations', isCorrect: false, rationale: 'The question deliberately excludes parents; it targets figures she chose for herself.' },
      { id: 'b', text: 'Her current level of career adaptability across concern, control, curiosity and confidence', isCorrect: false, rationale: 'Adaptability resources are assessed separately; the role model question is about self-concept.' },
      { id: 'c', text: 'Her self-concept: the traits she has chosen as a blueprint for the self she is constructing', isCorrect: true, rationale: 'Role models reveal the qualities a person has chosen to incorporate, a blueprint for self-construction.' },
      { id: 'd', text: 'Her Holland code, since admired figures predict which work setting will be most congruent', isCorrect: false, rationale: 'Magazines and favorite settings point to preferred work environments; role models speak to the self.' },
    ],
    rationale: 'In Savickas\'s career construction interview, early role models are treated as a blueprint for the self: the traits a client admired are ones she has chosen to build into her own identity. Other questions, such as favorite magazines or television shows, point to preferred work settings, and early recollections reveal life themes or preoccupations. Together they help the client author a coherent career story.',
    references: [{ source: SH, detail: 'Savickas\'s career construction theory: the career construction interview and role models' }],
  },
  {
    id: 'nce-s-cou-284',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: 'A 21-year-old who earlier explored several fields has committed to nursing and is now deciding to specialize in pediatric intensive care. In Ginzberg, Ginsburg, Axelrad and Herma\'s theory, she is in which substage of the realistic period?',
    options: [
      { id: 'a', text: 'Specification', isCorrect: true, rationale: 'Specification is the final realistic substage, when a person selects a specific job or specialty.' },
      { id: 'b', text: 'Crystallization', isCorrect: false, rationale: 'Crystallization is committing to a general field, which she has already done by choosing nursing.' },
      { id: 'c', text: 'Exploration', isCorrect: false, rationale: 'Exploration is the first realistic substage, when options are still being sampled broadly.' },
      { id: 'd', text: 'Transition', isCorrect: false, rationale: 'Transition is the last substage of the tentative period in adolescence, not of the realistic period.' },
    ],
    rationale: 'Ginzberg and colleagues described fantasy, tentative and realistic periods of career choice. The tentative period includes interest, capacity, value and transition substages. The realistic period, from about age 17 into the early twenties, moves through exploration, crystallization around a field and specification of a particular job or specialty.',
    references: [{ source: SH, detail: 'Developmental theories: Ginzberg and colleagues\' periods of career choice' }],
  },

  // ── HUMAN DEVELOPMENT THEORIES ───────────────────────────────────────────
  {
    id: 'nce-s-cou-285',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A 20-year-old says he has not thought much about what he wants in a career, religion or politics, has no plans and does not see why it matters. He is not distressed about this. Which of Marcia\'s identity statuses BEST fits?',
    options: [
      { id: 'a', text: 'Identity moratorium', isCorrect: false, rationale: 'Moratorium involves active exploration without commitment, often with some anxiety.' },
      { id: 'b', text: 'Identity foreclosure', isCorrect: false, rationale: 'Foreclosure is commitment without exploration, usually to values taken from parents.' },
      { id: 'c', text: 'Identity achievement', isCorrect: false, rationale: 'Achievement follows exploration with firm commitments, neither of which he shows.' },
      { id: 'd', text: 'Identity diffusion', isCorrect: true, rationale: 'Diffusion is neither exploring nor committing, often with apathy about identity questions.' },
    ],
    rationale: 'Marcia classified identity status by two dimensions: exploration and commitment. Achievement has both, moratorium has exploration without commitment, foreclosure has commitment without exploration, and diffusion has neither. Diffused young people often seem aimless or unconcerned about who they are becoming.',
    references: [{ source: BK, detail: 'Adolescence: Marcia\'s identity statuses' }],
  },
  {
    id: 'nce-s-cou-286',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A school counselor sets up regular meetings between a 9-year-old\'s parents and his teacher so that home and school follow the same homework and behavior plan. In Bronfenbrenner\'s ecological systems theory, the counselor is strengthening which system?',
    options: [
      { id: 'a', text: 'Microsystem', isCorrect: false, rationale: 'Each setting alone, home or classroom, is a microsystem; the links between them are something more.' },
      { id: 'b', text: 'Mesosystem', isCorrect: true, rationale: 'The mesosystem is the set of connections between microsystems, such as home and school.' },
      { id: 'c', text: 'Exosystem', isCorrect: false, rationale: 'The exosystem holds settings the child is not in that affect him, such as a parent\'s workplace.' },
      { id: 'd', text: 'Macrosystem', isCorrect: false, rationale: 'The macrosystem is the broad culture, values and laws, not specific home-school links.' },
    ],
    rationale: 'Bronfenbrenner described nested systems: the microsystem of immediate settings, the mesosystem of connections among those settings, the exosystem of settings that affect the child indirectly, the macrosystem of cultural values and laws, and the chronosystem of change over time. Strong home-school partnerships are a classic mesosystem support.',
    references: [{ source: BK, detail: 'History, theory and research strategies: Bronfenbrenner\'s ecological systems theory' }],
  },
  {
    id: 'nce-s-cou-287',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'hard',
    stem: 'An 8-year-old explains that he shares his snack with a classmate "because then she\'ll share her cookies with me tomorrow." For him, right action is whatever serves his own interests through fair trades. In Kohlberg\'s theory, this reasoning BEST fits which stage orientation?',
    options: [
      { id: 'a', text: 'Punishment and obedience', isCorrect: false, rationale: 'Stage 1 reasoning centers on avoiding punishment from authority, not on making even trades.' },
      { id: 'b', text: 'Interpersonal conformity', isCorrect: false, rationale: 'Stage 3 reasoning seeks approval as a good person and to maintain relationships.' },
      { id: 'c', text: 'Instrumental exchange', isCorrect: true, rationale: 'Stage 2 sees right action as meeting one\'s own needs through fair, tit-for-tat exchanges.' },
      { id: 'd', text: 'Social contract orientation', isCorrect: false, rationale: 'Stage 5 views laws as flexible agreements serving the greater good, far beyond this reasoning.' },
    ],
    rationale: 'Kohlberg\'s preconventional level has two stages: Stage 1, punishment and obedience, and Stage 2, the instrumental purpose orientation, in which right action is what satisfies one\'s own needs, often through equal exchange ("you scratch my back, I\'ll scratch yours"). Conventional reasoning (Stages 3 and 4) shifts toward approval and social order.',
    references: [{ source: BK, detail: 'Moral development: Kohlberg\'s preconventional level (Stage 2, instrumental purpose orientation)' }],
  },
  {
    id: 'nce-s-cou-288',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'hard',
    stem: 'A 5-year-old talks aloud to herself while working on a difficult puzzle ("No, the corner piece goes here first...") and talks more as the task gets harder. How would Vygotsky MOST likely interpret this behavior?',
    options: [
      { id: 'a', text: 'As self-guiding speech that helps her plan and that will later become silent inner speech', isCorrect: true, rationale: 'Vygotsky saw private speech as a tool for self-regulation that rises with task difficulty and is later internalized.' },
      { id: 'b', text: 'As egocentric speech that shows she cannot yet take the perspective of a nearby listener', isCorrect: false, rationale: 'This is Piaget\'s view of such speech, which Vygotsky disputed.' },
      { id: 'c', text: 'As a sign of possible language delay that calls for a speech-language evaluation soon', isCorrect: false, rationale: 'Private speech is typical in the preschool years and is not a sign of delay.' },
      { id: 'd', text: 'As attention-seeking behavior that adults should ignore so that it decreases over time', isCorrect: false, rationale: 'The child is directing her own actions, not seeking attention, so ignoring it misreads its purpose.' },
    ],
    rationale: 'Piaget called children\'s self-talk egocentric speech, reflecting an inability to take others\' perspectives. Vygotsky argued instead that this private speech is a tool for guiding thought and behavior, increases when tasks are challenging, and gradually becomes silent inner speech. Research has generally supported Vygotsky\'s view.',
    references: [{ source: BK, detail: 'Early childhood cognition: Vygotsky\'s private speech versus Piaget\'s egocentric speech' }],
  },

  // ── ATTACHMENT THEORY ────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-289',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'easy',
    stem: 'In the Strange Situation, a 12-month-old explores the toys with little attention to his mother, shows little distress when she leaves and, when she returns, looks away and does not seek contact. Which attachment classification BEST fits?',
    options: [
      { id: 'a', text: 'Secure', isCorrect: false, rationale: 'Secure infants use the parent as a base, may be upset at separation and seek comfort on reunion.' },
      { id: 'b', text: 'Resistant (ambivalent)', isCorrect: false, rationale: 'Resistant infants are highly distressed at separation and both seek and resist contact on reunion.' },
      { id: 'c', text: 'Disorganized', isCorrect: false, rationale: 'Disorganized infants show confused or contradictory behavior such as freezing or dazed looks.' },
      { id: 'd', text: 'Avoidant', isCorrect: true, rationale: 'Avoidant infants show little separation distress and avoid or ignore the parent on reunion.' },
    ],
    rationale: 'Ainsworth\'s Strange Situation classifies infants mainly by reunion behavior. Avoidant infants seem unresponsive to the parent, are not distressed by separation and turn away on return; this pattern is linked to caregiving that rebuffs bids for comfort. Main and Solomon later added the disorganized category.',
    references: [{ source: BK, detail: 'Emotional and social development in infancy: measuring attachment security (the Strange Situation)' }],
  },
  {
    id: 'nce-s-cou-290',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'medium',
    stem: 'Ainsworth\'s home observations linked infants\' later attachment classifications to how their caregivers had responded during the first year. Which caregiving pattern is MOST strongly associated with secure attachment?',
    options: [
      { id: 'a', text: 'Responding to each whimper at once so that the infant rarely experiences any distress at all', isCorrect: false, rationale: 'Sensitivity is about accurate, well-matched responses, not removing all distress.' },
      { id: 'b', text: 'Holding the infant as many hours as possible, whatever signals the infant may be giving', isCorrect: false, rationale: 'Contact that ignores the infant\'s cues is intrusive rather than sensitive.' },
      { id: 'c', text: 'Noticing the infant\'s signals, reading them accurately and responding promptly and fittingly', isCorrect: true, rationale: 'Sensitive responsiveness, as Ainsworth defined it, is the caregiving feature most tied to secure attachment.' },
      { id: 'd', text: 'Giving consistent physical care on a fixed schedule while limiting emotional responsiveness', isCorrect: false, rationale: 'Routine care with little emotional responsiveness is more consistent with avoidant patterns.' },
    ],
    rationale: 'Ainsworth found that sensitive caregiving, meaning noticing the infant\'s signals, interpreting them accurately and responding promptly and appropriately, predicted secure attachment. Inconsistent care was linked to resistant attachment, and rejecting or emotionally unavailable care to avoidant attachment. Research since then shows a moderate link between sensitivity and security.',
    references: [{ source: BK, detail: 'Emotional and social development in infancy: factors that affect attachment security (quality of caregiving)' }],
  },

  // ── HELPING SKILLS ───────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-291',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'easy',
    stem: 'A client mentions that she skipped her sister\'s wedding. The counselor asks, "Why did you do that?" and the client becomes guarded. What is the MOST likely problem with the counselor\'s question?',
    options: [
      { id: 'a', text: '"Why" questions can sound judgmental and lead the client to defend or justify herself', isCorrect: true, rationale: '"Why" questions often imply criticism and invite explanations and defensiveness rather than exploration.' },
      { id: 'b', text: 'It is a closed question, so it limits the client to a brief yes-or-no type of response', isCorrect: false, rationale: 'A "why" question is open, not closed; the problem is its judgmental tone.' },
      { id: 'c', text: 'It shifts the focus from the client\'s own experience to her sister\'s needs and feelings', isCorrect: false, rationale: 'The question stays on the client\'s actions; it does not shift focus to the sister.' },
      { id: 'd', text: 'It asks about the past, and counselors should limit questions to the present moment', isCorrect: false, rationale: 'Exploring past events is often useful; the timing of the event is not the issue.' },
    ],
    rationale: 'Questions beginning with "why" tend to put clients on the defensive because they can sound like a demand for justification. "What" and "how" questions, such as "What led to that decision?", invite description and exploration. Counselors also avoid strings of questions that make a session feel like an interrogation.',
    references: [{ source: GL, detail: 'Counseling skills: questions and the problems with "why" questions' }],
  },
  {
    id: 'nce-s-cou-292',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'medium',
    stem: 'Reviewing a recording, a supervisor notes that a trainee often changes the subject, jumping to topics that interest the trainee instead of staying with what the client just said. Which component of Ivey\'s attending behavior should the trainee practice?',
    options: [
      { id: 'a', text: 'Eye contact', isCorrect: false, rationale: 'Eye contact is a visual attending behavior; the problem described is in what the trainee says.' },
      { id: 'b', text: 'Vocal qualities', isCorrect: false, rationale: 'Vocal qualities concern tone, pace and volume rather than the topics the trainee follows.' },
      { id: 'c', text: 'Verbal tracking', isCorrect: true, rationale: 'Verbal tracking means staying with the client\'s topic and not jumping to new subjects.' },
      { id: 'd', text: 'Body language', isCorrect: false, rationale: 'Posture and gestures matter, but they do not address topic jumping in the trainee\'s speech.' },
    ],
    rationale: 'Ivey describes attending behavior through visuals (eye contact), vocal qualities, verbal tracking and attentive body language. Verbal tracking means following the client\'s story without topic jumps, which shows the client that the counselor is listening. Counselors also notice which topics they selectively attend to.',
    references: [{ source: GL, detail: 'Counseling skills: attending behavior and Ivey\'s microskills (verbal tracking)' }],
  },
  {
    id: 'nce-s-cou-293',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: 'A 70-year-old client says, "Moving in with my daughter means I\'ll see my grandkids every day. But I\'m giving up the house I lived in for forty years." Which response BEST reflects the client\'s feelings?',
    options: [
      { id: 'a', text: 'You will get to see your grandchildren every day once you move in with your daughter.', isCorrect: false, rationale: 'This paraphrases part of the content and leaves out both the feelings and the loss.' },
      { id: 'b', text: 'Have you thought about whether you could keep the house and visit the family more often?', isCorrect: false, rationale: 'This question moves to problem solving before the client\'s feelings have been heard.' },
      { id: 'c', text: 'Many people your age move in with family, and most adjust well within the first year.', isCorrect: false, rationale: 'Reassurance with a generalization minimizes the client\'s feelings and may sound ageist.' },
      { id: 'd', text: 'You\'re looking forward to being near the grandkids, and also grieving leaving your home.', isCorrect: true, rationale: 'This captures both sides of the client\'s mixed feelings without choosing between them.' },
    ],
    rationale: 'Clients often express mixed or contradictory feelings about one event. An accurate reflection of feeling names both emotions and links them to their sources, often with "and" rather than "but" so that neither feeling cancels the other. Paraphrasing content, advising or reassuring misses the emotional message.',
    references: [{ source: GL, detail: 'Counseling skills: reflection of feeling and mixed emotions' }],
  },
  {
    id: 'nce-s-cou-294',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: 'A counselor paraphrases, "So you\'re angry that your boss ignored your idea in the meeting." The client pauses and says, "Not angry, really. More like invisible." What is the BEST next response from the counselor?',
    options: [
      { id: 'a', text: 'Explain that anger is a common reaction to being ignored and is often hidden under hurt', isCorrect: false, rationale: 'Insisting on the counselor\'s label overrides the client\'s correction and weakens the alliance.' },
      { id: 'b', text: 'Accept the correction: "Invisible, as if your ideas don\'t register. Did I get that right?"', isCorrect: true, rationale: 'Taking in the correction and checking accuracy keeps the reflection client-centered and builds trust.' },
      { id: 'c', text: 'Move on to problem solving so that the client does not feel stuck on the word choice itself', isCorrect: false, rationale: 'Skipping past the correction misses the client\'s more precise and meaningful feeling.' },
      { id: 'd', text: 'Ask the client to describe a time she felt angry at work so the anger can be explored more', isCorrect: false, rationale: 'This pursues the counselor\'s hypothesis rather than the feeling the client has just named.' },
    ],
    rationale: 'Paraphrases and reflections are tentative hypotheses that the client can confirm or correct. When a client corrects one, the counselor accepts the new wording, reflects it and checks for accuracy (a "check-out"). Clients often refine their own understanding through this exchange, so a corrected reflection is still useful.',
    references: [{ source: GL, detail: 'Counseling skills: paraphrasing, accuracy and checking out' }],
  },
  {
    id: 'nce-s-cou-295',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'hard',
    stem: 'After a counselor gently points out a discrepancy, a client says, "Okay, I see that I keep missing my kids\' games, even though I say family comes first. I\'m still not sure what to do about it." On Ivey\'s Client Change Scale, this response is BEST classified as:',
    options: [
      { id: 'a', text: 'Denial', isCorrect: false, rationale: 'Denial would mean not seeing or refusing to admit the discrepancy, which the client openly accepts.' },
      { id: 'b', text: 'Partial examination', isCorrect: false, rationale: 'Partial examination involves working on only part of the discrepancy; he acknowledges all of it.' },
      { id: 'c', text: 'Acceptance and recognition', isCorrect: true, rationale: 'He fully accepts the discrepancy but has not yet generated a new way of acting.' },
      { id: 'd', text: 'Transcendence and new constructs', isCorrect: false, rationale: 'The top level involves new, larger ways of thinking and acting, which he has not reached.' },
    ],
    rationale: 'Ivey\'s Client Change Scale rates client responses to confrontation from denial (level 1), through partial examination (2), acceptance and recognition (3) and creation of a new solution (4), to transcendence or development of new, more inclusive constructs (5). A client who fully owns the discrepancy but has no plan yet is at level 3, and the counselor can now help generate new options.',
    references: [{ source: GL, detail: 'Counseling skills: confrontation and evaluating the client\'s response' }],
    reviewNote: 'Ivey\'s own text is not on the approved list; confirm the cited Gladding section covers the Client Change Scale levels.',
  },
  {
    id: 'nce-s-cou-296',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: 'Each session, a client asks her counselor what she should do and then thanks him warmly for "knowing best." The counselor notices he has begun giving advice he would not usually give. Which response BEST uses immediacy?',
    options: [
      { id: 'a', text: '"I notice we\'ve settled into a pattern where you ask and I answer. What\'s that like for you?"', isCorrect: true, rationale: 'Naming the pattern in their relationship as it happens and inviting her view is relationship immediacy.' },
      { id: 'b', text: '"You seem to rely on others for answers, and that likely began in your family growing up."', isCorrect: false, rationale: 'This is an interpretation about her past, not a here-and-now comment on their relationship.' },
      { id: 'c', text: '"Let\'s set a rule that I will not answer any more direct questions about what you should do."', isCorrect: false, rationale: 'Imposing a rule changes behavior without exploring what is happening between them.' },
      { id: 'd', text: '"You are capable of making good decisions, and I trust you to figure out what is best for you."', isCorrect: false, rationale: 'Reassurance may be kind, but it does not address the relational pattern the counselor noticed.' },
    ],
    rationale: 'Immediacy is the counselor\'s direct, present-tense comment on what is happening between counselor and client, often a pattern that mirrors the client\'s other relationships. Naming the pattern tentatively and inviting the client\'s experience opens it for exploration. It also helps the counselor step out of a role the client may be pulling him into.',
    references: [{ source: GL, detail: 'Counseling skills: immediacy' }],
  },
  {
    id: 'nce-s-cou-297',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'medium',
    stem: 'A client has met all of her counseling goals, but her counselor keeps suggesting "a few more sessions" because he enjoys their work and will miss her. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Keep meeting, since extra sessions are unlikely to harm a client who is doing well', isCorrect: false, rationale: 'Continuing counseling that no longer serves the client puts the counselor\'s needs ahead of hers.' },
      { id: 'b', text: 'Recognize his own reactions, consult a colleague and start planning a timely ending', isCorrect: true, rationale: 'Naming his countertransference, seeking consultation and moving toward termination protects the client.' },
      { id: 'c', text: 'Ask the client if she would like to keep coming monthly for some ongoing social support', isCorrect: false, rationale: 'Offering ongoing sessions for social contact blurs the professional role and serves the counselor.' },
      { id: 'd', text: 'End counseling at the next session without discussion so his feelings do not interfere', isCorrect: false, rationale: 'An abrupt ending without preparation denies the client a planned, collaborative termination.' },
    ],
    rationale: 'The ACA Code of Ethics directs counselors to end a counseling relationship when the client no longer needs or benefits from it. A counselor\'s own sadness or reluctance about ending is a form of countertransference that can prolong counseling for the counselor\'s benefit. Recognizing it, consulting and planning a well-prepared termination keeps the work centered on the client.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' },
      { source: GL, detail: 'Termination: counselor resistance to ending' },
    ],
  },

  // ── MULTICULTURAL COMPETENCE AND IDENTITY MODELS ─────────────────────────
  {
    id: 'nce-s-cou-298',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'hard',
    stem: 'A university counselor learns that several transgender students have been denied campus housing that matches their gender identity. She works with residence life administrators to revise the university\'s housing policy. In the MSJCC, this intervention targets which socioecological level?',
    options: [
      { id: 'a', text: 'Intrapersonal', isCorrect: false, rationale: 'Intrapersonal work addresses an individual\'s own thoughts, feelings and identity.' },
      { id: 'b', text: 'Interpersonal', isCorrect: false, rationale: 'Interpersonal work addresses relationships with family, friends and peers.' },
      { id: 'c', text: 'Public policy', isCorrect: false, rationale: 'Public policy refers to local, state and federal laws, not one university\'s internal rules.' },
      { id: 'd', text: 'Institutional', isCorrect: true, rationale: 'Changing the policies of a social institution such as a university is institutional-level advocacy.' },
    ],
    rationale: 'The Multicultural and Social Justice Counseling Competencies place counseling and advocacy interventions at socioecological levels: intrapersonal, interpersonal, institutional, community, public policy and international or global. Institutions include schools, universities, churches and agencies, so changing a university housing policy is institutional work. Public policy work targets laws and government policies.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling and advocacy interventions: socioecological levels (institutional)' }],
  },
  {
    id: 'nce-s-cou-299',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'medium',
    stem: 'A 13-year-old with a Black father and a White mother tells her school counselor that classmates keep asking "what she really is," and she feels she has to pick one racial group to belong to. In Poston\'s biracial identity development model, which stage BEST fits?',
    options: [
      { id: 'a', text: 'Personal identity', isCorrect: false, rationale: 'Personal identity is the early childhood stage, when self-concept rests on personal traits rather than group.' },
      { id: 'b', text: 'Choice of group categorization', isCorrect: true, rationale: 'In this stage, social pressure pushes a biracial youth to choose one racial or ethnic identity.' },
      { id: 'c', text: 'Enmeshment and denial', isCorrect: false, rationale: 'Enmeshment/denial follows the choice and brings guilt or confusion about rejecting one heritage.' },
      { id: 'd', text: 'Integration of both racial heritages', isCorrect: false, rationale: 'Integration is the final stage of valuing all of one\'s heritages, which she has not reached.' },
    ],
    rationale: 'Poston\'s five-stage model of biracial identity development runs from personal identity, through choice of group categorization, enmeshment/denial and appreciation, to integration. In the choice stage, peers, family and society press the young person to identify with one group. Counselors can validate the pressure and support exploration of all heritages.',
    references: [{ source: SS, detail: 'Racial/cultural identity development: biracial and multiracial identity (Poston\'s model)' }],
    reviewNote: 'Confirm that the Sue & Sue edition in use describes Poston\'s biracial model; no multiracial-specific text is on the approved list.',
  },
  {
    id: 'nce-s-cou-300',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: 'A White counseling student now rejects racism intellectually and seeks out classmates of color, often asking them to explain racism to her, while still judging their experiences by White norms. In Helms\'s White racial identity model, which status BEST fits?',
    options: [
      { id: 'a', text: 'Reintegration', isCorrect: false, rationale: 'Reintegration is a retreat to idealizing Whites and blaming people of color, which she has moved past.' },
      { id: 'b', text: 'Pseudo-independence', isCorrect: true, rationale: 'An intellectual commitment to racial justice while leaning on people of color and White standards marks this status.' },
      { id: 'c', text: 'Immersion and emersion', isCorrect: false, rationale: 'In immersion/emersion, she would turn to other Whites to explore what it means to be White.' },
      { id: 'd', text: 'Disintegration', isCorrect: false, rationale: 'Disintegration involves guilt, confusion and conflicting loyalties, not a settled intellectual stance.' },
    ],
    rationale: 'Helms\'s model moves from contact, disintegration and reintegration (abandoning racism) to pseudo-independence, immersion/emersion and autonomy (building a nonracist White identity). In pseudo-independence, a person accepts racial equality intellectually but still relies on people of color to explain racism and views them through White frames. Immersion/emersion shifts the focus to understanding one\'s own Whiteness.',
    references: [{ source: SS, detail: 'White racial identity development: Helms\'s White racial identity statuses' }],
  },
];
