// tools/nce/seed/counseling-9.js — Counseling Skills and Interventions, batch 5 (part 1)
// Hand-authored original items (nce-s-cou-241 … nce-s-cou-270).
const C = 'Corey (Theory & Practice)';
const G = 'Gladding (Counseling: A Comprehensive Profession)';

module.exports = [
  // ── GESTALT ──────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-241',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'medium',
    stem: 'A 34-year-old nurse works through a high fever because "real professionals do not take sick days," a rule her first charge nurse drilled into her. When her gestalt counselor asks whether she herself agrees with the rule, she looks puzzled and cannot say. Which contact boundary disturbance does this BEST illustrate?',
    options: [
      { id: 'a', text: 'Projection', isCorrect: false, rationale: 'Projection disowns parts of oneself by attributing them to others; she is not assigning her own traits to anyone.' },
      { id: 'b', text: 'Introjection', isCorrect: true, rationale: 'She has swallowed another person\'s standard whole, without chewing it over to decide whether it fits her.' },
      { id: 'c', text: 'Deflection', isCorrect: false, rationale: 'Deflection avoids contact through vagueness, humor or changing the subject; the issue here is an unexamined rule.' },
      { id: 'd', text: 'Retroflection', isCorrect: false, rationale: 'Retroflection turns onto oneself what one would like to do to others, such as self-blame in place of anger.' },
    ],
    rationale: 'Gestalt therapy describes disturbances at the contact boundary between person and environment. In introjection a person uncritically accepts the beliefs and standards of others without assimilating them, so the rules feel like "shoulds" that are not truly the person\'s own. Gestalt work helps the client become aware of introjects and decide which to keep and which to reject.',
    references: [{ source: C, detail: 'Gestalt Therapy: contact and resistances to contact (introjection)' }],
  },
  {
    id: 'nce-s-cou-242',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'easy',
    stem: 'While describing how her brother dismissed her at a family dinner, a client keeps making a small brushing-away motion with one hand. Her gestalt counselor asks her to make the motion larger and larger and then to give the hand a voice. Which technique is the counselor using?',
    options: [
      { id: 'a', text: 'Empty-chair dialogue', isCorrect: false, rationale: 'The empty chair has the client speak to an imagined person or part of the self, not amplify a gesture.' },
      { id: 'b', text: 'Making the rounds', isCorrect: false, rationale: 'Making the rounds is a group exercise in which a member speaks to or does something with each other member.' },
      { id: 'c', text: 'Reversal technique', isCorrect: false, rationale: 'Reversal asks the client to play the opposite of how they usually present, such as a shy client acting bold.' },
      { id: 'd', text: 'Exaggeration exercise', isCorrect: true, rationale: 'Exaggeration amplifies a small movement or gesture so the client becomes more aware of the feeling it carries.' },
    ],
    rationale: 'Gestalt counselors attend closely to nonverbal behavior as a clue to feelings outside awareness. In the exaggeration exercise the client repeats and enlarges a movement, posture or phrase, which intensifies the feeling attached to it and helps the client own what the body is expressing.',
    references: [{ source: C, detail: 'Gestalt Therapy: techniques (the exaggeration exercise)' }],
  },
  {
    id: 'nce-s-cou-243',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'hard',
    stem: 'Midway through a session, a client says, "I\'m stuck. I don\'t know what I feel, and I need you to tell me what to do," and then falls silent. Her gestalt counselor sees this as the impasse layer that Perls described. What would the counselor MOST likely do next?',
    options: [
      { id: 'a', text: 'Invite the client to stay with and fully experience the stuck feeling', isCorrect: true, rationale: 'Gestalt counselors help clients remain with the impasse so they can work through it, rather than rescuing them from it.' },
      { id: 'b', text: 'Offer concrete advice so the client can move past the stuck point', isCorrect: false, rationale: 'Advice would accept the client\'s bid for outside support and block her from finding her own way through.' },
      { id: 'c', text: 'Teach a relaxation exercise to reduce the client\'s discomfort quickly', isCorrect: false, rationale: 'Lowering the discomfort right away would help her escape the impasse, not experience and move through it.' },
      { id: 'd', text: 'Interpret the silence as resistance rooted in an early childhood conflict', isCorrect: false, rationale: 'Interpreting the past is a psychoanalytic move; gestalt work stays with present awareness.' },
    ],
    rationale: 'Perls described layers of neurosis (phony, phobic, impasse, implosive and explosive). At the impasse, clients feel stuck and try to get the environment, including the counselor, to provide direction and support. The gestalt counselor resists rescuing and encourages the client to stay with the stuckness, because fully experiencing it allows the client to find inner support and move through it.',
    references: [{ source: C, detail: 'Gestalt Therapy: layers of neurosis (the impasse)' }],
  },
  // ── REBT ─────────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-244',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'easy',
    stem: 'A retired bus driver tells his counselor, "I can\'t stand waiting at the pharmacy. Ten minutes in that line is unbearable, so I just leave without my medication." In Ellis\'s REBT, which irrational derivative BEST describes his belief?',
    options: [
      { id: 'a', text: 'Personalization', isCorrect: false, rationale: 'Personalization is a Beck distortion in which a person takes undue responsibility for outside events.' },
      { id: 'b', text: 'Global self-rating', isCorrect: false, rationale: 'Global rating condemns a whole person, as in "I am worthless"; he is not rating himself.' },
      { id: 'c', text: 'Low frustration tolerance', isCorrect: true, rationale: 'Insisting that discomfort is unbearable ("I can\'t stand it") is Ellis\'s low frustration tolerance.' },
      { id: 'd', text: 'Overgeneralization', isCorrect: false, rationale: 'Overgeneralization draws a sweeping rule from one event; his belief concerns tolerating discomfort.' },
    ],
    rationale: 'Ellis held that rigid demands produce derivative irrational beliefs: awfulizing, low frustration tolerance ("I can\'t stand it") and global rating of self or others. Low frustration tolerance leads people to avoid short-term discomfort at the cost of long-term goals, as when this client leaves without his medication. REBT disputes the belief that discomfort cannot be borne.',
    references: [{ source: C, detail: 'Rational Emotive Behavior Therapy: irrational beliefs and low frustration tolerance' }],
  },
  {
    id: 'nce-s-cou-245',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'medium',
    stem: 'A client insists that his partner must agree with him on every major decision. His REBT counselor asks, "How does it follow that because you would strongly prefer her agreement, she therefore must agree?" Which type of disputing is this?',
    options: [
      { id: 'a', text: 'Empirical disputing', isCorrect: false, rationale: 'Empirical disputing asks for evidence, such as "Where is the proof that she must agree?"' },
      { id: 'b', text: 'Functional disputing', isCorrect: false, rationale: 'Functional disputing asks whether the belief helps, such as "Where does this demand get you?"' },
      { id: 'c', text: 'Logical disputing', isCorrect: true, rationale: 'Logical disputing shows that a demand does not follow from a preference, however strong the preference is.' },
      { id: 'd', text: 'Philosophical disputing', isCorrect: false, rationale: 'Philosophical disputing asks whether life can still be satisfying even if the wish is not met.' },
    ],
    rationale: 'In the D step of the ABCDE model, REBT counselors challenge irrational beliefs in several ways. Logical disputes expose the leap from "I want" to "it must be"; empirical disputes test the belief against evidence; functional disputes question whether the belief serves the client\'s goals; philosophical disputes broaden the client\'s view of a satisfying life.',
    references: [{ source: C, detail: 'Rational Emotive Behavior Therapy: disputing irrational beliefs (logical, empirical, functional, philosophical)' }],
  },
  {
    id: 'nce-s-cou-246',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'hard',
    stem: 'A 26-year-old graduate student with panic attacks tells her REBT counselor, "Now I hate myself for being so weak that I panic at all." Following Ellis, what would the counselor typically address FIRST?',
    options: [
      { id: 'a', text: 'Her self-damning beliefs about having panic, before the panic itself', isCorrect: true, rationale: 'Ellis often targets the secondary disturbance first, because self-condemnation about a symptom blocks work on it.' },
      { id: 'b', text: 'Graded exposure to the bodily cues of panic, before any self-anger', isCorrect: false, rationale: 'Exposure may come later; Ellis viewed the disturbance about the disturbance as the first obstacle.' },
      { id: 'c', text: 'The childhood experiences that may first have produced the panic', isCorrect: false, rationale: 'REBT focuses on present beliefs rather than on tracing the historical origins of symptoms.' },
      { id: 'd', text: 'Reassurance that panic is not dangerous and will fade with time', isCorrect: false, rationale: 'Reassurance does not dispute the demand that she must not be weak, so the self-damning belief remains.' },
    ],
    rationale: 'REBT distinguishes primary disturbance (here, the panic) from secondary disturbance, the "disturbance about the disturbance" such as hating oneself for panicking. Ellis advised that counselors often tackle the secondary problem first, because self-condemnation adds suffering and interferes with work on the primary problem. Unconditional self-acceptance helps the client view the symptom as a problem to solve rather than proof of worthlessness.',
    references: [{ source: 'Ellis & Dryden (REBT)', detail: 'Secondary disturbance (disturbance about disturbance) and addressing it first' }, { source: C, detail: 'Rational Emotive Behavior Therapy: secondary disturbance (disturbance about disturbance)' }],
  },
  // ── SOLUTION-FOCUSED ─────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-247',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'medium',
    stem: 'At the end of a first session, a counselor tells a couple who fight about chores, "Between now and the next time we meet, notice what happens in your relationship that you want to keep happening." In de Shazer\'s approach, this assignment is known as:',
    options: [
      { id: 'a', text: 'A paradoxical directive', isCorrect: false, rationale: 'A paradoxical directive prescribes the symptom; this task asks the couple to notice what already works.' },
      { id: 'b', text: 'An externalizing question', isCorrect: false, rationale: 'Externalizing separates the person from the problem in narrative therapy; this is an observation task.' },
      { id: 'c', text: 'A skills-rehearsal assignment', isCorrect: false, rationale: 'Nothing new is being practiced; the couple is asked only to notice existing positive events.' },
      { id: 'd', text: 'The formula first session task', isCorrect: true, rationale: 'De Shazer\'s formula first session task asks clients to observe what they want to continue.' },
    ],
    rationale: 'De Shazer and colleagues developed the formula first session task as a standard assignment that shifts attention from problems to what is already going well. Because clients notice and report on positive events, the next session can build on existing strengths and exceptions rather than on a problem history.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: formula first session task' }],
  },
  {
    id: 'nce-s-cou-248',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'medium',
    stem: 'A counselor opens a second session by asking, "What\'s been better since we met?" A woman caring for her father with Parkinson\'s disease says there was one calm evening at home. Which response is MOST consistent with solution-focused practice?',
    options: [
      { id: 'a', text: '"That\'s good. Now, what has been hardest for you this past week?"', isCorrect: false, rationale: 'Moving straight to what was hardest drops the exception before it can be explored and built on.' },
      { id: 'b', text: '"What did you do that helped make that evening calmer than usual?"', isCorrect: true, rationale: 'Asking how she made it happen amplifies the exception and credits her with the change.' },
      { id: 'c', text: '"One calm evening is a start. What usually ruins the other evenings?"', isCorrect: false, rationale: 'Asking what ruins evenings returns the focus to problem talk rather than to what worked.' },
      { id: 'd', text: '"Let\'s look at what stops calm evenings from happening more often."', isCorrect: false, rationale: 'Analyzing barriers is problem-focused; SFBT studies the exception to find what to do more of.' },
    ],
    rationale: 'Solution-focused counselors open later sessions by asking what is better and then elicit, amplify and reinforce any improvement (sometimes summarized as EARS). Asking in detail how the client made the better time happen highlights her own resources and points to what she can do more of. Problem analysis is set aside in favor of building on exceptions.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: exceptions and building on what works in later sessions' }],
  },
  {
    id: 'nce-s-cou-249',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'easy',
    stem: 'Solution-focused brief therapy was developed mainly by which pair of clinicians at the Brief Family Therapy Center in Milwaukee?',
    options: [
      { id: 'a', text: 'Steve de Shazer and Insoo Kim Berg', isCorrect: true, rationale: 'De Shazer and Berg developed SFBT at the Brief Family Therapy Center in Milwaukee.' },
      { id: 'b', text: 'Michael White and David Epston', isCorrect: false, rationale: 'White and Epston developed narrative therapy in Australia and New Zealand.' },
      { id: 'c', text: 'Jay Haley and Cloé Madanes', isCorrect: false, rationale: 'Haley and Madanes are associated with strategic family therapy.' },
      { id: 'd', text: 'Paul Watzlawick and John Weakland', isCorrect: false, rationale: 'Watzlawick and Weakland worked at the Mental Research Institute in Palo Alto.' },
    ],
    rationale: 'Steve de Shazer and Insoo Kim Berg developed solution-focused brief therapy at the Brief Family Therapy Center in Milwaukee, drawing on the MRI brief therapy tradition but shifting attention from problems to solutions. Its hallmark techniques include the miracle question, exception-finding and scaling questions.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: key figures (de Shazer and Berg)' }],
  },
  // ── NARRATIVE ────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-250',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'medium',
    stem: 'A narrative counselor first asks a 15-year-old, "How much of your school week has the Panic taken over?" Later the counselor asks, "When have you had some influence over the Panic, even a little?" This paired line of questioning is known as:',
    options: [
      { id: 'a', text: 'Scaling questioning', isCorrect: false, rationale: 'Scaling questions ask for a 0 to 10 rating and come from solution-focused therapy.' },
      { id: 'b', text: 'Circular questioning', isCorrect: false, rationale: 'Circular questions, from the Milan team, ask family members about relationships and differences among them.' },
      { id: 'c', text: 'The miracle question', isCorrect: false, rationale: 'The miracle question asks clients to imagine life after the problem is gone overnight.' },
      { id: 'd', text: 'Relative influence questioning', isCorrect: true, rationale: 'Mapping the problem\'s influence on the person, then the person\'s influence on the problem, is relative influence questioning.' },
    ],
    rationale: 'White and Epston described relative influence questioning in two parts. The counselor first maps the influence of the externalized problem on the person\'s life and relationships, then maps the person\'s influence over the problem. The second set of questions brings forward unique outcomes that can anchor a preferred story.',
    references: [{ source: C, detail: 'Narrative Therapy: externalizing conversations and relative influence questioning' }],
  },
  {
    id: 'nce-s-cou-251',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'hard',
    stem: 'A 70-year-old widower says his life feels empty since his wife died. His narrative counselor asks who belongs in his "club of life," what his late wife would say she valued in him, and whether some members whose voices put him down should have less say. This practice is called:',
    options: [
      { id: 'a', text: 'Outsider-witness retelling', isCorrect: false, rationale: 'Outsider witnesses are invited audiences who listen and retell; no audience is present here.' },
      { id: 'b', text: 'Re-membering conversation', isCorrect: true, rationale: 'Re-membering reviews and revises the membership of the client\'s club of life, upgrading some voices and downgrading others.' },
      { id: 'c', text: 'Deconstructive listening', isCorrect: false, rationale: 'Deconstructive listening attends to gaps and ambiguities in a story; it does not review life\'s membership.' },
      { id: 'd', text: 'Scaffolding conversation', isCorrect: false, rationale: 'Scaffolding moves clients in small steps from the familiar toward new ideas, not toward reviewing relationships.' },
    ],
    rationale: 'Drawing on Barbara Myerhoff, Michael White described identity as shaped by an "association" or club of life whose members include living and dead, present and absent figures. In re-membering conversations, the counselor helps the client honor members who support a preferred identity, such as a deceased spouse, and revoke or reduce the membership of those whose voices are unhelpful.',
    references: [{ source: 'White (Maps of Narrative Practice)', detail: 'Ch. 3, re-membering conversations and the club of life' }, { source: C, detail: 'Narrative Therapy: re-authoring and re-membering conversations' }],
  },
  {
    id: 'nce-s-cou-252',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'medium',
    stem: 'A counseling student is asked to describe the counselor\'s position in narrative therapy as Michael White described it. Which description is MOST accurate?',
    options: [
      { id: 'a', text: 'An expert interpreter who uncovers the hidden meaning in the client\'s story', isCorrect: false, rationale: 'Narrative counselors avoid the expert-interpreter role; clients are the experts on their own lives.' },
      { id: 'b', text: 'A neutral observer who avoids any influence over the story being told', isCorrect: false, rationale: 'Narrative counselors do shape the conversation through their questions; they are not neutral observers.' },
      { id: 'c', text: 'Decentered but influential, treating the client as the expert on their life', isCorrect: true, rationale: 'White described the counselor as decentered, with the client\'s knowledge central, yet influential through questioning.' },
      { id: 'd', text: 'A directive strategist who assigns tasks designed to disrupt the problem', isCorrect: false, rationale: 'Assigning disruptive tasks is characteristic of strategic therapy rather than narrative practice.' },
    ],
    rationale: 'Michael White described the ideal narrative stance as "decentered and influential." The client\'s own knowledge and skills are at the center, and the counselor does not impose expert interpretations; at the same time, the counselor shapes the conversation through careful questions that help the client externalize problems and build a richer preferred story.',
    references: [{ source: C, detail: 'Narrative Therapy: the therapist\'s role and the client as expert' }],
  },
  // ── FEMINIST ─────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-253',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'feminist therapy',
    difficulty: 'medium',
    stem: 'A 41-year-old Latina office manager was told by human resources that she is "too emotional" about repeated sexual comments from a supervisor. Her feminist counselor describes her anger and poor sleep as understandable responses to an unjust situation rather than signs of personal pathology. Which intervention is the counselor using?',
    options: [
      { id: 'a', text: 'Gender-role analysis', isCorrect: false, rationale: 'Gender-role analysis explores the gender messages a client absorbed and their effects; this changes how symptoms are framed.' },
      { id: 'b', text: 'Reframing and relabeling', isCorrect: true, rationale: 'Feminist reframing moves the problem from the client\'s defects to social and environmental conditions.' },
      { id: 'c', text: 'Bibliotherapy', isCorrect: false, rationale: 'Bibliotherapy uses readings to educate the client; no reading is assigned in this scenario.' },
      { id: 'd', text: 'Assertiveness training', isCorrect: false, rationale: 'Assertiveness training builds skills for stating needs; the counselor is reinterpreting her reactions.' },
    ],
    rationale: 'In feminist therapy, reframing and relabeling shift the focus from "blaming the victim" toward the social and political factors that contribute to a client\'s distress. Symptoms such as anger or poor sleep may be understood as coping or survival responses to oppression or harassment, which reduces self-blame and can open the way to change and social action.',
    references: [{ source: C, detail: 'Feminist Therapy: techniques (reframing and relabeling)' }],
  },
  {
    id: 'nce-s-cou-254',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'feminist therapy',
    difficulty: 'hard',
    stem: 'A client\'s insurer requires a diagnosis before it will pay for counseling. Her counselor practices from a feminist perspective. Which approach to DSM-5-TR diagnosis is MOST consistent with feminist therapy?',
    options: [
      { id: 'a', text: 'Use diagnosis cautiously and collaboratively, weighing social context and bias', isCorrect: true, rationale: 'Feminist counselors share the process with clients and consider how oppression and bias shape symptoms.' },
      { id: 'b', text: 'Refuse to diagnose, since any label is a tool of patriarchal social control', isCorrect: false, rationale: 'Some feminist counselors decline to diagnose, but most use it with caution and collaboration.' },
      { id: 'c', text: 'Diagnose as any counselor would, since a diagnosis is a neutral clinical fact', isCorrect: false, rationale: 'Feminist therapy questions the neutrality of diagnosis and its potential for gender and cultural bias.' },
      { id: 'd', text: 'Diagnose only after the client has finished a complete gender-role analysis', isCorrect: false, rationale: 'No such rule exists; the issue is how diagnosis is used, not which technique must come first.' },
    ],
    rationale: 'Feminist therapists are wary of diagnostic labels that locate problems inside the individual and that may reflect gender, cultural or other bias. When a diagnosis is needed, many feminist counselors discuss it openly with the client, decide on it together and consider how social context, oppression and trauma contribute to symptoms. This fits the approach\'s egalitarian relationship and "personal is political" principle.',
    references: [{ source: C, detail: 'Feminist Therapy: the role of assessment and diagnosis' }],
  },
  // ── DBT ──────────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-255',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'easy',
    stem: 'A DBT skills trainer describes a state of mind that integrates "emotion mind" and "reasonable mind," allowing a person to sense what is true and act from inner balance. What is this state called?',
    options: [
      { id: 'a', text: 'Beginner\'s mind', isCorrect: false, rationale: 'Beginner\'s mind refers to approaching each moment freshly; it is not the synthesis of the two states.' },
      { id: 'b', text: 'Radical acceptance', isCorrect: false, rationale: 'Radical acceptance is a distress tolerance skill for accepting reality fully, not a state of mind.' },
      { id: 'c', text: 'Self-soothing', isCorrect: false, rationale: 'Self-soothing is a distress tolerance skill using the five senses to comfort oneself.' },
      { id: 'd', text: 'Wise mind', isCorrect: true, rationale: 'Wise mind is the integration of emotion mind and reasonable mind taught in the mindfulness module.' },
    ],
    rationale: 'Linehan\'s mindfulness module describes three states of mind. Emotion mind is driven by feelings, reasonable mind by logic and facts, and wise mind integrates both with intuitive knowing. The "what" and "how" mindfulness skills help clients reach wise mind before acting.',
    references: [{ source: 'Linehan (DBT Skills Training Manual)', detail: 'Mindfulness skills: wise mind (emotion mind and reasonable mind)' }],
  },
  {
    id: 'nce-s-cou-256',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'medium',
    stem: 'After a minor slip of the tongue at a party, a client feels intense shame and wants to hide in her room all weekend. She and her DBT therapist agree that the shame does not fit the facts. Which emotion regulation skill would the therapist MOST likely coach?',
    options: [
      { id: 'a', text: 'Self-soothing with the five senses in her room', isCorrect: false, rationale: 'Self-soothing is a distress tolerance skill and would not counter the urge to hide.' },
      { id: 'b', text: 'Radical acceptance of the mistake she made', isCorrect: false, rationale: 'Radical acceptance is a distress tolerance skill; it does not change an unjustified emotion.' },
      { id: 'c', text: 'Opposite action, going out to see her friends', isCorrect: true, rationale: 'When an emotion does not fit the facts, acting opposite to its urge (hiding) helps reduce it.' },
      { id: 'd', text: 'DEAR MAN, asking her friends for reassurance', isCorrect: false, rationale: 'DEAR MAN is an interpersonal effectiveness skill for making requests, not for changing shame.' },
    ],
    rationale: 'Opposite action is a core emotion regulation skill in DBT. When an emotion and its intensity do not fit the facts, the client acts fully opposite to the action urge; for unjustified shame, that means approaching and engaging rather than hiding. Repeated opposite action reduces the emotion over time.',
    references: [{ source: 'Linehan (DBT Skills Training Manual)', detail: 'Emotion regulation skills: checking the facts and opposite action' }],
  },
  {
    id: 'nce-s-cou-257',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'hard',
    stem: 'A client\'s DBT diary card shows that this week she cut herself once, skipped her skills group twice and had a painful argument with her sister. According to the DBT target hierarchy for individual sessions, which issue should the therapist address FIRST?',
    options: [
      { id: 'a', text: 'The self-harm, as a life-threatening behavior', isCorrect: true, rationale: 'Life-threatening behaviors, including self-harm, are the top priority in individual DBT sessions.' },
      { id: 'b', text: 'The missed group, as therapy-interfering behavior', isCorrect: false, rationale: 'Therapy-interfering behavior is the second target, addressed after life-threatening behavior.' },
      { id: 'c', text: 'The argument, as a quality-of-life interfering issue', isCorrect: false, rationale: 'Quality-of-life issues come third in the hierarchy, after the two higher targets.' },
      { id: 'd', text: 'Whichever topic the client most wishes to discuss', isCorrect: false, rationale: 'DBT uses the diary card to set the agenda by target priority, not by client preference alone.' },
    ],
    rationale: 'In stage 1 of DBT, individual therapy follows a target hierarchy: first life-threatening behaviors such as suicidal acts and self-harm, then therapy-interfering behaviors such as missed sessions, then quality-of-life interfering behaviors, and then increasing behavioral skills. The diary card shows which targets occurred during the week and guides the session agenda.',
    references: [
      { source: 'Linehan (DBT Skills Training Manual)', detail: 'Overview of DBT: stage 1 target hierarchy and diary cards' },
      { source: C, detail: 'Dialectical behavior therapy: treatment targets' },
    ],
  },
  // ── PLAY THERAPY ─────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-258',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'easy',
    stem: 'In a child-centered play therapy session, a 4-year-old silently drives a toy truck into a tower of blocks and watches it fall. The counselor says, "You\'re driving that right into there, and down it goes." This response is BEST described as:',
    options: [
      { id: 'a', text: 'Interpretation', isCorrect: false, rationale: 'Interpretation assigns meaning to the play, such as anger at a sibling; the counselor only describes it.' },
      { id: 'b', text: 'Tracking', isCorrect: true, rationale: 'Tracking describes what the child is doing, conveying the counselor\'s full attention without judgment.' },
      { id: 'c', text: 'Limit setting', isCorrect: false, rationale: 'Knocking down blocks harms no one, and the counselor sets no limit.' },
      { id: 'd', text: 'Esteem building', isCorrect: false, rationale: 'Esteem-building responses credit the child\'s effort or ability, such as "You figured that out."' },
    ],
    rationale: 'Child-centered play therapists use tracking to describe the child\'s play behavior aloud, often without naming toys the child has not named. Tracking shows the child that the counselor is present and interested, and it lets the child lead. Interpretations and evaluations are avoided because they shift direction away from the child.',
    references: [{ source: G, detail: 'Counseling children: child-centered play therapy responses (tracking)' }],
  },
  {
    id: 'nce-s-cou-259',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'medium',
    stem: 'A counselor about to begin child-centered play therapy with a 7-year-old wonders whether to read a list of playroom rules in the first few minutes. Following Landreth\'s guidance, what is the BEST approach to limits?',
    options: [
      { id: 'a', text: 'Review all of the playroom rules at the start so the child knows what to expect', isCorrect: false, rationale: 'A list of rules at the outset can inhibit play and suggests that the counselor expects misbehavior.' },
      { id: 'b', text: 'Ask the parent to explain the rules before the child enters the playroom', isCorrect: false, rationale: 'Limits belong in the child-counselor relationship and are set by the counselor when needed.' },
      { id: 'c', text: 'Post the written rules on the wall and point to them when problems arise', isCorrect: false, rationale: 'Written rules do not fit a young child\'s needs and replace the relationship with an impersonal list.' },
      { id: 'd', text: 'Set each limit only when it is needed, as situations arise during the play', isCorrect: true, rationale: 'Landreth advises that limits are not needed until they are needed, so they are set when they arise.' },
    ],
    rationale: 'Landreth recommends against opening play therapy with a list of rules, which can make a child cautious and signal distrust. The counselor offers a general, permissive introduction and sets specific limits, such as not hurting oneself or the counselor, only when a situation calls for them, using the ACT steps.',
    references: [{ source: G, detail: 'Counseling children: child-centered play therapy and limit setting' }],
  },
  {
    id: 'nce-s-cou-260',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'play therapy',
    difficulty: 'medium',
    stem: 'A parent asks why the counselor plans to use play therapy with her 5-year-old instead of talking through the child\'s fears about a new baby in the family. Which explanation BEST reflects developmental reasoning?',
    options: [
      { id: 'a', text: 'Play keeps the child busy so the counselor can watch for any hidden symptoms', isCorrect: false, rationale: 'Play is the medium of therapy itself, not a distraction that allows observation.' },
      { id: 'b', text: 'Children this age find talk boring, so playing is a reward for coming each week', isCorrect: false, rationale: 'Play is not used as a reward; it matches how young children process and express experience.' },
      { id: 'c', text: 'Young children lack abstract verbal reasoning, so play is their natural language', isCorrect: true, rationale: 'Preoperational children express feelings and work through experience in play more readily than in words.' },
      { id: 'd', text: 'Play lets the counselor interpret unconscious drives without the child\'s input', isCorrect: false, rationale: 'Modern play therapy follows the child\'s lead; it is not a way to bypass the child to interpret drives.' },
    ],
    rationale: 'In Piaget\'s preoperational stage (about ages 2 to 7), children think symbolically but lack the abstract reasoning and vocabulary needed to describe complex feelings. Play is their natural means of expression; as Landreth put it, toys are children\'s words and play is their language. Play therapy therefore meets young children at their developmental level.',
    references: [
      { source: 'Berk (Development Through the Lifespan)', detail: 'Early childhood: Piaget\'s preoperational stage and make-believe play' },
      { source: G, detail: 'Counseling children: rationale for play therapy' },
    ],
  },
  // ── PSYCHODYNAMIC ────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-261',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'medium',
    stem: 'For several weeks a psychodynamic counselor has noticed that a client\'s rage at his wife\'s mild comments seems to echo his anger at his critical mother. When is an interpretation of this link MOST likely to be useful?',
    options: [
      { id: 'a', text: 'When the material is close to awareness and the client can tolerate hearing it', isCorrect: true, rationale: 'Interpretations work best when the client is nearly ready to see the link and can absorb it.' },
      { id: 'b', text: 'As early as possible, so the client gains insight before his defenses harden', isCorrect: false, rationale: 'Premature interpretations tend to raise anxiety and resistance, and the client may reject them.' },
      { id: 'c', text: 'Only after the client asks the counselor directly to explain what is happening', isCorrect: false, rationale: 'Timing depends on the client\'s readiness, not on whether the client explicitly requests an interpretation.' },
      { id: 'd', text: 'Once the counselor is certain of the link, whatever the client\'s current readiness', isCorrect: false, rationale: 'Counselor certainty does not make an interpretation usable; the client\'s readiness is what matters.' },
    ],
    rationale: 'In psychoanalytic practice, interpretation explains the meaning of behavior, dreams, resistance and transference. Corey notes that timing matters: interpretations should be offered when the phenomenon is close to conscious awareness, should start from the surface and move only as deep as the client can go emotionally, and should follow a sound working relationship.',
    references: [{ source: C, detail: 'Psychoanalytic Therapy: interpretation and its timing' }],
  },
  // ── BEHAVIOR THERAPY ─────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-262',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'easy',
    stem: 'A doctoral student loves her evening run but keeps putting off writing her dissertation. Her counselor suggests that she go running only after she has written for one full hour. Which behavioral principle is the counselor applying?',
    options: [
      { id: 'a', text: 'Shaping', isCorrect: false, rationale: 'Shaping reinforces successive approximations of a target behavior, not one activity used as a reward for another.' },
      { id: 'b', text: 'The Premack principle', isCorrect: true, rationale: 'A high-frequency activity (running) is made contingent on a low-frequency one (writing) to reinforce it.' },
      { id: 'c', text: 'Negative reinforcement', isCorrect: false, rationale: 'Negative reinforcement removes an aversive stimulus; here a preferred activity is added after writing.' },
      { id: 'd', text: 'Stimulus generalization', isCorrect: false, rationale: 'Generalization is responding to stimuli similar to the original; it is not a reinforcement plan.' },
    ],
    rationale: 'The Premack principle, sometimes called "Grandma\'s rule," holds that a more probable behavior can reinforce a less probable one when access to it depends on first doing the less probable behavior. Counselors use it in self-management plans by making a favorite activity contingent on completing an avoided task.',
    references: [{ source: C, detail: 'Behavior Therapy: operant techniques and self-management (Premack principle)' }],
  },
  // ── FAMILY SYSTEMS ───────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-263',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'hard',
    stem: 'In a family session, a quiet 16-year-old\'s complaints are repeatedly overridden by her father and older brother, who form a strong coalition. A structural family therapist deliberately sides with the teenager for a period, backing her view until the family\'s hierarchy begins to shift. This technique is:',
    options: [
      { id: 'a', text: 'Detriangulation', isCorrect: false, rationale: 'Detriangulation is a Bowenian goal of removing oneself from a triangle, not siding with a member.' },
      { id: 'b', text: 'Reframing', isCorrect: false, rationale: 'Reframing gives a new meaning to a behavior; the therapist here is changing alliances, not meanings.' },
      { id: 'c', text: 'Enactment', isCorrect: false, rationale: 'An enactment has the family act out a transaction in session; it does not involve taking a side.' },
      { id: 'd', text: 'Unbalancing', isCorrect: true, rationale: 'Minuchin\'s unbalancing has the therapist temporarily join one member to change the family\'s power structure.' },
    ],
    rationale: 'In structural family therapy, Minuchin used unbalancing to challenge a rigid hierarchy or coalition. By temporarily affiliating with one family member, often the less powerful one, the therapist disrupts the usual distribution of power and forces the family to find new ways of relating. The therapist must later restore balance and avoid becoming fixed in a coalition.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Structural family therapy: restructuring techniques (unbalancing)' }],
  },
  // ── ADLERIAN ─────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-264',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'easy',
    stem: 'A shy 23-year-old says he wishes he were the kind of person who could start conversations with coworkers. His Adlerian counselor asks him, for one week, to behave as though he already were that person. Which technique is this?',
    options: [
      { id: 'a', text: 'Spitting in the soup', isCorrect: false, rationale: 'Spitting in the soup names the hidden payoff of a behavior to make it less appealing.' },
      { id: 'b', text: 'Catching oneself', isCorrect: false, rationale: 'Catching oneself means noticing an old pattern as it starts; it does not ask for new role behavior.' },
      { id: 'c', text: 'Acting as if', isCorrect: true, rationale: 'Acting as if invites the client to try on the role of the person he wishes to be.' },
      { id: 'd', text: 'Push-button technique', isCorrect: false, rationale: 'The push-button technique has clients alternate pleasant and unpleasant memories to see that they create feelings.' },
    ],
    rationale: 'Adlerian counselors use "acting as if" to help clients test new behavior that they believe is beyond them. Like an actor trying on a role, the client behaves for a set time as though he already had the desired quality, which can challenge mistaken beliefs about his limits and build courage.',
    references: [{ source: C, detail: 'Adlerian Therapy: reorientation techniques (acting as if)' }],
  },
  // ── PERSON-CENTERED ──────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-265',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'medium',
    stem: 'Rogers described accurate empathic understanding as sensing the client\'s private world "as if" it were the counselor\'s own. What does the "as if" quality emphasize?',
    options: [
      { id: 'a', text: 'The counselor appears to share the client\'s feelings in order to build rapport faster', isCorrect: false, rationale: 'Rogers did not mean pretending; genuine empathy requires congruence, not an act.' },
      { id: 'b', text: 'The counselor enters the client\'s world while keeping a separate sense of self', isCorrect: true, rationale: 'The counselor feels the client\'s world deeply without losing the "as if" and merging with it.' },
      { id: 'c', text: 'The counselor imagines how they themselves would feel in the client\'s situation', isCorrect: false, rationale: 'Imagining one\'s own reaction projects the counselor\'s frame onto the client instead of grasping the client\'s.' },
      { id: 'd', text: 'The counselor treats the client\'s account as a hypothesis to be checked against facts', isCorrect: false, rationale: 'Testing the client\'s account against facts is a cognitive stance, not person-centered empathy.' },
    ],
    rationale: 'For Rogers, accurate empathy means sensing the client\'s feelings and meanings as if they were one\'s own, but without ever losing the "as if" quality. The counselor stays a separate person, which keeps the counselor from being overwhelmed or confusing personal reactions with the client\'s experience, while still communicating deep understanding.',
    references: [{ source: C, detail: 'Person-Centered Therapy: accurate empathic understanding' }],
  },
  // ── EXISTENTIAL ──────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-266',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'hard',
    stem: 'An existential counselor notices that a 52-year-old engineer talks easily about his job and his duties to relatives, but goes blank when asked about his own values, feelings and sense of who he is. Which mode of being-in-the-world appears MOST neglected?',
    options: [
      { id: 'a', text: 'Eigenwelt (own world)', isCorrect: true, rationale: 'The Eigenwelt is one\'s relationship with oneself, including values, feelings and self-awareness.' },
      { id: 'b', text: 'Umwelt (natural world)', isCorrect: false, rationale: 'The Umwelt is the physical and biological world; nothing suggests he neglects his body or surroundings.' },
      { id: 'c', text: 'Mitwelt (social world)', isCorrect: false, rationale: 'The Mitwelt is the world of relationships with others, which he engages in readily.' },
      { id: 'd', text: 'Überwelt (spiritual world)', isCorrect: false, rationale: 'The Überwelt concerns ideals and beliefs about the world; the clearest gap is his relation to himself.' },
    ],
    rationale: 'Existential therapists, building on Binswanger and May, describe being-in-the-world in several modes: the Umwelt (natural or physical world), the Mitwelt (world of relationships), the Eigenwelt (relationship with oneself) and, in van Deurzen\'s addition, the Überwelt (spiritual or ideal world). A person can be engaged in some modes while neglecting others, and therapy explores the neglected dimension.',
    references: [{ source: C, detail: 'Existential Therapy: modes of being in the world (Umwelt, Mitwelt, Eigenwelt, Überwelt)' }],
  },
  // ── CBT ──────────────────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-267',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: 'A client says, "If I make a mistake in the meeting, people will notice." The counselor asks, "And if they notice, what would that mean about you?" The counselor repeats this kind of question after each answer until the client says, "That I\'m incompetent." Which technique is this?',
    options: [
      { id: 'a', text: 'Decatastrophizing', isCorrect: false, rationale: 'Decatastrophizing examines how likely and how bad a feared outcome is, rather than its meaning about the self.' },
      { id: 'b', text: 'Thought stopping', isCorrect: false, rationale: 'Thought stopping interrupts unwanted thoughts; it does not explore what lies beneath them.' },
      { id: 'c', text: 'Cognitive rehearsal', isCorrect: false, rationale: 'Cognitive rehearsal mentally practices coping with a future situation step by step.' },
      { id: 'd', text: 'Downward arrow technique', isCorrect: true, rationale: 'Repeatedly asking what a thought would mean moves from automatic thoughts down to a core belief.' },
    ],
    rationale: 'In cognitive therapy, the downward arrow technique uncovers intermediate and core beliefs that lie beneath automatic thoughts. The counselor repeatedly asks what the thought would mean if it were true, until the client reaches a basic belief about the self, such as "I\'m incompetent," which can then become a target for change.',
    references: [{ source: 'J. Beck (CBT: Basics and Beyond)', detail: 'Identifying intermediate and core beliefs: the downward arrow technique' }, { source: C, detail: 'Cognitive Behavior Therapy: Beck\'s cognitive therapy, identifying core beliefs' }],
  },
  // ── REALITY THERAPY ──────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-268',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'medium',
    stem: 'A father admits that he nags, criticizes and threatens his 14-year-old about grades, and their relationship has grown cold. In Glasser\'s choice theory, what would a reality therapist encourage him to use in place of these "deadly habits"?',
    options: [
      { id: 'a', text: 'Consistent consequences set out in a written behavior contract', isCorrect: false, rationale: 'Consequences used to force compliance still rely on external control, which Glasser rejected.' },
      { id: 'b', text: 'Praise and tangible rewards delivered right after good grades', isCorrect: false, rationale: 'Rewarding to control, or bribing, is itself one of Glasser\'s seven deadly habits.' },
      { id: 'c', text: 'Caring habits such as listening, supporting and encouraging', isCorrect: true, rationale: 'Glasser\'s caring habits build the relationship that external control damages.' },
      { id: 'd', text: 'Firmer limits paired with calm, logical explanation of rules', isCorrect: false, rationale: 'Firm limits imposed to control the teen do not replace control with connection.' },
    ],
    rationale: 'Glasser contrasted external control psychology with choice theory. His seven deadly habits (criticizing, blaming, complaining, nagging, threatening, punishing and bribing or rewarding to control) damage relationships, while the seven caring habits (supporting, encouraging, listening, accepting, trusting, respecting and negotiating differences) strengthen the connection people need to meet their basic needs.',
    references: [{ source: C, detail: 'Reality Therapy: choice theory, external control and caring versus deadly habits' }],
  },
  // ── MOTIVATIONAL INTERVIEWING ────────────────────────────────────────────
  {
    id: 'nce-s-cou-269',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: 'In a primary care clinic, a 58-year-old client asks a counselor, "Is it really that bad to have four beers every night?" Which response BEST follows the elicit-provide-elicit approach used in motivational interviewing?',
    options: [
      { id: 'a', text: '"What have you heard about it? I can share what we know, then hear your view."', isCorrect: true, rationale: 'This asks what the client knows, offers information with consent, and plans to ask for the client\'s reaction.' },
      { id: 'b', text: '"Yes, that is well above safe limits, so you should cut back to two at most."', isCorrect: false, rationale: 'Giving unsolicited advice and a directive reflects the righting reflex and invites sustain talk.' },
      { id: 'c', text: '"Why do you think you need four beers a night just to unwind after work?"', isCorrect: false, rationale: 'A "why" question about his need can sound judgmental and draws reasons for drinking.' },
      { id: 'd', text: '"Let\'s hold that question and first talk about how your week has gone."', isCorrect: false, rationale: 'Deflecting the question misses a natural chance to exchange information.' },
    ],
    rationale: 'Motivational interviewing uses elicit-provide-elicit to share information in a way that respects autonomy. The counselor first asks what the client already knows or wants to know, then offers information with permission and in a neutral way, and then asks what the client makes of it. This avoids the righting reflex and keeps the client active in the conversation.',
    references: [{ source: 'Miller & Rollnick (MI)', detail: 'Exchanging information: elicit-provide-elicit' }],
  },
  // ── TRAUMA-INFORMED ──────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-270',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'hard',
    stem: 'A 30-year-old with PTSD and alcohol use disorder is in early recovery and becomes overwhelmed when trauma memories come up. Her counselor begins Seeking Safety, the model developed by Lisa Najavits. Which feature BEST describes this model?',
    options: [
      { id: 'a', text: 'It requires a detailed trauma narrative before coping skills are taught', isCorrect: false, rationale: 'Seeking Safety does not require clients to tell their trauma story in detail.' },
      { id: 'b', text: 'It is present-focused, teaching safe coping for trauma and substance use', isCorrect: true, rationale: 'Seeking Safety is an integrated, present-focused model that builds safe coping skills for both conditions.' },
      { id: 'c', text: 'It treats the drinking first and delays trauma work until sobriety is stable', isCorrect: false, rationale: 'Seeking Safety addresses trauma and substance use at the same time rather than in sequence.' },
      { id: 'd', text: 'It uses repeated imaginal exposure to the worst memory in every session', isCorrect: false, rationale: 'Repeated imaginal exposure belongs to prolonged exposure, not to Seeking Safety.' },
    ],
    rationale: 'Seeking Safety is an integrated, present-focused treatment for co-occurring trauma and substance use. Its goal is safety: it teaches cognitive, behavioral and interpersonal coping skills that apply to both problems, without requiring clients to explore trauma memories in detail. This makes it suited to early recovery, when detailed trauma processing may destabilize the client.',
    references: [{ source: 'SAMHSA TIP 57', detail: 'Trauma-specific services: integrated models for trauma and substance use (Seeking Safety)' }],
  },
];
