// tools/nce/seed/counseling-5.js
// NCE seed — Counseling Skills and Interventions, batch 3: deeper coverage of
// ten core theories that had only two items each (Adlerian, person-centered,
// existential, gestalt, REBT, SFBT, narrative, feminist/relational-cultural,
// motivational interviewing, DBT). Three new items per theory.
const C = 'Corey (Theory & Practice)';
const MI = 'Miller & Rollnick (MI)';
const G = 'Goldenberg (Family Therapy)';

module.exports = [
  // ------------------------------------------------------------- Adlerian
  {
    id: 'nce-s-cou-121',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'medium',
    stem: 'During a lifestyle assessment, an Adlerian counselor asks a 38-year-old client to describe a single, specific incident from early childhood that she can picture clearly, including what she felt at the time. The counselor is LEAST concerned with whether the memory is factually accurate. What is the main purpose of gathering these early recollections?',
    options: [
      { id: 'a', text: 'To uncover repressed trauma so it can be worked through in transference', isCorrect: false, rationale: 'Recovering repressed material and working it through in the transference is a psychoanalytic goal, not the Adlerian use of early memories.' },
      { id: 'b', text: 'To reveal her private logic and core convictions about self, others and life', isCorrect: true, rationale: 'Adlerians treat early recollections as projective: the memories a person keeps reflect present convictions, goals and basic mistakes in the lifestyle.' },
      { id: 'c', text: 'To identify the conditioned stimuli that first triggered her current anxiety', isCorrect: false, rationale: 'Locating conditioned stimuli is a behavioral assessment task; Adlerians are not seeking a learning history of specific triggers.' },
      { id: 'd', text: 'To confirm the accuracy of her family history before choosing a diagnosis', isCorrect: false, rationale: 'Adlerians value early recollections for what the client selects and how she tells it, not for historical accuracy or diagnosis.' },
    ],
    rationale: 'In Adlerian lifestyle assessment, early recollections are single, specific memories, usually from before about age 10. Because people remember events consistent with their current view of life, the memories serve as a projective window into private logic, goals and basic mistakes. Factual accuracy matters little; the themes and the client\'s stance within the memory matter most.',
    references: [{ source: C, detail: 'Adlerian Therapy: lifestyle assessment and early recollections' }],
  },
  {
    id: 'nce-s-cou-122',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'easy',
    stem: 'An Adlerian counselor asks a client who feels stuck in a low mood to close his eyes and recall a pleasant memory, notice the feelings that come with it, then recall a painful memory and notice how his feelings shift, and then return to the pleasant one. The aim is to show him that he can influence his feelings by what he chooses to think about. This is called:',
    options: [
      { id: 'a', text: 'Rational emotive imagery', isCorrect: false, rationale: 'Rational emotive imagery (REBT) has the client imagine a feared event and change the emotion by changing the belief, not alternate pleasant and painful memories.' },
      { id: 'b', text: 'Acting as if', isCorrect: false, rationale: 'Acting as if invites the client to behave as though he were already the person he wishes to be, not to switch between memories.' },
      { id: 'c', text: 'The push-button technique', isCorrect: true, rationale: 'The push-button technique alternates pleasant and unpleasant images so the client sees he can "push the button" for the feeling he wants.' },
      { id: 'd', text: 'Systematic desensitization', isCorrect: false, rationale: 'Systematic desensitization pairs relaxation with a graded fear hierarchy; it is a behavioral fear-reduction method.' },
    ],
    rationale: 'The Adlerian push-button technique teaches that feelings are not simply things that happen to us. By deliberately calling up pleasant and then unpleasant memories and noticing the emotional shift, the client learns he can create or change feelings by what he chooses to focus on, which supports responsibility and encouragement.',
    references: [{ source: C, detail: 'Adlerian Therapy: reorientation techniques (push-button technique)' }],
  },
  {
    id: 'nce-s-cou-123',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'easy',
    stem: 'A 15-year-old who failed her first algebra test tells her school counselor she is "just bad at math" and wants to drop the class. She studied every evening for the next test and raised her score to a C. Which counselor response BEST reflects the Adlerian use of encouragement?',
    options: [
      { id: 'a', text: '"You\'re so smart. I was sure you would get an A one of these days."', isCorrect: false, rationale: 'This is praise that rates the person and sets an outcome standard; Adlerians distinguish such praise from encouragement.' },
      { id: 'b', text: '"A C is still a C. Let\'s set a firm goal of a B on the next test."', isCorrect: false, rationale: 'This focuses on the shortfall and raises the bar, which can deepen discouragement rather than build courage.' },
      { id: 'c', text: '"Maybe math just isn\'t your thing. Many people do fine without it."', isCorrect: false, rationale: 'This colludes with her discouraged belief that she lacks ability, which is the mistaken conviction to be challenged.' },
      { id: 'd', text: '"You studied each night, and your score rose. Your effort paid off."', isCorrect: true, rationale: 'Encouragement recognizes effort and improvement, building the courage and faith in herself that she can grow.' },
    ],
    rationale: 'Adlerians view many problems as rooted in discouragement, and they see encouragement as the most powerful method for change. Encouragement focuses on effort, improvement and the person\'s strengths, and it is not contingent on success. Praise, by contrast, rewards outcomes and can teach that worth depends on performing well.',
    references: [{ source: C, detail: 'Adlerian Therapy: encouragement as a core process' }],
  },
  // ----------------------------------------------------- person-centered
  {
    id: 'nce-s-cou-124',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'medium',
    stem: 'Carl Rogers (1957) proposed six conditions that are necessary and sufficient for therapeutic personality change. Besides the counselor\'s congruence, unconditional positive regard and empathy, which condition describes the state of the client entering the relationship?',
    options: [
      { id: 'a', text: 'The client is incongruent, being vulnerable or anxious', isCorrect: true, rationale: 'Rogers specified that the client is in a state of incongruence, vulnerable or anxious; this is one of the six conditions.' },
      { id: 'b', text: 'The client has insight into the childhood origins of distress', isCorrect: false, rationale: 'Insight into childhood origins is a psychodynamic aim and was not among Rogers\'s conditions.' },
      { id: 'c', text: 'The client agrees to specific, measurable treatment goals', isCorrect: false, rationale: 'Measurable goal setting is more typical of behavioral and brief approaches; Rogers did not require it.' },
      { id: 'd', text: 'The client has received an accurate diagnosis from the counselor', isCorrect: false, rationale: 'Rogers considered diagnosis unnecessary for change and potentially harmful to the relationship.' },
    ],
    rationale: 'Rogers\'s six conditions are: two persons are in psychological contact; the client is incongruent, vulnerable or anxious; the counselor is congruent in the relationship; the counselor experiences unconditional positive regard; the counselor experiences empathic understanding of the client\'s internal frame of reference; and the client at least minimally perceives the counselor\'s regard and empathy. He held that no particular technique, insight or diagnosis was required.',
    references: [{ source: C, detail: 'Person-Centered Therapy: necessary and sufficient conditions for change' }],
  },
  {
    id: 'nce-s-cou-125',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'easy',
    stem: 'A 60-year-old client caring for his wife with dementia asks his counselor, "Just tell me straight: should I move her into a memory care facility or not?" Which counselor response is MOST consistent with a person-centered, nondirective stance?',
    options: [
      { id: 'a', text: '"Most families in your situation find a facility is the better choice."', isCorrect: false, rationale: 'This gives advice from the counselor\'s frame of reference and shifts the decision away from the client.' },
      { id: 'b', text: '"Let\'s list the pros and cons this week and score each one at home."', isCorrect: false, rationale: 'A structured decision task is a directive, problem-solving move rather than following the client\'s experience.' },
      { id: 'c', text: '"You feel torn, and you wish someone would tell you what is right."', isCorrect: true, rationale: 'This empathic reflection stays in his frame of reference and trusts his capacity to reach his own decision.' },
      { id: 'd', text: '"Perhaps your guilt about her illness is what makes deciding so hard."', isCorrect: false, rationale: 'This is an interpretation that imposes the counselor\'s hypothesis about the cause of his difficulty.' },
    ],
    rationale: 'Person-centered counselors trust the client\'s actualizing tendency and capacity for self-direction. Rather than advising, assigning tasks or interpreting, they offer accurate empathy, genuineness and unconditional positive regard, so the client can explore his own experience and arrive at his own choice.',
    references: [{ source: C, detail: 'Person-Centered Therapy: nondirective stance and the client as expert' }],
  },
  {
    id: 'nce-s-cou-126',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'medium',
    stem: 'A counseling student is summarizing common criticisms of the person-centered approach for a theories exam. Which criticism is MOST often raised?',
    options: [
      { id: 'a', text: 'It casts the counselor as an expert who interprets the client\'s hidden motives', isCorrect: false, rationale: 'This describes classical psychoanalysis; person-centered counselors avoid the interpretive expert role.' },
      { id: 'b', text: 'Its low structure may not suit clients who want or expect active direction', isCorrect: true, rationale: 'Critics note that a nondirective stance can leave some clients, including many from cultures that expect an active helper, without enough guidance.' },
      { id: 'c', text: 'It depends heavily on standardized testing and diagnosis to guide treatment', isCorrect: false, rationale: 'Rogers de-emphasized testing and diagnosis, so this is the opposite of the approach.' },
      { id: 'd', text: 'It treats the therapeutic relationship as secondary to specific techniques', isCorrect: false, rationale: 'The relationship is the core of person-centered therapy, which places little weight on techniques.' },
    ],
    rationale: 'Person-centered therapy is praised for its emphasis on the relationship and the client\'s resources, and its core conditions are well supported by alliance research. Common criticisms are that it can be too passive or unstructured for clients in crisis or those who expect direction, and that some practitioners reduce it to simple reflection without real presence.',
    references: [{ source: C, detail: 'Person-Centered Therapy: limitations and criticisms; multicultural perspective' }],
  },
  // ---------------------------------------------------------- existential
  {
    id: 'nce-s-cou-127',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'medium',
    stem: 'A 29-year-old client has been offered a job abroad and says he feels anxious about the choice because no one can make it for him and he will have to live with the results. How would an existential counselor MOST likely view this anxiety?',
    options: [
      { id: 'a', text: 'As normal anxiety that comes with freedom and can spur growth and choice', isCorrect: true, rationale: 'Existentialists see normal anxiety as an unavoidable part of facing freedom and responsibility, and as a potential source of growth.' },
      { id: 'b', text: 'As a symptom to be reduced quickly with relaxation and breathing skills', isCorrect: false, rationale: 'Symptom reduction is a behavioral aim; existential counselors do not try to eliminate normal anxiety.' },
      { id: 'c', text: 'As the result of repressed impulses breaking through his ego defenses', isCorrect: false, rationale: 'This is a psychoanalytic account of anxiety, not an existential one.' },
      { id: 'd', text: 'As the product of an irrational demand that he dispute in homework', isCorrect: false, rationale: 'Disputing irrational demands is REBT; existential therapy treats this anxiety as a meaningful response to real givens.' },
    ],
    rationale: 'Existential therapy distinguishes normal anxiety, a fitting response to freedom, responsibility, death and isolation, from neurotic anxiety, which is out of proportion and blocks living. Rollo May described normal anxiety as something to face, not remove, because it can motivate authentic choice. The counselor helps the client own his freedom rather than escape the discomfort.',
    references: [{ source: C, detail: 'Existential Therapy: normal and neurotic anxiety; freedom and responsibility' }],
  },
  {
    id: 'nce-s-cou-128',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'hard',
    stem: 'Which pairing of existential theorist and contribution is accurate?',
    options: [
      { id: 'a', text: 'Viktor Frankl: the four ultimate concerns of death, freedom, isolation and meaninglessness', isCorrect: false, rationale: 'The four ultimate concerns were described by Irvin Yalom, not Frankl.' },
      { id: 'b', text: 'Irvin Yalom: logotherapy and the will to meaning as the primary human motivation', isCorrect: false, rationale: 'Logotherapy and the will to meaning are Frankl\'s contributions.' },
      { id: 'c', text: 'Rollo May: the I-Thou relationship as the basis of genuine human encounter', isCorrect: false, rationale: 'The I-Thou relationship comes from the philosopher Martin Buber, though existential counselors draw on it.' },
      { id: 'd', text: 'Rollo May: bringing existential ideas to American therapy and writing on anxiety', isCorrect: true, rationale: 'May was a key figure in introducing existential thought to U.S. psychotherapy and wrote extensively on anxiety, courage and freedom.' },
    ],
    rationale: 'Viktor Frankl founded logotherapy, emphasizing the will to meaning. Rollo May helped bring European existential thought to American psychotherapy, writing on normal anxiety and the courage to face freedom. Irvin Yalom identified four ultimate concerns: death, freedom, isolation and meaninglessness. Martin Buber, a philosopher, described the I-Thou relationship.',
    references: [{ source: C, detail: 'Existential Therapy: key figures (Frankl, May, Yalom) and philosophical roots' }],
  },
  {
    id: 'nce-s-cou-129',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'hard',
    stem: 'A client dreads sweating heavily when giving presentations, and the more he fears it, the more he sweats. His counselor asks him, before his next talk, to try to sweat as much as he possibly can and to show the audience just how much he can sweat. Which Frankl technique is this?',
    options: [
      { id: 'a', text: 'Dereflection', isCorrect: false, rationale: 'Dereflection redirects attention away from oneself and the symptom toward other meanings; it does not ask the client to wish for the symptom.' },
      { id: 'b', text: 'Flooding', isCorrect: false, rationale: 'Flooding is a behavioral exposure method of prolonged, intense contact with the feared stimulus, not a humorous wish for the symptom.' },
      { id: 'c', text: 'Paradoxical intention', isCorrect: true, rationale: 'Frankl\'s paradoxical intention asks clients to intend the very thing they fear, breaking the cycle of anticipatory anxiety.' },
      { id: 'd', text: 'Ordeal therapy', isCorrect: false, rationale: 'Ordeal therapy (Haley) attaches a burdensome task to the symptom; it is strategic, not logotherapeutic.' },
    ],
    rationale: 'In paradoxical intention, Frankl asked clients to wish for or deliberately produce what they fear, often with humor. Doing so interrupts anticipatory anxiety, the fear of the symptom that keeps the symptom going. Frankl paired it with dereflection, which moves attention away from hyper-reflection on oneself.',
    references: [{ source: C, detail: 'Existential Therapy: Frankl\'s logotherapy, paradoxical intention and dereflection' }],
  },
  // --------------------------------------------------------------- gestalt
  {
    id: 'nce-s-cou-130',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'easy',
    stem: 'A client speaks of her partner and herself as "we" when describing every feeling and opinion. She says they "never disagree," and she becomes anxious and vague when the counselor asks what she alone wants. In gestalt terms, this blurring of the boundary between self and other is called:',
    options: [
      { id: 'a', text: 'Introjection', isCorrect: false, rationale: 'Introjection is swallowing others\' beliefs and standards whole without examining them.' },
      { id: 'b', text: 'Confluence', isCorrect: true, rationale: 'Confluence blurs the self-other boundary so that differences are not felt, keeping conflict and separate wants out of awareness.' },
      { id: 'c', text: 'Projection', isCorrect: false, rationale: 'Projection attributes to others the traits or feelings one disowns in oneself.' },
      { id: 'd', text: 'Deflection', isCorrect: false, rationale: 'Deflection avoids contact through humor, vagueness or changing the subject.' },
    ],
    rationale: 'Gestalt therapy names several disturbances at the contact boundary: introjection, projection, retroflection, deflection and confluence. In confluence the person merges with others, seeks constant agreement and loses touch with personal wants. Counselors help such clients notice differences and ask, "What do you feel? What do you want?"',
    references: [{ source: C, detail: 'Gestalt Therapy: contact and resistances to contact (confluence)' }],
  },
  {
    id: 'nce-s-cou-131',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'medium',
    stem: 'A client gives a long, detached account of an argument he had with his brother two years ago. As he talks, his voice tightens and he taps his foot quickly. Which response is MOST consistent with gestalt therapy?',
    options: [
      { id: 'a', text: '"What are you aware of right now as you tell me this? Notice your foot."', isCorrect: true, rationale: 'This brings him into the here and now and directs attention to present, nonverbal experience, the heart of gestalt awareness work.' },
      { id: 'b', text: '"Why do you think you and your brother end up fighting like that so often?"', isCorrect: false, rationale: 'Gestalt counselors avoid "why" questions, which invite intellectualizing rather than present awareness.' },
      { id: 'c', text: '"What were you telling yourself during the argument that upset you?"', isCorrect: false, rationale: 'Identifying self-talk is a cognitive-behavioral move focused on the past event rather than present experience.' },
      { id: 'd', text: '"It sounds as if your brother reminds you of a parent from childhood."', isCorrect: false, rationale: 'This is a psychodynamic interpretation; gestalt counselors favor client discovery over counselor interpretation.' },
    ],
    rationale: 'Gestalt therapy holds that awareness in the present moment is itself curative. Counselors shift clients from talking about past events to experiencing what is happening now, often by noticing body language, voice and breath. "What" and "how" questions are preferred to "why" questions, which tend to produce explanations instead of contact.',
    references: [{ source: C, detail: 'Gestalt Therapy: the now, awareness, and attention to nonverbal behavior' }],
  },
  {
    id: 'nce-s-cou-132',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'hard',
    stem: 'Arnold Beisser\'s paradoxical theory of change is a foundation of gestalt practice. Which statement BEST captures it?',
    options: [
      { id: 'a', text: 'Change happens when the counselor prescribes the symptom the client most wants to stop', isCorrect: false, rationale: 'Prescribing the symptom is a strategic family therapy directive, not Beisser\'s theory.' },
      { id: 'b', text: 'Change happens when clients replace irrational demands with flexible preferences', isCorrect: false, rationale: 'Replacing demands with preferences is the REBT model of change.' },
      { id: 'c', text: 'Change happens when the counselor interprets resistance until the client gains insight', isCorrect: false, rationale: 'Interpreting resistance to produce insight is a psychoanalytic method.' },
      { id: 'd', text: 'Change happens when one becomes what one is, not when one tries to be what one is not', isCorrect: true, rationale: 'Beisser held that change comes through full awareness and acceptance of who one is now, not through striving to be different.' },
    ],
    rationale: 'Beisser\'s paradoxical theory of change states that the more a person tries to be who he or she is not, the more the person stays the same. Change occurs when the person fully experiences and owns current reality. Gestalt counselors therefore do not push for change; they heighten awareness of what is, trusting that integration follows.',
    references: [{ source: C, detail: 'Gestalt Therapy: the paradoxical theory of change' }],
  },
  // ------------------------------------------------------------------ REBT
  {
    id: 'nce-s-cou-133',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'easy',
    stem: 'A client who believes it would be unbearable to look foolish is assigned homework: wear a brightly mismatched outfit to the grocery store and loudly ask a clerk where the milk is while standing next to it. She is to notice that she can tolerate others\' reactions and still accept herself. This REBT technique is called:',
    options: [
      { id: 'a', text: 'Paradoxical intention', isCorrect: false, rationale: 'Paradoxical intention (Frankl) asks clients to wish for a feared symptom, such as trying to blush or sweat.' },
      { id: 'b', text: 'A shame-attacking exercise', isCorrect: true, rationale: 'Shame-attacking exercises have clients do harmless "foolish" acts in public to learn that disapproval is tolerable and not a verdict on their worth.' },
      { id: 'c', text: 'Rational emotive imagery', isCorrect: false, rationale: 'Rational emotive imagery is done in imagination, not by acting in public.' },
      { id: 'd', text: 'Systematic desensitization', isCorrect: false, rationale: 'Systematic desensitization pairs relaxation with a graded hierarchy, usually in imagination, to reduce fear.' },
    ],
    rationale: 'Albert Ellis developed shame-attacking exercises as in vivo homework. Clients deliberately do something they consider shameful but that harms no one, then work on not putting themselves down. REBT relies heavily on such homework to practice new rational beliefs between sessions.',
    references: [{ source: C, detail: 'REBT: behavioral techniques, homework and shame-attacking exercises' }],
  },
  {
    id: 'nce-s-cou-134',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'hard',
    stem: 'After failing the bar exam, a 27-year-old law graduate says, "I failed, so I\'m a failure." Her REBT counselor works toward unconditional self-acceptance (USA). Which goal BEST reflects this concept?',
    options: [
      { id: 'a', text: 'Restore her self-esteem by listing past successes that show her real worth', isCorrect: false, rationale: 'Ellis criticized self-esteem as conditional on achievement; rebuilding it through successes keeps worth tied to performance.' },
      { id: 'b', text: 'Help her see the exam was unimportant so the result need not upset her', isCorrect: false, rationale: 'REBT does not deny that the outcome is bad; appropriate disappointment is a healthy negative emotion.' },
      { id: 'c', text: 'Rate the failed exam as a poor result while accepting herself as fallible', isCorrect: true, rationale: 'USA means rating behaviors and outcomes, not the whole self, and accepting oneself as a fallible human regardless of performance.' },
      { id: 'd', text: 'Trace how her parents\' high standards first taught her to fear failure', isCorrect: false, rationale: 'REBT focuses on present beliefs; tracing childhood origins is not needed for unconditional self-acceptance.' },
    ],
    rationale: 'Ellis argued that global self-rating is irrational because a person is too complex to sum up with one score. Unconditional self-acceptance asks clients to evaluate their actions and outcomes, sometimes harshly, while accepting themselves without conditions. He contrasted this with self-esteem, which rises and falls with success and approval.',
    references: [{ source: C, detail: 'REBT: unconditional self-acceptance versus self-esteem' }],
  },
  {
    id: 'nce-s-cou-135',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'medium',
    stem: 'A counselor asks a client to imagine vividly that he is turned down for a date, let himself feel the depressed panic that follows, and then, while keeping the image, change the feeling to disappointment. Afterward they discuss what he told himself to make the change. This REBT technique is:',
    options: [
      { id: 'a', text: 'Rational emotive imagery', isCorrect: true, rationale: 'Rational emotive imagery has clients hold a vivid image of a feared event and shift an unhealthy emotion to a healthy one by changing the belief.' },
      { id: 'b', text: 'The push-button technique', isCorrect: false, rationale: 'The Adlerian push-button technique alternates pleasant and unpleasant memories; it does not keep one feared image constant.' },
      { id: 'c', text: 'Covert sensitization', isCorrect: false, rationale: 'Covert sensitization pairs an unwanted behavior with imagined aversive consequences to reduce that behavior.' },
      { id: 'd', text: 'Systematic desensitization', isCorrect: false, rationale: 'Systematic desensitization pairs relaxation with graded fear images; it does not ask the client to feel and then transform an emotion.' },
    ],
    rationale: 'In rational emotive imagery, the client imagines one of the worst things that could happen, allows the unhealthy emotion, and then changes it to a healthy negative emotion such as disappointment or concern. The change happens through a shift in belief, which the client then identifies and practices, often daily as homework.',
    references: [{ source: C, detail: 'REBT: emotive techniques (rational emotive imagery)' }],
  },
  // ------------------------------------------------------------------ SFBT
  {
    id: 'nce-s-cou-136',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'easy',
    stem: 'A client says she has felt sad "every single day" since moving to a new city. Her counselor asks, "Think about this past week. When was the sadness even a little lighter, and what was different then?" This is an example of:',
    options: [
      { id: 'a', text: 'A scaling question', isCorrect: false, rationale: 'Scaling questions ask the client to rate the problem or progress on a numerical scale, such as 0 to 10.' },
      { id: 'b', text: 'The miracle question', isCorrect: false, rationale: 'The miracle question asks the client to imagine the problem solved overnight and describe what would be different.' },
      { id: 'c', text: 'A coping question', isCorrect: false, rationale: 'Coping questions ask how the client has kept going despite difficulty, not when the problem was less present.' },
      { id: 'd', text: 'An exception question', isCorrect: true, rationale: 'Exception questions search for times the problem was absent or less severe, so the client can repeat what worked.' },
    ],
    rationale: 'Solution-focused counselors assume that problems are never constant. Exception questions direct attention to times the problem was absent or milder and to what the client was doing then. These exceptions become the raw material for solutions: do more of what works.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: exception questions' }],
  },
  {
    id: 'nce-s-cou-137',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'medium',
    stem: 'A father raising three children alone after his wife\'s death says nothing is going well, and he cannot recall a single time things were better. Which response is MOST consistent with a solution-focused coping question?',
    options: [
      { id: 'a', text: '"Let\'s find out what in your past is keeping you so stuck right now."', isCorrect: false, rationale: 'Searching the past for the cause of the problem is problem-focused, which SFBT deliberately avoids.' },
      { id: 'b', text: '"With so much on you, how have you managed to keep the kids fed and here?"', isCorrect: true, rationale: 'A coping question highlights the strength and effort already present when the client sees no exceptions.' },
      { id: 'c', text: '"On a scale of 0 to 10, how bad would you say things are for you today?"', isCorrect: false, rationale: 'This is a scaling question, and framing it around how bad things are keeps the focus on the problem.' },
      { id: 'd', text: '"It sounds like the grief is still very raw. Tell me more about the loss."', isCorrect: false, rationale: 'This empathic invitation is appropriate in many models but is not an SFBT coping question.' },
    ],
    rationale: 'When clients cannot identify exceptions, solution-focused counselors use coping questions, such as "How have you managed to keep going?" These questions bring out the client\'s resources and small successes already present in a hard situation. They respect the difficulty while shifting attention toward competence.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: coping questions and client competence' }],
  },
  {
    id: 'nce-s-cou-138',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'hard',
    stem: 'A 16-year-old is sent to counseling by his school after a fight. He says he has no problem and is only there because the principal required it. In de Shazer\'s terms, what is the counselor-client relationship, and what is the BEST response?',
    options: [
      { id: 'a', text: 'Complainant; ask him to watch for times when things go a bit better', isCorrect: false, rationale: 'A complainant sees a problem but not himself as part of the solution; this teen does not yet see a problem at all.' },
      { id: 'b', text: 'Customer; give him an action task to practice before the next session', isCorrect: false, rationale: 'A customer sees a problem and is ready to act; assigning tasks to an uncommitted client invites failure.' },
      { id: 'c', text: 'Visitor; compliment him for coming and avoid assigning him any tasks', isCorrect: true, rationale: 'A visitor sees no problem to work on; the counselor offers sincere compliments, explores what he might want, and gives no tasks.' },
      { id: 'd', text: 'Customer; confront his denial and set firm goals for his anger at once', isCorrect: false, rationale: 'Confronting denial is not a solution-focused stance, and the teen is not in a customer relationship.' },
    ],
    rationale: 'De Shazer described three kinds of relationships: visitor (no complaint or goal yet), complainant (sees a problem but expects others to change) and customer (sees a problem and is willing to act). These describe the relationship at a moment, not fixed client traits. With visitors, counselors build rapport through compliments and curiosity about what the client might want, saving tasks for later.',
    references: [{ source: C, detail: 'Solution-Focused Brief Therapy: customer, complainant and visitor relationships; compliments' }],
  },
  // ------------------------------------------------------------- narrative
  {
    id: 'nce-s-cou-139',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'medium',
    stem: 'A mother of twins says, "A good mother never needs help, so I\'m failing." Her narrative counselor asks, "Where did you learn that idea about good mothers? Who benefits when mothers believe it? Are there times it doesn\'t fit your life?" The counselor is MAINLY engaged in:',
    options: [
      { id: 'a', text: 'Deconstructing a dominant discourse', isCorrect: true, rationale: 'Deconstruction questions unpack the taken-for-granted discourses behind a problem story so the client can choose whether to accept them.' },
      { id: 'b', text: 'Disputing an irrational belief', isCorrect: false, rationale: 'Disputing tests a belief\'s logic and evidence (REBT); narrative questions trace a belief\'s cultural origins and effects instead.' },
      { id: 'c', text: 'Interpreting an unconscious conflict', isCorrect: false, rationale: 'Narrative counselors take a not-knowing stance and do not interpret hidden motives.' },
      { id: 'd', text: 'Naming an Adlerian basic mistake', isCorrect: false, rationale: 'Basic mistakes in the lifestyle are an Adlerian concept tied to private logic, not cultural discourse.' },
    ],
    rationale: 'Michael White and David Epston drew on the idea that problem stories are shaped by dominant cultural discourses. Deconstruction exposes where those discourses came from, whose interests they serve and how they have shaped the client\'s thin, problem-saturated description of herself. This opens space for a thicker, preferred story.',
    references: [{ source: C, detail: 'Narrative Therapy: deconstruction and dominant discourses' }],
  },
  {
    id: 'nce-s-cou-140',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'medium',
    stem: 'A young adult reclaiming her life from an eating disorder invites three friends to a session. While she talks with the counselor, the friends listen; then they describe what stood out to them, what it brought up in their own lives and how it moved them, and she responds. This narrative practice is known as:',
    options: [
      { id: 'a', text: 'Externalizing conversation', isCorrect: false, rationale: 'Externalizing separates the person from the problem in language; it does not depend on an audience of witnesses.' },
      { id: 'b', text: 'Family sculpting', isCorrect: false, rationale: 'Family sculpting (Satir) has members arrange one another physically to show relationships.' },
      { id: 'c', text: 'Reflecting team critique', isCorrect: false, rationale: 'Outsider witnesses do not critique or evaluate the client; reflecting teams also come from Andersen\'s work with clinicians.' },
      { id: 'd', text: 'Definitional ceremony', isCorrect: true, rationale: 'In a definitional ceremony, outsider witnesses hear the preferred story and retell it, which authenticates and thickens it.' },
    ],
    rationale: 'White adapted the definitional ceremony from anthropologist Barbara Myerhoff. The client tells her preferred story, outsider witnesses retell what resonated with them, and the client then responds to the retellings. The audience helps acknowledge and thicken the new identity claims so they are not held by the client alone.',
    references: [{ source: G, detail: 'Narrative therapy: definitional ceremonies and outsider witnesses' }],
    reviewNote: 'Confirm that Goldenberg (9th ed.) covers definitional ceremonies/outsider witnesses; Corey covers them only briefly. Reflecting-team distractor wording ("critique") chosen so it is clearly not the practice described.',
  },
  {
    id: 'nce-s-cou-141',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'medium',
    stem: 'After a session, a narrative counselor mails a client a letter that quotes the client\'s own words about how he stood up to "the Anger," notes questions the counselor is still curious about and names the steps he took. What is the MAIN purpose of such therapeutic letters?',
    options: [
      { id: 'a', text: 'To give him the counselor\'s formal diagnosis and expert view of his case', isCorrect: false, rationale: 'Narrative counselors avoid the expert, diagnostic stance; letters center the client\'s words, not a diagnosis.' },
      { id: 'b', text: 'To document and thicken his emerging story so it lasts between sessions', isCorrect: true, rationale: 'Letters record the alternative story in lasting form, extending and thickening it beyond the session.' },
      { id: 'c', text: 'To assign behavioral homework with rewards for each completed step', isCorrect: false, rationale: 'Contingent rewards for homework belong to behavior therapy, not narrative letter writing.' },
      { id: 'd', text: 'To keep a legal record of the session in place of case notes', isCorrect: false, rationale: 'Therapeutic letters are an intervention addressed to the client; they do not replace clinical records.' },
    ],
    rationale: 'David Epston in particular developed letter writing as a narrative practice. Letters capture unique outcomes and the client\'s preferred story in a durable, rereadable form, turning a thin problem story into a thicker, richly described one. White and Epston also used certificates and documents to celebrate new identities.',
    references: [{ source: C, detail: 'Narrative Therapy: letters and documents that support the alternative story' }],
  },
  // -------------------------------------------------------------- feminist
  {
    id: 'nce-s-cou-142',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'feminist therapy',
    difficulty: 'easy',
    stem: 'Which counselor practice BEST reflects the egalitarian relationship emphasized in feminist therapy?',
    options: [
      { id: 'a', text: 'Keeping a neutral blank screen so the client can project onto the counselor', isCorrect: false, rationale: 'The blank-screen stance is psychoanalytic and widens the power gap feminist counselors try to reduce.' },
      { id: 'b', text: 'Making the counselor\'s diagnosis the main basis for all treatment decisions', isCorrect: false, rationale: 'Feminist counselors are cautious about diagnostic labels and do not make the counselor\'s view the sole authority.' },
      { id: 'c', text: 'Demystifying counseling and treating the client as expert on her life', isCorrect: true, rationale: 'Demystifying the process and honoring the client\'s expertise reduce the power difference and support collaboration.' },
      { id: 'd', text: 'Avoiding any talk of values or social issues so the counselor stays neutral', isCorrect: false, rationale: 'Feminist counselors see neutrality as impossible and openly address values and social context.' },
    ],
    rationale: 'Feminist therapy views the counseling relationship as egalitarian. Counselors demystify the process through informed consent, share their orientation and values, use appropriate self-disclosure and treat clients as experts on their own lives. This models healthier uses of power and supports empowerment.',
    references: [{ source: C, detail: 'Feminist Therapy: the egalitarian therapeutic relationship' }],
  },
  {
    id: 'nce-s-cou-143',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'feminist therapy',
    difficulty: 'medium',
    stem: 'A home health aide who immigrated five years ago blames herself for "being weak" because she has not confronted an agency that underpays her. Her counselor helps her map the differences in power between her and the agency, including economic, legal and gender factors, and explore ways she might access power. This feminist intervention is:',
    options: [
      { id: 'a', text: 'Power analysis', isCorrect: true, rationale: 'Power analysis examines how unequal access to power shapes the client\'s situation and identifies ways to use or gain power.' },
      { id: 'b', text: 'Gender-role analysis', isCorrect: false, rationale: 'Gender-role analysis explores messages about how women and men should be; this work centers on broader power differences.' },
      { id: 'c', text: 'Cognitive reframing', isCorrect: false, rationale: 'Reframing offers a new meaning for the same facts but does not map structural power or plan to access it.' },
      { id: 'd', text: 'Assertiveness drills', isCorrect: false, rationale: 'Assertiveness training may follow, but the intervention described is an analysis of power, not skill rehearsal.' },
    ],
    rationale: 'In power analysis, feminist counselors help clients see the differences in power between groups in society and in their own relationships, and how these shape their options and self-blame. Clients then identify kinds of power they can use. Shifting the view from personal weakness to social context is a core feminist move.',
    references: [{ source: C, detail: 'Feminist Therapy: power analysis and intervention' }],
  },
  {
    id: 'nce-s-cou-144',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'feminist therapy',
    difficulty: 'medium',
    stem: 'Relational-cultural theory (RCT), developed by Jean Baker Miller, Judith Jordan and colleagues at the Stone Center, challenges traditional models of development. According to RCT, psychological growth occurs MAINLY through:',
    options: [
      { id: 'a', text: 'Separating from others to achieve independence and a firm, autonomous self', isCorrect: false, rationale: 'RCT critiques the separation-individuation model that treats autonomy as the goal of maturity.' },
      { id: 'b', text: 'Resolving unconscious drives and conflicts formed in early psychosexual stages', isCorrect: false, rationale: 'This describes Freudian theory, not RCT\'s focus on connection.' },
      { id: 'c', text: 'Learning new behaviors through reinforcement in structured, graded tasks', isCorrect: false, rationale: 'This is a behavioral account of change and omits the relational focus of RCT.' },
      { id: 'd', text: 'Growth-fostering relationships marked by mutual empathy and empowerment', isCorrect: true, rationale: 'RCT holds that people grow through and toward connection, in relationships of mutual empathy and mutual empowerment.' },
    ],
    rationale: 'Relational-cultural theory argues that people grow through connection rather than separation. Growth-fostering relationships involve mutual empathy and mutual empowerment, and chronic disconnection, often linked to marginalization and power, leads to isolation and suffering. RCT is closely tied to feminist therapy and attends to culture and social justice.',
    references: [{ source: C, detail: 'Feminist Therapy: relational-cultural theory (Miller, Jordan)' }],
  },
  // ---------------------------------------------------------------- MI
  {
    id: 'nce-s-cou-145',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: 'Near the end of a session about her drinking, a client says, "I\'m going to call the outpatient program on Monday and set up an intake." Using the DARN-CAT framework, which kind of change talk is this?',
    options: [
      { id: 'a', text: 'Desire', isCorrect: false, rationale: 'Desire statements express wanting or wishing ("I want to cut down"), not a pledge to act.' },
      { id: 'b', text: 'Commitment', isCorrect: true, rationale: '"I\'m going to" signals an intention to act, which is commitment, a form of mobilizing change talk.' },
      { id: 'c', text: 'Reasons', isCorrect: false, rationale: 'Reasons statements give specific benefits of change ("I\'d sleep better").' },
      { id: 'd', text: 'Taking steps', isCorrect: false, rationale: 'Taking steps describes an action already done ("I called them yesterday"); this call has not happened yet.' },
    ],
    rationale: 'Miller and Rollnick group change talk into preparatory talk (Desire, Ability, Reasons, Need) and mobilizing talk (Commitment, Activation, Taking steps). Commitment language such as "I will" or "I\'m going to" predicts change more strongly than preparatory talk. Counselors listen for, reflect and strengthen change talk.',
    references: [{ source: MI, detail: 'Evoking: preparatory (DARN) and mobilizing (CAT) change talk' }],
  },
  {
    id: 'nce-s-cou-146',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: 'A father who smokes in the car with his young children says being a present, healthy dad is "the most important thing in my life." Which response BEST develops discrepancy in a way consistent with the spirit of motivational interviewing?',
    options: [
      { id: 'a', text: '"Your kids matter most to you. How does smoking fit with that?"', isCorrect: true, rationale: 'This reflects his stated value and invites him to voice the gap between it and his behavior, evoking his own reasons.' },
      { id: 'b', text: '"You need to know that secondhand smoke in a car harms children\'s lungs."', isCorrect: false, rationale: 'Lecturing reflects the righting reflex and tends to provoke sustain talk rather than change talk.' },
      { id: 'c', text: '"If your kids matter most, then you would have quit smoking long ago."', isCorrect: false, rationale: 'This is a confrontational argument that challenges his sincerity and is likely to increase discord.' },
      { id: 'd', text: '"Let\'s set a quit date now, and I\'ll give you a list of nicotine aids."', isCorrect: false, rationale: 'Jumping to planning before he voices his own motivation skips evoking and risks resistance.' },
    ],
    rationale: 'Developing discrepancy means helping clients notice the gap between their values or goals and their current behavior, so the client, not the counselor, voices the argument for change. The MI spirit of partnership, acceptance, compassion and evocation rules out lecturing or confrontation, which tend to trigger sustain talk and discord.',
    references: [{ source: MI, detail: 'MI spirit; developing discrepancy between values and behavior' }],
  },
  {
    id: 'nce-s-cou-147',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'easy',
    stem: 'After building rapport with a client who has diabetes, depression and money worries, the counselor and client agree that they will concentrate on his eating and medication habits for now. In the four processes of motivational interviewing, this step is called:',
    options: [
      { id: 'a', text: 'Engaging', isCorrect: false, rationale: 'Engaging is establishing the working relationship, which has already occurred here.' },
      { id: 'b', text: 'Evoking', isCorrect: false, rationale: 'Evoking draws out the client\'s own motivation for change once a direction has been chosen.' },
      { id: 'c', text: 'Focusing', isCorrect: true, rationale: 'Focusing is developing and keeping a specific direction or change goal for the conversation.' },
      { id: 'd', text: 'Planning', isCorrect: false, rationale: 'Planning comes last, when the client is ready to commit to a specific plan of action.' },
    ],
    rationale: 'Miller and Rollnick describe four overlapping processes: engaging (building the relationship), focusing (agreeing on a direction), evoking (drawing out the client\'s own motivation) and planning (developing commitment and a concrete plan). Each builds on the one before, and counselors may return to earlier processes as needed.',
    references: [{ source: MI, detail: 'The four processes: engaging, focusing, evoking, planning' }],
  },
  // ------------------------------------------------------------------ DBT
  {
    id: 'nce-s-cou-148',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'easy',
    stem: 'After a client self-harms, her DBT therapist works with her to trace, step by step, her vulnerability factors that day, the prompting event, each thought, feeling and action leading to the behavior, and the consequences that followed. This procedure is called:',
    options: [
      { id: 'a', text: 'Radical acceptance', isCorrect: false, rationale: 'Radical acceptance is a distress tolerance skill of fully accepting reality as it is; it does not map links to a behavior.' },
      { id: 'b', text: 'A thought record', isCorrect: false, rationale: 'A thought record tracks situations, automatic thoughts and alternative responses (CBT), not a full behavioral sequence.' },
      { id: 'c', text: 'Wise mind practice', isCorrect: false, rationale: 'Wise mind is a mindfulness skill integrating emotion mind and reasonable mind, not an analysis of a behavior.' },
      { id: 'd', text: 'Behavioral chain analysis', isCorrect: true, rationale: 'Chain analysis maps every link from vulnerability and prompting event to the target behavior and its consequences.' },
    ],
    rationale: 'In DBT, a behavioral chain analysis is done after a target behavior such as self-harm. Therapist and client identify vulnerabilities, the prompting event, the chain of thoughts, emotions, sensations and actions, the behavior and its consequences. Each link becomes a point where a skill could be used instead, and a solution analysis follows.',
    references: [{ source: C, detail: 'Dialectical behavior therapy: behavioral chain analysis' }],
  },
  {
    id: 'nce-s-cou-149',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'medium',
    stem: 'A client in a DBT skills group practices asking her roommate to pay his share of the rent. At one point she says, "If you get your half to me by Friday, I\'ll stop bringing it up and things can get back to normal between us." In the DEAR MAN skill, this statement illustrates:',
    options: [
      { id: 'a', text: 'Assert', isCorrect: false, rationale: 'Assert is clearly asking for what one wants or saying no ("I need your half of the rent").' },
      { id: 'b', text: 'Reinforce', isCorrect: true, rationale: 'Reinforce means rewarding the person ahead of time by explaining the positive effects of getting what one asks for.' },
      { id: 'c', text: 'Negotiate', isCorrect: false, rationale: 'Negotiate is being willing to give to get, such as offering alternatives or a compromise.' },
      { id: 'd', text: 'Express', isCorrect: false, rationale: 'Express is sharing one\'s feelings and opinions about the situation using "I" statements.' },
    ],
    rationale: 'DEAR MAN is a DBT interpersonal effectiveness skill: Describe the situation, Express feelings, Assert the request, Reinforce the other person in advance, stay Mindful, Appear confident and Negotiate. Reinforcing explains what the other person gains by agreeing, which makes a yes more likely.',
    references: [{ source: C, detail: 'Dialectical behavior therapy: interpersonal effectiveness skills (DEAR MAN)' }],
    reviewNote: 'DEAR MAN detail comes from Linehan\'s DBT Skills Training Manual, which is not in the approved library; Corey covers DBT modules only briefly. Consider adding Linehan as an approved source.',
  },
  {
    id: 'nce-s-cou-150',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'hard',
    stem: 'A client says she freezes and goes silent whenever her manager raises his voice. Her DBT therapist responds, "Growing up, speaking up when your father yelled got you punished, so freezing makes sense given what you learned." In Linehan\'s levels of validation, this response BEST illustrates:',
    options: [
      { id: 'a', text: 'Validating in terms of past learning or biology', isCorrect: true, rationale: 'This level explains the response as understandable given the client\'s history, even if it does not fit the present situation.' },
      { id: 'b', text: 'Normalizing in terms of present circumstances', isCorrect: false, rationale: 'This level says the response would make sense for anyone in the current situation, without reference to the client\'s history.' },
      { id: 'c', text: 'Articulating the client\'s unverbalized feelings', isCorrect: false, rationale: 'This level puts into words what the client has not said, such as a feeling she has not named.' },
      { id: 'd', text: 'Radical genuineness with the client as an equal', isCorrect: false, rationale: 'Radical genuineness treats the client as a capable equal rather than fragile; it does not explain a response by history.' },
    ],
    rationale: 'Linehan described six levels of validation: (1) staying awake and attentive, (2) accurate reflection, (3) articulating the unverbalized, (4) validating in terms of past learning or biology, (5) normalizing in terms of present context, and (6) radical genuineness. Validation balances DBT\'s change strategies, communicating that the client\'s responses make sense, which supports the acceptance side of the acceptance-change dialectic.',
    references: [{ source: C, detail: 'Dialectical behavior therapy: validation strategies and the acceptance-change dialectic' }],
    reviewNote: 'Six validation levels follow Linehan (1997, 2015); Linehan is not in the approved source library and Corey may not list all six levels. SME should confirm the citation.',
  },
];
