// tools/nce/seed/counseling-13.js — Counseling Skills and Interventions, batch 7
// Hand-authored original items (nce-s-cou-361 … nce-s-cou-390).
const CO = 'Corey (Theory & Practice)';
const JB = 'J. Beck (CBT: Basics and Beyond)';
const ED = 'Ellis & Dryden (REBT)';
const WH = 'White (Maps of Narrative Practice)';
const MR = 'Miller & Rollnick (MI)';
const LN = 'Linehan (DBT Skills Training Manual)';
const GO = 'Goldenberg (Family Therapy)';

module.exports = [
  // ── PSYCHODYNAMIC AND PSYCHOANALYTIC THEORY ──────────────────────────────
  {
    id: 'nce-s-cou-361',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'easy',
    stem: `A 6-year-old who has been openly jealous since his baby sister was born now hugs her so often and so hard that she cries, and he loudly tells every visitor how much he loves her. Which defense mechanism does this BEST illustrate?`,
    options: [
      { id: 'a', text: `Sublimation`, isCorrect: false, rationale: `Sublimation channels an unacceptable impulse into a socially valued activity, such as art or sport, not into its exaggerated opposite.` },
      { id: 'b', text: `Projection`, isCorrect: false, rationale: `Projection attributes one's own impulse to someone else; he is not claiming that his sister is jealous of him.` },
      { id: 'c', text: `Reaction formation`, isCorrect: true, rationale: `He wards off unacceptable hostility by showing the opposite feeling in an exaggerated, rigid way, and the hostility leaks through.` },
      { id: 'd', text: `Regression`, isCorrect: false, rationale: `Regression is a return to behavior from an earlier stage, such as bed-wetting or baby talk, which is not described here.` },
    ],
    rationale: `In reaction formation, a person defends against a threatening impulse by actively expressing its opposite. The display is often excessive and inflexible, which is a clue that it is defensive rather than genuine. Here the overdone affection keeps jealousy out of awareness, while the rough hugs hint at the hostility underneath.`,
    references: [{ source: CO, detail: 'Psychoanalytic therapy: ego-defense mechanisms (reaction formation)' }],
  },
  {
    id: 'nce-s-cou-362',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'hard',
    stem: `A 35-year-old client raised in a strict household feels intense guilt and dread after she skips a family dinner to rest, even though no one has criticized her and nothing bad has happened. According to Freud's three types of anxiety, which type is she MOST likely experiencing?`,
    options: [
      { id: 'a', text: `Moral anxiety, a fear of her own conscience`, isCorrect: true, rationale: `Moral anxiety arises when the superego threatens to punish the ego for acting against internalized standards, and it is felt as guilt.` },
      { id: 'b', text: `Reality anxiety, a fear of a real outside threat`, isCorrect: false, rationale: `Reality anxiety is proportionate fear of an actual external danger; no one has criticized or threatened her.` },
      { id: 'c', text: `Neurotic anxiety, a fear of id urges breaking out`, isCorrect: false, rationale: `Neurotic anxiety is fear that instinctual impulses will break through and bring punishment; her distress centers on violated standards.` },
      { id: 'd', text: `Separation anxiety, a fear of losing an attachment`, isCorrect: false, rationale: `Separation anxiety is not one of Freud's three types of anxiety, and her fear is not about losing a caregiver.` },
    ],
    rationale: `Freud described three kinds of anxiety, each tied to a source of threat to the ego. Reality anxiety responds to dangers in the outside world, neurotic anxiety to the fear that id impulses will escape control, and moral anxiety to the fear of one's own conscience. Guilt after acting against internalized rules, with no outside threat present, points to moral anxiety from the superego.`,
    references: [{ source: CO, detail: 'Psychoanalytic therapy: anxiety (reality, neurotic and moral anxiety)' }],
  },

  // ── ADLERIAN THERAPY ─────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-363',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'medium',
    stem: `Over several sessions, an Adlerian counselor and a 42-year-old client have explored his family constellation and early memories, and he now understands his belief that he must please everyone to belong. The counselor next helps him try new behaviors and make different choices outside sessions. Which phase of Adlerian counseling is this?`,
    options: [
      { id: 'a', text: `Establishing the therapeutic relationship`, isCorrect: false, rationale: `Building a cooperative, egalitarian relationship is the first phase, and it is already in place here.` },
      { id: 'b', text: `Exploring the client's psychological dynamics`, isCorrect: false, rationale: `Assessment of the family constellation and early memories has already been completed.` },
      { id: 'c', text: `Encouraging self-understanding and insight`, isCorrect: false, rationale: `He has already gained insight into his mistaken belief; the work now moves from insight to action.` },
      { id: 'd', text: `Reorientation and reeducation of the client`, isCorrect: true, rationale: `The final phase puts insight into action, as the client is encouraged to take new risks and make new choices.` },
    ],
    rationale: `Adlerian counseling is commonly described in four phases: forming the relationship, assessing psychological dynamics through the lifestyle assessment, encouraging insight, and reorientation and reeducation. In reorientation, the counselor uses encouragement and action-oriented techniques so the client can act on new understanding. Insight alone is not seen as enough; change shows up in new behavior.`,
    references: [{ source: CO, detail: 'Adlerian therapy: the four phases of the therapeutic process (reorientation and reeducation)' }],
  },
  {
    id: 'nce-s-cou-364',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'easy',
    stem: `A 28-year-old client is thriving in her career but says she has no close friends and avoids dating. Her Adlerian counselor wants to assess how she is meeting the three life tasks that Adler described. Which set names those tasks?`,
    options: [
      { id: 'a', text: `Trust, autonomy and initiative`, isCorrect: false, rationale: `These are outcomes of Erikson's first three psychosocial stages, not Adler's life tasks.` },
      { id: 'b', text: `Work, friendship and love`, isCorrect: true, rationale: `Adler held that everyone must meet the tasks of occupation, society or friendship, and love or intimacy.` },
      { id: 'c', text: `Safety, esteem and belonging`, isCorrect: false, rationale: `These are levels in Maslow's hierarchy of needs rather than Adler's tasks.` },
      { id: 'd', text: `Freedom, fun and power`, isCorrect: false, rationale: `These are among Glasser's basic needs in choice theory, not Adler's life tasks.` },
    ],
    rationale: `Adler proposed that each person must address three universal life tasks: work, friendship (society) and love (intimacy). Later Adlerians such as Dreikurs and Mosak added tasks related to spirituality and getting along with oneself. Difficulty in one task, like this client's avoidance of friendship and intimacy, often reflects mistaken beliefs in her lifestyle.`,
    references: [{ source: CO, detail: 'Adlerian therapy: life tasks of work, friendship and love' }],
  },

  // ── PERSON-CENTERED THERAPY ──────────────────────────────────────────────
  {
    id: 'nce-s-cou-365',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'easy',
    stem: `A counselor invites a 47-year-old client to move to music, then draw whatever the movement stirred, then write freely about the drawing, with no judging of skill and with steady empathy and acceptance. Developed by Natalie Rogers, this approach extends her father Carl Rogers's core conditions. What is it called?`,
    options: [
      { id: 'a', text: `Person-centered expressive arts therapy`, isCorrect: true, rationale: `Natalie Rogers built this approach on her father's core conditions, linking art forms in sequence, which she called the creative connection.` },
      { id: 'b', text: `Psychoanalytic art therapy (Naumburg)`, isCorrect: false, rationale: `Naumburg's approach treats images as symbolic speech from the unconscious for interpretation, not as nondirective, linked expression.` },
      { id: 'c', text: `Psychodrama with role enactment (Moreno)`, isCorrect: false, rationale: `Psychodrama has clients act out scenes with a director and auxiliary egos; it does not chain movement, art and writing.` },
      { id: 'd', text: `Gestalt dream work, playing each part`, isCorrect: false, rationale: `Gestalt dream work has the client speak as each part of a dream, which is not the sequence described.` },
    ],
    rationale: `Natalie Rogers developed person-centered expressive arts therapy, which applies empathy, congruence and unconditional positive regard to the use of movement, art, writing, sound and other media. She described the creative connection, in which one art form stirs feelings that feed the next, deepening self-awareness. The focus is on the client's own process and meaning, not on artistic skill or counselor interpretation.`,
    references: [{ source: CO, detail: 'Person-centered therapy: Natalie Rogers\'s person-centered expressive arts therapy and the creative connection' }],
  },
  {
    id: 'nce-s-cou-366',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'medium',
    stem: `A new agency counselor trained in the person-centered approach asks her supervisor why traditional diagnosis and extensive formal testing play only a small role in her model. Which explanation BEST reflects Rogers's view?`,
    options: [
      { id: 'a', text: `Testing is too time-consuming to fit within a short course of counseling`, isCorrect: false, rationale: `Rogers's objection was about the stance diagnosis creates, not about how long tests take.` },
      { id: 'b', text: `Diagnosis is valid only when it is made by a psychiatrist or psychologist`, isCorrect: false, rationale: `Rogers did not argue that only certain professions may diagnose; he questioned the expert role itself.` },
      { id: 'c', text: `They cast the counselor as outside expert and shift focus off the client's view`, isCorrect: true, rationale: `Rogers worried that diagnosis puts the locus of evaluation in the counselor and pulls attention from the client's own experience.` },
      { id: 'd', text: `Test results lack the reliability needed to guide any treatment decisions`, isCorrect: false, rationale: `Rogers was not mainly critiquing test reliability; his concern was the effect on the relationship.` },
    ],
    rationale: `Person-centered counselors see the client, not the counselor, as the best expert on the client's life. Rogers believed that diagnosis and heavy reliance on testing place the counselor in an authoritative, evaluating role and can encourage an external locus of evaluation. Understanding comes instead from entering the client's subjective world, though many person-centered counselors still diagnose when settings require it.`,
    references: [{ source: CO, detail: 'Person-centered therapy: role of assessment and diagnosis' }],
  },

  // ── EXISTENTIAL THERAPY ──────────────────────────────────────────────────
  {
    id: 'nce-s-cou-367',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'medium',
    stem: `A 39-year-old client in a loving marriage, with close friends, says, "Even with all of them, there is a part of me no one can ever fully reach. I came into the world alone and I'll leave it alone." Yalom distinguished three kinds of isolation. Which kind is the client describing?`,
    options: [
      { id: 'a', text: `Interpersonal isolation from other people`, isCorrect: false, rationale: `Interpersonal isolation is loneliness from a lack of relationships or social skills; she has close ties.` },
      { id: 'b', text: `Existential isolation, an unbridgeable gulf`, isCorrect: true, rationale: `Existential isolation is the basic separateness of each person from others and the world, which no relationship can erase.` },
      { id: 'c', text: `Intrapersonal isolation within the self`, isCorrect: false, rationale: `Intrapersonal isolation is being cut off from parts of oneself, such as through repressed feelings or wishes.` },
      { id: 'd', text: `Social isolation caused by stigma or exclusion`, isCorrect: false, rationale: `Exclusion by others is not one of Yalom's three forms, and she reports being well connected.` },
    ],
    rationale: `Yalom described interpersonal isolation (separation from others), intrapersonal isolation (separation from parts of oneself) and existential isolation, the deepest form. Existential isolation refers to the unbridgeable gap between oneself and any other being, since each person enters and leaves existence alone. Existential counselors help clients face this reality and relate to others out of choice rather than out of fear of being alone.`,
    references: [{ source: CO, detail: 'Existential therapy: Yalom on isolation as an ultimate concern' }],
  },
  {
    id: 'nce-s-cou-368',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'hard',
    stem: `A 33-year-old man reports problems with sexual arousal. He describes constantly watching his own body for signs of failure during intimacy. His logotherapist encourages him to turn his attention away from himself and toward his partner and the shared experience. Which technique of Viktor Frankl is this?`,
    options: [
      { id: 'a', text: `Paradoxical intention`, isCorrect: false, rationale: `Paradoxical intention asks the client to wish for or deliberately try to produce the feared symptom, which is not what is described.` },
      { id: 'b', text: `Socratic dialogue`, isCorrect: false, rationale: `Socratic dialogue uses questions to help clients discover meaning; it does not redirect attention during the problem behavior.` },
      { id: 'c', text: `Attitude modification`, isCorrect: false, rationale: `Attitude modification aims to change a client's stance toward unavoidable suffering, not to shift attention away from the self.` },
      { id: 'd', text: `Dereflection`, isCorrect: true, rationale: `Dereflection counters hyperreflection, excessive self-observation, by redirecting attention away from the self toward other people or meanings.` },
    ],
    rationale: `Frankl observed that some problems, such as sexual dysfunction and insomnia, are worsened by hyperreflection, an anxious focus on oneself and one's performance. Dereflection breaks this cycle by turning the client's attention outward, toward a partner, a task or a meaning beyond the self. It differs from paradoxical intention, which deliberately invites the feared symptom.`,
    references: [{ source: CO, detail: 'Existential therapy: Frankl\'s logotherapy, dereflection and hyperreflection' }],
  },

  // ── GESTALT THERAPY ──────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-369',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'gestalt therapy',
    difficulty: 'medium',
    stem: `A client who describes himself as "easygoing" keeps complaining that his coworkers are "so judgmental" and "always criticizing everyone." His gestalt counselor asks him to repeat each sentence about his coworkers but begin it with "I," as in "I am so judgmental." Which contact disturbance is the counselor addressing?`,
    options: [
      { id: 'a', text: `Projection`, isCorrect: true, rationale: `In projection, a person disowns aspects of the self and attributes them to others; restating them with "I" helps him reown them.` },
      { id: 'b', text: `Introjection`, isCorrect: false, rationale: `Introjection is swallowing others' standards without examining them, not attributing one's own traits to others.` },
      { id: 'c', text: `Retroflection`, isCorrect: false, rationale: `Retroflection is turning onto oneself what one would like to do to others.` },
      { id: 'd', text: `Confluence`, isCorrect: false, rationale: `Confluence blurs the boundary between self and others so differences are not experienced.` },
    ],
    rationale: `Gestalt therapists view projection as disowning parts of oneself and seeing them in the environment instead. A common intervention is to have the client restate what he sees in others as statements about himself, which helps him notice and take responsibility for the disowned trait. The goal is greater awareness and integration rather than interpretation by the counselor.`,
    references: [{ source: CO, detail: 'Gestalt therapy: contact and resistances to contact (projection)' }],
  },
  {
    id: 'nce-s-cou-370',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'gestalt therapy',
    difficulty: 'easy',
    stem: `In a gestalt-oriented group, a member says she is sure nobody in the room really trusts her. The leader invites her to go to each member in turn and say something to them, such as "I'm afraid you don't trust me because...," completing the sentence for each person. What is this exercise called?`,
    options: [
      { id: 'a', text: `Empty chair`, isCorrect: false, rationale: `The empty chair has a client speak to an imagined person or part of the self, not to each real group member.` },
      { id: 'b', text: `Reversal`, isCorrect: false, rationale: `Reversal asks a client to act out the opposite of a usual behavior, such as a timid member playing a bold one.` },
      { id: 'c', text: `Making the rounds`, isCorrect: true, rationale: `In making the rounds, a member speaks to or does something with each other member to explore a theme or take a risk.` },
      { id: 'd', text: `Rehearsal`, isCorrect: false, rationale: `Rehearsal is practicing aloud what one has been silently preparing to say, not addressing each member in turn.` },
    ],
    rationale: `Making the rounds is a gestalt group exercise in which one member goes around the group, speaking to or doing something with each person. It is used when a member voices a feeling about the group as a whole, such as mistrust, so the feeling can be checked directly with each member. The exercise builds awareness and gives the member a chance to take a risk in the moment.`,
    references: [{ source: CO, detail: 'Gestalt therapy: experiments and exercises (making the rounds)' }],
  },

  // ── BEHAVIOR THERAPY ─────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-371',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: `A 9-year-old watches a skilled peer model a complex juggling routine. He pays close attention, can describe each step afterward and badly wants to perform it, yet he cannot do the routine because he lacks the coordination. In Bandura's model of observational learning, which process is limiting his performance?`,
    options: [
      { id: 'a', text: `Attention`, isCorrect: false, rationale: `He watched closely, so attention to the model was not the problem.` },
      { id: 'b', text: `Retention`, isCorrect: false, rationale: `He can describe each step, showing that he has stored the behavior in memory.` },
      { id: 'c', text: `Motivation`, isCorrect: false, rationale: `He badly wants to perform the routine, so motivation is present.` },
      { id: 'd', text: `Reproduction`, isCorrect: true, rationale: `Reproduction requires the physical capability to turn the stored image into action, which he lacks.` },
    ],
    rationale: `Bandura identified four processes in observational learning: attention, retention, motor reproduction and motivation. A learner may attend to a model, remember the behavior and want to imitate it, yet still fail if he lacks the skills to reproduce it. In counseling, modeling is often paired with guided practice and feedback to build the capacity to reproduce new behavior.`,
    references: [{ source: CO, detail: 'Behavior therapy: social learning (social-cognitive) approach and modeling' }],
  },
  {
    id: 'nce-s-cou-372',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: `A 50-year-old client who wants to cut back on late-night snacking agrees to write down, each time she snacks, the time, what she ate, where she was and how she felt. Within a week, before any other intervention, her snacking drops. Which statement BEST explains this?`,
    options: [
      { id: 'a', text: `Writing in a log serves as a punisher that is applied each time she eats`, isCorrect: false, rationale: `The log is not set up as an aversive consequence; the change comes from heightened awareness.` },
      { id: 'b', text: `Self-monitoring can be reactive, as the act of recording changes behavior`, isCorrect: true, rationale: `Self-monitoring is a core step in self-management, and recording a behavior often changes it in the desired direction.` },
      { id: 'c', text: `The log has extinguished snacking by removing the reward that keeps it up`, isCorrect: false, rationale: `Extinction requires withholding the reinforcer; the snacks themselves were still available and eaten.` },
      { id: 'd', text: `Recording her moods has desensitized her to cues that prompt late eating`, isCorrect: false, rationale: `Desensitization pairs relaxation with graded exposure; writing a log does not do this.` },
    ],
    rationale: `Self-management programs typically include choosing a goal, defining target behaviors, self-monitoring, building a plan for change and evaluating progress. Self-monitoring, the careful recording of when and where a behavior occurs, gives data for the plan. It is also reactive: simply observing and recording a behavior often shifts it toward the client's goal.`,
    references: [{ source: CO, detail: 'Behavior therapy: self-management programs and self-monitoring' }],
  },

  // ── COGNITIVE BEHAVIORAL THERAPY ─────────────────────────────────────────
  {
    id: 'nce-s-cou-373',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'easy',
    stem: `Early in a typical cognitive behavioral session, after a brief mood check, the counselor asks a 31-year-old client, "What problems or topics would you most like to work on today?" and the two decide together how to use the time. Which part of a CBT session is this?`,
    options: [
      { id: 'a', text: `Assigning homework`, isCorrect: false, rationale: `Homework, or an action plan, is usually set near the end of the session, not at the start.` },
      { id: 'b', text: `Setting the agenda`, isCorrect: true, rationale: `Collaborative agenda setting early in the session decides which problems the session will address.` },
      { id: 'c', text: `Eliciting feedback`, isCorrect: false, rationale: `Feedback on the session is asked for at the end, after work on the agenda is done.` },
      { id: 'd', text: `Final summary`, isCorrect: false, rationale: `A final summary pulls together the session's main points and comes near the close.` },
    ],
    rationale: `J. Beck describes a structured CBT session that typically includes a mood check, setting the agenda, reviewing the action plan, working on agenda items, summarizing, setting new homework and getting feedback. Setting the agenda together makes the most of limited time and models collaboration and problem solving. Structure is a defining feature of CBT, though the counselor adapts it to each client.`,
    references: [{ source: JB, detail: 'Structure of the therapy session: setting the agenda' }],
  },
  {
    id: 'nce-s-cou-374',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: `A 24-year-old client predicts, "If I speak up in my team meeting, people will roll their eyes and ignore me." He and his CBT counselor agree that he will make one comment at Thursday's meeting, note exactly how people respond and compare it with his prediction. What is this intervention?`,
    options: [
      { id: 'a', text: `A behavioral experiment to test the accuracy of his prediction`, isCorrect: true, rationale: `Behavioral experiments set up real-world tests of a specific belief and compare the outcome with the prediction.` },
      { id: 'b', text: `Flooding with full exposure to his most feared social situation`, isCorrect: false, rationale: `Flooding is prolonged exposure to a highly feared stimulus; one planned comment to test a belief is not this.` },
      { id: 'c', text: `Thought stopping to interrupt the negative thought as it arises`, isCorrect: false, rationale: `Thought stopping suppresses thoughts; this plan gathers evidence about the thought instead.` },
      { id: 'd', text: `Activity scheduling to raise his overall level of pleasant events`, isCorrect: false, rationale: `Activity scheduling targets mood through rewarding activities, not testing a particular prediction.` },
    ],
    rationale: `In CBT, a behavioral experiment is a planned activity that tests the validity of a thought or belief in real life. The client states the prediction, carries out the experiment and then compares what happened with what he expected. Evidence gathered firsthand is often more convincing than evidence discussed in session.`,
    references: [{ source: JB, detail: 'Behavioral experiments to test automatic thoughts and beliefs' }],
  },

  // ── RATIONAL EMOTIVE BEHAVIOR THERAPY ────────────────────────────────────
  {
    id: 'nce-s-cou-375',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'medium',
    stem: `A client says, "My boss must approve of everything I do, and if she doesn't, it shows I'm incompetent." Her REBT counselor asks, "Where is the evidence that your boss has to approve of everything you do? Is there any proof one bit of criticism means you are incompetent?" Which type of disputing is this?`,
    options: [
      { id: 'a', text: `Pragmatic disputing of how useful the belief is`, isCorrect: false, rationale: `Pragmatic disputing asks where a belief gets the client and how it helps or hurts her, not whether evidence supports it.` },
      { id: 'b', text: `Logical disputing of whether the belief follows`, isCorrect: false, rationale: `Logical disputing asks whether a demand follows logically from a preference, not whether evidence exists for it.` },
      { id: 'c', text: `Empirical disputing of the facts behind a belief`, isCorrect: true, rationale: `Empirical disputing asks for evidence that the belief is consistent with reality.` },
      { id: 'd', text: `Imaginal disputing using a vivid mental scene`, isCorrect: false, rationale: `Imagery techniques use vivid mental scenes, while this response asks direct questions about evidence.` },
    ],
    rationale: `REBT counselors dispute irrational beliefs in several ways. Empirical disputing asks whether there is evidence for the belief, logical disputing asks whether it follows from the client's preferences, and pragmatic disputing asks whether it helps the client reach her goals. Questions like "Where is the evidence?" mark the empirical approach.`,
    references: [{ source: ED, detail: 'Disputing irrational beliefs: empirical, logical and pragmatic arguments' }],
  },
  {
    id: 'nce-s-cou-376',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'rational emotive behavior therapy',
    difficulty: 'hard',
    stem: `A counselor trained in person-centered work begins learning REBT and asks how Albert Ellis viewed counselor warmth and a close, nurturing relationship. Which statement BEST reflects Ellis's position?`,
    options: [
      { id: 'a', text: `Warmth is the main ingredient of change, so it should come before disputing`, isCorrect: false, rationale: `This describes a relationship-centered view; Ellis placed the active disputing of beliefs at the center of change.` },
      { id: 'b', text: `Warmth is suited only to children, and adults respond best to firm debate`, isCorrect: false, rationale: `Ellis did not divide clients by age this way; his caution about warmth applied broadly.` },
      { id: 'c', text: `Warmth is useful only once the client has fully adopted rational beliefs`, isCorrect: false, rationale: `Ellis did not make warmth a reward for progress; he questioned its value as a change agent at any point.` },
      { id: 'd', text: `Full acceptance is vital, but much warmth may feed a dire need for approval`, isCorrect: true, rationale: `Ellis valued unconditional acceptance yet warned that too much warmth can reinforce clients' need for love and approval.` },
    ],
    rationale: `Ellis held that the counselor should accept clients unconditionally as fallible humans, but he did not see a warm, close relationship as necessary or sufficient for change. He cautioned that excessive warmth may foster dependence and reinforce the irrational belief that one must be approved of. In REBT, change comes mainly from actively disputing irrational beliefs and practicing new ones.`,
    references: [{ source: CO, detail: 'REBT: the therapist-client relationship and the role of warmth' }],
  },

  // ── REALITY THERAPY AND CHOICE THEORY ────────────────────────────────────
  {
    id: 'nce-s-cou-377',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'medium',
    stem: `A client in reality therapy offers this plan for the coming week: "I'm going to get my husband to stop criticizing me at dinner." Using Wubbolding's characteristics of an effective plan (SAMIC), what is the MAIN problem with this plan?`,
    options: [
      { id: 'a', text: `It is not controlled by the planner, since it depends on her husband`, isCorrect: true, rationale: `Effective plans are within the client's own control; she cannot control her husband's behavior.` },
      { id: 'b', text: `It is not immediate, since it is set for some time in the distant future`, isCorrect: false, rationale: `The plan is for the coming week, so it is timely enough to be acted on soon.` },
      { id: 'c', text: `It is too simple, since good plans need several detailed parts to work`, isCorrect: false, rationale: `Wubbolding favors simple plans; simplicity is a strength, not the flaw here.` },
      { id: 'd', text: `It lacks evaluation, since she has not rated her wants on a 1-10 scale`, isCorrect: false, rationale: `Self-evaluation is part of WDEP, but rating on a scale is not a requirement for an effective plan.` },
    ],
    rationale: `Wubbolding summarized effective plans with SAMIC: simple, attainable, measurable, immediate, controlled by the planner, committed to and consistently done. Because choice theory holds that we can control only our own behavior, a plan that depends on changing someone else is likely to fail. The counselor would help her craft a plan about what she herself will do at dinner.`,
    references: [{ source: CO, detail: 'Reality therapy: Wubbolding\'s characteristics of effective plans (SAMIC)' }],
  },
  {
    id: 'nce-s-cou-378',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'easy',
    stem: `A middle school principal relies on detentions, threats and reward charts to make students behave. William Glasser would describe this way of trying to make others act as we want with which term?`,
    options: [
      { id: 'a', text: `Positive behavior support`, isCorrect: false, rationale: `This is a school-wide behavioral framework, not Glasser's term for coercive control.` },
      { id: 'b', text: `Logical consequences`, isCorrect: false, rationale: `Logical consequences is an Adlerian and Dreikurs concept, not Glasser's critique.` },
      { id: 'c', text: `Token economy program`, isCorrect: false, rationale: `A token economy is a behavioral system of earned rewards, not Glasser's broader term.` },
      { id: 'd', text: `External control psychology`, isCorrect: true, rationale: `Glasser used this term for the belief that people can be made to behave through rewards, punishment and coercion.` },
    ],
    rationale: `Glasser contrasted choice theory with external control psychology, the common belief that we can and should control others through rewards, punishments and pressure. He argued that external control damages relationships and that people choose their own behavior to meet their needs. He applied these ideas to schools as well as counseling.`,
    references: [{ source: CO, detail: 'Reality therapy: choice theory versus external control psychology' }],
  },

  // ── SOLUTION-FOCUSED BRIEF THERAPY ───────────────────────────────────────
  {
    id: 'nce-s-cou-379',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'hard',
    stem: `A grandmother raising her 12-year-old grandson describes his defiance in detail and clearly wants things to change, but she believes only he can fix it and sees no role for herself. In de Shazer's terms, what is this relationship and what task fits it BEST?`,
    options: [
      { id: 'a', text: `Customer; ask her to try a new action at home this week`, isCorrect: false, rationale: `A customer sees herself as part of the solution and is ready to act; she does not yet see a role for herself.` },
      { id: 'b', text: `Visitor; compliment her and give no tasks at this time`, isCorrect: false, rationale: `A visitor does not see a problem to work on; she clearly names a problem she wants solved.` },
      { id: 'c', text: `Complainant; compliment her and give an observing task`, isCorrect: true, rationale: `A complainant describes a problem but not her part in solving it, so observation tasks fit best.` },
      { id: 'd', text: `Customer; teach her a new discipline plan to use with him`, isCorrect: false, rationale: `Teaching a new plan assumes customer-level readiness and puts the counselor in the expert role.` },
    ],
    rationale: `de Shazer described three kinds of client-counselor relationships. Visitors do not see a problem to work on, complainants describe a problem but do not yet see themselves as part of the solution, and customers are ready to act. For a complainant, the counselor compliments her concern and assigns observing tasks, such as noticing when her grandson is more cooperative.`,
    references: [{ source: CO, detail: 'Solution-focused brief therapy: customer, complainant and visitor relationships' }],
  },
  {
    id: 'nce-s-cou-380',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'solution-focused brief therapy',
    difficulty: 'medium',
    stem: `At the start of a first session, a solution-focused counselor asks a 45-year-old client, "Between the time you called to make this appointment and today, what have you noticed that's already a little different or better?" What is the main purpose of this question?`,
    options: [
      { id: 'a', text: `To check symptom severity before setting a diagnosis`, isCorrect: false, rationale: `Solution-focused counselors do not center the work on diagnosis or symptom severity.` },
      { id: 'b', text: `To find pre-session change the client can build on`, isCorrect: true, rationale: `The question looks for improvement that happened before therapy began, highlighting the client's own resources.` },
      { id: 'c', text: `To learn how ready the client is to accept homework`, isCorrect: false, rationale: `The question is about change already under way, not willingness to accept tasks.` },
      { id: 'd', text: `To uncover the root cause of the presenting problem`, isCorrect: false, rationale: `Solution-focused therapy does not search for causes of problems.` },
    ],
    rationale: `Solution-focused counselors often ask about pre-session (pre-therapy) change, since many clients notice some improvement between scheduling and the first session. Highlighting that change shows the client that change is already happening and that she contributed to it. The counselor then asks what she did to make it happen and how to do more of it.`,
    references: [{ source: CO, detail: 'Solution-focused brief therapy: pretherapy change' }],
  },

  // ── NARRATIVE THERAPY ────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-381',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'hard',
    stem: `A narrative counselor helps a 17-year-old move step by step from naming small, familiar events, to linking them, to drawing lessons from them and, finally, to forming plans based on those lessons. Each question stretches just beyond what the client can already know on her own. Michael White based this "scaffolding" map on which theorist's idea?`,
    options: [
      { id: 'a', text: `Vygotsky's zone of proximal development`, isCorrect: true, rationale: `White drew on Vygotsky's idea that learning happens in the gap between what one knows and what one can reach with support.` },
      { id: 'b', text: `Piaget's process of cognitive accommodation`, isCorrect: false, rationale: `Accommodation is Piaget's term for changing schemas; White's scaffolding map draws on Vygotsky.` },
      { id: 'c', text: `Bandura's concept of perceived self-efficacy`, isCorrect: false, rationale: `Self-efficacy is belief in one's capability; it is not the basis of the scaffolding map.` },
      { id: 'd', text: `Erikson's identity vs. role confusion`, isCorrect: false, rationale: `Erikson's adolescent stage concerns identity, not structured steps of learning with support.` },
    ],
    rationale: `In Maps of Narrative Practice, White describes scaffolding conversations based on Vygotsky's zone of proximal development. The counselor asks questions that help the client move in manageable steps from the known and familiar toward what is possible to know. This lets the client develop new concepts about her life and plans for action that she could not reach alone.`,
    references: [{ source: WH, detail: 'Scaffolding conversations and the zone of proximal development' }],
  },
  {
    id: 'nce-s-cou-382',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'narrative therapy',
    difficulty: 'easy',
    stem: `In a first session, a 54-year-old man describes his life only in terms of his depression: lost jobs, missed events and "letting everyone down." Other parts of his life barely appear in his account. Narrative therapists have a name for this kind of account. What is it?`,
    options: [
      { id: 'a', text: `A unique outcome`, isCorrect: false, rationale: `A unique outcome is an event that contradicts the problem story, the opposite of what he is describing.` },
      { id: 'b', text: `An alternative story`, isCorrect: false, rationale: `An alternative story is the preferred account built later from unique outcomes.` },
      { id: 'c', text: `A definitional ceremony`, isCorrect: false, rationale: `A definitional ceremony uses outsider witnesses to acknowledge a client's preferred story.` },
      { id: 'd', text: `A problem-saturated story`, isCorrect: true, rationale: `A problem-saturated story is a dominant account in which the problem defines the person's life and identity.` },
    ],
    rationale: `Narrative therapists describe the accounts clients bring as often problem-saturated, meaning the problem dominates how they see their lives and themselves. Such stories leave out experiences that do not fit the problem. The counselor externalizes the problem and searches for unique outcomes that can grow into a richer alternative story.`,
    references: [{ source: CO, detail: 'Narrative therapy: problem-saturated stories and alternative stories' }],
  },

  // ── FEMINIST THERAPY ─────────────────────────────────────────────────────
  {
    id: 'nce-s-cou-383',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'feminist therapy',
    difficulty: 'medium',
    stem: `A 34-year-old Korean American client says she longs to feel close to her friends, yet after past betrayals she hides her sadness and needs from them to avoid being hurt again. She notices this leaves her feeling even more alone. In relational-cultural theory, what is this dynamic called?`,
    options: [
      { id: 'a', text: `Mutual empowerment between friends`, isCorrect: false, rationale: `Mutual empowerment is an outcome of growth-fostering relationships, the opposite of the self-protective hiding she describes.` },
      { id: 'b', text: `Confluence with the friend group`, isCorrect: false, rationale: `Confluence is a gestalt term for blurring the boundary between self and others; she is holding herself apart.` },
      { id: 'c', text: `The central relational paradox`, isCorrect: true, rationale: `RCT describes yearning for connection while keeping parts of oneself out of relationships for safety, which deepens disconnection.` },
      { id: 'd', text: `An internalized gender-role message`, isCorrect: false, rationale: `Gender-role messages are explored in gender-role analysis; her pattern stems from relational hurt, not a gendered rule.` },
    ],
    rationale: `Relational-cultural theory, developed by Jean Baker Miller, Judith Jordan and colleagues, holds that people grow through connection. After hurtful or disconnecting experiences, people may use strategies of disconnection, hiding parts of themselves to stay safe in relationships. This central relational paradox, seeking connection while guarding against it, leads to further isolation, and counseling aims to rebuild the capacity for authentic, mutual connection.`,
    references: [{ source: CO, detail: 'Feminist therapy: relational-cultural theory, strategies of disconnection and the central relational paradox' }],
  },
  {
    id: 'nce-s-cou-384',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'feminist therapy',
    difficulty: 'easy',
    stem: `A 20-year-old college student who survived a sexual assault decides, with her feminist counselor's support, to join a campus group that lobbies for better reporting procedures and prevention programs. Which feminist therapy technique does this BEST illustrate?`,
    options: [
      { id: 'a', text: `Bibliotherapy`, isCorrect: false, rationale: `Bibliotherapy uses books and other media to inform clients, not involvement in advocacy work.` },
      { id: 'b', text: `Social action`, isCorrect: true, rationale: `Feminist counselors may encourage clients to take part in activities that work to change oppressive conditions.` },
      { id: 'c', text: `Reframing`, isCorrect: false, rationale: `Reframing changes how a problem is understood, but here the client is taking action in her community.` },
      { id: 'd', text: `Self-disclosure`, isCorrect: false, rationale: `Self-disclosure is the counselor sharing personal experience, not the client joining an advocacy group.` },
    ],
    rationale: `Feminist therapy holds that the personal is political and is committed to social change, not only individual adjustment. Social action, such as volunteering at a crisis center or lobbying for policy change, can empower clients and help them see their experiences in a social context. The counselor supports, but does not require, such involvement.`,
    references: [{ source: CO, detail: 'Feminist therapy: techniques and strategies (social action)' }],
  },

  // ── MOTIVATIONAL INTERVIEWING ────────────────────────────────────────────
  {
    id: 'nce-s-cou-385',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: `A 52-year-old man with diabetes says he is unsure about changing his diet. The new counselor quickly lists the risks of high blood sugar and urges him to start a meal plan, and the client begins arguing for why change is not realistic. In motivational interviewing terms, what has the counselor done?`,
    options: [
      { id: 'a', text: `Developed discrepancy between his values and his current diet`, isCorrect: false, rationale: `Developing discrepancy evokes the client's own values; the counselor here is supplying arguments.` },
      { id: 'b', text: `Acted on the righting reflex, which drew out more sustain talk`, isCorrect: true, rationale: `The urge to fix the problem and argue for change led the ambivalent client to voice the other side.` },
      { id: 'c', text: `Rolled with resistance by allowing him to argue against change`, isCorrect: false, rationale: `Rolling with discord means avoiding argument; the counselor provoked it instead.` },
      { id: 'd', text: `Moved properly into the planning process after the focus was set`, isCorrect: false, rationale: `Planning comes after change talk and readiness emerge, which has not happened yet.` },
    ],
    rationale: `Miller and Rollnick describe the righting reflex as the helper's natural urge to set things right by advising, warning or persuading. With an ambivalent client, arguing for change tends to prompt the client to argue for the other side, producing sustain talk. MI asks the counselor to resist this reflex and instead evoke the client's own reasons for change.`,
    references: [{ source: MR, detail: 'The righting reflex and ambivalence; sustain talk elicited by persuasion' }],
  },
  {
    id: 'nce-s-cou-386',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'hard',
    stem: `A 30-year-old client says, "My drinking is fine. I don't see why everyone is making such a fuss about it." The counselor replies in a calm, sincere tone, "So there's really nothing about your drinking that concerns you at all." Which MI response is this?`,
    options: [
      { id: 'a', text: `Amplified reflection`, isCorrect: true, rationale: `It restates the client's sustain talk in a slightly stronger form, which often prompts the client to voice the other side.` },
      { id: 'b', text: `Double-sided reflection`, isCorrect: false, rationale: `A double-sided reflection names both sides of ambivalence; this reply names only one side.` },
      { id: 'c', text: `Reframing the meaning`, isCorrect: false, rationale: `Reframing offers a new meaning for what the client said; this reply overstates his own meaning.` },
      { id: 'd', text: `Emphasizing autonomy`, isCorrect: false, rationale: `Emphasizing autonomy affirms the client's right to choose; this reply does not address choice.` },
    ],
    rationale: `An amplified reflection reflects the client's statement back in a somewhat exaggerated form. Said without sarcasm, it often leads the client to back away from the extreme and voice some concern, which is change talk. Tone matters: sarcasm turns an amplified reflection into a confrontation that increases discord.`,
    references: [{ source: MR, detail: 'Responding to sustain talk and discord: amplified reflection' }],
  },

  // ── DIALECTICAL BEHAVIOR THERAPY ─────────────────────────────────────────
  {
    id: 'nce-s-cou-387',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'medium',
    stem: `A client in a DBT skills group often agrees to cover coworkers' shifts, apologizes repeatedly and shades the truth so others won't be upset, then feels ashamed afterward. Her main goal is to respect herself after these talks. Which interpersonal effectiveness skill fits this goal BEST?`,
    options: [
      { id: 'a', text: `GIVE (gentle, interested, validate, easy manner)`, isCorrect: false, rationale: `GIVE targets relationship effectiveness, keeping the relationship strong, not self-respect.` },
      { id: 'b', text: `DEAR MAN (describe, express, assert, reinforce)`, isCorrect: false, rationale: `DEAR MAN targets objectives effectiveness, getting what one asks for, not keeping self-respect.` },
      { id: 'c', text: `PLEASE (physical illness, eating, drugs, sleep, exercise)`, isCorrect: false, rationale: `PLEASE is an emotion regulation skill for reducing vulnerability, not interpersonal effectiveness.` },
      { id: 'd', text: `FAST (fair, no apologies, stick to values, truthful)`, isCorrect: true, rationale: `FAST targets self-respect effectiveness: being fair, not over-apologizing, sticking to values and being truthful.` },
    ],
    rationale: `DBT interpersonal effectiveness has three sets of skills tied to three goals. DEAR MAN serves objectives effectiveness, GIVE serves relationship effectiveness and FAST serves self-respect effectiveness. A client who over-apologizes and shades the truth and then feels ashamed would benefit most from FAST.`,
    references: [{ source: LN, detail: 'Interpersonal effectiveness: FAST skills for self-respect effectiveness' }],
  },
  {
    id: 'nce-s-cou-388',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'dialectical behavior therapy',
    difficulty: 'medium',
    stem: `In a comprehensive DBT program, individual therapists and skills trainers meet weekly as a consultation team, where they discuss their own frustration and burnout and help one another stay effective with high-risk clients. Which function of comprehensive DBT does this team MAINLY serve?`,
    options: [
      { id: 'a', text: `Enhancing clients' capabilities through skills training`, isCorrect: false, rationale: `Building client skills is the main function of skills training groups, not the consultation team.` },
      { id: 'b', text: `Generalizing skills into the client's daily environment`, isCorrect: false, rationale: `Generalization is mainly served by between-session phone coaching and practice.` },
      { id: 'c', text: `Enhancing therapists' capabilities and motivation`, isCorrect: true, rationale: `The consultation team serves as "therapy for the therapists," supporting skill, motivation and adherence.` },
      { id: 'd', text: `Structuring the environment through case management`, isCorrect: false, rationale: `Structuring the environment involves arranging the treatment and home settings, not the team's mutual support.` },
    ],
    rationale: `Comprehensive DBT addresses five functions: enhancing client capabilities, improving client motivation, ensuring generalization, structuring the environment and enhancing therapist capabilities and motivation. The consultation team serves the last function. Treating chronically suicidal clients is demanding, so the team supports therapists so they can keep delivering the treatment well.`,
    references: [{ source: LN, detail: 'Functions and modes of comprehensive DBT: therapist consultation team' }],
  },

  // ── FAMILY SYSTEMS THEORIES (BOWEN, STRUCTURAL, STRATEGIC) ───────────────
  {
    id: 'nce-s-cou-389',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: `During a tense holiday visit, a 38-year-old woman stays calm as her parents argue, states her own view of a family decision without attacking anyone and remains warmly connected to both of them. A Bowenian counselor would see this as evidence of what?`,
    options: [
      { id: 'a', text: `A high level of differentiation of self`, isCorrect: true, rationale: `Differentiation is the ability to keep thinking and feeling distinct and hold one's own position while staying connected.` },
      { id: 'b', text: `An emotional cutoff from her family`, isCorrect: false, rationale: `Cutoff manages fusion by distancing or ending contact; she stays warmly connected.` },
      { id: 'c', text: `A rigid boundary around her subsystem`, isCorrect: false, rationale: `Rigid boundaries are a structural concept describing disengagement, not her calm self-definition.` },
      { id: 'd', text: `Emotional fusion with both her parents`, isCorrect: false, rationale: `Fusion would show as being swept into the conflict or reacting automatically, which she avoids.` },
    ],
    rationale: `Bowen's central concept, differentiation of self, refers to the ability to separate one's intellectual and emotional functioning and to hold an "I-position" while remaining in contact with others. Well-differentiated people can stay calm and thoughtful amid family anxiety without either fusing with others or cutting them off. Raising differentiation is the main goal of Bowenian therapy.`,
    references: [{ source: GO, detail: 'Bowen family systems theory: differentiation of self' }],
  },
  {
    id: 'nce-s-cou-390',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'easy',
    stem: `A Bowenian counselor explains that when spouses who are poorly differentiated face chronic anxiety, the fusion between them tends to show up in a few predictable ways: open marital conflict, illness or dysfunction in one spouse, impairment in a child, or emotional distance. Which Bowen concept describes these patterns?`,
    options: [
      { id: 'a', text: `Emotional cutoff`, isCorrect: false, rationale: `Emotional cutoff is reducing or ending contact with the family of origin to manage fusion, not the set of patterns within the nuclear family.` },
      { id: 'b', text: `Nuclear family emotional process`, isCorrect: true, rationale: `This concept names the patterns through which a couple's unresolved fusion and anxiety are expressed in the nuclear family.` },
      { id: 'c', text: `Societal emotional process`, isCorrect: false, rationale: `Societal emotional process extends Bowen's ideas to how anxiety and regression operate in society as a whole.` },
      { id: 'd', text: `Sibling position`, isCorrect: false, rationale: `Sibling position, drawn from Toman, links birth order to characteristic roles, not to how couples handle fusion.` },
    ],
    rationale: `Bowen described the nuclear family emotional process (originally the nuclear family emotional system) as the ways a family manages the anxiety and undifferentiation that spouses bring from their families of origin. The common patterns are marital conflict, dysfunction in one spouse, projection of the problem onto one or more children, and emotional distance. The lower the spouses' differentiation, the more intensely these patterns appear.`,
    references: [{ source: GO, detail: 'Bowen family systems theory: nuclear family emotional process (system)' }],
  },
];
