// tools/nce/seed/counseling-4.js
// NCE seed — Counseling Skills and Interventions, batch 2: theories not yet
// covered (strategic/MRI, Satir, Whitaker, Jung, Kohut, TA, multimodal,
// Meichenbaum, Bandura, Skinner, classical conditioning, ACT, MBCT, Glasser,
// brief psychodynamic), core microskills and multicultural frameworks, and
// crisis/trauma skills (PFA, TF-CBT, vicarious trauma, grounding, EMDR).
module.exports = [
  // ------------------------------------------------------- family systems
  {
    id: 'nce-s-cou-091',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: 'A strategic therapist tells a client with chronic insomnia that on any night he is still awake at midnight, he must get up and wax the kitchen floor until morning. The task is deliberately designed to be more unpleasant than the symptom itself. Which intervention and originator does this illustrate?',
    options: [
      { id: 'a', text: 'Ordeal therapy, associated with Jay Haley', isCorrect: true, rationale: 'Haley\'s ordeal therapy assigns a task more burdensome than the symptom, so giving up the symptom becomes the easier choice.' },
      { id: 'b', text: 'Unbalancing, associated with Salvador Minuchin', isCorrect: false, rationale: 'Unbalancing is a structural technique in which the therapist temporarily sides with one family member to shift the hierarchy.' },
      { id: 'c', text: 'Paradoxical intention, from Viktor Frankl', isCorrect: false, rationale: 'Frankl\'s paradoxical intention would ask the client to try to stay awake; it does not attach an aversive, effortful task to the symptom.' },
      { id: 'd', text: 'Detriangulation, associated with Murray Bowen', isCorrect: false, rationale: 'Detriangulation is a Bowenian process of removing oneself from a three-person emotional triangle, unrelated to symptom tasks.' },
    ],
    rationale: 'Jay Haley described ordeal therapy as a strategic directive in which the client must perform an ordeal, ideally one that is good for the person (exercise, chores), every time the symptom occurs. Because the ordeal costs more than the symptom, the client gives up the symptom. It reflects strategic therapy\'s focus on directives and on changing behavior rather than producing insight.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Strategic family therapy: Haley, directives and ordeals' }],
  },
  {
    id: 'nce-s-cou-092',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'hard',
    stem: 'A brief therapy team trained at the Mental Research Institute (MRI) in Palo Alto notices that a mother\'s repeated lectures to her withdrawn son lead him to withdraw further, which prompts more lectures. In the MRI model, what is the PRIMARY target of intervention?',
    options: [
      { id: 'a', text: 'The son\'s unresolved early childhood conflicts', isCorrect: false, rationale: 'MRI brief therapy deliberately avoids historical, insight-oriented exploration of early conflicts.' },
      { id: 'b', text: 'The family\'s level of differentiation of self', isCorrect: false, rationale: 'Differentiation of self is the central construct of Bowen family systems theory, not the MRI model.' },
      { id: 'c', text: 'The attempted solution maintaining the problem', isCorrect: true, rationale: 'The MRI team holds that well-meant attempted solutions (here, lecturing) keep the problem going, so interrupting them is the target.' },
      { id: 'd', text: 'The hierarchy and boundaries between subsystems', isCorrect: false, rationale: 'Restructuring hierarchy and subsystem boundaries is the focus of Minuchin\'s structural family therapy.' },
    ],
    rationale: 'In MRI brief therapy (Watzlawick, Weakland, Fisch), problems persist because of the very solutions people repeatedly apply to them. "More of the same" produces only first-order change within the system\'s existing rules; the therapist aims for second-order change by blocking or reversing the attempted solution, often through reframing or paradoxical directives.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Strategic family therapy: MRI brief therapy, attempted solutions, first- and second-order change' }],
  },
  {
    id: 'nce-s-cou-093',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'easy',
    stem: 'During a family session about a teenager\'s failing grades, her father answers every emotional comment with charts, rules and calm, logical analysis, showing little feeling for himself or for others. Which Satir communication stance is he displaying?',
    options: [
      { id: 'a', text: 'Blaming', isCorrect: false, rationale: 'The blamer finds fault and attacks others to protect the self, disregarding others\' feelings rather than all feelings.' },
      { id: 'b', text: 'Placating', isCorrect: false, rationale: 'The placater pleases and appeases others at the expense of the self; the father is not deferring to anyone.' },
      { id: 'c', text: 'Irrelevant', isCorrect: false, rationale: 'The irrelevant (distracting) stance changes the subject or clowns around, ignoring self, others and context.' },
      { id: 'd', text: 'Super-reasonable', isCorrect: true, rationale: 'The super-reasonable (computer) stance relies on cool logic and data while discounting the feelings of self and others.' },
    ],
    rationale: 'Virginia Satir described four incongruent survival stances people adopt under stress: placating, blaming, super-reasonable and irrelevant. Her goal was congruent communication, in which words, feelings and body language match and self, other and context are all honored.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Experiential family therapy: Satir communication stances' }],
  },
  {
    id: 'nce-s-cou-094',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: 'A family therapist insists early on that he decides who attends and how sessions are run, but then leaves it to the family to take responsibility for what will change. He relies on spontaneity, playfulness and co-therapy, and calls these struggles the "battle for structure" and the "battle for initiative." Which approach is this?',
    options: [
      { id: 'a', text: 'Symbolic-experiential (Whitaker)', isCorrect: true, rationale: 'Carl Whitaker described the battle for structure and the battle for initiative and emphasized the therapist\'s spontaneous, often absurd use of self.' },
      { id: 'b', text: 'Structural therapy (Minuchin)', isCorrect: false, rationale: 'Minuchin focused on joining, mapping and restructuring subsystems and boundaries rather than these two "battles."' },
      { id: 'c', text: 'Bowen systems therapy (Bowen)', isCorrect: false, rationale: 'Bowen\'s approach is calm, coaching and theory-driven, aimed at differentiation, not playful or provocative.' },
      { id: 'd', text: 'Validation model (Satir)', isCorrect: false, rationale: 'Satir was experiential too, but her model centers on self-esteem, communication stances and congruence.' },
    ],
    rationale: 'Carl Whitaker\'s symbolic-experiential family therapy values growth and creativity over technique. The therapist wins the battle for structure (control over the conditions of therapy) but must lose the battle for initiative, so that the family owns its decisions about change. Whitaker often worked with a co-therapist and used humor and "craziness" to unsettle rigid patterns.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Experiential family therapy: Whitaker, symbolic-experiential approach' }],
  },
  // ------------------------------------------------- psychodynamic family
  {
    id: 'nce-s-cou-095',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'medium',
    stem: 'A man who prides himself on generosity becomes intensely angry at a coworker he calls "greedy and selfish," although his friends say he can be quite stingy himself. A Jungian counselor would MOST likely view his reaction as a projection of which archetype?',
    options: [
      { id: 'a', text: 'The persona', isCorrect: false, rationale: 'The persona is the public mask a person presents; his generous image is persona, but what he projects is the disowned side.' },
      { id: 'b', text: 'The shadow', isCorrect: true, rationale: 'The shadow holds the traits a person rejects in himself; they are often projected onto others and met with strong emotion.' },
      { id: 'c', text: 'The anima', isCorrect: false, rationale: 'The anima is the feminine side of a man\'s psyche, not the store of disowned negative traits.' },
      { id: 'd', text: 'The Self', isCorrect: false, rationale: 'The Self is the archetype of wholeness and integration toward which individuation moves.' },
    ],
    rationale: 'Carl Jung proposed a collective unconscious containing archetypes shared across humanity, including the persona, shadow, anima/animus and Self. Disowned qualities in the shadow are commonly projected onto others, and a strong emotional charge toward someone is a clue. Jungian work aims at individuation, partly by recognizing and integrating the shadow.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: Jung\'s analytical psychology, archetypes and the shadow' }],
  },
  {
    id: 'nce-s-cou-096',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'hard',
    stem: 'A client raised by emotionally unavailable parents eagerly reports each accomplishment to the counselor, seems to need admiring responses, and feels deflated and empty when the counselor responds neutrally. In Kohut\'s self psychology, the client is MOST likely seeking which kind of response?',
    options: [
      { id: 'a', text: 'An idealizing selfobject response', isCorrect: false, rationale: 'Idealizing needs involve merging with a calm, admired figure; the client wants to be admired, not to admire.' },
      { id: 'b', text: 'A twinship selfobject response', isCorrect: false, rationale: 'Twinship (alter ego) needs involve feeling essentially alike with another person, not being admired.' },
      { id: 'c', text: 'A mirroring selfobject response', isCorrect: true, rationale: 'Mirroring needs are met by others who reflect back and admire the person\'s worth and achievements.' },
      { id: 'd', text: 'Splitting of good and bad objects', isCorrect: false, rationale: 'Splitting is an object relations concept (Klein, Kernberg) about keeping all-good and all-bad images apart, not a need for admiration.' },
    ],
    rationale: 'Heinz Kohut argued that a cohesive self develops when caregivers serve as selfobjects meeting three needs: mirroring (being admired), idealizing (merging with a strong, calm figure) and twinship (feeling alike). Unmet mirroring needs can leave adults hungry for admiration and fragile in self-esteem. Kohut\'s self psychology grew out of, and is often grouped with, object relations theory.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: contemporary trends, self psychology and object relations' }],
  },
  {
    id: 'nce-s-cou-097',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'A counseling student is comparing Freud\'s psychosexual theory with Erikson\'s psychosocial theory. Which statement MOST accurately describes a key difference between them?',
    options: [
      { id: 'a', text: 'Erikson\'s stages extend across the entire life span', isCorrect: true, rationale: 'Erikson\'s eight stages run from infancy through late adulthood, whereas Freud\'s stages end with the genital stage at puberty.' },
      { id: 'b', text: 'Erikson made sexual drives the core of every stage', isCorrect: false, rationale: 'Erikson shifted the emphasis from sexual drives to social and cultural tasks and the growth of identity.' },
      { id: 'c', text: 'Freud proposed eight stages ending in late adulthood', isCorrect: false, rationale: 'Freud described five psychosexual stages; the eight life-span stages belong to Erikson.' },
      { id: 'd', text: 'Freud stressed social crises more than instinctual drives', isCorrect: false, rationale: 'This reverses the theories; Freud stressed instinctual drives, and Erikson stressed psychosocial crises.' },
    ],
    rationale: 'Freud\'s five psychosexual stages (oral, anal, phallic, latency, genital) center on instinctual drives and end at adolescence. Erikson kept a stage framework but emphasized ego development, social relationships and culture, and he extended development across the whole life span with eight psychosocial crises from trust vs. mistrust to integrity vs. despair.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Psychoanalytic perspective: Freud\'s psychosexual and Erikson\'s psychosocial theories' }],
  },
  {
    id: 'nce-s-cou-098',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'easy',
    stem: 'Describing a mistake she made at work, a client says aloud to herself, in a scolding tone that echoes her mother, "You should have known better. How careless can you be?" In Eric Berne\'s transactional analysis, which ego state is she speaking from?',
    options: [
      { id: 'a', text: 'Adult', isCorrect: false, rationale: 'The Adult ego state processes information objectively in the here and now; it does not scold.' },
      { id: 'b', text: 'Critical Parent', isCorrect: true, rationale: 'The Critical (Controlling) Parent holds the rules, judgments and criticisms absorbed from caregivers.' },
      { id: 'c', text: 'Adapted Child', isCorrect: false, rationale: 'The Adapted Child complies with or rebels against parental messages; it receives the scolding rather than delivering it.' },
      { id: 'd', text: 'Free Child', isCorrect: false, rationale: 'The Free (Natural) Child is spontaneous, playful and expressive, not judgmental.' },
    ],
    rationale: 'Berne\'s transactional analysis describes three ego states: Parent (Critical and Nurturing), Adult and Child (Free and Adapted). Self-critical messages copied from caregivers come from the Critical Parent. TA also analyzes transactions between ego states, psychological games with hidden payoffs, and life scripts formed in childhood.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Transactional analysis: ego states, transactions, games and life scripts' }],
  },
  // ----------------------------------------------- behavioral and cognitive
  {
    id: 'nce-s-cou-099',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: 'Arnold Lazarus\'s multimodal therapy assesses clients across seven modalities summarized by the acronym BASIC I.D. What do the final letters "I.D." represent?',
    options: [
      { id: 'a', text: 'Insight and defense mechanisms', isCorrect: false, rationale: 'Insight and defenses are psychodynamic concepts and are not BASIC I.D. modalities.' },
      { id: 'b', text: 'Identity and dream content', isCorrect: false, rationale: 'Neither identity nor dreams is one of Lazarus\'s seven modalities.' },
      { id: 'c', text: 'Interpersonal and drugs/biology', isCorrect: true, rationale: 'The last two modalities are Interpersonal relationships and Drugs/biological functions.' },
      { id: 'd', text: 'Imagery and developmental history', isCorrect: false, rationale: 'Imagery is the earlier "I" in BASIC; developmental history is not a modality.' },
    ],
    rationale: 'Lazarus\'s technically eclectic multimodal therapy assesses Behavior, Affect, Sensation, Imagery, Cognition, Interpersonal relationships and Drugs/biology. Counselors then choose techniques from any orientation to address problems in each modality, guided by research on what works rather than by a single theory.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: Lazarus\'s multimodal therapy and the BASIC I.D.' }],
  },
  {
    id: 'nce-s-cou-100',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: 'A counselor prepares a newly hired paramedic for high-stress calls in three phases: first building an understanding of how stress works, then learning and rehearsing coping skills such as coping self-statements and relaxation, and finally applying them under graded, increasingly realistic stressors. Which approach is the counselor using?',
    options: [
      { id: 'a', text: 'Systematic desensitization', isCorrect: false, rationale: 'Wolpe\'s systematic desensitization pairs relaxation with an imagined fear hierarchy; it lacks the conceptualization and coping-skills phases.' },
      { id: 'b', text: 'Rational emotive imagery', isCorrect: false, rationale: 'Rational emotive imagery is an REBT technique for changing emotions by imagining a feared event while feeling a healthier emotion.' },
      { id: 'c', text: 'Cognitive processing therapy', isCorrect: false, rationale: 'Cognitive processing therapy treats PTSD by challenging stuck points about a past trauma, not by inoculating against future stress.' },
      { id: 'd', text: 'Stress inoculation training', isCorrect: true, rationale: 'Meichenbaum\'s stress inoculation training moves through conceptualization, skills acquisition and rehearsal, and application and follow-through.' },
    ],
    rationale: 'Donald Meichenbaum\'s stress inoculation training "inoculates" clients against stress by exposing them to manageable doses after they have learned coping skills. Its three phases are conceptualization, skills acquisition and rehearsal, and application and follow-through. It builds on his self-instructional training, which teaches clients to replace self-defeating inner speech with coping self-statements.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Cognitive behavior therapy: Meichenbaum\'s cognitive behavior modification and stress inoculation training' }],
  },
  {
    id: 'nce-s-cou-101',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: 'A 46-year-old client returning to the workforce doubts she can learn the spreadsheet software her new job requires. According to Bandura, which source of self-efficacy is generally the MOST powerful way to strengthen her belief that she can succeed?',
    options: [
      { id: 'a', text: 'Watching a peer of similar age master the software', isCorrect: false, rationale: 'Vicarious experience (modeling) raises self-efficacy, especially with similar models, but less strongly than one\'s own success.' },
      { id: 'b', text: 'Encouragement from her counselor that she can do it', isCorrect: false, rationale: 'Verbal persuasion helps but is weaker and easily undone by later failure.' },
      { id: 'c', text: 'Succeeding herself at small, graded spreadsheet tasks', isCorrect: true, rationale: 'Mastery (performance) experiences are the most powerful source of self-efficacy because they provide direct evidence of capability.' },
      { id: 'd', text: 'Feeling physically calmer when she sits down to work on it', isCorrect: false, rationale: 'Physiological and emotional states shape self-efficacy judgments, but they are the least direct of the four sources.' },
    ],
    rationale: 'Albert Bandura identified four sources of self-efficacy: mastery experiences, vicarious experiences (modeling), verbal persuasion, and physiological and emotional states. Mastery experiences are the strongest. Counselors therefore break goals into graded steps the client can succeed at, often after modeling and with encouragement.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: Bandura\'s social learning theory, modeling and self-efficacy' }],
  },
  {
    id: 'nce-s-cou-102',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'easy',
    stem: 'A slot machine pays out after an unpredictable number of plays, averaging about one win every 20 pulls. Which reinforcement schedule is this, and how does it typically affect extinction?',
    options: [
      { id: 'a', text: 'Fixed interval; quick to extinguish once payouts stop', isCorrect: false, rationale: 'A fixed-interval schedule reinforces the first response after a set time; payouts here depend on the number of plays.' },
      { id: 'b', text: 'Variable ratio; highly resistant to extinction', isCorrect: true, rationale: 'Reinforcement after an unpredictable number of responses is a variable-ratio schedule, which produces high, steady responding that is very hard to extinguish.' },
      { id: 'c', text: 'Fixed ratio; very resistant because it is predictable', isCorrect: false, rationale: 'A fixed ratio pays after a set number of responses; its predictability makes it less resistant to extinction than a variable ratio.' },
      { id: 'd', text: 'Variable interval; extinguishes faster than continuous', isCorrect: false, rationale: 'Payouts here depend on responses, not time, and intermittent schedules resist extinction more than continuous reinforcement.' },
    ],
    rationale: 'Skinner\'s intermittent schedules are fixed ratio, variable ratio, fixed interval and variable interval. Variable-ratio reinforcement produces the highest, steadiest response rates and the greatest resistance to extinction, which is why gambling is so persistent. Continuous reinforcement speeds learning but extinguishes fastest.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: operant conditioning and schedules of reinforcement' }],
  },
  {
    id: 'nce-s-cou-103',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: 'After being bitten by a neighbor\'s German shepherd, a 7-year-old now becomes frightened around other large dogs, yet he stays relaxed around small dogs and cats. In classical conditioning terms, his fear of other large dogs and his calm around small dogs reflect, respectively, which two processes?',
    options: [
      { id: 'a', text: 'Spontaneous recovery; stimulus generalization', isCorrect: false, rationale: 'Spontaneous recovery is the return of an extinguished response after a rest period; nothing here was extinguished.' },
      { id: 'b', text: 'Stimulus discrimination; second-order conditioning', isCorrect: false, rationale: 'This reverses the first process, and second-order conditioning pairs a new neutral stimulus with an existing conditioned stimulus.' },
      { id: 'c', text: 'Stimulus generalization; stimulus discrimination', isCorrect: true, rationale: 'Fear spreading to similar stimuli is generalization; responding differently to dissimilar stimuli is discrimination.' },
      { id: 'd', text: 'Higher-order conditioning; response extinction', isCorrect: false, rationale: 'His calm around small dogs is not extinction, since that fear was never conditioned and then weakened.' },
    ],
    rationale: 'In Pavlov\'s model the bite is the unconditioned stimulus, fear the unconditioned response, and the German shepherd becomes a conditioned stimulus. Stimulus generalization occurs when stimuli similar to the conditioned stimulus also elicit the response; stimulus discrimination occurs when the person responds only to stimuli close enough to the original.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: classical conditioning, generalization and discrimination' }],
  },
  {
    id: 'nce-s-cou-104',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'easy',
    stem: 'To teach a 4-year-old with a language delay to say "water," a therapist first reinforces any vocal sound, then only "wa," then "wa-ter," and finally only the complete word. Which behavioral technique is the therapist using?',
    options: [
      { id: 'a', text: 'Chaining', isCorrect: false, rationale: 'Chaining links a series of already-learned behaviors into a sequence, such as the steps of handwashing.' },
      { id: 'b', text: 'Token economy', isCorrect: false, rationale: 'A token economy delivers conditioned reinforcers (tokens) that are later exchanged for backup rewards; it is not defined by successive approximations.' },
      { id: 'c', text: 'Premack principle', isCorrect: false, rationale: 'The Premack principle uses a high-frequency activity to reinforce a lower-frequency one.' },
      { id: 'd', text: 'Shaping', isCorrect: true, rationale: 'Shaping reinforces successive approximations of a target behavior, raising the criterion step by step.' },
    ],
    rationale: 'Shaping builds a new behavior by reinforcing closer and closer approximations to the goal while no longer reinforcing earlier, cruder forms. It is often combined with other operant tools, such as token economies, in which tokens act as generalized conditioned reinforcers exchanged later for backup reinforcers.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: operant techniques, shaping and token economies' }],
  },
  {
    id: 'nce-s-cou-105',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: 'A client keeps telling herself, "I\'m a failure." Rather than disputing the thought, her counselor asks her to restate it as "I\'m having the thought that I\'m a failure" and to notice the words without arguing with them. Which acceptance and commitment therapy (ACT) process is the counselor targeting?',
    options: [
      { id: 'a', text: 'Cognitive restructuring', isCorrect: false, rationale: 'Cognitive restructuring is a traditional CBT strategy that tests and replaces the thought; ACT changes the client\'s relationship to the thought instead.' },
      { id: 'b', text: 'Cognitive defusion', isCorrect: true, rationale: 'Defusion helps clients see thoughts as passing words and images rather than literal truths, loosening their grip on behavior.' },
      { id: 'c', text: 'Committed action', isCorrect: false, rationale: 'Committed action is taking concrete steps in line with chosen values, not changing how one relates to a thought.' },
      { id: 'd', text: 'Values clarification', isCorrect: false, rationale: 'Values work identifies what matters most to the client; this exercise targets her relationship to a thought.' },
    ],
    rationale: 'Steven Hayes\'s ACT targets psychological flexibility through six hexaflex processes: acceptance, cognitive defusion, contact with the present moment, self-as-context, values and committed action. Defusion techniques, such as adding "I\'m having the thought that," create distance from thoughts without trying to change their content.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Third-wave behavior therapies: acceptance and commitment therapy, cognitive defusion' }],
  },
  {
    id: 'nce-s-cou-106',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'easy',
    stem: 'Mindfulness-based cognitive therapy (MBCT), developed by Segal, Williams and Teasdale, was designed primarily for which purpose?',
    options: [
      { id: 'a', text: 'Preventing relapse in people with recurrent depression', isCorrect: true, rationale: 'MBCT was built to reduce relapse in people who have had repeated major depressive episodes and are currently in remission.' },
      { id: 'b', text: 'Treating acute mania during inpatient hospitalization', isCorrect: false, rationale: 'MBCT is a group program for people who are currently well, not an acute treatment for mania.' },
      { id: 'c', text: 'Reducing self-harm in clients with borderline traits', isCorrect: false, rationale: 'This describes dialectical behavior therapy, which also uses mindfulness but was developed by Linehan.' },
      { id: 'd', text: 'Replacing exposure as the core treatment for specific phobias', isCorrect: false, rationale: 'Exposure remains the core treatment for specific phobias; MBCT was not developed for them.' },
    ],
    rationale: 'MBCT combines mindfulness practice, adapted from Kabat-Zinn\'s MBSR, with cognitive therapy in an 8-week group format. It teaches people with recurrent depression to notice early negative thinking and relate to it from a decentered stance, interrupting the rumination that can trigger relapse. Its strongest evidence is for people with three or more prior episodes.',
    references: [{ source: 'NICE guidelines', detail: 'Depression in adults (NG222): relapse prevention with mindfulness-based cognitive therapy' }],
  },
  {
    id: 'nce-s-cou-107',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'easy',
    stem: 'In William Glasser\'s choice theory, all behavior is an attempt to satisfy five basic needs. Which list names them?',
    options: [
      { id: 'a', text: 'Safety, esteem, belonging, purpose, and self-actualization', isCorrect: false, rationale: 'This resembles Maslow\'s hierarchy of needs, not Glasser\'s five basic needs.' },
      { id: 'b', text: 'Survival, attachment, mastery, autonomy, and meaning', isCorrect: false, rationale: 'This mixes concepts from attachment and self-determination theories; Glasser\'s list includes power, freedom and fun.' },
      { id: 'c', text: 'Love, work, play, spirituality, and self-direction', isCorrect: false, rationale: 'These echo Adlerian life tasks and wellness models rather than choice theory.' },
      { id: 'd', text: 'Survival, love and belonging, power, freedom, and fun', isCorrect: true, rationale: 'Glasser named survival, love and belonging, power (achievement), freedom and fun as the five basic needs.' },
    ],
    rationale: 'Choice theory holds that people choose behaviors to meet five genetically based needs: survival, love and belonging, power or achievement, freedom, and fun. Glasser saw love and belonging as central. Reality therapy helps clients evaluate whether what they are doing is meeting these needs and plan more effective choices.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Reality therapy: choice theory and the five basic needs' }],
  },
  {
    id: 'nce-s-cou-108',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'hard',
    stem: 'A counselor uses a time-limited psychodynamic approach (such as those of Mann or Strupp and Binder) with a client who has recurring conflicts with authority figures. How does this approach MOST differ from traditional long-term psychoanalysis?',
    options: [
      { id: 'a', text: 'Transference is avoided so the work stays short-term', isCorrect: false, rationale: 'Brief dynamic therapists actively use transference, especially as it relates to the focal pattern.' },
      { id: 'b', text: 'Free association becomes the counselor\'s main tool', isCorrect: false, rationale: 'Unstructured free association is typical of classical analysis; brief therapy is more focused and active.' },
      { id: 'c', text: 'Work centers on one focal conflict or relational pattern', isCorrect: true, rationale: 'Time-limited dynamic therapies select a single central issue or cyclical maladaptive pattern and keep the work on it.' },
      { id: 'd', text: 'The ending date is left open until the client feels ready', isCorrect: false, rationale: 'A set time limit, often agreed at the start (Mann used 12 sessions), is a defining feature, and the ending itself is used therapeutically.' },
    ],
    rationale: 'Brief psychodynamic therapies keep psychoanalytic ideas such as transference and unconscious conflict but limit the number of sessions, have the counselor take a more active role, and select a circumscribed focus, such as Mann\'s central issue or Strupp and Binder\'s cyclical maladaptive pattern. The fixed ending is used to work through issues of separation and loss.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: brief psychodynamic therapy and time-limited dynamic psychotherapy' }],
  },
  // ------------------------------------------------------------------ skills
  {
    id: 'nce-s-cou-109',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'easy',
    stem: 'A reluctant 16-year-old says only that last night "was bad" because of an argument with his mother. The counselor wants to invite him to tell the story in his own words. Which counselor question BEST serves that goal?',
    options: [
      { id: 'a', text: 'Were you upset by the argument?', isCorrect: false, rationale: 'A closed question invites a yes or no and limits how much he says.' },
      { id: 'b', text: 'Why did you yell at her?', isCorrect: false, rationale: '"Why" questions can sound accusatory and prompt defensiveness; it also assumes he yelled.' },
      { id: 'c', text: 'Was it about curfew or grades?', isCorrect: false, rationale: 'An either/or question is closed and imposes the counselor\'s guesses about the topic.' },
      { id: 'd', text: 'What happened during the argument?', isCorrect: true, rationale: 'An open "what" question invites him to describe events in his own words and at his own depth.' },
    ],
    rationale: 'Open questions, often starting with "what" or "how," encourage clients to elaborate and lead the content. Closed questions are useful for specific facts but narrow the conversation, and "why" questions often provoke defensiveness. Once a client is talking, minimal encouragers such as "mm-hm" help keep the story going.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: open and closed questions' }],
  },
  {
    id: 'nce-s-cou-110',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'easy',
    stem: 'A grieving client finishes describing her mother\'s final days in hospice, then stops speaking and looks down with tears in her eyes. What is the MOST helpful counselor response in that moment?',
    options: [
      { id: 'a', text: 'Allow a silence so she can stay with what she feels', isCorrect: true, rationale: 'A respectful, attentive silence gives her room to feel and reflect and signals that the counselor can stay present with her pain.' },
      { id: 'b', text: 'Ask a new question so the pause does not grow awkward', isCorrect: false, rationale: 'Filling the pause usually serves the counselor\'s discomfort and pulls her away from her feelings.' },
      { id: 'c', text: 'Offer reassurance that her mother is no longer suffering', isCorrect: false, rationale: 'Premature reassurance can minimize her grief and close down the emotion she is experiencing.' },
      { id: 'd', text: 'Summarize the session so far and move to coping planning', isCorrect: false, rationale: 'Shifting to planning at a moment of deep feeling is mistimed and can feel dismissive.' },
    ],
    rationale: 'Purposeful silence is an attending skill. It allows clients to experience emotion, gather thoughts and decide what to say next, and it communicates acceptance. Beginning counselors often rush to fill silences; the skill lies in reading whether a silence is productive (reflective) or a sign the client is stuck or confused.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: use of silence and attending' }],
  },
  {
    id: 'nce-s-cou-111',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: 'A client in early recovery asks his counselor, "Have you ever struggled with addiction yourself?" The counselor has been in recovery for many years. Which guideline BEST governs whether and how she self-discloses?',
    options: [
      { id: 'a', text: 'Share her own recovery story in full detail, since shared experience builds credibility', isCorrect: false, rationale: 'Lengthy disclosure shifts the focus to the counselor and can burden the client, whatever its intent.' },
      { id: 'b', text: 'Disclose only if it serves the client, keep it brief, and return the focus to him', isCorrect: true, rationale: 'Helpful self-disclosure is purposeful, brief, relevant to the client\'s goals, and followed by a quick return of the focus to the client.' },
      { id: 'c', text: 'Decline every personal question, because any disclosure is a boundary violation', isCorrect: false, rationale: 'Self-disclosure is a recognized skill; used sparingly and for the client\'s benefit, it is not a boundary violation.' },
      { id: 'd', text: 'Disclose only after he asks a second time, to confirm that his interest is sincere', isCorrect: false, rationale: 'Making him ask twice is not a recognized guideline; the test is whether disclosure serves his welfare.' },
    ],
    rationale: 'Counselor self-disclosure should be infrequent, brief, relevant and offered for the client\'s benefit rather than the counselor\'s needs. After disclosing, the counselor returns the focus to the client, for example by asking how the disclosure lands. Counselors should consider the client\'s culture, timing and whether the disclosure could blur roles.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: counselor self-disclosure' }],
  },
  {
    id: 'nce-s-cou-112',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'hard',
    stem: 'A father calls his 15-year-old "stubborn," and the counselor replies, "He sounds determined to stand by what he believes." Later, the counselor suggests the son\'s school refusal may be his way of keeping an eye on a parent he worries about. Which statement BEST distinguishes the two techniques?',
    options: [
      { id: 'a', text: 'The first is reframing, which recasts a whole situation; the second is relabeling a single trait', isCorrect: false, rationale: 'This reverses the terms; swapping one adjective is relabeling, and recasting the meaning of a situation is reframing.' },
      { id: 'b', text: 'The first is interpretation of a defense; the second is a paradoxical prescription', isCorrect: false, rationale: 'Neither statement interprets a defense or tells anyone to continue the symptom.' },
      { id: 'c', text: 'Both are confrontations of discrepancies between the family\'s words and actions', isCorrect: false, rationale: 'Confrontation points out a discrepancy; these statements offer new, more positive meanings instead.' },
      { id: 'd', text: 'The first relabels a negative trait; the second reframes what the behavior means', isCorrect: true, rationale: 'Relabeling replaces a negative descriptor with a positive one, while reframing places a behavior in a new context that changes its meaning.' },
    ],
    rationale: 'Both techniques change perception without changing facts. Relabeling attaches a more positive label to a person or trait ("stubborn" becomes "determined"). Reframing offers a different frame for a whole pattern, often giving a symptom a protective or caring function, which can open new options for the family. Reframing is especially associated with strategic and MRI approaches.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Family counseling techniques: reframing and relabeling' }],
    reviewNote: 'Verify the reframing vs. relabeling distinction against the Gladding glossary, since some texts treat relabeling as a subtype of reframing.',
  },
  {
    id: 'nce-s-cou-113',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: 'Pamela Hays\'s ADDRESSING framework helps counselors consider the many cultural influences shaping a client\'s identity. In this acronym, what does the first "D" stand for?',
    options: [
      { id: 'a', text: 'Developmental disabilities', isCorrect: true, rationale: 'The first D is developmental disabilities; the second D is disabilities acquired later in life.' },
      { id: 'b', text: 'Dominant-group status', isCorrect: false, rationale: 'Privilege runs through the whole framework, but dominant-group status is not a letter in the acronym.' },
      { id: 'c', text: 'Diagnostic history', isCorrect: false, rationale: 'Diagnostic history is a clinical, not cultural, factor and is not part of ADDRESSING.' },
      { id: 'd', text: 'Dialect and language', isCorrect: false, rationale: 'Language is considered under national origin and ethnicity; it is not one of the letters.' },
    ],
    rationale: 'ADDRESSING stands for Age and generational influences, Developmental disabilities, Disabilities acquired later in life, Religion and spiritual orientation, Ethnic and racial identity, Socioeconomic status, Sexual orientation, Indigenous heritage, National origin and Gender. Hays designed it to help counselors see clients\' intersecting identities and to examine where the counselor holds privilege.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Multidimensional identity: Hays\'s ADDRESSING framework' }],
    reviewNote: 'Confirm that the cited Sue & Sue edition discusses Hays\'s ADDRESSING framework; if not, cite a text that does.',
  },
  {
    id: 'nce-s-cou-114',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'hard',
    stem: 'After years of being passed over at work despite strong reviews, a client says he has little control over his career because of systemic discrimination, and he places responsibility for his situation on that system rather than on himself. In Derald Wing Sue\'s worldview model, which quadrant BEST fits?',
    options: [
      { id: 'a', text: 'Internal control, internal responsibility', isCorrect: false, rationale: 'IC-IR reflects the mainstream U.S. belief that people control their outcomes and are to blame for failures.' },
      { id: 'b', text: 'External control, external responsibility', isCorrect: true, rationale: 'EC-ER describes someone who sees outcomes as controlled by others and attributes problems to systemic forces such as discrimination.' },
      { id: 'c', text: 'External control, internal responsibility', isCorrect: false, rationale: 'EC-IR describes someone who has little control yet blames himself, often linked to internalized oppression.' },
      { id: 'd', text: 'Internal control, external responsibility', isCorrect: false, rationale: 'IC-ER describes someone who feels able to shape his life while recognizing systemic barriers, not one who feels little control.' },
    ],
    rationale: 'Sue crossed locus of control (internal or external) with locus of responsibility (internal or person-centered vs. external or system-centered) to form four worldviews. Counselors who assume an IC-IR view may misread an EC-ER client as resistant or blaming. Understanding the client\'s worldview, and the real barriers behind it, guides culturally responsive goals such as advocacy.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Worldview: locus of control and locus of responsibility quadrants' }],
  },
  {
    id: 'nce-s-cou-115',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'hard',
    stem: 'At intake, a counselor briefly asks a Latina client whether she minds working with a counselor of a different ethnicity. He never returns to culture, even when she later describes ethnic bias from her supervisor. In Day-Vines and colleagues\' broaching continuum, which style does this MOST reflect?',
    options: [
      { id: 'a', text: 'Avoidant', isCorrect: false, rationale: 'An avoidant counselor does not raise race or culture at all; this counselor did raise it once.' },
      { id: 'b', text: 'Infusing', isCorrect: false, rationale: 'An infusing counselor builds attention to culture and social justice into all of their work, well beyond the session.' },
      { id: 'c', text: 'Isolating', isCorrect: true, rationale: 'An isolating counselor broaches culture in a superficial, one-time way to satisfy an obligation, then drops it.' },
      { id: 'd', text: 'Integrated/congruent', isCorrect: false, rationale: 'An integrated/congruent counselor broaches routinely and links the client\'s cultural experiences to the presenting concerns.' },
    ],
    rationale: 'Broaching is the counselor\'s consistent, open invitation to explore how race, ethnicity and culture bear on the client\'s concerns. Day-Vines and colleagues described a continuum of broaching styles: avoidant, isolating, continuing/incongruent, integrated/congruent and infusing. Raising culture once and never connecting it to the client\'s experience is the isolating style.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Broaching race and culture in counseling: Day-Vines broaching continuum' }],
    reviewNote: 'Verify the broaching style names and order against Day-Vines et al. (2007) and confirm Sue & Sue covers them.',
  },
  // ----------------------------------------------------------- crisis/trauma
  {
    id: 'nce-s-cou-116',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'medium',
    stem: 'A counselor deployed to a family assistance center after a mass shooting will use Psychological First Aid (PFA) as developed by the National Child Traumatic Stress Network and National Center for PTSD. Which practice is NOT one of the PFA core actions?',
    options: [
      { id: 'a', text: 'Linking survivors with needed collaborative services', isCorrect: false, rationale: 'Linkage with collaborative services is one of the eight PFA core actions.' },
      { id: 'b', text: 'Gathering information on current needs and worries', isCorrect: false, rationale: 'Information gathering about current needs and concerns is a PFA core action.' },
      { id: 'c', text: 'Offering information on coping with stress reactions', isCorrect: false, rationale: 'Providing information on coping is a PFA core action.' },
      { id: 'd', text: 'Asking survivors to recount the event in detail', isCorrect: true, rationale: 'PFA does not require survivors to describe the event in detail; pressing for a detailed account can be distressing and resembles debriefing, which PFA avoids.' },
    ],
    rationale: 'PFA\'s eight core actions are contact and engagement, safety and comfort, stabilization, information gathering on current needs and concerns, practical assistance, connection with social supports, information on coping, and linkage with collaborative services. It is evidence-informed, flexible and non-intrusive, and it does not push survivors to retell or process their trauma.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis and disaster counseling: Psychological First Aid core actions' }],
  },
  {
    id: 'nce-s-cou-117',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'medium',
    stem: 'A counselor using trauma-focused cognitive behavioral therapy (TF-CBT) with a 9-year-old has completed psychoeducation and parenting skills, relaxation, affective modulation and cognitive coping. Following the PRACTICE sequence, which component comes NEXT?',
    options: [
      { id: 'a', text: 'In vivo mastery of trauma reminders', isCorrect: false, rationale: 'In vivo mastery follows the trauma narrative and is used only when the child avoids safe reminders.' },
      { id: 'b', text: 'Conjoint child-parent sessions', isCorrect: false, rationale: 'Conjoint sessions, often used to share the narrative with the caregiver, come after the narrative is developed.' },
      { id: 'c', text: 'Enhancing future safety', isCorrect: false, rationale: 'Enhancing safety is the final component of the PRACTICE sequence.' },
      { id: 'd', text: 'Trauma narrative and processing', isCorrect: true, rationale: 'After the stabilization skills, the child gradually develops and processes a narrative of the trauma.' },
    ],
    rationale: 'TF-CBT, developed by Cohen, Mannarino and Deblinger, follows the PRACTICE components: Psychoeducation and Parenting skills, Relaxation, Affective modulation, Cognitive coping, Trauma narrative and processing, In vivo mastery, Conjoint child-parent sessions and Enhancing safety. Coping skills are built first so the child can tolerate the gradual exposure of the trauma narrative.',
    references: [{ source: 'NICE guidelines', detail: 'PTSD (NG116): trauma-focused CBT for children and young people' }],
    reviewNote: 'The PRACTICE order is from Cohen, Mannarino and Deblinger; confirm NICE NG116 is an acceptable citation or swap to a source that describes the model.',
  },
  {
    id: 'nce-s-cou-118',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'medium',
    stem: 'After a year at a child advocacy center, a counselor notices lasting changes in her own beliefs: she now sees the world as unsafe, distrusts adults around her own children, and has intrusive images drawn from clients\' accounts. Which term BEST describes her experience?',
    options: [
      { id: 'a', text: 'Burnout', isCorrect: false, rationale: 'Burnout is exhaustion, cynicism and reduced effectiveness from workload and work conditions; it need not involve trauma-related changes in beliefs.' },
      { id: 'b', text: 'Vicarious trauma', isCorrect: true, rationale: 'Vicarious trauma is a cumulative change in the helper\'s inner world, such as beliefs about safety and trust, from empathic engagement with clients\' trauma.' },
      { id: 'c', text: 'Compassion satisfaction', isCorrect: false, rationale: 'Compassion satisfaction is the positive fulfillment helpers draw from their work, the opposite of her experience.' },
      { id: 'd', text: 'Countertransference', isCorrect: false, rationale: 'Countertransference is the counselor\'s reaction to a particular client rooted in her own history, not a cumulative shift in worldview.' },
    ],
    rationale: 'Vicarious trauma (McCann and Pearlman) is a lasting shift in a helper\'s beliefs about safety, trust and control that results from repeated exposure to clients\' trauma. Compassion fatigue (Figley) emphasizes the emotional cost of caring, including secondary traumatic stress, while burnout stems from work conditions. Remedies include supervision, caseload balance, peer support and personal self-care.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counselor wellness: burnout, compassion fatigue and vicarious trauma' }, { source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-cou-119',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'easy',
    stem: 'While talking about an assault, a client begins to dissociate: she stares blankly, speaks in a monotone, and says the room feels "far away." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Guide her to name things she can see and feel her feet on the floor', isCorrect: true, rationale: 'Grounding techniques that engage the senses and body bring her back into the present moment and her window of tolerance.' },
      { id: 'b', text: 'Encourage her to keep going so the memory can be fully processed today', isCorrect: false, rationale: 'Continuing while she is dissociated is unlikely to be therapeutic and can overwhelm her further.' },
      { id: 'c', text: 'Ask her to close her eyes and picture the memory in greater detail', isCorrect: false, rationale: 'Closing her eyes and deepening the memory increases the risk of further dissociation.' },
      { id: 'd', text: 'Interpret her dissociation as resistance to the work of the session', isCorrect: false, rationale: 'Dissociation is a protective response to overwhelming arousal, not resistance to be interpreted.' },
    ],
    rationale: 'When a client dissociates or becomes flooded, trauma-informed counselors first re-establish safety and present-moment awareness through grounding, such as the 5-4-3-2-1 senses exercise, feeling the feet on the floor, holding an object or naming the date and place. Trauma processing resumes only when the client is back within her window of tolerance.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis and trauma counseling: grounding and stabilization' }],
  },
  {
    id: 'nce-s-cou-120',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'medium',
    stem: 'In eye movement desensitization and reprocessing (EMDR), the client holds the disturbing image, negative belief and body sensations in mind while the counselor leads sets of eye movements, and distress ratings are taken until they fall toward zero. In Shapiro\'s eight-phase protocol, which phase is this?',
    options: [
      { id: 'a', text: 'Preparation', isCorrect: false, rationale: 'Preparation builds the relationship, explains EMDR and teaches calming skills before memories are processed.' },
      { id: 'b', text: 'Assessment', isCorrect: false, rationale: 'Assessment identifies the target image, negative and positive cognitions and baseline ratings without bilateral stimulation.' },
      { id: 'c', text: 'Desensitization', isCorrect: true, rationale: 'Desensitization uses sets of bilateral stimulation while the client attends to the target, until the SUD rating approaches 0.' },
      { id: 'd', text: 'Reevaluation', isCorrect: false, rationale: 'Reevaluation happens at the start of the next session to check whether earlier gains have held.' },
    ],
    rationale: 'Francine Shapiro\'s EMDR protocol has eight phases: history taking, preparation, assessment, desensitization, installation, body scan, closure and reevaluation. Bilateral stimulation (eye movements, taps or tones) is used during desensitization, installation of the positive cognition and the body scan. EMDR is recommended by several PTSD practice guidelines.',
    references: [{ source: 'APA CPG', detail: 'PTSD guideline (2017): EMDR as a conditionally recommended psychotherapy' }],
  },
];
