// tools/nce/seed/counseling-2.js
// NCE seed — Counseling Skills and Interventions, blueprint topics 16–29
// (group work, microskills, play therapy, crisis, career, development,
// attachment, multicultural competence, identity models, trauma, termination).
module.exports = [
  // ---------------------------------------------------------------- group work
  {
    id: 'nce-s-cou-031',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: "In the third session of a community anger-management group, members begin arguing about the attendance rule, and two members openly question whether the leader is qualified to run the group. According to Tuckman's model, the group is MOST likely in which stage?",
    options: [
      { id: 'a', text: 'Forming', isCorrect: false, rationale: 'Forming is the orientation stage of politeness, dependence on the leader and tentative participation, before open conflict emerges.' },
      { id: 'b', text: 'Storming', isCorrect: true, rationale: 'Storming is marked by conflict, challenges to the leader and struggles over control and rules as members test the group.' },
      { id: 'c', text: 'Norming', isCorrect: false, rationale: 'Norming follows storming; members have settled conflicts, agreed on norms and developed cohesion.' },
      { id: 'd', text: 'Performing', isCorrect: false, rationale: 'Performing is the productive stage in which the group works on its goals with little energy spent on conflict.' },
    ],
    rationale: "Tuckman (1965; adjourning added with Jensen in 1977) described forming, storming, norming, performing and adjourning. Conflict over rules and direct challenges to the leader's authority are the hallmark of storming, which leaders should treat as a normal developmental step rather than a sign the group is failing.",
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Group work: Tuckman stages of group development' }],
  },
  {
    id: 'nce-s-cou-032',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'hard',
    stem: "During the transition stage of a counseling group, a member crosses his arms and says to the leader, 'Honestly, this group is a waste of my time.' Other members fall silent. Which leader response BEST fits Corey's guidance for this stage?",
    options: [
      { id: 'a', text: 'Remind him that the group rules ask members to stay positive and to avoid discouraging the others in the room.', isCorrect: false, rationale: 'Invoking a rule to suppress the comment shuts down a challenge the group needs to work through and models avoidance of conflict.' },
      { id: 'b', text: 'Move to a structured exercise so the silence ends quickly and the group can return to the planned topic of the day.', isCorrect: false, rationale: 'Changing the subject bypasses the conflict; unaddressed resistance in the transition stage tends to go underground and erode trust.' },
      { id: 'c', text: 'Ask the other members whether they agree with him so that the group can vote on whether to keep meeting each week.', isCorrect: false, rationale: 'Polling members turns a personal reaction into a referendum, can isolate the member and puts the group itself on trial.' },
      { id: 'd', text: "Respond without defensiveness and invite him to say more about what isn't working for him in the group so far.", isCorrect: true, rationale: 'Corey advises leaders to meet challenges openly and non-defensively, treating resistance as useful information and modeling direct, respectful handling of conflict.' },
    ],
    rationale: 'In Corey\'s model the transition stage is characterized by anxiety, defensiveness, resistance and struggles for control, including challenges to the leader. The leader\'s task is to recognize and explore these reactions directly and non-defensively, which builds the trust needed to move into the working stage.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Group stages: transition stage, dealing with resistance and challenges to the leader' }],
  },
  {
    id: 'nce-s-cou-033',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A high school counselor plans a six-week group in which students learn and practice specific study and test-anxiety management skills, with brief lessons and structured activities each week. Under the ASGW classification of group work, this is BEST described as which type of group?',
    options: [
      { id: 'a', text: 'Psychoeducation group', isCorrect: true, rationale: 'Psychoeducation groups emphasize teaching information and skills, often to prevent problems, using structured content and activities.' },
      { id: 'b', text: 'Task group', isCorrect: false, rationale: 'Task and work groups focus on accomplishing an organizational goal, such as a committee or planning team, rather than member learning.' },
      { id: 'c', text: 'Counseling group', isCorrect: false, rationale: 'Counseling groups address interpersonal and developmental concerns through member interaction, with less didactic structure.' },
      { id: 'd', text: 'Psychotherapy group', isCorrect: false, rationale: 'Psychotherapy groups address more severe or chronic problems and personality reconstruction, which this skills group does not target.' },
    ],
    rationale: 'The ASGW identifies four group types: task/work, psychoeducation, counseling and psychotherapy. A time-limited, structured group whose main aim is teaching skills to a nonclinical population is a psychoeducation group.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Group work: ASGW types of groups' }],
  },
  {
    id: 'nce-s-cou-034',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'easy',
    stem: "After a member of a grief group shares that she still sets a place at the table for her late husband, three other members say they have done something similar. She replies, 'I thought I was the only one.' Which of Yalom's therapeutic factors is MOST evident?",
    options: [
      { id: 'a', text: 'Instillation of hope', isCorrect: false, rationale: 'Instillation of hope comes from seeing others improve or cope well, not from discovering that others share the same experience.' },
      { id: 'b', text: 'Altruism', isCorrect: false, rationale: 'Altruism is the benefit of helping others; the member here is the one receiving relief rather than giving help.' },
      { id: 'c', text: 'Universality', isCorrect: true, rationale: 'Universality is the relief of learning that one is not alone or unique in one\'s problems, thoughts or feelings.' },
      { id: 'd', text: 'Catharsis', isCorrect: false, rationale: 'Catharsis is the release of strong emotion; the key experience described is recognizing shared experience.' },
    ],
    rationale: "Yalom identified 11 therapeutic factors. Universality, the discovery that others share one's 'secret' struggles, often appears early in groups and reduces shame and isolation, which is why the member's statement that she thought she was the only one points to it.",
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Ch. 1: The therapeutic factors, universality' }],
  },
  {
    id: 'nce-s-cou-035',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: "In a young adult counseling group, two members repeatedly press a quieter member to 'finally tell us what really happened' with her family, even after she says she is not ready. Which leadership skill is MOST needed at this moment?",
    options: [
      { id: 'a', text: 'Linking, by connecting her reluctance to similar feelings that others in the group have described', isCorrect: false, rationale: 'Linking builds connection among members but does not stop the pressure being placed on her right now.' },
      { id: 'b', text: 'Drawing out, by inviting the quiet member to share a little more so the others feel heard', isCorrect: false, rationale: 'Drawing her out would join the pressure; she has already stated a boundary about disclosure.' },
      { id: 'c', text: 'Blocking, by stopping the pressure and affirming her right to decide what and when to share', isCorrect: true, rationale: 'Blocking protects members from counterproductive behavior such as coercive questioning while respecting their autonomy over disclosure.' },
      { id: 'd', text: 'Summarizing, by restating the main points of the discussion before moving to another member', isCorrect: false, rationale: 'Summarizing may move the group along but does not address the coercion or protect the member.' },
    ],
    rationale: 'Group leaders have a duty to protect members from undue pressure and from behaviors that threaten safety. Blocking intervenes in harmful patterns, such as pressuring, gossiping or breaking confidences, without attacking the members doing it.',
    references: [
      { source: 'Corey (Theory & Practice)', detail: 'Group leadership skills: blocking and protecting members' },
      { source: 'ACA Code of Ethics', detail: 'A.9.b Protecting Clients (group work)' },
    ],
  },
  {
    id: 'nce-s-cou-036',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'hard',
    stem: 'In a long-term interpersonal group, a man reacts to the male co-leader with the same deference and hidden resentment he felt toward his father, and competes with an older member as he did with his brother. Over months he recognizes the pattern and responds to them differently. Which of Yalom\'s therapeutic factors does this process BEST illustrate?',
    options: [
      { id: 'a', text: 'Corrective recapitulation of the primary family group', isCorrect: true, rationale: 'The group re-creates early family dynamics, and the member relives and then reworks those patterns in a new, corrective way.' },
      { id: 'b', text: 'Imitative behavior modeled on the co-leader and members', isCorrect: false, rationale: 'Imitative behavior means adopting behaviors seen in others; the core change here is reworking old family-based roles.' },
      { id: 'c', text: 'Socializing techniques learned through group role-plays', isCorrect: false, rationale: 'Socializing techniques are basic social skills learned in the group, not the reworking of family-of-origin patterns.' },
      { id: 'd', text: 'Existential factors, such as accepting final responsibility', isCorrect: false, rationale: 'Existential factors involve accepting responsibility, mortality and life\'s unfairness, not reliving family roles.' },
    ],
    rationale: 'Yalom describes groups as resembling a family in many ways, so members often relate to leaders and peers as they did to parents and siblings. When those patterns are not merely relived but explored and corrected, the factor is corrective recapitulation of the primary family group.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Ch. 1: Corrective recapitulation of the primary family group' }],
  },
  // ------------------------------------------------------------ microskills
  {
    id: 'nce-s-cou-037',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'easy',
    stem: "In Egan's SOLER guideline for nonverbal attending, what does the letter 'L' stand for?",
    options: [
      { id: 'a', text: 'Listen without interrupting', isCorrect: false, rationale: 'Uninterrupted listening matters, but SOLER describes physical posture, and L is not listening.' },
      { id: 'b', text: "Look at the client's face", isCorrect: false, rationale: 'Eye contact is the E in SOLER, not the L.' },
      { id: 'c', text: 'Limit note-taking in session', isCorrect: false, rationale: 'Note-taking is not one of the SOLER behaviors.' },
      { id: 'd', text: 'Lean slightly toward the client', isCorrect: true, rationale: 'L stands for leaning toward the client, a posture that signals involvement and interest.' },
    ],
    rationale: 'SOLER stands for Squarely face the client, Open posture, Lean toward the client, Eye contact and Relaxed manner. Egan presents these as flexible guidelines; the counselor adapts them to the client\'s culture and comfort, since direct eye contact or close posture is not welcome in every context.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Building the counseling relationship: attending behavior (SOLER)' }],
  },
  {
    id: 'nce-s-cou-038',
    reviewNote: 'Ivey\'s editions differ slightly on the hierarchy\'s base; the key holds across editions.',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'basic attending and listening skills',
    difficulty: 'medium',
    stem: "A practicum student is eager to start using confrontation and interpretation with clients. According to Ivey's microskills hierarchy, which skills should the student master FIRST?",
    options: [
      { id: 'a', text: 'Reflection of meaning and the interpretation of core themes', isCorrect: false, rationale: 'Reflection of meaning and interpretation sit higher in the hierarchy and rely on the listening foundation.' },
      { id: 'b', text: 'Attending behavior and the basic listening sequence', isCorrect: true, rationale: 'Attending and the basic listening sequence are the foundation on which higher-level influencing skills are built.' },
      { id: 'c', text: 'Influencing skills such as directives and feedback', isCorrect: false, rationale: 'Influencing skills are later in the hierarchy and are effective only after the client feels heard.' },
      { id: 'd', text: 'Skill integration and a personal style of counseling', isCorrect: false, rationale: 'Skill integration and personal style form the top of the hierarchy, reached after the other skills are mastered.' },
    ],
    rationale: 'Ivey\'s hierarchy rests on ethics, multicultural competence and wellness, then attending behavior, then the basic listening sequence (questions, observation, encouraging, paraphrasing, summarizing, reflecting feeling). Focusing, empathic confrontation, reflection of meaning, influencing skills and skill integration build on that base.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: Ivey microskills hierarchy' }],
  },
  {
    id: 'nce-s-cou-039',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'easy',
    stem: "A client says, 'My supervisor criticized my report in front of the whole team again, and I just sat there and said nothing.' Which counselor response is the BEST example of a reflection of feeling?",
    options: [
      { id: 'a', text: "You felt embarrassed, and maybe angry with yourself for not speaking up.", isCorrect: true, rationale: 'This names the likely emotions behind the statement, which is the defining feature of reflecting feeling.' },
      { id: 'b', text: 'Your supervisor criticized your report in front of the team once again.', isCorrect: false, rationale: 'This restates the content of the message, which makes it a paraphrase rather than a reflection of feeling.' },
      { id: 'c', text: 'What do you think stopped you from saying something to your supervisor?', isCorrect: false, rationale: 'This is an open question that explores reasons; it does not reflect the emotion being expressed.' },
      { id: 'd', text: 'Next time, it might help to ask your supervisor to talk with you privately.', isCorrect: false, rationale: 'This is advice-giving, an influencing response that skips past the client\'s feelings.' },
    ],
    rationale: 'A reflection of feeling identifies and names the emotion in the client\'s message, often tentatively, so the client feels understood and can explore it further. A paraphrase captures content; questions and advice are different skills.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: reflection of feeling versus paraphrasing' }],
  },
  {
    id: 'nce-s-cou-040',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: 'Midway through a session, a client has moved quickly among worries about money, conflict with her sister and trouble sleeping. The counselor wants to pull these threads together, check accuracy and help the client choose a focus. Which skill is MOST suited to this purpose?',
    options: [
      { id: 'a', text: 'Paraphrasing', isCorrect: false, rationale: 'Paraphrasing restates the content of a single statement rather than tying together several themes across the session.' },
      { id: 'b', text: 'Reflection of meaning', isCorrect: false, rationale: 'Reflection of meaning explores values and deeper significance, not the organization of several topics into a focus.' },
      { id: 'c', text: 'Summarizing', isCorrect: true, rationale: 'Summarizing condenses several statements or themes, checks understanding and helps set direction or transition.' },
      { id: 'd', text: 'Encouraging', isCorrect: false, rationale: 'Minimal encouragers keep the client talking; they do not integrate content across topics.' },
    ],
    rationale: 'Summarizing draws together the main content and feelings from a longer stretch of talk. It is used to begin or end sessions, to make transitions and to help a client who has raised many concerns decide what to work on.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: summarizing' }],
  },
  {
    id: 'nce-s-cou-041',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: "A client who is tearful and twisting a tissue says, 'I'm completely fine with the divorce. It's no big deal.' Which response BEST illustrates empathic confrontation?",
    options: [
      { id: 'a', text: "You aren't being honest with me or yourself, because you are clearly upset right now.", isCorrect: false, rationale: 'This accuses and judges the client, which is likely to raise defensiveness rather than invite exploration.' },
      { id: 'b', text: 'Divorce is one of the most stressful life events, so being upset would be quite normal.', isCorrect: false, rationale: 'This normalizes and reassures, but it does not name the discrepancy between the words and the behavior.' },
      { id: 'c', text: 'Why do you think you are telling me it is no big deal when it seems to matter a lot?', isCorrect: false, rationale: '"Why" questions tend to put clients on the defensive and ask for justification rather than reflection.' },
      { id: 'd', text: "You're saying the divorce is no big deal, and you're also in tears as we talk about it.", isCorrect: true, rationale: 'This nonjudgmentally places the verbal message beside the nonverbal one and lets the client explore the mixed message.' },
    ],
    rationale: 'Empathic confrontation identifies discrepancies, mixed messages or conflicts (often with an "on the one hand ... and on the other" format) in a supportive, nonjudgmental way. Its aim is to help the client notice and resolve the incongruity, not to win an argument.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: confrontation of discrepancies' }],
  },
  {
    id: 'nce-s-cou-042',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: "A counselor says, 'I notice that whenever we get close to talking about your father, you change the subject and glance at me as if checking my reaction. I'm wondering what is happening between us right now.' This statement is BEST described as:",
    options: [
      { id: 'a', text: 'Self-disclosure', isCorrect: false, rationale: 'Self-disclosure shares information about the counselor\'s own life; here the focus is the current relationship.' },
      { id: 'b', text: 'Immediacy', isCorrect: true, rationale: 'Immediacy addresses what is occurring in the here-and-now between counselor and client.' },
      { id: 'c', text: 'Interpretation', isCorrect: false, rationale: 'Interpretation offers a new frame for the client\'s behavior; this response invites discussion of the present interaction instead.' },
      { id: 'd', text: 'Reframing', isCorrect: false, rationale: 'Reframing recasts a situation in a different light; it does not focus on the counselor-client relationship.' },
    ],
    rationale: 'Immediacy is the counselor\'s direct, present-tense comment on the counseling relationship or on a pattern unfolding in the session. It is useful when trust, tension, dependence or avoidance in the relationship is blocking progress.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: immediacy' }],
  },
  // ------------------------------------------------------------ play therapy
  {
    id: 'nce-s-cou-043',
    reviewNote: 'The key\'s wording is in Landreth\'s style, not a direct quote.',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'medium',
    stem: 'In a child-centered play therapy session, a 6-year-old grows frustrated and raises a wooden block as if to throw it at the counselor. Using Landreth\'s ACT model of limit setting, which response is BEST?',
    options: [
      { id: 'a', text: "If you throw that block, our playtime is over for today and we will go back out.", isCorrect: false, rationale: 'Leading with a consequence skips acknowledging the feeling and offering an alternative; consequences come only if limits are repeatedly broken.' },
      { id: 'b', text: "We don't throw blocks in here. Can you please put it back on the shelf for me?", isCorrect: false, rationale: 'This states a limit but ignores the child\'s feeling and gives no acceptable outlet for it.' },
      { id: 'c', text: "You're really mad. I'm not for throwing. You can throw the soft ball at the wall.", isCorrect: true, rationale: 'This acknowledges the feeling, communicates the limit and targets an acceptable alternative, the three steps of ACT.' },
      { id: 'd', text: 'It sounds like you are feeling frustrated with how the game is going for you today.', isCorrect: false, rationale: 'Reflecting the feeling alone leaves the counselor and child unprotected; a limit is needed when safety is at stake.' },
    ],
    rationale: 'Landreth\'s ACT model: Acknowledge the child\'s feeling, Communicate the limit and Target an acceptable alternative. Limits in child-centered play therapy are few, are stated calmly and briefly, and protect physical safety and the relationship while leaving the feeling itself accepted.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: child-centered play therapy and limit setting' }],
  },
  {
    id: 'nce-s-cou-044',
    reviewNote: 'Kottman\'s Adlerian play therapy phases are cited via Gladding, which may not cover Kottman in depth.',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'hard',
    stem: "A play therapist spends early sessions building an egalitarian relationship with a 9-year-old, then gathers information about the child's lifestyle and mistaken beliefs, helps the child gain insight, and finally uses reorientation to practice new ways of belonging. This sequence is characteristic of which approach?",
    options: [
      { id: 'a', text: 'Adlerian play therapy', isCorrect: true, rationale: "Kottman's Adlerian play therapy proceeds through relationship building, exploring lifestyle, gaining insight and reorientation/reeducation." },
      { id: 'b', text: 'Child-centered play therapy', isCorrect: false, rationale: 'Child-centered play therapy is nondirective and does not assess lifestyle or work toward planned reeducation phases.' },
      { id: 'c', text: 'Theraplay', isCorrect: false, rationale: 'Theraplay is a directive, attachment-based approach involving caregivers in structured engagement and nurture activities.' },
      { id: 'd', text: 'Filial therapy', isCorrect: false, rationale: 'Filial therapy trains parents to conduct child-centered play sessions; it is not organized around lifestyle analysis.' },
    ],
    rationale: 'Terry Kottman\'s Adlerian play therapy integrates Adlerian concepts (lifestyle, mistaken beliefs, the Crucial Cs, encouragement) with play. Its four phases are building an egalitarian relationship, exploring the child\'s lifestyle, helping the child gain insight and reorientation/reeducation.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: approaches to play therapy (Adlerian, child-centered, filial)' }],
  },
  // ------------------------------------------------------------ crisis
  {
    id: 'nce-s-cou-045',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'medium',
    stem: "A college student arrives at the counseling center hours after learning his scholarship was revoked, saying he 'can't see a way forward.' Following Roberts' seven-stage crisis intervention model, what should the counselor do FIRST?",
    options: [
      { id: 'a', text: 'Help him generate options for funding and plan his next steps with financial aid', isCorrect: false, rationale: 'Generating and exploring alternatives is stage 5, after safety, rapport, problems and feelings have been addressed.' },
      { id: 'b', text: 'Conduct a thorough psychosocial and lethality assessment, including suicide risk', isCorrect: true, rationale: 'Stage 1 of Roberts\' model is a biopsychosocial and lethality assessment; his hopeless statement makes this urgent.' },
      { id: 'c', text: 'Explore and validate his feelings of shock, anger and shame about the revocation', isCorrect: false, rationale: 'Dealing with feelings and emotions is stage 4 of the model, not the first step.' },
      { id: 'd', text: 'Identify the main problems and the precipitating event that led him to come in today', isCorrect: false, rationale: 'Identifying major problems and precipitants is stage 3, after assessment and rapport building.' },
    ],
    rationale: "Roberts' seven stages are: (1) plan and conduct a thorough biopsychosocial and lethality assessment, (2) establish rapport, (3) identify major problems and precipitants, (4) deal with feelings and emotions, (5) generate and explore alternatives, (6) implement an action plan and (7) follow up. Stages can overlap, but safety assessment comes first.",
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: "Crisis counseling: Roberts' seven-stage crisis intervention model" }],
  },
  {
    id: 'nce-s-cou-046',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'easy',
    stem: 'A family is seen by a crisis counselor two days after their apartment was destroyed in a fire. Which goal BEST reflects the primary aim of crisis intervention?',
    options: [
      { id: 'a', text: 'Uncover early losses that make the family vulnerable to grief and resolve them', isCorrect: false, rationale: 'Exploring early history is a goal of longer-term therapy and can overwhelm people in acute crisis.' },
      { id: 'b', text: 'Restructure family roles and boundaries that may have contributed to stress', isCorrect: false, rationale: 'Structural change in family organization is a family therapy goal, not the immediate aim of crisis work.' },
      { id: 'c', text: 'Complete a diagnostic evaluation of each member to begin long-term treatment', isCorrect: false, rationale: 'Crisis intervention is brief and focused on coping; a crisis reaction is not by itself a disorder requiring diagnosis.' },
      { id: 'd', text: 'Restore the family to at least its pre-crisis level of coping and functioning', isCorrect: true, rationale: 'Crisis intervention seeks to stabilize people and restore equilibrium, at least to the pre-crisis level of functioning.' },
    ],
    rationale: 'A crisis is a time-limited state in which usual coping is overwhelmed. Crisis intervention is brief, active and present-focused, aiming to ensure safety, mobilize resources and coping and return people to at least their pre-crisis level of functioning; deeper personality or system change is left for later work if needed.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis counseling: goals of crisis intervention' }],
  },
  // ------------------------------------------------------------ career
  {
    id: 'nce-s-cou-047',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: "On Holland's RIASEC hexagon, which pair of personality types is MOST consistent, meaning the two types share the most characteristics?",
    options: [
      { id: 'a', text: 'Realistic and Investigative', isCorrect: true, rationale: 'Realistic and Investigative are adjacent on the hexagon, so they share the most traits and form a consistent pair.' },
      { id: 'b', text: 'Realistic and Social', isCorrect: false, rationale: 'Realistic and Social sit opposite each other on the hexagon and are the least consistent pairing.' },
      { id: 'c', text: 'Artistic and Conventional', isCorrect: false, rationale: 'Artistic and Conventional are opposite types, one valuing self-expression and the other order and structure.' },
      { id: 'd', text: 'Investigative and Enterprising', isCorrect: false, rationale: 'Investigative and Enterprising are opposite each other on the hexagon, so they are inconsistent.' },
    ],
    rationale: "Holland arranged the six types in the order R-I-A-S-E-C around a hexagon. Adjacent types are most consistent, alternate types are intermediate and opposite types (R-S, I-E, A-C) are least consistent. Holland's related ideas include congruence (fit between person and environment) and differentiation.",
    references: [{ source: 'Sharf (Career Development Theory)', detail: "Holland's theory of types: the hexagon and consistency" }],
  },
  {
    id: 'nce-s-cou-048',
    reviewNote: 'Super\'s stage ages are approximate; the rationale notes recycling.',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: "A 52-year-old nurse manager tells a counselor that her main concerns are holding on to the position she has built, keeping her clinical skills current and innovating within her role. In Super's life-span, life-space theory, these concerns BEST fit which career stage?",
    options: [
      { id: 'a', text: 'Establishment', isCorrect: false, rationale: 'Establishment (about ages 25 to 44) centers on stabilizing in and advancing within a chosen field.' },
      { id: 'b', text: 'Exploration', isCorrect: false, rationale: 'Exploration (about ages 15 to 24) involves crystallizing, specifying and implementing an occupational choice.' },
      { id: 'c', text: 'Maintenance', isCorrect: true, rationale: 'Maintenance (about ages 45 to 64) involves holding, updating and innovating to preserve one\'s position.' },
      { id: 'd', text: 'Disengagement', isCorrect: false, rationale: 'Disengagement (about 65 and older) involves decelerating, retirement planning and retirement living.' },
    ],
    rationale: "Super's stages are growth, exploration, establishment, maintenance and disengagement, each with developmental tasks; the maintenance tasks are holding, updating and innovating. Super also stressed that people recycle through stages and that work is one of several life roles shown in the life-career rainbow.",
    references: [{ source: 'Sharf (Career Development Theory)', detail: "Super's life-span, life-space theory: maintenance stage tasks" }],
  },
  {
    id: 'nce-s-cou-049',
    domain: 'counseling',
    cacrep: 'career',
    topic: 'career development theories (Holland, Super, Krumboltz)',
    difficulty: 'medium',
    stem: "A client is anxious because she has no clear five-year career plan. The counselor helps her see that past opportunities arose from unexpected events, and encourages curiosity, persistence, flexibility, optimism and risk taking to create and use future chance events. This approach reflects:",
    options: [
      { id: 'a', text: 'Theory of work adjustment', isCorrect: false, rationale: 'The theory of work adjustment (Dawis and Lofquist) addresses correspondence between worker needs and job reinforcers.' },
      { id: 'b', text: 'Planned happenstance theory', isCorrect: true, rationale: 'Planned happenstance (Mitchell, Levin and Krumboltz) teaches clients to create and capitalize on unplanned events.' },
      { id: 'c', text: 'Circumscription and compromise', isCorrect: false, rationale: "Gottfredson's theory explains how children narrow options by sex type and prestige, not how to use chance events." },
      { id: 'd', text: 'Cognitive information processing', isCorrect: false, rationale: 'CIP (Sampson, Peterson and colleagues) focuses on the pyramid of information processing and the CASVE decision cycle.' },
    ],
    rationale: "Planned happenstance grew out of Krumboltz's social learning theory of career decision making. It reframes indecision as open-mindedness and builds five skills (curiosity, persistence, flexibility, optimism and risk taking) so that clients can turn unplanned events into career opportunities.",
    references: [{ source: 'Sharf (Career Development Theory)', detail: "Krumboltz's social learning theory and planned happenstance" }],
  },
  // ------------------------------------------------------------ human development
  {
    id: 'nce-s-cou-050',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: "A 4-year-old eagerly plans games and starts projects, but his parents often scold him for 'making messes' when he tries new activities. In Erikson's theory, this child is working on which psychosocial crisis?",
    options: [
      { id: 'a', text: 'Autonomy vs. shame and doubt', isCorrect: false, rationale: 'Autonomy vs. shame and doubt is the toddler stage (about 1 to 3 years), centered on self-control and independence.' },
      { id: 'b', text: 'Industry vs. inferiority', isCorrect: false, rationale: 'Industry vs. inferiority is the school-age stage (about 6 to 12 years), centered on competence and productivity.' },
      { id: 'c', text: 'Trust vs. mistrust', isCorrect: false, rationale: 'Trust vs. mistrust is the infancy stage (birth to about 1 year), centered on reliable caregiving.' },
      { id: 'd', text: 'Initiative vs. guilt', isCorrect: true, rationale: 'Initiative vs. guilt (about 3 to 6 years) involves planning and starting activities; harsh criticism can foster guilt.' },
    ],
    rationale: "Erikson's eight stages are trust vs. mistrust (infancy), autonomy vs. shame and doubt (toddlerhood), initiative vs. guilt (preschool), industry vs. inferiority (school age), identity vs. role confusion (adolescence), intimacy vs. isolation (young adulthood), generativity vs. stagnation (middle adulthood) and integrity vs. despair (late adulthood).",
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: "Erikson's psychosocial theory: initiative vs. guilt in early childhood" }],
  },
  {
    id: 'nce-s-cou-051',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'easy',
    stem: 'An 8-year-old correctly explains that a ball of clay has the same amount of clay after it is rolled into a long snake, but she struggles with a purely hypothetical question about what would happen if people had no need for sleep. In Piaget\'s theory, she is MOST likely in which stage?',
    options: [
      { id: 'a', text: 'Concrete operational', isCorrect: true, rationale: 'The concrete operational child (about 7 to 11) masters conservation and logical operations on concrete objects but not abstract hypotheticals.' },
      { id: 'b', text: 'Preoperational', isCorrect: false, rationale: 'Preoperational children (about 2 to 7) typically fail conservation tasks because of centration.' },
      { id: 'c', text: 'Formal operational', isCorrect: false, rationale: 'Formal operational thinkers (about 11 and older) can reason about abstract and hypothetical propositions, which she cannot yet do.' },
      { id: 'd', text: 'Sensorimotor', isCorrect: false, rationale: 'The sensorimotor stage (birth to about 2) involves learning through senses and actions, before symbolic thought.' },
    ],
    rationale: "Piaget's four stages are sensorimotor (birth to 2), preoperational (2 to 7), concrete operational (7 to 11) and formal operational (11 and up). Conservation marks concrete operations; abstract, hypothetico-deductive reasoning marks formal operations.",
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: "Piaget's cognitive-developmental theory: concrete operational stage" }],
  },
  {
    id: 'nce-s-cou-052',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'human development theories (Erikson, Piaget, Kohlberg)',
    difficulty: 'medium',
    stem: "Asked whether a man should steal an unaffordable medicine to save his wife, a 16-year-old answers, 'No, because if everyone broke the law when they felt like it, society would fall apart.' This reasoning BEST fits which Kohlberg stage?",
    options: [
      { id: 'a', text: 'Stage 2: Instrumental exchange', isCorrect: false, rationale: 'Stage 2 (preconventional) reasoning focuses on self-interest and fair deals, not on maintaining social order.' },
      { id: 'b', text: 'Stage 3: Interpersonal conformity', isCorrect: false, rationale: 'Stage 3 reasoning centers on being seen as good and winning the approval of others.' },
      { id: 'c', text: 'Stage 4: Law and order orientation', isCorrect: true, rationale: 'Stage 4 (conventional) reasoning upholds laws and duties because they maintain the social system.' },
      { id: 'd', text: 'Stage 5: Social contract', isCorrect: false, rationale: 'Stage 5 (postconventional) sees laws as changeable agreements that can be set aside to protect basic rights such as life.' },
    ],
    rationale: "Kohlberg described three levels with two stages each: preconventional (1 punishment and obedience, 2 instrumental purpose), conventional (3 interpersonal conformity, 4 social-order maintenance or law and order) and postconventional (5 social contract, 6 universal ethical principles). Stage is judged by the reasoning given, not by the yes-or-no answer.",
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: "Kohlberg's theory of moral development: conventional level" }],
  },
  // ------------------------------------------------------------ attachment
  {
    id: 'nce-s-cou-053',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'medium',
    stem: "In the Strange Situation, a 14-month-old stays close to her mother and explores little. She becomes very distressed when her mother leaves, and on reunion she clings to her mother while also pushing away and crying angrily. Which attachment classification BEST fits?",
    options: [
      { id: 'a', text: 'Secure', isCorrect: false, rationale: 'Securely attached infants explore using the parent as a base and are readily comforted on reunion.' },
      { id: 'b', text: 'Anxious-ambivalent (resistant)', isCorrect: true, rationale: 'Resistant infants explore little, are highly distressed at separation and both seek and resist contact on reunion.' },
      { id: 'c', text: 'Avoidant', isCorrect: false, rationale: 'Avoidant infants show little distress at separation and ignore or avoid the parent on reunion.' },
      { id: 'd', text: 'Disorganized/disoriented', isCorrect: false, rationale: 'Disorganized infants show contradictory, confused behaviors such as freezing or approaching with the head averted.' },
    ],
    rationale: 'Ainsworth\'s Strange Situation identified secure, avoidant and anxious-ambivalent (resistant) patterns; Main and Solomon later added disorganized/disoriented. Mixing angry resistance with contact seeking on reunion is the signature of the resistant pattern, often linked to inconsistent caregiving.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Attachment: Ainsworth Strange Situation classifications' }],
  },
  {
    id: 'nce-s-cou-054',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'hard',
    stem: 'A counselor reviewing an infant assessment reads that, on reunion with a parent, the 12-month-old approached with his face turned away, then froze with a dazed expression. Which statement about this pattern is MOST accurate?',
    options: [
      { id: 'a', text: "It is Ainsworth's original avoidant category, linked mainly to warm but busy caregivers", isCorrect: false, rationale: 'Avoidant infants show organized avoidance, and the pattern is linked to rejecting, not warm-but-busy, caregiving.' },
      { id: 'b', text: 'It reflects a secure pattern in a temperamentally shy infant who needs time to warm up', isCorrect: false, rationale: 'Freezing and approach-avoidance are not features of secure attachment, regardless of temperament.' },
      { id: 'c', text: 'It is the resistant pattern, defined by clinging mixed with anger toward the caregiver', isCorrect: false, rationale: 'Resistant infants show organized ambivalence; the freezing and averted approach described here is different.' },
      { id: 'd', text: 'It fits the disorganized category added by Main and Solomon, tied to frightening care', isCorrect: true, rationale: 'Disorganized attachment involves contradictory or dazed behavior and is associated with frightened or frightening caregiving.' },
    ],
    rationale: 'Main and Solomon identified disorganized/disoriented attachment in infants whose behavior did not fit Ainsworth\'s three organized patterns. The infant lacks a coherent strategy, often because the caregiver is a source of both comfort and fear, as in maltreatment or unresolved parental trauma.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Attachment: disorganized/disoriented attachment (Main & Solomon)' }],
  },
  // ------------------------------------------------------------ multicultural
  {
    id: 'nce-s-cou-055',
    reviewNote: 'MSJCC cited via Sue & Sue; consider the primary source (Ratts et al., 2016) when one is added.',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'hard',
    stem: 'The original Sue, Arredondo and McDavis multicultural competencies were organized around attitudes and beliefs, knowledge and skills. Which additional aspirational competency did the Multicultural and Social Justice Counseling Competencies (MSJCC) add?',
    options: [
      { id: 'a', text: 'Action', isCorrect: true, rationale: 'The MSJCC framework adds action (AKSA), calling counselors to engage in advocacy and intervention at multiple levels.' },
      { id: 'b', text: 'Awareness', isCorrect: false, rationale: 'Awareness of one\'s own cultural values and biases was already central to the original competencies.' },
      { id: 'c', text: 'Assessment', isCorrect: false, rationale: 'Culturally appropriate assessment is part of skills, not a separate aspirational competency in the MSJCC.' },
      { id: 'd', text: 'Accreditation', isCorrect: false, rationale: 'Accreditation is a program-level standard, not one of the aspirational competencies.' },
    ],
    rationale: 'The MSJCC (Ratts and colleagues, endorsed by ACA in 2015) uses quadrants of privileged and marginalized counselor and client identities and four developmental domains: counselor self-awareness, client worldview, the counseling relationship, and counseling and advocacy interventions. Each domain includes attitudes and beliefs, knowledge, skills and action.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Multicultural and Social Justice Counseling Competencies (MSJCC)' }],
  },
  {
    id: 'nce-s-cou-056',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'easy',
    stem: 'A counselor notices she feels impatient with clients who defer major decisions to their extended families, and she begins examining how her own upbringing shapes that reaction. In the Sue, Arredondo and McDavis framework, this work MOST directly reflects which competency area?',
    options: [
      { id: 'a', text: "Understanding the worldview of the culturally different client", isCorrect: false, rationale: "Understanding the client's worldview is a separate area; her focus here is on her own conditioning." },
      { id: 'b', text: 'Developing culturally appropriate intervention strategies', isCorrect: false, rationale: 'Intervention strategies concern what the counselor does in session, not examining her own reactions.' },
      { id: 'c', text: 'Awareness of her own cultural values, assumptions and biases', isCorrect: true, rationale: 'Examining how her own background shapes reactions to clients is counselor self-awareness, the first competency area.' },
      { id: 'd', text: 'Knowledge of family structures common among collectivist cultures', isCorrect: false, rationale: 'Knowledge of client cultures matters, but the activity described is reflection on her own biases.' },
    ],
    rationale: 'Sue, Arredondo and McDavis (1992) described three characteristics of the culturally skilled counselor: awareness of one\'s own assumptions, values and biases; understanding the worldview of culturally different clients; and developing appropriate intervention strategies. Each is assessed across beliefs and attitudes, knowledge and skills.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Multicultural counseling competencies: counselor awareness of own assumptions, values and biases' }],
  },
  // ------------------------------------------------------------ identity models
  {
    id: 'nce-s-cou-057',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'medium',
    stem: "Months after a racist incident on campus shook her belief that race did not matter, a Black college student now surrounds herself with Black-centered organizations, studies Black history intensely and expresses anger toward White people. In Cross's Nigrescence model, she is MOST likely in which stage?",
    options: [
      { id: 'a', text: 'Pre-encounter', isCorrect: false, rationale: 'Pre-encounter involves low race salience or pro-White attitudes, which she has moved beyond.' },
      { id: 'b', text: 'Immersion-emersion', isCorrect: true, rationale: 'Immersion-emersion involves intense involvement in Black culture and often anger toward White people.' },
      { id: 'c', text: 'Encounter', isCorrect: false, rationale: 'The encounter is the event, here the incident, that challenged her prior worldview; she has moved past it.' },
      { id: 'd', text: 'Internalization', isCorrect: false, rationale: 'Internalization brings a secure, less reactive Black identity and openness to other groups.' },
    ],
    rationale: "Cross's model describes pre-encounter, encounter, immersion-emersion and internalization (with internalization-commitment for sustained action). After an encounter disrupts the old identity, the person often immerses in Black culture and withdraws from or rejects White culture before reaching a more secure, internalized identity.",
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Racial/cultural identity development: Cross Nigrescence model' }],
  },
  {
    id: 'nce-s-cou-058',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: 'After a multicultural course, a White counseling student feels guilt and confusion. She now sees racism around her, yet feels torn between loyalty to family members who make racist jokes and her new beliefs. In Helms\' White racial identity model, this experience BEST fits which status?',
    options: [
      { id: 'a', text: 'Contact', isCorrect: false, rationale: 'Contact involves obliviousness to racism and a naive, color-blind view, which she has moved past.' },
      { id: 'b', text: 'Reintegration', isCorrect: false, rationale: 'Reintegration resolves the conflict by retreating to beliefs in White superiority and blaming people of color.' },
      { id: 'c', text: 'Pseudo-independence', isCorrect: false, rationale: 'Pseudo-independence is an intellectual commitment to change that comes after the conflict of disintegration.' },
      { id: 'd', text: 'Disintegration', isCorrect: true, rationale: 'Disintegration involves guilt, confusion and conflict between new awareness of racism and loyalty to one\'s own group.' },
    ],
    rationale: "Helms' White racial identity statuses are contact, disintegration, reintegration, pseudo-independence, immersion/emersion and autonomy. Disintegration is the uncomfortable phase in which new awareness of racism collides with prior beliefs and group loyalties, producing guilt, shame and moral dilemmas.",
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: "White racial identity development: Helms' model" }],
  },
  // ------------------------------------------------------------ trauma and termination
  {
    id: 'nce-s-cou-059',
    reviewNote: 'SAMHSA\'s six trauma-informed principles are cited via Gladding (SAMHSA TIP 57 is not on the approved list).',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'medium',
    stem: 'At an intake, a client with a history of assault becomes visibly tense when the counselor closes the office door and moves her chair to sit between the client and the exit. Which response BEST reflects trauma-informed practice?',
    options: [
      { id: 'a', text: 'Name what she noticed, explain the reason for privacy and ask how the client wants the room set up', isCorrect: true, rationale: 'This offers transparency, voice and choice, restoring a sense of safety and control, which are core trauma-informed principles.' },
      { id: 'b', text: 'Continue the intake as planned so the client can see the office is safe and her anxiety will fade', isCorrect: false, rationale: 'Pressing on ignores a cue of distress and puts the counselor\'s agenda ahead of the client\'s sense of safety.' },
      { id: 'c', text: 'Begin a detailed account of the assault now so that the tension can be processed early in treatment', isCorrect: false, rationale: 'Pushing for trauma details at intake, before safety and stabilization, risks retraumatization.' },
      { id: 'd', text: 'Reassure her that the building is secure and that no one can come in while the door is fully closed', isCorrect: false, rationale: 'Reassurance alone does not give the client any control and may increase her sense of being trapped.' },
    ],
    rationale: "SAMHSA's trauma-informed approach rests on safety; trustworthiness and transparency; peer support; collaboration and mutuality; empowerment, voice and choice; and attention to cultural, historical and gender issues. Small environmental choices, explained openly, help clients regain control and prevent retraumatization.",
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Trauma and crisis counseling: principles of trauma-informed care' }],
  },
  {
    id: 'nce-s-cou-060',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'medium',
    stem: 'A client has met her goals for managing panic after 14 sessions, and she and the counselor agree to end counseling. Which approach to the final sessions is BEST?',
    options: [
      { id: 'a', text: 'End at the next session with a brief goodbye to avoid fostering dependence on counseling', isCorrect: false, rationale: 'An abrupt ending skips consolidation and relapse planning and gives no room to process feelings about ending.' },
      { id: 'b', text: 'Review her gains, anticipate setbacks, plan to keep progress and discuss feelings about ending', isCorrect: true, rationale: 'Effective termination consolidates learning, prepares for relapse, addresses feelings and clarifies how to return if needed.' },
      { id: 'c', text: 'Begin work on new goals so that she stays engaged and does not lose momentum after her progress', isCorrect: false, rationale: 'Adding goals once the agreed goals are met and the client no longer needs services is not in her interest.' },
      { id: 'd', text: 'Reduce session length gradually while avoiding talk about the ending so she is not made anxious', isCorrect: false, rationale: 'Avoiding the topic of ending denies the client a chance to process it and to plan for maintaining gains.' },
    ],
    rationale: 'Termination is a planned phase, not an event. Counselors review progress, help clients attribute change to their own efforts, anticipate challenges and relapse, explore feelings about ending and leave the door open, consistent with ACA guidance to terminate when services are no longer needed and to provide pretermination counseling.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' },
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Termination of counseling relationships' },
    ],
  },
];
