// tools/nce/seed/counseling-7.js
// NCE seed — Counseling Skills and Interventions, batch 4: new angles on core
// theories and skills (reality therapy, reflection/summarizing, confrontation,
// termination, Adlerian, person-centered, existential, behavior therapy, CBT,
// psychodynamic, family systems, trauma-informed care, crisis models, MI),
// including cross-theory comparison items.
const C = 'Corey (Theory & Practice)';
const MI = 'Miller & Rollnick (MI)';
const G = 'Goldenberg (Family Therapy)';
const GL = 'Gladding (Counseling: A Comprehensive Profession)';
const JG = 'James & Gilliland (Crisis Intervention Strategies)';

module.exports = [
  // ------------------------------------------------- reality therapy / choice theory
  {
    id: 'nce-s-cou-181',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'easy',
    stem: 'Glasser pictured total behavior as a car, with basic needs as the engine and wants as the steering wheel. Which two components are the front wheels, the parts of behavior a person controls most directly?',
    options: [
      { id: 'a', text: 'Feeling and physiology', isCorrect: false, rationale: 'Feeling and physiology are the back wheels; they follow along and change indirectly when acting and thinking change.' },
      { id: 'b', text: 'Wants and needs', isCorrect: false, rationale: 'In the metaphor, needs are the engine and wants steer the car; they are not components of total behavior.' },
      { id: 'c', text: 'Acting and thinking', isCorrect: true, rationale: 'Acting and thinking are the front wheels: the components over which people have the most direct control.' },
      { id: 'd', text: 'Perceiving and remembering', isCorrect: false, rationale: 'Perception plays a role in choice theory (the perceived world), but it is not one of the four wheels of total behavior.' },
    ],
    rationale: 'In choice theory, total behavior has four inseparable components: acting, thinking, feeling and physiology. Glasser argued that we have almost total control over acting and thinking and only indirect control over feeling and physiology. Reality therapists therefore focus on what the client is doing and thinking, expecting feelings and body states to follow.',
    references: [{ source: C, detail: 'Reality Therapy: choice theory and total behavior' }],
  },
  {
    id: 'nce-s-cou-182',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'medium',
    stem: 'A 17-year-old on probation says nothing matters to him, yet he lights up when he talks about his grandmother and about someday becoming a firefighter. A reality therapist notes that these belong to his quality world. In choice theory, the quality world is BEST described as:',
    options: [
      { id: 'a', text: 'A personal album of the people, things and ideas that best satisfy his needs', isCorrect: true, rationale: 'Glasser described the quality world as a set of specific pictures of the people, activities, possessions and beliefs that we believe will best satisfy our needs.' },
      { id: 'b', text: 'The stored record of past failures that has built up into a failure identity', isCorrect: false, rationale: 'Failure identity was an early Glasser concept about how people see themselves, not the store of need-satisfying pictures.' },
      { id: 'c', text: 'An unconscious storehouse of repressed wishes that drives his current choices', isCorrect: false, rationale: 'Repressed unconscious wishes are a psychoanalytic idea; choice theory emphasizes present, conscious choices.' },
      { id: 'd', text: 'The shared set of perceptions about reality that he holds with his peer group', isCorrect: false, rationale: 'The quality world is highly individual; it is not a set of perceptions shared with a group.' },
    ],
    rationale: 'The quality world is the core of choice theory\'s motivation: everyone carries a personal "album" of pictures of what would satisfy the needs for survival, love and belonging, power, freedom and fun. A reality therapist tries to learn what is in the client\'s quality world and to become part of it, then helps the client evaluate whether current behavior is getting him what he wants.',
    references: [{ source: C, detail: 'Reality Therapy: the quality world' }],
  },
  {
    id: 'nce-s-cou-183',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reality therapy and choice theory',
    difficulty: 'medium',
    stem: 'A client agreed to walk for 20 minutes three mornings this week. She returns saying she "just couldn\'t find the time." Which response BEST reflects the reality therapy principles of accepting no excuses and using no punishment?',
    options: [
      { id: 'a', text: '"That is disappointing. We agreed on this, so I expect you to make up the missed walks."', isCorrect: false, rationale: 'Expressing disappointment and imposing a make-up penalty is criticism and punishment, which reality therapists avoid because it damages the relationship.' },
      { id: 'b', text: '"Tell me more about what made this week so hard. Your schedule may explain a great deal."', isCorrect: false, rationale: 'Inviting a long account of why the plan failed accepts the excuse and keeps the focus off what she will do next.' },
      { id: 'c', text: '"Maybe this plan asked too much of you. Let\'s set exercise aside and work on something else."', isCorrect: false, rationale: 'Dropping the goal is giving up on the client, which Glasser explicitly cautioned against.' },
      { id: 'd', text: '"Do you still want this? If so, let\'s make a smaller plan you are sure you can carry out."', isCorrect: true, rationale: 'The counselor neither accepts the excuse nor punishes; she checks the want and helps make a simpler, more attainable plan.' },
    ],
    rationale: 'When a plan is not carried out, reality therapists do not accept excuses, do not criticize or punish, and do not give up. Instead they return to the client\'s wants, have the client evaluate what she is doing, and make a new plan that is simple, attainable and within her control (the SAMIC qualities of a good plan).',
    references: [{ source: C, detail: 'Reality Therapy: planning and commitment; no excuses, no punishment, do not give up' }],
  },

  // ------------------------------------------ reflection, paraphrasing and summarizing
  {
    id: 'nce-s-cou-184',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'easy',
    stem: 'A 56-year-old client says, "My son moved across the country for work last month. The house is so quiet now, and I still catch myself setting four places at dinner." Which response is the BEST reflection of feeling?',
    options: [
      { id: 'a', text: '"Your son moved away for work last month, and the house is quieter now."', isCorrect: false, rationale: 'This restates the content of what she said (a paraphrase) but does not name the emotion beneath it.' },
      { id: 'b', text: '"You are feeling a real sense of loss and loneliness with him gone."', isCorrect: true, rationale: 'It identifies the underlying emotions (loss, loneliness) that her words and the image of the extra place setting convey.' },
      { id: 'c', text: '"How often do the two of you talk now that he lives so far away?"', isCorrect: false, rationale: 'A question gathers information and shifts focus to logistics rather than reflecting her feeling.' },
      { id: 'd', text: '"Many parents feel this way at first, and it gets easier with time."', isCorrect: false, rationale: 'Reassurance and normalizing can feel dismissive and do not reflect her specific feeling back to her.' },
    ],
    rationale: 'A reflection of feeling names the emotion the client is expressing, often one implied rather than stated, so the client feels understood and can explore it further. Paraphrasing captures content, questions gather information, and reassurance can cut exploration short.',
    references: [{ source: GL, detail: 'Counseling skills: reflection of feeling versus paraphrasing' }],
  },
  {
    id: 'nce-s-cou-185',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'medium',
    stem: 'A counselor opens the fourth session by saying, "Last week you talked about the tension with your sister, the late nights at work and how little sleep you are getting, and you decided to try leaving the office by six. Where would you like to begin today?" Which skill is the counselor using, and for what purpose?',
    options: [
      { id: 'a', text: 'Paraphrasing, to restate a single message in fresher and shorter words', isCorrect: false, rationale: 'A paraphrase restates one recent client message; this response pulls together material from an entire prior session.' },
      { id: 'b', text: 'Interpretation, to offer a new frame of reference for the client\'s issues', isCorrect: false, rationale: 'The counselor adds no new meaning or explanation; she simply organizes what the client already said.' },
      { id: 'c', text: 'Summarizing, to tie earlier material together and give the session focus', isCorrect: true, rationale: 'Summaries condense several themes over a longer span and are often used to open a session, provide continuity and set direction.' },
      { id: 'd', text: 'Immediacy, to address what is happening in the relationship right now', isCorrect: false, rationale: 'Immediacy concerns the here-and-now counselor-client relationship, which this response does not address.' },
    ],
    rationale: 'Summarizing condenses several client statements, themes or feelings over a longer stretch of time. Counselors use it to begin a session (linking to the last one), to shift topics, to close a session, and to check shared understanding. It differs from paraphrasing in scope, and from interpretation in that it adds no new frame.',
    references: [{ source: GL, detail: 'Counseling skills: summarization and its uses' }],
  },

  // ---------------------------------------------------- confrontation and immediacy
  {
    id: 'nce-s-cou-186',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: 'A client says, "I\'m completely over the breakup," as her eyes fill with tears and she twists a ring on her finger. Which counselor response is the BEST example of a skilled confrontation?',
    options: [
      { id: 'a', text: '"You say you\'re over it, and yet your eyes are filling with tears."', isCorrect: true, rationale: 'It describes the discrepancy between her words and her nonverbal behavior, tentatively and without judgment, and leaves her room to explore it.' },
      { id: 'b', text: '"You clearly are not over it, and denying it will only make things harder."', isCorrect: false, rationale: 'This tells the client what she feels and labels her as denying; it is judgmental and likely to provoke defensiveness.' },
      { id: 'c', text: '"Why are you crying right now if you really are over the breakup?"', isCorrect: false, rationale: '"Why" questions about a discrepancy tend to feel accusatory and invite justification rather than exploration.' },
      { id: 'd', text: '"It sounds like you have worked very hard to move on from this breakup."', isCorrect: false, rationale: 'This supportive reflection ignores the discrepancy entirely, so it is not a confrontation.' },
    ],
    rationale: 'In counseling, confrontation means pointing out a discrepancy (between words and nonverbal behavior, between statements, or between words and actions) in a caring, descriptive way. The "you say ... and yet ..." format names both sides without judgment and invites the client to examine the mixed message. Accusing, interpreting or asking "why" tends to raise defenses.',
    references: [{ source: GL, detail: 'Counseling skills: confrontation of discrepancies' }],
  },
  {
    id: 'nce-s-cou-187',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'hard',
    stem: 'Over six sessions, a client has said repairing his marriage is his top goal, yet he has cancelled each couples appointment he scheduled. The alliance is strong. The counselor gently notes this discrepancy, and the client is quiet, then says, "I guess I\'ve been avoiding it because I\'m afraid she\'ll tell me she wants out." What should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Restate the discrepancy more firmly so that its importance is not lost on him', isCorrect: false, rationale: 'He has already acknowledged the discrepancy; pressing it harder adds pressure without adding understanding.' },
      { id: 'b', text: 'Shift to a lighter topic to ease the tension that the confrontation created', isCorrect: false, rationale: 'Retreating just as he opens up signals that his fear is too much to talk about and loses the opening the confrontation made.' },
      { id: 'c', text: 'Ask him to commit now to attending the next couples appointment he schedules', isCorrect: false, rationale: 'Moving straight to a commitment skips exploration of the fear that drives the avoidance and risks hollow compliance.' },
      { id: 'd', text: 'Reflect his fear and explore what avoiding the sessions has protected him from', isCorrect: true, rationale: 'Following a confrontation, the counselor attends to the client\'s response; he has accepted the discrepancy, so exploring the underlying fear deepens the work.' },
    ],
    rationale: 'A confrontation is only as useful as what follows it. The counselor watches how the client responds (denial, partial acceptance or full recognition) and builds on it. Here the client has recognized the discrepancy and named a fear, so empathic reflection and exploration of that fear come before planning new behavior.',
    references: [{ source: GL, detail: 'Counseling skills: confrontation and evaluating the client\'s response' }],
    reviewNote: 'Applied-skills judgment item; confirm the Gladding locator on confrontation and that "explore before planning" is the clearly best sequencing.',
  },

  // ------------------------------------------------------------ termination skills
  {
    id: 'nce-s-cou-188',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'hard',
    stem: 'A client whose panic attacks resolved months ago has a history of losing caregivers in childhood. Three sessions before a jointly planned ending, she reports two new panic attacks and asks whether she can keep coming "for as long as it takes." What is the BEST response?',
    options: [
      { id: 'a', text: 'Agree to continue open-ended weekly counseling, since her symptoms have now returned', isCorrect: false, rationale: 'Reflexively extending treatment can confirm her fear that she cannot cope without the counselor and skips the meaning of the ending.' },
      { id: 'b', text: 'Explore her feelings about ending, normalize a brief return of symptoms and review gains', isCorrect: true, rationale: 'A temporary return of symptoms near termination is a familiar reaction, especially with a history of loss; processing the ending and her skills is the core task.' },
      { id: 'c', text: 'Keep to the plan and avoid discussing the attacks, so as not to reinforce her symptoms', isCorrect: false, rationale: 'Ignoring the attacks and her feelings about ending leaves important material unprocessed and may feel like another abandonment.' },
      { id: 'd', text: 'Refer her to a new counselor now so that she has ongoing support once the sessions end', isCorrect: false, rationale: 'An abrupt transfer just before ending sidesteps the termination work and offers no reason why a new counselor is needed.' },
    ],
    rationale: 'Termination can stir up feelings of loss, particularly for clients with histories of abandonment, and a temporary regression is common. The counselor normalizes this, explores what ending means to the client, reviews her progress and coping skills, and may adjust the pace (for example, spacing sessions) rather than dropping or reflexively extending the plan.',
    references: [{ source: GL, detail: 'Termination: client reactions and resistance to ending' }],
  },
  {
    id: 'nce-s-cou-189',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'easy',
    stem: 'A client has met his counseling goals. Rather than stopping abruptly, the counselor proposes moving from weekly sessions to sessions every three weeks, followed by a booster session two months later. What is the MAIN purpose of this plan?',
    options: [
      { id: 'a', text: 'To let him practice new skills on his own while support is still available', isCorrect: true, rationale: 'Spacing sessions and adding a booster lets the client rely on himself while the counselor can still help consolidate gains and plan for setbacks.' },
      { id: 'b', text: 'To keep him from forming an unhealthy dependence in the early sessions', isCorrect: false, rationale: 'The plan addresses the end of counseling, not the formation of dependence early in treatment.' },
      { id: 'c', text: 'To meet an ACA requirement that each ending include follow-up sessions', isCorrect: false, rationale: 'The ACA Code of Ethics does not require follow-up sessions for every termination.' },
      { id: 'd', text: 'To delay the ending until he no longer reports any symptoms whatsoever', isCorrect: false, rationale: 'The goals are already met; waiting for a symptom-free state is not the aim of tapering.' },
    ],
    rationale: 'Gradually spacing sessions (fading) and scheduling a booster or follow-up session are common termination practices. They allow the client to test and consolidate new skills independently, give room to address relapse prevention, and make the ending less abrupt.',
    references: [{ source: GL, detail: 'Termination: fading sessions and follow-up' }],
  },

  // ------------------------------------------------------------------- Adlerian
  {
    id: 'nce-s-cou-190',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'medium',
    stem: 'A client reports frequent headaches that keep her home from social events. Her Adlerian counselor asks, "If these headaches went away tomorrow, what would you be doing differently in your life?" What is the PRIMARY purpose of this question?',
    options: [
      { id: 'a', text: 'To help her picture a future with no problem, as in a miracle question', isCorrect: false, rationale: 'The miracle question is a solution-focused technique for building goals; the Adlerian question has a diagnostic aim.' },
      { id: 'b', text: 'To uncover a repressed conflict that is being converted into pain', isCorrect: false, rationale: 'Conversion of repressed conflict is a psychoanalytic formulation, not the purpose Adlerians give this question.' },
      { id: 'c', text: 'To learn whether the symptom serves a purpose, such as avoiding a task', isCorrect: true, rationale: '"The Question" helps the counselor see whether the symptom has a social purpose, such as excusing the client from a life task she fears.' },
      { id: 'd', text: 'To rate how much the headaches interfere with her daily functioning', isCorrect: false, rationale: 'Rating functional impairment is an assessment task; the question is meant to reveal the goal of the symptom.' },
    ],
    rationale: 'Adlerians view symptoms as purposeful. "The Question" (asking what the client would do if the symptom were gone) helps distinguish problems that may be largely physical from those that serve a goal, such as avoiding friendship, work or love tasks. If the answer names something the client is avoiding, the symptom may be safeguarding her from it.',
    references: [{ source: C, detail: 'Adlerian Therapy: "The Question" and the purposeful nature of symptoms' }],
  },
  {
    id: 'nce-s-cou-191',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'Adlerian therapy',
    difficulty: 'hard',
    stem: 'A teacher consults a school counselor about a 9-year-old who tears up classmates\' artwork and makes cruel remarks to the teacher. The teacher says she feels deeply hurt and wonders how a child could treat her this way. Using Dreikurs\'s goals of misbehavior, which goal is the child MOST likely pursuing?',
    options: [
      { id: 'a', text: 'Attention', isCorrect: false, rationale: 'An attention goal typically leaves the adult feeling annoyed or irritated, not hurt.' },
      { id: 'b', text: 'Power', isCorrect: false, rationale: 'A power goal typically leaves the adult feeling angry, provoked or challenged.' },
      { id: 'c', text: 'Display of inadequacy', isCorrect: false, rationale: 'Display of inadequacy leaves the adult feeling hopeless or discouraged as the child gives up.' },
      { id: 'd', text: 'Revenge', isCorrect: true, rationale: 'When adults feel hurt, the child is often seeking revenge, trying to hurt others as he feels hurt.' },
    ],
    rationale: 'Rudolf Dreikurs, who extended Adler\'s ideas to parenting and schools, described four mistaken goals of misbehavior: attention, power, revenge and display of inadequacy. A practical clue is the adult\'s own reaction: annoyance (attention), anger (power), hurt (revenge) and hopelessness (inadequacy). Identifying the goal helps adults stop reinforcing it and encourage the child.',
    references: [{ source: C, detail: 'Adlerian Therapy: Dreikurs and the goals of misbehavior' }],
    reviewNote: 'Dreikurs\'s four goals are standard; confirm that the cited Corey edition covers them (Gladding\'s child/school chapters are an alternative locator).',
  },

  // ----------------------------------------------------------- person-centered
  {
    id: 'nce-s-cou-192',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'medium',
    stem: 'A client sees himself as "a calm person who doesn\'t get angry." When his partner says he shouted during an argument, he insists he was "just being emphatic." In Rogers\'s theory of personality, this BEST illustrates:',
    options: [
      { id: 'a', text: 'Reaction formation against an unacceptable id impulse of anger', isCorrect: false, rationale: 'Reaction formation (expressing the opposite of an impulse) is a Freudian defense rooted in id-superego conflict, not Rogers\'s framework.' },
      { id: 'b', text: 'Distortion of an experience that threatens the self-concept', isCorrect: true, rationale: 'Rogers held that experiences inconsistent with the self-concept are distorted or denied to awareness, maintaining incongruence.' },
      { id: 'c', text: 'Introjection of a parent\'s rules, swallowed whole without question', isCorrect: false, rationale: 'Introjection is a gestalt contact boundary disturbance about uncritically accepting others\' values.' },
      { id: 'd', text: 'Minimization, a cognitive distortion that should be disputed', isCorrect: false, rationale: 'Minimization is a CBT term, and person-centered counselors do not dispute thoughts.' },
    ],
    rationale: 'In Rogers\'s theory, when an experience (here, anger) does not fit the self-concept, the person may perceive it selectively (distortion) or keep it out of awareness entirely (denial). The gap between self-concept and experience is incongruence, which produces vulnerability and anxiety. The core conditions make it safe enough to let such experiences into awareness.',
    references: [{ source: C, detail: 'Person-Centered Therapy: incongruence, distortion and denial' }],
  },
  {
    id: 'nce-s-cou-193',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'person-centered therapy',
    difficulty: 'hard',
    stem: 'A client says, "I suppose I\'m kind of annoyed with my sister, but it\'s not a big deal," while clenching her fist. Which option BEST matches how a person-centered counselor and a gestalt counselor would each MOST likely respond?',
    options: [
      { id: 'a', text: 'Person-centered: reflect the annoyance she is starting to own; gestalt: ask her to give her fist a voice', isCorrect: true, rationale: 'Person-centered counselors follow and empathically reflect the client\'s emerging feeling; gestalt counselors direct attention to present bodily awareness and often invite the client to speak as the body part.' },
      { id: 'b', text: 'Person-centered: ask her to exaggerate the clenched fist; gestalt: reflect the annoyance she now owns', isCorrect: false, rationale: 'The pairing is reversed: exaggeration is a gestalt experiment, and nondirective reflection is person-centered.' },
      { id: 'c', text: 'Person-centered: interpret her anger as displaced; gestalt: dispute her belief that anger is no big deal', isCorrect: false, rationale: 'Interpreting displacement is psychoanalytic and disputing beliefs is REBT; neither fits these two approaches.' },
      { id: 'd', text: 'Person-centered: advise her on how to talk with her sister; gestalt: explore early memories of the sister', isCorrect: false, rationale: 'Person-centered counselors avoid advice, and gestalt work stays with present experience rather than early memories.' },
    ],
    rationale: 'Both approaches are humanistic and value awareness, but they differ in counselor activity. A person-centered counselor stays nondirective, offering empathy so the client can more fully own her feeling. A gestalt counselor is more active, noticing nonverbal behavior and creating experiments, such as giving the fist a voice, to heighten here-and-now awareness.',
    references: [
      { source: C, detail: 'Person-Centered Therapy: empathic reflection and the nondirective stance' },
      { source: C, detail: 'Gestalt Therapy: attending to nonverbal behavior and experiments' },
    ],
  },

  // ------------------------------------------------------------------ existential
  {
    id: 'nce-s-cou-194',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'easy',
    stem: 'A 44-year-old client says, "I have no choice but to stay in a job I hate. My family expects it." Which counselor response is MOST consistent with existential therapy?',
    options: [
      { id: 'a', text: 'Dispute the irrational belief that he must meet his family\'s expectations', isCorrect: false, rationale: 'Disputing "must" beliefs is the core REBT technique, not the existential focus.' },
      { id: 'b', text: 'Explore how his early bond with his father shaped this need to comply', isCorrect: false, rationale: 'Tracing present behavior to early relationships is a psychodynamic focus.' },
      { id: 'c', text: 'Help him see that staying is a choice and explore what it means to him', isCorrect: true, rationale: 'Existential counselors highlight freedom and responsibility, helping clients recognize that they are choosing even when they claim they have no choice.' },
      { id: 'd', text: 'Rehearse assertive statements he can use when his family raises it', isCorrect: false, rationale: 'Assertiveness rehearsal is a behavioral skills intervention.' },
    ],
    rationale: 'Existential therapy holds that people are free and therefore responsible for their choices. Statements such as "I have no choice" are seen as ways of avoiding that responsibility. The counselor helps the client own his choices, face the anxiety that comes with freedom, and decide how he wants to live.',
    references: [{ source: C, detail: 'Existential Therapy: freedom and responsibility' }],
  },
  {
    id: 'nce-s-cou-195',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'existential therapy',
    difficulty: 'hard',
    stem: 'A 67-year-old client recently told his cancer is terminal says, "What\'s the point of anything now?" He is not suicidal. Which counselor response is MOST characteristic of an existential approach rather than a cognitive behavioral one?',
    options: [
      { id: 'a', text: '"What evidence tells you that nothing has a point? Let\'s examine it together."', isCorrect: false, rationale: 'Testing the evidence for a thought is cognitive restructuring, a CBT method.' },
      { id: 'b', text: '"Facing death has you asking what matters. What gives your days meaning now?"', isCorrect: true, rationale: 'The existential counselor treats the question as a genuine confrontation with death and meaning and invites him to explore it.' },
      { id: 'c', text: '"Let\'s schedule a few small, pleasant activities each day to lift your mood."', isCorrect: false, rationale: 'Scheduling pleasant activities is behavioral activation, a CBT strategy for low mood.' },
      { id: 'd', text: '"Tell me about earlier losses in your life that this news is stirring up."', isCorrect: false, rationale: 'Linking present reactions to past losses reflects a psychodynamic focus.' },
    ],
    rationale: 'A CBT counselor might treat "What\'s the point?" as a hopeless automatic thought to test or as low mood to activate. An existential counselor sees it as an authentic encounter with the givens of death and meaninglessness and helps the client search for meaning, values and connection in the time that remains. Yalom argued that facing death honestly can deepen how one lives, and Frankl that meaning can be found even in unavoidable suffering.',
    references: [{ source: C, detail: 'Existential Therapy: death, meaning and the search for meaning' }],
  },

  // --------------------------------------------------------------- behavior therapy
  {
    id: 'nce-s-cou-196',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: 'Two counselors treat clients who fear elevators. One teaches relaxation and works up a ranked list of feared scenes. The other has the client ride an elevator repeatedly for a long session, without leaving, until the anxiety subsides. Which statement accurately contrasts these approaches?',
    options: [
      { id: 'a', text: 'Flooding pairs relaxation with each step; desensitization keeps the client at peak fear', isCorrect: false, rationale: 'This reverses the methods: relaxation pairing belongs to systematic desensitization.' },
      { id: 'b', text: 'Both rely on reciprocal inhibition, but flooding is limited to scenes that are imagined', isCorrect: false, rationale: 'Flooding does not rely on a competing relaxation response, and it can be done in vivo or in imagination.' },
      { id: 'c', text: 'Desensitization blocks escape; flooding lets the client stop at any step of a hierarchy', isCorrect: false, rationale: 'This reverses them: flooding prevents escape, while desensitization moves gradually and lets the client pause.' },
      { id: 'd', text: 'Flooding is intense and blocks escape; desensitization is graded and paired with relaxation', isCorrect: true, rationale: 'Flooding uses prolonged, high-intensity exposure with response prevention; systematic desensitization pairs relaxation with a graded hierarchy.' },
    ],
    rationale: 'Wolpe\'s systematic desensitization uses relaxation training, an anxiety hierarchy and gradual exposure so that relaxation inhibits anxiety. Flooding exposes the client to a highly feared stimulus for a prolonged period, in vivo or imaginal, while preventing escape, so anxiety extinguishes. Flooding often works faster but is more distressing and needs careful informed consent.',
    references: [{ source: C, detail: 'Behavior Therapy: systematic desensitization, in vivo exposure and flooding' }],
  },
  {
    id: 'nce-s-cou-197',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'easy',
    stem: 'A counselor, a 13-year-old and his parents write and sign an agreement: on each school night he finishes his homework by 8 p.m., he earns 30 minutes of video games, and his father will check the work and deliver the reward. Which behavioral technique is this?',
    options: [
      { id: 'a', text: 'Contingency contract', isCorrect: true, rationale: 'A contingency contract is a written agreement that specifies the target behavior, the consequence and who delivers it.' },
      { id: 'b', text: 'Token economy', isCorrect: false, rationale: 'A token economy uses tokens or points later exchanged for backup reinforcers; no tokens are involved here.' },
      { id: 'c', text: 'Response cost', isCorrect: false, rationale: 'Response cost removes a reinforcer after an unwanted behavior; this plan adds a reward for a wanted one.' },
      { id: 'd', text: 'Covert sensitization', isCorrect: false, rationale: 'Covert sensitization pairs an unwanted behavior with an imagined aversive event.' },
    ],
    rationale: 'Contingency contracts make the "if-then" relationship between behavior and consequence explicit. Effective contracts define the behavior in observable terms, specify the reinforcer, name who monitors and delivers it, and are agreed to by everyone involved, which increases the client\'s sense of ownership.',
    references: [{ source: C, detail: 'Behavior Therapy: operant techniques and contingency contracts' }],
  },

  // ----------------------------------------------------- cognitive behavioral therapy
  {
    id: 'nce-s-cou-198',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: 'A client says, "My boss walked right past me this morning without saying hello. I\'m going to get fired." Which counselor response BEST illustrates Socratic questioning?',
    options: [
      { id: 'a', text: '"Your boss was probably just busy, so I really doubt you will be fired."', isCorrect: false, rationale: 'Reassurance supplies the counselor\'s conclusion instead of helping the client examine the thought himself.' },
      { id: 'b', text: '"That is catastrophizing, so try replacing it with a positive thought."', isCorrect: false, rationale: 'Labeling the distortion and prescribing a replacement is didactic, not guided discovery.' },
      { id: 'c', text: '"What are some other reasons your boss might have walked past you?"', isCorrect: true, rationale: 'The open question guides the client to generate alternative explanations and weigh the evidence for himself.' },
      { id: 'd', text: '"How did you feel in that moment when your boss walked past you?"', isCorrect: false, rationale: 'Exploring the feeling is useful but does not question the accuracy of the automatic thought.' },
    ],
    rationale: 'Socratic questioning, central to Beck\'s guided discovery, uses open questions to help clients examine evidence, consider alternative explanations and reach their own conclusions about a thought. Counselor-supplied reassurance or labeling may be accurate but tends to be less persuasive than conclusions the client reaches.',
    references: [{ source: C, detail: 'Cognitive Behavior Therapy: Beck\'s Socratic dialogue and guided discovery' }],
  },
  {
    id: 'nce-s-cou-199',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'medium',
    stem: 'A client with depression says she used to love her pottery class and will start going again "once I feel more motivated." Which response BEST reflects behavioral activation?',
    options: [
      { id: 'a', text: 'Agree to wait until her mood lifts, since pushing activity now could set her up to fail', isCorrect: false, rationale: 'Behavioral activation holds that waiting for motivation keeps clients stuck; action is expected to come first.' },
      { id: 'b', text: 'Schedule a pottery session this week and rate her mood and mastery after it', isCorrect: true, rationale: 'BA works "outside-in": the client schedules valued activity according to a plan, not a mood, and tracks its effects.' },
      { id: 'c', text: 'First identify and dispute the core belief that is behind her lack of motivation', isCorrect: false, rationale: 'Disputing core beliefs is cognitive restructuring; BA targets behavior and avoidance directly.' },
      { id: 'd', text: 'Explore the earlier losses that may account for her loss of interest in pottery', isCorrect: false, rationale: 'Exploring past losses reflects a psychodynamic focus rather than activation.' },
    ],
    rationale: 'Behavioral activation treats depression by reducing avoidance and increasing contact with rewarding, valued activities. Clients monitor activities and mood, then schedule specific activities according to a plan rather than waiting to feel like it, often rating pleasure and mastery. Motivation tends to follow action rather than precede it.',
    references: [{ source: 'APA CPG', detail: 'Depression guideline (2019): behavioral therapy, including behavioral activation' }],
  },
  {
    id: 'nce-s-cou-200',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'cognitive behavioral therapy',
    difficulty: 'easy',
    stem: 'On a thought record, a client has written the situation, her automatic thought ("Everyone at the party thought I was boring") and her emotion (embarrassment, 85%). What does a cognitive therapy thought record typically ask her to do NEXT?',
    options: [
      { id: 'a', text: 'Trace the thought back to the childhood memory that first produced it', isCorrect: false, rationale: 'Finding the childhood origin of a thought is not the next step of a thought record.' },
      { id: 'b', text: 'Repeat a positive affirmation until the thought no longer feels true', isCorrect: false, rationale: 'Affirmations replace the thought without examining it, which is not cognitive restructuring.' },
      { id: 'c', text: 'Describe the thought in more detail without judging if it is accurate', isCorrect: false, rationale: 'Noticing thoughts without evaluating them is closer to mindfulness or defusion than to a thought record.' },
      { id: 'd', text: 'Weigh the evidence and write a more balanced, alternative response', isCorrect: true, rationale: 'Thought records move from identifying the thought to evaluating it and writing an adaptive response, then re-rating the emotion.' },
    ],
    rationale: 'A thought record structures cognitive restructuring: situation, automatic thought, emotion and its intensity, then evaluation of the thought (evidence for and against, alternative explanations) leading to a balanced or adaptive response, and finally a re-rating of the emotion. It teaches clients to treat thoughts as hypotheses rather than facts.',
    references: [{ source: C, detail: 'Cognitive Behavior Therapy: Beck\'s cognitive therapy and recording automatic thoughts' }],
  },

  // ---------------------------------------------- psychodynamic and psychoanalytic theory
  {
    id: 'nce-s-cou-201',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'easy',
    stem: 'Freud called it the "fundamental rule" of psychoanalysis: the client reports whatever comes to mind, however trivial, illogical or embarrassing it seems, without censoring it. This technique is called:',
    options: [
      { id: 'a', text: 'Free association', isCorrect: true, rationale: 'Free association asks the client to say everything that comes to mind, opening a path to unconscious material.' },
      { id: 'b', text: 'Dream analysis', isCorrect: false, rationale: 'Dream analysis interprets the manifest and latent content of dreams; it is a separate technique.' },
      { id: 'c', text: 'Interpretation', isCorrect: false, rationale: 'Interpretation is the analyst\'s explanation of the meaning of material, not the client\'s uncensored reporting.' },
      { id: 'd', text: 'Catharsis', isCorrect: false, rationale: 'Catharsis is the release of pent-up emotion, which may occur but is not the reporting rule itself.' },
    ],
    rationale: 'Free association is the basic method of psychoanalysis. By suspending conscious censorship, the client lets associations lead toward repressed wishes and conflicts. The analyst attends especially to blocks, pauses and changes of topic, which may signal resistance.',
    references: [{ source: C, detail: 'Psychoanalytic Therapy: free association' }],
  },
  {
    id: 'nce-s-cou-202',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'hard',
    stem: 'After gaining the insight that he ends relationships once they become close, a client begins arriving late and "forgets" a session. Weeks later he describes pulling away from a new partner in the same way. From a psychoanalytic perspective, which statement BEST describes what is happening and how to proceed?',
    options: [
      { id: 'a', text: 'The lateness reflects low motivation, so firm attendance rules with consequences should be set', isCorrect: false, rationale: 'Treating the lateness as a compliance problem misses its unconscious meaning, which is the analyst\'s main interest.' },
      { id: 'b', text: 'The repetition shows the insight was wrong, so the original interpretation should be dropped', isCorrect: false, rationale: 'Repetition after insight is expected; it does not by itself show the interpretation was wrong.' },
      { id: 'c', text: 'The lateness is resistance to be explored, and the repeated pattern calls for working through', isCorrect: true, rationale: 'Lateness and forgetting after a painful insight are classic resistance, and insight is consolidated by working through the conflict repeatedly.' },
      { id: 'd', text: 'The relapse shows a need for catharsis, so his feelings should be discharged more fully', isCorrect: false, rationale: 'Emotional discharge alone was abandoned by Freud as a mechanism of lasting change.' },
    ],
    rationale: 'In psychoanalytic therapy, resistance is anything that keeps unconscious material from awareness, such as lateness, missed sessions or changing the subject, and it is interpreted rather than punished. A single insight rarely changes a pattern; working through is the repeated exploration of the same conflict as it appears in many situations and in the transference until change takes hold.',
    references: [{ source: C, detail: 'Psychoanalytic Therapy: interpreting resistance and working through' }],
  },

  // ----------------------------------- family systems theories (Bowen, structural, strategic)
  {
    id: 'nce-s-cou-203',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'hard',
    stem: 'A 40-year-old moved across the country at 20 and has not spoken to his parents in ten years. He says, "I\'ve put all that behind me." His father also stopped speaking to his own family as a young man, and the client\'s marriage now swings between intense closeness and angry distance. How would a Bowenian therapist MOST likely understand and approach this?',
    options: [
      { id: 'a', text: 'His distance shows a high level of differentiation, so therapy should focus only on the marriage', isCorrect: false, rationale: 'For Bowen, physical or emotional distance is not differentiation; cutoff reflects unresolved fusion with the family.' },
      { id: 'b', text: 'The family\'s rigid boundaries should be restructured by having it enact the conflict in session', isCorrect: false, rationale: 'Boundaries and enactments are structural (Minuchin) concepts, not Bowen\'s.' },
      { id: 'c', text: 'The marriage problems call for a paradoxical directive to have the couple fight on purpose', isCorrect: false, rationale: 'Paradoxical directives are a strategic technique; Bowen coaching emphasizes calm, reflective self-work.' },
      { id: 'd', text: 'Cutoff manages unresolved fusion passed down the generations; he would be coached to reconnect', isCorrect: true, rationale: 'Emotional cutoff handles fusion by distance, and its repetition across generations reflects multigenerational transmission; Bowen coaching helps clients re-engage their families while staying differentiated.' },
    ],
    rationale: 'Bowen saw emotional cutoff as a way of managing unresolved attachment by distance, not as a sign of maturity; the fusion tends to reappear in other close relationships, such as a marriage. Multigenerational transmission explains how such patterns and levels of differentiation pass down family lines. Therapy often involves a genogram and coaching the client to make calm, person-to-person contact with family of origin.',
    references: [{ source: G, detail: 'Bowen family systems theory: emotional cutoff and multigenerational transmission process' }],
  },
  {
    id: 'nce-s-cou-204',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: 'In a first session with a family, a counselor lets the father speak first as the family expects, picks up the family\'s own phrases and pace, and follows their story. Afterward she sketches a diagram showing a diffuse boundary between the mother and son and a rigid one around the father. In structural family therapy, these two activities are BEST described as:',
    options: [
      { id: 'a', text: 'Triangulating and then detriangulating the parental subsystem', isCorrect: false, rationale: 'Triangulation and detriangulation are Bowen concepts about drawing in a third person, not this sequence.' },
      { id: 'b', text: 'Joining the family, then mapping its boundaries and subsystems', isCorrect: true, rationale: 'Accommodating to the family\'s style and hierarchy is joining; the boundary diagram is a structural map.' },
      { id: 'c', text: 'Prescribing the symptom, then reframing the family\'s problem', isCorrect: false, rationale: 'Symptom prescription and reframing are strategic techniques, and neither occurs here.' },
      { id: 'd', text: 'Building a genogram to trace patterns across three generations', isCorrect: false, rationale: 'A genogram traces multigenerational patterns (Bowen); a structural map shows current boundaries and alignments.' },
    ],
    rationale: 'Minuchin\'s structural therapist first joins the family, accommodating to its style through maintenance, tracking and mimesis, to become accepted as a leader of the therapeutic system. Family mapping then charts current structure: subsystems, hierarchy and boundaries that are clear, diffuse (enmeshed) or rigid (disengaged), guiding later restructuring interventions.',
    references: [{ source: G, detail: 'Structural family therapy: joining, accommodating and family mapping' }],
  },

  // -------------------------------------------------------- trauma-informed interventions
  {
    id: 'nce-s-cou-205',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'medium',
    stem: 'At intake, a counselor explains to a client with a history of sexual assault what each part of the interview involves and why questions are asked. She lets the client choose where to sit and whether the door stays open, and says she may skip any question. These practices BEST reflect:',
    options: [
      { id: 'a', text: 'Trauma-informed principles of safety, transparency and choice that limit retraumatization', isCorrect: true, rationale: 'Explaining procedures, offering choices and control, and attending to physical safety are core trauma-informed practices.' },
      { id: 'b', text: 'Early exposure to trauma cues so that habituation can begin right from the first session', isCorrect: false, rationale: 'Nothing here exposes the client to trauma cues; the aim is to reduce, not evoke, distress at intake.' },
      { id: 'c', text: 'Analytic neutrality and abstinence so that transference can develop without interference', isCorrect: false, rationale: 'Neutrality and abstinence are psychoanalytic stances and do not describe sharing control with the client.' },
      { id: 'd', text: 'Standardized intake procedures that apply the very same steps to every client at the agency', isCorrect: false, rationale: 'Offering individual choices is the opposite of a rigid, uniform procedure.' },
    ],
    rationale: 'Trauma-informed care assumes that many clients have trauma histories and organizes services to avoid retraumatization. Practices include physical and emotional safety, transparency about what will happen, and collaboration, choice and empowerment, so that clients regain a sense of control that trauma took away.',
    references: [{ source: 'SAMHSA TIP 57', detail: 'Trauma-informed care principles: safety, trustworthiness, choice and avoiding retraumatization' }],
  },
  {
    id: 'nce-s-cou-206',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'trauma-informed interventions',
    difficulty: 'hard',
    stem: 'A veteran with PTSD writes an impact statement about why he thinks a friend died in an ambush and how it changed his beliefs about safety, trust, power, esteem and intimacy. His therapist then helps him identify "stuck points," such as "It was my fault," and examine them with structured worksheets. Which treatment is this?',
    options: [
      { id: 'a', text: 'Prolonged exposure therapy', isCorrect: false, rationale: 'Prolonged exposure (Foa) centers on repeated imaginal and in vivo exposure, not written impact statements and stuck-point worksheets.' },
      { id: 'b', text: 'EMDR', isCorrect: false, rationale: 'EMDR (Shapiro) uses bilateral stimulation while the client holds the memory in mind, within an eight-phase protocol.' },
      { id: 'c', text: 'Cognitive processing therapy', isCorrect: true, rationale: 'CPT (Resick) uses the impact statement, stuck points and worksheets across five themes: safety, trust, power/control, esteem and intimacy.' },
      { id: 'd', text: 'Stress inoculation training', isCorrect: false, rationale: 'Stress inoculation training (Meichenbaum) builds coping skills in three phases; it does not target stuck points.' },
    ],
    rationale: 'Cognitive processing therapy, developed by Patricia Resick, is a trauma-focused cognitive therapy recommended in major PTSD practice guidelines. Clients write an impact statement, identify stuck points (often self-blame or overgeneralized beliefs), and use worksheets to challenge them, with later sessions on safety, trust, power and control, esteem and intimacy.',
    references: [
      { source: 'APA CPG', detail: 'PTSD guideline (2017): cognitive processing therapy' },
      { source: 'VA/DoD CPG', detail: 'PTSD guideline: trauma-focused psychotherapies (CPT, PE, EMDR)' },
    ],
  },

  // ----------------------------------------------------------- crisis intervention models
  {
    id: 'nce-s-cou-207',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'easy',
    stem: 'According to classic crisis theory, which statement BEST describes an acute crisis?',
    options: [
      { id: 'a', text: 'A sign of underlying mental illness that calls for long-term treatment', isCorrect: false, rationale: 'Crisis is viewed as a normal response to an overwhelming event, not evidence of psychopathology.' },
      { id: 'b', text: 'A property of the event, so anyone facing it will be in crisis', isCorrect: false, rationale: 'Crisis depends on the person\'s perception of the event and coping resources; the same event may not cause a crisis for everyone.' },
      { id: 'c', text: 'A chronic state that lasts until the person receives counseling', isCorrect: false, rationale: 'Crisis states are time-limited; a person reaches some new equilibrium with or without help.' },
      { id: 'd', text: 'A time-limited state that resolves within weeks, for better or worse', isCorrect: true, rationale: 'Caplan described crisis as a temporary disequilibrium that usually resolves within about four to six weeks, in an adaptive or maladaptive direction.' },
    ],
    rationale: 'Crisis theory, building on Lindemann and Caplan, holds that a crisis arises when a person perceives an event as overwhelming their usual coping. The state is time-limited, commonly cited as about four to six weeks, and resolves at a higher, equal or lower level of functioning. Because it contains both danger and opportunity, brief, prompt intervention can tip the outcome toward growth.',
    references: [{ source: JG, detail: 'Approaching crisis intervention: definitions of crisis and basic crisis theory' }],
    reviewNote: 'The "four to six weeks" duration is the commonly taught figure from Caplan; confirm wording against the cited James & Gilliland edition.',
  },
  {
    id: 'nce-s-cou-208',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'hard',
    stem: 'Hours after a house fire, a client sits staring at the floor, cannot say where she will sleep tonight, and does not respond to questions about whom she might call. Her triage assessment shows severe impairment. Using James and Gilliland\'s continuum of crisis worker involvement, which stance is MOST appropriate?',
    options: [
      { id: 'a', text: 'Nondirective, letting her generate her own plan so that her sense of control is not taken away', isCorrect: false, rationale: 'A nondirective stance fits clients who are mobile and able to act; she cannot currently generate options.' },
      { id: 'b', text: 'Directive, taking charge to assess safety, give clear guidance and arrange immediate shelter', isCorrect: true, rationale: 'When a client is immobile and severely impaired, the worker becomes directive, taking temporary control to meet urgent needs.' },
      { id: 'c', text: 'Collaborative, working as an equal partner to weigh options that she suggests for the night', isCorrect: false, rationale: 'Collaboration suits clients with partial mobility; she is not yet able to contribute options.' },
      { id: 'd', text: 'Deferred, holding off on any action until a full psychosocial history has been completed', isCorrect: false, rationale: 'Crisis work addresses immediate safety and needs first; a full history is not a prerequisite for action.' },
    ],
    rationale: 'James and Gilliland describe a continuum of worker involvement matched to the client\'s level of mobility, as gauged by triage assessment of affective, behavioral and cognitive functioning. Immobile clients need a directive worker; partially mobile clients, a collaborative one; and mobile clients, a nondirective one. The stance shifts toward less direction as the client regains functioning.',
    references: [{ source: JG, detail: 'Six-step model: directive, collaborative and nondirective involvement; Triage Assessment Form' }],
  },

  // ------------------------------------------------------------ motivational interviewing
  {
    id: 'nce-s-cou-209',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: 'Partway through a session, a court-referred client crosses his arms and says, "You\'re just like my probation officer, always telling me what to do." Which counselor response BEST reflects how motivational interviewing handles discord?',
    options: [
      { id: 'a', text: '"I\'m not telling you what to do. I\'m only giving you the facts here."', isCorrect: false, rationale: 'Defending oneself argues with the client and tends to increase discord.' },
      { id: 'b', text: '"If you don\'t engage here, I will have to report that to your officer."', isCorrect: false, rationale: 'A warning or threat is confrontational and escalates the conflict in the relationship.' },
      { id: 'c', text: '"You\'re tired of being told what to do. Here, the choices are yours."', isCorrect: true, rationale: 'Reflecting his frustration and emphasizing autonomy de-escalates discord without arguing.' },
      { id: 'd', text: '"Let\'s get back to your plan. What will you change before next week?"', isCorrect: false, rationale: 'Pushing ahead ignores the strain in the relationship and is likely to deepen it.' },
    ],
    rationale: 'In current MI, discord refers to tension in the working relationship, distinct from sustain talk about the behavior. Counselors respond without arguing: reflecting, apologizing, affirming or shifting focus, and emphasizing the client\'s autonomy. This replaces the older idea of "rolling with resistance" and keeps the counselor from triggering further defensiveness.',
    references: [{ source: MI, detail: 'Responding to sustain talk and discord; emphasizing autonomy' }],
  },
  {
    id: 'nce-s-cou-210',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'motivational interviewing',
    difficulty: 'medium',
    stem: 'Asked to rate on a 0 to 10 scale how important it is to her to stop vaping, a 19-year-old says, "Maybe a 3." Which follow-up question is MOST likely to elicit change talk?',
    options: [
      { id: 'a', text: '"Why a 3 and not a 1 or a 2?"', isCorrect: true, rationale: 'Asking why the number is not lower invites her to state her own reasons for change, which is change talk.' },
      { id: 'b', text: '"Why only a 3 and not higher?"', isCorrect: false, rationale: 'Asking why the number is not higher invites her to defend the status quo, eliciting sustain talk.' },
      { id: 'c', text: '"What would get you to a 10?"', isCorrect: false, rationale: 'Jumping to the top of the scale is a large leap that tends to bring out reasons it is not possible.' },
      { id: 'd', text: '"Isn\'t a 3 a bit low for you?"', isCorrect: false, rationale: 'This implies judgment and reflects the righting reflex, which tends to provoke defensiveness.' },
    ],
    rationale: 'Importance and confidence rulers are a common MI strategy for evoking change talk. The key follow-up is to ask why the client chose that number rather than a lower one, which prompts her to voice her own reasons for change. Asking why the number is not higher tends to elicit sustain talk instead.',
    references: [{ source: MI, detail: 'Evoking change talk: importance and confidence rulers' }],
  },
];
