// tools/nce/seed/counseling-6.js
// Batch 3: counseling skills, play, attachment, identity, multicultural,
// crisis, group, family, behavior and psychodynamic items (nce-s-cou-151 to 180).
module.exports = [
  {
    id: 'nce-s-cou-151',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'medium',
    stem: "After four sessions on grief, a 58-year-old client leaves a voicemail cancelling her next appointment and saying she 'just doesn't need counseling anymore.' The counselor believes important work remains. What is the BEST response?",
    options: [
      { id: 'a', text: 'Close the file without further contact, since the client has made her choice', isCorrect: false, rationale: 'Respecting autonomy does not require silence; a brief outreach to offer closure and options is good practice.' },
      { id: 'b', text: 'Reach out, invite a closing session to review progress and offer referral options', isCorrect: true, rationale: 'This respects her decision while offering pretermination counseling, a chance to explore her reasons and a path back or elsewhere.' },
      { id: 'c', text: 'Call several times each week until she agrees to resume her regular appointments', isCorrect: false, rationale: 'Repeated pressure disregards client autonomy and could feel coercive.' },
      { id: 'd', text: 'Mail a letter stating that ending now will most likely cause her grief to worsen', isCorrect: false, rationale: 'Predicting harm to persuade her to return is a pressure tactic and is not supported by the facts at hand.' },
    ],
    rationale: 'Clients may end counseling early for many reasons, including satisfaction, cost, discomfort or a rupture in the relationship. The counselor respects the choice but reaches out once to explore the decision, offer a closing session to consolidate gains and provide referrals, leaving the door open to return.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' },
      { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Termination: premature termination initiated by clients' },
    ],
  },
  {
    id: 'nce-s-cou-152',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'easy',
    stem: 'After 12 sessions and several changes in approach, a client with social anxiety shows no measurable improvement, and the client and counselor agree that counseling is not helping. According to the ACA Code of Ethics, what should the counselor do?',
    options: [
      { id: 'a', text: 'Continue the same sessions, since ending now would amount to abandonment', isCorrect: false, rationale: 'Ending a relationship that is not helping, with proper preparation and referral, is not abandonment; continuing without benefit is the concern.' },
      { id: 'b', text: 'End services at the next visit without discussion to avoid more expense', isCorrect: false, rationale: 'An abrupt ending without discussion denies the client pretermination counseling.' },
      { id: 'c', text: "Keep meeting monthly until the client's insurance benefits are used up", isCorrect: false, rationale: 'Continuing only to use available benefits does not serve the client and raises ethical concerns.' },
      { id: 'd', text: 'Provide pretermination counseling and recommend other service providers', isCorrect: true, rationale: 'The Code directs counselors to end services that are not benefiting the client, with pretermination counseling and referral as needed.' },
    ],
    rationale: 'ACA Code A.11.c directs counselors to terminate when it is reasonably apparent that the client no longer needs help, is not likely to benefit or is being harmed. Counselors provide pretermination counseling and recommend other service providers when necessary, so the client leaves with a path to help that may fit better.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' }],
  },
  {
    id: 'nce-s-cou-153',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'termination skills',
    difficulty: 'medium',
    stem: "A school counselor's individual sessions with a 7-year-old will end in three weeks because he has met his goals. Which approach to ending is MOST developmentally appropriate?",
    options: [
      { id: 'a', text: 'Mark the remaining sessions on a calendar together and plan a goodbye ritual', isCorrect: true, rationale: 'Concrete countdowns and a closing ritual give a young child advance notice, predictability and a sense of closure.' },
      { id: 'b', text: 'Tell him at the start of the final session so he has less time to be upset', isCorrect: false, rationale: 'Last-minute notice gives the child no time to prepare and can feel like abandonment.' },
      { id: 'c', text: 'Avoid mentioning the ending and simply stop scheduling him for sessions', isCorrect: false, rationale: 'An unexplained stop leaves the child confused and may feel like rejection.' },
      { id: 'd', text: 'Ask his teacher to explain the ending to him after the last session is over', isCorrect: false, rationale: 'The ending belongs in the relationship; handing it off to someone else after the fact avoids closure.' },
    ],
    rationale: 'Children understand time concretely, so endings are announced several sessions ahead and made visible, for example by counting down sessions on a calendar. A goodbye ritual, such as a drawing, a memory book or a review of what the child learned, honors the relationship and consolidates gains.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: preparing for and ending the relationship' }],
  },
  {
    id: 'nce-s-cou-154',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'hard',
    stem: "A client says, 'I keep picking up extra shifts even though I'm exhausted. My parents gave up everything to bring us to this country.' Which counselor response is the BEST example of a reflection of meaning?",
    options: [
      { id: 'a', text: "You're feeling exhausted and a bit trapped by all the extra shifts you work.", isCorrect: false, rationale: 'This names emotions, which makes it a reflection of feeling rather than of meaning.' },
      { id: 'b', text: "You've been working many extra shifts lately, even though you're worn out.", isCorrect: false, rationale: 'This restates content, which makes it a paraphrase.' },
      { id: 'c', text: 'Working this hard seems to be a way of honoring what your parents sacrificed.', isCorrect: true, rationale: 'This captures the value and purpose that give the behavior its significance for the client, the core of reflecting meaning.' },
      { id: 'd', text: "Perhaps you overwork because part of you fears you'll disappoint your parents.", isCorrect: false, rationale: 'This offers a new, counselor-generated explanation (a hidden fear), which is an interpretation.' },
    ],
    rationale: 'Reflection of meaning, in Ivey\'s microskills, goes beneath content and feeling to the values, purposes and significance a client attaches to experience. It stays close to what the client has implied, whereas interpretation offers a new frame drawn from the counselor\'s perspective.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: reflection of meaning versus interpretation' }],
  },
  {
    id: 'nce-s-cou-155',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'reflection, paraphrasing and summarizing',
    difficulty: 'easy',
    stem: "A client says, 'Between my night classes and my daughter's soccer schedule, I haven't had a free evening in a month.' Which counselor response is the BEST paraphrase?",
    options: [
      { id: 'a', text: 'Your evenings have been taken up by school and family commitments for weeks.', isCorrect: true, rationale: 'This restates the essential content in fresh, concise words, which is what a paraphrase does.' },
      { id: 'b', text: "Between night classes and soccer, you haven't had a free evening in a month.", isCorrect: false, rationale: 'Repeating the client\'s words almost verbatim is parroting, which can sound mechanical.' },
      { id: 'c', text: "You're feeling worn out and maybe resentful that there's no time for you.", isCorrect: false, rationale: 'This focuses on emotion, making it a reflection of feeling.' },
      { id: 'd', text: 'It sounds like you may have trouble saying no when others need something.', isCorrect: false, rationale: 'This adds a counselor hypothesis about the client, which is interpretation.' },
    ],
    rationale: 'A paraphrase restates the content of a client\'s message in the counselor\'s own, usually briefer, words. It shows accurate listening and invites the client to confirm or correct. Verbatim repetition (parroting) adds little and can feel mechanical.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: paraphrasing and the pitfall of parroting' }],
  },
  {
    id: 'nce-s-cou-156',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'confrontation and immediacy',
    difficulty: 'medium',
    stem: 'A client who was open in earlier sessions has arrived late three weeks in a row, answers in single words and avoids looking at the counselor. The counselor senses growing distance between them. Which response BEST demonstrates immediacy?',
    options: [
      { id: 'a', text: "You've been late three times now, and our policy is that sessions can't run over.", isCorrect: false, rationale: 'Stating policy addresses logistics, not what is happening in the relationship.' },
      { id: 'b', text: 'Coming late may be your way of resisting the hard work we have started to do here.', isCorrect: false, rationale: 'This is an interpretation of motive and may increase defensiveness.' },
      { id: 'c', text: "Let's go back to the goals we set in our first session and review your progress.", isCorrect: false, rationale: 'Shifting to goals sidesteps the relational shift the counselor is noticing.' },
      { id: 'd', text: "I'm sensing some distance between us lately, and I wonder what's happening for you.", isCorrect: true, rationale: 'The counselor tentatively names what is occurring between them right now and invites the client to explore it.' },
    ],
    rationale: 'Immediacy is the counselor\'s direct, tentative comment on what is happening in the counseling relationship in the present moment. Used when tension or distance develops, it brings the relationship itself into the conversation so ruptures can be explored and repaired.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling skills: relationship immediacy' }],
  },
  {
    id: 'nce-s-cou-157',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'basic attending and listening skills',
    difficulty: 'medium',
    stem: 'During intake, a client looks down or past the counselor most of the time and moves her chair back slightly when the counselor leans in. She explains that in her family, looking an elder or professional directly in the eye is considered disrespectful. What should the counselor do?',
    options: [
      { id: 'a', text: 'Gently encourage more eye contact to build trust and openness over time', isCorrect: false, rationale: 'This imposes the counselor\'s cultural norm on the client.' },
      { id: 'b', text: "Adjust own eye contact and distance, following the client's comfort cues", isCorrect: true, rationale: 'Attending behaviors are adapted to the client\'s cultural norms for gaze and personal space.' },
      { id: 'c', text: 'Note the gaze avoidance as a possible sign of depression or social anxiety', isCorrect: false, rationale: 'The client has given a cultural explanation; pathologizing it risks misdiagnosis.' },
      { id: 'd', text: 'Lean in closer to show warmth so that she feels more engaged in session', isCorrect: false, rationale: 'She has signaled discomfort with closeness; moving in would ignore her cue.' },
    ],
    rationale: 'Guidelines such as SOLER reflect a particular cultural norm. Comfort with eye contact (kinesics) and conversational distance (proxemics) varies across cultures and individuals, so culturally responsive attending means reading and following the client\'s cues rather than treating one style as the standard.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Nonverbal communication: proxemics and kinesics' }],
  },
  {
    id: 'nce-s-cou-158',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'easy',
    stem: "During child-centered play therapy, a 5-year-old holds up a paintbrush and asks the counselor, 'What color should I make the sky?' Which response BEST fits this approach?",
    options: [
      { id: 'a', text: 'Blue, just like the real sky outside.', isCorrect: false, rationale: 'Answering for the child directs the play and takes away a chance for self-direction.' },
      { id: 'b', text: 'Why do you want me to pick for you?', isCorrect: false, rationale: '"Why" questions ask young children to explain motives and can feel evaluative.' },
      { id: 'c', text: 'In here, you get to decide that.', isCorrect: true, rationale: 'Returning responsibility communicates trust in the child and builds decision-making and self-control.' },
      { id: 'd', text: "Let's paint it together and find out.", isCorrect: false, rationale: 'Joining to share the choice still shifts direction away from the child.' },
    ],
    rationale: 'In child-centered play therapy (Axline, Landreth), the counselor follows the child\'s lead. Key responses include tracking (describing what the child is doing, such as "You\'re putting that one on top") and returning responsibility, which hands decisions back to the child to foster autonomy and self-responsibility.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: child-centered play therapy responses' }],
  },
  {
    id: 'nce-s-cou-159',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'play therapy',
    difficulty: 'medium',
    stem: 'A counselor trains parents to hold weekly 30-minute nondirective play sessions with their own child at home, using reflective listening, tracking and limit setting, while the counselor supervises and gives feedback on their skills. Which approach is this?',
    options: [
      { id: 'a', text: 'Filial therapy', isCorrect: true, rationale: 'Filial therapy, developed by Bernard and Louise Guerney, trains parents as the agents of child-centered play sessions.' },
      { id: 'b', text: 'Theraplay', isCorrect: false, rationale: 'Theraplay (Jernberg) is an adult-led, attachment-based approach using structured, playful engagement, not nondirective play.' },
      { id: 'c', text: 'Parent-child interaction therapy', isCorrect: false, rationale: 'PCIT (Eyberg) coaches parents live, usually by earpiece, and includes a parent-directed discipline phase.' },
      { id: 'd', text: 'Sandplay therapy', isCorrect: false, rationale: 'Sandplay (Kalff, building on Lowenfeld\'s World Technique) is a Jungian method in which the child builds scenes in a sand tray with the therapist.' },
    ],
    rationale: 'Filial therapy treats parents as partners: the counselor teaches child-centered play skills, supervises practice sessions and then helps parents generalize the sessions to home. It aims to strengthen the parent-child relationship as the vehicle of change.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counseling children: filial therapy and sand tray approaches' }],
  },
  {
    id: 'nce-s-cou-160',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'hard',
    reviewNote: 'Confirm Berk 7th ed covers Bartholomew and Horowitz\'s four-category adult model; the model itself is standard.',
    stem: 'A 34-year-old client says he badly wants a close relationship, yet he pulls away whenever someone gets close because he expects to be hurt and doubts that he deserves love. In Bartholomew and Horowitz\'s four-category model of adult attachment, which style BEST fits?',
    options: [
      { id: 'a', text: 'Preoccupied', isCorrect: false, rationale: 'Preoccupied adults see themselves negatively but others positively, so they pursue closeness anxiously rather than withdraw.' },
      { id: 'b', text: 'Dismissing-avoidant', isCorrect: false, rationale: 'Dismissing adults view themselves positively and downplay any wish for closeness.' },
      { id: 'c', text: 'Secure', isCorrect: false, rationale: 'Secure adults hold positive views of self and others and are comfortable with intimacy.' },
      { id: 'd', text: 'Fearful-avoidant', isCorrect: true, rationale: 'He wants closeness but avoids it, with negative views of both himself and others.' },
    ],
    rationale: 'Bartholomew and Horowitz crossed a model of self (worthy or unworthy) with a model of others (trustworthy or not). Secure is positive-positive, preoccupied is negative self and positive other, dismissing is positive self and negative other, and fearful is negative on both, producing a desire for closeness alongside avoidance.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Early adulthood: adult attachment styles and intimate relationships' }],
  },
  {
    id: 'nce-s-cou-161',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'attachment theory',
    difficulty: 'easy',
    stem: 'Bowlby proposed that through repeated experiences with caregivers, a child builds mental representations of whether others are dependable and whether the self is worthy of care, which then guide expectations in later relationships. What did Bowlby call these representations?',
    options: [
      { id: 'a', text: 'Secure base', isCorrect: false, rationale: 'A secure base (emphasized by Ainsworth) is the caregiver from whom a child explores, not the mental representation itself.' },
      { id: 'b', text: 'Internal working models', isCorrect: true, rationale: 'Bowlby\'s internal working models are expectations about self and others built from early caregiving.' },
      { id: 'c', text: 'Object constancy', isCorrect: false, rationale: 'Object constancy is Mahler\'s term for holding a stable inner image of the caregiver.' },
      { id: 'd', text: 'Cognitive schemas', isCorrect: false, rationale: 'Schemas are Piaget\'s and Beck\'s terms for organized knowledge or core beliefs, not Bowlby\'s attachment concept.' },
    ],
    rationale: 'Bowlby argued that attachment experiences are internalized as working models of self and others. These models operate largely outside awareness and shape how a person seeks support, interprets others\' behavior and forms close relationships later in life.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Bowlby\'s ethological theory of attachment: internal working model' }],
  },
  {
    id: 'nce-s-cou-162',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'hard',
    stem: 'For two years a Korean American graduate student rejected anything she saw as White culture and worked only within Asian American groups. Lately she feels uneasy with that rigid stance, wonders whether it limits her personal autonomy and is sorting out which values are truly her own. In the Racial/Cultural Identity Development (R/CID) model, she is MOST likely in which stage?',
    options: [
      { id: 'a', text: 'Dissonance', isCorrect: false, rationale: 'Dissonance is the earlier stage in which experiences first challenge a conforming, majority-oriented view.' },
      { id: 'b', text: 'Resistance and immersion', isCorrect: false, rationale: 'This describes her previous two years of rejecting the dominant culture and endorsing her own group.' },
      { id: 'c', text: 'Introspection', isCorrect: true, rationale: 'Discomfort with rigid group views and a search for personal autonomy mark the introspection stage.' },
      { id: 'd', text: 'Integrative awareness', isCorrect: false, rationale: 'Integrative awareness reflects a secure, flexible identity that she is still working toward.' },
    ],
    rationale: 'The R/CID model (Atkinson, Morten and Sue, expanded by Sue and Sue) describes five stages: conformity, dissonance, resistance and immersion, introspection and integrative awareness. Introspection follows immersion, as the person questions rigid loyalty to the group and works out an individual identity.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Racial/Cultural Identity Development (R/CID) model' }],
  },
  {
    id: 'nce-s-cou-163',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'racial and cultural identity models',
    difficulty: 'medium',
    stem: "After a classmate's remark about her family's background, a 15-year-old Mexican American student begins asking her grandparents about their lives in Mexico, joins a Latinx student club and reads Chicano history, though she has not settled what her heritage means to her. In Phinney's model of ethnic identity, she is in which stage?",
    options: [
      { id: 'a', text: 'Ethnic identity search (moratorium)', isCorrect: true, rationale: 'Active exploration of heritage, often prompted by an encounter, without firm commitment marks the search stage.' },
      { id: 'b', text: 'Unexamined ethnic identity', isCorrect: false, rationale: 'This first stage involves little interest in or exploration of ethnicity; she is now actively exploring.' },
      { id: 'c', text: 'Achieved ethnic identity', isCorrect: false, rationale: 'Achievement requires a secure, committed sense of what ethnicity means, which she has not yet reached.' },
      { id: 'd', text: 'Integrative awareness', isCorrect: false, rationale: 'Integrative awareness is the final stage of the R/CID model, not part of Phinney\'s model.' },
    ],
    rationale: 'Phinney applied Marcia\'s identity statuses to ethnicity: an unexamined identity (diffuse or foreclosed), an ethnic identity search or moratorium often sparked by a significant experience, and an achieved identity marked by clarity and commitment. Exploration supported by family and community fosters well-being.',
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Adolescence: ethnic identity (Phinney)' }],
  },
  {
    id: 'nce-s-cou-164',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: 'A counselor who holds several privileged identities is working with a client from a marginalized racial and religious group. She sets aside time to explore with the client how their differences in power and privilege affect trust, communication and the work they are doing together. In the MSJCC, this falls MOST directly within which developmental domain?',
    options: [
      { id: 'a', text: 'Counselor self-awareness', isCorrect: false, rationale: 'Self-awareness concerns the counselor\'s own identities and biases; here the focus is how the two identities interact.' },
      { id: 'b', text: 'Counseling relationship', isCorrect: true, rationale: 'This domain addresses how privileged and marginalized statuses of counselor and client shape the relationship.' },
      { id: 'c', text: 'Client worldview', isCorrect: false, rationale: 'Client worldview concerns understanding the client\'s identities, values and experiences of oppression.' },
      { id: 'd', text: 'Counseling and advocacy interventions', isCorrect: false, rationale: 'This domain covers intervening at individual through international levels, not exploring the dyad itself.' },
    ],
    rationale: 'The MSJCC places the counselor-client pair in one of four quadrants defined by privileged and marginalized statuses. It then describes four developmental domains: counselor self-awareness, client worldview, the counseling relationship, and counseling and advocacy interventions, with attitudes and beliefs, knowledge, skills and action (AKSA) within each.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Quadrants and developmental domains: the counseling relationship' }],
  },
  {
    id: 'nce-s-cou-165',
    domain: 'counseling',
    cacrep: 'social_cultural',
    topic: 'multicultural counseling competencies',
    difficulty: 'medium',
    stem: "An older counseling text lists ataque de nervios as a 'culture-bound syndrome.' DSM-5-TR uses a broader term that includes cultural syndromes, cultural idioms of distress and cultural explanations or perceived causes. What is that term?",
    options: [
      { id: 'a', text: 'Culture-specific disorders', isCorrect: false, rationale: 'DSM-5-TR moved away from framing these patterns as disorders tied to one culture.' },
      { id: 'b', text: 'Atypical presentations', isCorrect: false, rationale: 'This implies a deviation from a supposedly typical norm, the view the newer framework rejects.' },
      { id: 'c', text: 'Ethnic variant syndromes', isCorrect: false, rationale: 'This is not a DSM-5-TR term.' },
      { id: 'd', text: 'Cultural concepts of distress', isCorrect: true, rationale: 'DSM-5-TR groups cultural syndromes, idioms of distress and explanations under cultural concepts of distress.' },
    ],
    rationale: 'DSM-5-TR replaced "culture-bound syndromes" with cultural concepts of distress, recognizing that all distress is culturally shaped and that these concepts may not map onto a single DSM disorder. The Cultural Formulation Interview helps counselors explore the client\'s own understanding of the problem.',
    references: [{ source: 'DSM-5-TR', detail: 'Section III: Culture and Psychiatric Diagnosis, cultural concepts of distress' }],
  },
  {
    id: 'nce-s-cou-166',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'easy',
    stem: "Using James and Gilliland's six-step model of crisis intervention, a counselor has defined the problem from the client's point of view, ensured the client's safety and provided support. What is the counselor's NEXT step?",
    options: [
      { id: 'a', text: 'Obtain commitment to a plan', isCorrect: false, rationale: 'Obtaining commitment is the sixth and final step.' },
      { id: 'b', text: 'Make a concrete plan', isCorrect: false, rationale: 'Making plans is the fifth step, after alternatives are explored.' },
      { id: 'c', text: 'Examine alternatives', isCorrect: true, rationale: 'The fourth step is exploring options, supports and coping mechanisms with the client.' },
      { id: 'd', text: 'Complete a full diagnosis', isCorrect: false, rationale: 'Formal diagnosis is not a step in the model; assessment runs throughout.' },
    ],
    rationale: 'James and Gilliland\'s model has three listening steps (define the problem, ensure client safety, provide support) followed by three acting steps (examine alternatives, make plans, obtain commitment). Assessment of the client\'s state and safety continues throughout all six steps.',
    references: [{ source: 'James & Gilliland (Crisis Intervention Strategies)', detail: 'Six-step model: define the problem, ensure safety, provide support, examine alternatives, make plans, obtain commitment' }],
  },
  {
    id: 'nce-s-cou-167',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'crisis intervention models',
    difficulty: 'hard',
    stem: "In Kanel's ABC model of crisis intervention, a counselor first builds rapport through attending and reflection. The counselor then identifies the precipitating event, the client's perception of it and the resulting distress and impaired functioning. What is this second phase called?",
    options: [
      { id: 'a', text: 'Boiling down the problem', isCorrect: true, rationale: 'The B phase narrows the focus to the trigger, the client\'s perception and the subjective distress.' },
      { id: 'b', text: 'Coping', isCorrect: false, rationale: 'Coping is the C phase, which follows and focuses on current and new coping strategies.' },
      { id: 'c', text: 'Achieving contact', isCorrect: false, rationale: 'Achieving contact is the A phase, the rapport building described first in the stem.' },
      { id: 'd', text: 'Brief safety planning', isCorrect: false, rationale: 'Safety is assessed throughout but is not the name of a phase in the ABC model.' },
    ],
    rationale: 'Kanel\'s ABC model has three phases: A, achieving (developing and maintaining) contact; B, boiling down the problem by identifying the precipitating event, perceptions and distress; and C, coping, in which the counselor explores past and new coping and builds a plan. Its focus on perception reflects the view that crises arise from how events are interpreted.',
    references: [{ source: 'Kanel (A Guide to Crisis Intervention)', detail: 'ABC model: A, achieving contact; B, boiling down the problem; C, coping' }],
  },
  {
    id: 'nce-s-cou-168',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: "Before launching a support group at a refugee resettlement agency, a counselor studies the community's needs, the agency's resources and support, and cultural attitudes toward discussing personal problems in a group. In the ASGW Best Practice Guidelines, this planning task is called:",
    options: [
      { id: 'a', text: 'Pre-group screening', isCorrect: false, rationale: 'Screening assesses individual prospective members, not the community and organizational context.' },
      { id: 'b', text: 'Ecological assessment', isCorrect: true, rationale: 'ASGW asks group workers to assess the community, agency and cultural context before forming a group.' },
      { id: 'c', text: 'Professional disclosure', isCorrect: false, rationale: 'Professional disclosure informs members about the leader and the group; it is not a needs assessment.' },
      { id: 'd', text: 'Group processing', isCorrect: false, rationale: 'Processing is the later, ongoing reflection on what happens in sessions.' },
    ],
    rationale: 'The ASGW Best Practice Guidelines organize group work into planning, performing and group processing. In planning, an ecological assessment of community needs, organizational support and cultural factors guides whether and how a group is offered. Processing, by contrast, means regular reflection on sessions with co-leaders, members or supervisors.',
    references: [{ source: 'ASGW Best Practice Guidelines', detail: 'Best Practice in Planning: ecological assessment' }],
  },
  {
    id: 'nce-s-cou-169',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'The T-group (training group), first developed at the National Training Laboratories in Bethel, Maine, used here-and-now feedback to teach human relations skills. Whose field theory and group dynamics research led to this movement?',
    options: [
      { id: 'a', text: 'Carl Rogers', isCorrect: false, rationale: 'Rogers developed the basic encounter group, which grew alongside but separately from T-groups.' },
      { id: 'b', text: 'Jacob Moreno', isCorrect: false, rationale: 'Moreno developed psychodrama and is credited with coining the term group therapy.' },
      { id: 'c', text: 'Joseph Pratt', isCorrect: false, rationale: 'Pratt led early educational "classes" for patients with tuberculosis in the early 1900s.' },
      { id: 'd', text: 'Kurt Lewin', isCorrect: true, rationale: 'Lewin\'s field theory and group dynamics work led his colleagues to found NTL and the T-group.' },
    ],
    rationale: 'Kurt Lewin studied how group forces shape individual behavior. His work led to the National Training Laboratories in 1947, where T-groups used here-and-now feedback to build interpersonal awareness. Rogers later extended the experiential group into the encounter group movement.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'History of group work: Lewin, T-groups and encounter groups' }],
  },
  {
    id: 'nce-s-cou-170',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'easy',
    stem: 'A counselor suggests that a recently widowed client try a community bereavement group run by and for people who have lost a spouse, with no professional leader. Compared with a counseling or therapy group, what BEST characterizes this kind of group?',
    options: [
      { id: 'a', text: 'It uses a professional leader trained to treat diagnosable mental disorders', isCorrect: false, rationale: 'This describes a psychotherapy group, not a peer-run group.' },
      { id: 'b', text: 'It follows a strict time-limited format with formal screening of all members', isCorrect: false, rationale: 'Mutual-aid groups are usually open and ongoing, without formal clinical screening.' },
      { id: 'c', text: 'It is peer-led, with members who share a concern offering one another support', isCorrect: true, rationale: 'Self-help and mutual-aid groups are led by members who share the problem and help one another.' },
      { id: 'd', text: 'It focuses mainly on reshaping personality through deep insight and analysis', isCorrect: false, rationale: 'Reconstructive personality change is a goal of some long-term therapy groups, not of mutual-aid groups.' },
    ],
    rationale: 'Self-help and mutual-aid groups, such as Alcoholics Anonymous or widow-to-widow programs, are organized around a shared concern and led by members rather than professionals. They emphasize support, hope, universality and practical help, and they can complement rather than replace professional counseling.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Group work: self-help and mutual-aid groups' }],
  },
  {
    id: 'nce-s-cou-171',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: "A 15-year-old in a court-mandated anger management group sits with his hood up and says, 'I'm only here because the judge made me.' What is the leader's BEST initial response?",
    options: [
      { id: 'a', text: 'Acknowledge he did not choose to come and invite him to say how that feels', isCorrect: true, rationale: 'Openly naming involuntary status respects his autonomy and turns resistance into material for the group.' },
      { id: 'b', text: 'Explain that members who do not take part may be reported back to the court', isCorrect: false, rationale: 'Leading with threats reinforces the power struggle and deepens resistance.' },
      { id: 'c', text: 'Ask the other members to persuade him that the group will really help him', isCorrect: false, rationale: 'Recruiting peers to convince him puts him on the spot and can feel like ganging up.' },
      { id: 'd', text: 'Ignore the remark and move on so he gets no attention for his resistance', isCorrect: false, rationale: 'Ignoring a direct statement misses a chance to engage him and may model avoidance.' },
    ],
    rationale: 'Adolescents, and especially involuntary members, often test leaders and guard their autonomy. Acknowledging their reluctance openly, respecting choices about what to disclose and inviting them to talk about being sent helps build trust and often reduces resistance more than pressure or avoidance.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Group work with adolescents and involuntary members' }],
  },
  {
    id: 'nce-s-cou-172',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group stages and dynamics',
    difficulty: 'medium',
    stem: "In the ninth session of a cohesive interpersonal group, Malik tells Rosa that her advice-giving feels 'preachy,' and Rosa responds sharply. The room goes quiet. What should the leader do?",
    options: [
      { id: 'a', text: 'Move on to a new topic to protect the cohesion the group has built so far', isCorrect: false, rationale: 'Avoiding conflict teaches members that strong feelings are unsafe and wastes useful material.' },
      { id: 'b', text: 'Help both speak directly to each other and explore what the exchange stirs up', isCorrect: true, rationale: 'Keeping the conflict in the here-and-now with direct communication makes it a source of learning.' },
      { id: 'c', text: 'Ask Malik and Rosa to work out their disagreement privately after the session', isCorrect: false, rationale: 'Moving conflict outside the group fosters subgrouping and removes it from shared work.' },
      { id: 'd', text: "Point out that Malik's feedback was too harsh and ask him to rephrase it now", isCorrect: false, rationale: 'Taking sides shuts down exploration and positions the leader as judge.' },
    ],
    rationale: 'Yalom notes that conflict is inevitable and, in a cohesive group, can be highly productive. The leader keeps it in the here-and-now, encourages members to speak directly and own their reactions, and helps the group examine what the exchange reveals about each person\'s interpersonal patterns.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Conflict in the therapy group (the advanced group)' }],
  },
  {
    id: 'nce-s-cou-173',
    domain: 'counseling',
    cacrep: 'group',
    topic: 'group leadership skills and therapeutic factors',
    difficulty: 'medium',
    stem: "A member describes feeling ignored at family dinners. The leader asks her, 'Is there anyone in this room who you feel might be ignoring you right now?' In Yalom's two-tiered approach to the here-and-now, this question is an example of:",
    options: [
      { id: 'a', text: 'Process illumination', isCorrect: false, rationale: 'Illumination is the second tier, in which the group reflects on and makes sense of what has happened.' },
      { id: 'b', text: 'Universality', isCorrect: false, rationale: 'Universality is a therapeutic factor, the relief of learning others share one\'s problems.' },
      { id: 'c', text: 'Catharsis', isCorrect: false, rationale: 'Catharsis is the expression of strong emotion, not a leader technique for shifting focus.' },
      { id: 'd', text: 'Here-and-now activation', isCorrect: true, rationale: 'Steering an outside concern into members\' relationships in the room is the first, activating tier.' },
    ],
    rationale: 'Yalom describes two tiers of here-and-now work. The leader first activates the here-and-now by moving the focus from outside, past events to members\' reactions to one another in the room. The leader then illuminates the process, helping members reflect on and understand what just occurred; activation without illumination yields emotion without learning.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Ch. 6: The here-and-now, activation and illumination of process' }],
  },
  {
    id: 'nce-s-cou-174',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: "A 9-year-old's frequent stomachaches keep his worried mother home from work. A therapist directs the boy to pretend to have a stomachache at set times and the mother to pretend to comfort him, turning the symptom into play while the mother takes back her caretaking role. This technique is MOST closely associated with:",
    options: [
      { id: 'a', text: 'Salvador Minuchin', isCorrect: false, rationale: 'Minuchin\'s structural therapy uses enactments, joining and boundary making rather than pretend directives.' },
      { id: 'b', text: 'Murray Bowen', isCorrect: false, rationale: 'Bowen emphasized differentiation, triangles and genograms, with the therapist as a calm coach.' },
      { id: 'c', text: 'Cloé Madanes', isCorrect: true, rationale: 'Madanes developed pretend techniques within strategic family therapy.' },
      { id: 'd', text: 'Virginia Satir', isCorrect: false, rationale: 'Satir\'s experiential approach focuses on communication stances, self-esteem and sculpting.' },
    ],
    rationale: 'Madanes viewed some children\'s symptoms as attempts to help a parent that also upset the family hierarchy. Pretend techniques ask the child to pretend to have the symptom and the parent to pretend to help, making the symptom voluntary and playful so it loses its function and the parent resumes an appropriate caregiving role.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Strategic family therapy: Madanes and pretend techniques' }],
  },
  {
    id: 'nce-s-cou-175',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'medium',
    stem: "In a group setting, a guide uses a client's family chronology to have members role-play scenes from the lives of the client's parents and grandparents, helping the client see them as people and let go of old learnings. This experiential technique, developed by Virginia Satir, is called:",
    options: [
      { id: 'a', text: 'Family reconstruction', isCorrect: true, rationale: 'Satir\'s family reconstruction re-enacts multigenerational scenes to free the "star" from outdated patterns.' },
      { id: 'b', text: 'Psychodrama', isCorrect: false, rationale: 'Psychodrama, created by Jacob Moreno, uses role-play but is not Satir\'s multigenerational technique.' },
      { id: 'c', text: 'Family sculpting', isCorrect: false, rationale: 'Sculpting arranges members in a physical tableau of present relationships rather than re-enacting family history.' },
      { id: 'd', text: 'Genogram construction', isCorrect: false, rationale: 'A genogram maps multigenerational patterns on paper (associated with Bowen) and does not involve role-play.' },
    ],
    rationale: 'Satir\'s family reconstruction guides a "star" through key events in three generations, using a family chronology and role players. Family sculpting, also used by Satir and by Duhl and Kantor, positions members physically to show closeness, distance and power. Both are experiential techniques that make family patterns visible and felt.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Experiential family therapy: Satir, family reconstruction and sculpting' }],
  },
  {
    id: 'nce-s-cou-176',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'family systems theories (Bowen, structural, strategic)',
    difficulty: 'hard',
    stem: 'Parents of a 14-year-old have grounded him for longer and longer periods for breaking curfew, with no effect. In MRI brief therapy terms, which outcome would represent second-order change?',
    options: [
      { id: 'a', text: 'The parents extend the grounding from one week to a full month', isCorrect: false, rationale: 'More of the same solution is first-order change in degree, not in kind.' },
      { id: 'b', text: 'The family changes the rules governing how curfew is set and handled', isCorrect: true, rationale: 'Altering the rules of the system itself is second-order change.' },
      { id: 'c', text: 'The parents add the loss of his phone to the grounding as a penalty', isCorrect: false, rationale: 'Adding another penalty stays within the same punitive pattern, so it is first-order.' },
      { id: 'd', text: 'The parents keep the same rules but enforce them more strictly', isCorrect: false, rationale: 'Stricter enforcement of unchanged rules is a first-order adjustment.' },
    ],
    rationale: 'Watzlawick, Weakland and Fisch distinguished first-order change, a change within a system whose rules stay the same, from second-order change, a change in the system\'s rules or structure. MRI therapists look for interventions such as reframing that interrupt "more of the same" attempted solutions.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'MRI interactional view: first-order and second-order change' }],
  },
  {
    id: 'nce-s-cou-177',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'medium',
    stem: "Parents decide to stop going into their 3-year-old's room when she cries at bedtime. On the second and third nights, her crying becomes louder and lasts longer than before. How should the counselor explain this?",
    options: [
      { id: 'a', text: 'Spontaneous recovery; the plan has failed and should be stopped now', isCorrect: false, rationale: 'Spontaneous recovery is the return of a behavior after extinction appeared complete; the plan has not failed.' },
      { id: 'b', text: 'Negative reinforcement; her crying is being made stronger by them', isCorrect: false, rationale: 'Nothing aversive is being removed after crying, so this is not negative reinforcement.' },
      { id: 'c', text: 'Punishment; ignoring the crying is causing her new emotional harm', isCorrect: false, rationale: 'Withholding attention is extinction, not punishment, and the increase is predictable.' },
      { id: 'd', text: 'Extinction burst; it is expected and fades if parents stay consistent', isCorrect: true, rationale: 'A temporary surge in a behavior when reinforcement stops is an extinction burst.' },
    ],
    rationale: 'When a previously reinforced behavior no longer produces its reinforcer, it often increases in frequency or intensity before declining, a pattern called an extinction burst. If caregivers give in during the burst, they reinforce a more intense version of the behavior on an intermittent schedule, so consistency is essential.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: operant extinction and the extinction burst' }],
  },
  {
    id: 'nce-s-cou-178',
    domain: 'counseling',
    cacrep: 'helping_relationships',
    topic: 'behavior therapy',
    difficulty: 'hard',
    stem: "To reduce a child's hand-biting, a behavior analyst delivers a token at the end of every 10-minute interval in which no hand-biting occurs, regardless of what else the child is doing. Which procedure is this?",
    options: [
      { id: 'a', text: 'DRA (alternative behavior)', isCorrect: false, rationale: 'DRA reinforces a specific replacement behavior, such as asking for help, rather than mere absence of the target.' },
      { id: 'b', text: 'DRL (low rates of behavior)', isCorrect: false, rationale: 'DRL reinforces the target behavior when it occurs at or below a set rate, for behaviors to reduce but not eliminate.' },
      { id: 'c', text: 'DRO (other behavior)', isCorrect: true, rationale: 'DRO reinforces the absence of the target behavior over an interval.' },
      { id: 'd', text: 'Premack principle', isCorrect: false, rationale: 'The Premack principle uses a high-probability activity to reinforce a low-probability one.' },
    ],
    rationale: 'Differential reinforcement of other behavior (DRO) delivers reinforcement when the target behavior has not occurred for a set interval, sometimes called differential reinforcement of zero rates. DRA reinforces a specified alternative behavior, DRI an incompatible one and DRL a low rate of the target itself.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Behavior therapy: differential reinforcement procedures' }],
  },
  {
    id: 'nce-s-cou-179',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'medium',
    stem: 'An 18-month-old who recently toddled off happily to explore now repeatedly returns to his mother, shadows her, wants her to share each discovery and becomes upset when she leaves, yet sometimes pushes her away. In Mahler\'s separation-individuation theory, he is in which subphase?',
    options: [
      { id: 'a', text: 'Rapprochement', isCorrect: true, rationale: 'Around 16 to 24 months, awareness of separateness brings renewed clinging alongside a push for autonomy.' },
      { id: 'b', text: 'Practicing', isCorrect: false, rationale: 'Practicing (about 10 to 16 months) is the earlier, exhilarated period of exploring with little concern for the mother.' },
      { id: 'c', text: 'Differentiation', isCorrect: false, rationale: 'Differentiation (about 5 to 10 months) is when the infant first begins to distinguish self from mother.' },
      { id: 'd', text: 'Object constancy', isCorrect: false, rationale: 'Object constancy (about 24 to 36 months) brings a stable inner image of the mother that eases separations.' },
    ],
    rationale: 'Mahler described separation-individuation subphases following the early autistic and symbiotic phases: differentiation, practicing, rapprochement and the move toward object constancy. The rapprochement crisis, with its mix of clinging and pushing away, is often linked to later difficulties with closeness and separateness.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: object relations theory and Mahler\'s separation-individuation' }],
  },
  {
    id: 'nce-s-cou-180',
    domain: 'counseling',
    cacrep: 'human_growth',
    topic: 'psychodynamic and psychoanalytic theory',
    difficulty: 'easy',
    reviewNote: 'Confirm Corey\'s object-relations section names Winnicott\'s transitional object and good-enough mother.',
    stem: 'A 2-year-old insists on bringing a worn stuffed rabbit to child care and clutches it when her father leaves. In Winnicott\'s object relations theory, what function does this transitional object serve?',
    options: [
      { id: 'a', text: 'It signals an insecure attachment that will need professional treatment', isCorrect: false, rationale: 'Transitional objects are a normal part of development, not a sign of pathology.' },
      { id: 'b', text: 'It soothes her and bridges her move from union with a parent to separateness', isCorrect: true, rationale: 'Winnicott saw the transitional object as an intermediate space that helps the child tolerate separation.' },
      { id: 'c', text: 'It reflects fixation at the oral stage caused by weaning that came too early', isCorrect: false, rationale: 'This applies Freud\'s psychosexual fixation, not Winnicott\'s concept.' },
      { id: 'd', text: 'It is a part-object she splits into all-good and all-bad parts to manage fear', isCorrect: false, rationale: 'Splitting and part-objects come from Melanie Klein, not the transitional object concept.' },
    ],
    rationale: 'Winnicott described the transitional object as the child\'s first "not-me" possession, standing between inner and outer reality and helping the child manage the gradual move to independence. It develops within a holding environment provided by a good-enough mother, who meets needs well at first and then fails in small, tolerable ways.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Psychoanalytic therapy: object relations (Winnicott, Klein)' }],
  },
];
