// tools/nce/seed/ethics-6.js — Professional Practice and Ethics, batch 6
// Hand-authored original items (nce-s-eth-121 … nce-s-eth-144).
module.exports = [
  {
    id: 'nce-s-eth-121',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'easy',
    stem: 'A former client has filed an ethics complaint against a counselor with the ACA Ethics Committee. The counselor wants to read the standards on cooperating with the committee and responding to complaints. Which section of the 2014 ACA Code of Ethics should she consult?',
    options: [
      { id: 'a', text: 'Section C, Professional Responsibility', isCorrect: false, rationale: 'Section C covers competence, advertising, public responsibility and impairment, not the complaint process.' },
      { id: 'b', text: 'Section A, The Counseling Relationship', isCorrect: false, rationale: 'Section A covers client welfare, consent, boundaries and termination within the counseling relationship.' },
      { id: 'c', text: 'Section I, Resolving Ethical Issues', isCorrect: true, rationale: 'Section I addresses ethics complaints, conflicts with law or employers, and cooperation with ethics committees.' },
      { id: 'd', text: 'Section B, Confidentiality and Privacy', isCorrect: false, rationale: 'Section B covers privacy, exceptions to confidentiality and records, not responding to complaints.' },
    ],
    rationale: 'The 2014 ACA Code of Ethics has nine sections, A through I. Section I, Resolving Ethical Issues, is the last; it covers knowledge of standards, suspected violations by colleagues, conflicts with law or organizations, and the duty to cooperate with ethics committees. Counselors who receive a complaint are expected to take part in the process rather than resign membership to avoid it.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section I: Resolving Ethical Issues (I.3 Cooperation With Ethics Committees)' }],
  },
  {
    id: 'nce-s-eth-122',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'medium',
    stem: 'A counselor researcher learns that a graduate assistant filled in blank items on 30 returned surveys with the answers participants "probably would have given," so the study would reach its target sample. The data are about to be analyzed. Under Section G of the ACA Code of Ethics, what should the researcher do?',
    options: [
      { id: 'a', text: 'Remove or flag the filled-in answers and analyze only the data that participants gave', isCorrect: true, rationale: 'G.4.a bars distorting or misrepresenting data; staff guesses are fabricated data and cannot be analyzed as real.' },
      { id: 'b', text: 'Keep the filled-in answers but note in the report that staff estimated some of the items', isCorrect: false, rationale: 'Disclosing the guesses does not make invented responses legitimate data; they still distort the results.' },
      { id: 'c', text: 'Keep the answers, since staff guesses work much like statistical imputation of missing data', isCorrect: false, rationale: 'Imputation is a transparent statistical method; an assistant writing in guessed answers is fabrication.' },
      { id: 'd', text: 'Let the assistant decide, since the lead researcher is not responsible for staff conduct', isCorrect: false, rationale: 'The principal researcher is responsible for the ethical conduct of the study, including that of research staff.' },
    ],
    rationale: 'ACA G.4.a requires counselors to plan, conduct and report research accurately and bars fraudulent research, distorted data and misrepresented results. Answers invented by staff are fabricated data, however well meant. The researcher removes them, handles missing data with an accepted and disclosed method, and addresses the assistant\'s conduct as the person responsible for the study.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.4.a Accurate Results' }, { source: 'ACA Code of Ethics', detail: 'G.1.f Principal Researcher Responsibility' }],
  },
  {
    id: 'nce-s-eth-123',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'hard',
    stem: 'A counselor educator wants to turn a former master\'s student\'s thesis into a journal article. The educator chaired the thesis and plans to rewrite much of the text for publication. Under the ACA Code of Ethics, how should authorship be handled?',
    options: [
      { id: 'a', text: 'The educator may be lead author, since rewriting the text is the larger share of the work', isCorrect: false, rationale: 'The Code gives lead authorship to the student when a work is substantially based on the student\'s thesis.' },
      { id: 'b', text: 'The student need only be thanked in a footnote, since the thesis has already been graded and filed', isCorrect: false, rationale: 'A footnote does not credit the person whose thesis the article is substantially based on.' },
      { id: 'c', text: 'The educator may publish alone, as a thesis chair holds joint rights to the student\'s work', isCorrect: false, rationale: 'Chairing a thesis gives no right to publish it alone; doing so takes credit for the student\'s work.' },
      { id: 'd', text: 'It may be published only with the student\'s permission and with the student as lead author', isCorrect: true, rationale: 'G.5.f requires the student\'s permission and lists the student as lead author for work based on a thesis.' },
    ],
    rationale: 'Under ACA G.5.f, manuscripts or presentations substantially based on a student\'s course papers, projects, dissertation or thesis are used only with the student\'s permission and list the student as lead author. G.5.d adds that credit goes to those who made significant contributions, in proportion to those contributions. Faculty power over students makes this protection important.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.5.f Student Research' }, { source: 'ACA Code of Ethics', detail: 'G.5.d Contributors' }],
  },
  {
    id: 'nce-s-eth-124',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'easy',
    stem: 'A counselor who holds the National Certified Counselor (NCC) credential and a state license describes herself on her practice website as a "Nationally Licensed Counselor." What is the problem with this description?',
    options: [
      { id: 'a', text: 'None, since a national certification and a state license together amount to the same thing', isCorrect: false, rationale: 'Certification and licensure are different; combining them does not create a national license.' },
      { id: 'b', text: 'It misstates her credential, because NCC is a national certification and not a license', isCorrect: true, rationale: 'NCC is a voluntary national certification; licenses are issued by states, so the title misleads the public.' },
      { id: 'c', text: 'It is acceptable only if she also lists the year she first passed the licensing exam', isCorrect: false, rationale: 'Adding an exam date does not correct a title that names a credential that does not exist.' },
      { id: 'd', text: 'It is acceptable as long as she practices only in the state that issued her license', isCorrect: false, rationale: 'Limiting practice to one state does not make "nationally licensed" accurate.' },
    ],
    rationale: 'Counselor licenses are granted by states; there is no national license. The NCC is a voluntary national certification from NBCC. Both the NBCC Code and ACA C.4.a require counselors to represent their credentials accurately, so a counselor lists "NCC" and her state license separately and correctly.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Accurate representation of NBCC credentials and qualifications' }, { source: 'ACA Code of Ethics', detail: 'C.4.a Accurate Representation' }],
  },
  {
    id: 'nce-s-eth-125',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'While applying for the NCC credential, a counselor inflates the number of supervised postgraduate hours on her application. She reasons that she is not yet an NCC, so the NBCC Code of Ethics does not apply to her. Which statement is accurate?',
    options: [
      { id: 'a', text: 'She is right, since the Code binds only counselors who already hold an NBCC credential', isCorrect: false, rationale: 'The NBCC Code applies to applicants as well as to certified counselors.' },
      { id: 'b', text: 'Only her state licensing board can act, since NBCC has no role in reviewing applications', isCorrect: false, rationale: 'NBCC reviews its own applications and can act on false information in them.' },
      { id: 'c', text: 'The inflated hours matter only if NBCC chooses to audit her application within the first year', isCorrect: false, rationale: 'Falsifying an application is a violation whether or not it is caught in an audit.' },
      { id: 'd', text: 'The Code also applies to applicants, so misstating hours can lead to denial or sanctions', isCorrect: true, rationale: 'The NBCC Code covers applicants, and dishonesty in the certification process can bring denial or sanctions.' },
    ],
    rationale: 'The NBCC Code of Ethics applies both to National Certified Counselors and to people applying for NBCC certification. Providing false information about education, supervision or experience undermines the integrity of the credential and can lead NBCC to deny certification or impose sanctions. Honesty with credentialing bodies is part of professional integrity from the start of a career.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Application to NCCs and applicants; honesty in the certification process' }],
  },
  {
    id: 'nce-s-eth-126',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A National Certified Counselor who works mainly in substance use treatment wants to add NBCC\'s specialty certification in addictions counseling to her credentials. Which credential should she pursue?',
    options: [
      { id: 'a', text: 'Master Addictions Counselor (MAC)', isCorrect: true, rationale: 'The MAC is NBCC\'s specialty certification in addictions counseling for NCCs.' },
      { id: 'b', text: 'Certified Rehabilitation Counselor', isCorrect: false, rationale: 'The CRC is a rehabilitation counseling credential from CRCC, not an NBCC addictions specialty.' },
      { id: 'c', text: 'National Certified School Counselor', isCorrect: false, rationale: 'The NCSC is an NBCC specialty, but it is for school counseling, not addictions.' },
      { id: 'd', text: 'Approved Clinical Supervisor (ACS)', isCorrect: false, rationale: 'The ACS is a supervision credential, not an addictions specialty.' },
    ],
    rationale: 'NBCC offers the National Certified Counselor (NCC) as its general credential and specialty certifications built on it, including the Certified Clinical Mental Health Counselor (CCMHC), the National Certified School Counselor (NCSC) and the Master Addictions Counselor (MAC). Specialty credentials require the NCC plus added training and experience in the specialty. Certification is voluntary and separate from state licensure.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Credentialing: NBCC national certification and specialty certifications' }],
  },
  {
    id: 'nce-s-eth-127',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'easy',
    stem: 'A community agency counselor carrying 70 cases says she feels drained, has started calling clients "the 2 o\'clock no-show" and "the difficult one," and doubts she helps anyone. In Maslach\'s model of burnout, which dimension do her labels for clients MOST reflect?',
    options: [
      { id: 'a', text: 'Emotional exhaustion', isCorrect: false, rationale: 'Exhaustion is the drained feeling she reports, not the detached labeling of clients.' },
      { id: 'b', text: 'Reduced personal accomplishment', isCorrect: false, rationale: 'This dimension fits her doubt that she helps anyone, not the labels.' },
      { id: 'c', text: 'Depersonalization', isCorrect: true, rationale: 'Depersonalization is a detached, impersonal or cynical stance toward the people one serves.' },
      { id: 'd', text: 'Vicarious traumatization', isCorrect: false, rationale: 'Vicarious trauma is a shift in core beliefs from trauma exposure, not a burnout dimension.' },
    ],
    rationale: 'Maslach described burnout as having three dimensions: emotional exhaustion, depersonalization (a detached or cynical response to clients) and reduced personal accomplishment. This counselor shows all three, and her impersonal labels for clients are the clearest sign of depersonalization. Burnout is a warning sign for impairment, which ACA C.2.g asks counselors to monitor in themselves.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counselor burnout: emotional exhaustion, depersonalization and reduced accomplishment' }, { source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-128',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'medium',
    stem: 'A counselor in long-term recovery from alcohol use disorder drank heavily over the weekend after a family loss. On Monday morning she feels hungover and shaky and has seven clients scheduled. Which action BEST follows the ACA Code of Ethics?',
    options: [
      { id: 'a', text: 'See the clients as planned, since one weekend of drinking does not make her impaired', isCorrect: false, rationale: 'She is shaky and hungover now; her current state, not the length of the lapse, puts clients at risk.' },
      { id: 'b', text: 'Cancel or arrange coverage for the day, then seek help before resuming her caseload', isCorrect: true, rationale: 'C.2.g directs counselors to stop offering services when impaired and to seek assistance first.' },
      { id: 'c', text: 'See the clients but tell each one about the relapse so they can decide whether to stay', isCorrect: false, rationale: 'Disclosure does not make impaired services safe and shifts the counselor\'s burden onto clients.' },
      { id: 'd', text: 'Keep the schedule and talk about the relapse with her own counselor at the next session', isCorrect: false, rationale: 'Seeking help is right, but it does not justify seeing clients today while impaired.' },
    ],
    rationale: 'ACA C.2.g asks counselors to monitor themselves for signs of impairment and to refrain from offering services when their physical, mental or emotional state is likely to harm clients. They seek help for problems that reach the level of impairment and, if needed, limit, suspend or end services until it is safe to resume. Arranging coverage protects clients and continuity of care.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-129',
    domain: 'ethics',
    cacrep: 'helping_relationships',
    topic: 'counselor impairment and self-care',
    difficulty: 'hard',
    stem: 'A counselor going through a painful divorce notices that she quickly sides with clients against their spouses and feels irritated when clients consider reconciling. Her supervisor wants to help her manage these reactions. Which approach BEST matches Gelso and Hayes\'s work on managing countertransference?',
    options: [
      { id: 'a', text: 'Avoid any client in marital conflict until her divorce is final and the feelings have faded', isCorrect: false, rationale: 'Avoidance may be needed briefly if reactions are severe, but it does not build the capacity to manage them.' },
      { id: 'b', text: 'Build self-insight and self-integration, such as through personal therapy and supervision', isCorrect: true, rationale: 'Self-insight and self-integration are core countertransference management factors in Gelso and Hayes\'s model.' },
      { id: 'c', text: 'Disclose her divorce to these clients so they understand the source of her strong reactions', isCorrect: false, rationale: 'This disclosure serves the counselor\'s needs and shifts attention away from the client.' },
      { id: 'd', text: 'Suppress her reactions in session and focus only on technique until the feelings subside', isCorrect: false, rationale: 'Suppression without understanding tends to let countertransference shape the work unnoticed.' },
    ],
    rationale: 'Gelso and Hayes describe five factors in managing countertransference: self-insight, self-integration, anxiety management, empathy and conceptualizing skills. Personal therapy and supervision help counselors understand where their reactions come from and keep them from acting them out with clients. Unmanaged reactions tied to a counselor\'s own life stress can become impairment, which C.2.g asks counselors to monitor.',
    references: [{ source: 'Gelso & Hayes (Countertransference)', detail: 'Countertransference management factors: self-insight, self-integration, anxiety management, empathy, conceptualizing skills' }, { source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-130',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'A 26-year-old client who has been in counseling for four months sends the counselor a friend request on the counselor\'s personal social media account, saying it would help her feel "more connected." Under the ACA Code of Ethics, what should the counselor do?',
    options: [
      { id: 'a', text: 'Accept the request but limit the client\'s view of personal posts through privacy settings', isCorrect: false, rationale: 'A limited personal connection is still a personal virtual relationship with a current client.' },
      { id: 'b', text: 'Accept the request, since social media contact is a minor and helpful boundary crossing', isCorrect: false, rationale: 'The Code does not treat this as an acceptable crossing; it prohibits it with current clients.' },
      { id: 'c', text: 'Ignore the request and say nothing, so the client is not embarrassed by being turned down', isCorrect: false, rationale: 'Silence leaves the client confused and misses a chance to discuss the boundary and her need.' },
      { id: 'd', text: 'Decline and discuss in session why personal online ties with clients are not permitted', isCorrect: true, rationale: 'A.5.e prohibits personal virtual relationships with current clients; talking it through supports the work.' },
    ],
    rationale: 'ACA A.5.e prohibits counselors from having personal virtual relationships, such as through social media, with current clients. The counselor declines the request and explores in session what the request means to the client, which can be useful clinical material. The counselor\'s social media policy, reviewed during informed consent, should explain this in advance.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.5.e Personal Virtual Relationships With Current Clients' }, { source: 'ACA Code of Ethics', detail: 'H.6.a Virtual Professional Presence' }],
  },
  {
    id: 'nce-s-eth-131',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'hard',
    stem: 'A counselor has seen a 38-year-old woman individually for a year. She now asks the counselor to start seeing her and her husband together for couples counseling, and the counselor is willing. Under the ACA Code of Ethics, what must happen before the change?',
    options: [
      { id: 'a', text: 'Explain the change and its effects, get informed consent, and note the right to refuse it', isCorrect: true, rationale: 'A.6.d requires informed consent for a role change, including the right to refuse it and its consequences.' },
      { id: 'b', text: 'Begin joint sessions, since she already consented to treatment with this same counselor', isCorrect: false, rationale: 'Consent to individual counseling does not cover a change to couples counseling.' },
      { id: 'c', text: 'End individual work first, since a counselor may not shift from individual to couples work', isCorrect: false, rationale: 'The Code permits this role change when it is handled through informed consent.' },
      { id: 'd', text: 'Have the husband sign a release, since only his consent is needed for the new format', isCorrect: false, rationale: 'The existing client\'s informed consent to the change is central; a release for the husband is not enough.' },
    ],
    rationale: 'ACA A.6.d treats a shift from individual to relationship or family counseling as a role change. The counselor obtains informed consent and explains the client\'s right to refuse services related to the change, along with any effects, such as how confidentiality and the alliance may shift with a second client. The husband also gives his own informed consent as a new client.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.6.d Role Changes in the Professional Relationship' }],
  },
  {
    id: 'nce-s-eth-132',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'scope of practice and competence',
    difficulty: 'easy',
    stem: 'A client taking an antidepressant prescribed by her primary care physician tells her counselor she feels better and plans to stop the medication this week. She asks whether stopping on her own is safe. What is the counselor\'s BEST response?',
    options: [
      { id: 'a', text: 'Advise her to taper the dose slowly over two weeks to reduce the risk of side effects', isCorrect: false, rationale: 'Giving dosing instructions is medical advice outside a counselor\'s scope of practice.' },
      { id: 'b', text: 'Tell her that stopping is fine, since her improved mood shows that she no longer needs the drug', isCorrect: false, rationale: 'This is a medical judgment the counselor is not trained or licensed to make.' },
      { id: 'c', text: 'Urge her to talk with her prescriber first, and offer to coordinate care with her consent', isCorrect: true, rationale: 'This respects the counselor\'s scope while supporting the client and her care team.' },
      { id: 'd', text: 'Tell her to keep taking the full dose, since stopping would undo the progress so far', isCorrect: false, rationale: 'Telling her to continue is also a medication decision that belongs to the prescriber.' },
    ],
    rationale: 'Counselors practice within the boundaries of their education, training and licensure, which do not include prescribing or advising on medication changes. The counselor can share general concerns, encourage the client to consult her prescriber before stopping, and, with consent, coordinate with the physician. Exploring her reasons for wanting to stop remains within the counselor\'s role.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.a Boundaries of Competence' }, { source: 'ACA Code of Ethics', detail: 'D.1.c Interdisciplinary Teamwork' }],
  },
  {
    id: 'nce-s-eth-133',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'scope of practice and competence',
    difficulty: 'medium',
    stem: 'A counselor whose group training and experience are in psychoeducational groups is asked by her agency to lead a long-term psychotherapy group for adults with complex trauma histories. What is her BEST course of action?',
    options: [
      { id: 'a', text: 'Get specialized training and supervised experience in that type of group before leading it', isCorrect: true, rationale: 'Competence is specific to group type; she builds it through training and supervision first.' },
      { id: 'b', text: 'Lead the group, since basic group leadership skills carry over evenly across all types of groups', isCorrect: false, rationale: 'ASGW distinguishes group types because each calls for different specialized skills.' },
      { id: 'c', text: 'Lead the group as a psychoeducational class so that it stays within her current training', isCorrect: false, rationale: 'Changing the format quietly does not meet the needs the group was formed to serve.' },
      { id: 'd', text: 'Accept the role, since an agency assignment makes the group part of her scope of practice', isCorrect: false, rationale: 'An employer\'s assignment does not create competence or expand professional boundaries.' },
    ],
    rationale: 'ASGW identifies distinct group specializations, including task, psychoeducational, counseling and psychotherapy groups, each calling for its own training. ACA C.2.a and C.2.b limit practice to areas of competence and require education, training and supervised experience before practicing in a new specialty area. Long-term trauma psychotherapy groups demand advanced skills in managing intense affect and member safety.',
    references: [{ source: 'ASGW Best Practice Guidelines', detail: 'Group leader competence and training for the type of group led' }, { source: 'ACA Code of Ethics', detail: 'C.2.b New Specialty Areas of Practice' }],
  },
  {
    id: 'nce-s-eth-134',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'medium',
    stem: 'A licensure supervisor meets weekly with a supervisee who describes her sessions in detail. The supervisor has never seen or heard any of the supervisee\'s work. Two clients have recently dropped out without notice. What change would BEST meet the supervisor\'s obligation to clients?',
    options: [
      { id: 'a', text: 'Ask the supervisee to write longer summaries of each session before their weekly supervision meetings', isCorrect: false, rationale: 'Longer summaries are still self-report and may miss what the supervisee does not notice.' },
      { id: 'b', text: 'Contact the two clients directly to ask why they ended counseling without giving notice', isCorrect: false, rationale: 'This bypasses the supervisee and does not fix how the supervisor monitors ongoing care.' },
      { id: 'c', text: 'Continue as before, since a supervisee\'s self-report is the accepted basis for supervision', isCorrect: false, rationale: 'Self-report alone limits the supervisor\'s ability to monitor the services clients receive.' },
      { id: 'd', text: 'Add direct review of the work, such as recordings or live observation, with client consent', isCorrect: true, rationale: 'Direct review lets the supervisor monitor client welfare and supervisee performance, as F.1.a requires.' },
    ],
    rationale: 'Under ACA F.1.a, a supervisor\'s primary obligation is to monitor the services supervisees provide to clients. Self-report misses what the supervisee does not see or chooses not to share, so direct methods such as recordings or live observation give a fuller picture. Clients consent to recording or observation in advance, as B.6.c and B.6.d require.',
    references: [{ source: 'ACA Code of Ethics', detail: 'F.1.a Client Welfare' }, { source: 'ACA Code of Ethics', detail: 'B.6.c Permission to Record' }],
  },
  {
    id: 'nce-s-eth-135',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'hard',
    stem: 'A counselor in private practice is hired by a school district to consult with teachers on building trauma-informed classrooms. Before the consulting work begins, which step does the ACA Code of Ethics call for?',
    options: [
      { id: 'a', text: 'Gather confidential details on the individual students the teachers are most worried about', isCorrect: false, rationale: 'Student details are not needed for this consultation and raise privacy concerns.' },
      { id: 'b', text: 'Review, in writing and verbally, the rights and responsibilities of her and the consultees', isCorrect: true, rationale: 'D.2.b calls for written and verbal review of both parties\' rights and responsibilities in formal consultation.' },
      { id: 'c', text: 'Offer individual counseling to any of the teachers who seem stressed during the consultation', isCorrect: false, rationale: 'Adding a counseling role to a consulting role creates a multiple relationship.' },
      { id: 'd', text: 'Agree to report each teacher\'s performance to the principal as part of her contract work', isCorrect: false, rationale: 'This makes the consultant an evaluator and should not be agreed to without clear consent from consultees.' },
    ],
    rationale: 'ACA D.2.b requires that, when providing formal consultation, counselors review in writing and verbally the rights and responsibilities of both counselor and consultees, using clear language. This clarifies goals, roles, confidentiality and limits before work begins. D.2.a adds that consultants must be competent in the area of consultation and refer when needed.',
    references: [{ source: 'ACA Code of Ethics', detail: 'D.2.b Informed Consent in Formal Consultation' }, { source: 'ACA Code of Ethics', detail: 'D.2.a Consultant Competency' }],
  },
  {
    id: 'nce-s-eth-136',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'easy',
    stem: 'Through the 20/20: A Vision for the Future of Counseling initiative, a large group of counseling organizations agreed on a shared definition of counseling to support a unified professional identity. Which statement captures that definition?',
    options: [
      { id: 'a', text: 'Counseling is the treatment of diagnosed mental disorders through talk-based psychotherapy methods alone', isCorrect: false, rationale: 'The definition is broader than disorder treatment and includes wellness, education and career goals.' },
      { id: 'b', text: 'Counseling is a brief advice-giving service that helps people without disorders solve everyday practical problems', isCorrect: false, rationale: 'The definition describes an empowering relationship, not advice-giving for healthy people only.' },
      { id: 'c', text: 'A relationship that empowers diverse people to reach mental health, wellness, education and career goals', isCorrect: true, rationale: 'This matches the consensus 20/20 definition of counseling.' },
      { id: 'd', text: 'Counseling is the use of psychological tests to classify people and guide them into suitable careers', isCorrect: false, rationale: 'This resembles early vocational guidance, not the modern consensus definition.' },
    ],
    rationale: 'The 20/20 initiative, sponsored by ACA and the American Association of State Counseling Boards, produced a consensus definition: counseling is a professional relationship that empowers diverse individuals, families and groups to accomplish mental health, wellness, education and career goals. The definition emphasizes empowerment, diversity and a wellness focus rather than illness alone, which sets counseling apart from neighboring professions.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: '20/20: A Vision for the Future of Counseling consensus definition of counseling' }],
  },
  {
    id: 'nce-s-eth-137',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'medium',
    stem: 'A counselor educator is teaching the history of counselor licensure in the United States. Which statement is accurate?',
    options: [
      { id: 'a', text: 'California was the first state to license professional counselors, and Virginia was the last', isCorrect: false, rationale: 'The order is reversed: Virginia was first and California was last.' },
      { id: 'b', text: 'Every state licensed counselors by 1990, soon after CACREP was founded in 1981', isCorrect: false, rationale: 'CACREP dates to 1981, but licensure did not reach all 50 states until 2009.' },
      { id: 'c', text: 'Virginia licensed counselors first, in 1976, and California was the last state, in 2009', isCorrect: true, rationale: 'Virginia passed the first counselor licensure law in 1976; California completed the 50 states in 2009.' },
      { id: 'd', text: 'Counselor licensure began at the federal level and was later handed over to the states', isCorrect: false, rationale: 'Counselor licensure has been a state matter from the start; there is no federal license.' },
    ],
    rationale: 'Counselor licensure in the United States is state-based. Virginia enacted the first general counselor licensure law in 1976, and California became the last of the 50 states to license professional counselors in 2009. Differences among state laws are one reason portability efforts such as the Counseling Compact have developed.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'History of counselor licensure: Virginia (1976) to California (2009)' }],
  },
  {
    id: 'nce-s-eth-138',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A counselor sees that many clients struggle to use a county clinic that offers no materials in Spanish. A local parents\' group is already organizing on the issue. The counselor offers the group her data skills and support while its members lead the effort. Which ACA Advocacy Competencies domain does this BEST illustrate?',
    options: [
      { id: 'a', text: 'Community collaboration', isCorrect: true, rationale: 'She acts with a community group at the school/community level, supporting its own leadership.' },
      { id: 'b', text: 'Systems advocacy', isCorrect: false, rationale: 'Systems advocacy is the counselor acting on behalf of clients to change a system, not supporting a group\'s lead.' },
      { id: 'c', text: 'Client/student advocacy', isCorrect: false, rationale: 'This is acting on behalf of an individual client, not joining a community effort.' },
      { id: 'd', text: 'Social/political advocacy', isCorrect: false, rationale: 'This is acting in the public arena on legislation and policy, not supporting a local group.' },
    ],
    rationale: 'The ACA Advocacy Competencies distinguish acting with clients and communities from acting on their behalf, at the client, school/community and public arena levels. Community collaboration means working alongside groups that are addressing a shared concern, offering the counselor\'s skills while the community leads. Systems advocacy, by contrast, has the counselor taking the lead to change an institution.',
    references: [{ source: 'ACA Advocacy Competencies', detail: 'School/community level: community collaboration vs. systems advocacy' }],
  },
  {
    id: 'nce-s-eth-139',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'hard',
    stem: 'A counselor who is a white, upper-middle-class man reflects on how his privilege and his client\'s marginalized status as a low-income Black woman shape power, trust and communication between them in session. In the Multicultural and Social Justice Counseling Competencies, which developmental domain does this MOST directly address?',
    options: [
      { id: 'a', text: 'Counselor self-awareness', isCorrect: false, rationale: 'Self-awareness centers on the counselor\'s own identity; the focus here is the interaction between them.' },
      { id: 'b', text: 'Client worldview', isCorrect: false, rationale: 'Client worldview centers on understanding the client\'s identities and experiences.' },
      { id: 'c', text: 'Counseling and advocacy interventions', isCorrect: false, rationale: 'This domain concerns intervening at individual through systemic levels, not the in-session dynamic.' },
      { id: 'd', text: 'The counseling relationship', isCorrect: true, rationale: 'This domain addresses how privileged and marginalized statuses of both parties shape their relationship.' },
    ],
    rationale: 'The MSJCC (Ratts et al., 2016) arrange competencies in four developmental domains: counselor self-awareness, client worldview, the counseling relationship, and counseling and advocacy interventions. A quadrant model places counselor and client as privileged or marginalized. The counseling relationship domain asks how those combined statuses affect power, trust and communication in the work.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Developmental domains; privileged and marginalized quadrants; the counseling relationship' }],
  },
  {
    id: 'nce-s-eth-140',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'medium',
    stem: 'A doctoral student preparing to teach and supervise counselors wants to join the ACA division devoted to counselor preparation and clinical supervision, which publishes the journal Counselor Education and Supervision. Which organization is it?',
    options: [
      { id: 'a', text: 'NBCC', isCorrect: false, rationale: 'NBCC is an independent certification body, not an ACA division.' },
      { id: 'b', text: 'ACES', isCorrect: true, rationale: 'The Association for Counselor Education and Supervision focuses on counselor preparation and supervision.' },
      { id: 'c', text: 'AARC', isCorrect: false, rationale: 'The Association for Assessment and Research in Counseling focuses on assessment and research.' },
      { id: 'd', text: 'CACREP', isCorrect: false, rationale: 'CACREP accredits counseling programs; it is not a membership division.' },
    ],
    rationale: 'The Association for Counselor Education and Supervision (ACES) is the ACA division for counselor educators and supervisors and publishes Counselor Education and Supervision. It promotes quality in counselor preparation and supervision practice. CACREP accredits programs and NBCC certifies individuals; neither is an ACA division.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'ACA divisions: Association for Counselor Education and Supervision' }],
  },
  {
    id: 'nce-s-eth-141',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'medium',
    stem: 'A counselor who works in vocational rehabilitation with adults who have disabilities wants the national credential specific to rehabilitation counseling. Which body grants that credential?',
    options: [
      { id: 'a', text: 'CRCC, which grants the Certified Rehabilitation Counselor (CRC) credential', isCorrect: true, rationale: 'The Commission on Rehabilitation Counselor Certification grants the CRC.' },
      { id: 'b', text: 'CACREP, which accredits rehabilitation programs and certifies their graduates', isCorrect: false, rationale: 'CACREP accredits programs; it does not certify individual counselors.' },
      { id: 'c', text: 'ASCA, which certifies counselors who serve students with disabilities', isCorrect: false, rationale: 'ASCA is the school counselor association and does not grant a rehabilitation credential.' },
      { id: 'd', text: 'AASCB, which issues a rehabilitation counseling license valid in all states', isCorrect: false, rationale: 'AASCB is an association of state boards; it issues no licenses, and there is no national license.' },
    ],
    rationale: 'The Commission on Rehabilitation Counselor Certification (CRCC) grants the Certified Rehabilitation Counselor (CRC) credential and maintains its own code of ethics for CRCs. Certification is a voluntary national credential separate from state licensure. Accreditation bodies such as CACREP review programs, not individuals.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Credentialing: rehabilitation counseling and the CRC credential (CRCC)' }],
  },
  {
    id: 'nce-s-eth-142',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'medium',
    stem: 'Early in counseling, a 45-year-old client discloses an affair and asks the counselor not to write "anything at all" about her sessions, because her spouse might someday see the record. What is the counselor\'s BEST response?',
    options: [
      { id: 'a', text: 'Agree to keep no record of her sessions, so that her request for privacy is honored', isCorrect: false, rationale: 'Counselors must keep the documentation needed to provide and continue services.' },
      { id: 'b', text: 'Keep a separate private file at home so that the official agency record holds no session content', isCorrect: false, rationale: 'A hidden file is less secure and misrepresents what the official record contains.' },
      { id: 'c', text: 'Explain that some records are required, and discuss what will be noted and who may see it', isCorrect: true, rationale: 'This meets A.1.b while respecting her concern through openness about content and access.' },
      { id: 'd', text: 'Record every detail of the affair, since full notes protect the counselor in any dispute', isCorrect: false, rationale: 'Excess personal detail is not needed for care and adds risk to the client\'s privacy.' },
    ],
    rationale: 'ACA A.1.b requires counselors to create, safeguard and maintain the documentation needed to provide services, including sufficient and timely notes. The counselor explains this, describes how records are protected and who can access them, and documents what is clinically necessary without needless personal detail. Being open about records supports trust and informed consent.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.1.b Records and Documentation' }, { source: 'Wiger (Documentation)', detail: 'Clinically necessary content and minimum necessary detail in progress notes' }],
  },
  {
    id: 'nce-s-eth-143',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'informed consent and its required elements',
    difficulty: 'easy',
    stem: 'A counseling intern\'s practicum requires her to audio-record sessions for review in supervision. A new client arrives for an intake. Under the ACA Code of Ethics, what must the intern do about the recording?',
    options: [
      { id: 'a', text: 'Record the session and tell the client afterward, since supervision benefits the client too', isCorrect: false, rationale: 'Permission must come before recording, not after the fact.' },
      { id: 'b', text: 'Record without asking, since the recordings are kept within the training program alone', isCorrect: false, rationale: 'Limited access does not remove the need for the client\'s permission.' },
      { id: 'c', text: 'Record only the intern\'s own voice, since that avoids any need for client permission', isCorrect: false, rationale: 'Session content is still captured, and the client still has a right to decide.' },
      { id: 'd', text: 'Get the client\'s permission before recording and explain how it will be used and stored', isCorrect: true, rationale: 'B.6.c requires client permission before sessions are recorded.' },
    ],
    rationale: 'ACA B.6.c requires counselors to obtain clients\' permission before recording sessions by electronic or other means, and F.1.c requires that clients know the counselor is in training and how supervision affects confidentiality. Informed consent covers who will hear the recording, how it is stored and when it is erased. Clients may decline.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.6.c Permission to Record' }, { source: 'ACA Code of Ethics', detail: 'F.1.c Informed Consent and Client Rights' }],
  },
  {
    id: 'nce-s-eth-144',
    domain: 'ethics',
    cacrep: 'career',
    topic: 'telehealth and technology ethics',
    difficulty: 'hard',
    stem: 'A counselor providing career counseling by video wants a 34-year-old client to complete a free online "career personality quiz" she found on a popular website. The site gives no information on how the quiz was developed or tested. What is the BEST ethical course?',
    options: [
      { id: 'a', text: 'Use the quiz, since online tools are acceptable in distance counseling if the client agrees', isCorrect: false, rationale: 'Client agreement does not make an untested instrument valid for career decisions.' },
      { id: 'b', text: 'Choose an instrument with documented validity, reliability and norms that fit the client', isCorrect: true, rationale: 'E.6.a requires weighing validity, reliability and appropriateness when selecting assessments.' },
      { id: 'c', text: 'Use the quiz but present its results to the client as a firm guide to her best careers', isCorrect: false, rationale: 'Presenting unknown-quality results as firm guidance misleads the client.' },
      { id: 'd', text: 'Use the quiz, since free career tools carry less risk than formal psychological testing', isCorrect: false, rationale: 'Career decisions carry real stakes; low cost does not lower the standard for evidence.' },
    ],
    rationale: 'ACA E.6.a asks counselors to consider validity, reliability, psychometric limits and appropriateness when selecting assessments, whether given in person or online. Many free web quizzes have no technical data, so their results cannot support career decisions. Well-developed interest and values inventories with documented norms, interpreted with the client, serve distance career counseling better.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.6.a Appropriateness of Instruments' }, { source: 'Sharf (Career Development Theory)', detail: 'Use of interest and values inventories in career counseling' }],
  },
];
