// tools/nce/seed/ethics-2.js — Professional Practice and Ethics, batch 2
// Hand-authored original items (nce-s-eth-025 … nce-s-eth-048).
module.exports = [
  {
    id: 'nce-s-eth-025',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'informed consent and its required elements',
    difficulty: 'medium',
    stem: 'A client in private practice stopped attending sessions and has an unpaid balance of several hundred dollars. The counselor is considering turning the account over to a collection agency. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Inform the client of the intended collection step and give a chance to pay the balance', isCorrect: true, rationale: 'A.10.d requires counselors to inform clients of intended collection actions and offer an opportunity to pay first.' },
      { id: 'b', text: 'Send the account to the agency right away, since the client has already ended counseling', isCorrect: false, rationale: 'Ending services does not remove the duty to notify the client before using collection measures.' },
      { id: 'c', text: 'Write off the debt, because counselors may not pursue payment from any current or past client', isCorrect: false, rationale: 'The Code permits collection agencies or legal measures when clients are informed first.' },
      { id: 'd', text: 'Give the agency the client\'s diagnosis and session notes so it can justify the charges', isCorrect: false, rationale: 'Only the minimum information needed for collection is disclosed; clinical details are not shared.' },
    ],
    rationale: 'Under A.10.d, counselors who intend to use collection agencies or legal measures for nonpayment first tell the client what they intend and give the client an opportunity to pay. Fee and billing arrangements, including how nonpayment is handled, also belong in the initial informed consent (A.2.b). Any disclosure to a collector is limited to what is needed.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.10.d Nonpayment of Fees' }],
  },
  {
    id: 'nce-s-eth-026',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'In a rural farming community where trading services is common, a client who recently lost his job asks whether he could repair the counselor\'s office roof in exchange for sessions. Under the ACA Code of Ethics, when is bartering acceptable?',
    options: [
      { id: 'a', text: 'Whenever the counselor sets the value of the work, since the counselor bears responsibility', isCorrect: false, rationale: 'One-sided valuation by the counselor increases the risk of exploitation.' },
      { id: 'b', text: 'Only when the counselor proposes it first, so that the client does not feel pressured to offer', isCorrect: false, rationale: 'The Code says the client should request the arrangement, not the counselor.' },
      { id: 'c', text: 'If the client requests it, it is not exploitive, it is accepted locally, and it is in writing', isCorrect: true, rationale: 'A.10.e lists client request, no exploitation or harm, and community acceptance, with a written contract.' },
      { id: 'd', text: 'Only for clients with no insurance, as long as a supervisor signs off on the trade in advance', isCorrect: false, rationale: 'Insurance status and supervisor approval are not the conditions the Code sets for bartering.' },
    ],
    rationale: 'A.10.e allows bartering only when the client requests it, the arrangement does not result in exploitation or harm, and such arrangements are an accepted practice among professionals in the community. Counselors consider cultural implications, discuss concerns with the client, and document the agreement in a clear written contract.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.10.e Bartering' }],
  },
  {
    id: 'nce-s-eth-027',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'termination and referral',
    difficulty: 'easy',
    stem: 'A counselor accepts a job in another state and will close her practice in two months. Several of her clients are still working on active treatment goals. Which action BEST avoids client abandonment?',
    options: [
      { id: 'a', text: 'Stop scheduling sessions now and mail each client a letter after the office has closed', isCorrect: false, rationale: 'Ending contact abruptly without preparation or referral is a form of abandonment.' },
      { id: 'b', text: 'Keep seeing clients until the last day and leave referrals to the clients\' own judgment', isCorrect: false, rationale: 'Counselors help arrange continued care rather than leaving clients to find it alone.' },
      { id: 'c', text: 'Ask clients to keep texting her after the move so that their counseling can continue informally', isCorrect: false, rationale: 'Informal contact across state lines raises licensure and boundary problems, not continuity.' },
      { id: 'd', text: 'Tell clients early, provide pretermination counseling, and help arrange suitable referrals', isCorrect: true, rationale: 'A.11.c and A.12 call for timely notice, pretermination counseling, and referral to other providers.' },
    ],
    rationale: 'A.12 prohibits abandoning or neglecting clients and requires arrangements for continuation of treatment during interruptions such as relocation. A.11.c and A.11.d direct counselors to provide pretermination counseling, recommend other providers, and coordinate an appropriate transfer of services.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.12 Abandonment and Client Neglect' }, { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' }],
  },
  {
    id: 'nce-s-eth-028',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'hard',
    stem: 'A counselor receives a subpoena from the attorney for a client\'s former spouse, demanding the client\'s full counseling file for a custody hearing. The client has not signed a release. What is the counselor\'s BEST course of action?',
    options: [
      { id: 'a', text: 'Send the complete file at once, since a subpoena carries the same force as a court order', isCorrect: false, rationale: 'An attorney-issued subpoena generally does not by itself authorize release of privileged records.' },
      { id: 'b', text: 'Contact the client, seek legal advice, and release nothing without consent or a court order', isCorrect: true, rationale: 'B.2.d and state privilege law favor client consent or a judicial order, with disclosure limited.' },
      { id: 'c', text: 'Ignore the subpoena, because counseling records are privileged and cannot be required', isCorrect: false, rationale: 'Ignoring a subpoena can bring legal penalties; privilege must be asserted, not assumed.' },
      { id: 'd', text: 'Call the former spouse\'s attorney to discuss the client\'s progress and resolve it informally', isCorrect: false, rationale: 'Discussing the client with the opposing attorney is itself a breach of confidentiality.' },
    ],
    rationale: 'A subpoena is a demand that must be answered, but it is not the same as a judge\'s order to disclose. Counselors notify the client, consult an attorney, and assert privilege when appropriate. Under B.2.d, even when a court orders disclosure, counselors seek the client\'s written consent or ask that disclosure be prohibited or limited as narrowly as possible. State law varies.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.d Court-Ordered Disclosure' }, { source: 'State law', detail: 'Privileged communication and response to subpoenas vs court orders' }],
    reviewNote: 'Verify that the subpoena-vs-court-order distinction is stated accurately enough for a general (non-state-specific) NCE item.',
  },
  {
    id: 'nce-s-eth-029',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'medium',
    stem: 'Three months after a long-term client dies of natural causes, her adult son calls the counselor and asks for copies of his mother\'s session notes so he can "understand her better." What should guide the counselor\'s response?',
    options: [
      { id: 'a', text: 'Release the notes, since confidentiality obligations end once a client has died', isCorrect: false, rationale: 'B.3.f states that counselors protect the confidentiality of deceased clients.' },
      { id: 'b', text: 'Release the notes, since any adult child is the legal heir to a parent\'s own records', isCorrect: false, rationale: 'Family relationship alone does not confer legal authority over a decedent\'s records.' },
      { id: 'c', text: 'Protect her confidentiality, following state law on who may act for the deceased', isCorrect: true, rationale: 'B.3.f protects deceased clients\' confidentiality consistent with law and agency policy.' },
      { id: 'd', text: 'Share a verbal summary instead, since a summary does not breach confidentiality', isCorrect: false, rationale: 'A summary is still a disclosure of confidential information without valid authorization.' },
    ],
    rationale: 'B.3.f directs counselors to protect the confidentiality of deceased clients, consistent with legal requirements and agency or setting policies. Typically only a legally authorized personal representative, such as an executor, may authorize release, and who qualifies is set by state law, which varies.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.3.f Deceased Clients' }, { source: 'State law', detail: 'Personal representative authority over a deceased person\'s records' }],
  },
  {
    id: 'nce-s-eth-030',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'easy',
    stem: 'A licensed counselor wants advice from a peer consultation group about a difficult case involving a well-known local business owner. The client has not given consent to discuss the case. How should the counselor proceed?',
    options: [
      { id: 'a', text: 'Present the case without details that could reasonably identify the client to the group', isCorrect: true, rationale: 'B.7 bars identifying disclosures in consultation without consent, sharing only what is needed.' },
      { id: 'b', text: 'Share the client\'s name, since members of a consultation group are bound by confidentiality', isCorrect: false, rationale: 'Peer consultants do not share the counselor\'s duty in a way that permits identifying the client.' },
      { id: 'c', text: 'Avoid consultation altogether, since any discussion of a case breaches client confidentiality', isCorrect: false, rationale: 'Consultation is encouraged; it is done with de-identified information or with consent.' },
      { id: 'd', text: 'Share full details but ask the group to sign a confidentiality agreement before the meeting', isCorrect: false, rationale: 'A group agreement does not replace client consent for identifying disclosures.' },
    ],
    rationale: 'In case consultation, counselors do not disclose information that could reasonably lead to the client\'s identification unless the client has consented or disclosure cannot be avoided, and they share only what is needed for the consultation. With a well-known client, extra care is needed to remove identifying details.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.7 Case Consultation' }],
  },
  {
    id: 'nce-s-eth-031',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'medium',
    stem: 'A counselor is about to begin couples counseling with two partners in their fifties. To prevent problems later, what should the counselor do regarding confidentiality at the outset?',
    options: [
      { id: 'a', text: 'Promise each partner that anything said in an individual call will stay secret from the other', isCorrect: false, rationale: 'Blanket secret-keeping promises can undermine the couple work and should not be made by default.' },
      { id: 'b', text: 'Tell both partners that the counselor will decide case by case what to reveal between them', isCorrect: false, rationale: 'An unannounced, case-by-case approach leaves clients unable to give informed consent.' },
      { id: 'c', text: 'Skip the topic, since confidentiality rules do not apply when both partners are present', isCorrect: false, rationale: 'B.4.b requires discussing confidentiality expectations and limits in couples work.' },
      { id: 'd', text: 'Define who the client is and get a written agreement on how confidences will be handled', isCorrect: true, rationale: 'B.4.b asks counselors to define the client and document agreement on confidentiality.' },
    ],
    rationale: 'In couples and family counseling, B.4.b directs counselors to clearly define who is considered the client and to discuss expectations and limits of confidentiality. Counselors seek agreement among all parties, document it in writing, and A.8 adds that the nature of each relationship is clarified at the outset.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.4.b Couples and Family Counseling' }, { source: 'ACA Code of Ethics', detail: 'A.8 Multiple Clients' }],
  },
  {
    id: 'nce-s-eth-032',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'scope of practice and competence',
    difficulty: 'easy',
    stem: 'A counselor is forming a 10-week psychoeducational group on managing workplace stress. According to the ACA Code of Ethics, what is the main purpose of screening prospective members?',
    options: [
      { id: 'a', text: 'To make sure the group is full before the first meeting so the program stays funded', isCorrect: false, rationale: 'Enrollment targets are not the ethical purpose of screening.' },
      { id: 'b', text: 'To select members whose goals fit the group and whose well-being will not be at risk', isCorrect: true, rationale: 'A.9.a calls for selecting compatible members who will not impede the group or be harmed.' },
      { id: 'c', text: 'To collect enough personal history that members need not share anything in sessions', isCorrect: false, rationale: 'Screening is about fit and safety, not replacing disclosure during the group.' },
      { id: 'd', text: 'To exclude any applicant who has a mental health diagnosis from a psychoeducation group', isCorrect: false, rationale: 'A diagnosis alone is not a reason to exclude; fit with group goals is the standard.' },
    ],
    rationale: 'A.9.a directs counselors to screen prospective group members to the extent possible, selecting members whose needs and goals are compatible with the group\'s goals, who will not impede the group process, and whose well-being will not be jeopardized by the group experience.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.9.a Screening' }, { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Selection of clients for group therapy' }],
  },
  {
    id: 'nce-s-eth-033',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'During the fourth session of an adolescent anger-management group, several members begin mocking a quieter member\'s accent, and she starts to cry. What is the leader\'s MOST appropriate response?',
    options: [
      { id: 'a', text: 'Intervene at once to stop the mocking and protect the member, then process what happened', isCorrect: true, rationale: 'A.9.b requires reasonable precautions to protect group members from emotional harm.' },
      { id: 'b', text: 'Let the group handle it alone, since peer feedback is how adolescent groups mature over time', isCorrect: false, rationale: 'Allowing ridicule to continue fails the leader\'s duty to protect members.' },
      { id: 'c', text: 'Ask the upset member to leave until she is calm enough to rejoin the group discussion', isCorrect: false, rationale: 'Removing the targeted member punishes her rather than addressing the harmful behavior.' },
      { id: 'd', text: 'Note the incident and raise it with each member\'s parents after the session has ended', isCorrect: false, rationale: 'Delaying action leaves the member unprotected during the session.' },
    ],
    rationale: 'In a group setting, A.9.b directs counselors to take reasonable precautions to protect clients from physical, emotional, or psychological trauma. Blocking harmful interactions is a core leader skill; once safety is restored, the incident can be processed, including the bias it reflects.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.9.b Protecting Clients' }, { source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Leader role in establishing group norms and safety' }],
  },
  {
    id: 'nce-s-eth-034',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'scope of practice and competence',
    difficulty: 'easy',
    stem: 'An agency director asks a newly licensed counselor to administer and interpret an individually administered intelligence test. The counselor has never been trained on this instrument. What should the counselor do?',
    options: [
      { id: 'a', text: 'Administer it after reading the manual, since the license covers all forms of assessment', isCorrect: false, rationale: 'Reading a manual does not establish competence with a complex individual test.' },
      { id: 'b', text: 'Administer it but have the computer scoring report serve as the clinical interpretation', isCorrect: false, rationale: 'Counselors remain responsible for interpretation even when scoring is automated (E.9).' },
      { id: 'c', text: 'Decline until trained and supervised in its use, and refer the testing to a qualified peer', isCorrect: true, rationale: 'E.2.a limits counselors to assessments they are trained and competent to use.' },
      { id: 'd', text: 'Administer it, since the director has the authority to approve staff for any test that is needed', isCorrect: false, rationale: 'An employer cannot confer competence; the ethical duty rests with the counselor.' },
    ],
    rationale: 'E.2.a states that counselors use only those testing and assessment services for which they have been trained and are competent. Counselors who rely on technology-assisted interpretation are trained in the construct and the instrument before using it. Until competent, the counselor refers the assessment.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.2.a Limits of Competence' }, { source: 'Hays (Assessment)', detail: 'Test user qualifications' }],
  },
  {
    id: 'nce-s-eth-035',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'record keeping and documentation',
    difficulty: 'hard',
    stem: 'A client involved in a disability claim signs a release asking the counselor to send her raw personality test responses and scores directly to her attorney, who has no training in psychological testing. How should the counselor respond under the ACA Code of Ethics?',
    options: [
      { id: 'a', text: 'Send the raw data, since a signed release obligates the counselor to send anything asked for', isCorrect: false, rationale: 'Consent is necessary but E.4 also limits release to qualified recipients.' },
      { id: 'b', text: 'Refuse any release, since test results may not leave the counselor\'s office in any form', isCorrect: false, rationale: 'Results can be released with consent; the issue is who receives raw data.' },
      { id: 'c', text: 'Send the raw data only after the attorney promises not to share it with the opposing side', isCorrect: false, rationale: 'A promise of nondisclosure does not make an untrained recipient qualified to interpret.' },
      { id: 'd', text: 'Offer a written interpretive report, or send raw data to a professional qualified to use it', isCorrect: true, rationale: 'E.4 releases identified data with consent only to persons qualified to interpret them.' },
    ],
    rationale: 'E.4 states that counselors release assessment data in which the client is identified only with consent of the client or a legal representative, and only to persons the counselor recognizes as qualified to interpret the data. A report written for lay readers, or release to a qualified professional, meets both the client\'s need and the standard.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.4 Release of Data to Qualified Personnel' }, { source: 'HIPAA', detail: 'Individual right of access to the designated record set' }],
    reviewNote: 'Verify how E.4 interacts with HIPAA and state client-access rights to raw test data, which may require release to the client.',
  },
  {
    id: 'nce-s-eth-036',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'scope of practice and competence',
    difficulty: 'medium',
    stem: 'A counselor plans to use a depression inventory with a client who immigrated from Vietnam a year ago and is learning English. The inventory was normed mainly on U.S.-born English speakers. What is the BEST ethical approach?',
    options: [
      { id: 'a', text: 'Use the inventory as usual, since depression symptoms appear the same across all cultures', isCorrect: false, rationale: 'Symptom expression and item meaning can differ across cultures and languages.' },
      { id: 'b', text: 'Use it with caution, note its norm limits, and weigh results with interviews and context', isCorrect: true, rationale: 'E.8 calls for cautious use of measures normed on other groups and cultural context.' },
      { id: 'c', text: 'Translate the items on the spot and score the client\'s answers with the published norms', isCorrect: false, rationale: 'An informal translation changes the test, so the published norms no longer apply.' },
      { id: 'd', text: 'Skip all formal assessment, since no standardized test can be fair to a recent immigrant', isCorrect: false, rationale: 'Assessment can be used with appropriate caution; avoiding it entirely is not required.' },
    ],
    rationale: 'E.8 directs counselors to select and use with caution assessment techniques normed on populations other than the client\'s, and to recognize the effects of culture, language, and other factors on administration and interpretation. Results are placed in the context of other information, and limits are noted in the report.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.8 Multicultural Issues/Diversity in Assessment' }, { source: 'Hays (Assessment)', detail: 'Culturally fair assessment and norm-group relevance' }],
  },
  {
    id: 'nce-s-eth-037',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'hard',
    stem: 'A site supervisor has given a post-master\'s supervisee written feedback for six months about missed risk assessments and late notes. Despite a written remediation plan, the problems continue. What is the supervisor\'s MOST appropriate next step?',
    options: [
      { id: 'a', text: 'Document the deficits, consult, and decline to endorse licensure while following due process', isCorrect: true, rationale: 'F.6.b supports remediation, consultation, and withholding endorsement with due process.' },
      { id: 'b', text: 'Endorse the supervisee for licensure anyway, since all of the required hours have been completed', isCorrect: false, rationale: 'Hours alone do not justify endorsing a supervisee who is not competent.' },
      { id: 'c', text: 'Quietly end supervision and let the supervisee find another supervisor without a record', isCorrect: false, rationale: 'Ending without documentation or due process sidesteps the gatekeeping role.' },
      { id: 'd', text: 'Report the supervisee to the licensing board for misconduct without telling the supervisee', isCorrect: false, rationale: 'Performance deficits call for documented gatekeeping steps, not a secret misconduct report.' },
    ],
    rationale: 'Supervisors act as gatekeepers. Under F.6.b, they identify limitations that could impede performance, help secure remediation, and when needed recommend dismissal or decline to endorse supervisees who are unable to provide competent services. They consult, document their decisions, and ensure the supervisee knows the options for addressing the decision.',
    references: [{ source: 'ACA Code of Ethics', detail: 'F.6.b Gatekeeping and Remediation' }],
  },
  {
    id: 'nce-s-eth-038',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'medium',
    stem: 'A counselor educator teaching a group counseling course requires students to take part in an experiential group as members. How should the educator handle evaluation of students in this experience?',
    options: [
      { id: 'a', text: 'Grade each student on how much personal material the student discloses in the group', isCorrect: false, rationale: 'Basing grades on depth of self-disclosure is what the Code prohibits.' },
      { id: 'b', text: 'Share notable disclosures with faculty so they can assess students\' fitness for practice', isCorrect: false, rationale: 'Students should know the risks of self-disclosure; casual sharing of it misuses the group.' },
      { id: 'c', text: 'Keep grades apart from the level of self-disclosure and explain the risks of disclosing', isCorrect: true, rationale: 'Section F requires that evaluation not depend on self-disclosure and that risks be explained.' },
      { id: 'd', text: 'Require that students disclose a past trauma, since depth is needed for group learning', isCorrect: false, rationale: 'Requiring specific personal disclosures exploits students and is not required to learn.' },
    ],
    rationale: 'When educational programs include self-growth or self-disclosure experiences, counselor educators inform students of the ethical ramifications of self-disclosure, and evaluation is not dependent on the student\'s level of self-disclosure. Many programs also use outside facilitators so the instructor does not evaluate what students reveal.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section F, self-growth experiences in counselor education' }, { source: 'CACREP 2024 Standards', detail: 'Experiential group learning in the group counseling core area' }],
    reviewNote: 'Confirm the exact ACA 2014 subsection number for self-growth experiences in Section F (believed to be F.8.c) before citing it.',
  },
  {
    id: 'nce-s-eth-039',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'easy',
    stem: 'After a session in which a new client mentions a popular online video channel she runs, the counselor is tempted to look up the channel and the client\'s public social media posts. What does the ACA Code of Ethics advise?',
    options: [
      { id: 'a', text: 'Viewing is fine, since anything posted publicly by a client is open to the counselor', isCorrect: false, rationale: 'Public availability does not override the Code\'s respect for client privacy online.' },
      { id: 'b', text: 'Viewing is fine if the counselor does not comment, like, or follow the client\'s posts', isCorrect: false, rationale: 'Passive viewing without consent still intrudes on the client\'s virtual presence.' },
      { id: 'c', text: 'Viewing is required, since it gives collateral information useful for diagnosis', isCorrect: false, rationale: 'There is no duty to search clients online, and doing so needs consent.' },
      { id: 'd', text: 'Respect the client\'s online privacy and view it only if the client gives consent', isCorrect: true, rationale: 'H.6.c directs counselors to respect clients\' social media privacy unless given consent.' },
    ],
    rationale: 'H.6.c directs counselors to respect the privacy of clients\' presence on social media unless given consent to view such information. Counselors also explain their own social media policies as part of informed consent (H.6.b).',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.6.c Client Virtual Presence' }],
  },
  {
    id: 'nce-s-eth-040',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'easy',
    stem: 'A counselor in solo practice is retiring and has paper files for clients seen over the past 15 years. How should the counselor handle retention and disposal of these records?',
    options: [
      { id: 'a', text: 'Discard all files in the office recycling bin once the practice has officially closed', isCorrect: false, rationale: 'Recycling bins expose confidential records and ignore retention requirements.' },
      { id: 'b', text: 'Keep files for the period state law requires, then destroy them in a secure manner', isCorrect: true, rationale: 'B.6.h links retention to law and requires disposal that protects confidentiality.' },
      { id: 'c', text: 'Give each file to a family member to store at home until the clients ask for them', isCorrect: false, rationale: 'Untrained family members lack authority and safeguards for client records.' },
      { id: 'd', text: 'Shred all files at once, since a closed practice has no further duty for its records', isCorrect: false, rationale: 'Retention duties continue after closing; immediate destruction may violate law.' },
    ],
    rationale: 'B.6.h directs counselors to store records after termination to ensure reasonable future access, to maintain them in accordance with federal and state law and licensure rules, and to dispose of them in a way that protects confidentiality, such as shredding. Retention periods are set by state law and vary. Counselors also plan for records in case of retirement or incapacity.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.6.h Storage and Disposal After Termination' }, { source: 'State law', detail: 'Record retention periods for licensed counselors' }],
  },
  {
    id: 'nce-s-eth-041',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'medium',
    stem: 'A counselor at a state agency is told that a new agency rule requires sharing full session notes with a client\'s employer whenever the employer pays for services. The counselor believes this conflicts with the ACA Code of Ethics. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Follow the rule without comment, since a legal requirement replaces any ethical code', isCorrect: false, rationale: 'I.1.c first calls for stating the ethical commitment and trying to resolve the conflict.' },
      { id: 'b', text: 'Make known the commitment to the Code and take steps to resolve the conflict', isCorrect: true, rationale: 'I.1.c directs counselors to state their commitment and work to resolve the conflict.' },
      { id: 'c', text: 'Refuse to follow the rule, since ethical codes take legal priority over agency rules', isCorrect: false, rationale: 'Ethical codes do not override law; outright refusal skips the steps the Code sets out.' },
      { id: 'd', text: 'Stop taking notes so that there is no record that could be given to employers', isCorrect: false, rationale: 'Failing to document violates record-keeping duties and does not resolve the conflict.' },
    ],
    rationale: 'Under I.1.c, when ethical responsibilities conflict with laws, regulations, or other legal authority, counselors make known their commitment to the ACA Code and take steps to resolve the conflict. If it cannot be resolved that way, counselors, acting in the client\'s best interest, may adhere to the legal requirement.',
    references: [{ source: 'ACA Code of Ethics', detail: 'I.1.c Conflicts Between Ethics and Laws' }],
  },
  {
    id: 'nce-s-eth-042',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'hard',
    stem: 'A counselor learns that a colleague has been billing insurers for family sessions that never took place. When she raised it privately, the colleague dismissed her concern and the billing continued. What should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Report it to the licensing board or another proper authority, since informal efforts failed', isCorrect: true, rationale: 'I.2.b calls for formal reporting when informal resolution fails or harm is likely.' },
      { id: 'b', text: 'Raise it with the colleague again every month, since informal resolution must still be continued', isCorrect: false, rationale: 'The Code does not require repeating failed informal efforts while harm continues.' },
      { id: 'c', text: 'Warn the colleague\'s clients about the billing so that they can decide to change counselors', isCorrect: false, rationale: 'Contacting the colleague\'s clients is not an appropriate reporting channel.' },
      { id: 'd', text: 'Drop the matter, since billing disputes are between insurers and providers, not counselors', isCorrect: false, rationale: 'Fraud is an ethical violation counselors are expected to address.' },
    ],
    rationale: 'I.2.a supports informal resolution first when appropriate. When an apparent violation has substantially harmed or is likely to harm others and is not appropriate for, or not resolved by, informal resolution, I.2.b directs counselors to take further action such as referral to state licensure boards, ethics committees, certification bodies, or institutional authorities.',
    references: [{ source: 'ACA Code of Ethics', detail: 'I.2.b Reporting Ethical Violations' }, { source: 'ACA Code of Ethics', detail: 'I.2.a Informal Resolution' }],
  },
  {
    id: 'nce-s-eth-043',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'medium',
    stem: 'A licensed professional counselor holds a master\'s in counseling and a doctorate in music history. On her practice website she calls herself "Dr." and lists her credentials. What does the ACA Code of Ethics say about this?',
    options: [
      { id: 'a', text: 'It is acceptable, since any earned doctorate allows the title "Dr." in every context', isCorrect: false, rationale: 'C.4.d restricts using "Dr." in a counseling context when the doctorate is unrelated.' },
      { id: 'b', text: 'It is acceptable if the website also lists her current state counseling license number too', isCorrect: false, rationale: 'A license number does not correct a misleading implication of doctoral-level competence.' },
      { id: 'c', text: 'It is acceptable as long as no client has ever complained that the title was misleading to them', isCorrect: false, rationale: 'Misrepresentation is unethical whether or not anyone complains.' },
      { id: 'd', text: 'It is misleading, because the doctorate is not in counseling or a closely related field', isCorrect: true, rationale: 'C.4.d bars implying doctoral-level competence with an unrelated doctorate.' },
    ],
    rationale: 'C.4.a requires accurate representation of credentials, and C.4.d states that counselors do not imply doctoral-level competence by using "Dr." in a counseling context when their doctorate is not in counseling or a related field. C.3.a likewise requires advertising to be accurate and not misleading.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.4.d Implying Doctoral-Level Competence' }, { source: 'ACA Code of Ethics', detail: 'C.3.a Accurate Advertising' }],
  },
  {
    id: 'nce-s-eth-044',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'hard',
    stem: 'A 78-year-old client with a terminal illness tells his counselor he is considering ending his life through his state\'s legal medical aid-in-dying process. He has no other risk factors. Under the ACA Code of Ethics, how should the counselor approach confidentiality?',
    options: [
      { id: 'a', text: 'Disclose the plan to his family at once, since any talk of dying requires a breach of trust', isCorrect: false, rationale: 'B.2.b gives counselors discretion; automatic disclosure is not required.' },
      { id: 'b', text: 'Arrange involuntary hospitalization, since his choice must be treated as suicidal', isCorrect: false, rationale: 'A lawful end-of-life choice is not automatically treated as a psychiatric emergency.' },
      { id: 'c', text: 'Use discretion on breaching, guided by consultation, law, and the client\'s situation', isCorrect: true, rationale: 'B.2.b gives counselors discretion, informed by consultation and applicable law.' },
      { id: 'd', text: 'Refer him to another counselor, since end-of-life choices fall outside counseling', isCorrect: false, rationale: 'Supporting end-of-life decision making is within the counselor\'s role.' },
    ],
    rationale: 'B.2.b gives counselors who work with terminally ill clients considering hastening death the option to maintain confidentiality, depending on applicable laws and the specific circumstances, after seeking consultation or supervision from appropriate professional and legal parties. Counselors also help clients explore options, values, and supports. State law on medical aid in dying varies.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.b Confidentiality Regarding End-of-Life Decisions' }, { source: 'State law', detail: 'Medical aid-in-dying statutes (legal in some states only)' }],
    reviewNote: 'Confirm the 2014 code location B.2.b for end-of-life confidentiality (the 2005 code placed end-of-life care at A.9).',
  },
  {
    id: 'nce-s-eth-045',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A 24-year-old client from a close-knit Mexican American family lives at home and gives part of his pay to his parents. The counselor, who values independence, begins urging him to move out to "become his own person." The client has not named this as a goal. What is the ethical concern?',
    options: [
      { id: 'a', text: 'The counselor is right to push independence, since adulthood requires leaving home', isCorrect: false, rationale: 'This is a culturally bound assumption, not a universal developmental requirement.' },
      { id: 'b', text: 'The counselor is imposing personal values instead of exploring the client\'s own', isCorrect: true, rationale: 'A.4.b bars imposing the counselor\'s values; goals should reflect the client\'s worldview.' },
      { id: 'c', text: 'The counselor should refer him, since cultural differences make counseling unworkable', isCorrect: false, rationale: 'Cultural difference is not grounds for referral; the counselor builds competence instead.' },
      { id: 'd', text: 'The concern is billing, since family issues are not covered as a reason for counseling', isCorrect: false, rationale: 'Billing is unrelated to the ethical issue of value imposition.' },
    ],
    rationale: 'A.4.b directs counselors to be aware of, and avoid imposing, their own values, attitudes, and beliefs. Many collectivist families see interdependence and financial support of parents as healthy. Goals should come from the client, explored within the client\'s cultural context (A.2.c, A.1.c).',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Individualism vs collectivism and culture-bound counseling values' }],
  },
  {
    id: 'nce-s-eth-046',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'informed consent and its required elements',
    difficulty: 'easy',
    stem: 'A counselor researcher is preparing a consent form for a study of coping in caregivers of people with dementia. Which statement is a required element of informed consent for research participants?',
    options: [
      { id: 'a', text: 'Participants may decline or withdraw at any time without penalty', isCorrect: true, rationale: 'G.2.a lists the freedom to withdraw without penalty as a required element.' },
      { id: 'b', text: 'Participants must finish the study once they have signed the form', isCorrect: false, rationale: 'Participation is voluntary throughout; withdrawal must be allowed.' },
      { id: 'c', text: 'Participants give up the right to see results in exchange for pay', isCorrect: false, rationale: 'Payment does not remove participant rights, and results may be shared.' },
      { id: 'd', text: 'Participants are told the hypotheses only after data have been used', isCorrect: false, rationale: 'Purposes and procedures are explained up front, except in justified deception.' },
    ],
    rationale: 'G.2.a requires researchers to explain the purpose and procedures, risks, benefits, alternatives, limits of confidentiality, the format and audience for results, and that participants are free to withdraw at any time without penalty. Consent is an ongoing process, not a one-time signature.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.2.a Informed Consent in Research' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Informed consent and voluntary participation' }],
  },
  {
    id: 'nce-s-eth-047',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'confidentiality and its limits',
    difficulty: 'medium',
    stem: 'A counselor in a community agency plans to survey clients about service satisfaction and later publish the findings. The agency has access to a university institutional review board (IRB). Which step is MOST appropriate before collecting data?',
    options: [
      { id: 'a', text: 'Begin the survey now, since satisfaction surveys of clients carry no risk to them', isCorrect: false, rationale: 'Research with clients involves risks, including pressure to participate and privacy.' },
      { id: 'b', text: 'Ask clients to put their names on surveys so their answers can be checked later', isCorrect: false, rationale: 'Collecting names without need raises risk; data should be de-identified when possible.' },
      { id: 'c', text: 'Collect the data first and seek a review only if the results turn out to be publishable', isCorrect: false, rationale: 'Review occurs before data collection, not after results are known.' },
      { id: 'd', text: 'Seek IRB review and plan how consent is obtained and how data will be kept private', isCorrect: true, rationale: 'Section G calls for review of research and for protecting participants\' consent and privacy.' },
    ],
    rationale: 'Section G directs counselors to follow applicable law and institutional review requirements, to obtain informed consent, and to protect the confidentiality of participant information. Planned publication makes this research rather than routine program evaluation, so IRB review is sought before data collection, and data are de-identified and stored securely.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section G, Research and Publication (institutional review and confidentiality of information)' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Institutional review boards and protection of participants' }],
    reviewNote: 'Check whether a specific G subsection (e.g., G.1.b or G.2.d) should be cited for IRB review and data confidentiality.',
  },
  {
    id: 'nce-s-eth-048',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'ethical decision-making models',
    difficulty: 'medium',
    stem: 'A counselor\'s outcome study finds that a group program her agency promotes did not reduce symptoms more than a waitlist. The agency director suggests leaving these results out of the annual report. What should the counselor do?',
    options: [
      { id: 'a', text: 'Omit the findings, since agency staff must support the programs their employer runs', isCorrect: false, rationale: 'Loyalty to an employer does not permit withholding results of professional value.' },
      { id: 'b', text: 'Adjust the analysis until the program shows a positive effect worth reporting on', isCorrect: false, rationale: 'Manipulating analyses to produce a result is a form of data distortion (G.4.a).' },
      { id: 'c', text: 'Report the results accurately, since unfavorable findings may not be withheld', isCorrect: true, rationale: 'G.4.b states that results reflecting unfavorably on programs are not withheld.' },
      { id: 'd', text: 'Report only the subgroups in which scores improved and describe them as overall gains', isCorrect: false, rationale: 'Selective reporting misrepresents results and violates G.4.a.' },
    ],
    rationale: 'G.4.a requires counselors to plan, conduct, and report research accurately without distorting data or biasing results. G.4.b states that results of professional value are reported, and results that reflect unfavorably on institutions, programs, services, or vested interests are not withheld.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.4.b Obligation to Report Unfavorable Results' }, { source: 'ACA Code of Ethics', detail: 'G.4.a Accurate Results' }],
  },
];
