// tools/nce/seed/ethics-1.js — Professional Practice and Ethics (24 original items)
module.exports = [
  {
    id: 'nce-s-eth-001',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'informed consent and its required elements',
    difficulty: 'easy',
    stem: 'A newly licensed counselor is drafting an informed consent document for a private practice. Which element is a required part of informed consent under the ACA Code of Ethics?',
    options: [
      { id: 'a', text: 'A guarantee that the presenting problem will improve within a set number of sessions', isCorrect: false, rationale: 'Counselors explain potential benefits and risks; promising a specific outcome is misleading.' },
      { id: 'b', text: 'An explanation of the limits of confidentiality and how fees and billing are handled', isCorrect: true, rationale: 'A.2.b lists confidentiality limits and fees and billing arrangements among required disclosures.' },
      { id: 'c', text: 'A summary of the counselor\'s personal religious and political values for the client', isCorrect: false, rationale: 'Counselors avoid imposing personal values (A.4.b); disclosing them is not a consent element.' },
      { id: 'd', text: 'A signed waiver releasing the counselor from liability for any outcome of treatment', isCorrect: false, rationale: 'Liability waivers are not part of informed consent and do not serve client welfare.' },
    ],
    rationale: 'Informed consent gives clients the information needed to choose whether to enter or continue counseling. ACA A.2.b names elements such as the purposes, goals, techniques, risks and benefits of services, the counselor\'s credentials, fees and billing, the limits of confidentiality, and the client\'s right to refuse services. Consent is an ongoing process, not a single signature.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.b Types of Information Needed' }],
  },
  {
    id: 'nce-s-eth-002',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'informed consent and its required elements',
    difficulty: 'medium',
    stem: 'A 12-year-old is brought to counseling by his custodial grandmother, who holds legal guardianship. The boy says he does not want to be there. How should the counselor BEST approach consent?',
    options: [
      { id: 'a', text: 'Treat the grandmother\'s signature as sufficient and skip any discussion with the boy', isCorrect: false, rationale: 'Legal consent from a guardian does not remove the duty to seek the minor\'s assent.' },
      { id: 'b', text: 'Decline to begin services until the boy is old enough to provide legal consent alone', isCorrect: false, rationale: 'Minors routinely receive counseling with guardian consent; refusing service is not required.' },
      { id: 'c', text: 'Let the boy decide alone whether to continue, since his preference overrides consent', isCorrect: false, rationale: 'A minor generally cannot give legal consent; the guardian\'s role cannot simply be set aside.' },
      { id: 'd', text: 'Obtain the guardian\'s consent and seek the boy\'s assent in language he can understand', isCorrect: true, rationale: 'A.2.d directs counselors to seek the assent of clients who cannot give consent and to include guardians.' },
    ],
    rationale: 'When a client cannot legally consent, counselors obtain consent from the parent or guardian and still seek the client\'s assent, explaining services in developmentally appropriate terms. This balances the guardian\'s legal rights with the minor\'s autonomy and welfare. Age-of-consent rules for minors vary by state, so counselors also check state law.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.d Inability to Give Consent' }],
  },
  {
    id: 'nce-s-eth-003',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'medium',
    stem: 'A counselor is starting a grief group for adults. During the first session, what should the counselor tell members about confidentiality?',
    options: [
      { id: 'a', text: 'That members are asked to keep what is shared private, but this cannot be guaranteed', isCorrect: true, rationale: 'B.4.a asks counselors to explain the importance and parameters of confidentiality in group work.' },
      { id: 'b', text: 'That group confidentiality is protected by the same law that binds the counselor', isCorrect: false, rationale: 'Group members are generally not bound by the counselor\'s legal duties; this overstates protection.' },
      { id: 'c', text: 'That confidentiality applies only to the counselor, so members may share freely', isCorrect: false, rationale: 'Members should be asked to respect each other\'s privacy; this undermines group safety.' },
      { id: 'd', text: 'That any member who discloses outside the group will face legal action by the counselor', isCorrect: false, rationale: 'This is an inaccurate threat; the counselor cannot enforce group confidentiality this way.' },
    ],
    rationale: 'In group work the counselor can promise to protect confidentiality but cannot guarantee that other members will. ACA B.4.a requires counselors to clearly explain the importance and parameters of confidentiality for the specific group. Setting this expectation at the outset supports informed consent and group trust.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.4.a Group Work' }],
  },
  {
    id: 'nce-s-eth-004',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'hard',
    stem: 'A client discloses a new diagnosis of a contagious, life-threatening disease and says she has not told her long-term partner, with whom she continues to have unprotected sex. State law permits disclosure in this situation. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Contact the partner right away and inform him of the diagnosis without telling the client', isCorrect: false, rationale: 'B.2.c calls for assessing the client\'s intent to inform the partner before any disclosure.' },
      { id: 'b', text: 'Keep the information confidential, since health conditions are outside the limits', isCorrect: false, rationale: 'B.2.c recognizes that disclosure to an identifiable third party at high risk may be justified.' },
      { id: 'c', text: 'Assess whether the client intends to inform her partner or to change the risky behavior', isCorrect: true, rationale: 'B.2.c directs counselors to assess client intent before disclosing to third parties at risk.' },
      { id: 'd', text: 'Refer the client to a medical provider and end counseling until she discloses to him', isCorrect: false, rationale: 'Ending services as leverage is coercive and may amount to abandonment (A.12).' },
    ],
    rationale: 'ACA B.2.c states that when clients disclose a contagious, life-threatening disease, counselors may be justified in disclosing to identifiable third parties at serious and foreseeable risk if laws permit. Before doing so, counselors assess the client\'s intent to inform those parties or to stop harmful behavior. State law varies, so counselors confirm what their jurisdiction permits or requires.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.c Contagious, Life-Threatening Diseases' }],
  },
  {
    id: 'nce-s-eth-005',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'easy',
    stem: 'During a session, a client names a former coworker, states he has bought a handgun, and describes a plan to shoot her at her home this weekend. Which action is MOST consistent with the counselor\'s ethical duties?',
    options: [
      { id: 'a', text: 'Keep the threat confidential and explore the client\'s anger at the next session', isCorrect: false, rationale: 'A specific, imminent threat to an identifiable person is a recognized limit of confidentiality.' },
      { id: 'b', text: 'Ask the client to sign a no-harm contract and continue with the planned session work', isCorrect: false, rationale: 'No-harm contracts do not reduce risk and do not meet the duty to protect an identified victim.' },
      { id: 'c', text: 'Take protective steps such as warning the victim or police, as state law directs', isCorrect: true, rationale: 'B.2.a permits disclosure to protect identified others from serious and foreseeable harm.' },
      { id: 'd', text: 'End the session early and refer the client to a psychiatrist for medication review', isCorrect: false, rationale: 'Referral alone does nothing to protect the identified person from imminent harm.' },
    ],
    rationale: 'Following Tarasoff v. Regents of the University of California (1976), counselors may have a duty to protect identifiable victims of serious threats. ACA B.2.a states that confidentiality does not apply when disclosure is required to protect identified others from serious and foreseeable harm. Whether the duty is mandatory or permissive, and what steps satisfy it, varies by state law.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }, { source: 'State law', detail: 'Duty-to-warn/protect statutes (mandatory vs permissive, Tarasoff)' }],
  },
  {
    id: 'nce-s-eth-006',
    domain: 'ethics',
    cacrep: 'helping_relationships',
    topic: 'duty to warn and protect',
    difficulty: 'medium',
    stem: 'A client frustrated about a custody dispute says, "Sometimes I could just kill my ex." He names no plan, has no weapons, has no history of violence, and laughs it off. What is the counselor\'s BEST response?',
    options: [
      { id: 'a', text: 'Explore the statement further to assess intent, plan, means, and history of violence', isCorrect: true, rationale: 'An ambiguous statement calls for violence risk assessment before any decision to disclose.' },
      { id: 'b', text: 'Notify the ex-spouse and local police immediately that a threat has been made', isCorrect: false, rationale: 'Breaching confidentiality without assessing seriousness or foreseeability is premature.' },
      { id: 'c', text: 'Ignore the remark, since venting about an ex-spouse is common in custody conflicts', isCorrect: false, rationale: 'Dismissing a statement of violence without assessment risks missing real danger.' },
      { id: 'd', text: 'Terminate services because the client has made a threat against another person', isCorrect: false, rationale: 'Termination does not address risk and may leave the client and others less safe.' },
    ],
    rationale: 'The duty to protect is triggered by serious and foreseeable harm, not by every angry remark. The counselor should assess intent, plan, means, target, and history, consult as needed, and document the reasoning. If assessment reveals a serious threat, protective action under B.2.a and state law follows.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-007',
    reviewNote: 'Rationale says counselors are mandated reporters \'in every U.S. state\'; definitions vary by state.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'medium',
    stem: 'A school-based counselor notices bruises in the shape of a hand on a 7-year-old\'s arm. The child says, "Dad gets mad," and then stops talking. The counselor is unsure whether abuse occurred. What should the counselor do?',
    options: [
      { id: 'a', text: 'Gather more evidence by questioning the parents before deciding whether to report', isCorrect: false, rationale: 'Investigating is the role of child protective services and may place the child at risk.' },
      { id: 'b', text: 'Wait to see whether new injuries appear before making a report to the authorities', isCorrect: false, rationale: 'Delay is not permitted once reasonable suspicion exists; certainty is not required.' },
      { id: 'c', text: 'Ask the child\'s teacher to make the report so the counseling relationship is protected', isCorrect: false, rationale: 'In most states the duty to report is personal and cannot be handed off to a colleague.' },
      { id: 'd', text: 'Make a report to child protective services based on reasonable suspicion of abuse', isCorrect: true, rationale: 'Mandated reporters report reasonable suspicion; proof or certainty is not required.' },
    ],
    rationale: 'Counselors are mandated reporters of suspected child abuse and neglect in every U.S. state. The threshold is reasonable suspicion or cause to believe, not proof, and the counselor should not investigate. Specific timelines, reporting agencies, and procedures vary by state law, and many school policies add internal notification steps.',
    references: [{ source: 'State law', detail: 'Child abuse reporting statutes: reasonable suspicion standard' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-008',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'hard',
    stem: 'A counselor in a HIPAA-covered agency keeps process notes about session dynamics and her own impressions in a file separate from the medical record. Under the HIPAA Privacy Rule, how are these notes treated?',
    options: [
      { id: 'a', text: 'They are part of the designated record set and may be released for any payment purpose', isCorrect: false, rationale: 'Separately kept psychotherapy notes are excluded from routine payment disclosures.' },
      { id: 'b', text: 'They are psychotherapy notes, and most disclosures require a specific authorization', isCorrect: true, rationale: 'HIPAA defines psychotherapy notes and requires specific authorization for most uses.' },
      { id: 'c', text: 'They lose all protection once a client signs a general release of medical information', isCorrect: false, rationale: 'A general release does not suffice; psychotherapy notes need their own authorization.' },
      { id: 'd', text: 'They must be given to the client on request under the HIPAA right of access to records', isCorrect: false, rationale: 'Psychotherapy notes are excluded from the HIPAA right of access, though state law may differ.' },
    ],
    rationale: 'HIPAA gives psychotherapy notes, meaning a counselor\'s notes analyzing session content that are kept separate from the medical record, special protection. Most uses and disclosures require a specific authorization, and they are excluded from the client\'s general right of access. Items such as diagnosis, medications, session times, and treatment plans are not psychotherapy notes.',
    references: [{ source: 'HIPAA', detail: 'Privacy Rule: psychotherapy notes definition and authorization (45 CFR 164.501, 164.508)' }],
  },
  {
    id: 'nce-s-eth-009',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'easy',
    stem: 'A competent adult client asks to see a copy of her counseling records. What does the ACA Code of Ethics direct the counselor to do?',
    options: [
      { id: 'a', text: 'Provide reasonable access, limiting it only with compelling evidence of harm to her', isCorrect: true, rationale: 'B.6.e directs reasonable access, limited only when access would cause the client harm.' },
      { id: 'b', text: 'Refuse the request, since counseling records belong only to the counselor and agency', isCorrect: false, rationale: 'Clients have a right of reasonable access to their own records under B.6.e.' },
      { id: 'c', text: 'Release the records only after she obtains a court order or a lawyer makes a request', isCorrect: false, rationale: 'No court order is needed for a competent client to access her own records.' },
      { id: 'd', text: 'Give her a summary only, because clients may not see the counselor\'s written records', isCorrect: false, rationale: 'The Code does not limit clients to summaries; it supports access and help interpreting records.' },
    ],
    rationale: 'ACA B.6.e states that counselors provide reasonable access to records and copies when requested by competent clients. Access is limited only when there is compelling evidence that it would cause harm to the client, and counselors document the request and their reasoning. Counselors also offer assistance in interpreting records (B.6.f).',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.6.e Client Access' }],
  },
  {
    id: 'nce-s-eth-010',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'Two years after ending counseling with a client, a counselor runs into the former client at a community event, and the former client asks the counselor out on a date. Under the ACA Code of Ethics, what applies?',
    options: [
      { id: 'a', text: 'A romantic relationship is allowed now, since more than one year has passed since the end', isCorrect: false, rationale: 'The ACA standard is five years, not one year.' },
      { id: 'b', text: 'A romantic relationship is allowed if a colleague agrees there is no risk of exploitation', isCorrect: false, rationale: 'Consultation does not override the five-year prohibition.' },
      { id: 'c', text: 'A romantic relationship is prohibited for five years after the last professional contact', isCorrect: true, rationale: 'A.5.c prohibits such relationships for five years following the last professional contact.' },
      { id: 'd', text: 'A romantic relationship is permitted as long as the former client initiated the request', isCorrect: false, rationale: 'Who initiates does not change the prohibition; responsibility rests with the counselor.' },
    ],
    rationale: 'ACA A.5.c prohibits sexual or romantic relationships with former clients, their romantic partners, or family members for five years after the last professional contact, in person or electronic. Even after five years, counselors must show forethought and document that the relationship is not exploitative. The responsibility rests with the counselor regardless of who initiates.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.5.c Sexual and/or Romantic Relationships With Former Clients' }],
  },
  {
    id: 'nce-s-eth-011',
    domain: 'ethics',
    cacrep: 'helping_relationships',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'A counselor in a small rural town is invited by a long-term client to attend the client\'s high school graduation, which the client has worked toward despite major barriers. The counselor believes attending could benefit the client. What should the counselor do?',
    options: [
      { id: 'a', text: 'Decline, because any contact outside the office is an ethical violation for counselors', isCorrect: false, rationale: 'The Code permits boundary extensions that benefit clients when handled with safeguards.' },
      { id: 'b', text: 'Weigh benefits and risks, discuss it with the client, and document the rationale', isCorrect: true, rationale: 'A.6.b asks counselors to document rationale, benefit, and anticipated consequences.' },
      { id: 'c', text: 'Attend without discussion, since a graduation is a public event open to everyone', isCorrect: false, rationale: 'A boundary extension should be discussed and documented, not done casually.' },
      { id: 'd', text: 'Attend only if the client agrees to end counseling before the graduation ceremony', isCorrect: false, rationale: 'Terminating services to permit contact is unnecessary and harms the client.' },
    ],
    rationale: 'ACA A.6.b recognizes that extending boundaries, such as attending a formal ceremony, can benefit clients. Before doing so, counselors document the rationale, potential benefit, and anticipated consequences, and take precautions such as informed consent, consultation, and supervision. Rural settings make such decisions more common, which increases the need for careful reasoning.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.6.b Extending Counseling Boundaries' }],
  },
  {
    id: 'nce-s-eth-012',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'scope of practice and competence',
    difficulty: 'hard',
    stem: 'A licensed counselor completes a one-day introductory workshop on a specialized trauma therapy and wants to start using it with several clients who have complex trauma. Which course of action BEST meets the counselor\'s ethical obligations?',
    options: [
      { id: 'a', text: 'Use the method now, since the counselor\'s license covers all trauma treatments', isCorrect: false, rationale: 'A license defines legal scope, not competence in every specialized method.' },
      { id: 'b', text: 'Use the method now but tell clients it is experimental and get written consent', isCorrect: false, rationale: 'Consent does not replace the training needed to use a new specialty competently.' },
      { id: 'c', text: 'Use the method now, since a workshop certificate shows enough competence to practice', isCorrect: false, rationale: 'A single introductory workshop rarely provides the training and supervision C.2.b requires.' },
      { id: 'd', text: 'Pursue further training and supervised practice before using it, and refer if needed', isCorrect: true, rationale: 'C.2.b requires education, training, and supervised experience before practicing a new specialty.' },
    ],
    rationale: 'ACA C.2.a limits practice to the boundaries of competence based on education, training, supervised experience, and credentials. When entering a new specialty area, C.2.b requires appropriate education, training, and supervised experience, and steps to protect clients from harm while skills develop. Referral is appropriate when the counselor cannot yet provide competent care.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.b New Specialty Areas of Practice' }, { source: 'ACA Code of Ethics', detail: 'C.2.a Boundaries of Competence' }],
  },
  {
    id: 'nce-s-eth-013',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'easy',
    stem: 'A counselor wants guidance on keeping separate professional and personal social media profiles. Which section of the 2014 ACA Code of Ethics MOST directly addresses this issue?',
    options: [
      { id: 'a', text: 'Section B, Confidentiality and Privacy', isCorrect: false, rationale: 'Section B covers privacy broadly but social media is addressed in Section H.' },
      { id: 'b', text: 'Section D, Relationships With Others', isCorrect: false, rationale: 'Section D addresses relationships with colleagues and other professionals.' },
      { id: 'c', text: 'Section C, Professional Responsibility', isCorrect: false, rationale: 'Section C covers competence, advertising, and credentials, not social media profiles.' },
      { id: 'd', text: 'Section H, Distance Counseling', isCorrect: true, rationale: 'Section H covers distance counseling, technology, and social media, including H.6.' },
    ],
    rationale: 'The 2014 ACA Code has nine sections, A through I. Section H, Distance Counseling, Technology, and Social Media, was new in 2014; H.6.a directs counselors who keep both a professional and a personal presence on social media to create separate profiles. Knowing the section layout helps counselors find guidance quickly.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section H; H.6.a Virtual Professional Presence' }],
  },
  {
    id: 'nce-s-eth-014',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A licensed counselor who also holds the National Certified Counselor (NCC) credential is accused of an ethics violation. Which statement about the NBCC Code of Ethics is accurate?',
    options: [
      { id: 'a', text: 'It replaces the state licensing board, so state law no longer applies to the counselor', isCorrect: false, rationale: 'State licensure law applies independently of national certification.' },
      { id: 'b', text: 'It binds NCCs, and NBCC can act on the certification apart from any state board action', isCorrect: true, rationale: 'NBCC enforces its Code for its certificants; boards enforce licensure separately.' },
      { id: 'c', text: 'It applies only to counselor educators who teach in CACREP-accredited graduate programs', isCorrect: false, rationale: 'The NBCC Code applies to NCCs and applicants, not only to educators.' },
      { id: 'd', text: 'It is advisory only, so NBCC cannot suspend or revoke a credential for a violation', isCorrect: false, rationale: 'NBCC can impose sanctions on certification, including revocation.' },
    ],
    rationale: 'The NBCC Code of Ethics applies to National Certified Counselors and applicants for NBCC credentials. NBCC can investigate complaints and sanction or revoke certification, which is separate from any action a state licensing board takes on a license. A counselor may therefore answer to more than one body for the same conduct.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Scope and application to NCCs and applicants; enforcement of certification' }],
  },
  {
    id: 'nce-s-eth-015',
    reviewNote: 'Stadler\'s tests are cited to Corey\'s ethical decision-making chapter in general, not a section.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'medium',
    stem: 'While evaluating a chosen course of action, a counselor asks, "Would I be comfortable if this decision were reported in the local newspaper?" Which test from Stadler\'s model is the counselor applying?',
    options: [
      { id: 'a', text: 'The test of justice', isCorrect: false, rationale: 'Justice asks whether the counselor would treat others in the same situation the same way.' },
      { id: 'b', text: 'The test of universality', isCorrect: false, rationale: 'Universality asks whether the counselor would recommend the action to others in the same situation.' },
      { id: 'c', text: 'The test of publicity', isCorrect: true, rationale: 'Publicity asks whether the counselor would be comfortable having the action made public.' },
      { id: 'd', text: 'The test of fidelity', isCorrect: false, rationale: 'Fidelity is a moral principle about keeping commitments, not one of Stadler\'s tests.' },
    ],
    rationale: 'Many ethical decision-making models, including the Forester-Miller and Davis practitioner\'s guide, include Stadler\'s three tests for evaluating a selected action. Justice asks whether others would be treated the same, publicity asks whether the counselor would accept public reporting, and universality asks whether the counselor would recommend it to colleagues. Passing all three supports the soundness of the decision.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Ethical issues: steps in ethical decision making' }],
  },
  {
    id: 'nce-s-eth-016',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'hard',
    stem: 'A clinical supervisor learns that a post-master\'s supervisee has not told clients that she is under supervision or that their cases are discussed with the supervisor. What is the supervisor\'s MOST appropriate response?',
    options: [
      { id: 'a', text: 'Require the supervisee to inform clients of her status and how supervision affects privacy', isCorrect: true, rationale: 'F.1.c requires that clients know supervisee qualifications and supervision\'s effect on confidentiality.' },
      { id: 'b', text: 'Allow it, since supervision is internal and does not change confidentiality for clients', isCorrect: false, rationale: 'Case discussion with a supervisor is a disclosure clients must be told about.' },
      { id: 'c', text: 'Report the supervisee to the licensing board before discussing the problem with her', isCorrect: false, rationale: 'Corrective supervision is the first step; a board report is premature here.' },
      { id: 'd', text: 'End the supervision contract at once and tell the supervisee to find a new supervisor', isCorrect: false, rationale: 'Abrupt termination leaves clients unprotected and skips remediation.' },
    ],
    rationale: 'A supervisor\'s primary obligation is to monitor the welfare of the clients served by the supervisee (F.1.a). Supervisors ensure that clients are aware of the supervisee\'s qualifications and of how the supervision process affects the limits of confidentiality (F.1.c). Supervisors share responsibility for client care and should correct the problem promptly through supervision.',
    references: [{ source: 'ACA Code of Ethics', detail: 'F.1.c Informed Consent and Client Rights' }, { source: 'ACA Code of Ethics', detail: 'F.1.a Client Welfare' }],
  },
  {
    id: 'nce-s-eth-017',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'easy',
    stem: 'Which statement BEST describes the difference between state licensure and national certification for counselors?',
    options: [
      { id: 'a', text: 'Licensure is legal permission to practice in a state; certification is a voluntary credential', isCorrect: true, rationale: 'Licensure is state regulation; certifications such as the NCC are voluntary and national.' },
      { id: 'b', text: 'Certification is required by law in every state; licensure is optional for private practice', isCorrect: false, rationale: 'This reverses the two; licensure is the legal requirement for independent practice.' },
      { id: 'c', text: 'Licensure and certification are the same credential, issued by different agencies by region', isCorrect: false, rationale: 'They are distinct credentials with different legal weight and issuing bodies.' },
      { id: 'd', text: 'Certification allows practice in all states; licensure applies only to school counselors', isCorrect: false, rationale: 'National certification does not authorize practice in any state.' },
    ],
    rationale: 'Licensure is a state legal credential that regulates the practice and title of professional counseling within that jurisdiction. National certification, such as the NBCC\'s National Certified Counselor credential, is voluntary and shows that a counselor met national standards but does not by itself permit practice. Interstate practice is addressed through state law and mechanisms such as the Counseling Compact.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Credentialing: licensure, certification, and accreditation' }],
  },
  {
    id: 'nce-s-eth-018',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A counselor learns that a client who uses a wheelchair is being denied a reasonable accommodation by her landlord. The counselor wants to contact the housing authority about this client\'s case. What must the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Contact the housing authority right away, since advocacy is a core professional duty', isCorrect: false, rationale: 'Advocating for an identifiable client without consent breaches confidentiality.' },
      { id: 'b', text: 'Avoid advocacy entirely, because it falls outside the counselor\'s professional role', isCorrect: false, rationale: 'A.7.a affirms advocacy to address barriers to client growth and development.' },
      { id: 'c', text: 'Write a public letter about the landlord to raise awareness of housing discrimination', isCorrect: false, rationale: 'Publicizing the case exposes the client and still lacks her consent.' },
      { id: 'd', text: 'Obtain the client\'s consent before advocating on her behalf as an identifiable client', isCorrect: true, rationale: 'A.7.b requires client consent before advocating on behalf of an identifiable client.' },
    ],
    rationale: 'ACA A.7.a supports advocacy at individual, group, institutional, and societal levels to address barriers that inhibit client growth. A.7.b requires counselors to obtain client consent before engaging in advocacy on behalf of an identifiable client. Seeking consent also respects the client\'s autonomy and may support her own self-advocacy.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.7.b Confidentiality and Advocacy' }],
  },
  {
    id: 'nce-s-eth-019',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'medium',
    stem: 'A counselor licensed in one state is asked to provide video counseling to a client who lives in another state. Which consideration is MOST important before beginning?',
    options: [
      { id: 'a', text: 'Only the laws of the counselor\'s home state apply, since that is where the license is', isCorrect: false, rationale: 'H.1.b notes that the client\'s state laws may also apply.' },
      { id: 'b', text: 'The counselor may be subject to the laws of both the counselor\'s and client\'s locations', isCorrect: true, rationale: 'H.1.b directs counselors to know the laws of both locations in distance counseling.' },
      { id: 'c', text: 'Licensure rules do not apply to video sessions, since no in-person contact takes place', isCorrect: false, rationale: 'Distance counseling is still the practice of counseling and is regulated.' },
      { id: 'd', text: 'Any license is valid nationwide for telehealth as long as the platform is encrypted', isCorrect: false, rationale: 'Encryption addresses security, not legal authority to practice across states.' },
    ],
    rationale: 'ACA H.1.b states that counselors providing distance services understand they may be subject to the laws and regulations of both their practicing location and the client\'s place of residence. In practice, many states regulate based on where the client is located, and rules vary by state. Interstate options such as the Counseling Compact apply only among member states.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.1.b Laws and Statutes' }, { source: 'Counseling Compact', detail: 'Privilege to practice in member states' }],
  },
  {
    id: 'nce-s-eth-020',
    reviewNote: 'Confirm ACA H.2.a explicitly lists emergency procedures among telehealth informed-consent items.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'easy',
    stem: 'A counselor is starting video sessions with a new client who has a history of suicidal ideation. Which step is MOST important to complete during the first telehealth session?',
    options: [
      { id: 'a', text: 'Ask the client to keep the camera off so that the session feels less intrusive', isCorrect: false, rationale: 'Turning off video reduces the counselor\'s ability to assess and does not address safety.' },
      { id: 'b', text: 'Record the session so it can be reviewed later if any emergency happens', isCorrect: false, rationale: 'Recording requires consent and does nothing to prepare for an emergency.' },
      { id: 'c', text: 'Confirm the client\'s location and a local emergency plan and contact person', isCorrect: true, rationale: 'Knowing the client\'s location and local resources is essential for responding to a crisis.' },
      { id: 'd', text: 'Use any free video app the client prefers so that the client feels comfortable', isCorrect: false, rationale: 'Platforms must protect confidentiality; preference alone is not the standard (H.2.d).' },
    ],
    rationale: 'Distance counseling requires planning for emergencies the counselor cannot handle in person. Counselors confirm the client\'s physical location, identify local emergency services, and agree on a plan as part of telehealth informed consent (H.2.a). This is especially important for clients with elevated risk.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.2.a Informed Consent and Disclosure' }],
  },
  {
    id: 'nce-s-eth-021',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'termination and referral',
    difficulty: 'medium',
    stem: 'A counselor with strong religious beliefs is assigned a client who wants help with stress in her same-sex marriage. The counselor feels uncomfortable and wants to refer the client elsewhere. What does the ACA Code of Ethics state?',
    options: [
      { id: 'a', text: 'Referral is appropriate whenever a client\'s issue conflicts with the counselor\'s faith', isCorrect: false, rationale: 'A.11.b prohibits referral based solely on the counselor\'s personally held values.' },
      { id: 'b', text: 'Referral is required, since counselors must avoid any client whose values differ', isCorrect: false, rationale: 'The Code calls for respecting diversity and avoiding value imposition, not avoiding clients.' },
      { id: 'c', text: 'Referral based only on the counselor\'s personal values is not permitted by the Code', isCorrect: true, rationale: 'A.11.b prohibits values-based referral; counselors seek training to work with diverse clients.' },
      { id: 'd', text: 'Referral is acceptable if the counselor explains the religious reason to the client', isCorrect: false, rationale: 'Explaining the reason does not make a values-based referral ethical and may harm the client.' },
    ],
    rationale: 'ACA A.11.b states that counselors refrain from referring prospective and current clients based solely on the counselor\'s personally held values, attitudes, beliefs, and behaviors. A.4.b directs counselors to avoid imposing their own values. Counselors seek training and supervision when values affect their work, and referral is reserved for genuine gaps in competence.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.b Values Within Termination and Referral' }, { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-eth-022',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'hard',
    stem: 'A counselor notices that a colleague has been arriving late, smelling of alcohol, and falling asleep in team meetings. The colleague carries a full caseload. What should the counselor do FIRST, if it can be done safely?',
    options: [
      { id: 'a', text: 'Speak privately with the colleague about the concerns and encourage seeking help', isCorrect: true, rationale: 'C.2.g and I.2.a support helping colleagues recognize impairment and informal resolution first.' },
      { id: 'b', text: 'File a complaint with the state licensing board without speaking to the colleague', isCorrect: false, rationale: 'Formal reports follow when informal steps fail or clients face imminent harm.' },
      { id: 'c', text: 'Tell the colleague\'s clients about the concerns so that they can make choices', isCorrect: false, rationale: 'This breaches the colleague\'s privacy and is not the counselor\'s role.' },
      { id: 'd', text: 'Say nothing, since a colleague\'s personal life is outside the counselor\'s concern', isCorrect: false, rationale: 'The Code expects counselors to act when colleague impairment may harm clients.' },
    ],
    rationale: 'ACA C.2.g asks counselors to monitor themselves for impairment and to assist colleagues or supervisors in recognizing their own impairment, providing consultation and help when warranted. I.2.a directs counselors to first attempt informal resolution with a colleague when feasible. If the problem persists or clients are at substantial risk, counselors take further action, such as reporting to supervisors or the licensing board.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }, { source: 'ACA Code of Ethics', detail: 'I.2.a Informal Resolution' }],
  },
  {
    id: 'nce-s-eth-023',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'easy',
    stem: 'A student comparing master\'s programs in clinical mental health counseling asks which organization accredits counseling graduate programs. Which organization is it?',
    options: [
      { id: 'a', text: 'NBCC', isCorrect: false, rationale: 'The National Board for Certified Counselors (NBCC) grants national certification (such as the NCC) and administers the NCE.' },
      { id: 'b', text: 'CACREP', isCorrect: true, rationale: 'The Council for Accreditation of Counseling and Related Educational Programs (CACREP) accredits master\'s and doctoral counseling programs.' },
      { id: 'c', text: 'ACA', isCorrect: false, rationale: 'The American Counseling Association (ACA) is a professional membership association that publishes the Code of Ethics.' },
      { id: 'd', text: 'AMHCA', isCorrect: false, rationale: 'The American Mental Health Counselors Association (AMHCA) is a professional association for clinical mental health counselors.' },
    ],
    rationale: 'CACREP, the Council for Accreditation of Counseling and Related Educational Programs, accredits counseling graduate programs. NBCC certifies individual counselors and administers the NCE, while ACA and its divisions and affiliates, such as AMHCA and ASCA, are membership associations. State licensing boards regulate practice within each state.',
    references: [{ source: 'CACREP 2024 Standards', detail: 'Accreditation of counseling master\'s and doctoral programs' }, { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Professional organizations and accreditation' }],
  },
  {
    id: 'nce-s-eth-024',
    reviewNote: 'Cited as ACA G.2 generally; confirm subsection letters for deception and debriefing.',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'medium',
    stem: 'A counselor researcher wants to study help-seeking and plans to briefly mislead participants about the study\'s true aim, because full disclosure would bias their answers. Under the ACA Code of Ethics, when is this acceptable?',
    options: [
      { id: 'a', text: 'Whenever participants have signed a general consent form for the overall study', isCorrect: false, rationale: 'General consent does not by itself justify deception.' },
      { id: 'b', text: 'Whenever the researcher believes the study results will be published widely', isCorrect: false, rationale: 'Publication plans do not justify deceiving participants.' },
      { id: 'c', text: 'Whenever participants are students, since course credit offsets any harm done', isCorrect: false, rationale: 'Students need added protection, and credit does not offset deception.' },
      { id: 'd', text: 'Only if no alternative is feasible, the value justifies it, and debriefing follows', isCorrect: true, rationale: 'G.2 permits deception only when alternatives are not feasible, value justifies it, and debriefing occurs.' },
    ],
    rationale: 'The ACA Code allows deception in research only when alternative procedures are not feasible and the prospective value of the research justifies it. Deception that is likely to cause physical or emotional harm is not permitted, and researchers explain the deception during debriefing as soon as feasible. Institutional review boards also review such designs.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.2 Rights of Research Participants (deception and debriefing)' }],
  },
];
