// tools/nce/seed/ethics-3.js — Professional Practice and Ethics, batch 3
// Hand-authored original items (nce-s-eth-049 … nce-s-eth-072).
module.exports = [
  {
    id: 'nce-s-eth-049',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'medium',
    stem: 'A 68-year-old client with an intellectual disability lives in a licensed group home. She tells her counselor that night staff often lock the pantry and send her to bed without dinner as punishment. She has lost weight since her last visit. State law names counselors as mandated reporters of abuse and neglect of vulnerable adults. What should the counselor do?',
    options: [
      { id: 'a', text: 'Tell the group home administrator, who is responsible for investigating staff', isCorrect: false, rationale: 'Notifying the facility does not satisfy a statutory duty to report to the designated agency, and the facility has a conflict of interest.' },
      { id: 'b', text: 'Wait until the client shows clear physical injury before making any report', isCorrect: false, rationale: 'Reporting laws require reasonable suspicion, not proof of injury; withholding food as punishment is itself neglect or abuse.' },
      { id: 'c', text: 'Report the suspected neglect to adult protective services or the named agency', isCorrect: true, rationale: 'A mandated reporter with reasonable suspicion reports to the agency the statute designates, such as adult protective services.' },
      { id: 'd', text: 'Keep the disclosure confidential unless the client signs a release to share it', isCorrect: false, rationale: 'Confidentiality yields when law requires disclosure (ACA B.2.a); a release is not needed for a mandated report.' },
    ],
    rationale: 'Most states require counselors to report suspected abuse, neglect or exploitation of older or vulnerable adults to adult protective services or another designated agency, and the threshold is reasonable suspicion rather than proof. ACA B.2.a recognizes that confidentiality does not apply when legal requirements demand disclosure. Telling the facility alone does not meet the duty.',
    references: [{ source: 'State law', detail: 'Vulnerable adult / adult protective services mandatory reporting statutes (vary by state)' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-050',
    reviewNote: 'Reporting of past abuse disclosed by an adult varies widely by state; confirm the framing that the duty turns on state statute and current risk to children.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'hard',
    stem: 'A 36-year-old client discloses that an uncle sexually abused her from ages 8 to 11. She does not want to file a report. In passing, she mentions that the uncle now coaches a youth soccer team. How should the counselor approach the question of reporting?',
    options: [
      { id: 'a', text: 'Make no report, since child abuse laws cover only victims who are minors now', isCorrect: false, rationale: 'Some states require or permit reports when the alleged abuser has current access to children, so this is too absolute.' },
      { id: 'b', text: 'Report at once, since abuse of a child must be reported regardless of when it occurred', isCorrect: false, rationale: 'Many states do not require reports of past abuse disclosed by an adult; the counselor must check the statute.' },
      { id: 'c', text: 'Ask the client to file her own police report before discussing the abuse further', isCorrect: false, rationale: 'Making the report a condition of counseling ignores client autonomy and does not resolve the counselor\'s own duty.' },
      { id: 'd', text: 'Check the state statute and consult, weighing that children may be at present risk', isCorrect: true, rationale: 'The duty depends on state law, and current access to children is the key fact; consultation and the client\'s involvement guide next steps.' },
    ],
    rationale: 'Mandated reporting laws are written mainly to protect children who are currently at risk, and states differ on whether a report is required when an adult discloses abuse from childhood. Some states require or allow a report when the alleged abuser still has access to children. The counselor reviews the specific statute, consults, documents the reasoning, and involves the client in the process where possible.',
    references: [{ source: 'State law', detail: 'Child abuse reporting statutes: adult disclosure of past abuse and current risk to minors' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-051',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'easy',
    stem: 'A counselor has just phoned in a report of suspected child neglect to the state child protection hotline. Which documentation practice is MOST appropriate?',
    options: [
      { id: 'a', text: 'Note the date, time, facts reported, agency worker\'s name and report number', isCorrect: true, rationale: 'A factual record of what was reported, when and to whom shows that the legal duty was met.' },
      { id: 'b', text: 'Keep no note of the call, so that the family cannot later learn who reported', isCorrect: false, rationale: 'Failing to document leaves no record that the duty was fulfilled; reporter identity is protected by law.' },
      { id: 'c', text: 'Record the counselor\'s conclusion about which parent is guilty of the neglect', isCorrect: false, rationale: 'Records should contain observed facts and disclosures, not conclusions of guilt, which are for investigators.' },
      { id: 'd', text: 'Store the report details only in a personal file kept at the counselor\'s home', isCorrect: false, rationale: 'Records belong in the secure clinical record, not in a personal file outside the agency or practice.' },
    ],
    rationale: 'After a mandated report, the counselor documents objective facts: the date and time of the report, the agency contacted, the name of the person who took it, any reference number, and the information conveyed, including the client\'s own words where relevant. This record shows the legal duty was met and supports continuity of care. Speculation about guilt does not belong in the note.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Documenting mandated reports and critical incidents' }, { source: 'State law', detail: 'Child abuse and neglect reporting procedures' }],
  },
  {
    id: 'nce-s-eth-052',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'easy',
    stem: 'Under the Family Educational Rights and Privacy Act (FERPA), when do the rights to inspect and control a student\'s education records transfer from the parents to the student?',
    options: [
      { id: 'a', text: 'When the student turns 16 and may leave school', isCorrect: false, rationale: 'FERPA does not tie the transfer of rights to compulsory-attendance age.' },
      { id: 'b', text: 'At age 18, or on entering college at any age', isCorrect: true, rationale: 'The student becomes an "eligible student" at 18 or on attending a postsecondary institution.' },
      { id: 'c', text: 'On graduating from high school, whatever the age', isCorrect: false, rationale: 'Graduation alone does not transfer FERPA rights; age 18 or postsecondary attendance does.' },
      { id: 'd', text: 'At age 21, the age set for all federal privacy laws', isCorrect: false, rationale: 'FERPA sets 18, and there is no single age for all federal privacy laws.' },
    ],
    rationale: 'FERPA gives parents rights over their child\'s education records until the student turns 18 or attends a postsecondary institution, at which point the student becomes an "eligible student" and the rights transfer. Schools may still disclose to parents in limited situations, such as when the student is a tax dependent or in a health or safety emergency.',
    references: [{ source: 'FERPA', detail: '34 CFR 99.3 and 99.5: eligible student and transfer of parental rights' }],
  },
  {
    id: 'nce-s-eth-053',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'medium',
    stem: 'A middle school counselor jots brief notes after student meetings to jog her memory. A parent asks to see "everything the school has" on his son. Under FERPA, which condition would keep the counselor\'s notes outside the definition of education records?',
    options: [
      { id: 'a', text: 'They are typed on a school computer and saved in the student\'s file', isCorrect: false, rationale: 'Placing notes in the student file makes them part of the education record.' },
      { id: 'b', text: 'They are shared with the student support team to plan interventions', isCorrect: false, rationale: 'Once notes are revealed to others, the sole-possession exclusion is lost.' },
      { id: 'c', text: 'They are labeled "confidential" and locked in the main office cabinet', isCorrect: false, rationale: 'A label and a lock do not change status if others in the office can access them.' },
      { id: 'd', text: 'They are used only as her memory aid and are not shown to anyone else', isCorrect: true, rationale: 'Sole-possession records kept as a personal memory aid and not shared are excluded from education records.' },
    ],
    rationale: 'FERPA excludes from "education records" notes that are kept in the sole possession of the maker, used only as a personal memory aid, and not accessible or revealed to any other person except a temporary substitute. Once such notes are shared, placed in the student file, or used to make decisions, they become education records that parents may inspect.',
    references: [{ source: 'FERPA', detail: '34 CFR 99.3 definition of education records: sole-possession exclusion' }],
  },
  {
    id: 'nce-s-eth-054',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'hard',
    stem: 'A client at a HIPAA-covered clinic reads her records and asks the counselor to change an intake note that lists past alcohol misuse, which she says is wrong. The counselor reviewed the intake carefully and believes the note is accurate and complete. What does the HIPAA Privacy Rule require?',
    options: [
      { id: 'a', text: 'Delete the note, because clients control the content of their own records', isCorrect: false, rationale: 'Clients may request amendment, but the provider is not required to accept a change it finds inaccurate.' },
      { id: 'b', text: 'Refuse to discuss it, because clients may view but not seek changes to records', isCorrect: false, rationale: 'HIPAA gives individuals an explicit right to request amendment of their records.' },
      { id: 'c', text: 'Answer in writing; if denied, explain why and let her file a disagreement', isCorrect: true, rationale: 'A denial must be written, give the basis, and tell the client she may submit a statement of disagreement.' },
      { id: 'd', text: 'Amend it only if a supervisor agrees, then send the change to all insurers', isCorrect: false, rationale: 'Supervisor approval is not the HIPAA standard, and blanket disclosure to insurers violates minimum necessary.' },
    ],
    rationale: 'Under 45 CFR 164.526, individuals may ask a covered entity to amend their protected health information. The entity may deny the request if the information is accurate and complete, but it must respond in writing within set time limits, state the basis for denial, and explain the right to file a statement of disagreement that is then linked to the record. Disclosures of the amendment follow the minimum necessary standard.',
    references: [{ source: 'HIPAA', detail: '45 CFR 164.526 Amendment of protected health information' }],
  },
  {
    id: 'nce-s-eth-055',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A counselor is licensed in her state, holds the National Certified Counselor (NCC) credential, and is a member of the American Counseling Association. Which ethical standards apply to her professional conduct?',
    options: [
      { id: 'a', text: 'The ACA Code, the NBCC Code and her licensing board\'s rules all apply', isCorrect: true, rationale: 'Each body binds her through a separate tie: membership, certification and licensure.' },
      { id: 'b', text: 'Only the state board rules, since licensure overrides voluntary codes', isCorrect: false, rationale: 'Licensure does not cancel obligations she accepted by joining ACA and holding the NCC.' },
      { id: 'c', text: 'Only the NBCC Code, since national certification outranks state law', isCorrect: false, rationale: 'National certification does not outrank state law; licensure regulates legal practice.' },
      { id: 'd', text: 'Only whichever code is strictest, as the others then fall away entirely', isCorrect: false, rationale: 'All applicable codes remain in force; she is accountable to each body separately.' },
    ],
    rationale: 'Counselors are often bound by several codes at once. ACA members agree to follow the ACA Code of Ethics, NCCs and applicants are bound by the NBCC Code of Ethics, and licensees must follow the rules and code adopted by their state board. Each body can act on a violation within its own authority, so the counselor attends to all of them.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Application to NCCs and applicants' }, { source: 'ACA Code of Ethics', detail: 'Preamble and Purpose: application to ACA members' }],
  },
  {
    id: 'nce-s-eth-056',
    reviewNote: 'Confirm the current NBCC Code wording on self-reporting duties and the 60-day window cited in the rationale.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A National Certified Counselor receives a public reprimand from her state licensing board for a documentation lapse. She wonders whether she must tell NBCC, since the matter was handled by the state. What does the NBCC Code of Ethics expect?',
    options: [
      { id: 'a', text: 'No notice is needed, as NBCC reviews only complaints that clients file', isCorrect: false, rationale: 'NBCC can act on licensure discipline as well as on client complaints.' },
      { id: 'b', text: 'She reports the board action to NBCC within the time the Code sets', isCorrect: true, rationale: 'The NBCC Code requires NCCs to report disciplinary actions by licensing boards to NBCC.' },
      { id: 'c', text: 'She tells NBCC only if the board fully revokes or suspends her license', isCorrect: false, rationale: 'The reporting duty is not limited to revocation or suspension.' },
      { id: 'd', text: 'She waits for the renewal form and mentions it at her next recertification', isCorrect: false, rationale: 'The Code sets a reporting window rather than deferring disclosure to renewal.' },
    ],
    rationale: 'The NBCC Code of Ethics requires NCCs to report to NBCC disciplinary actions taken by licensing or credentialing bodies, along with certain legal matters, within a set period (60 days in recent versions). This lets NBCC decide independently whether action on the certification is warranted.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'NCC duty to report licensure discipline and legal actions to NBCC' }],
  },
  {
    id: 'nce-s-eth-057',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'medium',
    stem: 'Two months after her father\'s death, a counselor finds herself tearful and distracted in sessions with several bereaved clients, and she lost track of one client\'s risk disclosure last week. What is her MOST appropriate course of action?',
    options: [
      { id: 'a', text: 'Keep her full caseload, since staying busy is the best way to work through grief', isCorrect: false, rationale: 'Continuing unchanged after a missed risk disclosure puts clients at risk of harm.' },
      { id: 'b', text: 'Quietly close her practice to new and current clients without notice to them', isCorrect: false, rationale: 'Abrupt closure without notice or transfer amounts to client abandonment.' },
      { id: 'c', text: 'Seek help and consultation, and limit or transfer cases until she can serve safely', isCorrect: true, rationale: 'C.2.g directs impaired counselors to seek assistance and limit, suspend or end services as needed.' },
      { id: 'd', text: 'Disclose her loss to grieving clients so that they can support her in sessions', isCorrect: false, rationale: 'Using clients for support reverses roles and serves the counselor\'s needs, not the clients\'.' },
    ],
    rationale: 'ACA C.2.g directs counselors to monitor themselves for signs of impairment, seek assistance for problems that reach the level of impairment, and limit, suspend or terminate professional responsibilities until it is safe to resume. Consultation, personal counseling and a temporary transfer of affected cases protect clients without abandoning them.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-058',
    reviewNote: 'Confirm the Gladding chapter locator for vicarious trauma vs burnout; the McCann & Pearlman attribution is standard.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'easy',
    stem: 'After three years of working mainly with survivors of violent crime, a counselor notices that she now sees the world as unsafe, distrusts strangers, and has intrusive images from clients\' stories. Which term BEST describes this?',
    options: [
      { id: 'a', text: 'Vicarious trauma', isCorrect: true, rationale: 'Vicarious trauma is a lasting change in the helper\'s beliefs about safety and trust from empathic exposure to trauma.' },
      { id: 'b', text: 'Countertransference', isCorrect: false, rationale: 'Countertransference is the counselor\'s reaction to a particular client, often tied to the counselor\'s own history.' },
      { id: 'c', text: 'Simple job burnout', isCorrect: false, rationale: 'Burnout is exhaustion and cynicism from workload and conditions, not a shift in trauma-related schemas.' },
      { id: 'd', text: 'Moral distress', isCorrect: false, rationale: 'Moral distress arises when one cannot act on what one believes is ethically right.' },
    ],
    rationale: 'Vicarious traumatization, described by McCann and Pearlman, is a cumulative change in the counselor\'s inner experience and core beliefs, such as safety, trust and control, that results from empathic engagement with clients\' trauma. It differs from burnout, which stems from work conditions, and calls for supervision, caseload balance and self-care as part of ethical practice (ACA C.2.g).',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Counselor burnout, vicarious trauma and self-care' }, { source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-059',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'easy',
    stem: 'A counselor wants to join the American Counseling Association division that focuses on multicultural counseling and that endorsed the Multicultural and Social Justice Counseling Competencies. Which division should she join?',
    options: [
      { id: 'a', text: 'ASGW', isCorrect: false, rationale: 'The Association for Specialists in Group Work focuses on group work and its best practices.' },
      { id: 'b', text: 'ACES', isCorrect: false, rationale: 'The Association for Counselor Education and Supervision focuses on training and supervision.' },
      { id: 'c', text: 'IAMFC', isCorrect: false, rationale: 'The International Association of Marriage and Family Counselors focuses on couple and family work.' },
      { id: 'd', text: 'AMCD', isCorrect: true, rationale: 'The Association for Multicultural Counseling and Development focuses on multicultural counseling.' },
    ],
    rationale: 'The Association for Multicultural Counseling and Development (AMCD) is the ACA division devoted to multicultural and diversity issues, and it developed the Multicultural and Social Justice Counseling Competencies with ACA endorsement. ACA divisions each serve a specialty area, such as group work (ASGW), counselor education (ACES) and family counseling (IAMFC).',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'AMCD development and ACA endorsement of the competencies' }, { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Professional organizations and ACA divisions' }],
  },
  {
    id: 'nce-s-eth-060',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'medium',
    stem: 'A counselor educator is preparing a slide that matches counseling bodies with their roles. Which pairing is accurate?',
    options: [
      { id: 'a', text: 'CACREP: issues licenses that let counselors practice in each state', isCorrect: false, rationale: 'CACREP accredits graduate programs; it does not license anyone.' },
      { id: 'b', text: 'Chi Sigma Iota: the international honor society of the counseling field', isCorrect: true, rationale: 'Chi Sigma Iota is the counseling academic and professional honor society.' },
      { id: 'c', text: 'NBCC: accredits master\'s and doctoral counseling graduate programs', isCorrect: false, rationale: 'NBCC certifies individual counselors and administers the NCE; CACREP accredits programs.' },
      { id: 'd', text: 'State licensing board: awards the National Certified Counselor title', isCorrect: false, rationale: 'The NCC is awarded by NBCC; state boards grant licenses to practice.' },
    ],
    rationale: 'Chi Sigma Iota is the international honor society for counseling students, professional counselors and counselor educators, promoting scholarship, leadership and excellence. CACREP accredits programs, NBCC grants national certification such as the NCC, and state boards license counselors and enforce state practice law.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Professional organizations: Chi Sigma Iota, NBCC, CACREP and state boards' }],
  },
  {
    id: 'nce-s-eth-061',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'hard',
    stem: 'The California Supreme Court decided Tarasoff v. Regents of the University of California twice, in 1974 and again on rehearing in 1976. How did the 1976 decision change the clinician\'s obligation?',
    options: [
      { id: 'a', text: 'It framed it as a duty to protect, met by warning or other reasonable steps', isCorrect: true, rationale: 'Tarasoff II held a duty to use reasonable care to protect the victim, which warning may or may not satisfy.' },
      { id: 'b', text: 'It removed any duty, ruling that therapy privilege outweighs third parties', isCorrect: false, rationale: 'The court reaffirmed liability, stating that the protective privilege ends where public peril begins.' },
      { id: 'c', text: 'It limited the duty to cases in which the client has already hurt someone', isCorrect: false, rationale: 'The duty concerns foreseeable future violence against an identifiable victim, not past harm.' },
      { id: 'd', text: 'It required clinicians to call the police after any client voices anger', isCorrect: false, rationale: 'The duty arises from a serious threat of violence, not ordinary expressions of anger.' },
    ],
    rationale: 'Tarasoff I (1974) held that a therapist had a duty to warn a foreseeable victim. On rehearing, Tarasoff II (1976) restated this as a broader duty to protect: when a therapist determines, or should determine, that a client poses a serious danger of violence to another, the therapist must use reasonable care to protect the intended victim, which may include warning, notifying police or other steps.',
    references: [{ source: 'State law', detail: 'Tarasoff v. Regents of the University of California (1974, 1976) and state duty-to-protect law' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-062',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'easy',
    stem: 'A counselor relocates her practice to a new state. A colleague tells her that "duty to warn works the same everywhere because of Tarasoff." What is the MOST accurate response?',
    options: [
      { id: 'a', text: 'Tarasoff is a federal ruling, so every state follows the same rule', isCorrect: false, rationale: 'Tarasoff was a California Supreme Court case, not a federal ruling binding all states.' },
      { id: 'b', text: 'Duty to warn applies only to psychiatrists, not licensed counselors', isCorrect: false, rationale: 'State duty-to-protect laws commonly cover licensed mental health professionals, including counselors.' },
      { id: 'c', text: 'States differ, so she must learn her new state\'s duty-to-protect law', isCorrect: true, rationale: 'Some states mandate action, some permit disclosure, and some have no statute, so she checks local law.' },
      { id: 'd', text: 'The ACA Code sets one duty-to-warn rule that replaces state statutes', isCorrect: false, rationale: 'The ACA Code defers to legal requirements and does not replace state statutes.' },
    ],
    rationale: 'Tarasoff was a California decision. States have since adopted different approaches: some impose a mandatory duty to warn or protect, some permit but do not require disclosure, and some have no statute or case law. Counselors must know the law in each state where they practice, including what triggers the duty and what actions discharge it.',
    references: [{ source: 'State law', detail: 'Duty-to-warn/protect statutes: mandatory, permissive or none' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-063',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'medium',
    stem: 'The Preamble of the 2014 ACA Code of Ethics lists core professional values of the counseling profession. Which of the following is one of those core values?',
    options: [
      { id: 'a', text: 'Protecting the field\'s public image', isCorrect: false, rationale: 'Reputation of the profession is not listed among the Preamble\'s core values.' },
      { id: 'b', text: 'Maximizing cost-effectiveness', isCorrect: false, rationale: 'Cost-effectiveness is not a core professional value in the Preamble.' },
      { id: 'c', text: 'Deferring to client families', isCorrect: false, rationale: 'The Code emphasizes client autonomy, not deference to family on treatment.' },
      { id: 'd', text: 'Promoting social justice', isCorrect: true, rationale: 'Promoting social justice is one of the core professional values listed in the Preamble.' },
    ],
    rationale: 'The Preamble names the profession\'s core values: enhancing human development throughout the life span; honoring diversity and embracing a multicultural approach; promoting social justice; safeguarding the integrity of the counselor-client relationship; and practicing in a competent and ethical manner. It also lists the ethical principles of autonomy, nonmaleficence, beneficence, justice, fidelity and veracity.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Preamble: core professional values and fundamental principles' }],
  },
  {
    id: 'nce-s-eth-064',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'termination and referral',
    difficulty: 'hard',
    stem: 'A client\'s partner has twice confronted the counselor in the parking lot after sessions and left threatening voicemails. The counselor no longer feels safe continuing the relationship. Under the ACA Code of Ethics, what may the counselor do?',
    options: [
      { id: 'a', text: 'End services by letter right away, giving no referrals, since the threat is not her fault', isCorrect: false, rationale: 'Even when termination is justified, the counselor offers pretermination counseling and referrals as appropriate.' },
      { id: 'b', text: 'Terminate, since threats from someone close to the client are an accepted reason', isCorrect: true, rationale: 'A.11.c permits termination when the counselor is in jeopardy of harm by someone in a relationship with the client.' },
      { id: 'c', text: 'Continue indefinitely, because ending services would punish the client for the partner', isCorrect: false, rationale: 'The Code does not require counselors to keep working while in jeopardy of harm.' },
      { id: 'd', text: 'Invite the partner into joint sessions to resolve the conflict before any decision', isCorrect: false, rationale: 'Bringing a threatening person into sessions raises risk and is not required before termination.' },
    ],
    rationale: 'A.11.c states that counselors may terminate when they are in jeopardy of harm by the client or by another person with whom the client has a relationship. Counselors still provide pretermination counseling and recommend other service providers when necessary, and they document the reasons and safety steps taken.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' }],
  },
  {
    id: 'nce-s-eth-065',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'termination and referral',
    difficulty: 'medium',
    stem: 'A counselor realizes that a client\'s severe eating disorder requires specialized care beyond her competence. She offers three referrals to qualified providers, but the client declines all of them and asks to keep seeing her. What does the ACA Code of Ethics direct?',
    options: [
      { id: 'a', text: 'Continue, since the client\'s wish to stay outweighs the competence concern', isCorrect: false, rationale: 'Client preference does not permit practice outside competence when serious risk is present.' },
      { id: 'b', text: 'Keep working with her but drop eating-related goals from the treatment plan', isCorrect: false, rationale: 'Ignoring the main clinical problem does not address the risk and is not what the Code directs.' },
      { id: 'c', text: 'Discontinue the counseling relationship once the referrals have been offered', isCorrect: true, rationale: 'A.11.b states that if clients decline the suggested referrals, counselors discontinue the relationship.' },
      { id: 'd', text: 'Ask a friend with eating-disorder training to coach her by phone each week', isCorrect: false, rationale: 'Informal coaching is not supervision or consultation and does not establish competence.' },
    ],
    rationale: 'A.11.b provides that when counselors lack the competence to help a client, they avoid entering or continuing the relationship, know culturally and clinically appropriate referral resources, and suggest them. If the client declines the suggested referrals, the counselor discontinues the relationship, handling the transition with care to avoid abandonment.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.b Competence Within Termination and Referral' }],
  },
  {
    id: 'nce-s-eth-066',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'At the final session, a client who immigrated from the Philippines brings her counselor a small box of homemade pastries to thank her, explaining that in her family such gifts express respect. How should the counselor approach this gift?',
    options: [
      { id: 'a', text: 'Weigh its value, the client\'s motive, the relationship and cultural meaning', isCorrect: true, rationale: 'A.10.f directs counselors to consider the relationship, monetary value, and the client\'s and counselor\'s motives.' },
      { id: 'b', text: 'Decline it politely, since the Code bars all gifts from current clients', isCorrect: false, rationale: 'The Code recognizes that small tokens of appreciation may be acceptable and does not bar all gifts.' },
      { id: 'c', text: 'Accept it, then offer a gift of equal value back so that the two are even', isCorrect: false, rationale: 'Reciprocal gift-giving is not required and can blur the professional relationship.' },
      { id: 'd', text: 'Accept it only if the client agrees to put the gift in writing beforehand', isCorrect: false, rationale: 'The Code sets factors to weigh, not a written agreement, for small gifts.' },
    ],
    rationale: 'A.10.f recognizes that in some cultures small gifts are a token of respect and gratitude. When deciding whether to accept, counselors consider the therapeutic relationship, the monetary value of the gift, the client\'s motivation for giving it, and the counselor\'s motivation for accepting or declining. Refusing a modest, culturally meaningful gift can itself harm the relationship.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.10.f Receiving Gifts' }],
  },
  {
    id: 'nce-s-eth-067',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'informed consent and its required elements',
    difficulty: 'easy',
    stem: 'A counselor has a guardian\'s consent to give a career interest inventory to a 17-year-old student. Under the ACA Code of Ethics, what must the counselor explain to the student before the assessment?',
    options: [
      { id: 'a', text: 'The raw scoring keys, so she can check the scoring on her own later on', isCorrect: false, rationale: 'Sharing scoring keys would compromise test security and is not part of informed consent.' },
      { id: 'b', text: 'Nothing until results are in, so that her answers stay honest and unbiased', isCorrect: false, rationale: 'E.3.a requires the explanation before the assessment, not after.' },
      { id: 'c', text: 'Only the time the inventory will take, since interest tests are low risk', isCorrect: false, rationale: 'Low risk does not remove the duty to explain the nature, purpose and use of results.' },
      { id: 'd', text: 'Its nature and purpose and who will use the results, in words she grasps', isCorrect: true, rationale: 'E.3.a requires explaining nature, purposes and specific use of results in understandable language.' },
    ],
    rationale: 'E.3.a requires counselors, before an assessment, to explain its nature and purposes and the specific use of results by potential recipients, in terms and language the client can understand. This applies to low-stakes instruments too, and with minors the counselor also involves parents or guardians as appropriate.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.3.a Explanation to Clients' }],
  },
  {
    id: 'nce-s-eth-068',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'scope of practice and competence',
    difficulty: 'medium',
    stem: 'A counselor running a workshop on test anxiety wants to photocopy several items from a published, copyrighted achievement test to use as practice handouts. What is the ethical issue?',
    options: [
      { id: 'a', text: 'None, as long as the counselor removes the publisher\'s name from each page', isCorrect: false, rationale: 'Removing attribution makes the problem worse; it does not grant permission.' },
      { id: 'b', text: 'Copying items without permission breaks test security and publisher rights', isCorrect: true, rationale: 'E.10 requires maintaining test security and not reproducing published tests without permission.' },
      { id: 'c', text: 'It is acceptable only if the handouts are collected and shredded at the end', isCorrect: false, rationale: 'Collecting handouts does not cure unauthorized reproduction or exposure of items.' },
      { id: 'd', text: 'It is allowed for any educational purpose under the fair use of all tests', isCorrect: false, rationale: 'Exposing secure items can invalidate the test for future takers; fair use does not cover this.' },
    ],
    rationale: 'E.10 directs counselors to maintain the integrity and security of tests and assessment techniques consistent with legal and contractual obligations, and not to appropriate, reproduce or modify published assessments without acknowledgment and permission from the publisher. Exposing items also threatens the validity of the test for future examinees.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.10 Assessment Security' }],
  },
  {
    id: 'nce-s-eth-069',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'medium',
    stem: 'A licensed counselor agrees to provide clinical supervision for a new graduate working toward licensure. Under the ACA Code of Ethics, what should the supervisor do at the start of the relationship?',
    options: [
      { id: 'a', text: 'Start case review at once and discuss evaluation only when problems arise', isCorrect: false, rationale: 'Delaying the discussion of evaluation denies the supervisee informed consent.' },
      { id: 'b', text: 'Ask the supervisee to waive any right to appeal a negative evaluation', isCorrect: false, rationale: 'Supervisees must be told of due process and appeal mechanisms, not asked to waive them.' },
      { id: 'c', text: 'Review policies, evaluation methods and due process for appeals with her', isCorrect: true, rationale: 'F.4.a builds informed consent into supervision, including policies and due process appeal.' },
      { id: 'd', text: 'Rely on the graduate program\'s handbook, since it covers all expectations', isCorrect: false, rationale: 'Post-degree supervision needs its own informed consent; a school handbook does not cover it.' },
    ],
    rationale: 'F.4.a requires supervisors to incorporate the principles of informed consent and participation into supervision, informing supervisees of the policies and procedures to which supervisors are to adhere and the mechanisms for due process appeal of individual supervisor actions. Many supervisors put this in a written supervision agreement that also covers evaluation, emergencies and fees.',
    references: [{ source: 'ACA Code of Ethics', detail: 'F.4.a Informed Consent for Supervision' }],
  },
  {
    id: 'nce-s-eth-070',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'supervision and consultation responsibilities',
    difficulty: 'medium',
    stem: 'A counselor\'s close friend asks her to serve as the licensure supervisor for the friend\'s adult son, who just finished a counseling degree. The counselor is confident she could be fair. What does the ACA Code of Ethics direct?',
    options: [
      { id: 'a', text: 'Accept, provided she documents the friendship in the supervision file', isCorrect: false, rationale: 'Documentation does not cure the loss of objectivity the Code warns about.' },
      { id: 'b', text: 'Accept, but have a second supervisor sign his final evaluation as well', isCorrect: false, rationale: 'A co-signer does not remove the conflict in the ongoing supervisory relationship.' },
      { id: 'c', text: 'Accept if the son agrees in writing that their personal ties will not matter', isCorrect: false, rationale: 'Supervisee consent does not resolve the supervisor\'s inability to stay objective.' },
      { id: 'd', text: 'Decline, since she may be unable to judge him with full objectivity', isCorrect: true, rationale: 'F.3.d bars supervisory relationships with friends or family members where objectivity is at risk.' },
    ],
    rationale: 'F.3.d states that supervisors are prohibited from engaging in supervisory relationships with individuals with whom they have an inability to remain objective, such as friends or family members. The counselor\'s own confidence does not settle the matter; the safer course is to decline and help the son find another qualified supervisor.',
    references: [{ source: 'ACA Code of Ethics', detail: 'F.3.d Friends or Family Members' }],
  },
  {
    id: 'nce-s-eth-071',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'easy',
    stem: 'A group practice is moving from paper charts to a cloud-based electronic health record. Under the ACA Code of Ethics, what should counselors tell clients about this change?',
    options: [
      { id: 'a', text: 'Nothing, because record storage is an internal business decision only', isCorrect: false, rationale: 'H.5.a requires informing clients how records are kept electronically.' },
      { id: 'b', text: 'How records are stored, including encryption and archive retention', isCorrect: true, rationale: 'H.5.a lists the type of encryption and security and archival storage as things clients are told.' },
      { id: 'c', text: 'That electronic records are fully secure and cannot ever be breached', isCorrect: false, rationale: 'Counselors acknowledge the limits of technology security rather than promising it is perfect.' },
      { id: 'd', text: 'That clients must sign a waiver of all liability for any data breach', isCorrect: false, rationale: 'Liability waivers are not part of the Code and do not replace security duties.' },
    ],
    rationale: 'H.5.a directs counselors to maintain electronic records in accordance with relevant laws and to inform clients how records are maintained electronically, including the type of encryption and security assigned to the records and whether, and for how long, archival storage is kept. HIPAA\'s Security Rule adds administrative, physical and technical safeguards for electronic records.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.5.a Records' }, { source: 'HIPAA', detail: 'Security Rule safeguards for electronic PHI (45 CFR Part 164, Subpart C)' }],
  },
  {
    id: 'nce-s-eth-072',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'medium',
    stem: 'The mother of a 14-year-old client calls after the third session and asks the counselor to tell her "everything he says," noting that she has legal custody and pays for services. The teen has asked that his talks stay private. What is the counselor\'s BEST approach?',
    options: [
      { id: 'a', text: 'Respect her rights, clarify what will be shared, and keep safety limits clear', isCorrect: true, rationale: 'B.5.b asks counselors to respect parental rights while explaining the confidential nature of counseling.' },
      { id: 'b', text: 'Give her full session details, since a parent who pays controls the record', isCorrect: false, rationale: 'Payment does not entitle a parent to all session content, and full disclosure can damage trust.' },
      { id: 'c', text: 'Refuse to speak with her at all, since the teen asked for complete privacy', isCorrect: false, rationale: 'Ignoring a custodial parent disregards the parent\'s legal rights and responsibilities.' },
      { id: 'd', text: 'End counseling, since the parent and teen want different things from it', isCorrect: false, rationale: 'Differing wishes are common and are worked through, not a reason to terminate.' },
    ],
    rationale: 'B.5.b directs counselors to inform parents and guardians about the role of counselors and the confidential nature of the counseling relationship, consistent with legal and custodial arrangements, and to respect the inherent rights and responsibilities of parents. Ideally the counselor sets these terms with parent and minor at the outset: general progress may be shared, specific content stays private, and safety concerns are disclosed.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.5.b Responsibility to Parents and Legal Guardians' }],
  },
];
