// tools/nce/seed/ethics-4.js — Professional Practice and Ethics, batch 4
// Hand-authored original items (nce-s-eth-073 … nce-s-eth-096).
module.exports = [
  {
    id: 'nce-s-eth-073',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'easy',
    stem: 'A counselor at a community clinic is reviewing her progress notes before an internal audit. Which entry BEST reflects what belongs in a progress note?',
    options: [
      { id: 'a', text: 'A near-verbatim transcript of everything the client said during the hour', isCorrect: false, rationale: 'Transcripts are excessive and expose more private material than the record needs.' },
      { id: 'b', text: 'Client presentation, interventions used, response, risk status and plan', isCorrect: true, rationale: 'A progress note documents observable presentation, the service provided, the client\'s response, risk and the next steps.' },
      { id: 'c', text: 'The counselor\'s guesses about the private lives of the client\'s coworkers', isCorrect: false, rationale: 'Speculation about third parties is not clinically necessary and should not be recorded.' },
      { id: 'd', text: 'A list of the counselor\'s own feelings and frustrations about the client', isCorrect: false, rationale: 'Personal reactions belong in supervision or consultation, not in the clinical record.' },
    ],
    rationale: 'Progress notes should be timely, accurate and objective, recording what services were provided and why, how the client responded, any risk findings, and the plan. ACA B.6.a asks counselors to create and maintain records needed to provide professional services. Excess detail, speculation about others and counselor feelings add risk without clinical value.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Progress note content: presentation, interventions, response, risk and plan' }, { source: 'ACA Code of Ethics', detail: 'B.6.a Creating and Maintaining Records and Documentation' }],
  },
  {
    id: 'nce-s-eth-074',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'medium',
    stem: 'A week after writing a progress note in the clinic\'s electronic record, a counselor realizes she entered the wrong medication dose that the client reported. How should she correct the error?',
    options: [
      { id: 'a', text: 'Delete the original note and write a new one dated to the session day', isCorrect: false, rationale: 'Deleting and back-dating destroys the original entry and can look like falsification.' },
      { id: 'b', text: 'Edit the dose in the original note quietly so the record reads correctly', isCorrect: false, rationale: 'An unmarked change hides that the record was altered and when.' },
      { id: 'c', text: 'Leave the note as written, since signed entries may not be changed later', isCorrect: false, rationale: 'Known errors should be corrected; leaving false information harms care.' },
      { id: 'd', text: 'Add a dated, signed addendum noting the error and the correct dose', isCorrect: true, rationale: 'An addendum corrects the record while keeping the original visible and showing who changed it and when.' },
    ],
    rationale: 'Records are corrected in a way that keeps the original entry visible and marks the correction with the date and the counselor\'s signature: a single line through the error on paper, or a dated addendum or amendment in an electronic record. Erasing, overwriting or back-dating can be viewed as falsifying records. Accurate correction protects both care and the record\'s integrity.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Correcting errors: late entries and addenda that preserve the original entry' }, { source: 'ACA Code of Ethics', detail: 'B.6.a Creating and Maintaining Records and Documentation' }],
  },
  {
    id: 'nce-s-eth-075',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'hard',
    stem: 'A counselor saw a couple in joint sessions and also met once with each partner alone. After the couple separates, one partner, a 42-year-old man, asks for a copy of "the whole file." The other partner has not given consent. What does the ACA Code of Ethics direct?',
    options: [
      { id: 'a', text: 'Release only the parts of the record that relate directly to him', isCorrect: true, rationale: 'B.6.e limits access in multiple-client records to the parts that relate to the requesting client, without other clients\' confidential material.' },
      { id: 'b', text: 'Release the entire file, since he took part in most of the sessions', isCorrect: false, rationale: 'The file includes his partner\'s confidential material, including her individual session.' },
      { id: 'c', text: 'Refuse all access, since couple records belong to the counselor alone', isCorrect: false, rationale: 'Clients have a right to reasonable access to their records; a blanket refusal is not supported.' },
      { id: 'd', text: 'Release the file only after his former partner reviews and edits it', isCorrect: false, rationale: 'Letting one client edit the record is improper and does not protect either client.' },
    ],
    rationale: 'ACA B.6.e states that in situations involving multiple clients, counselors provide individual clients with only those parts of records that relate directly to them and do not include confidential information related to any other client. Setting rules for couple records at the start, including how individual sessions are documented, prevents disputes later.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.6.e Client Access' }],
  },
  {
    id: 'nce-s-eth-076',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'easy',
    stem: 'A counselor promised a client she would call him back with a referral by Friday. On Friday, her schedule is overloaded, but she makes the call before leaving work. Which of Kitchener\'s moral principles does this action MOST directly reflect?',
    options: [
      { id: 'a', text: 'Justice', isCorrect: false, rationale: 'Justice concerns fairness and equal treatment, not keeping a specific promise.' },
      { id: 'b', text: 'Veracity', isCorrect: false, rationale: 'Veracity is truthfulness; the act here is honoring a commitment.' },
      { id: 'c', text: 'Fidelity', isCorrect: true, rationale: 'Fidelity means being faithful to commitments and promises made to clients.' },
      { id: 'd', text: 'Autonomy', isCorrect: false, rationale: 'Autonomy is respect for the client\'s right to make his own choices.' },
    ],
    rationale: 'Kitchener\'s principles include autonomy, beneficence, nonmaleficence, justice and fidelity, with veracity often added in later work. Fidelity refers to honoring commitments and being trustworthy, which builds the trust the counseling relationship depends on.',
    references: [{ source: 'Forester-Miller & Davis (Practitioner\'s Guide to Ethical Decision Making)', detail: 'Moral principles: autonomy, justice, beneficence, nonmaleficence, fidelity (and veracity)' }],
  },
  {
    id: 'nce-s-eth-077',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'medium',
    stem: 'A nonprofit agency fills open counseling slots by giving priority to clients with private insurance. A counselor argues that slots should go first to clients with the most severe needs, regardless of payer. Which moral principle is the counselor MOST directly invoking?',
    options: [
      { id: 'a', text: 'Justice, the fair allocation of services and resources', isCorrect: true, rationale: 'Justice concerns fairness and equitable distribution of services, which is the issue raised.' },
      { id: 'b', text: 'Fidelity, keeping promises made to current clients', isCorrect: false, rationale: 'No promise to a particular client is at stake in the policy dispute.' },
      { id: 'c', text: 'Veracity, being truthful with clients about services', isCorrect: false, rationale: 'The concern is how services are allocated, not honesty in disclosure.' },
      { id: 'd', text: 'Autonomy, respecting each client\'s freedom of choice', isCorrect: false, rationale: 'Clients\' self-determination is not the issue in how slots are assigned.' },
    ],
    rationale: 'Justice means treating people fairly and distributing services equitably; treating clients differently requires a rationale that is relevant to the difference. Prioritizing by ability to pay rather than clinical need raises a justice concern, and counselors may advocate within the agency for fairer policies.',
    references: [{ source: 'Forester-Miller & Davis (Practitioner\'s Guide to Ethical Decision Making)', detail: 'Moral principles: justice as fairness and equitable treatment' }],
  },
  {
    id: 'nce-s-eth-078',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'hard',
    stem: 'A competent 55-year-old client decides to leave a stable job to open a risky small business. She is not in danger, but her counselor believes the move will cause her great stress and financial harm and is tempted to keep steering sessions toward talking her out of it. Which two principles are MOST in tension?',
    options: [
      { id: 'a', text: 'Justice and fidelity, since the client may lose her income', isCorrect: false, rationale: 'Neither fair distribution nor a broken promise is at issue.' },
      { id: 'b', text: 'Veracity and justice, since the plan affects her family too', isCorrect: false, rationale: 'Truthfulness and fairness are not the competing values in this choice.' },
      { id: 'c', text: 'Fidelity and veracity, since she has set her goals for therapy', isCorrect: false, rationale: 'No commitment or truthfulness conflict drives the counselor\'s dilemma.' },
      { id: 'd', text: 'Autonomy and beneficence, since her choice and welfare differ', isCorrect: true, rationale: 'Her right to self-determination conflicts with the counselor\'s wish to do good for her.' },
    ],
    rationale: 'Autonomy is respect for a competent client\'s right to make her own decisions; beneficence is the duty to promote her welfare. When a client\'s free choice differs from what the counselor believes is good for her, and no serious harm is foreseeable, autonomy generally prevails. The counselor can explore consequences openly without imposing her own values (ACA A.4.b).',
    references: [{ source: 'Forester-Miller & Davis (Practitioner\'s Guide to Ethical Decision Making)', detail: 'Moral principles: autonomy versus beneficence' }, { source: 'ACA Code of Ethics', detail: 'A.4.b Personal Values' }],
  },
  {
    id: 'nce-s-eth-079',
    reviewNote: 'Compact privileges were not yet being issued in every member state when written; confirm current operational status and the "law of the client\'s state" framing against the Compact text.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'medium',
    stem: 'A counselor holds a full, unencumbered license in her home state, which belongs to the Counseling Compact. She obtains a privilege to practice in another member state to see a client there by video. Whose practice laws govern her work with that client?',
    options: [
      { id: 'a', text: 'Only her home state\'s laws, since the privilege rests on that license', isCorrect: false, rationale: 'The privilege is based on the home license, but practice follows the remote state\'s laws.' },
      { id: 'b', text: 'The laws of the member state where the client is located during care', isCorrect: true, rationale: 'Under the Compact, a privilege holder must follow the laws and rules of the remote state where the client is located.' },
      { id: 'c', text: 'Only federal rules, since telehealth across states is federally run', isCorrect: false, rationale: 'Counseling practice is regulated by states; no federal license governs it.' },
      { id: 'd', text: 'The Compact Commission\'s own national practice act for counselors', isCorrect: false, rationale: 'The Commission administers the Compact; it does not replace state practice acts.' },
    ],
    rationale: 'The Counseling Compact lets a counselor with an unencumbered license in a home member state practice in other member states through a privilege to practice. While using that privilege, the counselor is subject to the laws and regulations of the remote state where the client is located, and that state may act against the privilege. ACA H.1.b likewise notes that distance counselors may be subject to the laws of the client\'s location.',
    references: [{ source: 'Counseling Compact', detail: 'Privilege to practice: adherence to the laws and rules of the remote state' }, { source: 'ACA Code of Ethics', detail: 'H.1.b Laws and Statutes' }],
  },
  {
    id: 'nce-s-eth-080',
    reviewNote: 'Associate-level license titles and supervision rules vary by state; confirm the general framing.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'hard',
    stem: 'A counselor holds an associate-level counseling license that, under her state\'s law, requires practice under an approved supervisor. She also holds the NCC credential. A friend urges her to open a solo private practice, saying "the NCC shows you\'re qualified." What determines whether she may practice independently?',
    options: [
      { id: 'a', text: 'Her NCC, since national certification overrides tiered state licenses', isCorrect: false, rationale: 'National certification is voluntary and does not authorize practice or override state law.' },
      { id: 'b', text: 'Her degree, since a CACREP master\'s permits independent counseling', isCorrect: false, rationale: 'A degree is a requirement for licensure, not a legal authorization to practice.' },
      { id: 'c', text: 'Her state\'s law for her license tier, which limits independent work', isCorrect: true, rationale: 'The scope and conditions of each license tier are set by state law; an associate license requires supervision.' },
      { id: 'd', text: 'Her own judgment of her skills, since competence is self-assessed', isCorrect: false, rationale: 'Competence matters ethically, but self-assessment cannot expand a legal scope of practice.' },
    ],
    rationale: 'State licensure law defines who may practice counseling and under what conditions, including tiered licenses for counselors still completing supervised experience. National certification such as the NCC is a voluntary professional credential and does not grant the legal right to practice. ACA C.2.a also directs counselors to practice only within the boundaries of their credentials.',
    references: [{ source: 'State law', detail: 'Counselor licensure tiers: associate licenses and supervision requirements' }, { source: 'ACA Code of Ethics', detail: 'C.2.a Boundaries of Competence' }],
  },
  {
    id: 'nce-s-eth-081',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'licensure, credentialing and professional identity',
    difficulty: 'easy',
    stem: 'A state\'s counselor law is described as a "title act" rather than a "practice act." What does a title act do?',
    options: [
      { id: 'a', text: 'It limits who may use a protected title such as "licensed counselor"', isCorrect: true, rationale: 'A title act restricts use of the protected professional title to people who hold the credential.' },
      { id: 'b', text: 'It limits who may perform counseling services for a fee in the state', isCorrect: false, rationale: 'Restricting the activity itself is what a practice act does.' },
      { id: 'c', text: 'It sets the standards that graduate programs must meet to accredit', isCorrect: false, rationale: 'Program standards are set by accreditors such as CACREP, not by state title laws.' },
      { id: 'd', text: 'It requires every counselor in the state to hold national certification', isCorrect: false, rationale: 'National certification is voluntary and is not created by a state title act.' },
    ],
    rationale: 'A title act protects the use of a professional title, so only credentialed people may call themselves, for example, a licensed professional counselor. A practice act goes further and defines the scope of practice, restricting who may perform the regulated activities. Most states now regulate both the title and the practice of counseling.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Credentialing: licensure, certification, title and practice acts' }],
  },
  {
    id: 'nce-s-eth-082',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A counselor who works with many clients facing eviction testifies before a state legislative committee in support of a bill to expand tenant protections. In the ACA Advocacy Competencies, which domain does this work fall under?',
    options: [
      { id: 'a', text: 'Client/student domain, through direct client empowerment', isCorrect: false, rationale: 'Client-level work helps an individual build self-advocacy skills or acts for one client.' },
      { id: 'b', text: 'School/community domain, through community collaboration', isCorrect: false, rationale: 'Community collaboration joins local groups; legislative testimony targets public policy.' },
      { id: 'c', text: 'Clinical domain, through individual treatment planning', isCorrect: false, rationale: 'There is no clinical domain in the competencies; treatment planning is not advocacy.' },
      { id: 'd', text: 'Public arena domain, through social/political advocacy', isCorrect: true, rationale: 'Influencing legislation and public policy is social/political advocacy in the public arena.' },
    ],
    rationale: 'The ACA Advocacy Competencies describe three domains: client/student, school/community and public arena, each with an "acting with" and an "acting on behalf" level. Testifying to lawmakers to change policy that affects many clients is social/political advocacy in the public arena. ACA A.7.a supports advocacy at individual, group, institutional and societal levels.',
    references: [{ source: 'ACA Advocacy Competencies', detail: 'ACA Advocacy Competencies: client/student, school/community and public arena domains' }, { source: 'ACA Code of Ethics', detail: 'A.7.a Advocacy' }],
  },
  {
    id: 'nce-s-eth-083',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A counselor notices that several clients from the same apartment complex report asthma flare-ups from mold, and the landlord ignores repair requests. Which action BEST represents systemic rather than client-level advocacy?',
    options: [
      { id: 'a', text: 'Help one client draft a letter to the landlord about her own unit', isCorrect: false, rationale: 'Supporting one client\'s self-advocacy is valuable but stays at the client level.' },
      { id: 'b', text: 'Teach each affected client coping skills for the stress of the mold', isCorrect: false, rationale: 'Coping skills address individual distress, not the conditions causing it.' },
      { id: 'c', text: 'Work with a tenants\' group and housing officials on building repairs', isCorrect: true, rationale: 'Collaborating with community groups to change the conditions affecting many tenants is systems advocacy.' },
      { id: 'd', text: 'Refer each client separately to a legal aid office for their claims', isCorrect: false, rationale: 'Individual referrals address each case one at a time rather than the system.' },
    ],
    rationale: 'Client-level advocacy helps a particular client access resources or self-advocate. Systemic advocacy targets the policies, institutions or conditions that create barriers for many people, often by collaborating with community groups. When counselors see a pattern across clients, the MSJCC and ACA A.7.a support intervening at the institutional and community levels, with client consent for any case-specific action.',
    references: [{ source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling and advocacy interventions: institutional and community levels' }, { source: 'ACA Code of Ethics', detail: 'A.7.a Advocacy' }],
  },
  {
    id: 'nce-s-eth-084',
    domain: 'ethics',
    cacrep: 'social_cultural',
    topic: 'counselor advocacy and social justice',
    difficulty: 'medium',
    stem: 'A 29-year-old client who is Deaf tells her counselor that her employer keeps refusing to provide an interpreter for staff meetings. She is articulate, knows her rights, and wants to handle it herself, but feels discouraged. Which advocacy approach BEST fits this situation?',
    options: [
      { id: 'a', text: 'Call the employer\'s human resources office on the client\'s behalf', isCorrect: false, rationale: 'Acting for a client who wants to self-advocate undercuts her autonomy and needs consent.' },
      { id: 'b', text: 'Help her identify strengths and plan her own self-advocacy steps', isCorrect: true, rationale: 'Empowerment, acting with the client, fits a capable client who wants to advocate for herself.' },
      { id: 'c', text: 'Focus sessions on accepting the workplace as it currently operates', isCorrect: false, rationale: 'Encouraging adjustment to discrimination ignores the systemic barrier she faces.' },
      { id: 'd', text: 'File a formal discrimination complaint to a federal agency for her', isCorrect: false, rationale: 'Filing for her overrides her stated wish to act on her own behalf.' },
    ],
    rationale: 'At the client level, the ACA Advocacy Competencies distinguish empowerment (acting with clients to build self-advocacy) from advocacy on their behalf. When a client is able and wants to act for herself, the counselor helps her recognize strengths, identify resources and plan steps. ACA A.7.b requires client consent before counselors advocate on a client\'s behalf.',
    references: [{ source: 'ACA Advocacy Competencies', detail: 'Client/student empowerment: acting with clients before acting on their behalf' }, { source: 'ACA Code of Ethics', detail: 'A.7.b Confidentiality and Advocacy' }, { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'ACA Advocacy Competencies: client/student empowerment' }],
  },
  {
    id: 'nce-s-eth-085',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'easy',
    stem: 'A counseling intern says self-care is "a personal lifestyle choice that has nothing to do with ethics." How does the 2014 ACA Code of Ethics treat counselor self-care?',
    options: [
      { id: 'a', text: 'As a private matter outside the scope of professional standards', isCorrect: false, rationale: 'The Code directly links self-care to meeting professional responsibilities.' },
      { id: 'b', text: 'As required only for counselors who are already showing impairment', isCorrect: false, rationale: 'Self-care is framed as ongoing and preventive, not only a response to impairment.' },
      { id: 'c', text: 'As a duty that applies only to supervisors overseeing trainees', isCorrect: false, rationale: 'The expectation applies to all counselors, not only supervisors.' },
      { id: 'd', text: 'As part of the professional responsibility to serve clients well', isCorrect: true, rationale: 'The Code expects counselors to engage in self-care to best meet their professional responsibilities.' },
    ],
    rationale: 'The introduction to Section C of the ACA Code states that counselors engage in self-care activities to maintain and promote their emotional, physical, mental and spiritual well-being to best meet their professional responsibilities. Standard C.2.g adds that counselors monitor themselves for impairment and refrain from offering services when impaired.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section C Introduction (self-care); C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-086',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'counselor impairment and self-care',
    difficulty: 'medium',
    stem: 'A counselor in solo practice is diagnosed with a progressive neurological illness. She is fully able to work now but knows sudden decline is possible. Under the ACA Code of Ethics, what should she do to protect her clients?',
    options: [
      { id: 'a', text: 'Prepare a plan naming a colleague to handle clients and records', isCorrect: true, rationale: 'C.2.h calls for a plan for transfer of clients and files if the counselor becomes incapacitated.' },
      { id: 'b', text: 'Close her practice right away, since any illness is an impairment', isCorrect: false, rationale: 'A diagnosis alone is not impairment; she may practice while able, with planning and monitoring.' },
      { id: 'c', text: 'Tell each client her full diagnosis so they can decide whether to stay', isCorrect: false, rationale: 'Full medical disclosure is not required and may shift focus from clients\' needs.' },
      { id: 'd', text: 'Rely on her family to contact clients if she becomes unable to work', isCorrect: false, rationale: 'Family members are not qualified to manage confidential records or clinical transitions.' },
    ],
    rationale: 'ACA C.2.h directs counselors to prepare a plan for the transfer of clients and the distribution of records to an identified colleague or records custodian in case of incapacitation, death or termination of practice, often called a professional will. Under C.2.g, she continues to monitor for signs of impairment and limits practice if it appears.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.h Counselor Incapacitation, Death, Retirement, or Termination of Practice' }, { source: 'ACA Code of Ethics', detail: 'C.2.g Impairment' }],
  },
  {
    id: 'nce-s-eth-087',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'easy',
    stem: 'A new clinical supervisor wants the section of the 2014 ACA Code of Ethics that covers supervisor gatekeeping, evaluation of supervisees and counselor educator duties. Which section should she read?',
    options: [
      { id: 'a', text: 'Section D', isCorrect: false, rationale: 'Section D, Relationships With Other Professionals, covers colleagues, employers and consultation, not supervision duties.' },
      { id: 'b', text: 'Section E', isCorrect: false, rationale: 'Section E, Evaluation, Assessment, and Interpretation, covers testing and assessment of clients.' },
      { id: 'c', text: 'Section F', isCorrect: true, rationale: 'Section F, Supervision, Training, and Teaching, addresses supervision, evaluation and gatekeeping, and counselor educator duties.' },
      { id: 'd', text: 'Section I', isCorrect: false, rationale: 'Section I, Resolving Ethical Issues, covers ethics complaints, conflicts with law and cooperation with committees.' },
    ],
    rationale: 'The 2014 ACA Code has nine sections: A The Counseling Relationship; B Confidentiality and Privacy; C Professional Responsibility; D Relationships With Other Professionals; E Evaluation, Assessment, and Interpretation; F Supervision, Training, and Teaching; G Research and Publication; H Distance Counseling, Technology, and Social Media; and I Resolving Ethical Issues. Gatekeeping and supervisee evaluation appear in Section F.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section F Supervision, Training, and Teaching (F.6.b Gatekeeping and Remediation)' }],
  },
  {
    id: 'nce-s-eth-088',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ACA Code of Ethics structure',
    difficulty: 'medium',
    stem: 'A counselor asks whether the 2014 ACA Code of Ethics tells counselors exactly which decision-making model to use when facing a dilemma. Which statement is accurate?',
    options: [
      { id: 'a', text: 'It requires the Forester-Miller and Davis model for all ethics cases', isCorrect: false, rationale: 'The Code names no single required model.' },
      { id: 'b', text: 'It expects a credible model able to bear public scrutiny, not a set one', isCorrect: true, rationale: 'The Code asks counselors to use a credible model whose application can withstand scrutiny.' },
      { id: 'c', text: 'It ranks its standards so higher sections settle conflicts automatically', isCorrect: false, rationale: 'The Code does not rank its standards to resolve dilemmas mechanically.' },
      { id: 'd', text: 'It leaves decision making entirely to each employer\'s written policy', isCorrect: false, rationale: 'Employer policy does not replace the counselor\'s ethical decision-making duty.' },
    ],
    rationale: 'The Purpose section and standard I.1.b note that no single decision-making model is best for every situation, so counselors are expected to use a credible model that can bear public scrutiny of its application. Counselors also consult, document their reasoning, and draw on ethical principles and the Code\'s standards.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Purpose; I.1.b Ethical Decision Making' }],
  },
  {
    id: 'nce-s-eth-089',
    reviewNote: 'Confirm that the current NBCC Code of Ethics addresses misrepresenting a lapsed credential; the exact directive number is not cited.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A counselor\'s National Certified Counselor (NCC) credential lapsed eight months ago after she did not recertify. Her website, business cards and email signature still list "NCC." What is the ethical concern?',
    options: [
      { id: 'a', text: 'She is misrepresenting a credential she no longer holds', isCorrect: true, rationale: 'Listing a lapsed credential misleads the public about her qualifications.' },
      { id: 'b', text: 'There is none, since she met the standard when she earned it', isCorrect: false, rationale: 'A credential may be claimed only while it is current and in good standing.' },
      { id: 'c', text: 'It is a concern only if a client is harmed by her services', isCorrect: false, rationale: 'Misrepresentation is a violation whether or not harm results.' },
      { id: 'd', text: 'It is a concern only for her state license, not certification', isCorrect: false, rationale: 'The issue is her claim of national certification, which NBCC governs.' },
    ],
    rationale: 'Both the NBCC Code of Ethics and ACA C.4.a require counselors to represent their credentials accurately. Continuing to list a lapsed certification misleads clients and the public. She should remove the designation at once or complete the steps to reinstate it.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Accurate representation of credentials and qualifications' }, { source: 'ACA Code of Ethics', detail: 'C.4.a Accurate Representation' }],
  },
  {
    id: 'nce-s-eth-090',
    reviewNote: 'Confirm that the NBCC Code of Ethics (rather than only the candidate agreement) addresses examination security.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'NBCC Code of Ethics',
    difficulty: 'medium',
    stem: 'A counselor who just passed the NCE posts a list of questions she remembers from the exam in an online study group to help friends who test next month. How is this viewed under NBCC standards?',
    options: [
      { id: 'a', text: 'As acceptable, since the items came from her own memory', isCorrect: false, rationale: 'Recalled items are still secure exam content; the source does not change that.' },
      { id: 'b', text: 'As acceptable, as long as she posts the items anonymously', isCorrect: false, rationale: 'Anonymity does not make sharing secure content ethical.' },
      { id: 'c', text: 'As a concern only if her friends end up passing the exam', isCorrect: false, rationale: 'The breach occurs when content is shared, whatever the result.' },
      { id: 'd', text: 'As a breach of exam security that can put her NCC at risk', isCorrect: true, rationale: 'Sharing secure exam content violates NBCC standards and may lead to sanctions.' },
    ],
    rationale: 'NBCC requires applicants and certificants to protect the security of its examinations, and disclosing recalled exam content is a violation that can lead to sanctions such as denial or revocation of certification. Exam security protects the validity of the credential for every counselor who holds it.',
    references: [{ source: 'NBCC Code of Ethics', detail: 'Examination security and integrity of the certification process' }],
  },
  {
    id: 'nce-s-eth-091',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'easy',
    stem: 'A newly hired high school counselor wants to join the national professional association for school counselors that publishes a national model for school counseling programs. Which organization is it?',
    options: [
      { id: 'a', text: 'AMHCA', isCorrect: false, rationale: 'The American Mental Health Counselors Association serves clinical mental health counselors.' },
      { id: 'b', text: 'ASCA', isCorrect: true, rationale: 'The American School Counselor Association publishes the ASCA National Model.' },
      { id: 'c', text: 'NBCC', isCorrect: false, rationale: 'NBCC is a certification board, not a membership association for school counselors.' },
      { id: 'd', text: 'CACREP', isCorrect: false, rationale: 'CACREP accredits graduate programs; it is not a membership association.' },
    ],
    rationale: 'The American School Counselor Association (ASCA) is the national association for school counselors and publishes the ASCA National Model, a framework for comprehensive school counseling programs, along with its own ethical standards for school counselors.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Professional organizations: ASCA and the ASCA National Model' }],
  },
  {
    id: 'nce-s-eth-092',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'professional organizations and their roles',
    difficulty: 'medium',
    stem: 'A state counseling board wants to join a national organization made up of state counselor licensing boards that works on issues such as license portability and consistent regulatory standards. Which organization fits this description?',
    options: [
      { id: 'a', text: 'CSI', isCorrect: false, rationale: 'Chi Sigma Iota (CSI) is the counseling honor society for students and professionals.' },
      { id: 'b', text: 'ACA', isCorrect: false, rationale: 'The American Counseling Association (ACA) is a membership association of individual counselors, not of boards.' },
      { id: 'c', text: 'AASCB', isCorrect: true, rationale: 'The American Association of State Counseling Boards (AASCB) brings together state counselor licensing boards on regulatory issues such as portability.' },
      { id: 'd', text: 'NBCC', isCorrect: false, rationale: 'The National Board for Certified Counselors (NBCC) certifies individuals and develops exams; its members are not state boards.' },
    ],
    rationale: 'The American Association of State Counseling Boards (AASCB) is the organization of state counselor licensing boards. It works on regulatory consistency, licensure portability and public protection. ACA serves individual members, NBCC grants national certification and develops exams, and CSI is the profession\'s honor society.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Credentialing bodies: AASCB, NBCC and state licensure boards' }],
  },
  {
    id: 'nce-s-eth-093',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'hard',
    stem: 'A 15-year-old client reveals that she has been cutting her thighs and has had thoughts of "not waking up." Her father emailed the counselor that morning demanding to know what his daughter talks about. She begs the counselor not to tell her parents anything. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Complete a risk assessment, then plan with her what parents must learn', isCorrect: true, rationale: 'Risk must be assessed first; safety information is then shared with parents with the teen involved.' },
      { id: 'b', text: 'Reply to the father\'s email with a full summary of what she disclosed', isCorrect: false, rationale: 'Disclosure before assessing risk and without the teen\'s involvement shares more than needed.' },
      { id: 'c', text: 'Keep the disclosure private, since she asked that nothing be shared', isCorrect: false, rationale: 'A minor\'s request cannot override the duty to protect when safety is at stake.' },
      { id: 'd', text: 'Tell her sessions will stop unless she tells her parents herself today', isCorrect: false, rationale: 'Threatening to end services is coercive and risks abandonment of an at-risk teen.' },
    ],
    rationale: 'Self-injury and passive suicidal ideation call first for a structured risk assessment. If the assessment shows risk, ACA B.2.a permits disclosure to protect the client, and with a minor the counselor involves the teen in deciding how parents are told, sharing only what is needed for safety (B.2.e). The father\'s general demand for content is handled separately, balancing parental rights with the teen\'s privacy (B.5.b).',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm; B.2.e Minimal Disclosure' }, { source: 'ACA Code of Ethics', detail: 'B.5.b Responsibility to Parents and Legal Guardians' }],
  },
  {
    id: 'nce-s-eth-094',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'hard',
    stem: 'A father in individual counseling for depression asks his counselor to testify as an expert in his upcoming custody trial and to recommend that he receive primary custody. He says, "You know me better than anyone." What should the counselor do?',
    options: [
      { id: 'a', text: 'Agree, since a long alliance gives her the best basis for an opinion', isCorrect: false, rationale: 'Familiarity from treatment is not a basis for a forensic opinion and creates a dual role.' },
      { id: 'b', text: 'Agree if the other parent and both attorneys consent to her testimony', isCorrect: false, rationale: 'Consent of others does not cure the conflict between therapeutic and forensic roles.' },
      { id: 'c', text: 'Write a letter supporting custody instead of appearing at the hearing', isCorrect: false, rationale: 'A custody recommendation in writing is the same forensic opinion in a different form.' },
      { id: 'd', text: 'Explain she cannot give a custody opinion and refer him to an evaluator', isCorrect: true, rationale: 'E.13.c bars evaluating current clients for forensic purposes; a neutral evaluator is the proper source.' },
    ],
    rationale: 'ACA E.13.c states that counselors do not evaluate current or former clients, clients\' romantic partners or clients\' family members for forensic purposes. A treating counselor lacks the neutrality and full information a custody evaluation requires. If legally compelled, she may testify as a fact witness with appropriate consent, describing treatment rather than recommending custody.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.13.c Client Evaluation Prohibited' }, { source: 'ACA Code of Ethics', detail: 'A.6.e Nonprofessional Interactions or Relationships (Other Than Sexual or Romantic)' }],
  },
  {
    id: 'nce-s-eth-095',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'record keeping and documentation',
    difficulty: 'hard',
    stem: 'A client with adjustment disorder learns his insurer will pay for more sessions only for "a serious diagnosis." He asks his counselor to record major depressive disorder, and the practice manager says, "Everyone does it." What should the counselor do?',
    options: [
      { id: 'a', text: 'Record major depression, since the client has consented to the code', isCorrect: false, rationale: 'Client consent does not make a false diagnosis to an insurer honest or legal.' },
      { id: 'b', text: 'Keep the accurate diagnosis and discuss other payment or care options', isCorrect: true, rationale: 'Diagnoses must be accurate; the counselor can explore sliding fees, self-pay or referral.' },
      { id: 'c', text: 'Record major depression only until the client\'s finances stabilize', isCorrect: false, rationale: 'A time-limited false diagnosis is still fraudulent billing.' },
      { id: 'd', text: 'Follow the manager\'s direction, since the practice bears the billing risk', isCorrect: false, rationale: 'Employer pressure does not excuse misrepresentation; the counselor is personally accountable.' },
    ],
    rationale: 'Counselors provide proper diagnoses (ACA E.5.a) and are accurate, honest and objective in reports to third parties, including insurers (C.6.b). Upcoding a diagnosis to obtain payment is insurance fraud and can also harm the client through an inaccurate permanent record. The counselor addresses the financial barrier through legitimate options instead.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.5.a Proper Diagnosis; C.6.b Reports to Third Parties' }],
  },
  {
    id: 'nce-s-eth-096',
    reviewNote: 'Subpoena response and revocation handling vary by state and court rules; confirm the general guidance.',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'confidentiality and its limits',
    difficulty: 'hard',
    stem: 'A client signed a release last month letting her counselor share records in her divorce case. On the same day, the counselor receives a subpoena for the records from the spouse\'s attorney and a signed letter from the client revoking the release. What should the counselor do?',
    options: [
      { id: 'a', text: 'Send the records, since the release was valid when the subpoena was issued', isCorrect: false, rationale: 'Revocation applies to future disclosures; nothing has yet been released in reliance on it.' },
      { id: 'b', text: 'Ignore the subpoena, since the client has now withdrawn her permission', isCorrect: false, rationale: 'A subpoena is a legal document that must receive a timely response.' },
      { id: 'c', text: 'Honor the revocation, respond to the subpoena, and seek a court order', isCorrect: true, rationale: 'The revocation stops voluntary release; the counselor responds without disclosing and asserts privilege.' },
      { id: 'd', text: 'Send a summary only, since that limits what the spouse\'s side will see', isCorrect: false, rationale: 'Any disclosure now lacks valid consent or a court order.' },
    ],
    rationale: 'A client may revoke an authorization in writing, and the revocation applies to any disclosure not yet made. A subpoena alone is not a court order, so the counselor responds in a timely way, notifies the client, asserts privilege on her behalf, consults an attorney, and discloses only what a court orders, limiting it to what is necessary (ACA B.2.c and B.2.e).',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.c Court-Ordered Disclosure' }, { source: 'HIPAA', detail: '45 CFR 164.508(b)(5) Revocation of authorizations' }],
  },
];
