// tools/nce/seed/ethics-5.js — Professional Practice and Ethics, batch 5
// Hand-authored original items (nce-s-eth-097 … nce-s-eth-120).
module.exports = [
  {
    id: 'nce-s-eth-097',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'medium',
    stem: 'After a careful risk assessment, a counselor concludes that she must notify a man whom her client, a 31-year-old warehouse worker, has credibly threatened to stab. What information should she share when she makes the call?',
    options: [
      { id: 'a', text: 'The client\'s full diagnosis, treatment history and recent session notes for context', isCorrect: false, rationale: 'Diagnosis, history and notes go well beyond what is needed to protect the man.' },
      { id: 'b', text: 'Nothing that names the client, so the client\'s privacy is kept fully intact', isCorrect: false, rationale: 'A warning that does not identify the source of danger may not let the man protect himself.' },
      { id: 'c', text: 'Only the essential facts: who poses the threat and the nature of the danger', isCorrect: true, rationale: 'B.2.e directs that only essential information is revealed when disclosure is required.' },
      { id: 'd', text: 'Whatever the man asks about the client, since the duty overrides all privacy', isCorrect: false, rationale: 'The duty to protect permits a limited disclosure, not open access to the client\'s information.' },
    ],
    rationale: 'When serious and foreseeable harm requires a disclosure, ACA B.2.e limits it to essential information. In a warning, that means enough for the person to protect themselves, such as the source and nature of the threat, without diagnosis or treatment details. Where possible, the client is told about the disclosure beforehand and involved in the decision.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.e Minimal Disclosure' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-098',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'hard',
    stem: 'The father of an adult client calls a counselor and says his son has been talking about "getting even" with his ex-partner\'s new boyfriend and has been driving past the boyfriend\'s home. The client has said nothing like this in session. How should the counselor BEST view the father\'s report?',
    options: [
      { id: 'a', text: 'As risk information to assess promptly, since some state laws treat it as able to trigger a duty', isCorrect: true, rationale: 'Courts in some states (e.g., Ewing v. Goldstein) have held that a family member\'s report to the therapist can trigger the duty to protect.' },
      { id: 'b', text: 'As hearsay that cannot create any duty, because only the client\'s own words count in law', isCorrect: false, rationale: 'This is not true in every jurisdiction; some courts have held otherwise, and clinically the report must be assessed.' },
      { id: 'c', text: 'As grounds to warn the boyfriend at once, before speaking with the client about any of it', isCorrect: false, rationale: 'A warning without assessment skips the step that tells the counselor whether the risk is serious and foreseeable.' },
      { id: 'd', text: 'As a confidentiality breach by the father, which the counselor should report to the client', isCorrect: false, rationale: 'The father did not breach any duty, and treating the call this way ignores a possible risk to an identifiable person.' },
    ],
    rationale: 'Information about a client\'s dangerousness does not have to come from the client to be clinically and legally significant. In Ewing v. Goldstein (2004), a California appellate court held that a family member\'s report to the therapist could trigger the statutory duty to protect. Counselors assess such reports promptly, consult, and follow the law of their own state.',
    references: [{ source: 'State law', detail: 'Ewing v. Goldstein (Cal. Ct. App. 2004): family member communications and the duty to protect' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-099',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'duty to warn and protect',
    difficulty: 'easy',
    stem: 'A counseling student asks why many textbooks now use the phrase "duty to protect" rather than "duty to warn." Which answer is MOST accurate?',
    options: [
      { id: 'a', text: 'Duty to protect applies only to suicide risk, while duty to warn covers harm to others', isCorrect: false, rationale: 'Both terms concern danger to others; suicide risk is handled under separate standards.' },
      { id: 'b', text: 'Duty to protect requires that police be called first, before any other step is taken', isCorrect: false, rationale: 'No single required first step applies; options depend on the case and on state law.' },
      { id: 'c', text: 'Duty to protect means the counselor shares liability for any harm the client commits', isCorrect: false, rationale: 'The term describes the clinician\'s obligation to act reasonably, not automatic liability.' },
      { id: 'd', text: 'Protecting may involve steps besides a warning, such as hospitalization or police contact', isCorrect: true, rationale: 'The 1976 Tarasoff ruling framed the duty as reasonable care to protect, which a warning alone may or may not meet.' },
    ],
    rationale: 'The 1976 Tarasoff decision held that when a therapist determines a patient presents a serious danger of violence to another, the therapist must use reasonable care to protect the intended victim. Warning the victim is one option; others include notifying police, arranging hospitalization, or intensifying treatment. State laws define which actions discharge the duty.',
    references: [{ source: 'State law', detail: 'Tarasoff v. Regents of the University of California (1976): duty to use reasonable care to protect' }],
  },
  {
    id: 'nce-s-eth-100',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'medium',
    stem: 'An agency counselor tells her supervisor that a 9-year-old client described being burned with a cigarette by a parent\'s partner. The supervisor says, "I\'ll take care of the report." Two days later, the counselor cannot confirm that any report was made. What should she do?',
    options: [
      { id: 'a', text: 'Wait for the supervisor to follow up, since the agency chain of command now owns it', isCorrect: false, rationale: 'In most states the mandated reporter\'s duty is personal and is not met by telling a supervisor.' },
      { id: 'b', text: 'Make the report herself now, since telling a supervisor does not discharge her duty', isCorrect: true, rationale: 'Mandated reporting duties generally rest on the individual; she must make sure a report is made promptly.' },
      { id: 'c', text: 'Ask the child about the burn in more detail first, so the report will be complete', isCorrect: false, rationale: 'Investigating is the role of child protective services; more questioning can harm the child and the case.' },
      { id: 'd', text: 'Call the parent\'s partner to hear his account before deciding whether to report', isCorrect: false, rationale: 'Contacting the alleged abuser can put the child at further risk and is not the counselor\'s role.' },
    ],
    rationale: 'In most jurisdictions a mandated reporter\'s obligation is individual: informing a supervisor or administrator does not relieve the counselor of the duty to make sure a report reaches child protective services or law enforcement within the required time. Agency procedures can support reporting but do not replace it. The counselor should report and document the date, time and agency contacted.',
    references: [{ source: 'State law', detail: 'Child abuse reporting statutes: individual duty of mandated reporters and reporting timelines' }],
  },
  {
    id: 'nce-s-eth-101',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'hard',
    stem: 'A 40-year-old father in counseling for anger tells his counselor that last week he struck his 6-year-old with a belt, leaving welts. He says it will not happen again and that counseling is how he is "fixing it." He asks the counselor to keep it private. What should the counselor do?',
    options: [
      { id: 'a', text: 'Keep it confidential, since the client is already in treatment for the very problem', isCorrect: false, rationale: 'Being in treatment does not remove the legal duty to report suspected child abuse.' },
      { id: 'b', text: 'File the required report and discuss it with the client, as reviewed in informed consent', isCorrect: true, rationale: 'Mandated reporting applies when the client is the alleged abuser; the counselor can stay engaged and transparent.' },
      { id: 'c', text: 'Report only if the client strikes the child again, since this was a single incident', isCorrect: false, rationale: 'Reporting laws do not wait for repeated abuse; one incident with injury can trigger the duty.' },
      { id: 'd', text: 'End counseling and refer him elsewhere, so a new provider can decide about reporting', isCorrect: false, rationale: 'Referring out evades the duty and abandons a client who is seeking help.' },
    ],
    rationale: 'Child abuse reporting laws apply regardless of whether the person disclosing is the victim, a witness, or the alleged perpetrator, and they do not exempt clients who are already in treatment. Because reporting is a limit of confidentiality, it should be covered in informed consent at the start. Counselors can report while staying engaged and supporting the client\'s change efforts.',
    references: [{ source: 'State law', detail: 'Child abuse reporting statutes: duty applies to disclosures by alleged perpetrators' }, { source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }],
  },
  {
    id: 'nce-s-eth-102',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'mandated reporting of abuse and neglect',
    difficulty: 'easy',
    stem: 'A new school counselor hesitates to report a suspicion of neglect because she fears the family will sue her if child protective services finds nothing. What should her supervisor tell her?',
    options: [
      { id: 'a', text: 'She should wait for proof, since a report that turns out unfounded can lead to liability', isCorrect: false, rationale: 'The standard is reasonable suspicion, not proof, and good-faith reports are protected.' },
      { id: 'b', text: 'She may report anonymously, which is the only way to avoid being named in a lawsuit', isCorrect: false, rationale: 'Mandated reporters usually must identify themselves; protection comes from good-faith immunity.' },
      { id: 'c', text: 'State laws give immunity for reports made in good faith, even if abuse is not found', isCorrect: true, rationale: 'All states grant immunity from liability for good-faith reports, and failing to report can carry penalties.' },
      { id: 'd', text: 'She should get the parents\' consent before reporting, which protects her from a suit', isCorrect: false, rationale: 'Parental consent is not required to report and seeking it could put the child at risk.' },
    ],
    rationale: 'Mandated reporters must report when they have reasonable cause to suspect abuse or neglect. State laws, consistent with federal CAPTA requirements, protect people who report in good faith from civil and criminal liability even when the report is not substantiated. By contrast, knowingly failing to report can bring fines or other penalties.',
    references: [{ source: 'State law', detail: 'Good-faith immunity for child abuse and neglect reporters; penalties for failure to report' }],
  },
  {
    id: 'nce-s-eth-103',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'medium',
    stem: 'A billing specialist at a HIPAA-covered group practice asks a counselor to forward complete session notes for every client so claims can be submitted faster. Which HIPAA principle MOST directly applies?',
    options: [
      { id: 'a', text: 'Minimum necessary: share only the information that is needed to process the claims', isCorrect: true, rationale: 'For payment and operations uses, the minimum necessary standard limits what staff may access.' },
      { id: 'b', text: 'Right of access: staff have the same rights to full records that clients themselves do', isCorrect: false, rationale: 'The right of access belongs to the individual client, not to workforce members.' },
      { id: 'c', text: 'Treatment exception: anyone in the practice may see full notes without any limits', isCorrect: false, rationale: 'Billing is a payment function, not treatment, and is subject to minimum necessary limits.' },
      { id: 'd', text: 'Breach notification: clients must be told each time a billing staff member views notes', isCorrect: false, rationale: 'Breach notification applies to impermissible disclosures, not routine permitted access.' },
    ],
    rationale: 'The HIPAA Privacy Rule requires covered entities to limit uses and disclosures of protected health information to the minimum necessary to accomplish the purpose. Claims usually need dates, codes and diagnoses, not full session content. The minimum necessary standard does not apply to disclosures to other providers for treatment, but billing is a payment function.',
    references: [{ source: 'HIPAA', detail: 'Privacy Rule minimum necessary standard (45 CFR 164.502(b), 164.514(d))' }],
  },
  {
    id: 'nce-s-eth-104',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'easy',
    stem: 'A counselor opening a private practice that bills health insurance electronically is setting up her intake paperwork. Under the HIPAA Privacy Rule, what must she give new clients?',
    options: [
      { id: 'a', text: 'A full copy of her case notes from every past client so they can judge her methods', isCorrect: false, rationale: 'Sharing other clients\' records would itself be a serious privacy violation.' },
      { id: 'b', text: 'A signed waiver giving up their right to see their own records for the treatment term', isCorrect: false, rationale: 'HIPAA gives clients a right of access; providers may not require waiving it.' },
      { id: 'c', text: 'A written guarantee that no information will be shared without their permission ever', isCorrect: false, rationale: 'HIPAA and law permit some disclosures without authorization, so this promise is inaccurate.' },
      { id: 'd', text: 'A Notice of Privacy Practices, with a good-faith effort to get written acknowledgment', isCorrect: true, rationale: 'Direct treatment providers give the notice at first service and try to obtain acknowledgment of receipt.' },
    ],
    rationale: 'A covered health care provider with a direct treatment relationship must give clients a Notice of Privacy Practices no later than the first service and make a good-faith effort to obtain written acknowledgment of receipt. The notice explains how information may be used and disclosed and describes clients\' rights, such as access and amendment.',
    references: [{ source: 'HIPAA', detail: 'Notice of Privacy Practices and acknowledgment of receipt (45 CFR 164.520)' }],
  },
  {
    id: 'nce-s-eth-105',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'HIPAA and FERPA basics for counselors',
    difficulty: 'hard',
    stem: 'The mother of a 20-year-old university student calls the campus counseling center and demands her daughter\'s counseling records, saying FERPA gives her a right to them because she pays tuition. The records are used only for the student\'s treatment. What is the BEST response?',
    options: [
      { id: 'a', text: 'Release the records, since FERPA gives parents of college students full access', isCorrect: false, rationale: 'At the postsecondary level FERPA rights belong to the student, not the parent.' },
      { id: 'b', text: 'Release a summary only, since paying tuition gives the parent a partial FERPA right', isCorrect: false, rationale: 'Paying tuition does not create a FERPA access right to counseling records.' },
      { id: 'c', text: 'Decline; these are treatment records, and the student\'s consent would be needed', isCorrect: true, rationale: 'Records made and used only for treatment are excluded from FERPA education records.' },
      { id: 'd', text: 'Release them after a 45-day wait, the timeline FERPA sets for record requests', isCorrect: false, rationale: 'The 45-day timeline applies to eligible students\' own access requests, not to this parent.' },
    ],
    rationale: 'Under FERPA, records on a student who is 18 or older or in postsecondary education that are made by a mental health professional, used only for treatment, and shared only with treating providers are treatment records, excluded from education records. FERPA rights at a university belong to the student. Counselors protect these records and release them with the student\'s consent or as law allows.',
    references: [{ source: 'FERPA', detail: 'Definition of education records; exclusion of treatment records (34 CFR 99.3)' }, { source: 'ACA Code of Ethics', detail: 'B.6.g Disclosure or Transfer' }],
  },
  {
    id: 'nce-s-eth-106',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'medium',
    stem: 'A counselor provides text-based counseling through a secure platform. A new client prefers to use only a screen name and has not turned on video. Under the ACA Code of Ethics, what should the counselor do?',
    options: [
      { id: 'a', text: 'Take steps to verify the client\'s identity at the outset and during the counseling', isCorrect: true, rationale: 'H.3 calls for verifying client identity at the beginning and throughout distance counseling.' },
      { id: 'b', text: 'Accept the screen name alone, since anonymity is a core benefit of online counseling', isCorrect: false, rationale: 'Anonymity does not remove the need to know who the client is, for example in emergencies.' },
      { id: 'c', text: 'Require the client to mail in a notarized identity form before any text exchange', isCorrect: false, rationale: 'This is an unnecessary barrier; the Code suggests simpler methods such as code words.' },
      { id: 'd', text: 'Decline to work by text, since the Code permits distance counseling by video only', isCorrect: false, rationale: 'The Code addresses many technologies, including text, and does not limit services to video.' },
    ],
    rationale: 'ACA H.3 directs counselors who use distance counseling to verify a client\'s identity at the beginning and throughout the process, for example with code words, numbers or other identifiers. Verification matters for consent, for protecting confidentiality, and for responding if the client is in crisis.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.3 Client Verification' }],
  },
  {
    id: 'nce-s-eth-107',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'hard',
    stem: 'A counselor has seen a 66-year-old client by video for two months. The client\'s hearing loss and unreliable internet now make sessions hard to follow, and both agree little progress is being made. The counselor\'s office is a short drive from the client. What does the ACA Code of Ethics direct?',
    options: [
      { id: 'a', text: 'Keep using video, since the client chose telehealth at the start and consent is set', isCorrect: false, rationale: 'Informed consent is ongoing, and the Code addresses what to do when distance services are not working.' },
      { id: 'b', text: 'Consider delivering services face-to-face, since distance services are not effective', isCorrect: true, rationale: 'H.4.d directs counselors to consider face-to-face services when distance counseling is ineffective.' },
      { id: 'c', text: 'End counseling, because poor technology means the client cannot benefit from services', isCorrect: false, rationale: 'Ending services ignores an available in-person option that could meet the client\'s needs.' },
      { id: 'd', text: 'Switch to email only, since written messages avoid both hearing and connection issues', isCorrect: false, rationale: 'Email-only work is a major change that may not be effective and should not be imposed this way.' },
    ],
    rationale: 'ACA H.4.d states that when distance counseling services are deemed ineffective by the counselor or client, counselors consider delivering services face-to-face; if that is not possible, they help the client find appropriate services. H.4.e also asks counselors to consider access issues. Here an in-person option is close at hand.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.4.d Effectiveness of Services' }],
  },
  {
    id: 'nce-s-eth-108',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'telehealth and technology ethics',
    difficulty: 'easy',
    stem: 'A counselor in private practice wants to use a free consumer video-chat app for telehealth sessions because clients already have it on their phones. What is the MAIN ethical concern?',
    options: [
      { id: 'a', text: 'Free apps cost too little to count as a legitimate professional business expense', isCorrect: false, rationale: 'Cost is not the ethical issue; security of client information is.' },
      { id: 'b', text: 'Clients may enjoy video sessions more than in-person ones and stop coming to the office', isCorrect: false, rationale: 'Client preference for telehealth is not an ethical problem.' },
      { id: 'c', text: 'Video sessions cannot be billed, so offering them would mislead clients about fees', isCorrect: false, rationale: 'Many payers reimburse telehealth; billing rules are not the main concern here.' },
      { id: 'd', text: 'The platform may not use encryption and safeguards that meet legal privacy standards', isCorrect: true, rationale: 'H.2.d requires current encryption standards that meet applicable legal requirements.' },
    ],
    rationale: 'ACA H.2.d directs counselors to use current encryption standards in technology-based communications that meet applicable legal requirements. Under HIPAA, a covered counselor also needs appropriate safeguards and, typically, a business associate agreement with the platform vendor. Convenience does not outweigh protecting client confidentiality.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.2.d Security' }, { source: 'HIPAA', detail: 'Security Rule safeguards for electronic PHI and business associate agreements' }],
  },
  {
    id: 'nce-s-eth-109',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'termination and referral',
    difficulty: 'easy',
    stem: 'A 52-year-old client has met all of his goals for managing panic attacks and has had no symptoms for three months. He enjoys sessions and asks to keep coming every week "just to talk." What is the counselor\'s MOST appropriate response?',
    options: [
      { id: 'a', text: 'Discuss ending counseling, since he no longer appears to need the counselor\'s help', isCorrect: true, rationale: 'A.11.c says to terminate when it is reasonably apparent the client no longer needs assistance.' },
      { id: 'b', text: 'Continue weekly sessions indefinitely, since the client wants them and pays for them', isCorrect: false, rationale: 'Continuing services that are no longer needed does not serve the client\'s welfare.' },
      { id: 'c', text: 'End services at the next session without discussion, since his goals have been met', isCorrect: false, rationale: 'Termination should be planned and discussed, not abrupt.' },
      { id: 'd', text: 'Set new goals for him so that continued weekly sessions can be justified to the payer', isCorrect: false, rationale: 'Creating goals to justify services puts the counselor\'s or payer\'s needs ahead of the client.' },
    ],
    rationale: 'ACA A.11.c directs counselors to terminate when it becomes reasonably apparent that clients no longer need assistance, are not likely to benefit, or are being harmed by continued counseling. Termination is a planned process that reviews gains, prepares for setbacks, and leaves the door open to return if new concerns arise.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' }],
  },
  {
    id: 'nce-s-eth-110',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'termination and referral',
    difficulty: 'medium',
    stem: 'In week five of a 12-week closed process group for young adults, a member privately tells the leader he plans to quit and will not come back. He says he feels criticized by other members. What should the leader do FIRST?',
    options: [
      { id: 'a', text: 'Insist that he finish all 12 weeks, as he agreed to that commitment when he joined', isCorrect: false, rationale: 'Members have the right to leave; the leader cannot require them to stay.' },
      { id: 'b', text: 'Tell the group next week that he quit because the others had criticized him too much', isCorrect: false, rationale: 'Disclosing his private reasons without consent would breach his trust.' },
      { id: 'c', text: 'Explore his reasons and encourage him to raise the decision in the group before leaving', isCorrect: true, rationale: 'Discussing the decision in group can resolve the conflict and lets members process the ending.' },
      { id: 'd', text: 'Accept his choice at once and remove him from the group without any more discussion', isCorrect: false, rationale: 'Quick acceptance misses a chance to address the conflict and can harm the member and the group.' },
    ],
    rationale: 'A member\'s abrupt departure affects both the member and the group. Leaders respect a member\'s right to leave but explore the reasons and encourage the member to talk about the decision in the group, where interpersonal tension can often be worked through. Policies on leaving the group are best explained during pre-group orientation.',
    references: [{ source: 'Yalom & Leszcz (Group Psychotherapy)', detail: 'Premature termination: dropouts and discussing departure in the group' }, { source: 'ASGW Best Practice Guidelines', detail: 'Planning and performing: informing members of group policies and procedures' }],
  },
  {
    id: 'nce-s-eth-111',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'termination and referral',
    difficulty: 'hard',
    stem: 'A client in private practice has missed three payments despite reminders and a reduced fee. The counselor\'s consent form explains what happens when fees go unpaid. The client is not in crisis. Which course BEST fits the ACA Code of Ethics?',
    options: [
      { id: 'a', text: 'Keep seeing the client for free, since ending services over money is forbidden', isCorrect: false, rationale: 'A.11.c permits termination for nonpayment of agreed fees.' },
      { id: 'b', text: 'Stop scheduling sessions and send a letter, with no need for further discussion', isCorrect: false, rationale: 'Ending without pretermination counseling risks abandonment.' },
      { id: 'c', text: 'Hold the client\'s records until the balance is paid, then plan a referral after', isCorrect: false, rationale: 'Withholding records over a debt harms the client and is not an appropriate step.' },
      { id: 'd', text: 'End services for nonpayment, with pretermination counseling and referral options', isCorrect: true, rationale: 'The Code allows termination for unpaid fees when the counselor provides pretermination counseling and referrals.' },
    ],
    rationale: 'ACA A.11.c permits counselors to terminate when clients do not pay fees as agreed, but they provide pretermination counseling and recommend other service providers when necessary. Explaining nonpayment procedures in informed consent at the start makes this process fair and predictable.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' }],
  },
  {
    id: 'nce-s-eth-112',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'informed consent and its required elements',
    difficulty: 'medium',
    stem: 'Four months into talk therapy, a counselor believes a structured exposure-based approach would help a client with social anxiety. The client signed a general consent form at intake. What should the counselor do before starting the new approach?',
    options: [
      { id: 'a', text: 'Start it next session, since the intake consent already covered the counseling services', isCorrect: false, rationale: 'General consent at intake does not cover a major change in modality.' },
      { id: 'b', text: 'Explain the approach, its risks and benefits, and the client\'s right to decline it', isCorrect: true, rationale: 'A.2.a and A.2.b describe consent as ongoing and give clients the right to refuse modality changes.' },
      { id: 'c', text: 'Get a supervisor\'s approval, since the client cannot judge the merits of the technique', isCorrect: false, rationale: 'Consultation may help, but it does not replace the client\'s own informed choice.' },
      { id: 'd', text: 'Introduce the exercises gradually without labeling them so the client does not worry', isCorrect: false, rationale: 'Hiding the nature of an intervention undermines informed consent and trust.' },
    ],
    rationale: 'ACA A.2.a treats informed consent as an ongoing part of counseling that is documented throughout the relationship. A.2.b includes the client\'s right to be informed about techniques, risks and benefits, and to refuse any services or modality changes and be told the consequences. A new approach calls for a fresh consent discussion.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.a Informed Consent; A.2.b Types of Information Needed' }],
  },
  {
    id: 'nce-s-eth-113',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'informed consent and its required elements',
    difficulty: 'medium',
    stem: 'A counselor will lead a 16-week group for adults ordered by a court to attend after domestic violence convictions. The probation office requires attendance and progress reports. What must the counselor explain to members before the group begins?',
    options: [
      { id: 'a', text: 'What information will be shared with the probation office and with whom it is shared', isCorrect: true, rationale: 'A.2.e requires explaining to mandated clients what information is shared and with whom.' },
      { id: 'b', text: 'That everything said in group stays confidential, the same as in voluntary counseling', isCorrect: false, rationale: 'This misstates the limits; reports to probation are required in a mandated group.' },
      { id: 'c', text: 'That members have no right to refuse services because the court ordered the group', isCorrect: false, rationale: 'Mandated clients may refuse; counselors discuss the possible consequences of refusing.' },
      { id: 'd', text: 'That progress reports will be shared only if a member breaks one of the group\'s rules', isCorrect: false, rationale: 'Reports are routine in this setting, and members need to know that up front.' },
    ],
    rationale: 'ACA A.2.e directs counselors working with mandated clients to discuss the required limits of confidentiality and to explain what type of information is shared and with whom before counseling begins. Clients may still choose to refuse services, and counselors discuss the potential consequences. In groups, this pre-group orientation is part of informed consent.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.e Mandated Clients' }, { source: 'ASGW Best Practice Guidelines', detail: 'Planning: informed consent and orientation of prospective members' }],
  },
  {
    id: 'nce-s-eth-114',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'informed consent and its required elements',
    difficulty: 'medium',
    stem: 'A counselor educator wants students in her practicum course to complete surveys for her study on counselor self-efficacy. What must she make clear to the students under the ACA Code of Ethics?',
    options: [
      { id: 'a', text: 'Taking part is a course requirement, since research is part of professional training', isCorrect: false, rationale: 'Making participation mandatory removes the voluntary choice the Code protects.' },
      { id: 'b', text: 'Students who take part will get extra credit that others cannot earn any other way', isCorrect: false, rationale: 'Credit available only through participation pressures students; an equal alternative is needed.' },
      { id: 'c', text: 'Students may decline, but declining will be noted in the course evaluation file', isCorrect: false, rationale: 'Recording refusals in evaluations links participation to academic standing.' },
      { id: 'd', text: 'Choosing not to take part will not affect their grades, and an alternative is offered', isCorrect: true, rationale: 'The Code requires that participation not affect academic standing and that an alternative be offered.' },
    ],
    rationale: 'Under ACA Section G, researchers who involve students or supervisees make clear that the decision to participate does not affect academic standing or the supervisory relationship. Students who choose not to participate are given an appropriate alternative way to meet any requirement. This protects voluntary consent where a power imbalance exists.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.2 Rights of Research Participants (Student/Supervisee Participation)' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Informed consent and voluntary participation' }],
  },
  {
    id: 'nce-s-eth-115',
    domain: 'ethics',
    cacrep: 'research',
    topic: 'informed consent and its required elements',
    difficulty: 'hard',
    stem: 'An IRB approved a study in which participants were told it measured "attention" when it really measured reactions to staged peer feedback. Data collection for each participant has just ended. What is the researcher\'s main obligation at this point?',
    options: [
      { id: 'a', text: 'Keep the true purpose hidden so that future participants will not learn of it from them', isCorrect: false, rationale: 'Protecting the design does not override participants\' right to a full explanation.' },
      { id: 'b', text: 'Wait to explain the study until results are published so the findings stay unbiased', isCorrect: false, rationale: 'Clarification is owed after data collection, not delayed until publication.' },
      { id: 'c', text: 'Fully explain the study\'s nature and correct any misconceptions the deception caused', isCorrect: true, rationale: 'The Code requires full clarification after data collection to remove misconceptions.' },
      { id: 'd', text: 'Send a brief thank-you note, since the IRB approval already covers the deception used', isCorrect: false, rationale: 'IRB approval does not replace the duty to debrief participants.' },
    ],
    rationale: 'ACA Section G directs that after data are collected, counselors give participants full clarification of the nature of the study to remove any misconceptions. When deception was used, this debriefing explains what was concealed and why. Where withholding information is justified, researchers take reasonable steps to avoid harm.',
    references: [{ source: 'ACA Code of Ethics', detail: 'G.2 Rights of Research Participants (Explanations After Data Collection)' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Deception and debriefing in research with human participants' }],
  },
  {
    id: 'nce-s-eth-116',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'scope of practice and competence',
    difficulty: 'medium',
    stem: 'Midway through a timed achievement test given to a 14-year-old student, a fire alarm forces a 20-minute evacuation. The counselor resumes the test afterward. How should the counselor handle the results?',
    options: [
      { id: 'a', text: 'Score and report the results as usual, since the student finished all of the test', isCorrect: false, rationale: 'An interruption is an irregularity that may affect validity and must not be ignored.' },
      { id: 'b', text: 'Note the irregularity in the interpretation, and treat results as questionable', isCorrect: true, rationale: 'The Code requires noting nonstandard conditions; results may be invalid or of questionable validity.' },
      { id: 'c', text: 'Add 20 minutes of credit to the student\'s raw score to make up for the lost time', isCorrect: false, rationale: 'Adjusting scores by hand has no basis in the norms and distorts the results.' },
      { id: 'd', text: 'Destroy the answer sheet and record that the student did not take the test at all', isCorrect: false, rationale: 'Destroying data and misreporting events is dishonest and is not required.' },
    ],
    rationale: 'Under ACA Section E, counselors give assessments under the conditions set during standardization. When irregularities occur during administration, those conditions are noted in interpretation, and results may be designated as invalid or of questionable validity. Retesting with an alternate form may be considered if appropriate.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.7 Conditions of Assessment Administration (administration conditions and irregularities)' }, { source: 'Hays (Assessment)', detail: 'Standardized administration and threats to validity' }],
  },
  {
    id: 'nce-s-eth-117',
    domain: 'ethics',
    cacrep: 'assessment',
    topic: 'record keeping and documentation',
    difficulty: 'medium',
    stem: 'A school team wants to decide a 12-year-old\'s placement using intelligence and achievement scores from testing done when the student was 7, on an edition of the test that has since been revised. Under the ACA Code of Ethics, what should the counselor advise?',
    options: [
      { id: 'a', text: 'Do not rely on those outdated results for this decision; seek current assessment data', isCorrect: true, rationale: 'E.11 bars using obsolete or outdated assessment results for the current purpose.' },
      { id: 'b', text: 'Use the old scores, since intelligence is stable and the earlier testing was valid', isCorrect: false, rationale: 'Results from five years earlier on an older edition are outdated for today\'s decision.' },
      { id: 'c', text: 'Use the old scores but raise each by a few points to adjust for the student\'s growth', isCorrect: false, rationale: 'Ad hoc score adjustment has no psychometric basis.' },
      { id: 'd', text: 'Let the team decide, since placement is an education matter outside assessment ethics', isCorrect: false, rationale: 'Counselors have an ethical duty to prevent misuse of outdated assessment data by others.' },
    ],
    rationale: 'ACA E.11 states that counselors do not use data or results from assessments that are obsolete or outdated for the current purpose, such as noncurrent versions of instruments, and they make every effort to prevent others from misusing obsolete measures and data. High-stakes decisions call for current, appropriate assessment.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.11 Obsolete Assessment and Outdated Results' }],
  },
  {
    id: 'nce-s-eth-118',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'multiple relationships and boundary crossings',
    difficulty: 'medium',
    stem: 'While screening for a new depression support group, a counselor learns that one applicant is her next-door neighbor, whose children play with hers. The applicant is a good clinical fit. What is the BEST course of action?',
    options: [
      { id: 'a', text: 'Admit the neighbor without comment, since screening is about clinical fit and not the leader', isCorrect: false, rationale: 'Screening also weighs relationships that could harm the member or the group.' },
      { id: 'b', text: 'Admit the neighbor but avoid any contact at home for the full length of the group', isCorrect: false, rationale: 'Avoiding the neighbor is unrealistic and does not address the dual relationship itself.' },
      { id: 'c', text: 'Ask other members to vote on whether the neighbor may join at the first session', isCorrect: false, rationale: 'This exposes the applicant\'s private information and shifts the leader\'s duty to members.' },
      { id: 'd', text: 'Discuss the dual-relationship risks with the applicant and help find another group', isCorrect: true, rationale: 'A pre-existing personal relationship is a reason to explore risks and refer to another group.' },
    ],
    rationale: 'ACA A.9.a asks group leaders to screen prospective members and select those whose well-being will not be jeopardized by the group experience. A close personal relationship with the leader creates a dual relationship that can compromise objectivity and the member\'s comfort in group. When an alternative exists, referral is usually best.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.9.a Screening' }, { source: 'ASGW Best Practice Guidelines', detail: 'Screening and selection of members; avoiding dual relationships' }],
  },
  {
    id: 'nce-s-eth-119',
    domain: 'ethics',
    cacrep: 'professional_orientation',
    topic: 'ethical decision-making models',
    difficulty: 'medium',
    stem: 'A counselor using Forester-Miller and Davis\'s Practitioner\'s Guide has clearly identified the problem: a client\'s employer wants session updates. According to the model, what should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Brainstorm as many possible courses of action as she can with a trusted colleague', isCorrect: false, rationale: 'Generating options is a later step in the model.' },
      { id: 'b', text: 'Pick the action she favors and test it against justice, publicity and universality', isCorrect: false, rationale: 'Evaluating a chosen action comes after options are generated and weighed.' },
      { id: 'c', text: 'Apply the ACA Code of Ethics to see whether it addresses or resolves the issue', isCorrect: true, rationale: 'Applying the ACA Code is the second step, right after identifying the problem.' },
      { id: 'd', text: 'Carry out the most cautious response at once and record her reasons in the file', isCorrect: false, rationale: 'Implementing a course of action is the final step of the model.' },
    ],
    rationale: 'Forester-Miller and Davis outline seven steps: identify the problem, apply the ACA Code of Ethics, determine the nature and dimensions of the dilemma, generate potential courses of action, consider consequences and choose, evaluate the selected course, and implement it. If the Code clearly resolves the issue, the counselor follows it; if not, the process continues.',
    references: [{ source: 'Forester-Miller & Davis (Practitioner\'s Guide to Ethical Decision Making)', detail: 'Steps 1 and 2: identify the problem, then apply the ACA Code of Ethics' }],
  },
  {
    id: 'nce-s-eth-120',
    domain: 'ethics',
    cacrep: 'group',
    topic: 'professional organizations and their roles',
    difficulty: 'easy',
    stem: 'A counselor who leads psychoeducational and therapy groups wants to join the ACA division that publishes best practice guidelines and training standards for group workers. Which organization should she join?',
    options: [
      { id: 'a', text: 'American Group Psychotherapy Association', isCorrect: false, rationale: 'AGPA is an independent interdisciplinary group, not an ACA division.' },
      { id: 'b', text: 'Association for Specialists in Group Work', isCorrect: true, rationale: 'ASGW is the ACA division for group work and publishes best practice and training standards.' },
      { id: 'c', text: 'American Mental Health Counselors Association', isCorrect: false, rationale: 'AMHCA represents clinical mental health counselors, not group work specifically.' },
      { id: 'd', text: 'National Board for Certified Counselors', isCorrect: false, rationale: 'NBCC is a credentialing body, not an ACA division.' },
    ],
    rationale: 'The Association for Specialists in Group Work (ASGW) is the ACA division devoted to group work. It publishes the Best Practice Guidelines, the Professional Standards for the Training of Group Workers and the Multicultural and Social Justice Competence Principles for Group Workers. Leaders often use these documents in planning, performing and processing groups.',
    references: [{ source: 'ASGW Best Practice Guidelines', detail: 'ASGW as the ACA division for group work and its guidelines' }],
  },
];
