// tools/nce/seed/intake-1.js — Intake, Assessment, and Diagnosis (original items)
module.exports = [
  {
    id: 'nce-s-ass-001',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'intake interview structure',
    difficulty: 'easy',
    stem: 'A counselor at a community agency begins a first session with a 34-year-old client who has been referred for "stress." Before asking about presenting concerns or history, what should the counselor address?',
    options: [
      { id: 'a', text: 'A full family genogram covering at least three generations', isCorrect: false, rationale: 'A genogram can be useful later, but it is not the opening task and does not secure informed consent.' },
      { id: 'b', text: 'Informed consent, including the limits of confidentiality', isCorrect: true, rationale: 'Clients need to know their rights, the nature of services, and the limits of confidentiality before disclosing sensitive information.' },
      { id: 'c', text: 'A provisional DSM-5-TR diagnosis for the referral form', isCorrect: false, rationale: 'A diagnosis requires assessment data that have not yet been gathered; it cannot come first.' },
      { id: 'd', text: 'Long-term treatment goals the client hopes to reach', isCorrect: false, rationale: 'Goal setting follows assessment of the presenting problem; it is premature at the very start.' },
    ],
    rationale: 'Intake interviews typically open with informed consent and an explanation of confidentiality and its limits, then move to presenting problem, history, mental status, risk, and goals. Discussing limits first lets the client make an informed choice about what to disclose.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.2.a Informed Consent; B.1.d Explanation of Limitations' }],
  },
  {
    id: 'nce-s-ass-002',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'mental status examination',
    difficulty: 'hard',
    stem: 'When asked why he came in, a 61-year-old client describes his commute, the parking garage, a conversation with a neighbor, and the weather in great detail before finally explaining that he has been sleeping poorly. How should the counselor record this in the mental status examination?',
    options: [
      { id: 'a', text: 'Tangentiality, noted under thought process', isCorrect: false, rationale: 'Tangential speech drifts away and does not return to the original question; this client does return to it.' },
      { id: 'b', text: 'Flight of ideas, noted under thought content', isCorrect: false, rationale: 'Flight of ideas involves rapid, accelerated shifts, usually with pressured speech, and is a thought process finding, not content.' },
      { id: 'c', text: 'Circumstantiality, noted under thought process', isCorrect: true, rationale: 'Excessive, irrelevant detail that eventually reaches the point is circumstantiality, a disturbance of thought process.' },
      { id: 'd', text: 'Perseveration, noted under perceptual disturbance', isCorrect: false, rationale: 'Perseveration is repetition of the same response, and it is not a perceptual finding.' },
    ],
    rationale: 'The MSE separates thought process (how ideas connect) from thought content (what the person thinks about). Circumstantial speech is roundabout but goal-directed in the end; tangential speech never gets back to the goal. Both are recorded under thought process.',
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: thought process' }],
  },
  {
    id: 'nce-s-ass-003',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'medium',
    stem: 'During intake, a 19-year-old college student says, "Sometimes I wish I could just go to sleep and not wake up." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Ask directly about thoughts of suicide, plans, intent, and means', isCorrect: true, rationale: 'Passive death wishes call for direct, specific questions about ideation, plan, intent, means, and past behavior to estimate risk.' },
      { id: 'b', text: 'Avoid the subject so as not to put the idea of suicide in her mind', isCorrect: false, rationale: 'Asking about suicide does not increase risk; avoiding it leaves risk unassessed.' },
      { id: 'c', text: 'Arrange an involuntary hospitalization before the session ends', isCorrect: false, rationale: 'Level of care is decided after assessment; a passive wish alone does not establish need for involuntary admission.' },
      { id: 'd', text: 'Refer her to a psychiatrist and end the intake for the day', isCorrect: false, rationale: 'Referral without assessment abandons the risk question and may leave the client without support.' },
    ],
    rationale: 'A wish to be dead is the lowest rung of suicidal ideation on structured tools such as the C-SSRS, but it requires follow-up. The counselor asks plainly about active thoughts, method, intent, plan, preparatory behavior, and prior attempts, then decides on next steps based on that picture.',
    references: [{ source: 'C-SSRS', detail: 'Ideation severity: wish to be dead through active ideation with plan and intent' }],
  },
  {
    id: 'nce-s-ass-004',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'medium',
    stem: 'A 47-year-old veteran reports recurring suicidal thoughts without a current plan or intent. He mentions that he keeps a loaded handgun in his nightstand. Which step is MOST important to include in his safety plan?',
    options: [
      { id: 'a', text: 'A written promise that he will not harm himself before next week', isCorrect: false, rationale: 'No-harm contracts lack evidence of protective value and do not address lethal means.' },
      { id: 'b', text: 'A list of reasons for living to read when he feels hopeless', isCorrect: false, rationale: 'Reasons for living can help, but they do not reduce access to a highly lethal method.' },
      { id: 'c', text: 'A plan to increase his exercise and sleep routine this month', isCorrect: false, rationale: 'Wellness activities are reasonable adjuncts but leave the most urgent risk factor untouched.' },
      { id: 'd', text: 'Lethal means counseling to store the gun outside the home', isCorrect: true, rationale: 'Firearm access sharply raises lethality; collaborative means restriction is a core safety-plan step.' },
    ],
    rationale: 'Firearms are the most lethal common method of suicide, and reducing access during high-risk periods saves lives. The Stanley-Brown Safety Planning Intervention includes making the environment safe, such as having a trusted person hold a firearm or storing it locked away from home.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Step 6 (final step): Making the environment safe, including lethal means' }],
  },
  {
    id: 'nce-s-ass-005',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'easy',
    stem: 'A counselor trained years ago asks a colleague where to record the Axis V Global Assessment of Functioning (GAF) score when using DSM-5-TR. What is the BEST answer?',
    options: [
      { id: 'a', text: 'On Axis V, as in earlier versions of the manual', isCorrect: false, rationale: 'DSM-5-TR has no Axis V; the multiaxial system is gone.' },
      { id: 'b', text: 'On Axis IV, together with psychosocial stressors', isCorrect: false, rationale: 'There are no axes in DSM-5-TR, so Axis IV does not exist either.' },
      { id: 'c', text: 'Nowhere; DSM-5-TR uses nonaxial documentation', isCorrect: true, rationale: 'DSM-5 dropped the multiaxial system and the GAF; diagnoses are listed together without axes.' },
      { id: 'd', text: 'In a required appendix scored from zero to 100', isCorrect: false, rationale: 'No GAF appendix exists; the GAF was removed from the manual.' },
    ],
    rationale: 'DSM-5 and DSM-5-TR replaced the five-axis system with nonaxial documentation. Psychosocial and contextual factors are noted with codes from "Other Conditions That May Be a Focus of Clinical Attention," and the GAF was dropped; the WHODAS 2.0 is offered as a measure of disability.',
    references: [{ source: 'DSM-5-TR', detail: 'Section I: Use of the Manual (nonaxial documentation)' }],
  },
  {
    id: 'nce-s-ass-006',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'hard',
    stem: 'A 28-year-old client currently meets criteria for a major depressive episode. Two years ago she had a 5-day period of elevated mood, decreased need for sleep, and rapid speech that friends noticed, with no marked impairment, hospitalization, or psychotic features. She has had no other mood episodes. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Major depressive disorder, recurrent', isCorrect: false, rationale: 'A past hypomanic episode rules out major depressive disorder.' },
      { id: 'b', text: 'Bipolar II disorder', isCorrect: true, rationale: 'At least one hypomanic episode plus at least one major depressive episode, with no manic episode, defines bipolar II.' },
      { id: 'c', text: 'Bipolar I disorder', isCorrect: false, rationale: 'Bipolar I requires a manic episode, which lasts at least one week (or any duration if hospitalized) and causes marked impairment, hospitalization, or psychosis.' },
      { id: 'd', text: 'Cyclothymic disorder', isCorrect: false, rationale: 'Cyclothymia requires two years of subthreshold symptoms and is excluded once a major depressive episode occurs.' },
    ],
    rationale: 'Hypomania lasts at least four consecutive days, is observable by others, and does not cause marked impairment or require hospitalization. Mania lasts at least a week (or any duration if hospitalized) and is severe enough to cause marked impairment, require hospitalization, or include psychotic features. A hypomanic episode plus a major depressive episode equals bipolar II.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar II Disorder criteria; Hypomanic Episode Criterion A' }],
  },
  {
    id: 'nce-s-ass-007',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'reliability types',
    difficulty: 'easy',
    stem: 'A test developer gives the same anxiety inventory to the same group of adults twice, two weeks apart, and correlates the two sets of scores. Which type of reliability is being estimated?',
    options: [
      { id: 'a', text: 'Test-retest reliability', isCorrect: true, rationale: 'Correlating scores from the same test given twice to the same people estimates stability over time.' },
      { id: 'b', text: 'Alternate-form reliability', isCorrect: false, rationale: 'Alternate-form reliability uses two different but equivalent versions of the test.' },
      { id: 'c', text: 'Split-half reliability', isCorrect: false, rationale: 'Split-half reliability comes from one administration divided into two halves.' },
      { id: 'd', text: 'Interrater reliability', isCorrect: false, rationale: 'Interrater reliability is agreement between two or more scorers or observers.' },
    ],
    rationale: 'Test-retest reliability (the coefficient of stability) reflects how consistent scores are across time. The interval matters: too short invites practice and memory effects, too long lets real change lower the coefficient.',
    references: [{ source: 'Hays (Assessment)', detail: 'Reliability: test-retest (coefficient of stability)' }],
  },
  {
    id: 'nce-s-ass-008',
    domain: 'intake',
    cacrep: 'research',
    topic: 'reliability types',
    difficulty: 'medium',
    stem: 'A school counselor has a single administration of a 40-item vocabulary test in which every item is scored simply right or wrong. Which statistic is BEST suited to estimate the test\'s internal consistency?',
    options: [
      { id: 'a', text: 'A test-retest correlation', isCorrect: false, rationale: 'Test-retest requires two administrations and measures stability, not internal consistency.' },
      { id: 'b', text: 'Cohen\'s kappa coefficient', isCorrect: false, rationale: 'Kappa indexes agreement between raters, corrected for chance.' },
      { id: 'c', text: 'An alternate-form coefficient', isCorrect: false, rationale: 'Alternate-form reliability needs a second, equivalent version of the test.' },
      { id: 'd', text: 'Kuder-Richardson Formula 20', isCorrect: true, rationale: 'KR-20 estimates internal consistency from one administration of dichotomously scored items.' },
    ],
    rationale: 'Internal consistency estimates come from one administration. KR-20 is used with dichotomous (right/wrong) items; coefficient (Cronbach\'s) alpha generalizes it to items with more than two score points. Split-half reliability, corrected with the Spearman-Brown formula, is another single-administration option.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Internal consistency: KR-20 and coefficient alpha' }],
  },
  {
    id: 'nce-s-ass-009',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'validity types',
    difficulty: 'medium',
    stem: 'Developers of a new mechanical aptitude test give it to newly hired technicians and correlate those scores with supervisor performance ratings collected 18 months later. What type of validity evidence does this provide?',
    options: [
      { id: 'a', text: 'Concurrent validity', isCorrect: false, rationale: 'Concurrent validity uses a criterion measured at about the same time as the test.' },
      { id: 'b', text: 'Predictive validity', isCorrect: true, rationale: 'The criterion is measured well after testing, so this is criterion-related predictive validity.' },
      { id: 'c', text: 'Content validity', isCorrect: false, rationale: 'Content validity concerns how well items sample the domain, judged by experts, not a criterion correlation.' },
      { id: 'd', text: 'Discriminant validity', isCorrect: false, rationale: 'Discriminant validity is construct evidence showing low correlation with unrelated constructs.' },
    ],
    rationale: 'Criterion-related validity has two forms that differ by timing: concurrent (criterion gathered at the same time) and predictive (criterion gathered later). Correlating test scores with later job ratings shows how well the test forecasts future performance.',
    references: [{ source: 'Hays (Assessment)', detail: 'Validity: criterion-related (concurrent and predictive)' }],
  },
  {
    id: 'nce-s-ass-010',
    domain: 'intake',
    cacrep: 'research',
    topic: 'validity types',
    difficulty: 'medium',
    stem: 'A new depression scale correlates .78 with an established depression inventory and .06 with a measure of musical aptitude. The low correlation with musical aptitude is BEST described as evidence of which type of validity?',
    options: [
      { id: 'a', text: 'Convergent validity', isCorrect: false, rationale: 'Convergent evidence is the high correlation with the established depression inventory, not the low one.' },
      { id: 'b', text: 'Predictive validity', isCorrect: false, rationale: 'Predictive validity concerns forecasting a later criterion, which is not described here.' },
      { id: 'c', text: 'Discriminant validity', isCorrect: true, rationale: 'A low correlation with a theoretically unrelated construct supports discriminant (divergent) validity.' },
      { id: 'd', text: 'Face validity', isCorrect: false, rationale: 'Face validity is whether a test looks like it measures its target; it is not shown by correlations.' },
    ],
    rationale: 'Construct validity is supported by convergent evidence (strong relations with measures of the same construct) and discriminant evidence (weak relations with measures of different constructs). The multitrait-multimethod matrix examines both together.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Construct validity: convergent and discriminant evidence' }],
  },
  {
    id: 'nce-s-ass-011',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'easy',
    stem: 'A district reading test reports, for each fourth grader, whether the student has mastered at least 80% of the grade-level reading objectives, regardless of how classmates performed. What kind of test is this?',
    options: [
      { id: 'a', text: 'A norm-referenced test', isCorrect: false, rationale: 'Norm-referenced tests compare a score with a norm group, which this report does not do.' },
      { id: 'b', text: 'An ipsative measure', isCorrect: false, rationale: 'Ipsative measures compare traits within one person, not mastery of a standard.' },
      { id: 'c', text: 'A projective technique', isCorrect: false, rationale: 'Projective techniques use ambiguous stimuli to explore personality.' },
      { id: 'd', text: 'A criterion-referenced test', isCorrect: true, rationale: 'Comparing performance with a fixed standard of mastery is criterion-referenced.' },
    ],
    rationale: 'Criterion-referenced tests interpret a score against a set standard or body of content (what the person can do). Norm-referenced tests interpret a score against the performance of a comparison group (how the person ranks).',
    references: [{ source: 'Hays (Assessment)', detail: 'Norm-referenced vs criterion-referenced interpretation' }],
  },
  {
    id: 'nce-s-ass-012',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'medium',
    stem: 'Scores on a test are normally distributed. Approximately what percentage of test takers score between one standard deviation below the mean and two standard deviations above the mean?',
    options: [
      { id: 'a', text: 'About 82%', isCorrect: true, rationale: 'About 34% fall between -1 SD and the mean, and about 47.5% between the mean and +2 SD, for roughly 82%.' },
      { id: 'b', text: 'About 68%', isCorrect: false, rationale: '68% is the share within plus or minus one SD of the mean.' },
      { id: 'c', text: 'About 95%', isCorrect: false, rationale: '95% is the share within plus or minus two SD of the mean.' },
      { id: 'd', text: 'About 48%', isCorrect: false, rationale: 'About 47.5% lies between the mean and +2 SD alone; the band below the mean is left out.' },
    ],
    rationale: 'On the normal curve about 68% of scores fall within 1 SD of the mean, about 95% within 2 SD, and about 99.7% within 3 SD. Halving those figures gives the share on one side: about 34% from the mean to 1 SD and about 47.5% from the mean to 2 SD.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'The normal curve: 68-95-99.7 rule' }],
  },
  {
    id: 'nce-s-ass-013',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'hard',
    stem: 'A counselor compares four results from different normally distributed tests. Which result reflects the HIGHEST standing relative to its norm group?',
    options: [
      { id: 'a', text: 'A z score of +1.2', isCorrect: false, rationale: 'A z of +1.2 is below the T score of 65, which equals z = +1.5.' },
      { id: 'b', text: 'A deviation IQ of 118', isCorrect: false, rationale: 'With mean 100 and SD 15, an IQ of 118 equals z = +1.2.' },
      { id: 'c', text: 'A T score of 65', isCorrect: true, rationale: 'With mean 50 and SD 10, a T of 65 is 1.5 SD above the mean, the highest of the four.' },
      { id: 'd', text: 'A percentile rank of 88', isCorrect: false, rationale: 'The 88th percentile corresponds to a z of about +1.17.' },
    ],
    rationale: 'Converting each score to z allows comparison: z = (score - mean) / SD. T scores have a mean of 50 and SD of 10; deviation IQs have a mean of 100 and SD of 15; the 84th percentile is about z = +1.0 and the 88th about z = +1.17.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard scores: z, T and deviation IQ conversions' }],
  },
  {
    id: 'nce-s-ass-014',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'hard',
    stem: 'On a normally distributed test, one student\'s percentile rank rose from 50 to 60 and another student\'s rose from 89 to 99. Which statement about their raw-score gains is accurate?',
    options: [
      { id: 'a', text: 'Both students gained about the same number of raw-score points', isCorrect: false, rationale: 'Percentile ranks are not equal-interval units, so equal percentile gains do not mean equal raw gains.' },
      { id: 'b', text: 'The second student needed a much larger raw-score gain', isCorrect: true, rationale: 'Scores thin out in the upper tail, so moving from the 89th to 99th percentile takes far more raw-score distance.' },
      { id: 'c', text: 'The first student needed a much larger raw-score gain', isCorrect: false, rationale: 'Scores cluster near the mean, so a 10-rank gain there takes a small raw-score change.' },
      { id: 'd', text: 'The gains cannot be compared without first converting to stanines', isCorrect: false, rationale: 'Stanines are not needed; converting percentiles to z scores shows the difference directly.' },
    ],
    rationale: 'Percentile ranks are ordinal. Because most scores pile up near the mean, a small raw change in the middle moves the percentile a lot, while the same percentile change in the tail requires a large raw change. Here 50 to 60 is about 0.25 SD; 89 to 99 is about 1.1 SD.',
    references: [{ source: 'Hays (Assessment)', detail: 'Percentile ranks: ordinal scale and interpretation limits' }],
  },
  {
    id: 'nce-s-ass-015',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard error of measurement',
    difficulty: 'medium',
    stem: 'A client obtains a score of 92 on a test with a standard error of measurement (SEM) of 4. Which range is the approximate 95% confidence band for the client\'s true score?',
    options: [
      { id: 'a', text: '88 to 96', isCorrect: false, rationale: 'Plus or minus 1 SEM gives a band of about 68% confidence.' },
      { id: 'b', text: '90 to 94', isCorrect: false, rationale: 'Plus or minus half an SEM is far narrower than any standard band.' },
      { id: 'c', text: '80 to 104', isCorrect: false, rationale: 'Plus or minus 3 SEM gives about 99.7% confidence, wider than asked.' },
      { id: 'd', text: '84 to 100', isCorrect: true, rationale: 'Plus or minus about 2 SEM (1.96 x 4, roughly 8 points) gives the 95% band.' },
    ],
    rationale: 'The SEM is the standard deviation of a person\'s hypothetical scores around the true score. Bands of plus or minus 1 SEM, about 1.96 SEM (often rounded to 2), and 3 SEM around the obtained score give roughly 68%, 95%, and 99.7% confidence that the true score lies inside. Here 1.96 x 4 = 7.84, so the 95% band is about 84 to 100.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement and confidence intervals' }],
  },
  {
    id: 'nce-s-ass-016',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard error of measurement',
    difficulty: 'hard',
    stem: 'A test has a standard deviation of 15 and a reliability coefficient of .91. What is its standard error of measurement?',
    options: [
      { id: 'a', text: '4.5 points', isCorrect: true, rationale: 'SEM = 15 x the square root of (1 - .91) = 15 x 0.3 = 4.5.' },
      { id: 'b', text: '1.35 points', isCorrect: false, rationale: 'This multiplies the SD by .09 and omits the square root.' },
      { id: 'c', text: '13.65 points', isCorrect: false, rationale: 'This multiplies the SD by the reliability coefficient itself.' },
      { id: 'd', text: '0.3 points', isCorrect: false, rationale: 'This is only the square root of (1 - .91), not multiplied by the SD.' },
    ],
    rationale: 'SEM = SD x the square root of (1 - r). Higher reliability means a smaller SEM and narrower confidence bands; a perfectly reliable test would have an SEM of zero.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Standard error of measurement formula' }],
  },
  {
    id: 'nce-s-ass-017',
    reviewNote: 'Check the Wechsler age ranges used in the rationale (WPPSI-IV, WISC-V, WAIS-IV).',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intelligence and achievement tests',
    difficulty: 'easy',
    stem: 'A school-based counselor is part of a team evaluating the intellectual functioning of a 10-year-old. Which instrument is designed for this child\'s age?',
    options: [
      { id: 'a', text: 'WAIS-IV', isCorrect: false, rationale: 'The WAIS-IV is normed for adults and older adolescents (16 and up).' },
      { id: 'b', text: 'WPPSI-IV', isCorrect: false, rationale: 'The WPPSI-IV is for preschool and early primary children, below age 8.' },
      { id: 'c', text: 'WISC-V', isCorrect: true, rationale: 'The WISC-V covers ages 6 through 16, including a 10-year-old.' },
      { id: 'd', text: 'MMPI-A', isCorrect: false, rationale: 'The MMPI-A is an adolescent personality inventory, not an intelligence test.' },
    ],
    rationale: 'The Wechsler scales are split by age: WPPSI-IV for young children (about 2½ to 7½), WISC-V for ages 6 to 16, and WAIS-IV for ages 16 to 90. Each yields a Full Scale IQ with a mean of 100 and SD of 15.',
    references: [{ source: 'Hays (Assessment)', detail: 'Intelligence testing: Wechsler scales by age range' }],
  },
  {
    id: 'nce-s-ass-018',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'easy',
    stem: 'A counselor wants a personality inventory built on the five-factor model (neuroticism, extraversion, openness, agreeableness, and conscientiousness). Which instrument fits this purpose?',
    options: [
      { id: 'a', text: 'Rorschach Inkblot Test', isCorrect: false, rationale: 'The Rorschach is a projective technique, not a five-factor inventory.' },
      { id: 'b', text: 'NEO Personality Inventory-3', isCorrect: true, rationale: 'The NEO-PI-3 measures the five broad domains of the five-factor model and their facets.' },
      { id: 'c', text: 'Myers-Briggs Type Indicator', isCorrect: false, rationale: 'The MBTI sorts people into Jungian types rather than measuring the five factors.' },
      { id: 'd', text: 'MMPI-3', isCorrect: false, rationale: 'The MMPI-3 focuses on psychopathology and validity scales, not the five-factor model.' },
    ],
    rationale: 'The NEO-PI-3 (Costa and McCrae) assesses neuroticism, extraversion, openness, agreeableness, and conscientiousness, each with six facets. The MMPI family is used mainly to assess psychopathology and includes validity scales for over- and underreporting.',
    references: [{ source: 'Hays (Assessment)', detail: 'Personality inventories: NEO-PI-3 and the five-factor model' }],
  },
  {
    id: 'nce-s-ass-019',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'easy',
    stem: 'A counselor shows an adolescent a series of ambiguous drawings of people in everyday situations and asks him to tell a story about each one, with a beginning, middle, and end. Which instrument is being used?',
    options: [
      { id: 'a', text: 'Rorschach Inkblot Test', isCorrect: false, rationale: 'The Rorschach uses inkblots, not pictures of people, and asks what the person sees.' },
      { id: 'b', text: 'House-Tree-Person', isCorrect: false, rationale: 'In House-Tree-Person the client makes the drawings rather than responding to them.' },
      { id: 'c', text: 'Rotter Incomplete Sentences', isCorrect: false, rationale: 'The Rotter uses sentence stems for the client to finish, not pictures.' },
      { id: 'd', text: 'Thematic Apperception Test', isCorrect: true, rationale: 'The TAT presents ambiguous picture cards and asks for a story about each.' },
    ],
    rationale: 'The Thematic Apperception Test, developed by Morgan and Murray, is a projective technique in which stories told about ambiguous scenes are thought to reveal needs, motives, and conflicts. Projective tests rely on ambiguous stimuli and generally have weaker psychometric support than objective inventories.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective techniques: Thematic Apperception Test' }],
  },
  {
    id: 'nce-s-ass-020',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'medium',
    stem: 'On the PHQ-9, a client\'s total score is 6, in the mild range, but she marks "several days" on the last item, which asks about thoughts that she would be better off dead or of hurting herself. What should the counselor do next?',
    options: [
      { id: 'a', text: 'Follow up at once with a direct suicide risk assessment', isCorrect: true, rationale: 'Any endorsement of the self-harm item calls for direct risk assessment whatever the total score.' },
      { id: 'b', text: 'Note mild depression and recheck the PHQ-9 next month', isCorrect: false, rationale: 'Waiting ignores a positive response on the item that flags possible suicidal thinking.' },
      { id: 'c', text: 'Give the GAD-7 to see whether anxiety explains the item', isCorrect: false, rationale: 'An anxiety screen does not assess or rule out suicide risk.' },
      { id: 'd', text: 'Treat the item as invalid because the total score is low', isCorrect: false, rationale: 'A low total does not cancel a positive item 9; risk can exist with few other symptoms.' },
    ],
    rationale: 'The PHQ-9 has nine items scored 0 to 3 (total 0 to 27). Item 9 screens for passive or active thoughts of death or self-harm; any positive answer should be followed by a clinician\'s direct suicide risk assessment, since a screening total alone does not measure risk.',
    references: [{ source: 'Hays (Assessment)', detail: 'Screening instruments: Patient Health Questionnaire-9 (PHQ-9)' }],
  },
  {
    id: 'nce-s-ass-021',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'medium',
    stem: 'A 52-year-old client says that when he goes a day without drinking he gets shaky, sweaty, and cannot sleep. Using the ASAM Criteria (3rd edition), under which dimension should the counselor rate these symptoms?',
    options: [
      { id: 'a', text: 'Readiness to change', isCorrect: false, rationale: 'This dimension rates motivation and engagement, not physical withdrawal.' },
      { id: 'b', text: 'Recovery environment', isCorrect: false, rationale: 'This dimension rates the client\'s living situation and supports.' },
      { id: 'c', text: 'Intoxication and withdrawal', isCorrect: true, rationale: 'Tremor, sweating, and insomnia on stopping alcohol are withdrawal signs, rated in Dimension 1.' },
      { id: 'd', text: 'Relapse potential', isCorrect: false, rationale: 'This dimension rates risk of continued use, not current withdrawal.' },
    ],
    rationale: 'The ASAM Criteria rate six dimensions to match level of care. Dimension 1 covers intoxication and withdrawal; in the widely taught third edition the others address biomedical conditions, emotional/behavioral/cognitive conditions, readiness to change, relapse or continued-use potential, and the recovery environment. The 2023 fourth edition renamed and reorganized several later dimensions, but intoxication and withdrawal remains part of Dimension 1. Alcohol withdrawal can be dangerous and may call for medically managed care.',
    references: [{ source: 'ASAM Criteria', detail: '3rd edition, Dimension 1: acute intoxication and/or withdrawal potential' }],
  },
  {
    id: 'nce-s-ass-022',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'medium',
    stem: 'A counselor is asked to assess the cognitive abilities of a 13-year-old who arrived from Guatemala six months ago and is still learning English. Which approach is MOST appropriate?',
    options: [
      { id: 'a', text: 'Give a verbal English IQ test and report the score as usual', isCorrect: false, rationale: 'The score would mostly reflect English proficiency, so reporting it without caveats is invalid.' },
      { id: 'b', text: 'Use a nonverbal or native-language measure, interpreted with care', isCorrect: true, rationale: 'Reducing language load and noting norm limits gives a fairer, more valid picture of ability.' },
      { id: 'c', text: 'Delay all testing until he has lived in the country for five years', isCorrect: false, rationale: 'A rigid wait is arbitrary and may delay needed services; fairer methods exist now.' },
      { id: 'd', text: 'Add 15 points to his score to adjust for the language barrier', isCorrect: false, rationale: 'Arbitrary score adjustment has no psychometric basis and distorts results.' },
    ],
    rationale: 'Counselors select instruments whose norms and language suit the client and interpret results in light of culture, language, and acculturation. When a test was not normed on the client\'s population, the report should say so. Nonverbal measures or measures in the client\'s dominant language reduce bias from limited English.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.8 Multicultural Issues/Diversity in Assessment' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Culturally biased assessment and test interpretation' }],
  },
  {
    id: 'nce-s-ass-023',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'During a biopsychosocial intake, a 55-year-old client with no prior mental health history describes new anxiety, a racing heart, weight loss despite a good appetite, and feeling hot all the time. What is the counselor\'s BEST next step?',
    options: [
      { id: 'a', text: 'Diagnose generalized anxiety disorder and begin relaxation training', isCorrect: false, rationale: 'GAD requires that symptoms not be due to a medical condition, which has not been ruled out.' },
      { id: 'b', text: 'Explore childhood experiences that may underlie the new anxiety', isCorrect: false, rationale: 'This skips the possibility that a medical problem is driving the symptoms.' },
      { id: 'c', text: 'Reassure the client that midlife anxiety is common and expected', isCorrect: false, rationale: 'Reassurance without evaluation may miss a treatable physical cause.' },
      { id: 'd', text: 'Recommend a medical evaluation to rule out a physical cause', isCorrect: true, rationale: 'Late onset with weight loss and heat intolerance suggests a possible medical cause, such as thyroid disease.' },
    ],
    rationale: 'The biological part of a biopsychosocial history covers health, medications, and physical symptoms. New-onset anxiety in midlife with physical signs such as weight loss and heat intolerance can reflect conditions like hyperthyroidism, so a medical evaluation comes before a mental disorder diagnosis.',
    references: [{ source: 'DSM-5-TR', detail: 'Anxiety Disorder Due to Another Medical Condition; GAD Criterion E' }],
  },
  {
    id: 'nce-s-ass-024',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'medium',
    stem: 'A client being assessed for alcohol use says he "only has a couple of beers on weekends." With his written consent, the counselor also interviews his spouse. What is the PRIMARY value of this collateral information?',
    options: [
      { id: 'a', text: 'It can confirm or add to self-report that may be minimized', isCorrect: true, rationale: 'Collateral sources help check self-report, which can be limited by minimization or poor insight.' },
      { id: 'b', text: 'It removes the need for a structured diagnostic interview', isCorrect: false, rationale: 'Collateral data supplement, not replace, a thorough clinical interview.' },
      { id: 'c', text: 'It lets the spouse set the goals of the client\'s treatment', isCorrect: false, rationale: 'Treatment goals are set collaboratively with the client, who directs his own care.' },
      { id: 'd', text: 'It supplies the evidence that state law requires to diagnose', isCorrect: false, rationale: 'Diagnosis does not legally require collateral reports; they are clinically useful, not mandatory.' },
    ],
    rationale: 'Collateral information from family, prior records, or other providers broadens the assessment, especially when the client may underreport, lack insight, or have memory problems. It is gathered with the client\'s consent and weighed alongside the client\'s own account.',
    references: [{ source: 'Hays (Assessment)', detail: 'Collateral sources of assessment information' }],
  },
];
