// tools/nce/seed/intake-3.js — Intake, Assessment, and Diagnosis, batch 3 (original items)
module.exports = [
  {
    id: 'nce-s-ass-049',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'differential diagnosis',
    difficulty: 'medium',
    stem: 'An 8-year-old is referred for poor concentration, restlessness, and unfinished classwork. His teacher from last year describes him as attentive and settled. The problems began about five months ago, shortly after he witnessed a violent break-in at his home, and he now has nightmares and startles easily. Which finding MOST argues against ADHD as the primary explanation?',
    options: [
      { id: 'a', text: 'His restlessness is seen both at home and at school', isCorrect: false, rationale: 'Symptoms in two or more settings are required for ADHD, so this finding is consistent with ADHD rather than against it.' },
      { id: 'b', text: 'He is a boy referred in the early elementary years', isCorrect: false, rationale: 'Age and gender describe common referral patterns; they do not help separate ADHD from a trauma response.' },
      { id: 'c', text: 'The symptoms began suddenly after a traumatic event', isCorrect: true, rationale: 'An abrupt onset after trauma, with no earlier history and with intrusion and arousal symptoms, points toward a trauma-related disorder.' },
      { id: 'd', text: 'His classwork is left unfinished, not done poorly', isCorrect: false, rationale: 'Failing to finish schoolwork is itself a listed ADHD inattention symptom, so it does not argue against ADHD.' },
    ],
    rationale: 'ADHD is a neurodevelopmental disorder with a persistent pattern that typically shows up early and across settings. When attention problems and restlessness appear abruptly after a traumatic event in a child who was previously attentive, and they come with nightmares and an exaggerated startle response, a trauma- and stressor-related disorder better explains the picture. Hyperarousal and intrusive memories can look like inattention and hyperactivity, so onset timing and trauma history are key differentiators.',
    references: [{ source: 'DSM-5-TR', detail: 'Attention-deficit/hyperactivity disorder: Differential Diagnosis' }, { source: 'SAMHSA TIP 57', detail: 'Trauma-related symptoms that resemble other disorders' }],
  },
  {
    id: 'nce-s-ass-050',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'hard',
    stem: 'A 35-year-old client reports three weeks of depressed mood, loss of interest, guilt, and poor concentration. His partner says he has been "snappy and irritable" with everyone. He sleeps about four hours a night but wakes exhausted and drags through the day. He reports no past periods of elevated mood or unusual energy. Which diagnosis is BEST supported?',
    options: [
      { id: 'a', text: 'Major depressive disorder, single episode', isCorrect: true, rationale: 'He has at least five depressive symptoms for two weeks or more; irritability and insomnia with fatigue fit a depressive episode.' },
      { id: 'b', text: 'Bipolar II disorder, current episode depressed', isCorrect: false, rationale: 'Bipolar II requires at least one past hypomanic episode, and he reports no periods of elevated mood or increased energy.' },
      { id: 'c', text: 'Cyclothymic disorder with depressive features', isCorrect: false, rationale: 'Cyclothymic disorder requires at least two years of fluctuating subthreshold symptoms, not a three-week episode.' },
      { id: 'd', text: 'Disruptive mood dysregulation disorder', isCorrect: false, rationale: 'DMDD is diagnosed only in children and adolescents (first diagnosis between ages 6 and 18), with onset before age 10.' },
    ],
    rationale: 'Irritability is common in depression and does not by itself suggest bipolarity. Hypomania requires a distinct period of abnormally elevated, expansive, or irritable mood together with increased activity or energy. This client sleeps little but feels exhausted, which is insomnia, not the decreased need for sleep seen in hypomania. With no history of hypomanic episodes, the depressive episode is best diagnosed as major depressive disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Major depressive disorder: Differential Diagnosis; hypomanic episode Criteria A-B' }],
  },
  {
    id: 'nce-s-ass-051',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'medium',
    stem: 'A 42-year-old client in a severe depressive episode believes she is being punished for terrible sins and that her organs are rotting. Her family reports that these beliefs appeared only after the depression began, and she has never had psychotic symptoms while her mood was stable. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Schizophrenia, first episode, acute', isCorrect: false, rationale: 'Psychosis that occurs only during mood episodes points to a mood disorder; schizophrenia is excluded when mood episodes explain it.' },
      { id: 'b', text: 'Schizoaffective disorder, depressive type', isCorrect: false, rationale: 'Schizoaffective disorder requires delusions or hallucinations for two weeks or more without a major mood episode.' },
      { id: 'c', text: 'Delusional disorder, somatic type', isCorrect: false, rationale: 'Delusional disorder is not diagnosed when delusions occur only during major depressive or manic episodes.' },
      { id: 'd', text: 'MDD, severe, with psychotic features', isCorrect: true, rationale: 'Delusions confined to a major depressive episode are coded with the psychotic features specifier.' },
    ],
    rationale: 'The deciding question is when the psychotic symptoms occur. If delusions or hallucinations happen only during a major depressive episode, the diagnosis is major depressive disorder with psychotic features; here the content (guilt, punishment, bodily decay) is mood-congruent. Schizoaffective disorder requires a period of at least two weeks of psychosis without a major mood episode, and schizophrenia is ruled out when mood episodes account for the psychosis.',
    references: [{ source: 'DSM-5-TR', detail: 'Depressive disorders: with psychotic features specifier; schizoaffective disorder Criterion B' }],
  },
  {
    id: 'nce-s-ass-052',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'hard',
    stem: 'A 24-year-old is brought in after four days of paranoid beliefs and hearing voices. He reports using methamphetamine daily for the past month and stopping two days ago. He has no prior psychiatric history. Which approach to diagnosis is MOST appropriate?',
    options: [
      { id: 'a', text: 'Diagnose schizophrenia, as he has delusions and hallucinations', isCorrect: false, rationale: 'Schizophrenia requires continuous signs for six months and is excluded when a substance explains the symptoms.' },
      { id: 'b', text: 'Consider a substance-induced psychosis and see if it clears', isCorrect: true, rationale: 'Onset during heavy stimulant use suggests a substance-induced disorder; persistence well after stopping would point elsewhere.' },
      { id: 'c', text: 'Diagnose brief psychotic disorder, as it has lasted under a month', isCorrect: false, rationale: 'Brief psychotic disorder is not diagnosed when the disturbance is attributable to a substance.' },
      { id: 'd', text: 'Postpone any psychosis assessment until a 90-day program ends', isCorrect: false, rationale: 'Psychosis needs prompt assessment for safety and care; waiting months is not a diagnostic strategy.' },
    ],
    rationale: 'Stimulants such as methamphetamine can produce paranoia and hallucinations. DSM-5-TR asks whether the symptoms began during or soon after substance use and whether they persist for a substantial period (for example, about a month) after intoxication or withdrawal ends. Symptoms that clear with abstinence support a substance/medication-induced psychotic disorder; symptoms that persist, or a history of psychosis without use, suggest an independent psychotic disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Substance/medication-induced psychotic disorder: Criterion C and Differential Diagnosis' }],
  },
  {
    id: 'nce-s-ass-053',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'easy',
    stem: 'A counselor gives a client a form with stems such as "I regret..." and "My father..." and asks her to finish each one in her own words. Which type of instrument is this?',
    options: [
      { id: 'a', text: 'A sentence completion test such as the Rotter', isCorrect: true, rationale: 'Incomplete sentence stems that the client finishes freely define the sentence completion method, such as the Rotter Incomplete Sentences Blank.' },
      { id: 'b', text: 'An objective personality inventory like the MMPI-3', isCorrect: false, rationale: 'The MMPI-3 uses fixed true/false items scored against scales, not open-ended responses.' },
      { id: 'c', text: 'A word association technique in the style of Jung', isCorrect: false, rationale: 'Word association asks for the first word that comes to mind after a single stimulus word, not completing sentences.' },
      { id: 'd', text: 'A symptom checklist such as the SCL-90-R measure', isCorrect: false, rationale: 'The SCL-90-R asks clients to rate how much listed symptoms have bothered them, a structured self-report format.' },
    ],
    rationale: 'Sentence completion tests are often called semi-structured projective techniques: the stem gives some structure, but the client supplies the content, which may reveal attitudes, conflicts, and concerns. The Rotter Incomplete Sentences Blank is the best-known example. Like other projectives, responses are interpreted with caution and alongside other data.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective personality assessment: sentence completion techniques' }],
  },
  {
    id: 'nce-s-ass-054',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'medium',
    stem: 'As part of an evaluation for possible depression, a school counselor asks a 9-year-old to draw a house, a tree, and a person. Afterward, a colleague proposes diagnosing depression because the tree in the drawing has no leaves. Which response BEST reflects sound practice with this technique?',
    options: [
      { id: 'a', text: 'Accept the sign, as drawing tests are well validated for mood', isCorrect: false, rationale: 'Individual drawing signs have weak and inconsistent research support for diagnosing specific disorders.' },
      { id: 'b', text: 'Rescore the drawing with a longer and more detailed checklist', isCorrect: false, rationale: 'A longer checklist does not fix the underlying validity problem of reading diagnoses from single drawing features.' },
      { id: 'c', text: 'Treat the drawing as a hypothesis to check against other data', isCorrect: true, rationale: 'Projective drawings are best used for rapport and hypothesis generation, confirmed by interviews, ratings, and other measures.' },
      { id: 'd', text: 'Have the child draw again and diagnose if the sign is repeated', isCorrect: false, rationale: 'Repeating the task does not make the sign a valid indicator of depression; the diagnosis still lacks evidence.' },
    ],
    rationale: 'The House-Tree-Person technique, developed by Buck, asks the client to draw and then talk about the drawings. Interpreting single features (such as a bare tree) as signs of a disorder has limited reliability and validity support. Projectives are best used to build rapport and generate hypotheses that are then checked against interview data, behavior ratings, collateral reports, and standardized measures.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective drawings (House-Tree-Person): uses and psychometric limitations' }],
  },
  {
    id: 'nce-s-ass-055',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'medium',
    stem: 'Over the past year, a client\'s drinking has met these DSM-5-TR criteria: drinking more than intended, unsuccessful efforts to cut down, craving, continued use despite arguments with his spouse about it, and tolerance. He reports no withdrawal symptoms. Which severity specifier applies?',
    options: [
      { id: 'a', text: 'Mild, as no withdrawal symptoms are reported', isCorrect: false, rationale: 'Withdrawal is not required for any severity level; severity is set by how many criteria are met.' },
      { id: 'b', text: 'Moderate, based on the number of criteria met', isCorrect: true, rationale: 'Five criteria fall in the moderate range (4-5 criteria); mild is 2-3 and severe is 6 or more.' },
      { id: 'c', text: 'Severe, as tolerance shows physical dependence', isCorrect: false, rationale: 'Tolerance is one criterion among eleven; it does not by itself raise the severity level.' },
      { id: 'd', text: 'Unspecified, until withdrawal is also confirmed', isCorrect: false, rationale: 'An alcohol use disorder can be diagnosed and rated without withdrawal; at least two criteria in 12 months are needed.' },
    ],
    rationale: 'DSM-5-TR substance use disorders have 11 criteria; at least two within a 12-month period are needed for the diagnosis. Severity is rated by count: mild (2-3 symptoms), moderate (4-5), and severe (6 or more). Physiological features such as tolerance and withdrawal are not required, and neither one alone determines severity.',
    references: [{ source: 'DSM-5-TR', detail: 'Alcohol use disorder: Criteria A and severity specifiers' }],
  },
  {
    id: 'nce-s-ass-056',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'easy',
    stem: 'In an integrated primary care clinic, a 44-year-old patient screens positive on the AUDIT-C. What does this result BEST support as the next step?',
    options: [
      { id: 'a', text: 'Diagnosing alcohol use disorder, mild severity', isCorrect: false, rationale: 'A screening tool flags possible risk; it cannot establish whether DSM-5-TR criteria are met.' },
      { id: 'b', text: 'Referring the patient to inpatient detoxification', isCorrect: false, rationale: 'Level of care depends on a full assessment, such as of withdrawal risk, not on a positive screen alone.' },
      { id: 'c', text: 'Placing the patient in a relapse prevention group', isCorrect: false, rationale: 'Treatment placement before any diagnostic assessment skips the step that tells what care is needed.' },
      { id: 'd', text: 'Fuller assessment to see if a disorder exists', isCorrect: true, rationale: 'A positive screen calls for further evaluation, such as the full AUDIT and a diagnostic interview.' },
    ],
    rationale: 'The AUDIT-C is the three consumption items of the 10-item AUDIT. Like all screeners, it is built to identify people who may have a problem, trading some precision for speed. A positive result is followed by a fuller assessment (for example, the complete AUDIT, a clinical interview against DSM-5-TR criteria, and review of consequences) before diagnosis or placement.',
    references: [{ source: 'Hays (Assessment)', detail: 'Substance use screening (AUDIT, AUDIT-C) versus diagnostic assessment' }],
  },
  {
    id: 'nce-s-ass-057',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'easy',
    stem: 'A counselor in a high school health center wants a brief substance use screening tool that was developed and validated specifically for adolescents. Which instrument BEST fits this need?',
    options: [
      { id: 'a', text: 'CRAFFT', isCorrect: true, rationale: 'The CRAFFT was developed for adolescents and asks about situations such as riding in a car with an impaired driver.' },
      { id: 'b', text: 'CAGE questionnaire', isCorrect: false, rationale: 'The CAGE was developed for adults and focuses on lifetime alcohol problems, not adolescent use.' },
      { id: 'c', text: 'Michigan Alcoholism Screening Test', isCorrect: false, rationale: 'The MAST was developed with adults and screens for alcohol problems only.' },
      { id: 'd', text: 'Addiction Severity Index', isCorrect: false, rationale: 'The ASI is a longer adult interview measuring problem severity, not a brief adolescent screen.' },
    ],
    rationale: 'The CRAFFT is a brief screen for adolescent substance use risk. Its name comes from its key words: Car, Relax, Alone, Forget, Friends, Trouble. It covers alcohol and other drugs and fits settings such as schools and pediatric care. Like any screen, a positive result leads to further assessment rather than diagnosis.',
    references: [{ source: 'Hays (Assessment)', detail: 'Substance use screening with adolescents: CRAFFT' }],
  },
  {
    id: 'nce-s-ass-058',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'A parent brings a 6-year-old for an intake because of delayed speech and difficulty playing with peers. Which part of the biopsychosocial history is MOST important to gather in detail at this point?',
    options: [
      { id: 'a', text: 'The parent\'s own job history and career plans', isCorrect: false, rationale: 'Parent employment can matter for context, but it does not address the child\'s developmental concerns.' },
      { id: 'b', text: 'The child\'s scores on recent reading tests', isCorrect: false, rationale: 'At age 6, formal reading data are limited and do not explain early speech and social delays.' },
      { id: 'c', text: 'Developmental milestones and early health', isCorrect: true, rationale: 'Timing of speech, motor, and social milestones, plus prenatal and early medical history, is central to these concerns.' },
      { id: 'd', text: 'The family\'s faith practices and affiliation', isCorrect: false, rationale: 'Spiritual context can be relevant to a full history, but it is not the priority for speech and social delays.' },
    ],
    rationale: 'For young children, the developmental history is a core section of the biopsychosocial assessment. When to first words, phrases, walking, and social play emerged, and any prenatal, birth, hearing, or medical issues, help distinguish typical variation from conditions such as language disorder, hearing loss, or autism spectrum disorder, and guide referrals.',
    references: [{ source: 'Hays (Assessment)', detail: 'Clinical interview: developmental and biopsychosocial history' }, { source: 'Berk (Development Through the Lifespan)', detail: 'Language and social development in early childhood' }],
  },
  {
    id: 'nce-s-ass-059',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'During a biopsychosocial intake for her first episode of depression, a 22-year-old mentions that her mother was hospitalized for bipolar disorder. Why is this family history clinically important?',
    options: [
      { id: 'a', text: 'It confirms that the client has bipolar disorder herself', isCorrect: false, rationale: 'Family history raises risk but cannot establish a diagnosis; the client\'s own history must meet criteria.' },
      { id: 'b', text: 'It raises concern for bipolarity, so screening is key', isCorrect: true, rationale: 'A first-degree relative with bipolar disorder increases risk, so past hypomania and future mood shifts need careful screening.' },
      { id: 'c', text: 'It is not relevant once the client is an adult living alone', isCorrect: false, rationale: 'Family psychiatric history keeps its relevance to risk regardless of the client\'s age or living situation.' },
      { id: 'd', text: 'It shows that the client\'s depression is mostly learned', isCorrect: false, rationale: 'Family history reflects genetic and environmental influences; it does not show that symptoms were learned.' },
    ],
    rationale: 'Family psychiatric history is a standard part of the biopsychosocial assessment. Bipolar disorder is strongly heritable, so a depressed client with a first-degree relative who has bipolar disorder warrants careful questioning about past hypomanic or manic symptoms and monitoring over time. The information also matters for any referral for medication evaluation, because antidepressants alone may carry risk in bipolar disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Bipolar I disorder: Risk and Prognostic Factors (genetic and physiological)' }, { source: 'Hays (Assessment)', detail: 'Clinical interview: family history' }],
  },
  {
    id: 'nce-s-ass-060',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'Near the end of a biopsychosocial interview, a counselor asks a 58-year-old client about his friendships, his faith community, times he coped well in the past, and things he does well. What is the main purpose of gathering this information?',
    options: [
      { id: 'a', text: 'To estimate whether he qualifies for disability benefits', isCorrect: false, rationale: 'Benefit eligibility depends on functional limits and outside rules, not on a strengths inventory.' },
      { id: 'b', text: 'To screen him for grandiosity and inflated self-esteem', isCorrect: false, rationale: 'Asking about strengths is not a mania screen; grandiosity is assessed through mood history and the MSE.' },
      { id: 'c', text: 'To set the DSM-5-TR severity specifier for his diagnosis', isCorrect: false, rationale: 'Severity specifiers depend on symptom criteria, not on the client\'s supports or strengths.' },
      { id: 'd', text: 'To find resources that the treatment plan can build on', isCorrect: true, rationale: 'Strengths, supports, and past coping successes are resources that inform goals and interventions.' },
    ],
    rationale: 'A complete biopsychosocial history covers not only problems and risks but also strengths, social supports, spiritual resources, and past coping. These protective factors shape a realistic, collaborative treatment plan, can support safety planning, and convey to the client that the counselor sees the whole person rather than a list of deficits.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Biopsychosocial assessment: strengths and resources' }],
  },
  {
    id: 'nce-s-ass-061',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'intake interview structure',
    difficulty: 'easy',
    stem: 'When structuring an initial intake interview, which sequence is generally recommended for exploring the client\'s concerns?',
    options: [
      { id: 'a', text: 'Begin with closed questions on the most sensitive topics', isCorrect: false, rationale: 'Starting with sensitive, closed questions before rapport tends to limit disclosure and raise anxiety.' },
      { id: 'b', text: 'Ask about trauma history before the presenting problem', isCorrect: false, rationale: 'The client\'s reason for coming usually comes first; detailed trauma questions follow once rapport is built.' },
      { id: 'c', text: 'Start with open questions, then narrow to specifics', isCorrect: true, rationale: 'This funnel approach lets the client tell the story in their own words, then fills gaps with targeted questions.' },
      { id: 'd', text: 'Read a full symptom checklist before any open question', isCorrect: false, rationale: 'Leading with a checklist structures the interview around the form rather than the client\'s concerns.' },
    ],
    rationale: 'Most intake models use a funnel: after informed consent, the counselor invites the client to describe the presenting concern in their own words with open-ended questions, then narrows to specific questions about onset, duration, severity, and history. This builds rapport, captures the client\'s view of the problem, and still yields the detail needed for diagnosis and planning.',
    references: [{ source: 'Hays (Assessment)', detail: 'Clinical interviewing: structure and sequencing of the intake' }, { source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'The initial interview' }],
  },
  {
    id: 'nce-s-ass-062',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intake interview structure',
    difficulty: 'medium',
    stem: 'An agency is deciding between a fully structured diagnostic interview and an unstructured clinical interview for its intakes. Which statement accurately compares the two approaches?',
    options: [
      { id: 'a', text: 'Structured interviews yield higher interrater reliability', isCorrect: true, rationale: 'Fixed wording and order reduce variation between interviewers, which raises agreement on diagnoses.' },
      { id: 'b', text: 'Unstructured interviews are less open to clinician bias', isCorrect: false, rationale: 'Unstructured interviews depend more on clinician judgment, which makes them more open to bias.' },
      { id: 'c', text: 'Structured interviews let clinicians freely vary questions', isCorrect: false, rationale: 'Freedom to vary questions describes unstructured or semi-structured interviews, not fully structured ones.' },
      { id: 'd', text: 'Unstructured interviews are too unreliable to be of use', isCorrect: false, rationale: 'Unstructured interviews offer flexibility and rapport and remain widely used, despite lower reliability.' },
    ],
    rationale: 'Fully structured interviews ask set questions in a set order with set scoring, so different interviewers reach more similar conclusions (higher reliability). The tradeoff is less flexibility to follow the client\'s lead. Unstructured interviews offer flexibility and rapport but rely heavily on the clinician, which lowers reliability and leaves more room for bias. Semi-structured interviews fall between the two.',
    references: [{ source: 'Hays (Assessment)', detail: 'Clinical interviews: structured, semi-structured and unstructured formats' }],
  },
  {
    id: 'nce-s-ass-063',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'mental status examination',
    difficulty: 'easy',
    stem: 'During a mental status examination, a client correctly gives her name and says she is in a hospital, but she cannot state the month, the year, or the day of the week. How should orientation be recorded?',
    options: [
      { id: 'a', text: 'Fully oriented in all three spheres', isCorrect: false, rationale: 'She cannot give the date, so she is not oriented to time.' },
      { id: 'b', text: 'Oriented to person and place, not time', isCorrect: true, rationale: 'She knows who she is and where she is but not the date, so she is oriented to person and place only.' },
      { id: 'c', text: 'Oriented to time and place, not person', isCorrect: false, rationale: 'She correctly gave her own name, so orientation to person is intact.' },
      { id: 'd', text: 'Disoriented in all three spheres', isCorrect: false, rationale: 'She is oriented to both person and place, so she is not fully disoriented.' },
    ],
    rationale: 'Orientation in the MSE is usually checked for person, place, and time (sometimes also situation) and recorded as, for example, "oriented x2." Orientation to time is typically the first to be lost in delirium and dementia, while orientation to person is usually the last. Any disorientation warrants attention to possible medical or neurocognitive causes.',
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: sensorium and orientation' }],
  },
  {
    id: 'nce-s-ass-064',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'mental status examination',
    difficulty: 'medium',
    stem: 'A 39-year-old client says, "I know my drinking is out of control, and it\'s hurting my kids." Later in the session she mentions that she drove her children to school that morning after drinking. How are insight and judgment BEST described in the mental status examination?',
    options: [
      { id: 'a', text: 'Insight is poor, but judgment is good', isCorrect: false, rationale: 'She recognizes the problem and its effects, so insight is not poor; driving after drinking is not good judgment.' },
      { id: 'b', text: 'Insight and judgment are both intact', isCorrect: false, rationale: 'Driving her children after drinking shows impaired judgment, despite her awareness.' },
      { id: 'c', text: 'Insight is absent, and judgment is poor', isCorrect: false, rationale: 'She names the problem and its harm to her children, so insight is present, not absent.' },
      { id: 'd', text: 'Insight fair, but judgment impaired', isCorrect: true, rationale: 'She understands the problem (insight) but made a dangerous decision (judgment), so the two are rated differently.' },
    ],
    rationale: 'In the MSE, insight is the client\'s awareness that a problem exists and understanding of its causes and effects. Judgment is the ability to make sound decisions and anticipate consequences, best inferred from real recent behavior. The two can diverge: a client may describe a problem accurately yet still act in risky ways, as here.',
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: insight and judgment' }],
  },
  {
    id: 'nce-s-ass-065',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'hard',
    stem: 'A 36-year-old client reports a plan to overdose this weekend on medication she has been saving and says she intends to act on it. She adds that her two children "are the reason I\'m still here." How should the counselor weigh her children as a protective factor?',
    options: [
      { id: 'a', text: 'Note it, but treat risk as high and act on safety now', isCorrect: true, rationale: 'Protective factors matter, but a plan with intent and means signals high acute risk that needs immediate action.' },
      { id: 'b', text: 'View it as reducing her risk to low; plan to meet next week', isCorrect: false, rationale: 'A single protective factor does not offset a specific plan, stated intent, and access to means.' },
      { id: 'c', text: 'Have her sign a no-harm contract, then end the session', isCorrect: false, rationale: 'No-suicide contracts are not supported as protection and do not address the plan or her access to means.' },
      { id: 'd', text: 'Set it aside, since protective factors do not change risk', isCorrect: false, rationale: 'Protective factors are part of a sound formulation and can be used in safety planning; they are not ignored.' },
    ],
    rationale: 'Suicide risk formulation weighs risk factors, warning signs, and protective factors together, but protective factors do not cancel out acute warning signs. Ideation with a specific plan, stated intent, and available means indicates high acute risk and calls for immediate safety steps, such as restricting means, involving supports, and arranging a higher level of care as needed. Her reasons for living can be built into the safety plan.',
    references: [{ source: 'C-SSRS', detail: 'Suicidal ideation with specific plan and intent' }, { source: 'Stanley-Brown SPI', detail: 'Reasons for living and means restriction' }],
  },
  {
    id: 'nce-s-ass-066',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'easy',
    stem: 'A counselor is assessing an adult client\'s risk of harming others. Which factor is generally considered the strongest single predictor of future violent behavior?',
    options: [
      { id: 'a', text: 'Having any diagnosed mental disorder', isCorrect: false, rationale: 'Most people with mental disorders are not violent; diagnosis alone is a weak predictor.' },
      { id: 'b', text: 'A score below average on an IQ test', isCorrect: false, rationale: 'Intelligence test scores are not a strong or direct predictor of violence.' },
      { id: 'c', text: 'A history of past violent behavior', isCorrect: true, rationale: 'Past violence is the most consistently supported predictor of future violence.' },
      { id: 'd', text: 'Living alone, away from family members', isCorrect: false, rationale: 'Living alone is not an established predictor of violence toward others.' },
    ],
    rationale: 'In violence risk assessment, past behavior is the best predictor of future behavior: a history of violence, especially recent, frequent, or severe violence, carries the most weight. Other factors that raise risk include substance use, stated threats or intent, access to weapons, and certain active symptoms, such as command hallucinations or paranoid beliefs about a specific person.',
    references: [{ source: 'Hays (Assessment)', detail: 'Risk assessment: violence and harm to others' }],
  },
  {
    id: 'nce-s-ass-067',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'medium',
    stem: 'A 20-year-old has had delusions, hallucinations, and disorganized speech for two months. The symptoms continue, and it is not yet known whether he will recover within six months. Which diagnosis is MOST appropriate now?',
    options: [
      { id: 'a', text: 'Schizophrenia, first episode', isCorrect: false, rationale: 'Schizophrenia requires continuous signs of disturbance for at least six months.' },
      { id: 'b', text: 'Brief psychotic disorder', isCorrect: false, rationale: 'Brief psychotic disorder lasts at least one day but less than one month.' },
      { id: 'c', text: 'Schizoaffective disorder', isCorrect: false, rationale: 'No major mood episode is described, which schizoaffective disorder requires.' },
      { id: 'd', text: 'Schizophreniform disorder (provisional)', isCorrect: true, rationale: 'Symptoms of one to six months with recovery not yet known call for a provisional schizophreniform diagnosis.' },
    ],
    rationale: 'DSM-5-TR uses "provisional" when there is a strong presumption that full criteria will be met but not enough information is yet available. Schizophreniform disorder lasts at least one month but less than six. When the diagnosis must be made before recovery is known, it is labeled provisional; if symptoms reach six months, the diagnosis changes to schizophrenia.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizophreniform disorder: Diagnostic Criteria B; provisional diagnosis (Use of the Manual)' }],
  },
  {
    id: 'nce-s-ass-068',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'hard',
    stem: 'A counselor on a school evaluation team is documenting autism spectrum disorder for a 7-year-old using DSM-5-TR. How are the severity levels for this diagnosis assigned?',
    options: [
      { id: 'a', text: 'As a single overall level based on the child\'s IQ score', isCorrect: false, rationale: 'Intellectual impairment is recorded with its own specifier; it does not set autism severity.' },
      { id: 'b', text: 'Separately for social communication and restricted behavior', isCorrect: true, rationale: 'Each of the two core domains receives its own level, from requiring support to requiring very substantial support.' },
      { id: 'c', text: 'By the total count of criteria the child meets across domains', isCorrect: false, rationale: 'Autism severity reflects the support needed, not a criteria count as in substance use disorders.' },
      { id: 'd', text: 'By how early in life the symptoms were first noticed by parents', isCorrect: false, rationale: 'Age of recognition is part of the history, but it does not determine the severity level.' },
    ],
    rationale: 'For autism spectrum disorder, DSM-5-TR rates current severity separately for social communication and for restricted, repetitive behaviors, using Level 1 ("requiring support"), Level 2 ("requiring substantial support"), and Level 3 ("requiring very substantial support"). The levels can differ between domains and can change over time. Accompanying intellectual or language impairment is recorded with separate specifiers.',
    references: [{ source: 'DSM-5-TR', detail: 'Autism spectrum disorder: severity levels and specifiers' }],
  },
  {
    id: 'nce-s-ass-069',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intelligence and achievement tests',
    difficulty: 'easy',
    stem: 'A clinic wants a single individually administered intelligence test it can use with clients ranging from a 4-year-old to a 70-year-old. Which instrument covers this full age range?',
    options: [
      { id: 'a', text: 'Wechsler Intelligence Scale for Children-V', isCorrect: false, rationale: 'The WISC-V is normed for school-age children (about 6 to 16), not preschoolers or older adults.' },
      { id: 'b', text: 'Wechsler Preschool and Primary Scale-IV', isCorrect: false, rationale: 'The WPPSI-IV covers young children (about 2½ to 7), not adults.' },
      { id: 'c', text: 'Stanford-Binet Intelligence Scales (SB5)', isCorrect: true, rationale: 'The SB5 is normed from age 2 through 85 and older, covering both clients.' },
      { id: 'd', text: 'Wechsler Adult Intelligence Scale-IV', isCorrect: false, rationale: 'The WAIS-IV starts at age 16, so it cannot be used with a 4-year-old.' },
    ],
    rationale: 'The Stanford-Binet Intelligence Scales, Fifth Edition (SB5), spans roughly ages 2 to 85+ and measures five factors (fluid reasoning, knowledge, quantitative reasoning, visual-spatial processing, and working memory) in both verbal and nonverbal domains. The Wechsler scales instead use separate tests by age band: WPPSI for preschoolers, WISC for school-age children, and WAIS for older adolescents and adults.',
    references: [{ source: 'Hays (Assessment)', detail: 'Intelligence testing: Stanford-Binet Fifth Edition and the Wechsler scales' }],
    reviewNote: 'Age ranges stated approximately (SB5 2-85+, WISC-V 6-16, WPPSI-IV 2:6-7:7, WAIS-IV 16-90); a WAIS-5 has since been published with a similar adult range. SME to confirm editions.',
  },
  {
    id: 'nce-s-ass-070',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intelligence and achievement tests',
    difficulty: 'medium',
    stem: 'A 10-year-old\'s WISC-V Full Scale IQ is 112, while her reading standard score on the Woodcock-Johnson IV Tests of Achievement is 78. Both scales have a mean of 100 and a standard deviation of 15. What has this pattern traditionally been taken to suggest?',
    options: [
      { id: 'a', text: 'A possible specific learning disability in reading', isCorrect: true, rationale: 'A large gap between average-or-better ability and low achievement is the classic ability-achievement discrepancy.' },
      { id: 'b', text: 'Mild intellectual disability that affects reading', isCorrect: false, rationale: 'An IQ of 112 is above average, which rules out intellectual disability.' },
      { id: 'c', text: 'Invalid testing, as the two scores should match', isCorrect: false, rationale: 'Ability and achievement measure different things; a gap is meaningful, not proof of invalid testing.' },
      { id: 'd', text: 'Above-average reading skill for a child of her age', isCorrect: false, rationale: 'A standard score of 78 is about 1.5 SD below the mean, well below average.' },
    ],
    rationale: 'The ability-achievement discrepancy model compares an intelligence score (such as WISC-V FSIQ) with an achievement score (such as on the WIAT or Woodcock-Johnson). A gap of more than two standard deviations, as here (34 points), was long used to identify a specific learning disability. IDEA 2004 no longer requires schools to use a discrepancy and permits response-to-intervention approaches, and DSM-5-TR does not require a discrepancy.',
    references: [{ source: 'Hays (Assessment)', detail: 'Achievement testing: ability-achievement discrepancy and learning disabilities' }],
  },
  {
    id: 'nce-s-ass-071',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'medium',
    stem: 'A counselor wants to use an English-language anxiety inventory with Vietnamese-speaking clients and asks a bilingual staff member to translate it word for word. What is the MOST important limitation of this plan?',
    options: [
      { id: 'a', text: 'Any translated test loses its reliability completely', isCorrect: false, rationale: 'Translation does not erase reliability by definition; it must be re-examined in the new version.' },
      { id: 'b', text: 'Translation alone does not ensure equivalence or norms', isCorrect: true, rationale: 'Items may change meaning across languages, and English-speaking norms may not apply to the new group.' },
      { id: 'c', text: 'Clients must take it in English to compare to the norms', isCorrect: false, rationale: 'Testing in a client\'s weaker language threatens validity; it is not the solution.' },
      { id: 'd', text: 'Anxiety cannot be assessed across different cultures', isCorrect: false, rationale: 'Anxiety can be assessed cross-culturally with suitably adapted and validated measures.' },
    ],
    rationale: 'Culturally fair assessment requires more than literal translation. Adapted tests need linguistic, conceptual, and metric equivalence, usually established through processes such as back-translation and review by bilingual experts, followed by evidence of reliability and validity with the new population. Scores should also be interpreted against appropriate norms; ACA Code E.8 calls for caution when using instruments normed on other populations.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.8 Multicultural Issues/Diversity in Assessment' }, { source: 'Hays (Assessment)', detail: 'Culturally fair assessment: test translation and equivalence' }],
  },
  {
    id: 'nce-s-ass-072',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'hard',
    stem: 'A 30-year-old client of Puerto Rican heritage describes an episode at her father\'s funeral in which she screamed uncontrollably, trembled, felt heat rising in her chest, and briefly felt detached, then felt like herself again. Which approach BEST reflects culturally fair assessment?',
    options: [
      { id: 'a', text: 'Diagnose panic disorder based on the physical symptoms she reports', isCorrect: false, rationale: 'One episode tied to a stressful event does not meet panic disorder criteria, and cultural meaning is not explored.' },
      { id: 'b', text: 'Record it as a dissociative disorder due to the brief detachment', isCorrect: false, rationale: 'Brief detachment within a culturally recognized distress episode does not establish a dissociative disorder.' },
      { id: 'c', text: 'Note it as a psychotic episode given the loss of control described', isCorrect: false, rationale: 'Nothing in the episode suggests delusions or hallucinations; loss of control is not psychosis.' },
      { id: 'd', text: 'Explore it as a possible cultural idiom of distress before labeling', isCorrect: true, rationale: 'The pattern matches ataque de nervios, a cultural concept of distress, so its meaning should be explored first.' },
    ],
    rationale: 'DSM-5-TR describes ataque de nervios as a cultural concept of distress common among people of Latin American, and especially Caribbean, heritage. It often follows a stressful family event and can include uncontrollable shouting, crying, trembling, heat rising to the head or chest, and brief dissociation, with a quick return to usual functioning. Exploring the client\'s own explanation, for example with the Cultural Formulation Interview, guards against misdiagnosing culturally shaped distress.',
    references: [{ source: 'DSM-5-TR', detail: 'Culture and Psychiatric Diagnosis: cultural concepts of distress (ataque de nervios)' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Culturally appropriate assessment and diagnosis' }],
  },
];
