// tools/nce/seed/intake-4.js — Intake, Assessment, and Diagnosis, batch 4 (original items)
module.exports = [
  {
    id: 'nce-s-ass-073',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'easy',
    stem: 'A parent is reading her son\'s score report from a statewide mathematics test. Which statement on the report is a norm-referenced interpretation?',
    options: [
      { id: 'a', text: 'He answered 34 of the 40 test items correctly', isCorrect: false, rationale: 'A raw score of items correct makes no comparison with other test takers, so it is not norm-referenced.' },
      { id: 'b', text: 'He scored higher than 70% of same-grade students', isCorrect: true, rationale: 'Comparing his score with a norm group of same-grade students is the defining feature of a norm-referenced interpretation.' },
      { id: 'c', text: 'He met the state proficiency standard in math', isCorrect: false, rationale: 'Meeting a fixed proficiency standard compares him with a criterion, not with other students.' },
      { id: 'd', text: 'He mastered 9 of the 10 fraction objectives tested', isCorrect: false, rationale: 'Mastery of stated objectives is a criterion-referenced interpretation of what he can do.' },
    ],
    rationale: 'A norm-referenced interpretation describes a score by its position relative to a norm group, as with percentile ranks and standard scores. A criterion-referenced interpretation describes performance against a fixed standard or set of objectives, regardless of how others performed. The same test can support both kinds of statement, so the question is what the score is being compared with.',
    references: [{ source: 'Hays (Assessment)', detail: 'Norm-referenced and criterion-referenced score interpretation' }],
  },
  {
    id: 'nce-s-ass-074',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'hard',
    stem: 'A counselor educator is building a criterion-referenced mastery test for a crisis-intervention training module. After instruction, 96% of trainees answer one item correctly. The item covers an essential safety skill named in the module objectives. What should the developer do with this item?',
    options: [
      { id: 'a', text: 'Drop it, because an item this easy fails to spread scores apart', isCorrect: false, rationale: 'Spreading scores apart is a norm-referenced goal; a mastery test is not built to rank trainees.' },
      { id: 'b', text: 'Rewrite it so that about half of all the trainees will miss it', isCorrect: false, rationale: 'Targeting a difficulty near .50 maximizes variance for norm-referenced tests, not for mastery testing.' },
      { id: 'c', text: 'Replace it with an item that better separates the top trainees', isCorrect: false, rationale: 'Separating high from low scorers serves ranking; it would drop coverage of a required objective.' },
      { id: 'd', text: 'Keep it, since it measures a required objective most mastered', isCorrect: true, rationale: 'A criterion-referenced item is judged by its match to the objective; high success after instruction is the desired result.' },
    ],
    rationale: 'Norm-referenced tests favor items of moderate difficulty that discriminate among examinees, because their purpose is to rank people. Criterion-referenced tests sample the content domain defined by the objectives, so an item tied to an essential skill stays in the test even when nearly everyone passes it after good instruction. Low score variance is expected, and even welcome, on a mastery test.',
    references: [{ source: 'Hays (Assessment)', detail: 'Criterion-referenced test construction; item difficulty and discrimination' }],
  },
  {
    id: 'nce-s-ass-075',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'medium',
    stem: 'A counselor plans to use a nonverbal ability test whose manual reports norms that were gathered about 30 years ago. When comparing today\'s clients with that norm group, what is the MAIN interpretive concern?',
    options: [
      { id: 'a', text: 'Scores may run high, since average performance has risen over time', isCorrect: true, rationale: 'Population gains in ability-test performance mean old norms set a lower bar, inflating current standard scores.' },
      { id: 'b', text: 'Old norms pose no problem when internal consistency is still high', isCorrect: false, rationale: 'Reliability says nothing about whether the norm group still represents the people being tested.' },
      { id: 'c', text: 'Scores may run low, since older norm groups were more test-savvy', isCorrect: false, rationale: 'This reverses the documented direction; outdated ability norms tend to overstate current standing.' },
      { id: 'd', text: 'Outdated norms alter raw scores but leave percentile ranks intact', isCorrect: false, rationale: 'Percentile ranks are computed from the norm group, so they are exactly what outdated norms distort.' },
    ],
    rationale: 'A norm-referenced score is only as meaningful as the norm group behind it. On ability tests, average performance in many populations rose over the 20th century (the Flynn effect), so clients compared with an old norm group tend to receive inflated standard scores and percentiles. Counselors should check the age, size, and makeup of the norm sample and prefer recently normed editions.',
    references: [{ source: 'Hays (Assessment)', detail: 'Evaluating norm groups: recency, representativeness, and size' }],
    reviewNote: 'Flynn effect framing: gains have slowed or reversed in some countries in recent decades. SME to confirm the "may run high" wording is appropriately hedged.',
  },
  {
    id: 'nce-s-ass-076',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard error of measurement',
    difficulty: 'hard',
    stem: 'A college counseling center uses a regression equation to predict first-year GPA from an admissions test score. A counselor wants a statistic that shows how far students\' actual GPAs typically fall from their predicted GPAs. Which statistic should she use?',
    options: [
      { id: 'a', text: 'The standard error of measurement of the admissions test', isCorrect: false, rationale: 'The SEM describes how obtained test scores vary around a person\'s true score, not prediction error for a criterion.' },
      { id: 'b', text: 'The standard error of the mean for the sample of GPAs', isCorrect: false, rationale: 'The standard error of the mean describes how precisely a sample mean estimates a population mean.' },
      { id: 'c', text: 'The standard error of estimate for the regression line', isCorrect: true, rationale: 'The standard error of estimate is the typical spread of actual criterion scores around predicted scores.' },
      { id: 'd', text: 'The standard deviation of the admissions test scores', isCorrect: false, rationale: 'This describes how spread out the predictor scores are, not how accurate the GPA predictions are.' },
    ],
    rationale: 'Three standard errors are easy to confuse. The standard error of measurement concerns a single test and the error around an individual\'s true score; the standard error of estimate concerns prediction and the error around a predicted criterion score; the standard error of the mean concerns sampling and the error in a sample mean as an estimate of the population mean. Predicting GPA from a test calls for the standard error of estimate.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement vs standard error of estimate' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Standard error of the mean; regression and prediction error' }],
  },
  {
    id: 'nce-s-ass-077',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard error of measurement',
    difficulty: 'medium',
    stem: 'Two anxiety scales use the same score metric and have the same standard deviation. Scale X has a reliability coefficient of .95, and Scale Y has one of .70. Why will Scale X have the smaller standard error of measurement?',
    options: [
      { id: 'a', text: 'Higher reliability increases the spread of the obtained scale scores', isCorrect: false, rationale: 'The two scales have the same standard deviation; reliability does not enlarge score spread.' },
      { id: 'b', text: 'Less of its score variance is error, so scores sit nearer true scores', isCorrect: true, rationale: 'SEM = SD times the square root of (1 - r); as r rises, the error portion and the SEM both shrink.' },
      { id: 'c', text: 'Reliable scales have more items, and the SEM is divided by item count', isCorrect: false, rationale: 'The SEM formula uses the SD and reliability coefficient; there is no division by the number of items.' },
      { id: 'd', text: 'Higher reliability means a stronger correlation with a criterion', isCorrect: false, rationale: 'Correlation with a criterion is validity evidence, and it is not what determines the SEM.' },
    ],
    rationale: 'The standard error of measurement is computed as SD multiplied by the square root of (1 minus the reliability coefficient). Reliability is the share of observed-score variance that is true-score variance, so the remainder is error. With equal standard deviations, the scale with .95 reliability leaves only 5% error variance versus 30%, giving a smaller SEM and narrower confidence bands around an individual\'s score.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement and its relation to reliability' }],
  },
  {
    id: 'nce-s-ass-078',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard error of measurement',
    difficulty: 'hard',
    stem: 'On a test battery where each subtest has a standard error of measurement of 4, a 12-year-old earns 103 on Verbal Reasoning and 109 on Spatial Reasoning. His parent asks whether spatial reasoning is a real strength. Using bands of plus or minus 1 SEM, what should the counselor say?',
    options: [
      { id: 'a', text: 'The bands overlap, so the gap may reflect measurement error', isCorrect: true, rationale: 'The bands run 99-107 and 105-113; overlap means the true scores may not differ.' },
      { id: 'b', text: 'The 6-point gap exceeds one SEM, so it is a genuine strength', isCorrect: false, rationale: 'Both scores carry error, so a gap slightly larger than one SEM is not enough to call the difference real.' },
      { id: 'c', text: 'The gap can be judged only after converting both to percentiles', isCorrect: false, rationale: 'Changing the score metric does not remove measurement error from either score.' },
      { id: 'd', text: 'Error bands apply to composite scores, not to subtest scores', isCorrect: false, rationale: 'Every score, including a subtest score, has measurement error and can be reported with a band.' },
    ],
    rationale: 'Reporting scores as bands rather than points reminds everyone that each obtained score contains error. A common rule of thumb is that when two scores\' bands overlap, the difference should not be treated as meaningful; when they do not overlap, a real difference is more likely. A more precise approach uses the standard error of the difference, which is larger than either SEM because both scores contribute error.',
    references: [{ source: 'Hays (Assessment)', detail: 'Confidence bands; comparing two scores with the standard error of measurement' }],
  },
  {
    id: 'nce-s-ass-079',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'medium',
    stem: 'A 27-year-old graduate student completes the NEO-PI-3 as part of career counseling. Her Extraversion score is very low, and her Neuroticism score is average. She asks whether this means something is wrong with her. What is the BEST interpretation to offer?',
    options: [
      { id: 'a', text: 'It suggests social anxiety that should be assessed further', isCorrect: false, rationale: 'Low Extraversion is not a measure of anxiety, and her Neuroticism score, which taps distress, is average.' },
      { id: 'b', text: 'It shows emotional instability and a tendency toward distress', isCorrect: false, rationale: 'Emotional instability and proneness to distress describe high Neuroticism, not low Extraversion.' },
      { id: 'c', text: 'It points to difficulty cooperating with and trusting others', isCorrect: false, rationale: 'Trust and cooperativeness belong to the Agreeableness domain, not Extraversion.' },
      { id: 'd', text: 'It reflects a reserved style and a liking for quieter settings', isCorrect: true, rationale: 'Low Extraversion describes a reserved, independent person who prefers less stimulation; it is a normal trait.' },
    ],
    rationale: 'The NEO-PI-3 measures normal-range personality on the five-factor model. Low Extraversion (introversion) means a person tends to be reserved, prefers smaller groups or solitude, and seeks less stimulation; it does not mean unhappiness or anxiety. Distress proneness is captured by Neuroticism. Interpreting traits as normal variation, and relating them to the client\'s goals, is the appropriate use of the profile.',
    references: [{ source: 'Hays (Assessment)', detail: 'NEO Personality Inventory-3: five-factor domains and interpretation' }],
  },
  {
    id: 'nce-s-ass-080',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'medium',
    stem: 'A 34-year-old client took the Myers-Briggs Type Indicator (MBTI) at work two years ago and was typed ENFP. Taking it again in counseling, she is typed INFP. Her Extraversion-Introversion preference score was close to the midpoint both times. What BEST explains the change?',
    options: [
      { id: 'a', text: 'Her basic personality has shifted a great deal over the past two years', isCorrect: false, rationale: 'A small move across the midpoint does not show major personality change.' },
      { id: 'b', text: 'The second result is invalid, so the first type is her true type', isCorrect: false, rationale: 'Nothing suggests an invalid administration; neither type is more "true" when the preference is unclear.' },
      { id: 'c', text: 'Splitting a continuous score into two types can flip near the middle', isCorrect: true, rationale: 'The MBTI sorts scores into either/or categories, so small shifts near the cut point change the reported type.' },
      { id: 'd', text: 'A change in type like this shows that she is in a period of crisis', isCorrect: false, rationale: 'The MBTI is not a measure of distress, and a type change near the midpoint has no clinical meaning.' },
    ],
    rationale: 'The MBTI reports four dichotomous preferences that combine into 16 types, but the underlying preference scores are continuous. People whose scores fall near the dividing point can be assigned a different type on retest, which is a well-known limit of type measures. The MBTI is used for self-understanding and career exploration; it is not designed for diagnosis or for selection decisions.',
    references: [{ source: 'Hays (Assessment)', detail: 'Myers-Briggs Type Indicator: type scoring and limitations' }, { source: 'Sharf (Career Development Theory)', detail: 'Use of the MBTI in career counseling' }],
  },
  {
    id: 'nce-s-ass-081',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'easy',
    stem: 'A counselor uses the Sixteen Personality Factor Questionnaire (16PF) in premarital counseling. Which description of this instrument is accurate?',
    options: [
      { id: 'a', text: 'A normal-range personality measure built through factor analysis', isCorrect: true, rationale: 'Raymond Cattell derived the 16PF\'s primary factors through factor analysis of trait descriptors.' },
      { id: 'b', text: 'An inventory empirically keyed to identify psychiatric patient groups', isCorrect: false, rationale: 'Empirical keying against clinical groups describes the MMPI tradition, not the 16PF.' },
      { id: 'c', text: 'A projective task in which clients describe ambiguous inkblots', isCorrect: false, rationale: 'Describing inkblots is the Rorschach, a projective test; the 16PF is a self-report questionnaire.' },
      { id: 'd', text: 'A type indicator that sorts people into Jungian categories', isCorrect: false, rationale: 'Sorting people into Jungian types describes the MBTI, not the 16PF\'s trait dimensions.' },
    ],
    rationale: 'The 16PF, developed by Raymond Cattell, is an objective self-report inventory of normal adult personality. Its 16 primary factors were identified through factor analysis and are summarized in broader global factors that resemble the Big Five. Because it describes normal traits rather than psychopathology, it is often used in career, couples, and personal growth counseling.',
    references: [{ source: 'Hays (Assessment)', detail: 'Sixteen Personality Factor Questionnaire (16PF): primary and global factors' }],
  },
  {
    id: 'nce-s-ass-082',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'easy',
    stem: 'During intake, a 45-year-old client mentions that she saw a counselor at another agency for depression three years ago. The counselor would like to review those records. What is the BEST way to obtain them?',
    options: [
      { id: 'a', text: 'Phone the former counselor and ask for a verbal case summary', isCorrect: false, rationale: 'An informal call without the client\'s knowledge or authorization bypasses her control over her information.' },
      { id: 'b', text: 'Have her sign a release naming the agency and records sought', isCorrect: true, rationale: 'A written, informed release specifying the source and the information requested respects her rights.' },
      { id: 'c', text: 'Ask her to describe that treatment and skip the records entirely', isCorrect: false, rationale: 'Her recollection is useful, but prior records add diagnoses, dates, and responses she may not recall.' },
      { id: 'd', text: 'Request the full file, including all notes, as routine practice', isCorrect: false, rationale: 'Requesting everything by default ignores the client\'s consent and the principle of seeking only what is needed.' },
    ],
    rationale: 'Prior treatment records can clarify past diagnoses, treatments tried, and response to care. The counselor should explain why the records would help and obtain the client\'s written authorization that names the releasing agency, the recipient, the information sought, and its purpose. Limiting the request to what is relevant respects privacy, and some material, such as psychotherapy notes, carries extra protection.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.6.g Disclosure or Transfer' }, { source: 'HIPAA', detail: '45 CFR 164.508 Uses and disclosures requiring an authorization' }],
    reviewNote: 'HIPAA permits provider-to-provider disclosure for treatment without authorization (psychotherapy notes and Part 2 records excepted); the key is framed as best practice. SME to confirm the HIPAA citation fits.',
  },
  {
    id: 'nce-s-ass-083',
    domain: 'intake',
    cacrep: 'professional_orientation',
    topic: 'collateral information and records',
    difficulty: 'medium',
    stem: 'A client on probation asks her counselor to send attendance and progress information to her probation officer. The release she signs and dates names the counselor, the probation officer, the information to be sent, the purpose, and the required notices on revocation and redisclosure. Under HIPAA, which required element is still missing?',
    options: [
      { id: 'a', text: 'A notary\'s seal that verifies the client\'s signature', isCorrect: false, rationale: 'HIPAA does not require notarization for an authorization to be valid.' },
      { id: 'b', text: 'The diagnosis that supports her referral to treatment', isCorrect: false, rationale: 'A diagnosis is not a required element; the form must describe the information, not justify the treatment.' },
      { id: 'c', text: 'A second signature from a witness at the counseling agency', isCorrect: false, rationale: 'A witness signature is not one of the required core elements of a valid authorization.' },
      { id: 'd', text: 'An expiration date or event that ends the authorization', isCorrect: true, rationale: 'A valid authorization must state when it expires, either as a date or as a defined event.' },
    ],
    rationale: 'Under the HIPAA Privacy Rule, a valid authorization includes a specific description of the information, who may disclose it, who may receive it, the purpose, an expiration date or event, the client\'s signature and date, and statements about the right to revoke and the potential for redisclosure. A release missing its expiration is defective, so the counselor should have the client complete it before sending anything.',
    references: [{ source: 'HIPAA', detail: '45 CFR 164.508(c) Core elements and required statements of a valid authorization' }],
  },
  {
    id: 'nce-s-ass-084',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'hard',
    stem: 'A counselor is assessing a 74-year-old widower for possible cognitive decline. He says he manages fine. His daughter, who visits three times a week, describes missed medications and getting lost while driving. His son, who lives overseas and speaks with him by phone monthly, says he "sounds like his old self." How should the counselor weigh these reports?',
    options: [
      { id: 'a', text: 'Average the two accounts, since each child knows him well', isCorrect: false, rationale: 'Averaging ignores how differently placed the two informants are to observe his daily functioning.' },
      { id: 'b', text: 'Defer to his own report, since he is a competent adult client', isCorrect: false, rationale: 'People with cognitive decline often lack awareness of their deficits, so self-report alone is unreliable here.' },
      { id: 'c', text: 'Weigh the daughter\'s direct observations and seek testing', isCorrect: true, rationale: 'Her frequent, specific, firsthand observations carry more weight, and objective testing can corroborate them.' },
      { id: 'd', text: 'Discount the daughter\'s report, as caregiver strain biases it', isCorrect: false, rationale: 'Possible bias is worth noting, but it does not erase concrete, firsthand observations of safety problems.' },
    ],
    rationale: 'When collateral reports conflict, counselors weigh each informant\'s opportunity to observe, how recent and specific the observations are, and any reasons for bias. Brief phone calls can mask deficits that show up in daily tasks such as managing medications or driving. Rather than picking a side, the counselor uses the conflict to guide further assessment, such as cognitive screening and a medical evaluation.',
    references: [{ source: 'Hays (Assessment)', detail: 'Collateral sources: evaluating informant reports' }, { source: 'DSM-5-TR', detail: 'Major and mild neurocognitive disorders: Criterion A (concern of the individual, a knowledgeable informant, or the clinician)' }],
  },
  {
    id: 'nce-s-ass-085',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'hard',
    stem: 'A counselor reviewing a psychological report notes that the Rorschach was formally scored, while the Thematic Apperception Test (TAT) was interpreted. Which statement BEST compares how these two projective tests are typically scored?',
    options: [
      { id: 'a', text: 'The Rorschach has normed coding systems such as Exner\'s and R-PAS; TAT stories are usually read clinically', isCorrect: true, rationale: 'The Rorschach is commonly coded with normed systems, while the TAT is most often interpreted without a single standard system.' },
      { id: 'b', text: 'The TAT is coded with Exner\'s Comprehensive System; the Rorschach is read only through clinical intuition', isCorrect: false, rationale: 'This reverses the tests: Exner\'s Comprehensive System was developed for the Rorschach, not the TAT.' },
      { id: 'c', text: 'Both are scored by computer against national norms, so examiner training matters relatively little', isCorrect: false, rationale: 'Projective tests require extensive examiner training, and the TAT lacks a single computerized normed scoring.' },
      { id: 'd', text: 'Neither test has any formal scoring system, so both rest entirely on the examiner\'s personal judgment', isCorrect: false, rationale: 'The Rorschach has detailed, research-based coding systems, so it does not rest on judgment alone.' },
    ],
    rationale: 'Exner\'s Comprehensive System brought standardized administration, coding, and norms to the Rorschach, and the Rorschach Performance Assessment System (R-PAS) later built on that work. The TAT has several research scoring approaches, but in practice it is usually interpreted qualitatively by examining themes, needs, and relationships in the stories. This difference affects how much weight each result can bear in an assessment.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective personality assessment: Rorschach scoring systems and the TAT' }],
    reviewNote: 'Formal TAT scoring systems exist (e.g., SCORS, need-achievement coding) but are not uniformly used; SME to confirm the "usually read clinically" framing.',
  },
  {
    id: 'nce-s-ass-086',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'test selection and administration',
    difficulty: 'easy',
    stem: 'A middle school principal asks the school counselor to "give some tests" to a seventh grader who is "having problems." What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Give a broad battery so that no possible problem is overlooked', isCorrect: false, rationale: 'Testing without a focus wastes time, burdens the student, and may produce results no one can use.' },
      { id: 'b', text: 'Choose the instruments the school already owns and knows well', isCorrect: false, rationale: 'Convenience should not drive test choice; the instrument must fit the question being asked.' },
      { id: 'c', text: 'Clarify the specific question the assessment needs to answer', isCorrect: true, rationale: 'A clear referral question determines what to assess and which instruments are appropriate.' },
      { id: 'd', text: 'Begin with a personality inventory to screen for any disorder', isCorrect: false, rationale: 'Picking an instrument before knowing the concern puts the tool ahead of the purpose.' },
    ],
    rationale: 'Assessment begins by defining its purpose. A vague request such as "having problems" must be turned into a specific referral question, for example about attention, mood, learning, or behavior, before any instrument is chosen. The question then guides test selection, the information sources needed (including parent consent and input), and how results will be used.',
    references: [{ source: 'Hays (Assessment)', detail: 'The assessment process: clarifying the referral question; selecting instruments' }],
  },
  {
    id: 'nce-s-ass-087',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'test selection and administration',
    difficulty: 'medium',
    stem: 'A vocational rehabilitation agency asks a counselor whether a 30-year-old client meets criteria for intellectual developmental disorder. Which assessment plan BEST answers this referral question?',
    options: [
      { id: 'a', text: 'An individual intelligence test alone, since IQ defines the disorder', isCorrect: false, rationale: 'DSM-5-TR requires deficits in adaptive functioning as well; an IQ score alone cannot establish the diagnosis.' },
      { id: 'b', text: 'An individual intelligence test plus a standardized adaptive measure', isCorrect: true, rationale: 'The diagnosis requires both intellectual and adaptive deficits, so both must be measured directly.' },
      { id: 'c', text: 'A group achievement test plus a brief cognitive screening instrument', isCorrect: false, rationale: 'Group achievement tests and brief screens are not adequate for a diagnostic decision about intellect.' },
      { id: 'd', text: 'A personality inventory plus an interest inventory for job matching', isCorrect: false, rationale: 'These may help with vocational planning, but they do not address intellectual or adaptive functioning.' },
    ],
    rationale: 'Intellectual developmental disorder requires deficits in intellectual functions, confirmed by clinical assessment and individualized standardized testing, together with deficits in adaptive functioning, with onset during the developmental period. Severity levels are defined by adaptive functioning. A sound plan therefore pairs an individually administered intelligence test with a standardized adaptive behavior measure and a developmental history.',
    references: [{ source: 'DSM-5-TR', detail: 'Intellectual developmental disorder: Criteria A-C and severity levels' }, { source: 'Hays (Assessment)', detail: 'Selecting instruments to fit the referral question' }],
  },
  {
    id: 'nce-s-ass-088',
    domain: 'intake',
    cacrep: 'research',
    topic: 'reliability types',
    difficulty: 'medium',
    stem: 'A test manual reports a reliability coefficient of .80 for a self-esteem scale. Which interpretation of this value is correct?',
    options: [
      { id: 'a', text: 'About 64% of the variance is true variance, found by squaring .80', isCorrect: false, rationale: 'Squaring applies to a correlation between two different measures; a reliability coefficient is read directly.' },
      { id: 'b', text: 'About 80% of the people who take the scale receive accurate scores', isCorrect: false, rationale: 'Reliability describes score variance in a group, not the share of individuals scored accurately.' },
      { id: 'c', text: 'The scale correlates .80 with an outside self-esteem criterion', isCorrect: false, rationale: 'A correlation with an outside criterion is a validity coefficient, not a reliability coefficient.' },
      { id: 'd', text: 'About 80% of observed score variance reflects true-score differences', isCorrect: true, rationale: 'A reliability coefficient estimates the proportion of observed-score variance that is true-score variance.' },
    ],
    rationale: 'In classical test theory, a reliability coefficient is interpreted directly as the proportion of observed-score variance attributable to true-score differences. A coefficient of .80 means about 80% true variance and 20% error variance. Unlike a validity coefficient, it is not squared, because it already represents a ratio of variances.',
    references: [{ source: 'Hays (Assessment)', detail: 'Interpreting reliability coefficients: true and error variance' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Classical test theory and reliability' }],
  },
  {
    id: 'nce-s-ass-089',
    domain: 'intake',
    cacrep: 'research',
    topic: 'validity types',
    difficulty: 'hard',
    stem: 'An aptitude test correlates .35 with supervisors\' later job performance ratings. A colleague tells the counselor the test is worthless because this figure is so far below the test\'s .90 reliability. Which response is MOST accurate?',
    options: [
      { id: 'a', text: 'Modest validity coefficients are common and can still aid prediction', isCorrect: true, rationale: 'Validity coefficients are typically much lower than reliability coefficients and can still improve decisions.' },
      { id: 'b', text: 'The test explains about 35% of the variance in job performance', isCorrect: false, rationale: 'Shared variance is the coefficient squared, so .35 explains roughly 12% of criterion variance.' },
      { id: 'c', text: 'A validity coefficient must equal the reliability to be of any use', isCorrect: false, rationale: 'Reliability sets an upper limit on validity; validity is not expected to reach it.' },
      { id: 'd', text: 'The coefficient shows that the true reliability of the test is .35', isCorrect: false, rationale: 'A test-criterion correlation is validity evidence; it does not re-estimate reliability.' },
    ],
    rationale: 'A validity coefficient is the correlation between test scores and a criterion. Because criteria such as supervisor ratings are themselves imperfect and many factors affect performance, validity coefficients are usually far lower than reliability coefficients. Squaring .35 gives about .12, so the test accounts for roughly 12% of criterion variance, which can still add useful information when combined with other data.',
    references: [{ source: 'Hays (Assessment)', detail: 'Validity coefficients: interpretation and typical size' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Coefficient of determination (r squared)' }],
  },
  {
    id: 'nce-s-ass-090',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'hard',
    stem: 'Two cultural groups differ in average scores on a clerical aptitude test. Research shows the test predicts later job performance equally well for both groups, using the same regression line. A hiring manager concludes that the test is biased. What is the BEST response?',
    options: [
      { id: 'a', text: 'Any gap in group means is itself proof that a test is biased', isCorrect: false, rationale: 'Group mean differences can reflect real differences in opportunity or preparation, not only test bias.' },
      { id: 'b', text: 'A mean gap alone does not show bias; equal prediction argues against it', isCorrect: true, rationale: 'Bias is a technical question; equal prediction across groups is evidence against predictive bias.' },
      { id: 'c', text: 'Equal prediction proves the test is fair in every possible use and setting', isCorrect: false, rationale: 'Fairness is broader than bias and includes access, consequences, and how scores are used.' },
      { id: 'd', text: 'Bias can be judged only by a panel reviewing items for offense', isCorrect: false, rationale: 'Content review helps, but statistical evidence such as differential prediction is central to judging bias.' },
    ],
    rationale: 'Test bias is a psychometric property: systematic error that makes a test measure or predict differently for different groups, studied through item functioning and differential prediction. Test fairness is a broader judgment about equitable treatment, access, and the consequences of test use. A mean difference alone does not establish bias, yet a technically unbiased test can still be used unfairly, so both questions deserve attention.',
    references: [{ source: 'Hays (Assessment)', detail: 'Test bias and test fairness; differential prediction' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Cultural bias in assessment' }],
  },
  {
    id: 'nce-s-ass-091',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'test selection and administration',
    difficulty: 'medium',
    stem: 'A client with low vision takes a timed, standardized reading-comprehension test in large print with extended time as an accommodation for her disability. How should the counselor handle the results?',
    options: [
      { id: 'a', text: 'Score it with the usual norms and make no note of the changes', isCorrect: false, rationale: 'Leaving out the accommodations would hide a departure from standard conditions that affects interpretation.' },
      { id: 'b', text: 'Discard the results, since accommodated scores are unusable', isCorrect: false, rationale: 'Accommodated results can still be informative; the code calls for noting conditions, not discarding results.' },
      { id: 'c', text: 'Note the changed conditions in the report and interpret with care', isCorrect: true, rationale: 'Documenting nonstandard conditions and qualifying interpretation is the ethically required approach.' },
      { id: 'd', text: 'Lower her score to offset the advantage given to her by the extra time', isCorrect: false, rationale: 'Ad hoc score adjustments have no psychometric basis and would distort the results further.' },
    ],
    rationale: 'Accommodations for disability are often necessary so that a test measures the intended skill rather than the disability. Because norms were built under standard conditions, the counselor notes the accommodations in the interpretation and treats the comparison with norms cautiously; results may be designated as of questionable validity when conditions differ substantially. Some publishers provide guidance on which accommodations preserve comparability.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.7.a Administration Conditions' }, { source: 'Hays (Assessment)', detail: 'Testing accommodations for individuals with disabilities' }],
  },
  {
    id: 'nce-s-ass-092',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'test selection and administration',
    difficulty: 'medium',
    stem: 'To save session time, a counselor wants clients to complete a symptom inventory online at home before intake. The publisher validated the inventory only for proctored administration in an office. Under the ACA Code of Ethics, what should the counselor do?',
    options: [
      { id: 'a', text: 'Allow home use, since online forms are equal to paper forms', isCorrect: false, rationale: 'Equivalence across formats and settings must be shown; it cannot be assumed.' },
      { id: 'b', text: 'Allow home use once the client signs an informed consent form', isCorrect: false, rationale: 'Consent does not make an instrument valid for a use it was not designed or validated for.' },
      { id: 'c', text: 'Allow home use but double the time limit to offset household distractions', isCorrect: false, rationale: 'Changing the time limit adds another departure from standard conditions rather than solving one.' },
      { id: 'd', text: 'Have clients take it under supervision, as it was validated that way', isCorrect: true, rationale: 'Instruments not designed and validated for self-administration should not be used unsupervised.' },
    ],
    rationale: 'The ACA Code of Ethics directs counselors not to permit unsupervised use of an assessment unless it was designed, intended, and validated for self-administration or scoring. Counselors using technology to administer tests must also ensure the platform functions properly and gives accurate results. Convenience does not justify a use that the validity evidence does not support.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.7.d Unsupervised Assessments; E.7.c Technological Administration' }],
    reviewNote: 'Confirm ACA 2014 section numbers E.7.c (Technological Administration) and E.7.d (Unsupervised Assessments).',
  },
  {
    id: 'nce-s-ass-093',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'communicating assessment results',
    difficulty: 'easy',
    stem: 'A counselor is reviewing a personality inventory profile with a 50-year-old client, who looks worried when she sees that one scale is elevated. Which approach to communicating the results is BEST?',
    options: [
      { id: 'a', text: 'Explain the scale in plain terms and ask how it fits her life', isCorrect: true, rationale: 'Clear language and inviting her reactions make the results understandable and collaborative.' },
      { id: 'b', text: 'Read the computer narrative aloud so she hears the full report', isCorrect: false, rationale: 'Automated narratives are generic and technical; the counselor is responsible for interpretation.' },
      { id: 'c', text: 'Skip the elevated scale so that she will not feel more upset', isCorrect: false, rationale: 'Withholding results disregards her right to know and leaves her worry unaddressed.' },
      { id: 'd', text: 'Hand her the profile to study at home and talk next session', isCorrect: false, rationale: 'Leaving her alone with an elevated score and no explanation invites misunderstanding.' },
    ],
    rationale: 'Clients have the right to know their results and the basis for the counselor\'s conclusions. Good interpretation uses everyday language, presents scores as estimates and one source of information, links findings to the client\'s goals, and invites the client to compare the results with her own experience. This turns the profile into a shared working tool rather than a verdict.',
    references: [{ source: 'ACA Code of Ethics', detail: 'E.1.b Client Welfare' }, { source: 'Hays (Assessment)', detail: 'Communicating assessment results to clients' }],
  },
  {
    id: 'nce-s-ass-094',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'medium',
    stem: 'A counselor at a veterans\' clinic gives a client the PTSD Checklist for DSM-5 (PCL-5) at intake and again every few weeks during treatment. Which description of the PCL-5 is accurate?',
    options: [
      { id: 'a', text: 'A structured clinician interview that is the standard for diagnosis', isCorrect: false, rationale: 'This describes the Clinician-Administered PTSD Scale for DSM-5 (CAPS-5), not the PCL-5.' },
      { id: 'b', text: 'A self-report symptom measure used to screen and to track change', isCorrect: true, rationale: 'The PCL-5 is a brief self-report of DSM-5 PTSD symptoms used for screening and monitoring.' },
      { id: 'c', text: 'A checklist of the traumatic events a client has been exposed to', isCorrect: false, rationale: 'Listing exposure to events is the job of a trauma-exposure checklist, not this symptom measure.' },
      { id: 'd', text: 'A projective measure that uncovers unconscious trauma conflicts', isCorrect: false, rationale: 'The PCL-5 is an objective self-report scale with rated items, not a projective technique.' },
    ],
    rationale: 'The PCL-5 is a 20-item self-report measure in which clients rate how much each DSM-5 PTSD symptom has bothered them in the past month. It is widely used to screen, to support a provisional diagnosis, and to monitor change across treatment as part of measurement-based care. A positive result should be followed by a full clinical assessment rather than treated as a diagnosis on its own.',
    references: [{ source: 'VA/DoD CPG', detail: 'PTSD guideline: screening and measurement-based care with the PCL-5' }, { source: 'DSM-5-TR', detail: 'Posttraumatic stress disorder: Criteria B-E' }],
  },
  {
    id: 'nce-s-ass-095',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'couples and family assessment',
    difficulty: 'easy',
    stem: 'In early sessions with a couple, a counselor draws a diagram of three generations of both partners\' families, marking marriages, divorces, deaths, illnesses, substance use, and close or cut-off relationships. What is the main assessment purpose of this tool?',
    options: [
      { id: 'a', text: 'To produce a standardized score for each partner\'s satisfaction', isCorrect: false, rationale: 'A genogram is a qualitative map, not a normed instrument that yields scores.' },
      { id: 'b', text: 'To decide which partner is mainly to blame for the couple\'s ongoing conflict', isCorrect: false, rationale: 'Systemic assessment looks at patterns and context rather than assigning individual blame.' },
      { id: 'c', text: 'To screen each partner for a personality disorder before treatment', isCorrect: false, rationale: 'A genogram maps family structure and patterns; it is not a diagnostic screen.' },
      { id: 'd', text: 'To reveal family patterns across generations that shape current issues', isCorrect: true, rationale: 'Genograms show repeating patterns, alliances, and cutoffs that may bear on present problems.' },
    ],
    rationale: 'The genogram, rooted in Bowen family systems theory, maps at least three generations of a family\'s structure, events, and relationships. As an assessment tool, it helps counselor and clients see recurring patterns, such as conflict, cutoffs, illness, or substance use, that may be carried into the current relationship. It is also a collaborative way to gather family history.',
    references: [{ source: 'Goldenberg (Family Therapy)', detail: 'Bowen family systems: the genogram as an assessment tool' }],
  },
  {
    id: 'nce-s-ass-096',
    domain: 'intake',
    cacrep: 'career',
    topic: 'career assessment: interest inventories',
    difficulty: 'medium',
    stem: 'On the Strong Interest Inventory, a 26-year-old client\'s highest General Occupational Theme is Artistic. Within that theme, her Basic Interest Scale for Culinary Arts is high, while those for Writing and Mass Communication and for Visual Arts and Design are low. How should the counselor interpret this?',
    options: [
      { id: 'a', text: 'The low scales cancel the theme, so artistic work does not fit her', isCorrect: false, rationale: 'One high Basic Interest Scale shows a real artistic interest; the low scales only narrow where it lies.' },
      { id: 'b', text: 'The Basic Interest Scales reflect skills, and themes reflect interests', isCorrect: false, rationale: 'Both scales measure interests; self-rated skill confidence is assessed separately.' },
      { id: 'c', text: 'The theme is broad, and the scales show which artistic areas she favors', isCorrect: true, rationale: 'Basic Interest Scales break each broad theme into specific areas of interest.' },
      { id: 'd', text: 'The Basic Interest Scales compare her with workers in each occupation', isCorrect: false, rationale: 'Comparison with satisfied workers in specific occupations is the role of the Occupational Scales.' },
    ],
    rationale: 'The Strong Interest Inventory reports results at several levels. The six General Occupational Themes follow Holland\'s RIASEC model and describe broad interest patterns; the Basic Interest Scales break those themes into more specific interest areas; the Occupational Scales compare the client\'s likes and dislikes with those of satisfied workers in particular occupations. Reading the Basic Interest Scales within a theme helps the counselor pinpoint which kinds of work fit best.',
    references: [{ source: 'Sharf (Career Development Theory)', detail: 'Strong Interest Inventory: General Occupational Themes, Basic Interest Scales, Occupational Scales' }, { source: 'Hays (Assessment)', detail: 'Career assessment: interest inventories' }],
    reviewNote: 'Confirm that Culinary Arts, Writing and Mass Communication, and Visual Arts and Design are Basic Interest Scales under the Artistic theme in the current Strong edition.',
  },
];
