// tools/nce/seed/intake-5.js — Intake, Assessment and Diagnosis, batch 5
// Hand-authored original items (nce-s-ass-097 … nce-s-ass-120).
module.exports = [
  {
    id: 'nce-s-ass-097',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intake interview structure',
    difficulty: 'medium',
    stem: 'A counselor is starting a first telehealth intake with a 29-year-old client who has joined the video call from a parked car. Before moving into the presenting concern, which step BEST belongs at the opening of this intake?',
    options: [
      { id: 'a', text: 'Ask the client to describe the main reason they are seeking counseling now', isCorrect: false, rationale: 'Exploring the presenting concern matters, but it follows the setup steps that make remote work safe.' },
      { id: 'b', text: 'Give a brief symptom checklist so the session can begin with numbers', isCorrect: false, rationale: 'A screening measure can be useful later; it does not address consent or safety for remote sessions.' },
      { id: 'c', text: 'Confirm where the client is right now and an emergency plan for the session', isCorrect: true, rationale: 'Knowing the client\'s location and how to get help locally is part of informed consent and emergency planning for distance counseling.' },
      { id: 'd', text: 'Suggest the client wait to talk until they can return home to a private room', isCorrect: false, rationale: 'Privacy can be discussed collaboratively, but sending the client away skips the needed consent and safety steps.' },
    ],
    rationale: 'An intake opens with orienting tasks before clinical content: introductions, informed consent, limits of confidentiality, and, for distance counseling, verification of the client\'s identity and current location plus emergency procedures. Location matters because the counselor needs to know which local resources to contact if a crisis arises during the session. Only after this foundation does the interview move to the presenting problem and history.',
    references: [{ source: 'ACA Code of Ethics', detail: 'H.2.a Informed Consent and Disclosure (distance counseling, including emergency procedures); H.3 Client Verification' }],
  },
  {
    id: 'nce-s-ass-098',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intake interview structure',
    difficulty: 'easy',
    stem: 'Many intake forms ask the counselor to record the presenting problem, or chief complaint, as a short quotation in the client\'s own words. What is the main reason for this practice?',
    options: [
      { id: 'a', text: 'It preserves how the client sees the problem before any clinical framing', isCorrect: true, rationale: 'A direct quote keeps the client\'s perspective and language on record, separate from the counselor\'s interpretation.' },
      { id: 'b', text: 'It lets the counselor skip the later questions about history and context', isCorrect: false, rationale: 'The quote opens the interview; history and context are still gathered afterward.' },
      { id: 'c', text: 'It is required so that a diagnosis can be billed to the client\'s insurer', isCorrect: false, rationale: 'Billing depends on a diagnosis and documentation of necessity, not on quoting the client.' },
      { id: 'd', text: 'It shows the counselor has accepted the client\'s view as the diagnosis', isCorrect: false, rationale: 'Recording the client\'s words does not mean adopting them as the clinical formulation.' },
    ],
    rationale: 'The presenting problem is usually recorded first and, where possible, in the client\'s own words. This documents what brought the client in from their point of view, which later helps the counselor check whether the treatment plan addresses the client\'s actual concern. The counselor\'s clinical impressions are recorded separately.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Intake documentation: presenting problem in the client\'s own words' }],
  },
  {
    id: 'nce-s-ass-099',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'hard',
    stem: 'During a mental status examination, a 31-year-old client with insomnia mentions that a few times, just as she was drifting off to sleep, she heard someone call her name and then realized no one was there. She reports no other unusual perceptions, and her thinking is organized. How should the counselor record this?',
    options: [
      { id: 'a', text: 'As auditory hallucinations that meet the first criterion for schizophrenia', isCorrect: false, rationale: 'Perceptions that occur only while falling asleep are not counted as psychotic hallucinations.' },
      { id: 'b', text: 'As a disorder of thought process, since the voice reflects loosened associations', isCorrect: false, rationale: 'Hearing a voice is a perceptual experience; thought process concerns how ideas are connected.' },
      { id: 'c', text: 'As a delusion, since she believed for a moment that someone was in the room', isCorrect: false, rationale: 'A delusion is a fixed false belief; she corrected her impression immediately.' },
      { id: 'd', text: 'As a hypnagogic experience, which is common and not in itself a sign of psychosis', isCorrect: true, rationale: 'Brief perceptions at sleep onset are hypnagogic and fall within the range of normal experience.' },
    ],
    rationale: 'The perception section of the mental status examination notes hallucinations and illusions, but context matters. DSM-5-TR notes that hallucinations occurring while falling asleep (hypnagogic) or waking (hypnopompic) are within the range of normal experience. With organized thinking and no other perceptual disturbance, the counselor records the experience accurately without labeling it psychotic.',
    references: [{ source: 'DSM-5-TR', detail: 'Schizophrenia spectrum: key features — hallucinations; hypnagogic and hypnopompic experiences' }],
  },
  {
    id: 'nce-s-ass-100',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'easy',
    stem: 'A 45-year-old client calmly tells the counselor that the evening news anchor has been sending him personal messages about a secret mission. In which part of the mental status examination does this belong?',
    options: [
      { id: 'a', text: 'Perception', isCorrect: false, rationale: 'Perception covers hallucinations and illusions; he describes a belief about real broadcasts.' },
      { id: 'b', text: 'Thought content', isCorrect: true, rationale: 'Delusions and ideas of reference are recorded under thought content.' },
      { id: 'c', text: 'Thought process', isCorrect: false, rationale: 'Thought process describes how ideas connect, such as tangential or logical.' },
      { id: 'd', text: 'Orientation', isCorrect: false, rationale: 'Orientation covers awareness of person, place, and time.' },
    ],
    rationale: 'The mental status examination separates what a person thinks (thought content) from how the thoughts are organized (thought process). Beliefs that television or other media carry personal messages are delusions of reference and are recorded under thought content, along with obsessions, preoccupations, and suicidal or homicidal ideation.',
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: thought content vs thought process' }],
  },
  {
    id: 'nce-s-ass-101',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'medium',
    stem: 'A counselor reviews intake notes on a 52-year-old client. Which piece of information is a WARNING SIGN of possible near-term suicide risk rather than a longer-standing risk factor?',
    options: [
      { id: 'a', text: 'A brother died by suicide when the client was in their early twenties', isCorrect: false, rationale: 'Family history of suicide is an enduring risk factor, not a sign of imminent risk.' },
      { id: 'b', text: 'The client recently began giving away prized items and saying goodbye', isCorrect: true, rationale: 'Giving away possessions and saying goodbye are recognized warning signs that call for immediate assessment.' },
      { id: 'c', text: 'The client has lived with a painful chronic back condition for ten years', isCorrect: false, rationale: 'Chronic pain raises risk over time but is a background factor, not an acute warning sign.' },
      { id: 'd', text: 'The client made a suicide attempt by overdose about fifteen years ago', isCorrect: false, rationale: 'A past attempt is a strong long-term risk factor, but it is historical rather than a current warning sign.' },
    ],
    rationale: 'Risk factors such as prior attempts, family history, and chronic illness raise risk over a lifetime; warning signs signal that risk may be rising now. Warning signs include talking about wanting to die or being a burden, seeking means, withdrawing, giving away possessions, and saying goodbye. A warning sign calls for direct questioning about ideation, plan, intent, and access to means in the current session.',
    references: [{ source: 'SAMHSA 988 Lifeline', detail: 'Suicide warning signs' }, { source: 'C-SSRS', detail: 'Screening for current ideation, intent, plan, and recent behavior' }],
  },
  {
    id: 'nce-s-ass-102',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'hard',
    stem: 'A 27-year-old warehouse worker, furious about being passed over for promotion, says of his supervisor, "One of these days he\'s going to get what\'s coming to him." He then changes the subject. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Ask directly what he means, including any plan, means, and past violence', isCorrect: true, rationale: 'An ambiguous remark calls for direct assessment of intent, plan, access to weapons, and history before any decision.' },
      { id: 'b', text: 'Call the supervisor to warn him, since a target has now been identified', isCorrect: false, rationale: 'Warning is considered only after assessment shows serious and foreseeable danger under the governing law.' },
      { id: 'c', text: 'Follow the change of subject so the client does not feel accused or judged', isCorrect: false, rationale: 'Letting a possible threat pass unexamined leaves the counselor unable to judge the level of risk.' },
      { id: 'd', text: 'Schedule a personality inventory to measure his general level of hostility', isCorrect: false, rationale: 'A trait measure cannot answer the immediate question of whether he intends to harm a specific person.' },
    ],
    rationale: 'When a client makes an ambiguous statement about harming someone, the counselor\'s first job is to clarify it: whether there is intent, a plan, a means such as a weapon, an identified victim, and a history of violence. That assessment determines whether the situation reaches the threshold of serious and foreseeable harm. Duties to warn or protect, and how they are carried out, depend on that finding and on state law.',
    references: [{ source: 'ACA Code of Ethics', detail: 'B.2.a Serious and Foreseeable Harm and Legal Requirements' }, { source: 'State law', detail: 'Duty-to-warn and duty-to-protect statutes vary by jurisdiction' }],
  },
  {
    id: 'nce-s-ass-103',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'medium',
    stem: 'A 41-year-old client in Minnesota has had major depressive episodes that began in late October and fully remitted by April in each of the last three years. There have been no depressive episodes at other times of year, and no clear yearly stressor explains the timing. Which specifier BEST fits?',
    options: [
      { id: 'a', text: 'With melancholic features', isCorrect: false, rationale: 'Melancholic features describe symptom quality, such as loss of pleasure and early waking, not timing.' },
      { id: 'b', text: 'With atypical features', isCorrect: false, rationale: 'Atypical features describe mood reactivity and related symptoms, not a link to time of year.' },
      { id: 'c', text: 'With peripartum onset', isCorrect: false, rationale: 'Peripartum onset applies to episodes during pregnancy or within four weeks after delivery.' },
      { id: 'd', text: 'With seasonal pattern', isCorrect: true, rationale: 'Regular onset and remission at set times of year, with no nonseasonal episodes, fit this specifier.' },
    ],
    rationale: 'The seasonal pattern specifier applies to recurrent major depressive disorder (and to bipolar episodes) when onset and full remission occur at characteristic times of year. In the last two years there must be at least two episodes showing the seasonal relationship and no nonseasonal episodes, and seasonal episodes must substantially outnumber nonseasonal ones over the lifetime. Timing explained by an obvious seasonal stressor, such as yearly unemployment, does not count.',
    references: [{ source: 'DSM-5-TR', detail: 'Depressive disorders: specifier "with seasonal pattern"' }],
  },
  {
    id: 'nce-s-ass-104',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'hard',
    stem: 'For 14 months, a 26-year-old has had depressed mood plus four other depressive symptoms lasting about three days, roughly once a month, unrelated to the menstrual cycle. She has never met criteria for another depressive or bipolar disorder. The counselor wants the diagnosis to state why full criteria are not met. Which diagnosis fits?',
    options: [
      { id: 'a', text: 'Unspecified depressive disorder, with the reason left unstated', isCorrect: false, rationale: 'The unspecified category is used when the clinician chooses not to state the reason or lacks the information.' },
      { id: 'b', text: 'Major depressive disorder, recurrent, with the provisional label', isCorrect: false, rationale: 'Provisional is for a strong expectation that full criteria will be met; three-day episodes cannot meet the two-week rule.' },
      { id: 'c', text: 'Other specified depressive disorder (recurrent brief depression)', isCorrect: true, rationale: 'The other specified category lets the clinician name the specific reason, here recurrent brief depression.' },
      { id: 'd', text: 'Adjustment disorder with depressed mood, recurrent episodes type', isCorrect: false, rationale: 'Adjustment disorder requires an identifiable stressor and has no recurrent subtype.' },
    ],
    rationale: 'DSM-5-TR offers two residual categories in each chapter. "Other specified" is used when the clinician chooses to communicate the specific reason criteria are not met, by recording the name of the category followed by the reason; "unspecified" is used when the clinician chooses not to give a reason or lacks enough information. Recurrent brief depression, with full-symptom episodes of 2 to 13 days at least monthly for 12 months, is a listed example of other specified depressive disorder.',
    references: [{ source: 'DSM-5-TR', detail: 'Other specified depressive disorder (recurrent brief depression); use of other specified vs unspecified categories' }],
  },
  {
    id: 'nce-s-ass-105',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'intelligence and achievement tests',
    difficulty: 'easy',
    stem: 'An early intervention team wants an individually administered measure of cognitive, language, and motor development for an 18-month-old born prematurely. Which instrument is designed for a child this age?',
    options: [
      { id: 'a', text: 'Bayley Infant and Toddler Scales', isCorrect: true, rationale: 'The Bayley scales assess cognitive, language, and motor development from early infancy to about 42 months.' },
      { id: 'b', text: 'Wechsler Intelligence Scale (WISC-V)', isCorrect: false, rationale: 'The WISC-V is for children aged 6 through 16 and is far above this child\'s age.' },
      { id: 'c', text: 'Wechsler Preschool Scale (WPPSI-IV)', isCorrect: false, rationale: 'The WPPSI-IV begins at 2 years 6 months, so it does not reach an 18-month-old.' },
      { id: 'd', text: 'Peabody Picture Vocabulary Test-5', isCorrect: false, rationale: 'The PPVT measures receptive vocabulary only, not cognitive and motor development.' },
    ],
    rationale: 'Infant and toddler assessment uses developmental scales rather than conventional intelligence tests. The Bayley Scales of Infant and Toddler Development cover roughly the first three and a half years and assess cognitive, language, and motor domains, with social-emotional and adaptive behavior gathered by caregiver report. Scores in infancy are less predictive of later IQ than scores in school age, so results guide early intervention rather than fixed labels.',
    references: [{ source: 'Hays (Assessment)', detail: 'Assessment of infants and young children: Bayley Scales' }, { source: 'Berk (Development Through the Lifespan)', detail: 'Infant intelligence tests and their predictive value' }],
  },
  {
    id: 'nce-s-ass-106',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'intelligence and achievement tests',
    difficulty: 'medium',
    stem: 'A counselor at an adult education program wants a brief, individually administered screen of basic academic skills, such as word reading, spelling, and math computation, for a 38-year-old returning learner. Which instrument fits this purpose?',
    options: [
      { id: 'a', text: 'Wechsler Adult Intelligence Scale-IV', isCorrect: false, rationale: 'The WAIS-IV measures intellectual ability, not acquired academic skills.' },
      { id: 'b', text: 'Raven\'s Progressive Matrices', isCorrect: false, rationale: 'Raven\'s measures nonverbal reasoning with visual patterns, not academic skills.' },
      { id: 'c', text: 'Vineland Adaptive Behavior Scales-3', isCorrect: false, rationale: 'The Vineland measures adaptive behavior in daily life, not reading or math skills.' },
      { id: 'd', text: 'Wide Range Achievement Test-5', isCorrect: true, rationale: 'The WRAT-5 is a brief achievement measure of word reading, comprehension, spelling, and math computation.' },
    ],
    rationale: 'Achievement tests measure what a person has learned, while intelligence and aptitude tests estimate ability or potential to learn. The Wide Range Achievement Test is a short, individually administered achievement screen covering reading, spelling, and math computation across a wide age range. A full intelligence test or an adaptive behavior scale answers a different referral question.',
    references: [{ source: 'Hays (Assessment)', detail: 'Achievement testing: individually administered screening batteries' }],
  },
  {
    id: 'nce-s-ass-107',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'easy',
    stem: 'A counselor asks an 8-year-old to "draw a picture of everyone in your family, including you, doing something." Which projective technique is this?',
    options: [
      { id: 'a', text: 'House-Tree-Person', isCorrect: false, rationale: 'The House-Tree-Person asks for separate drawings of a house, a tree, and a person.' },
      { id: 'b', text: 'Kinetic Family Drawing', isCorrect: true, rationale: 'The Kinetic Family Drawing asks for the whole family shown doing something, to reveal relationships and roles.' },
      { id: 'c', text: 'Bender-Gestalt Test', isCorrect: false, rationale: 'The Bender-Gestalt asks the person to copy geometric designs to assess visual-motor skill.' },
      { id: 'd', text: 'Draw-A-Person Test', isCorrect: false, rationale: 'The Draw-A-Person asks for a single human figure, not the family in action.' },
    ],
    rationale: 'In the Kinetic Family Drawing, the "kinetic" element is the instruction to show family members doing something. Clinicians look at who is included, relative size and placement, interaction, and activity as hypotheses about how the child experiences the family. Like other drawing techniques, it is best used to open conversation rather than to diagnose.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective drawing techniques: Kinetic Family Drawing' }],
  },
  {
    id: 'nce-s-ass-108',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'hard',
    stem: 'A psychological report states that the Rorschach was administered and coded using the Rorschach Performance Assessment System (R-PAS), with the results compared against international reference norms. What does this description tell the counselor reading the report?',
    options: [
      { id: 'a', text: 'The client told stories about pictures that were scored for needs and press', isCorrect: false, rationale: 'Storytelling scored for needs and press describes Murray\'s Thematic Apperception Test.' },
      { id: 'b', text: 'The examiner read the inkblot responses freely with no set coding rules', isCorrect: false, rationale: 'R-PAS exists precisely to replace free interpretation with standardized coding.' },
      { id: 'c', text: 'The inkblots were given and coded with a standardized, normed system', isCorrect: true, rationale: 'R-PAS specifies administration and coding rules and compares scores with reference norms.' },
      { id: 'd', text: 'A true-false self-report inventory was given in place of the inkblots', isCorrect: false, rationale: 'The report says the Rorschach itself was administered; R-PAS is a way of scoring it.' },
    ],
    rationale: 'The Rorschach has been used with several scoring approaches. Exner\'s Comprehensive System standardized administration and coding for decades, and R-PAS, developed later by researchers including Meyer and Mihura, updated the coding with standardized procedures and norm-referenced scores. These systems improve reliability compared with free interpretation, though the Rorschach remains a performance-based measure whose results are integrated with other data.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective and performance-based personality assessment: Rorschach scoring systems' }],
  },
  {
    id: 'nce-s-ass-109',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'hard',
    stem: 'A 60-year-old client has taken a prescribed opioid exactly as directed for chronic back pain for two years. She needs a higher dose than at first for the same relief and feels ill if she misses a dose. She reports no other problems with the medication. How should these two findings be weighed toward opioid use disorder?',
    options: [
      { id: 'a', text: 'They are not counted, because she takes the drug as prescribed', isCorrect: true, rationale: 'DSM-5-TR excludes tolerance and withdrawal from the count when an opioid is taken solely under medical supervision.' },
      { id: 'b', text: 'They count as two criteria, enough for a mild opioid use disorder', isCorrect: false, rationale: 'Two criteria would mean mild severity, but these two are not counted when use is as prescribed.' },
      { id: 'c', text: 'They count, but only once she has used the drug for over a year', isCorrect: false, rationale: 'Duration of use does not change the exclusion for appropriately prescribed medication.' },
      { id: 'd', text: 'They count as one criterion, since both reflect body adaptation', isCorrect: false, rationale: 'Tolerance and withdrawal are separate criteria; the issue is whether they count at all.' },
    ],
    rationale: 'Tolerance and withdrawal are expected physiological effects of long-term opioid treatment. DSM-5-TR therefore notes that these two criteria are not considered met for people taking opioids solely under appropriate medical supervision. A diagnosis would require other criteria, such as using more than prescribed, craving, or continued use despite harm.',
    references: [{ source: 'DSM-5-TR', detail: 'Opioid use disorder, Criteria 10 and 11 notes (tolerance and withdrawal under medical supervision)' }],
  },
  {
    id: 'nce-s-ass-110',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'medium',
    stem: 'To get a detailed picture of a client\'s drinking, a counselor sits with him and a calendar of the past 90 days. Using paydays, holidays, and family events as memory anchors, they estimate how many drinks he had on each day. Which method is the counselor using?',
    options: [
      { id: 'a', text: 'The CAGE questionnaire', isCorrect: false, rationale: 'The CAGE is four yes-or-no screening questions, not a day-by-day record.' },
      { id: 'b', text: 'The AUDIT screening test', isCorrect: false, rationale: 'The AUDIT is a 10-item screen, not a calendar-based recall method.' },
      { id: 'c', text: 'Addiction Severity Index', isCorrect: false, rationale: 'The ASI is a structured interview rating problem severity across life areas.' },
      { id: 'd', text: 'The Timeline Followback', isCorrect: true, rationale: 'The Timeline Followback uses a calendar and memory anchors to reconstruct daily use.' },
    ],
    rationale: 'The Timeline Followback is a calendar-based interview that reconstructs day-by-day substance use over a set window, often 30 to 90 days, using personal events to aid recall. It yields detailed data on frequency, quantity, and patterns such as weekend binges, and it can be repeated to track change. Screening tools such as the CAGE and AUDIT only flag possible problems.',
    references: [{ source: 'Sobell & Sobell (Timeline Followback)', detail: 'Calendar method with memory anchors for daily use estimates' }, { source: 'Hays (Assessment)', detail: 'Substance use assessment: structured and calendar-based methods' }],
  },
  {
    id: 'nce-s-ass-111',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'A 17-year-old who arrived in the United States as a refugee eight months ago is referred for sleep problems and irritability. When taking the biopsychosocial history, which approach to the migration history is MOST complete?',
    options: [
      { id: 'a', text: 'Focus on current school stress, since past events are better left for later', isCorrect: false, rationale: 'Leaving out the migration history can miss trauma and losses that explain current symptoms.' },
      { id: 'b', text: 'Ask mainly about the war and danger that led the family to leave home', isCorrect: false, rationale: 'Pre-migration events matter, but stressors during flight and after arrival are also important.' },
      { id: 'c', text: 'Explore life before leaving, the journey itself, and life since arriving', isCorrect: true, rationale: 'Covering pre-migration, migration, and post-migration phases captures the full range of stressors and supports.' },
      { id: 'd', text: 'Ask about legal status first, since it decides which services are offered', isCorrect: false, rationale: 'Opening with legal status can frighten the client and is not the core of a clinical history.' },
    ],
    rationale: 'Refugee and immigrant clients may face stressors in three phases: before leaving (violence, persecution, loss), during migration (danger, camps, separation from family), and after arrival (acculturation, discrimination, language barriers, poverty). A biopsychosocial history that covers all three, along with strengths and supports, gives a fuller picture than one focused on a single phase. Questions should be paced with care to avoid retraumatizing the client.',
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Counseling refugees and immigrants: pre-migration, migration, and post-migration stressors' }],
  },
  {
    id: 'nce-s-ass-112',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'biopsychosocial history',
    difficulty: 'medium',
    stem: 'A biopsychosocial intake with a 20-year-old college student shows that her mother has an anxiety disorder, panic attacks began after a car accident last month, she now skips classes held in the building where her first attack happened, and she is close to her older sister. Which finding is a PERPETUATING factor?',
    options: [
      { id: 'a', text: 'Her mother\'s long history of being treated for an anxiety disorder', isCorrect: false, rationale: 'Family history is a predisposing factor that raised vulnerability before the problem began.' },
      { id: 'b', text: 'Skipping classes held in the building where her first attack happened', isCorrect: true, rationale: 'Avoidance keeps the fear from being disconfirmed, so it maintains the problem over time.' },
      { id: 'c', text: 'The car accident last month that came just before the first attack', isCorrect: false, rationale: 'An event that triggered onset is a precipitating factor, not one that maintains the problem.' },
      { id: 'd', text: 'Her close and supportive relationship with her older sister at home', isCorrect: false, rationale: 'A supportive relationship is a protective factor that can be drawn on in treatment.' },
    ],
    rationale: 'Biopsychosocial data are often organized into predisposing factors (vulnerabilities such as family history), precipitating factors (events that triggered onset), perpetuating factors (what keeps the problem going), and protective factors (strengths and supports). Perpetuating factors are especially useful for treatment planning because many can be changed; here, avoidance maintains panic and would be a target for exposure-based work.',
    references: [{ source: 'Hays (Assessment)', detail: 'Integrating intake and history data into a case conceptualization' }],
  },
  {
    id: 'nce-s-ass-113',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'easy',
    stem: 'A client\'s score on a self-report scale converts to a z-score of -1.5. What is the equivalent T-score?',
    options: [
      { id: 'a', text: '15', isCorrect: false, rationale: 'This multiplies by 10 without adding the mean of 50.' },
      { id: 'b', text: '45', isCorrect: false, rationale: 'This treats -1.5 as half a standard deviation below the mean.' },
      { id: 'c', text: '65', isCorrect: false, rationale: 'This places the score 1.5 standard deviations above the mean.' },
      { id: 'd', text: '35', isCorrect: true, rationale: 'T = 50 + 10(-1.5) = 50 - 15 = 35.' },
    ],
    rationale: 'T-scores have a mean of 50 and a standard deviation of 10, so T = 50 + 10z. A z-score of -1.5 lies one and a half standard deviations below the mean, which is 15 T-score points below 50, giving a T-score of 35.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard scores: z-scores and T-scores' }],
  },
  {
    id: 'nce-s-ass-114',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'medium',
    stem: 'A normally distributed test has a mean of 50 and a standard deviation of 15. A client earns a raw score of 65. Approximately what is the client\'s percentile rank?',
    options: [
      { id: 'a', text: 'About the 84th percentile', isCorrect: true, rationale: 'The z-score is (65 - 50) / 15 = +1.0; about 50% + 34% = 84% of scores fall below it.' },
      { id: 'b', text: 'About the 65th percentile', isCorrect: false, rationale: 'This confuses the raw score with the percentile rank.' },
      { id: 'c', text: 'About the 98th percentile', isCorrect: false, rationale: 'The 98th percentile corresponds to about z = +2.0, two standard deviations above the mean.' },
      { id: 'd', text: 'About the 68th percentile', isCorrect: false, rationale: 'About 68% of scores fall between -1 and +1 SD; that is not the percentile for z = +1.' },
    ],
    rationale: 'First convert to a z-score: (65 - 50) / 15 = +1.0. In a normal distribution, 50% of scores fall below the mean and about 34% fall between the mean and +1 standard deviation, so a z-score of +1.0 corresponds to roughly the 84th percentile. Confusing this with the 68% that falls within one standard deviation on both sides is a common error.',
    references: [{ source: 'Hays (Assessment)', detail: 'The normal curve: converting z-scores to percentile ranks' }],
  },
  {
    id: 'nce-s-ass-115',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard error of measurement',
    difficulty: 'hard',
    stem: 'A test has a standard deviation of 10 and a reliability coefficient of .91. A client obtains a score of 60. Within which range does the client\'s true score fall with about 68% confidence?',
    options: [
      { id: 'a', text: '54 to 66', isCorrect: false, rationale: 'This is roughly the 95% band, using about two SEMs on each side.' },
      { id: 'b', text: '51 to 69', isCorrect: false, rationale: 'This uses three SEMs on each side, far wider than a 68% band.' },
      { id: 'c', text: '57 to 63', isCorrect: true, rationale: 'SEM = 10 x the square root of .09 = 3, so 60 plus or minus 3 gives 57 to 63.' },
      { id: 'd', text: '59 to 61', isCorrect: false, rationale: 'This uses 10 x .09 = 0.9 and forgets the square root in the formula.' },
    ],
    rationale: 'The standard error of measurement is SD multiplied by the square root of (1 - r): 10 x the square root of .09 = 10 x .3 = 3. About 68% of the time the true score lies within one SEM of the obtained score (60 plus or minus 3, or 57 to 63), and about 95% of the time within roughly two SEMs (about 54 to 66). Reporting a band rather than a single score reminds clients that every obtained score contains error.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement and confidence intervals' }],
  },
  {
    id: 'nce-s-ass-116',
    domain: 'intake',
    cacrep: 'career',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'medium',
    stem: 'In career counseling, a 44-year-old client completes a work values exercise in which she must rank 12 values from most to least important. Security ranks first and Prestige ranks last. Which interpretation is accurate?',
    options: [
      { id: 'a', text: 'She values security more strongly than most adults in a comparison norm group', isCorrect: false, rationale: 'A forced ranking has no norm group comparison, so it cannot show standing relative to others.' },
      { id: 'b', text: 'Security outranks her other values; it says nothing about other people', isCorrect: true, rationale: 'Ranked (ipsative) results show the relative order of values within one person only.' },
      { id: 'c', text: 'She has met a set cutoff that marks mastery of career values clarity', isCorrect: false, rationale: 'A values ranking has no mastery criterion; it is not a criterion-referenced test.' },
      { id: 'd', text: 'Prestige is of no importance to her, as it was ranked in last place', isCorrect: false, rationale: 'Last place means least important of the 12, not unimportant; all values may matter to some degree.' },
    ],
    rationale: 'Ipsative measures, such as forced-choice or ranking formats, compare a person\'s preferences with one another, so the results show what matters most and least to that individual. Because every person\'s rankings sum to the same total, ipsative results cannot be used to compare one person\'s strength of a value with other people\'s, which requires normative scoring. They are useful for clarifying priorities in career decisions.',
    references: [{ source: 'Hays (Assessment)', detail: 'Ipsative vs normative score interpretation' }, { source: 'Sharf (Career Development Theory)', detail: 'Assessing work values in career counseling' }],
  },
  {
    id: 'nce-s-ass-117',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'medium',
    stem: 'Seven months after her husband\'s death, a 66-year-old client reports intense yearning for him nearly every day, trouble accepting the death, and feeling that part of her has died. These reactions impair her daily functioning. Why would prolonged grief disorder not be diagnosed at this point?',
    options: [
      { id: 'a', text: 'For adults, at least 12 months must have passed since the death', isCorrect: true, rationale: 'DSM-5-TR requires that at least 12 months have elapsed since the death for adults (6 months for children).' },
      { id: 'b', text: 'Yearning for the person who died is not one of its core symptoms', isCorrect: false, rationale: 'Intense yearning or preoccupation with the deceased is a core required symptom.' },
      { id: 'c', text: 'The diagnosis applies only when the death was sudden or violent', isCorrect: false, rationale: 'Prolonged grief disorder does not require a particular manner of death.' },
      { id: 'd', text: 'It is listed only in Section III as a condition for further study', isCorrect: false, rationale: 'In DSM-5-TR, prolonged grief disorder is an official diagnosis in Section II.' },
    ],
    rationale: 'DSM-5-TR added prolonged grief disorder to the trauma- and stressor-related disorders. For adults, at least 12 months must have passed since the death (at least 6 months for children and adolescents), with intense yearning or preoccupation plus additional symptoms such as identity disruption or marked emotional pain. Before that point, intense grief is usually understood as an expected response, though the counselor should still assess for a co-occurring major depressive episode.',
    references: [{ source: 'DSM-5-TR', detail: 'Prolonged grief disorder, Criterion A (time since death)' }],
  },
  {
    id: 'nce-s-ass-118',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'medium',
    stem: 'In a primary care behavioral health program, a 35-year-old patient scores 12 on the GAD-7. How should the counselor interpret and use this result?',
    options: [
      { id: 'a', text: 'As severe anxiety that confirms a diagnosis of generalized anxiety disorder', isCorrect: false, rationale: 'A score of 12 falls in the moderate range, and no screening score confirms a diagnosis.' },
      { id: 'b', text: 'As minimal anxiety, since only scores above 20 call for any further review', isCorrect: false, rationale: 'The maximum score is 21; scores of 10 or more are a common cutoff for further evaluation.' },
      { id: 'c', text: 'As a diagnosis of panic disorder, since the GAD-7 measures panic frequency', isCorrect: false, rationale: 'The GAD-7 rates generalized anxiety symptoms; it does not count panic attacks.' },
      { id: 'd', text: 'As moderate anxiety that calls for a fuller diagnostic assessment to follow', isCorrect: true, rationale: 'Scores of 10 to 14 are moderate, and a positive screen leads to a clinical diagnostic evaluation.' },
    ],
    rationale: 'The GAD-7 is a seven-item screen scored 0 to 21, with cutoffs of 5, 10, and 15 marking mild, moderate, and severe anxiety. A score of 10 or higher is commonly used to flag possible clinically significant anxiety. Like all screening instruments, it identifies who needs further assessment; a diagnosis rests on a clinical interview against DSM-5-TR criteria.',
    references: [{ source: 'Hays (Assessment)', detail: 'Brief screening instruments: GAD-7 scoring and interpretation' }],
  },
  {
    id: 'nce-s-ass-119',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'easy',
    stem: 'A counselor in an adolescent treatment program wants an MMPI-family inventory for a 16-year-old client. Which version is normed for this age group?',
    options: [
      { id: 'a', text: 'MMPI-3', isCorrect: false, rationale: 'The MMPI-3 is normed for adults aged 18 and older.' },
      { id: 'b', text: 'MMPI-2', isCorrect: false, rationale: 'The MMPI-2 is an adult instrument for ages 18 and older.' },
      { id: 'c', text: 'MMPI-A-RF', isCorrect: true, rationale: 'The MMPI-A-RF is the restructured form normed for adolescents aged 14 to 18.' },
      { id: 'd', text: 'MMPI-2-RF', isCorrect: false, rationale: 'The MMPI-2-RF is the restructured form for adults, not adolescents.' },
    ],
    rationale: 'The MMPI family includes separate adult and adolescent versions. The MMPI-2, MMPI-2-RF, and MMPI-3 are normed on adults, while the MMPI-A and its restructured form, the MMPI-A-RF, are normed for adolescents aged 14 to 18. Using an adult form with a 16-year-old would compare the client with the wrong norm group.',
    references: [{ source: 'Hays (Assessment)', detail: 'Minnesota Multiphasic Personality Inventory: adult and adolescent versions' }],
  },
  {
    id: 'nce-s-ass-120',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'reliability types',
    difficulty: 'medium',
    stem: 'A counselor needs to reassess a client\'s reading comprehension three weeks after a first testing and worries that the client will remember specific passages and answers. The test publisher offers two versions built to the same specifications. Which kind of reliability evidence matters MOST for this plan?',
    options: [
      { id: 'a', text: 'Interrater reliability between two independent scorers', isCorrect: false, rationale: 'Interrater reliability concerns agreement between scorers, not equivalence of two versions.' },
      { id: 'b', text: 'Alternate-forms reliability between the two test versions', isCorrect: true, rationale: 'Switching versions is sound only if the two forms are shown to yield equivalent scores.' },
      { id: 'c', text: 'Internal consistency of the items within a single version', isCorrect: false, rationale: 'Internal consistency shows items hang together but says nothing about whether forms match.' },
      { id: 'd', text: 'Test-retest reliability of the same version over 3 weeks', isCorrect: false, rationale: 'Reusing the same version invites the memory effects the counselor wants to avoid.' },
    ],
    rationale: 'Alternate-forms (parallel-forms) reliability is estimated by giving two equivalent versions of a test to the same people and correlating the scores. It is the relevant evidence when a counselor plans to retest with a different form to reduce practice and memory effects. Test-retest reliability uses the same form twice and is vulnerable to exactly those effects.',
    references: [{ source: 'Hays (Assessment)', detail: 'Reliability: alternate-forms (parallel-forms) reliability' }],
  },
];
