// tools/nce/seed/intake-7.js — Intake, Assessment, and Diagnosis, batch 7
// Hand-authored original items (nce-s-ass-145 … nce-s-ass-168).
module.exports = [
  {
    id: 'nce-s-ass-145',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'intake interview structure',
    difficulty: 'medium',
    stem: `A 52-year-old Korean American client tells the counselor at intake that she has slept poorly and "worried constantly" for nearly ten years. She has never sought help before. Which question would BEST identify what prompted her to seek counseling now?`,
    options: [
      { id: 'a', text: `What led you to decide to come in for help at this point?`, isCorrect: true, rationale: `Asking "why now" draws out the precipitating event or tipping point that turned a long-standing problem into a reason to seek help.` },
      { id: 'b', text: `How would you rate your worry on a scale from 1 to 10?`, isCorrect: false, rationale: `A scaling question gauges current severity but does not reveal what changed to bring her in.` },
      { id: 'c', text: `Did anyone in your family also have trouble with worry?`, isCorrect: false, rationale: `Family history belongs in the intake, but it addresses vulnerability, not the recent precipitant.` },
      { id: 'd', text: `What have you already tried to manage the worry yourself?`, isCorrect: false, rationale: `Past coping attempts are useful to know but do not explain why she is seeking help at this moment.` },
    ],
    rationale: `When a problem is long-standing, the intake should explore what has changed recently, such as a new stressor, a loss, a worsening of symptoms, or pressure from others. The precipitant often reveals the client's most urgent concern, her expectations for counseling, and possible risk. It also helps the counselor and client agree on initial goals.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Clinical interviewing: presenting problem, onset and precipitating events' }],
  },
  {
    id: 'nce-s-ass-146',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'easy',
    stem: `During an interview, a 33-year-old client shifts within a minute from laughing loudly to sobbing and then to shouting angrily, with no change in topic that would explain the shifts. Which term BEST describes this client's affect in the mental status examination?`,
    options: [
      { id: 'a', text: `Blunted`, isCorrect: false, rationale: `Blunted affect is a marked reduction in the intensity of emotional expression, the opposite of this presentation.` },
      { id: 'b', text: `Labile`, isCorrect: true, rationale: `Labile affect is rapid, abrupt shifting between emotional states that are out of proportion to what is happening.` },
      { id: 'c', text: `Constricted`, isCorrect: false, rationale: `Constricted affect is a narrowed range of emotional expression, not rapid swings across a wide range.` },
      { id: 'd', text: `Incongruent`, isCorrect: false, rationale: `Incongruent affect is a mismatch between expressed emotion and thought content; the hallmark here is rapid shifting.` },
    ],
    rationale: `The MSE describes affect by its range, intensity, stability, and appropriateness to content. Lability concerns stability: emotions change quickly and dramatically without an adequate trigger. It can appear in mania, intoxication, some neurological conditions, and personality disorders, so it is described and then considered alongside the rest of the assessment.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: affect (range, intensity, stability, appropriateness)' }],
  },
  {
    id: 'nce-s-ass-147',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'medium',
    stem: `While describing his week, a 24-year-old client stops abruptly in the middle of a sentence and stays silent for several seconds. When the counselor asks what happened, he says his mind "went completely empty" and he cannot recall what he was saying. How should the counselor record this in the mental status examination?`,
    options: [
      { id: 'a', text: `Circumstantiality in thought process`, isCorrect: false, rationale: `Circumstantiality is excessive detail that eventually reaches the point, not a sudden halt in thought.` },
      { id: 'b', text: `Poverty of speech, reduced output`, isCorrect: false, rationale: `Poverty of speech is a general reduction in the amount of speech, not an abrupt break mid-sentence.` },
      { id: 'c', text: `Thought blocking in thought process`, isCorrect: true, rationale: `Thought blocking is a sudden interruption in the train of thought, often with the person unable to recall what was being said.` },
      { id: 'd', text: `Psychomotor slowing in behavior`, isCorrect: false, rationale: `Psychomotor slowing is general slowing of movement and speech, not a sudden stop in the flow of thought.` },
    ],
    rationale: `Thought process describes how ideas are connected and how they flow. Thought blocking is a sudden stop in that flow, after which the person may report that the thought vanished. It is often associated with psychotic disorders but can also occur with severe anxiety, so the counselor records the observation and considers it with other findings rather than diagnosing from it alone.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: thought process (blocking, circumstantiality, tangentiality)' }],
  },
  {
    id: 'nce-s-ass-148',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'medium',
    stem: `A 31-year-old client is being discharged after a week on an inpatient psychiatric unit following a suicide attempt. He says he feels "much better" and is eager to return to work. The community counselor is scheduling follow-up. Which statement about his suicide risk is MOST accurate?`,
    options: [
      { id: 'a', text: `His risk has returned to his baseline level, since he now reports better mood`, isCorrect: false, rationale: `Reported improvement does not cancel the recent attempt, which remains one of the strongest risk factors.` },
      { id: 'b', text: `His risk is low now, because inpatient care has resolved the underlying crisis`, isCorrect: false, rationale: `A short hospital stay stabilizes acute danger but rarely resolves the stressors he returns to.` },
      { id: 'c', text: `His risk can be judged mainly by how eager he now seems to return to his job`, isCorrect: false, rationale: `Eagerness is one observation, not a basis for a risk judgment; a full reassessment is needed.` },
      { id: 'd', text: `His risk stays high in the weeks after discharge, so prompt follow-up is needed`, isCorrect: true, rationale: `The period right after psychiatric discharge carries markedly elevated suicide risk, so early contact and a safety plan are essential.` },
    ],
    rationale: `Suicide risk is especially high in the days and weeks after discharge from inpatient care, when people return to the stressors that preceded the crisis with less support. A recent attempt is a major risk factor even when mood appears improved. Best practice is a follow-up appointment soon after discharge, an updated safety plan, and attention to lethal means.`,
    references: [{ source: 'James & Gilliland (Crisis Intervention Strategies)', detail: 'Suicide: risk assessment, prior attempts and periods of heightened risk' }, { source: 'Stanley-Brown SPI', detail: 'Safety planning and follow-up contact for people leaving emergency or inpatient care' }],
  },
  {
    id: 'nce-s-ass-149',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'medium',
    stem: `A counselor is assessing violence risk in a 29-year-old client and wants the plan to target factors that treatment could change. Which of the following is a DYNAMIC risk factor for violence?`,
    options: [
      { id: 'a', text: `Current heavy alcohol use`, isCorrect: true, rationale: `Active substance use is a changeable (dynamic) factor that treatment and monitoring can target.` },
      { id: 'b', text: `A history of violent arrests`, isCorrect: false, rationale: `Past violence is a strong predictor but a static factor; history cannot be changed.` },
      { id: 'c', text: `Childhood exposure to abuse`, isCorrect: false, rationale: `Childhood abuse is a historical, static factor that remains fixed regardless of treatment.` },
      { id: 'd', text: `Early age at first offense`, isCorrect: false, rationale: `Age at first offense is fixed in the past, so it is a static factor.` },
    ],
    rationale: `Risk factors are commonly divided into static factors, which are historical and unchangeable, and dynamic factors, which can change over time and with intervention. Static factors such as prior violence help estimate baseline risk, while dynamic factors such as substance use, acute symptoms, access to weapons, and current anger guide treatment planning and monitoring.`,
    references: [{ source: 'James & Gilliland (Crisis Intervention Strategies)', detail: 'Assessing violence potential: historical versus current, changeable risk factors' }],
  },
  {
    id: 'nce-s-ass-150',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'medium',
    stem: `A 46-year-old client seeks counseling because of frequent arguments with his husband about money and household roles. After a thorough assessment, the counselor finds that he does not meet criteria for any mental disorder. How can the counselor document the focus of counseling using DSM-5-TR?`,
    options: [
      { id: 'a', text: `Diagnose adjustment disorder, since some distress is present`, isCorrect: false, rationale: `Adjustment disorder requires clinically significant distress or impairment beyond what the stressor would explain; distress alone is not enough.` },
      { id: 'b', text: `Record relationship distress from the Z-code conditions`, isCorrect: true, rationale: `DSM-5-TR lists Relationship Distress With Spouse or Intimate Partner among conditions that may be a focus of clinical attention.` },
      { id: 'c', text: `Use unspecified anxiety disorder so the service can be billed`, isCorrect: false, rationale: `Assigning a diagnosis that the assessment does not support misrepresents the client's condition.` },
      { id: 'd', text: `Leave the record blank until a disorder appears in a later session`, isCorrect: false, rationale: `The reason for services should be documented; DSM-5-TR provides codes for non-disorder concerns.` },
    ],
    rationale: `DSM-5-TR includes a chapter on Other Conditions That May Be a Focus of Clinical Attention, most coded with ICD-10-CM Z codes. These are not mental disorders but describe problems, such as relationship distress, that bring a person to counseling or affect care. Using them lets the counselor document the focus accurately without assigning an unsupported diagnosis.`,
    references: [{ source: 'DSM-5-TR', detail: 'Other Conditions That May Be a Focus of Clinical Attention: Relationship Distress With Spouse or Intimate Partner (Z63.0)' }],
  },
  {
    id: 'nce-s-ass-151',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'hard',
    stem: `A 34-year-old woman who met criteria for severe alcohol use disorder has spent the past five months in a residential program where alcohol is not available. Since admission she has met no criteria for the disorder except continued craving. Which DSM-5-TR course specifiers should accompany the diagnosis?`,
    options: [
      { id: 'a', text: `In sustained remission, in a controlled environment`, isCorrect: false, rationale: `Sustained remission requires 12 months or longer without meeting criteria other than craving; she is at five months.` },
      { id: 'b', text: `In early remission, with no further specifier needed`, isCorrect: false, rationale: `An added specifier is used when the person is in a setting where access to the substance is restricted.` },
      { id: 'c', text: `In sustained remission, with craving noted separately`, isCorrect: false, rationale: `The time frame is wrong, and craving is already the one criterion allowed during remission.` },
      { id: 'd', text: `In early remission, in a controlled environment`, isCorrect: true, rationale: `Three to under 12 months with no criteria met except craving is early remission, and residential restriction adds the controlled-environment specifier.` },
    ],
    rationale: `For substance use disorders, DSM-5-TR defines early remission as at least 3 but less than 12 months without meeting any criterion except craving, and sustained remission as 12 months or longer. The specifier "in a controlled environment" is added when the person is in a setting where access to the substance is restricted. It signals that remission has not yet been tested in an unrestricted setting.`,
    references: [{ source: 'DSM-5-TR', detail: 'Alcohol Use Disorder: specifiers in early remission, in sustained remission, in a controlled environment' }],
  },
  {
    id: 'nce-s-ass-152',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'medium',
    stem: `During an intake, a 27-year-old client says his neighbors keep "trinkling the walls with glorphic waves." Asked what he means, he explains that "glorphic" is a kind of energy only he can sense and "trinkling" is how they send it. In the mental status examination, how should the counselor describe these invented words?`,
    options: [
      { id: 'a', text: `Clang associations`, isCorrect: false, rationale: `Clang associations link words by sound or rhyme rather than meaning; these are newly coined words.` },
      { id: 'b', text: `Echolalia`, isCorrect: false, rationale: `Echolalia is repeating another person's words or phrases, not inventing new ones.` },
      { id: 'c', text: `Neologisms`, isCorrect: true, rationale: `Neologisms are new words a person creates, often with private meanings known only to the speaker.` },
      { id: 'd', text: `Circumstantiality`, isCorrect: false, rationale: `Circumstantiality is excessive, roundabout detail that eventually reaches the point, not invented vocabulary.` },
    ],
    rationale: `The MSE records the form of speech and thought separately from its content. Neologisms are invented words, or ordinary words given idiosyncratic meanings, and they are a sign of disorganized thinking most often seen in psychotic disorders. The counselor quotes examples in the record, since specific wording lets other clinicians judge the finding, and considers it alongside thought content such as the belief that neighbors are sending energy.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: speech and thought process (neologisms, clang associations, echolalia)' }],
  },
  {
    id: 'nce-s-ass-153',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'hard',
    stem: `Six weeks after giving birth, a 30-year-old client reports sudden, vivid images of dropping her baby down the stairs. She finds the images horrifying, has no wish to harm the infant, avoids carrying him near stairs, and checks many times a night that he is breathing. Her mood is otherwise stable. Which diagnosis do these symptoms MOST suggest?`,
    options: [
      { id: 'a', text: `Postpartum psychosis`, isCorrect: false, rationale: `She recognizes the images as unwanted and senseless; there are no delusions, hallucinations, or disorganization.` },
      { id: 'b', text: `Generalized anxiety disorder`, isCorrect: false, rationale: `GAD worry is about realistic everyday matters, not intrusive, unwanted images followed by checking and avoidance.` },
      { id: 'c', text: `Depression with peripartum onset`, isCorrect: false, rationale: `Her mood is stable, and the presentation centers on intrusive images and compulsive checking.` },
      { id: 'd', text: `Obsessive-compulsive disorder`, isCorrect: true, rationale: `Intrusive, unwanted harm images that cause distress, plus checking and avoidance meant to prevent harm, are obsessions and compulsions.` },
    ],
    rationale: `Obsessions are intrusive, unwanted thoughts, urges, or images that cause marked distress, and the person tries to ignore, suppress, or neutralize them, often with compulsions. Unwanted thoughts of accidentally or deliberately harming an infant are common in perinatal OCD and are experienced as repugnant, which distinguishes them from psychotic thinking. Recognizing this pattern prevents both missed diagnosis and unwarranted alarm about intent to harm.`,
    references: [{ source: 'DSM-5-TR', detail: 'Obsessive-Compulsive Disorder: obsessions, compulsions and differential diagnosis with anxiety and psychotic disorders' }],
  },
  {
    id: 'nce-s-ass-154',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'reliability types',
    difficulty: 'hard',
    stem: `A clerical speed test has 200 very easy items and a strict 5-minute time limit; scores depend almost entirely on how many items a person reaches. The developer reports an odd-even split-half reliability of .97. What is the main concern with this estimate?`,
    options: [
      { id: 'a', text: `Split-half methods inflate reliability for speeded tests`, isCorrect: true, rationale: `On a pure speed test, odd and even half scores are nearly identical for each person, so the split-half coefficient is spuriously high.` },
      { id: 'b', text: `Split-half methods underestimate reliability for easy items`, isCorrect: false, rationale: `The problem is overestimation, and it comes from the time limit, not item ease alone.` },
      { id: 'c', text: `Odd-even splits are only valid for tests with fewer items`, isCorrect: false, rationale: `Test length is not the issue; a long power test can be split this way appropriately.` },
      { id: 'd', text: `A value of .97 shows the test has strong construct validity`, isCorrect: false, rationale: `A reliability coefficient, even a correct one, is not evidence of construct validity.` },
    ],
    rationale: `Internal consistency methods assume that performance reflects item content rather than how far a person gets. On a speeded test, almost every attempted item is correct, so any odd-even split produces near-identical halves and an inflated coefficient. Test-retest or alternate-form reliability, or split halves timed separately, give more appropriate estimates for speeded tests.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Reliability: internal consistency estimates and speeded versus power tests' }],
  },
  {
    id: 'nce-s-ass-155',
    domain: 'intake',
    cacrep: 'research',
    topic: 'reliability types',
    difficulty: 'medium',
    stem: `A graduate program studies the reliability of a reasoning test using only its admitted students, all of whom scored in the top 10% on that test. The reliability coefficient comes out much lower than the one reported in the test manual. What is the MOST likely explanation?`,
    options: [
      { id: 'a', text: `Admitted students answered the items more carelessly`, isCorrect: false, rationale: `Nothing suggests careless responding; the sample's score range explains the drop.` },
      { id: 'b', text: `The narrow range of scores lowered the correlation`, isCorrect: true, rationale: `Restricting the sample to top scorers shrinks score variance, and correlation-based coefficients fall when variance is restricted.` },
      { id: 'c', text: `The test manual must have reported its values in error`, isCorrect: false, rationale: `The manual's value came from a broader norm sample, so the two estimates are not directly comparable.` },
      { id: 'd', text: `Higher-scoring examinees are less consistent over time`, isCorrect: false, rationale: `High scorers are not inherently less consistent; the lower value reflects the limited range.` },
    ],
    rationale: `Reliability coefficients are correlations, and correlations depend on the variability of scores in the sample. When a sample includes only a narrow slice of the score range, true-score differences shrink relative to error, and the coefficient drops. Counselors should compare their clients with the sample used to estimate reliability before relying on a manual's figure.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Factors affecting reliability: heterogeneity of the sample and restriction of range' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Correlation: restriction of range' }],
  },
  {
    id: 'nce-s-ass-156',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'validity types',
    difficulty: 'hard',
    stem: `A clinic already predicts treatment dropout from a brief intake interview. Before adding a 45-minute questionnaire to every intake, the director wants to know whether the questionnaire improves prediction beyond what the interview already provides. Which type of validity evidence is the director asking about?`,
    options: [
      { id: 'a', text: `Concurrent validity`, isCorrect: false, rationale: `Concurrent validity compares scores with a criterion measured at the same time, not added predictive value.` },
      { id: 'b', text: `Content validity`, isCorrect: false, rationale: `Content validity concerns how well items sample a domain, not prediction of dropout.` },
      { id: 'c', text: `Incremental validity`, isCorrect: true, rationale: `Incremental validity is the improvement in prediction a measure adds over information already available.` },
      { id: 'd', text: `Convergent validity`, isCorrect: false, rationale: `Convergent validity is a strong correlation with other measures of the same construct.` },
    ],
    rationale: `Incremental validity asks whether a new measure explains additional variance in a criterion after existing predictors are accounted for, often tested with hierarchical regression. A measure can be valid on its own yet add little if it overlaps with what is already known. It is a practical question whenever extra testing costs client and staff time.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Validity: criterion-related evidence and incremental validity' }],
  },
  {
    id: 'nce-s-ass-157',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'hard',
    stem: `To set the passing score on a licensure exam, a panel of experts estimates, for each item, the probability that a minimally competent practitioner would answer it correctly, and the estimates are summed into a cut score. What does this approach mean for how candidates' results are interpreted?`,
    options: [
      { id: 'a', text: `A fixed share of candidates will fail each time the exam is given`, isCorrect: false, rationale: `A fixed failure rate is a norm-referenced approach; here anyone who meets the standard passes.` },
      { id: 'b', text: `Each candidate's score is reported as a percentile within the cohort`, isCorrect: false, rationale: `Percentile ranks compare candidates with each other, which this cut-score method does not do.` },
      { id: 'c', text: `Passing depends mostly on how well others in the same cohort score`, isCorrect: false, rationale: `The cut score is fixed in advance from item judgments, not from the cohort's performance.` },
      { id: 'd', text: `Passing depends on meeting a set standard, not on others' scores`, isCorrect: true, rationale: `An expert-judged cut score makes the decision criterion-referenced: each candidate is compared with a standard of competence.` },
    ],
    rationale: `This is the Angoff method of standard setting, widely used for licensure and certification exams. Because the cut score reflects a judged level of minimum competence, results are interpreted against that standard, so in principle every candidate could pass or fail. Norm-referenced interpretation, by contrast, locates a person relative to a comparison group.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Criterion-referenced interpretation: setting cut scores (Angoff method)' }],
  },
  {
    id: 'nce-s-ass-158',
    domain: 'intake',
    cacrep: 'research',
    topic: 'standard scores, percentiles and the normal curve',
    difficulty: 'easy',
    stem: `A counselor graphs scores from a brief screening scale and sees that, compared with a normal curve, most scores bunch tightly around the mean, forming a tall, narrow peak with heavier tails. Which term describes the shape of this distribution?`,
    options: [
      { id: 'a', text: `Leptokurtic`, isCorrect: true, rationale: `A leptokurtic distribution is more sharply peaked than the normal curve, with scores clustered near the mean and heavier tails.` },
      { id: 'b', text: `Platykurtic`, isCorrect: false, rationale: `A platykurtic distribution is flatter than normal, with scores spread more evenly across the range.` },
      { id: 'c', text: `Positively skewed`, isCorrect: false, rationale: `Skew describes asymmetry, with a long tail on one side, not how peaked the curve is.` },
      { id: 'd', text: `Bimodal`, isCorrect: false, rationale: `A bimodal distribution has two distinct peaks, not one tall, narrow peak.` },
    ],
    rationale: `Kurtosis describes how peaked or flat a distribution is relative to the normal (mesokurtic) curve. Leptokurtic distributions have a tall, narrow center and heavier tails; platykurtic distributions are flat and broad. Kurtosis and skewness are separate properties: one concerns peakedness, the other symmetry.`,
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Descriptive statistics: shape of distributions, kurtosis (leptokurtic, mesokurtic, platykurtic)' }],
  },
  {
    id: 'nce-s-ass-159',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard error of measurement',
    difficulty: 'easy',
    stem: `A parent asks a school counselor what the "standard error of measurement" printed on her son's test report means. Which explanation is accurate?`,
    options: [
      { id: 'a', text: `How far the class average falls from the national average`, isCorrect: false, rationale: `That describes a group comparison, not the precision of one student's score.` },
      { id: 'b', text: `How much his score would vary if he took the test many times`, isCorrect: true, rationale: `The SEM estimates the spread of a person's obtained scores around the true score across hypothetical repeated testings.` },
      { id: 'c', text: `How much of his score reflects effort rather than ability`, isCorrect: false, rationale: `The SEM does not separate effort from ability; it reflects random measurement error.` },
      { id: 'd', text: `How many items on his test were scored wrongly by mistake`, isCorrect: false, rationale: `Scoring mistakes are not what the SEM measures; it is a statistical estimate from reliability.` },
    ],
    rationale: `The standard error of measurement is the standard deviation of the scores a person would obtain if tested many times, assuming no practice or fatigue. It is calculated from the test's standard deviation and reliability and is used to build confidence bands around an obtained score. A smaller SEM means a more precise score.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement: definition and use in confidence intervals' }],
  },
  {
    id: 'nce-s-ass-160',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'intelligence and achievement tests',
    difficulty: 'easy',
    stem: `On an intelligence test, a 68-year-old retired teacher scores well above average on vocabulary and general knowledge subtests but only average on timed tasks that require solving novel visual puzzles. In Cattell's theory, the vocabulary and knowledge tasks mainly measure which ability?`,
    options: [
      { id: 'a', text: `Fluid intelligence`, isCorrect: false, rationale: `Fluid intelligence is reasoning with novel problems, as in the timed visual puzzles.` },
      { id: 'b', text: `Working memory`, isCorrect: false, rationale: `Working memory is holding and manipulating information in mind briefly, not stored knowledge.` },
      { id: 'c', text: `Crystallized intelligence`, isCorrect: true, rationale: `Crystallized intelligence is accumulated knowledge and vocabulary gained through education and experience.` },
      { id: 'd', text: `Processing speed`, isCorrect: false, rationale: `Processing speed is how quickly simple tasks are done; vocabulary and knowledge are not speed measures.` },
    ],
    rationale: `Cattell, later with Horn, distinguished fluid intelligence (Gf), the capacity to reason and solve new problems, from crystallized intelligence (Gc), knowledge built through culture and schooling. Crystallized abilities tend to hold steady or grow into later adulthood, while fluid abilities and speed decline earlier. This pattern helps explain the profile of this older client.`,
    references: [{ source: 'Berk (Development Through the Lifespan)', detail: 'Middle and late adulthood: crystallized and fluid intelligence' }, { source: 'Hays (Assessment)', detail: 'Theories of intelligence: Cattell-Horn fluid and crystallized abilities' }],
  },
  {
    id: 'nce-s-ass-161',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'medium',
    stem: `A counselor at an outpatient clinic wants a self-report inventory designed for adults already in mental health treatment. It should focus on personality patterns and clinical syndromes and report base rate scores rather than T-scores. Which instrument fits?`,
    options: [
      { id: 'a', text: `NEO Personality Inventory-3`, isCorrect: false, rationale: `The NEO-PI-3 measures the five-factor traits in the general population and reports T-scores.` },
      { id: 'b', text: `California Psychological Inventory`, isCorrect: false, rationale: `The CPI assesses everyday interpersonal traits in nonclinical populations.` },
      { id: 'c', text: `The 16PF Questionnaire, 5th edition`, isCorrect: false, rationale: `The 16PF measures normal-range personality factors and uses sten scores.` },
      { id: 'd', text: `Millon Clinical Multiaxial Inventory-IV`, isCorrect: true, rationale: `The MCMI-IV is normed on adults in treatment, targets personality patterns and clinical syndromes, and uses base rate scores.` },
    ],
    rationale: `The MCMI-IV is built on Millon's theory of personality and normed on clinical samples, so it is meant for people already presenting for mental health care, not for screening the general public. Its base rate scores adjust for how common each pattern is in clinical populations. Instruments such as the NEO-PI-3, CPI, and 16PF describe normal-range personality instead.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Personality assessment: Millon Clinical Multiaxial Inventory and base rate scores' }],
  },
  {
    id: 'nce-s-ass-162',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'easy',
    stem: `A counselor wants a storytelling projective technique for a 5-year-old, using pictures designed for young children in which the characters are animals in human-like situations. Which instrument fits this description?`,
    options: [
      { id: 'a', text: `Children's Apperception Test`, isCorrect: true, rationale: `The CAT, developed by Bellak and Bellak for young children, presents animal figures in human situations for storytelling.` },
      { id: 'b', text: `Rotter Incomplete Sentences Blank`, isCorrect: false, rationale: `This is a sentence completion technique, not picture-based storytelling.` },
      { id: 'c', text: `Rorschach Inkblot Test`, isCorrect: false, rationale: `The Rorschach uses inkblots that the person describes, not pictures of characters.` },
      { id: 'd', text: `Kinetic Family Drawing`, isCorrect: false, rationale: `The KFD asks the child to draw the family doing something, not to tell stories about pictures.` },
    ],
    rationale: `Apperception tests ask people to tell stories about ambiguous pictures, on the assumption that they project their own needs and conflicts into the stories. The Children's Apperception Test adapted the TAT approach for young children by using animal figures, which were thought to be easier for children to identify with; a later version uses human figures. Like other projectives, it is interpreted cautiously and alongside other data.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Projective techniques: apperception tests (TAT and Children\'s Apperception Test)' }],
  },
  {
    id: 'nce-s-ass-163',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'easy',
    stem: `A counselor uses the CAGE questionnaire with a 58-year-old client. He answers "yes" to having felt he should cut down on his drinking and to having had a drink first thing in the morning to steady his nerves. How should this result be interpreted?`,
    options: [
      { id: 'a', text: `It confirms that he has an alcohol use disorder diagnosis`, isCorrect: false, rationale: `A screen identifies possible problems; diagnosis requires a full assessment against DSM-5-TR criteria.` },
      { id: 'b', text: `It is a positive screen that calls for fuller assessment`, isCorrect: true, rationale: `Two or more "yes" answers on the CAGE is generally considered clinically significant and warrants further assessment.` },
      { id: 'c', text: `It is negative, because a positive screen needs all four`, isCorrect: false, rationale: `The usual cutoff is two of four items, not all four.` },
      { id: 'd', text: `It shows low risk, since only half the items were endorsed`, isCorrect: false, rationale: `Two endorsements meet the usual cutoff, and a morning eye-opener is especially concerning.` },
    ],
    rationale: `The CAGE asks four yes-or-no questions about Cutting down, Annoyance at criticism, Guilt, and an Eye-opener drink. A score of 2 or more is the usual cutoff for a positive screen. Like other screening tools, it flags people who need a fuller assessment rather than establishing a diagnosis.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Substance use screening instruments: CAGE scoring and cutoff' }],
  },
  {
    id: 'nce-s-ass-164',
    domain: 'intake',
    cacrep: 'research',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'medium',
    stem: `A college counseling center chooses a depression screener with very high sensitivity and only moderate specificity. Which outcome should staff expect when they use it?`,
    options: [
      { id: 'a', text: `Few students it flags will turn out not to be depressed`, isCorrect: false, rationale: `Few false positives would reflect high specificity, which this screener lacks.` },
      { id: 'b', text: `Many students with depression will be missed by the screen`, isCorrect: false, rationale: `Missing many true cases describes low sensitivity, the opposite of this tool.` },
      { id: 'c', text: `Few depressed students are missed, but some flags are false`, isCorrect: true, rationale: `High sensitivity means few false negatives; moderate specificity means a fair number of false positives.` },
      { id: 'd', text: `Most negative results will need follow-up to be confirmed`, isCorrect: false, rationale: `With high sensitivity, negative results are fairly trustworthy; positives are what need follow-up.` },
    ],
    rationale: `Sensitivity is the proportion of people with a condition whom the test correctly flags, and specificity is the proportion without it whom the test correctly clears. Screening tools are usually tuned for high sensitivity so that few true cases are missed, accepting more false positives. That is why a positive screen is followed by a fuller diagnostic assessment.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Screening: sensitivity, specificity and false positives' }],
  },
  {
    id: 'nce-s-ass-165',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'medium',
    stem: `Before a timed math achievement test, a proctor tells a group of high school students that the test "tends to show differences between boys and girls." Girls in this group score lower than equally prepared girls who took the test without the remark. Which phenomenon BEST explains the difference?`,
    options: [
      { id: 'a', text: `Test-retest error`, isCorrect: false, rationale: `Test-retest error concerns score changes across repeated testing, not a remark made before one session.` },
      { id: 'b', text: `The Flynn effect`, isCorrect: false, rationale: `The Flynn effect is a rise in population test scores over decades.` },
      { id: 'c', text: `Regression to the mean`, isCorrect: false, rationale: `Regression to the mean affects extreme scorers on retesting, not equally prepared groups tested once.` },
      { id: 'd', text: `Stereotype threat`, isCorrect: true, rationale: `Making a negative group stereotype salient can raise anxiety and depress performance among members of that group.` },
    ],
    rationale: `Stereotype threat, described by Steele and Aronson, occurs when people risk confirming a negative stereotype about their group, and the resulting concern lowers their performance. It shows that test scores can be influenced by the testing context, not only by ability. Culturally fair assessment includes administering tests in conditions that avoid cueing group stereotypes.`,
    references: [{ source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Stereotype threat and its effect on test performance' }, { source: 'Hays (Assessment)', detail: 'Assessment of diverse populations: test-taker and situational factors' }],
  },
  {
    id: 'nce-s-ass-166',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'medium',
    stem: `A school counselor gathers teacher ratings for a 12-year-old referred for possible inattention. One teacher, who rates most students across the full range, describes this boy as polite and a pleasure to have in class and rates him excellent on every scale, including organization and task completion, where his work samples show clear problems. Which rating error is MOST likely?`,
    options: [
      { id: 'a', text: `Halo effect`, isCorrect: true, rationale: `A favorable overall impression from one trait, politeness, is spilling over into ratings of unrelated behaviors.` },
      { id: 'b', text: `Central tendency error`, isCorrect: false, rationale: `Central tendency error is clustering ratings in the middle of the scale, not rating everything excellent.` },
      { id: 'c', text: `Leniency error`, isCorrect: false, rationale: `Leniency is rating all ratees favorably; this teacher uses the full range with other students.` },
      { id: 'd', text: `Contrast error`, isCorrect: false, rationale: `Contrast error is rating someone in relation to a person rated just before, which is not described here.` },
    ],
    rationale: `Rating scales completed by teachers, parents, or other informants are vulnerable to rater errors. The halo effect occurs when a general impression, positive or negative, colors ratings of specific, unrelated traits. Counselors reduce its impact by gathering ratings from several informants, checking them against work samples and observations, and using scales with behaviorally specific items.`,
    references: [{ source: 'Hays (Assessment)', detail: 'Rating scales and behavioral observation: rater errors (halo, leniency, central tendency)' }],
  },
  {
    id: 'nce-s-ass-167',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'medium',
    stem: `A 44-year-old client diagnosed with major depressive disorder, single episode, has improved over three months of treatment. She no longer meets full criteria for a major depressive episode, but she still has low energy and some trouble concentrating most days. Which DSM-5-TR specifier describes her current status?`,
    options: [
      { id: 'a', text: `In full remission`, isCorrect: false, rationale: `Full remission requires no significant signs or symptoms of the disturbance for the past 2 months.` },
      { id: 'b', text: `In partial remission`, isCorrect: true, rationale: `Some symptoms of the episode remain, but full criteria are no longer met, which defines partial remission.` },
      { id: 'c', text: `Recurrent episode, mild`, isCorrect: false, rationale: `She has not had a new episode; "recurrent" requires a second episode after an interval of remission.` },
      { id: 'd', text: `With melancholic features`, isCorrect: false, rationale: `Melancholic features describe the symptom pattern of an episode, not its remission status.` },
    ],
    rationale: `DSM-5-TR uses remission specifiers when criteria for a major depressive episode are no longer met. Partial remission means symptoms of the immediately previous episode are present but full criteria are not met, or there has been a period of less than 2 months without significant symptoms. Full remission requires 2 months with no significant signs or symptoms. Residual symptoms matter clinically because they raise the risk of relapse.`,
    references: [{ source: 'DSM-5-TR', detail: 'Major Depressive Disorder: remission specifiers (in partial remission, in full remission)' }],
  },
  {
    id: 'nce-s-ass-168',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'easy',
    stem: `During a substance use assessment, a client says she drinks "two big glasses of wine" each evening. To record her intake accurately, the counselor converts it into standard drinks. In the United States, one standard drink of table wine is about how much?`,
    options: [
      { id: 'a', text: `12 ounces`, isCorrect: false, rationale: `Twelve ounces is a standard drink of regular beer (about 5% alcohol), not wine.` },
      { id: 'b', text: `8 ounces`, isCorrect: false, rationale: `Eight ounces is roughly a standard drink of malt liquor, not table wine.` },
      { id: 'c', text: `5 ounces`, isCorrect: true, rationale: `About 5 ounces of wine at roughly 12% alcohol contains one standard drink (about 14 grams of pure alcohol).` },
      { id: 'd', text: `1.5 ounces`, isCorrect: false, rationale: `One and a half ounces is a standard drink of 80-proof distilled spirits.` },
    ],
    rationale: `A U.S. standard drink contains about 14 grams of pure alcohol: 12 ounces of regular beer, 5 ounces of table wine, or 1.5 ounces of 80-proof spirits. Clients often pour larger servings than they realize, so a "big glass" of wine may hold two or more standard drinks. Converting reported use into standard drinks makes quantity estimates comparable across assessment sessions and tools.`,
    references: [{ source: 'Sobell & Sobell (Timeline Followback)', detail: 'Recording daily use in standard drink units' }, { source: 'Hays (Assessment)', detail: 'Substance use assessment: quantifying consumption' }],
  },
];
