// tools/nce/seed/intake-6.js — Intake, Assessment and Diagnosis, batch 6
// Hand-authored original items (nce-s-ass-121 … nce-s-ass-144).
module.exports = [
  {
    id: 'nce-s-ass-121',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'validity types',
    difficulty: 'easy',
    stem: 'A state board is building a certification exam for school counselors. A panel of experienced practitioners checks every item against a table of specifications that lists the job tasks and how much weight each should carry. Which type of validity evidence does this process mainly provide?',
    options: [
      { id: 'a', text: 'Face validity', isCorrect: false, rationale: 'Face validity is how the test looks to test takers, not a systematic expert review against a blueprint.' },
      { id: 'b', text: 'Content validity', isCorrect: true, rationale: 'Expert judgment of how well items sample a defined domain, guided by a table of specifications, is content validity evidence.' },
      { id: 'c', text: 'Predictive validity', isCorrect: false, rationale: 'Predictive validity needs a later criterion, such as job performance, correlated with scores.' },
      { id: 'd', text: 'Convergent validity', isCorrect: false, rationale: 'Convergent validity comes from correlations with other measures of the same construct.' },
    ],
    rationale: 'Content validity asks whether a test\'s items adequately and proportionally sample the domain it claims to cover. It is built in during development by writing items to a table of specifications (test blueprint) and having subject-matter experts judge the match. Unlike criterion-related validity, it rests on systematic expert judgment rather than a correlation coefficient.',
    references: [{ source: 'Hays (Assessment)', detail: 'Validity: content validity, test blueprints and expert review' }],
  },
  {
    id: 'nce-s-ass-122',
    domain: 'intake',
    cacrep: 'research',
    topic: 'validity types',
    difficulty: 'medium',
    stem: 'A college counseling center finds that scores on an admissions test correlate .60 with students\' first-year grade point averages. A staff member asks what this validity coefficient means. Which interpretation is accurate?',
    options: [
      { id: 'a', text: 'About 60% of students will have their first-year GPA predicted correctly by the test', isCorrect: false, rationale: 'A correlation is not a hit rate; it does not tell what percentage of individual predictions will be right.' },
      { id: 'b', text: 'About 64% of the differences in first-year GPA are explained by the test scores', isCorrect: false, rationale: 'Sixty-four percent is the variance NOT shared (1 - .36), so this reverses the meaning.' },
      { id: 'c', text: 'The test must have a reliability of .36, since validity is the square of reliability', isCorrect: false, rationale: 'Validity is limited by reliability, but reliability is not found by squaring a validity coefficient.' },
      { id: 'd', text: 'About 36% of the differences in first-year GPA are shared with the test scores', isCorrect: true, rationale: 'Squaring r gives the coefficient of determination: .60 x .60 = .36, or 36% shared variance.' },
    ],
    rationale: 'A validity coefficient is a correlation between test scores and a criterion. Squaring it gives the coefficient of determination, the proportion of criterion variance shared with (accounted for by) the test: .60 squared is .36, so 36% of the variation in GPA is associated with test scores and 64% is not. A coefficient of .60 is strong for a predictor, yet much of the criterion still depends on other factors.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Correlation: coefficient of determination (r squared) as shared variance' }, { source: 'Hays (Assessment)', detail: 'Criterion-related validity: interpreting validity coefficients' }],
  },
  {
    id: 'nce-s-ass-123',
    domain: 'intake',
    cacrep: 'career',
    topic: 'validity types',
    difficulty: 'hard',
    stem: 'Researchers give the Career Decision Scale to undecided first-year students before and after a semester-long career planning course. Indecision scores drop for course participants but not for a similar group that did not take the course. The researchers cite this result in support of the scale. What type of evidence is it?',
    options: [
      { id: 'a', text: 'Construct validity, because scores change in the way the theory of indecision predicts', isCorrect: true, rationale: 'Showing that scores respond to an intervention as the construct predicts is a recognized source of construct validity evidence.' },
      { id: 'b', text: 'Content validity, because the items cover the main reasons students are undecided', isCorrect: false, rationale: 'Content validity is judged from item coverage, not from score changes after an intervention.' },
      { id: 'c', text: 'Poor test-retest reliability, because scores for one group shifted over the semester', isCorrect: false, rationale: 'A change that appears only in the group that received the course reflects real change, not instability of the measure.' },
      { id: 'd', text: 'Concurrent validity, because scores are compared with another test given at the same time', isCorrect: false, rationale: 'No second criterion measure was given; the comparison is between groups over time.' },
    ],
    rationale: 'Construct validity is supported by many kinds of evidence, including experimental studies showing that scores change in theoretically expected ways. If a measure of career indecision drops after a career intervention but stays stable in a comparison group, that pattern fits what the construct predicts. The stable comparison group also argues against the change being measurement error.',
    references: [{ source: 'Hays (Assessment)', detail: 'Construct validity: evidence from intervention and group-difference studies' }, { source: 'Sharf (Career Development Theory)', detail: 'Career decision making and indecision: assessment of indecision' }],
  },
  {
    id: 'nce-s-ass-124',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'hard',
    stem: 'A test developer compares bilingual and monolingual examinees who earned the same total scores on a reading test. On one item, an idiom-based question, bilingual examinees at every total-score level answer correctly far less often than monolingual examinees. What does this finding MOST likely indicate?',
    options: [
      { id: 'a', text: 'The bilingual examinees have lower reading ability than the monolingual examinees', isCorrect: false, rationale: 'The groups were matched on total score, so a general ability difference does not explain the gap on this item.' },
      { id: 'b', text: 'The item discriminates well and should be kept to separate strong and weak readers', isCorrect: false, rationale: 'Discrimination concerns high versus low scorers overall, not differences between matched groups.' },
      { id: 'c', text: 'The item shows differential functioning and may be biased against bilingual examinees', isCorrect: true, rationale: 'When equally able groups perform differently on an item, the item functions differently and should be reviewed for bias.' },
      { id: 'd', text: 'The overall test is invalid for every group, since one of its items has a problem', isCorrect: false, rationale: 'One flagged item calls for review or removal of that item, not rejection of the whole test.' },
    ],
    rationale: 'Differential item functioning (DIF) analysis compares groups who are matched on the overall trait the test measures. If matched groups still differ in their odds of answering an item correctly, something other than the target ability, here familiarity with an idiom, is influencing the item. Flagged items are reviewed and revised or dropped, which is a key step in making a test culturally fair.',
    references: [{ source: 'Hays (Assessment)', detail: 'Test bias: item bias and differential item functioning' }],
  },
  {
    id: 'nce-s-ass-125',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'medium',
    stem: 'A counselor chooses a nonverbal matrix-reasoning test to estimate the problem-solving ability of a 40-year-old client who recently arrived from Eritrea and speaks little English. A colleague says the test is "culture-free," so cultural factors no longer need to be considered. How should the counselor respond?',
    options: [
      { id: 'a', text: 'Nonverbal tests lower language demands but still reflect cultural and schooling experience', isCorrect: true, rationale: 'Culture-fair tests reduce, but do not remove, the influence of familiarity with testing, abstract figures, and timed tasks.' },
      { id: 'b', text: 'Nonverbal tests are fully culture-free, so the score can be read like any other client\'s', isCorrect: false, rationale: 'No test is culture-free; experience with test formats and schooling still affects performance.' },
      { id: 'c', text: 'Nonverbal tests are unsuitable for adults, so a verbal test given in English is better here', isCorrect: false, rationale: 'An English verbal test would mainly measure English proficiency for this client.' },
      { id: 'd', text: 'Nonverbal tests are valid only if the client was born in the country where norms were set', isCorrect: false, rationale: 'Norm fit matters, but birthplace alone does not decide validity, and the test can still be used with care.' },
    ],
    rationale: 'Culture-fair or culture-reduced tests, such as nonverbal matrix tasks, lessen reliance on language and specific cultural knowledge. They are not culture-free: familiarity with paper-and-pencil formats, abstract designs, formal schooling, and working against time all affect scores. Counselors still consider the client\'s background and the norm group when interpreting results.',
    references: [{ source: 'Hays (Assessment)', detail: 'Culturally fair assessment: culture-reduced (culture-fair) versus culture-free tests' }],
  },
  {
    id: 'nce-s-ass-126',
    domain: 'intake',
    cacrep: 'social_cultural',
    topic: 'culturally fair assessment',
    difficulty: 'medium',
    stem: 'A counselor plans to give a standardized personality inventory to a 33-year-old client who moved from Mexico a year ago, speaks mostly Spanish at home, and is comfortable with conversational English at work. What should the counselor do BEFORE selecting the form and norms to use?',
    options: [
      { id: 'a', text: 'Give the English form, since conversational English at work shows enough proficiency', isCorrect: false, rationale: 'Workplace conversation does not show the reading level and fluency needed for a long inventory.' },
      { id: 'b', text: 'Skip standardized testing, since no inventory can be fairly used with recent immigrants', isCorrect: false, rationale: 'Many inventories have translated forms and research with diverse groups; careful selection is the answer.' },
      { id: 'c', text: 'Ask a family member to read each item aloud in Spanish while the client gives answers', isCorrect: false, rationale: 'Informal oral translation by a relative changes standard conditions and may affect privacy and honesty.' },
      { id: 'd', text: 'Assess the client\'s acculturation and language dominance to guide the form and norms used', isCorrect: true, rationale: 'Knowing acculturation and preferred language helps the counselor pick an appropriate version and interpret scores in context.' },
    ],
    rationale: 'Acculturation and language dominance affect how clients understand items and how well a norm group represents them. Assessing them first, informally or with an acculturation measure, helps the counselor decide whether a translated and validated form is needed and how cautiously to interpret results. The ACA Code asks counselors to consider culture when selecting and interpreting tests.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section E: Evaluation, Assessment, and Interpretation — multicultural issues and diversity in assessment' }, { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Acculturation and culturally appropriate assessment' }],
  },
  {
    id: 'nce-s-ass-127',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'medium',
    stem: 'With a signed release, a counselor receives hospital records from four years ago for a 36-year-old client. The discharge summary lists borderline personality disorder, but the client says that diagnosis "never fit" and was made during a single crisis admission. How should the counselor use this record?',
    options: [
      { id: 'a', text: 'Adopt the prior diagnosis so the client\'s records stay consistent across providers', isCorrect: false, rationale: 'Copying a prior diagnosis without assessment can carry forward an error.' },
      { id: 'b', text: 'Treat it as one source of data and test it against a current, independent assessment', isCorrect: true, rationale: 'Records inform the picture, but the counselor reaches a diagnosis from their own current evaluation.' },
      { id: 'c', text: 'Set the record aside, since the client disagrees with it and it is four years old', isCorrect: false, rationale: 'Older records can still hold useful history about symptoms, risk, and prior treatment.' },
      { id: 'd', text: 'Ask the hospital to remove the diagnosis before the counselor completes an assessment', isCorrect: false, rationale: 'The counselor has no basis to challenge the record before doing their own evaluation.' },
    ],
    rationale: 'Prior records are valuable collateral data, offering history of symptoms, risk, and treatment response. They are also snapshots taken in a particular context, and a diagnosis made during one crisis admission may not hold over time. Counselors weigh records alongside the interview and other sources rather than adopting or dismissing a prior diagnosis automatically.',
    references: [{ source: 'Hays (Assessment)', detail: 'Clinical assessment: integrating records and collateral sources with interview data' }],
  },
  {
    id: 'nce-s-ass-128',
    domain: 'intake',
    cacrep: 'professional_orientation',
    topic: 'collateral information and records',
    difficulty: 'easy',
    stem: 'During intake for depression, a 25-year-old client declines to sign a release that would let the counselor speak with her mother. She is not at imminent risk and is otherwise engaged in the assessment. What should the counselor do?',
    options: [
      { id: 'a', text: 'Call the mother anyway, since family input is needed for a complete diagnostic picture', isCorrect: false, rationale: 'Contacting a third party without consent breaches confidentiality when no exception applies.' },
      { id: 'b', text: 'Pause the assessment until the client agrees to sign the release for her mother', isCorrect: false, rationale: 'Making services depend on a release pressures the client and is not needed for assessment.' },
      { id: 'c', text: 'Respect her decision, explore her concerns, and continue the assessment without it', isCorrect: true, rationale: 'An adult client controls the release of her information; the counselor can still assess well from other data.' },
      { id: 'd', text: 'Contact the mother only for history, since this does not reveal what was said in session', isCorrect: false, rationale: 'Even confirming that a person is a client discloses confidential information.' },
    ],
    rationale: 'Collateral contacts with family or other providers require the client\'s informed, written consent unless a recognized exception to confidentiality applies. When an adult client declines, the counselor respects that choice, may gently explore the reasons, documents the decision, and proceeds with the information available. The client can revisit the release later.',
    references: [{ source: 'ACA Code of Ethics', detail: 'Section B: Confidentiality and Privacy — respecting client rights; consent to disclose information' }],
  },
  {
    id: 'nce-s-ass-129',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'collateral information and records',
    difficulty: 'medium',
    stem: 'A counselor is assessing a 10-year-old for a court-ordered custody evaluation. The father, who is seeking sole custody, describes the child as severely aggressive at home. The mother and the child\'s teacher describe only mild, occasional outbursts. How should the counselor weigh these reports?',
    options: [
      { id: 'a', text: 'Rely most on the father\'s account, since a parent describing more problems is more cautious', isCorrect: false, rationale: 'Severity of a report does not make it more accurate, especially when the informant has a stake in the outcome.' },
      { id: 'b', text: 'Rely on the teacher\'s report alone, since school staff have no reason to be inaccurate', isCorrect: false, rationale: 'Teachers see one setting; a single source is not enough even when it seems neutral.' },
      { id: 'c', text: 'Average the three reports to get one score that reflects the child\'s typical behavior', isCorrect: false, rationale: 'Averaging hides real differences across settings and ignores informant motivation.' },
      { id: 'd', text: 'Weigh each informant\'s setting and motives, and gather more data before concluding', isCorrect: true, rationale: 'Informant stake and setting both affect reports, so the counselor integrates sources and seeks corroboration.' },
    ],
    rationale: 'Collateral reports are shaped by the informant\'s vantage point and by what they stand to gain or lose. In an evaluation tied to custody, a parent\'s report may be influenced by the dispute, so the counselor weighs it alongside other informants, records, and direct observation. Discrepancies are treated as data to explain, not averaged away.',
    references: [{ source: 'Hays (Assessment)', detail: 'Collateral sources: informant bias and integrating multiple sources of information' }],
  },
  {
    id: 'nce-s-ass-130',
    domain: 'intake',
    cacrep: 'career',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'medium',
    stem: 'On the Strong Interest Inventory, a 21-year-old client\'s Investigative General Occupational Theme has a standard score of 62. She asks whether this means she "got 62 percent." Which explanation is accurate?',
    options: [
      { id: 'a', text: 'It means she marked "Like" on about 62% of the items in the Investigative theme', isCorrect: false, rationale: 'The theme score is a converted standard score, not the share of items she endorsed.' },
      { id: 'b', text: 'It means her interests fall at the 62nd percentile compared with other college students', isCorrect: false, rationale: 'A standard score of 62 on this scale is well above the 62nd percentile.' },
      { id: 'c', text: 'It is a standard score, a bit over one SD above the mean of a broad sample of adults', isCorrect: true, rationale: 'Theme scores have a mean of 50 and SD of 10 in a general reference sample, so 62 is 1.2 SD above the mean.' },
      { id: 'd', text: 'It means she has about a 62% chance of succeeding in an investigative type of career', isCorrect: false, rationale: 'Interest scores describe likes and dislikes, not chances of success.' },
    ],
    rationale: 'The Strong Interest Inventory reports General Occupational Theme scores as standard scores with a mean of 50 and a standard deviation of 10, based on a general reference sample of employed adults. Interpretation is norm-referenced: a score of 62 shows stronger Investigative interests than most people in that sample. It is not a percentage correct, a percentile, or a prediction of success.',
    references: [{ source: 'Hays (Assessment)', detail: 'Strong Interest Inventory: General Occupational Themes reported as standard scores (mean 50, SD 10)' }],
  },
  {
    id: 'nce-s-ass-131',
    domain: 'intake',
    cacrep: 'career',
    topic: 'intelligence and achievement tests',
    difficulty: 'easy',
    stem: 'A 19-year-old\'s Strong Interest Inventory profile shows a high score on the Physician occupational scale. He asks, "So this proves I can make it through medical school?" Which response is BEST?',
    options: [
      { id: 'a', text: 'Interest scores show similar likes, not ability; grades and test scores speak to ability', isCorrect: true, rationale: 'Interest inventories compare likes and dislikes with satisfied workers; ability evidence comes from achievement and aptitude data.' },
      { id: 'b', text: 'A high occupational score is a strong sign that he has the ability to finish the training', isCorrect: false, rationale: 'Interest scores do not measure aptitude or achievement, so they cannot predict academic success.' },
      { id: 'c', text: 'He should take the inventory again, since a single result cannot be trusted for planning', isCorrect: false, rationale: 'Retesting does not change what the inventory measures; the issue is interest versus ability.' },
      { id: 'd', text: 'A high score means he should drop other options and focus only on applying to medicine', isCorrect: false, rationale: 'One scale should open exploration, not close off other options.' },
    ],
    rationale: 'Interest inventories such as the Strong describe how closely a person\'s likes and dislikes match those of people satisfied in an occupation. They do not measure intelligence, aptitude, or achievement. Career counselors combine interest results with ability evidence such as grades, achievement tests, and admissions test scores before judging the fit of a demanding path.',
    references: [{ source: 'Hays (Assessment)', detail: 'Career assessment: interest inventories versus aptitude and achievement measures' }],
  },
  {
    id: 'nce-s-ass-132',
    domain: 'intake',
    cacrep: 'research',
    topic: 'reliability types',
    difficulty: 'hard',
    stem: 'A 10-item self-efficacy scale has a reliability coefficient of .50. The developer adds 20 new items of the same kind and quality, for 30 items in all. According to the Spearman-Brown formula, what is the estimated reliability of the longer scale?',
    options: [
      { id: 'a', text: '.67', isCorrect: false, rationale: 'This is the result for doubling the test (2 x .50 / 1.50), not tripling it.' },
      { id: 'b', text: '.75', isCorrect: true, rationale: 'With k = 3: (3 x .50) / (1 + 2 x .50) = 1.50 / 2.00 = .75.' },
      { id: 'c', text: '.90', isCorrect: false, rationale: 'Reliability rises with length but with diminishing returns; .90 overstates the gain.' },
      { id: 'd', text: '1.50', isCorrect: false, rationale: 'Simply multiplying by 3 gives an impossible value; reliability cannot exceed 1.0.' },
    ],
    rationale: 'The Spearman-Brown formula estimates reliability when test length changes by a factor of k: r_new = k r / (1 + (k - 1) r). Tripling a scale with reliability .50 gives 1.50 / 2.00 = .75. Adding comparable items raises reliability, but each added block helps less than the one before.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Reliability: Spearman-Brown prophecy formula and test length' }],
  },
  {
    id: 'nce-s-ass-133',
    domain: 'intake',
    cacrep: 'research',
    topic: 'norm- vs criterion-referenced tests',
    difficulty: 'medium',
    stem: 'A seventh grader answers 42 of 60 items correctly on a reading test. The score report lists his percentile rank as 85. His parent asks what the two numbers mean. Which statement is accurate?',
    options: [
      { id: 'a', text: 'He answered 85% of the items correctly, which placed him at the 70th percentile', isCorrect: false, rationale: 'This swaps the two numbers; 42 of 60 is 70%, and the percentile rank is 85.' },
      { id: 'b', text: 'He answered 70% of items correctly, so he scored lower than about 85% of his peers', isCorrect: false, rationale: 'A percentile rank of 85 means he scored higher than about 85% of the norm group, not lower.' },
      { id: 'c', text: 'He answered 85% of the items correctly, and about 70% of his peers did at least as well', isCorrect: false, rationale: 'The percentage correct is 42 / 60 = 70%, and percentile rank refers to students scoring below him.' },
      { id: 'd', text: 'He answered 70% of items correctly and scored higher than about 85% of the norm group', isCorrect: true, rationale: '42 / 60 = .70, a percentage correct; a percentile rank of 85 means he outscored about 85% of the norm group.' },
    ],
    rationale: 'Percentage correct (42 / 60 = 70%) is an absolute, criterion-style figure about how much of the content a student mastered. A percentile rank is a norm-referenced figure: the percentage of the norm group scoring below the student. A difficult test can produce a modest percentage correct and a high percentile rank, as here.',
    references: [{ source: 'Hays (Assessment)', detail: 'Score interpretation: percentile ranks versus percentage correct' }],
  },
  {
    id: 'nce-s-ass-134',
    domain: 'intake',
    cacrep: 'human_growth',
    topic: 'screening instruments (PHQ-9, GAD-7, AUDIT, CAGE)',
    difficulty: 'medium',
    stem: 'At a pediatric clinic, a parent completes the M-CHAT-R/F, an autism screening checklist, for a 20-month-old. The result falls in the medium-risk range. The parent asks the counselor whether this means the child has autism. What is the BEST response?',
    options: [
      { id: 'a', text: 'Yes; a medium-risk result on this checklist is enough to make the autism diagnosis', isCorrect: false, rationale: 'A screening result flags possible risk; diagnosis requires a comprehensive evaluation.' },
      { id: 'b', text: 'No; screening this young is unreliable, so wait until the child is in school to retest', isCorrect: false, rationale: 'The tool is designed for toddlers, and waiting would delay early intervention if needed.' },
      { id: 'c', text: 'Not yet; follow-up questions come next, then a full evaluation if concerns remain', isCorrect: true, rationale: 'A screen that flags concerns leads to follow-up and, if still positive, referral for diagnostic evaluation.' },
      { id: 'd', text: 'No; the result is a false positive, since most toddlers this age show these behaviors', isCorrect: false, rationale: 'A screen cannot be dismissed without follow-up; doing so could delay early identification.' },
    ],
    rationale: 'Developmental screeners such as the M-CHAT-R/F identify toddlers who may need further assessment; they do not diagnose. A result that raises concern leads to the structured follow-up questions and, if concern persists, referral for a comprehensive diagnostic evaluation. Early identification matters because early intervention can improve developmental outcomes.',
    references: [{ source: 'Hays (Assessment)', detail: 'Screening versus diagnostic assessment: positive screens lead to follow-up and comprehensive evaluation' }, { source: 'Berk (Development Through the Lifespan)', detail: 'Early childhood development: autism and the value of early identification' }],
  },
  {
    id: 'nce-s-ass-135',
    domain: 'intake',
    cacrep: 'helping_relationships',
    topic: 'intake interview structure',
    difficulty: 'easy',
    stem: 'With about ten minutes left in a first intake session, a counselor has gathered the presenting concern, history, and a risk screen for a 50-year-old client. What is the MOST useful way to close the intake?',
    options: [
      { id: 'a', text: 'Summarize the main concerns, check accuracy, and agree on next steps and questions', isCorrect: true, rationale: 'A closing summary confirms shared understanding and sets a clear, collaborative plan.' },
      { id: 'b', text: 'Use the remaining time to begin a new topic, such as the client\'s early childhood', isCorrect: false, rationale: 'Opening new, deep material at the end leaves no time to process it.' },
      { id: 'c', text: 'Give the client the formal diagnosis and a full treatment plan to sign before leaving', isCorrect: false, rationale: 'Diagnosis and planning are shared and collaborative; presenting them as finished skips client input.' },
      { id: 'd', text: 'End on time with no summary, since the next session will review all of this material', isCorrect: false, rationale: 'Ending without a summary misses a chance to confirm understanding and build the alliance.' },
    ],
    rationale: 'The close of an intake ties the session together. The counselor summarizes key concerns and strengths, checks whether the summary fits the client\'s view, and agrees on next steps such as scheduling, referrals, or homework, inviting the client\'s questions. This structure supports the working alliance and makes the plan collaborative.',
    references: [{ source: 'Ivey et al. (Intentional Interviewing)', detail: 'Five-stage interview structure: summarizing and planning at the end of the session' }],
  },
  {
    id: 'nce-s-ass-136',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'mental status examination',
    difficulty: 'easy',
    stem: 'A 29-year-old client speaks rapidly and is hard to interrupt. She says, "Your plant is green, green is for go, go to the races, horses need water, I should start a water company." How should the counselor record this in the mental status examination?',
    options: [
      { id: 'a', text: 'Circumstantiality', isCorrect: false, rationale: 'Circumstantial speech includes many details but eventually reaches the original point.' },
      { id: 'b', text: 'Flight of ideas', isCorrect: true, rationale: 'Rapid jumps from idea to idea, linked by word play or chance associations, describe flight of ideas.' },
      { id: 'c', text: 'Thought blocking', isCorrect: false, rationale: 'Thought blocking is a sudden halt in the train of thought, not a rapid stream.' },
      { id: 'd', text: 'Perseveration', isCorrect: false, rationale: 'Perseveration is repeating the same idea or response, not jumping between ideas.' },
    ],
    rationale: 'Flight of ideas is a thought process finding: an accelerated flow of ideas with abrupt shifts, where connections are based on sounds, word play, or distracting stimuli. It often occurs with pressured speech and is common in manic episodes. Unlike loosened associations, the links between ideas can usually be followed.',
    references: [{ source: 'Hays (Assessment)', detail: 'Mental status examination: thought process (flight of ideas, circumstantiality, blocking)' }, { source: 'DSM-5-TR', detail: 'Manic episode, Criterion B: flight of ideas or subjective experience that thoughts are racing' }],
  },
  {
    id: 'nce-s-ass-137',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'suicide and violence risk assessment',
    difficulty: 'hard',
    stem: 'Using the Columbia Suicide Severity Rating Scale (C-SSRS), a counselor asks about recent behavior. A 44-year-old client says that last week he poured a bottle of pills into his hand, intending to die, then put them back on his own before swallowing any. No one else was present. How is this behavior classified?',
    options: [
      { id: 'a', text: 'An interrupted attempt, since the act was stopped before any pills were swallowed', isCorrect: false, rationale: 'An interrupted attempt is stopped by an outside person or circumstance, which did not occur here.' },
      { id: 'b', text: 'Non-suicidal self-injurious behavior, since no physical injury took place at all', isCorrect: false, rationale: 'He reported intent to die, so the behavior is suicidal, not non-suicidal self-injury.' },
      { id: 'c', text: 'Suicidal ideation only, since the client did not take any action that could harm him', isCorrect: false, rationale: 'Pouring out pills to take them is a behavior, not only a thought.' },
      { id: 'd', text: 'An aborted or self-interrupted attempt, since he stopped himself before taking any pills', isCorrect: true, rationale: 'The C-SSRS defines an aborted or self-interrupted attempt as beginning steps toward an attempt and stopping oneself.' },
    ],
    rationale: 'The C-SSRS separates suicidal behaviors into actual attempts, interrupted attempts (stopped by an outside circumstance), aborted or self-interrupted attempts (the person stops themselves), and preparatory acts such as gathering means or writing a note. Each counts as suicidal behavior and raises concern. Precise classification guides risk formulation and safety planning.',
    references: [{ source: 'C-SSRS', detail: 'Suicidal behavior section: actual, interrupted, and aborted or self-interrupted attempts; preparatory acts' }],
  },
  {
    id: 'nce-s-ass-138',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'DSM-5-TR diagnostic structure and specifiers',
    difficulty: 'medium',
    stem: 'A 37-year-old outpatient comes to an agency seeking treatment for alcohol use disorder, which is the focus of today\'s visit. During the intake, the counselor also confirms a long-standing generalized anxiety disorder. Under DSM-5-TR recording guidance, which diagnosis is generally listed first?',
    options: [
      { id: 'a', text: 'Generalized anxiety disorder, because the condition with the earliest onset is listed first', isCorrect: false, rationale: 'Order is not set by which disorder began first.' },
      { id: 'b', text: 'Whichever diagnosis has the lowest ICD-10-CM code, so that the record is in code order', isCorrect: false, rationale: 'Diagnoses are not ordered numerically by code.' },
      { id: 'c', text: 'Alcohol use disorder, as the reason for the visit is generally listed first in outpatient care', isCorrect: true, rationale: 'In outpatient settings, the condition chiefly responsible for the visit is generally listed first.' },
      { id: 'd', text: 'Generalized anxiety disorder, because anxiety disorders come before substance use disorders', isCorrect: false, rationale: 'DSM-5-TR chapter order does not set the order of a client\'s diagnoses.' },
    ],
    rationale: 'When a person has more than one diagnosis, DSM-5-TR asks clinicians to list the principal diagnosis (inpatient) or the reason for visit (outpatient) first. The reason for visit is the condition chiefly responsible for the services received. Additional diagnoses are listed after it, and the other conditions still guide care.',
    references: [{ source: 'DSM-5-TR', detail: 'Use of the Manual: principal diagnosis and reason for visit' }],
  },
  {
    id: 'nce-s-ass-139',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'differential diagnosis',
    difficulty: 'medium',
    stem: 'For the past year, a 27-year-old accountant has had sudden surges of pounding heart, shaking, and breathlessness, but only when asked to present in meetings or to eat with coworkers. He fears they will see him as incompetent and now avoids team lunches. He has had no unexpected attacks. Which diagnosis BEST fits?',
    options: [
      { id: 'a', text: 'Social anxiety disorder', isCorrect: true, rationale: 'Fear of negative evaluation in social and performance situations, with avoidance for 6 months or more, fits social anxiety disorder.' },
      { id: 'b', text: 'Panic disorder', isCorrect: false, rationale: 'Panic disorder requires recurrent unexpected attacks; his attacks occur only in feared social situations.' },
      { id: 'c', text: 'Agoraphobia', isCorrect: false, rationale: 'Agoraphobic fear centers on escape or help being hard to get in places such as crowds or transit.' },
      { id: 'd', text: 'Generalized anxiety disorder', isCorrect: false, rationale: 'GAD involves broad, hard-to-control worry across many areas, not fear focused on scrutiny.' },
    ],
    rationale: 'Panic attacks can occur within many disorders. When attacks happen only in social or performance situations and are driven by fear of being judged, the diagnosis is social anxiety disorder rather than panic disorder, which requires recurrent unexpected attacks. The panic attack specifier can be added to note the attacks.',
    references: [{ source: 'DSM-5-TR', detail: 'Social Anxiety Disorder: criteria and differential diagnosis (panic disorder); panic attack specifier' }],
  },
  {
    id: 'nce-s-ass-140',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'standard error of measurement',
    difficulty: 'hard',
    stem: 'An ability test has a standard deviation of 15. Its manual reports a reliability of .84 for 6- and 7-year-olds and .96 for adults. A 7-year-old earns a score of 100. Within which range does the child\'s true score fall with about 68% confidence?',
    options: [
      { id: 'a', text: '97 to 103', isCorrect: false, rationale: 'This uses the adult SEM of 3 (15 x .20), which does not apply to a 7-year-old.' },
      { id: 'b', text: '94 to 106', isCorrect: true, rationale: 'SEM = 15 x the square root of (1 - .84) = 15 x .40 = 6; 100 plus or minus 6 gives 94 to 106.' },
      { id: 'c', text: '88 to 112', isCorrect: false, rationale: 'Plus or minus 12 is about a 95% band (2 SEMs), not 68%.' },
      { id: 'd', text: '84 to 116', isCorrect: false, rationale: 'This treats 1 - .84 as 16 points instead of multiplying 15 by its square root.' },
    ],
    rationale: 'The standard error of measurement is SD x the square root of (1 - r). Because reliability often differs by age, the counselor uses the coefficient for the client\'s own group: 15 x the square root of .16 = 15 x .40 = 6. One SEM on either side of the obtained score gives a 68% confidence band of 94 to 106.',
    references: [{ source: 'Hays (Assessment)', detail: 'Standard error of measurement: computation and confidence bands; reliability by age group' }],
  },
  {
    id: 'nce-s-ass-141',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'personality inventories (MMPI-3, NEO-PI)',
    difficulty: 'medium',
    stem: 'A counselor at a community mental health center is considering the MMPI-3 for a 45-year-old client with a complex presentation. Which description of the MMPI-3 is accurate?',
    options: [
      { id: 'a', text: 'A projective test in which the client describes what they see in ambiguous visual images', isCorrect: false, rationale: 'The MMPI-3 is an objective self-report inventory, not a projective test.' },
      { id: 'b', text: 'An inventory normed for adolescents aged 14 to 18 that cannot be used with adult clients', isCorrect: false, rationale: 'Adolescent versions are the MMPI-A and MMPI-A-RF; the MMPI-3 is for adults.' },
      { id: 'c', text: 'A measure of the five-factor model that yields scores for openness and agreeableness', isCorrect: false, rationale: 'The five-factor domains are measured by the NEO inventories.' },
      { id: 'd', text: 'A true/false self-report inventory for adults that includes scales checking response style', isCorrect: true, rationale: 'The MMPI-3 is an adult true/false inventory with validity scales for non-responding, inconsistency, over- and underreporting.' },
    ],
    rationale: 'The MMPI-3 is the current adult version of the MMPI, a broad objective self-report inventory answered true or false. Its validity scales detect non-responding, inconsistent responding, and over- or underreporting before substantive scales are interpreted. Adolescents take the MMPI-A or MMPI-A-RF, and five-factor traits are assessed with instruments such as the NEO-PI-3.',
    references: [{ source: 'Hays (Assessment)', detail: 'Personality assessment: MMPI family of instruments and validity scales' }],
  },
  {
    id: 'nce-s-ass-142',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'projective tests',
    difficulty: 'easy',
    stem: 'A counselor considering a projective technique asks a supervisor what main advantage is usually claimed for projective tests compared with self-report inventories. What is the BEST answer?',
    options: [
      { id: 'a', text: 'They have higher reliability because scoring rules leave no room for judgment', isCorrect: false, rationale: 'Projective tests typically have lower reliability, partly because scoring involves judgment.' },
      { id: 'b', text: 'They are faster to give and score, making them well suited to group screening', isCorrect: false, rationale: 'Most projective techniques are individually given and time-consuming to score.' },
      { id: 'c', text: 'Their purpose is less obvious, so responses are harder to shape deliberately', isCorrect: true, rationale: 'Ambiguous tasks make it harder for clients to tell what a "good" answer is, reducing deliberate faking.' },
      { id: 'd', text: 'They yield precise diagnoses that match DSM-5-TR criteria for most disorders', isCorrect: false, rationale: 'Projective results generate hypotheses; they do not map directly to diagnostic criteria.' },
    ],
    rationale: 'Projective techniques present ambiguous stimuli, based on the idea that people project their needs and conflicts into their responses. Because the purpose is less transparent, clients have a harder time presenting themselves in a planned way. The trade-offs are lower reliability, scoring that depends on examiner judgment, and weaker validity evidence for many uses.',
    references: [{ source: 'Hays (Assessment)', detail: 'Projective assessment: projective hypothesis, advantages and limitations' }],
  },
  {
    id: 'nce-s-ass-143',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'substance use assessment',
    difficulty: 'medium',
    stem: 'An outpatient program wants a semi-structured interview that rates the severity of an adult client\'s problems across medical status, employment, alcohol use, drug use, legal status, family and social relationships, and psychiatric status. Which instrument fits this purpose?',
    options: [
      { id: 'a', text: 'Addiction Severity Index', isCorrect: true, rationale: 'The ASI is a semi-structured interview rating problem severity across seven life areas.' },
      { id: 'b', text: 'CAGE questionnaire', isCorrect: false, rationale: 'The CAGE is a four-question alcohol screen, not a multi-area severity interview.' },
      { id: 'c', text: 'CRAFFT screening tool', isCorrect: false, rationale: 'The CRAFFT is a brief screen developed for adolescents.' },
      { id: 'd', text: 'AUDIT-C screening items', isCorrect: false, rationale: 'The AUDIT-C is three consumption questions about alcohol only.' },
    ],
    rationale: 'The Addiction Severity Index (ASI) is a widely used semi-structured interview for adults that assesses seven areas: medical, employment and support, alcohol, drug, legal, family and social, and psychiatric. Its multi-area profile helps with treatment planning and tracking change. Brief screens such as the CAGE, AUDIT-C, and CRAFFT identify possible problems but do not map severity across life areas.',
    references: [{ source: 'Hays (Assessment)', detail: 'Substance use assessment: Addiction Severity Index and brief screening instruments' }],
  },
  {
    id: 'nce-s-ass-144',
    domain: 'intake',
    cacrep: 'assessment',
    topic: 'biopsychosocial history',
    difficulty: 'hard',
    stem: 'A 48-year-old client with no psychiatric history reports two weeks of little sleep, irritability, racing thoughts, and unusual energy. In the medical section of the biopsychosocial history, she mentions starting a high-dose course of prednisone for a severe asthma flare about three weeks ago. What should the counselor do?',
    options: [
      { id: 'a', text: 'Diagnose bipolar I disorder, since her symptoms meet the criteria for a manic episode', isCorrect: false, rationale: 'Symptoms caused by a medication do not count toward bipolar I disorder.' },
      { id: 'b', text: 'Record the timeline and coordinate with her prescriber, since the drug may be the cause', isCorrect: true, rationale: 'Corticosteroids can induce manic-like symptoms; the timing calls for medical consultation.' },
      { id: 'c', text: 'Advise her to stop taking the prednisone right away, since it is causing her symptoms', isCorrect: false, rationale: 'Medication changes are a prescriber\'s decision; stopping corticosteroids abruptly can be unsafe.' },
      { id: 'd', text: 'Leave the medication out of the assessment, since it is unrelated to her mental health', isCorrect: false, rationale: 'Medication history is central to the biopsychosocial assessment and differential diagnosis.' },
    ],
    rationale: 'The medical part of the biopsychosocial history includes current medications and recent changes, because many medications affect mood and behavior. DSM-5-TR lists corticosteroids among medications that can induce bipolar-type symptoms, and an episode that begins after starting such a drug is diagnosed as substance/medication-induced unless evidence shows otherwise. The counselor documents the timing and coordinates with the prescriber rather than giving medical advice.',
    references: [{ source: 'DSM-5-TR', detail: 'Substance/Medication-Induced Bipolar and Related Disorder: medications such as corticosteroids' }],
  },
];
