// tools/nce/seed/treatment-6.js — Treatment Planning, batch 6
// Hand-authored original items (nce-s-trt-086 … nce-s-trt-102).
module.exports = [
  {
    id: 'nce-s-trt-086',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'medium',
    stem: 'A 37-year-old client has recovered from her second major depressive episode after 14 sessions of cognitive behavioral therapy. As discharge nears, she says, "What if the depression sneaks up on me again?" Which aftercare step BEST addresses her concern?',
    options: [
      { id: 'a', text: 'Reassure her that people who finish CBT seldom have another depressive episode afterward', isCorrect: false, rationale: 'This is inaccurate; depression often recurs, especially after more than one episode, and false reassurance leaves her unprepared.' },
      { id: 'b', text: 'Keep weekly sessions going without an end date so that any return of symptoms is caught', isCorrect: false, rationale: 'Open-ended weekly care is not clinically indicated once goals are met and can undercut her confidence in her own skills.' },
      { id: 'c', text: 'Write a plan with her that lists early warning signs and the steps she will take if they appear', isCorrect: true, rationale: 'Preparing for setbacks with a written plan of personal warning signs and coping steps is a core relapse prevention task before termination.' },
      { id: 'd', text: 'Ask her to contact the agency only if she begins to have thoughts of suicide after discharge', isCorrect: false, rationale: 'Waiting for suicidal thoughts sets the bar for returning far too high; earlier warning signs should prompt action.' },
    ],
    rationale: 'In cognitive behavioral therapy, relapse prevention is built into the final phase of treatment. The counselor helps the client anticipate setbacks, identify her own early warning signs and write down the skills and supports she will use, including when to seek a booster session. This turns the fear of recurrence into a concrete plan she can act on.',
    references: [{ source: 'J. Beck (CBT: Basics and Beyond)', detail: 'Termination and relapse prevention: preparing for setbacks and planning for early warning signs' }],
  },
  {
    id: 'nce-s-trt-087',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'easy',
    stem: 'A 24-year-old client in treatment for anxiety has missed three sessions in a row and has not answered phone calls. Agency policy allows the case to be closed. What should the counselor do before closing the case?',
    options: [
      { id: 'a', text: 'Send a caring outreach letter that invites return and lists referral and crisis resources', isCorrect: true, rationale: 'Outreach that leaves the door open and offers other resources avoids abandonment and supports continuity of care.' },
      { id: 'b', text: 'Close the case without contact, since the client has chosen to stop coming to counseling', isCorrect: false, rationale: 'Closing with no outreach risks abandonment; the reason for the absences is unknown and the client may still need help.' },
      { id: 'c', text: 'Keep the case open with weekly calls until the client agrees to come back for a final session', isCorrect: false, rationale: 'Repeated pursuit can feel intrusive and ignores the client\'s choice; one clear outreach with resources is the standard.' },
      { id: 'd', text: 'Ask the client\'s emergency contact to find out why the client has stopped coming to sessions', isCorrect: false, rationale: 'Contacting a third party about attendance without consent breaches confidentiality when there is no emergency.' },
    ],
    rationale: 'When a client stops attending, the counselor should try to reach them, invite a return or a closing session, and offer referrals and crisis resources before the case is closed. The ACA Code asks counselors to provide pretermination counseling and recommend other providers when needed, so that ending services does not amount to abandonment. The outreach attempt and closing summary are documented in the record.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' },
      { source: 'Wiger (Documentation)', detail: 'Termination documentation: discharge reason, outreach attempts and referrals offered' },
    ],
  },
  {
    id: 'nce-s-trt-088',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'safety planning',
    difficulty: 'medium',
    stem: 'While building a safety plan, a 32-year-old client names her older brother as the only person she would call for help in a crisis. She adds that he works nights and seldom answers his phone after 10 p.m., when her urges are strongest. What should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Accept the brother as her contact, since she trusts him and chose him on her own', isCorrect: false, rationale: 'Her trust matters, but leaving a known barrier unaddressed makes this step likely to fail when she needs it most.' },
      { id: 'b', text: 'Move straight to the step on making her home safer, since this step will not work', isCorrect: false, rationale: 'Skipping the step gives up on social support; the barrier can be solved by adding contacts who are reachable.' },
      { id: 'c', text: 'Tell her to call 911 instead of family members whenever her urges begin late at night', isCorrect: false, rationale: 'Emergency services belong in the plan for imminent danger, but they do not replace the social support step.' },
      { id: 'd', text: 'Explore this barrier with her and identify other people she could reach late at night', isCorrect: true, rationale: 'Safety planning includes checking how likely each step is to be used and problem-solving obstacles, such as an unreachable contact.' },
    ],
    rationale: 'In the Safety Planning Intervention, the counselor asks how likely the client is to use each step and works through any obstacles. A contact who cannot be reached at the hours of highest risk is a barrier that should be solved, for example by adding other people or a crisis line for those hours. A plan that fits the client\'s real life is more likely to be used.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Assessing the likelihood of using each step and problem-solving barriers to use' }],
  },
  {
    id: 'nce-s-trt-089',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'safety planning',
    difficulty: 'hard',
    stem: 'A 66-year-old widower completing a Stanley-Brown safety plan says, "When the dark thoughts start, I walk to the diner and chat with the regulars about baseball. I don\'t tell them how I feel, but it takes my mind off things." In which step of the safety plan does this strategy BEST belong?',
    options: [
      { id: 'a', text: 'People I can ask for help', isCorrect: false, rationale: 'This step lists people the client tells about the crisis and asks for help; he does not disclose his distress at the diner.' },
      { id: 'b', text: 'Social settings for distraction', isCorrect: true, rationale: 'Going to a social setting to take his mind off things, without disclosing the crisis, fits the distraction step.' },
      { id: 'c', text: 'Internal coping strategies on my own', isCorrect: false, rationale: 'Internal strategies are things he does on his own without contacting others, such as a hobby at home.' },
      { id: 'd', text: 'Warning signs that a crisis is coming', isCorrect: false, rationale: 'Warning signs are the thoughts, moods and situations that signal a crisis, not the actions taken in response.' },
    ],
    rationale: 'The Stanley-Brown plan moves from warning signs, to internal coping strategies, to people and social settings that provide distraction, to people the client can ask for help, to professionals and crisis services, and finally to making the environment safe. The distraction step uses social contact without disclosing the crisis, while the help step involves telling someone that he is struggling. His diner visits fit the distraction step.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Step 3, people and social settings that provide distraction, versus Step 4, people whom I can ask for help' }],
  },
  {
    id: 'nce-s-trt-090',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'easy',
    stem: 'A counselor-in-training lists this objective for a 45-year-old client with depression: "Counselor will provide cognitive behavioral therapy weekly for 12 weeks." Why is this entry a weak treatment objective?',
    options: [
      { id: 'a', text: 'It names a treatment approach that has too little evidence for adults with depression', isCorrect: false, rationale: 'CBT is a well-supported treatment for depression; the problem lies in how the objective is written.' },
      { id: 'b', text: 'It describes the counselor\'s intervention, not a measurable change by the client', isCorrect: true, rationale: 'Objectives state what the client will do or achieve; the counselor\'s planned service belongs under interventions.' },
      { id: 'c', text: 'It sets a 12-week time frame, which is too long for an objective in a treatment plan', isCorrect: false, rationale: 'A defined time frame is a strength, and 12 weeks is a reasonable span for this kind of objective.' },
      { id: 'd', text: 'It leaves out the diagnosis, which must be repeated within each treatment objective', isCorrect: false, rationale: 'The diagnosis appears elsewhere in the plan; objectives do not need to restate it.' },
    ],
    rationale: 'A treatment plan separates goals, objectives and interventions. Objectives are measurable, client-centered steps, such as a target score or behavior by a set date, while interventions describe what the counselor will do to help the client get there. Writing the counselor\'s service as an objective leaves no way to judge the client\'s progress.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plans: measurable client objectives distinguished from clinician interventions' }],
  },
  {
    id: 'nce-s-trt-091',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'medium',
    stem: 'A supervisor reviews this objective for a 16-year-old referred for angry outbursts at school: "Client will gain insight into the causes of his anger by the end of the semester." Which revision BEST makes the objective measurable?',
    options: [
      { id: 'a', text: 'Client will develop a much deeper understanding of his anger by the end of the semester', isCorrect: false, rationale: '"Deeper understanding" is still an internal state that cannot be observed or counted.' },
      { id: 'b', text: 'Client will feel calmer and more in control at school by the end of the fall semester', isCorrect: false, rationale: 'Feeling calmer is a worthy aim but is vague and gives no way to observe or measure change.' },
      { id: 'c', text: 'Client will attend all of his weekly counseling sessions through the end of the semester', isCorrect: false, rationale: 'Attendance is measurable but tracks participation, not a change in the problem behavior.' },
      { id: 'd', text: 'Client will name three anger triggers and use a coping skill for each in session by week 4', isCorrect: true, rationale: 'This states observable client behaviors, a number to count and a deadline, so progress can be checked.' },
    ],
    rationale: 'Measurable objectives use observable action verbs such as name, list, use or reduce, rather than internal states such as understand, gain insight or feel. They also specify how much and by when. Turning "insight" into naming triggers and showing coping skills lets the counselor and client see whether the objective has been met.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Writing behavioral objectives: observable action verbs, criteria and target dates' }],
  },
  {
    id: 'nce-s-trt-092',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A 29-year-old client with moderate opioid use disorder is stable on buprenorphine, has no medical or psychiatric complications and wants to stay in recovery. However, he shares an apartment with two people who use heroin daily, and he has nowhere else to live. Which assessment dimension MOST supports a more structured setting?',
    options: [
      { id: 'a', text: 'Recovery or living environment', isCorrect: true, rationale: 'Living with people who use daily, with no other housing, is a serious environmental risk that can justify more structure.' },
      { id: 'b', text: 'Withdrawal potential', isCorrect: false, rationale: 'He is stable on buprenorphine, so acute withdrawal is not driving the placement decision.' },
      { id: 'c', text: 'Biomedical conditions', isCorrect: false, rationale: 'The stem states that he has no medical complications.' },
      { id: 'd', text: 'Readiness to change', isCorrect: false, rationale: 'He wants to stay in recovery, so readiness is a strength here rather than a concern.' },
    ],
    rationale: 'Placement decisions rest on a multidimensional assessment rather than diagnosis alone. Here every dimension looks favorable except his living environment, where daily exposure to active use and the lack of other housing threaten his recovery. That single dimension can support a more structured option, such as a residential setting or recovery housing combined with continued medication.',
    references: [{ source: 'ASAM Criteria', detail: 'Multidimensional assessment: recovery/living environment as a basis for level-of-care decisions' }],
  },
  {
    id: 'nce-s-trt-093',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'On day 12 of a residential substance use program, a 40-year-old client has no withdrawal symptoms, a stable home with a sober partner and strong coping skills, and meets criteria for outpatient care. The program requires every client to complete 30 days. What does level-of-care practice support?',
    options: [
      { id: 'a', text: 'Keep her in residential care for all 30 days, since full program completion predicts success', isCorrect: false, rationale: 'Length of stay should follow the client\'s progress, not a fixed program length.' },
      { id: 'b', text: 'Discharge her with no follow-up care, since she has done so well in the first two weeks', isCorrect: false, rationale: 'Moving down a level is appropriate, but ending all care removes needed support early in recovery.' },
      { id: 'c', text: 'Transfer her to outpatient care now, based on reassessment of her current needs and progress', isCorrect: true, rationale: 'Ongoing reassessment should move clients along the continuum when they meet criteria for a different level.' },
      { id: 'd', text: 'Extend her stay to 60 days so she can build even stronger coping skills before going home', isCorrect: false, rationale: 'Extending care she no longer needs is over-placement and disrupts her home and work life without benefit.' },
    ],
    rationale: 'Level-of-care decisions are outcome-driven rather than time-driven. Clients are reassessed during treatment and moved to the least intensive level that is safe and effective once they meet its criteria, instead of staying for a preset number of days. Continuing care at the next level keeps support in place during the transition.',
    references: [{ source: 'ASAM Criteria', detail: 'Continued service and transfer criteria: variable length of service based on progress rather than fixed program length' }],
  },
  {
    id: 'nce-s-trt-094',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'easy',
    stem: 'The parents of a 6-year-old girl describe daily defiance, frequent tantrums and hitting her younger brother. Her teacher reports similar behavior at school. Which intervention has the strongest evidence as a first-line approach for this age group?',
    options: [
      { id: 'a', text: 'Parent training that teaches praise, clear commands and consistent consequences', isCorrect: true, rationale: 'Behavioral parent training programs are the first-line, best-supported treatment for conduct problems in young children.' },
      { id: 'b', text: 'Weekly individual insight-oriented therapy so the girl can explore her feelings', isCorrect: false, rationale: 'Insight-oriented individual work with a young child lacks the evidence that parent-focused behavioral programs have.' },
      { id: 'c', text: 'A referral for stimulant medication as the first step to bring her behavior down', isCorrect: false, rationale: 'Medication is not a first-line treatment for conduct problems themselves, and no ADHD diagnosis is described.' },
      { id: 'd', text: 'A peer group with other aggressive children so they can learn from one another', isCorrect: false, rationale: 'Grouping aggressive children together can reinforce problem behavior and is not the recommended first step.' },
    ],
    rationale: 'For children aged about 3 to 11 with oppositional or conduct problems, parent training programs have the strongest research base. Parents learn to use positive attention, praise, clear instructions and consistent, non-harsh consequences, which change the patterns that keep the behavior going. Medication is not recommended as routine treatment for conduct problems.',
    references: [{ source: 'NICE guidelines', detail: 'Antisocial behaviour and conduct disorders in children and young people (CG158): parent training programmes for ages 3 to 11' }],
  },
  {
    id: 'nce-s-trt-095',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'hard',
    stem: 'A 48-year-old client with generalized anxiety disorder has not improved after psychoeducation and a guided self-help program. Under NICE stepped-care guidance, which pair of psychological treatments is recommended as the high-intensity option?',
    options: [
      { id: 'a', text: 'Eye movement desensitization and reprocessing or psychodynamic therapy', isCorrect: false, rationale: 'Neither EMDR nor psychodynamic therapy is a recommended high-intensity treatment for GAD in this guidance.' },
      { id: 'b', text: 'Individual cognitive behavioral therapy or applied relaxation training', isCorrect: true, rationale: 'NICE names individual CBT and applied relaxation as the high-intensity psychological options for GAD.' },
      { id: 'c', text: 'Exposure and response prevention or interpersonal psychotherapy alone', isCorrect: false, rationale: 'ERP is a treatment for OCD, and IPT is not a recommended high-intensity intervention for GAD.' },
      { id: 'd', text: 'Nondirective supportive counseling or a large psychoeducational group', isCorrect: false, rationale: 'Psychoeducational groups are a low-intensity step, and supportive counseling is not a recommended GAD treatment.' },
    ],
    rationale: 'NICE uses stepped care for generalized anxiety disorder: identification and psychoeducation first, then low-intensity interventions such as guided self-help or psychoeducational groups, and then high-intensity options. At the high-intensity step, the recommended psychological treatments are individual CBT or applied relaxation, with medication as an alternative based on client preference. Treatment intensity is stepped up only when a lower step has not helped.',
    references: [{ source: 'NICE guidelines', detail: 'Generalised anxiety disorder and panic disorder in adults (CG113): stepped care, step 3 high-intensity CBT or applied relaxation' }],
  },
  {
    id: 'nce-s-trt-096',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'medium',
    stem: 'A 51-year-old client with mild alcohol use disorder and no withdrawal history wants to cut down to two drinks on weekend evenings. Her counselor believes abstinence would be safer. During treatment planning, what is the MOST collaborative way to proceed?',
    options: [
      { id: 'a', text: 'Write abstinence as the goal, since the counselor\'s expertise should guide what goes in the plan', isCorrect: false, rationale: 'Imposing a goal the client does not hold tends to raise resistance and lower engagement.' },
      { id: 'b', text: 'Delay planning until the client accepts that abstinence is the only realistic goal for her', isCorrect: false, rationale: 'Withholding planning until she agrees is confrontational and risks losing her from treatment.' },
      { id: 'c', text: 'Adopt her reduction goal, share concerns openly, and agree to review progress on it together', isCorrect: true, rationale: 'Starting from the client\'s goal, giving honest input and planning to reassess respects her autonomy while keeping safety in view.' },
      { id: 'd', text: 'Let her write the plan entirely on her own so the counselor does not influence her choices', isCorrect: false, rationale: 'Collaboration means shared work; the counselor should still offer expertise and help shape measurable steps.' },
    ],
    rationale: 'Collaborative planning treats the client as the decision maker about her own goals while the counselor contributes information and concerns. In motivational interviewing, the counselor can offer a view with permission, then negotiate a plan that starts where the client is and includes a way to check how it is working. If moderation proves difficult, the goal can be revisited together.',
    references: [{ source: 'Miller & Rollnick (MI)', detail: 'Planning: negotiating change goals, offering information with permission and honoring client autonomy' }],
  },
  {
    id: 'nce-s-trt-097',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'medium',
    stem: 'A counselor uses the Outcome Rating Scale (ORS) at the start and the Session Rating Scale (SRS) at the end of each session. A 22-year-old client\'s ORS scores are flat, and after session three his SRS score drops well below his earlier ratings. What should the counselor do?',
    options: [
      { id: 'a', text: 'Invite his feedback about what did not fit in the session and adjust the approach with him', isCorrect: true, rationale: 'The SRS taps the alliance; a drop calls for an open conversation about goals, methods and fit.' },
      { id: 'b', text: 'Increase session frequency, since the drop in the SRS shows that his symptoms are worsening', isCorrect: false, rationale: 'The SRS measures the client\'s view of the session and alliance, not his symptoms.' },
      { id: 'c', text: 'Set the SRS aside and focus on the ORS, since only the ORS is a true measure of outcome', isCorrect: false, rationale: 'Alliance feedback is useful because alliance problems predict dropout and poor outcomes.' },
      { id: 'd', text: 'Replace both scales with a longer symptom inventory that gives more reliable scores', isCorrect: false, rationale: 'Swapping measures avoids the signal; the drop should be explored with the client directly.' },
    ],
    rationale: 'The ORS is a brief measure of how the client is doing personally, interpersonally, socially and overall, while the SRS asks how the session went in terms of the relationship, goals and topics, approach and overall fit. A falling SRS score is an early alliance warning. Discussing it openly and adjusting the work is the purpose of this kind of client feedback system.',
    references: [{ source: 'Lambert (Outcome Monitoring)', detail: 'Client feedback systems: Outcome Rating Scale and Session Rating Scale, alliance feedback' }],
  },
  {
    id: 'nce-s-trt-098',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'easy',
    stem: 'A community mental health center plans to adopt the Outcome Questionnaire-45 (OQ-45) to track client progress. Which three areas of functioning does the OQ-45 assess?',
    options: [
      { id: 'a', text: 'Mood, anxiety and substance use', isCorrect: false, rationale: 'These are symptom areas but not the three OQ-45 subscales.' },
      { id: 'b', text: 'Insight, motivation and alliance', isCorrect: false, rationale: 'These are process variables, not the outcome domains the OQ-45 measures.' },
      { id: 'c', text: 'Cognition, memory and attention', isCorrect: false, rationale: 'These are neuropsychological domains, not OQ-45 subscales.' },
      { id: 'd', text: 'Symptoms, relationships, social role', isCorrect: true, rationale: 'The OQ-45 has Symptom Distress, Interpersonal Relations and Social Role subscales.' },
    ],
    rationale: 'The OQ-45 is a 45-item self-report measure designed for repeated use during therapy. Its three subscales are Symptom Distress, Interpersonal Relations and Social Role performance, and higher scores mean more distress. Its sensitivity to change makes it useful for session-by-session monitoring.',
    references: [{ source: 'Lambert (Outcome Monitoring)', detail: 'Outcome Questionnaire-45: Symptom Distress, Interpersonal Relations and Social Role subscales' }],
  },
  {
    id: 'nce-s-trt-099',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'hard',
    stem: 'A 34-year-old client stopped gambling six weeks ago. He is working hard to stay away from casinos and to handle urges as they come. According to the Transtheoretical Model, which processes of change are MOST emphasized at his stage?',
    options: [
      { id: 'a', text: 'Consciousness raising and dramatic relief to build his awareness of the problem', isCorrect: false, rationale: 'These experiential processes are most used early, in moving from precontemplation to contemplation.' },
      { id: 'b', text: 'Stimulus control and counterconditioning to manage cues and replace the behavior', isCorrect: true, rationale: 'In the action stage, behavioral processes such as stimulus control and counterconditioning are emphasized.' },
      { id: 'c', text: 'Environmental reevaluation to weigh how his gambling has affected his family', isCorrect: false, rationale: 'Environmental reevaluation is linked mainly with contemplation, when people are weighing change.' },
      { id: 'd', text: 'Self-reevaluation to picture who he would be without gambling in his life', isCorrect: false, rationale: 'Self-reevaluation is most prominent in the shift from contemplation to preparation.' },
    ],
    rationale: 'Having changed his behavior within the past six months, he is in the action stage. Research on the Transtheoretical Model links the action and maintenance stages with behavioral processes: stimulus control, counterconditioning, contingency management and helping relationships. Experiential processes such as consciousness raising, dramatic relief and reevaluation are emphasized in earlier stages.',
    references: [{ source: 'Transtheoretical Model', detail: 'Integration of stages and processes of change: behavioral processes in action and maintenance' }],
  },
  {
    id: 'nce-s-trt-100',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'medium',
    stem: 'A counselor at a HIPAA-covered agency is sending a client\'s assessment and treatment summary to the psychiatrist who will now manage the client\'s medication. A colleague says HIPAA\'s minimum necessary standard requires removing most details first. Which statement is accurate?',
    options: [
      { id: 'a', text: 'Minimum necessary applies to every disclosure, so only a diagnosis and medication may be sent', isCorrect: false, rationale: 'The standard has exceptions, and disclosures to a provider for treatment are one of them.' },
      { id: 'b', text: 'Minimum necessary bars any sharing of mental health records unless a court orders the release', isCorrect: false, rationale: 'HIPAA permits sharing for treatment; a court order is not needed for coordination between providers.' },
      { id: 'c', text: 'Minimum necessary does not apply to disclosures made to another provider for treatment purposes', isCorrect: true, rationale: 'The Privacy Rule exempts disclosures to, or requests by, a health care provider for treatment from this standard.' },
      { id: 'd', text: 'Minimum necessary applies only to paper records, so electronic summaries can be sent in full', isCorrect: false, rationale: 'The standard covers protected health information in any form, paper or electronic.' },
    ],
    rationale: 'Under the HIPAA Privacy Rule, the minimum necessary standard limits uses and disclosures for purposes such as payment and operations, but it does not apply to disclosures to a health care provider for treatment. Providers can share what is clinically relevant to coordinate care. Psychotherapy notes kept separate from the record still require the client\'s authorization, and state law or agency policy may set stricter rules.',
    references: [{ source: 'HIPAA', detail: 'Privacy Rule minimum necessary standard (45 CFR 164.502(b)): exception for disclosures to a provider for treatment' }],
  },
  {
    id: 'nce-s-trt-101',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'In a trial of a group treatment for depression, the treatment group\'s mean posttest score is 21 and the control group\'s mean is 27 on a measure where higher scores mean more severe symptoms. The pooled standard deviation is 8. What is Cohen\'s d, and how large is the effect?',
    options: [
      { id: 'a', text: '0.75, between medium and large', isCorrect: true, rationale: 'd = (27 - 21) / 8 = 0.75, which falls between the medium (0.5) and large (0.8) benchmarks.' },
      { id: 'b', text: '1.33, a very large effect', isCorrect: false, rationale: 'This divides the SD by the mean difference (8 / 6) instead of the reverse.' },
      { id: 'c', text: '6.0, a very large effect', isCorrect: false, rationale: 'Six is the raw mean difference; d divides it by the standard deviation.' },
      { id: 'd', text: '0.29, a small effect', isCorrect: false, rationale: 'This divides the difference by a mean (6 / 21) instead of by the standard deviation.' },
    ],
    rationale: 'Cohen\'s d is the difference between two group means divided by the pooled standard deviation, which expresses the effect in standard deviation units. Here (27 - 21) / 8 = 0.75. By Cohen\'s conventions (about 0.2 small, 0.5 medium, 0.8 large), this is a medium-to-large effect.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Effect size: computing Cohen\'s d from group means and pooled standard deviation' }],
  },
  {
    id: 'nce-s-trt-102',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'hard',
    stem: 'A small pilot study had a power of .60 to detect a medium effect. It found p = .24, and the authors concluded that the new intervention does not work. If the intervention truly has a medium effect, what error may they have made, and how likely was it?',
    options: [
      { id: 'a', text: 'A Type I error, with probability .05', isCorrect: false, rationale: 'A Type I error is rejecting a true null; these authors did not reject the null.' },
      { id: 'b', text: 'A Type II error, with probability .60', isCorrect: false, rationale: '.60 is the power, the chance of correctly detecting the effect, not the chance of missing it.' },
      { id: 'c', text: 'A Type I error, with probability .40', isCorrect: false, rationale: 'The error is failing to detect a real effect, which is Type II, not Type I.' },
      { id: 'd', text: 'A Type II error, with probability .40', isCorrect: true, rationale: 'Missing a real effect is a Type II error; beta = 1 - power = 1 - .60 = .40.' },
    ],
    rationale: 'A Type II error is failing to reject a false null hypothesis, that is, missing an effect that really exists. Its probability, beta, equals 1 minus power, so a study with power of .60 has a .40 chance of missing a true medium effect. Underpowered outcome studies can therefore lead to the mistaken conclusion that an effective treatment does not work.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Hypothesis testing: Type II error, beta and statistical power (1 - beta)' }],
  },
];
