// tools/nce/seed/treatment-2.js — Treatment Planning, batch 2 (research & program evaluation heavy)
module.exports = [
  {
    id: 'nce-s-trt-018',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'easy',
    stem: 'A survey of 600 adolescents finds that hours spent on social media correlate r = .45 with scores on a depressive symptom scale. Which conclusion is BEST supported by this finding?',
    options: [
      { id: 'a', text: 'Heavy social media use causes depressive symptoms in teenagers', isCorrect: false, rationale: 'A correlation cannot establish causation; depression could drive use, or a third variable could affect both.' },
      { id: 'b', text: 'Teens who use social media more tend to report more depressive symptoms', isCorrect: true, rationale: 'A positive correlation means higher values on one variable tend to go with higher values on the other, without implying cause.' },
      { id: 'c', text: 'About 45 percent of depressive symptoms are explained by social media use', isCorrect: false, rationale: 'Shared variance is r squared (.45 x .45, about 20 percent), and even that describes association, not explanation by cause.' },
      { id: 'd', text: 'Reducing social media time will lower depression scores for most teens', isCorrect: false, rationale: 'Predicting the effect of changing one variable is a causal claim that requires an experimental design.' },
    ],
    rationale: 'Correlational designs show whether and how strongly two variables move together, but not why. The direction of influence is unknown, and a third variable (such as loneliness or poor sleep) may account for both. The coefficient of determination (r squared) gives the proportion of shared variance; here about 20 percent.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Correlational research: correlation vs causation and the coefficient of determination' }],
  },
  {
    id: 'nce-s-trt-019',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'A statistics instructor asks counseling students to classify several variables by scale of measurement. Which variable is measured on an interval scale?',
    options: [
      { id: 'a', text: 'Clients\' ranked order of improvement', isCorrect: false, rationale: 'Ranks show order but not equal distances between positions, which makes them ordinal.' },
      { id: 'b', text: 'Number of sessions each client attended', isCorrect: false, rationale: 'A count has equal intervals and a true zero (no sessions), which makes it a ratio scale.' },
      { id: 'c', text: 'Temperature in degrees Fahrenheit', isCorrect: true, rationale: 'Fahrenheit has equal intervals but an arbitrary zero point, the defining feature of an interval scale.' },
      { id: 'd', text: 'Clients\' primary diagnostic category', isCorrect: false, rationale: 'Diagnostic categories are named groups with no inherent order, which makes them nominal.' },
    ],
    rationale: 'The four scales build on each other: nominal (categories), ordinal (rank order), interval (equal units but no true zero), and ratio (equal units plus a true zero). Because interval data lack a true zero, ratios are not meaningful; 80 degrees Fahrenheit is not twice as hot as 40 degrees.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Scales of measurement: nominal, ordinal, interval and ratio' }],
  },
  {
    id: 'nce-s-trt-020',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'Annual household incomes of clients at a community counseling agency are mostly low, but a small number of clients report very high incomes. Which statement about this distribution is accurate?',
    options: [
      { id: 'a', text: 'It is positively skewed, and the mean is higher than the median', isCorrect: true, rationale: 'A tail of a few very high values is a positive skew, and the mean is pulled toward that tail, above the median.' },
      { id: 'b', text: 'It is negatively skewed, and the mean is lower than the median', isCorrect: false, rationale: 'A negative skew has its tail toward low values; here the tail is toward high incomes.' },
      { id: 'c', text: 'It is positively skewed, and the mode is higher than the mean', isCorrect: false, rationale: 'In a positive skew the mode sits at the peak on the low end, below both the median and the mean.' },
      { id: 'd', text: 'It is symmetrical, so the mean, median and mode are about equal', isCorrect: false, rationale: 'A few extreme high values make the distribution asymmetrical, so the three measures separate.' },
    ],
    rationale: 'Skew is named for the direction of the tail. In a positively skewed distribution, the typical order is mode < median < mean, because the mean is sensitive to extreme scores. For skewed data such as income, the median is usually the best single measure of central tendency.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Descriptive statistics: measures of central tendency and skewed distributions' }],
  },
  {
    id: 'nce-s-trt-021',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'Scores on a depression inventory are normally distributed with a mean of 50 and a standard deviation of 10. A client scores 60. Approximately what percentage of the norm group scored at or below this client?',
    options: [
      { id: 'a', text: '34 percent', isCorrect: false, rationale: 'About 34 percent of scores fall between the mean and +1 SD; this omits the 50 percent below the mean.' },
      { id: 'b', text: '50 percent', isCorrect: false, rationale: 'Fifty percent falls at or below the mean of 50, not at a score one SD above it.' },
      { id: 'c', text: '68 percent', isCorrect: false, rationale: 'About 68 percent fall within plus or minus 1 SD of the mean, which is a band, not a cumulative percentage.' },
      { id: 'd', text: '84 percent', isCorrect: true, rationale: 'A score of 60 is z = +1; 50 percent fall below the mean plus about 34 percent between the mean and +1 SD.' },
    ],
    rationale: 'The standard deviation describes how spread out scores are around the mean. In a normal distribution, about 68 percent of scores fall within 1 SD of the mean, 95 percent within 2 SD, and 99.7 percent within 3 SD. A score 1 SD above the mean (z = +1, T = 60) sits at about the 84th percentile.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Standard deviation, the normal curve and percentile ranks' }],
  },
  {
    id: 'nce-s-trt-022',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'A researcher randomly assigns 90 clients to one of three conditions (individual CBT, a mindfulness group, or a waitlist) and compares the groups on posttest anxiety scores measured on an interval scale. Which statistical test is MOST appropriate?',
    options: [
      { id: 'a', text: 'An independent-samples t-test', isCorrect: false, rationale: 'A t-test compares only two group means; running several t-tests inflates the Type I error rate.' },
      { id: 'b', text: 'A one-way analysis of variance', isCorrect: true, rationale: 'One categorical independent variable with three levels and one interval dependent variable calls for a one-way ANOVA.' },
      { id: 'c', text: 'A chi-square test of independence', isCorrect: false, rationale: 'Chi-square tests relationships between categorical variables (frequencies), not differences in mean scores.' },
      { id: 'd', text: 'A Pearson product-moment correlation', isCorrect: false, rationale: 'Pearson r measures the linear relationship between two continuous variables, not group differences.' },
    ],
    rationale: 'Here the independent variable is treatment condition (three levels) and the dependent variable is the anxiety score. A one-way ANOVA compares three or more group means in a single test while holding the Type I error rate at alpha; post hoc tests then show which groups differ. A t-test is used for two groups, chi-square for categorical outcomes, and Pearson r for relationships between two continuous variables.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Selecting inferential statistics: t-test, ANOVA, chi-square and correlation' }],
  },
  {
    id: 'nce-s-trt-023',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'hard',
    stem: 'A counselor-researcher is planning a study comparing two interventions and wants to reduce the risk of missing a true but modest difference between them. Which change would MOST directly increase statistical power?',
    options: [
      { id: 'a', text: 'Lowering alpha from .05 to .01 to guard against false positives', isCorrect: false, rationale: 'A stricter alpha makes it harder to reject the null, which lowers power and raises Type II risk.' },
      { id: 'b', text: 'Using a smaller sample so each participant gets more attention', isCorrect: false, rationale: 'Smaller samples increase sampling error and reduce power to detect a real effect.' },
      { id: 'c', text: 'Increasing the number of participants assigned to each condition', isCorrect: true, rationale: 'Larger samples reduce standard error, making a true effect of a given size more likely to be detected.' },
      { id: 'd', text: 'Switching from a one-tailed test to a two-tailed test of the effect', isCorrect: false, rationale: 'Splitting alpha across two tails lowers power for an effect in the predicted direction.' },
    ],
    rationale: 'Power (1 - beta) is the probability of correctly rejecting a false null hypothesis. It rises with larger sample size, larger effect size, a more lenient alpha, a one-tailed test (when the direction is correct), and more reliable measures. Researchers run a power analysis before a study, often targeting .80, to choose a sample size that can detect the expected effect.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Statistical power, sample size and Type II error' }],
  },
  {
    id: 'nce-s-trt-024',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'hard',
    stem: 'A trial finds that a new anxiety program works well. Participants knew they were in a closely watched study, received extra attention from research staff, and liked being part of something new. Critics doubt that the results will hold in routine agency practice. Which threat are the critics MOST likely describing?',
    options: [
      { id: 'a', text: 'Reactive effects of the experimental arrangements', isCorrect: true, rationale: 'Changes caused by knowing one is studied (a Hawthorne-type effect) limit generalization to ordinary settings, a threat to external validity.' },
      { id: 'b', text: 'Statistical regression of extreme scores toward the mean', isCorrect: false, rationale: 'Regression is an internal validity threat tied to selecting extreme scorers, which the stem does not describe.' },
      { id: 'c', text: 'Instrumentation changes in how outcomes were measured', isCorrect: false, rationale: 'Instrumentation is an internal validity threat involving shifts in measurement, not generalizability.' },
      { id: 'd', text: 'Selection differences between the groups being compared', isCorrect: false, rationale: 'Selection is an internal validity threat about nonequivalent groups, not about generalizing to practice.' },
    ],
    rationale: 'External validity concerns whether results generalize to other people, settings and times. Reactive arrangements, such as the Hawthorne effect, occur when the research situation itself (attention, novelty, awareness of being studied) contributes to the outcome, so effects may shrink in routine care. Internal validity threats such as history, regression, selection and instrumentation instead question whether the treatment caused the change at all.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Threats to external validity: reactive effects of experimental arrangements' }],
  },
  {
    id: 'nce-s-trt-025',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'hard',
    stem: 'A school counselor wants to show that a social skills intervention caused improvement for three elementary students on the autism spectrum. Once learned, the skills are not expected to fade, and withdrawing the intervention would be ethically questionable. Which design BEST fits these conditions?',
    options: [
      { id: 'a', text: 'An AB design with a single baseline and treatment phase', isCorrect: false, rationale: 'An AB design lacks replication, so it cannot rule out other explanations such as maturation or history.' },
      { id: 'b', text: 'An ABAB reversal design that withdraws the intervention', isCorrect: false, rationale: 'Reversal requires withdrawing treatment and expects behavior to return to baseline, neither of which fits here.' },
      { id: 'c', text: 'A one-group pretest-posttest design with all three students', isCorrect: false, rationale: 'This pre-experimental design has no control for threats such as maturation or history.' },
      { id: 'd', text: 'A multiple-baseline design staggered across the students', isCorrect: true, rationale: 'Starting the intervention at different times for each student shows control without withdrawing treatment.' },
    ],
    rationale: 'In a multiple-baseline design, baselines begin together but the intervention is introduced at staggered points across participants, behaviors or settings. If each behavior changes only when the intervention starts for it, the counselor gains evidence of causation without a reversal. It is the design of choice when behavior is not reversible or withdrawal would be unethical; a simple AB design shows change but not experimental control.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Single-subject designs: AB vs multiple-baseline designs' }],
  },
  {
    id: 'nce-s-trt-026',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'medium',
    stem: 'A researcher conducts in-depth interviews with 12 parents who have lost a child to overdose. Her goal is to describe the essence of how parents live through this kind of grief, setting aside her own assumptions as she analyzes the data. Which qualitative tradition does this study reflect?',
    options: [
      { id: 'a', text: 'Grounded theory', isCorrect: false, rationale: 'Grounded theory aims to generate a theory of a process through constant comparison and theoretical sampling.' },
      { id: 'b', text: 'Phenomenology', isCorrect: true, rationale: 'Describing the essence of a lived experience and bracketing researcher assumptions are hallmarks of phenomenology.' },
      { id: 'c', text: 'Ethnography', isCorrect: false, rationale: 'Ethnography studies the shared patterns of a culture-sharing group through prolonged fieldwork and observation.' },
      { id: 'd', text: 'Case study', isCorrect: false, rationale: 'A case study examines one or a few bounded systems in depth using multiple sources of data.' },
    ],
    rationale: 'Phenomenology seeks the essential structure of a lived experience shared by several people, typically through in-depth interviews, with the researcher bracketing (epoche) personal assumptions. Grounded theory builds theory from data, ethnography describes a culture, and a case study explores a bounded case in its context.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Qualitative traditions: phenomenology, grounded theory, ethnography and case study' }],
  },
  {
    id: 'nce-s-trt-027',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'easy',
    stem: 'After coding interviews with first-generation college students, a counselor-researcher shares her preliminary themes with the participants and asks whether the themes accurately capture their experiences. Which trustworthiness strategy is she using?',
    options: [
      { id: 'a', text: 'Triangulation', isCorrect: false, rationale: 'Triangulation compares multiple data sources, methods, investigators or theories, not participant review of findings.' },
      { id: 'b', text: 'Peer debriefing', isCorrect: false, rationale: 'Peer debriefing involves a colleague, not the participants, reviewing and questioning the analysis.' },
      { id: 'c', text: 'Member checking', isCorrect: true, rationale: 'Returning interpretations to participants to confirm their accuracy is member checking.' },
      { id: 'd', text: 'Audit trail', isCorrect: false, rationale: 'An audit trail documents decisions throughout the study so an outside reviewer can follow them.' },
    ],
    rationale: 'Trustworthiness is the qualitative counterpart of validity and reliability, with criteria such as credibility, transferability, dependability and confirmability (Lincoln and Guba). Member checking is a key credibility strategy; triangulation, peer debriefing, prolonged engagement, thick description and audit trails support other criteria.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Trustworthiness in qualitative research: member checking and triangulation' }],
  },
  {
    id: 'nce-s-trt-028',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'medium',
    stem: 'A state counseling association plans to survey its members and wants school, clinical mental health and rehabilitation counselors represented in the sample in the same proportions as in the full membership, with members chosen at random. Which sampling method BEST meets this goal?',
    options: [
      { id: 'a', text: 'Stratified random sampling', isCorrect: true, rationale: 'Dividing the population into subgroups and randomly sampling from each guarantees proportional representation.' },
      { id: 'b', text: 'Simple random sampling', isCorrect: false, rationale: 'Simple random sampling gives everyone an equal chance but does not guarantee each subgroup\'s proportion.' },
      { id: 'c', text: 'Convenience sampling', isCorrect: false, rationale: 'Convenience sampling uses whoever is easily available and is neither random nor proportional.' },
      { id: 'd', text: 'Snowball sampling', isCorrect: false, rationale: 'Snowball sampling recruits through referrals from participants and is used for hard-to-reach groups.' },
    ],
    rationale: 'Stratified random sampling divides a population into strata on a key characteristic and then randomly selects from each stratum, often in proportion to its size. It improves representativeness on that characteristic compared with simple random sampling, while convenience and snowball samples are nonprobability methods that limit generalization.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Probability vs nonprobability sampling: stratified random sampling' }],
  },
  {
    id: 'nce-s-trt-029',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'easy',
    stem: 'A researcher locates 48 published and unpublished studies of group counseling for adolescent depression and statistically combines their effect sizes to estimate an overall effect. What type of study is this?',
    options: [
      { id: 'a', text: 'A narrative literature review', isCorrect: false, rationale: 'A narrative review summarizes studies in words without statistically pooling their results.' },
      { id: 'b', text: 'A longitudinal cohort study', isCorrect: false, rationale: 'A cohort study follows one group of participants over time and collects new data.' },
      { id: 'c', text: 'A randomized controlled trial', isCorrect: false, rationale: 'An RCT randomly assigns its own participants to conditions rather than combining prior studies.' },
      { id: 'd', text: 'A meta-analysis', isCorrect: true, rationale: 'Quantitatively pooling effect sizes across many studies to estimate an overall effect is meta-analysis.' },
    ],
    rationale: 'Meta-analysis converts the results of many studies to a common effect size metric (such as Cohen\'s d) and combines them, weighting larger studies more heavily. Including unpublished studies helps reduce publication bias. Meta-analyses of randomized trials are often placed at the top of evidence hierarchies used in evidence-based practice.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Meta-analysis and effect sizes' }],
  },
  {
    id: 'nce-s-trt-030',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'medium',
    stem: 'A college counseling center builds a logic model for a new peer-support program. Which entry belongs in the outcomes column of the model rather than in the outputs column?',
    options: [
      { id: 'a', text: 'Number of peer-support sessions held each semester', isCorrect: false, rationale: 'Sessions delivered are an output, a count of activity, not a change in participants.' },
      { id: 'b', text: 'Number of students who attended at least one session', isCorrect: false, rationale: 'Attendance counts are outputs that show reach, not program effects.' },
      { id: 'c', text: 'Lower loneliness scores among participating students', isCorrect: true, rationale: 'A change in participants\' loneliness is an outcome, the intended effect of the program.' },
      { id: 'd', text: 'Number of peer supporters who finished the training course', isCorrect: false, rationale: 'Trained supporters are a product of program activities, which makes this an output.' },
    ],
    rationale: 'A logic model links inputs (resources) to activities, outputs (direct products such as sessions held and people served), and outcomes (changes in knowledge, behavior or well-being). Process evaluation examines whether activities and outputs are delivered as planned; outcome evaluation examines whether the intended changes occurred.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Program evaluation: logic models, process vs outcome evaluation' }],
  },
  {
    id: 'nce-s-trt-031',
    reviewNote: 'Wiger reference detail describes the concept, not an exact chapter title.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'easy',
    stem: 'The parents and teacher of an 8-year-old boy report frequent tantrums when classwork becomes frustrating. Which objective for his treatment plan is MOST measurable?',
    options: [
      { id: 'a', text: 'He will use his calm-down card instead of a tantrum in 4 of 5 hard tasks by March', isCorrect: true, rationale: 'This names an observable replacement behavior, a success criterion (4 of 5 tasks) and a deadline.' },
      { id: 'b', text: 'He will gain better control of his emotions and feel happier at school this year', isCorrect: false, rationale: 'Emotional control and happiness are not defined in observable terms and lack a success criterion.' },
      { id: 'c', text: 'He will learn why tantrums upset classmates and grow more empathy toward them', isCorrect: false, rationale: 'Understanding and empathy are internal states with no observable measure or time frame.' },
      { id: 'd', text: 'He will meet with the school counselor every week to talk through angry feelings', isCorrect: false, rationale: 'Attending sessions describes the intervention, not a measurable change in the problem behavior.' },
    ],
    rationale: 'Objectives for children should describe a specific, observable behavior that teachers or parents can count, a criterion for success, and a target date. Framing the objective as a replacement behavior (using a coping tool) rather than only the absence of tantrums also gives the child something concrete to practice and adults something to reinforce.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plans: observable, measurable objectives' }],
  },
  {
    id: 'nce-s-trt-032',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A 26-year-old man with schizophrenia was discharged from a psychiatric unit two weeks ago. He is taking his medication and has no suicidal or homicidal ideation, but he has missed several outpatient appointments and struggles to manage daily tasks on his own. Consistent with the least restrictive environment, which plan is MOST appropriate?',
    options: [
      { id: 'a', text: 'Readmit him to the inpatient unit until his attendance becomes consistent', isCorrect: false, rationale: 'He has no acute risk; hospitalizing him for missed appointments is far more restrictive than needed.' },
      { id: 'b', text: 'Add assertive community treatment or case management to support him at home', isCorrect: true, rationale: 'Bringing intensive supports to him in the community addresses engagement and daily functioning in the least restrictive setting.' },
      { id: 'c', text: 'Arrange long-term placement in a locked residential facility for his safety', isCorrect: false, rationale: 'A locked setting is unjustified for a client who is stable and not dangerous to himself or others.' },
      { id: 'd', text: 'Continue monthly outpatient visits and close the case if he misses another', isCorrect: false, rationale: 'This ignores clear signs that his current level of support is not enough and risks disengagement.' },
    ],
    rationale: 'The least restrictive environment principle calls for providing care in the most integrated, least confining setting that can safely meet the client\'s needs. When a client is stable but struggling to engage and function, the first step is to intensify community-based supports, such as assertive community treatment or case management, rather than move him to a more restrictive setting.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Clinical mental health counseling: community-based care and the least restrictive setting' }],
    reviewNote: 'Gladding reference detail is a concept paraphrase; confirm a better-matched source if available.',
  },
  {
    id: 'nce-s-trt-033',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'medium',
    stem: 'A 33-year-old client finishing treatment for alcohol use disorder is building a relapse prevention plan with her counselor. Based on the cognitive-behavioral relapse prevention model, which element is MOST central to the plan?',
    options: [
      { id: 'a', text: 'Agreeing that any single lapse means treatment failed and must start over', isCorrect: false, rationale: 'This all-or-nothing view feeds the abstinence violation effect, which turns lapses into full relapses.' },
      { id: 'b', text: 'Avoiding all talk of cravings so that the urges lose their power over time', isCorrect: false, rationale: 'Avoiding discussion of cravings leaves her unprepared; the model teaches recognizing and coping with urges.' },
      { id: 'c', text: 'Focusing the plan mainly on the past events that first led her to drink', isCorrect: false, rationale: 'Relapse prevention is present- and future-focused, centered on upcoming risks and skills.' },
      { id: 'd', text: 'Identifying her high-risk situations and rehearsing coping responses', isCorrect: true, rationale: 'Spotting personal high-risk situations and practicing coping skills for them is the core of relapse prevention.' },
    ],
    rationale: 'Marlatt and Gordon\'s relapse prevention model holds that relapse risk rises when a person meets a high-risk situation without an effective coping response. Plans therefore identify triggers, build and rehearse coping skills, increase self-efficacy, and treat a lapse as a learning opportunity rather than a failure, countering the abstinence violation effect.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Cognitive behavioral approaches: relapse prevention, high-risk situations and coping skills' }],
    reviewNote: 'Confirm the Corey edition in use covers relapse prevention; Marlatt & Gordon is the primary source but is not on the approved list.',
  },
  {
    id: 'nce-s-trt-034',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'easy',
    stem: 'An interdisciplinary team at an adolescent residential program decides that clients who miss group will lose family phone calls for a week. The counselor on the team believes this decision raises ethical concerns. What should the counselor do FIRST?',
    options: [
      { id: 'a', text: 'Report the team to the state licensing board for unethical practice', isCorrect: false, rationale: 'Outside avenues are pursued only after attempts to resolve the concern within the team have failed.' },
      { id: 'b', text: 'Tell the clients\' families privately that she disagrees with the team', isCorrect: false, rationale: 'Going around the team to families undermines the team and does not address the decision itself.' },
      { id: 'c', text: 'Raise the concern with the team and try to resolve it within the team', isCorrect: true, rationale: 'The ACA Code directs counselors to first attempt to resolve ethical concerns about team decisions within the team.' },
      { id: 'd', text: 'Follow the decision without comment, since team consensus outranks her', isCorrect: false, rationale: 'Counselors keep their own ethical obligations on a team and may not simply defer to consensus.' },
    ],
    rationale: 'Counselors on interdisciplinary teams keep the focus on how best to serve clients and clarify the professional and ethical obligations of the team and its members. When a team decision raises ethical concerns, they first try to resolve the concern within the team; if that fails, they pursue other avenues consistent with client well-being.',
    references: [{ source: 'ACA Code of Ethics', detail: 'D.1.d Establishing Professional and Ethical Obligations' }],
    reviewNote: 'Confirm the section number D.1.d for resolving team ethical concerns within the team (vs D.1.c Interdisciplinary Teamwork).',
  },
];
