// tools/nce/seed/treatment-3.js — Treatment Planning, batch 3 (treatment planning heavy)
module.exports = [
  {
    id: 'nce-s-trt-035',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'medium',
    stem: 'A 31-year-old graduate student has had recurrent unexpected panic attacks for six months. She now avoids crowded buses and worries constantly that her racing heart signals a heart attack. Medical causes have been ruled out. Which psychotherapy approach is the BEST first-line choice?',
    options: [
      { id: 'a', text: 'Supportive listening that steers away from discussing body sensations', isCorrect: false, rationale: 'Avoiding feared sensations maintains the fear of them; nondirective support is not a first-line treatment for panic disorder.' },
      { id: 'b', text: 'Cognitive behavioral therapy that includes interoceptive exposure', isCorrect: true, rationale: 'CBT with psychoeducation, cognitive restructuring of catastrophic misinterpretations, and interoceptive and situational exposure is the best-supported psychotherapy for panic disorder.' },
      { id: 'c', text: 'Helping her plan routes that avoid the situations where attacks occur', isCorrect: false, rationale: 'Planned avoidance reinforces agoraphobic avoidance and the belief that the situations are dangerous.' },
      { id: 'd', text: 'Dream analysis aimed at uncovering the unconscious source of her fear', isCorrect: false, rationale: 'Dream analysis is not an evidence-based first-line treatment for panic disorder and does not target the panic cycle.' },
    ],
    rationale: 'Panic disorder is maintained by catastrophic misinterpretation of bodily sensations and by avoidance. Cognitive behavioral treatment, such as Panic Control Treatment, combines psychoeducation, cognitive restructuring, and exposure to feared body sensations (interoceptive exposure) and situations. Guidelines name CBT as the first-line psychological treatment.',
    references: [
      { source: 'Barlow PCT', detail: 'Panic Control Treatment: interoceptive exposure and cognitive restructuring' },
      { source: 'NICE guidelines', detail: 'CG113 Generalised anxiety disorder and panic disorder in adults: CBT for panic disorder' },
    ],
  },
  {
    id: 'nce-s-trt-036',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'medium',
    stem: 'A 24-year-old client meets criteria for borderline personality disorder. She cuts herself several times a month during intense emotional storms, and reducing self-harm is her top priority. Which treatment has the strongest research support for this presentation?',
    options: [
      { id: 'a', text: 'Brief solution-focused therapy limited to three sessions', isCorrect: false, rationale: 'A three-session brief model does not provide the skills training and structure needed for recurrent self-harm in BPD.' },
      { id: 'b', text: 'Prolonged exposure therapy targeting traumatic memories', isCorrect: false, rationale: 'Prolonged exposure targets PTSD; starting it with uncontrolled self-harm is not the first-line approach for BPD.' },
      { id: 'c', text: 'A psychoeducational group on personality disorder myths', isCorrect: false, rationale: 'Psychoeducation alone does not teach the emotion regulation and distress tolerance skills that reduce self-harm.' },
      { id: 'd', text: 'Comprehensive dialectical behavior therapy (DBT) program', isCorrect: true, rationale: 'Comprehensive DBT (individual therapy, skills group, phone coaching, consultation team) has the strongest evidence for reducing self-harm in BPD.' },
    ],
    rationale: 'Dialectical behavior therapy was developed for chronically suicidal and self-harming clients with borderline personality disorder. Its comprehensive form combines individual therapy, skills training in mindfulness, distress tolerance, emotion regulation and interpersonal effectiveness, between-session coaching, and a therapist consultation team. Guidelines recommend it when reducing recurrent self-harm is a priority.',
    references: [{ source: 'NICE guidelines', detail: 'CG78 Borderline personality disorder: consider a comprehensive DBT programme when reducing recurrent self-harm is a priority' }],
  },
  {
    id: 'nce-s-trt-037',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'hard',
    stem: 'A clinical supervisor is reviewing the common factors versus specific factors debate with a counselor-in-training. Across comparisons of well-established (bona fide) therapies, which finding is MOST consistent with the common factors research?',
    options: [
      { id: 'a', text: 'Alliance quality predicts outcome more than which model is used', isCorrect: true, rationale: 'Meta-analyses find the alliance reliably predicts outcome, while differences among bona fide treatments are small.' },
      { id: 'b', text: 'Specific techniques explain most of the variance in outcomes', isCorrect: false, rationale: 'Specific ingredients account for a small share of outcome variance compared with relational and client factors.' },
      { id: 'c', text: 'Counselor years of experience is the strongest single predictor', isCorrect: false, rationale: 'Years of experience is a weak predictor of outcome; it does not outweigh the alliance.' },
      { id: 'd', text: 'Matching the model to the diagnosis removes therapist effects', isCorrect: false, rationale: 'Therapist effects persist across models; some counselors get better results regardless of the approach used.' },
    ],
    rationale: 'The common factors view (Rosenzweig, Frank, Lambert, Wampold) holds that elements shared by effective therapies, such as the alliance, empathy, expectancy and a credible rationale, account for much of the change. Comparisons of bona fide treatments show small differences, while the alliance consistently predicts outcome. This does not make specific methods irrelevant; many conditions, such as PTSD and panic, have treatments with specific evidence.',
    references: [{ source: 'Corey (Theory & Practice)', detail: 'Integrative approaches: common factors and the therapeutic relationship as a predictor of outcome' }],
    reviewNote: 'Common factors findings (Wampold & Imel; Lambert) are well established, but confirm the Corey edition discusses common factors research explicitly.',
  },
  {
    id: 'nce-s-trt-038',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'medium',
    stem: 'A 45-year-old man with obsessive-compulsive disorder is nervous about exposure and response prevention and asks whether there are other options. Which response BEST reflects shared decision making?',
    options: [
      { id: 'a', text: 'Tell him ERP is the evidence-based choice, so the plan cannot change', isCorrect: false, rationale: 'Insisting on one option without exploring his concerns and preferences removes him from the decision.' },
      { id: 'b', text: 'Let him choose any approach he likes without discussing the evidence', isCorrect: false, rationale: 'Shared decision making requires the counselor to bring evidence; deferring entirely abandons that role.' },
      { id: 'c', text: 'Review the options, evidence and his concerns, then decide jointly', isCorrect: true, rationale: 'Shared decision making combines the counselor\'s knowledge of the evidence with the client\'s values and preferences in a joint choice.' },
      { id: 'd', text: 'Postpone treatment planning until his anxiety about ERP has resolved', isCorrect: false, rationale: 'Delaying planning leaves him untreated; fear of ERP is something to discuss and plan for, not wait out.' },
    ],
    rationale: 'Evidence-based practice integrates the best research evidence, clinical expertise and client characteristics, values and preferences. In shared decision making the counselor explains the options with their benefits and burdens, explores the client\'s concerns, and arrives at a plan together. Here that might include explaining how ERP is graded and client-paced.',
    references: [{ source: 'APA CPG', detail: 'Evidence-based practice: integrating patient values and preferences into treatment decisions' }],
  },
  {
    id: 'nce-s-trt-039',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'medium',
    stem: 'A 19-year-old Mexican American client with depression tells her counselor that decisions in her family are made together and that she wants her mother involved in her care. Which approach to the treatment plan is MOST culturally responsive?',
    options: [
      { id: 'a', text: 'Include her mother in planning as she wishes, keeping core methods', isCorrect: true, rationale: 'Cultural adaptation honors her value of family involvement while keeping the active ingredients of effective treatment.' },
      { id: 'b', text: 'Keep the plan individual, since adult clients decide treatment alone', isCorrect: false, rationale: 'This imposes an individualistic worldview and ignores the client\'s own stated wish for family involvement.' },
      { id: 'c', text: 'Assume every Latina client prefers family therapy over individual work', isCorrect: false, rationale: 'This stereotypes the client; adaptation should follow her stated preferences, not group generalizations.' },
      { id: 'd', text: 'Ask her mother to set the goals because she is the family decision maker', isCorrect: false, rationale: 'The client remains the decision maker about her own care; involving family does not mean handing over her goals.' },
    ],
    rationale: 'Culturally adapted treatment adjusts how a plan is delivered (who is involved, language, metaphors, goals framed in the client\'s values) while preserving the core components of effective treatment. The adaptation should be driven by the individual client\'s stated values, here familismo and collective decision making, rather than by assumptions about a group.',
    references: [
      { source: 'Sue & Sue (Counseling the Culturally Diverse)', detail: 'Culturally appropriate intervention strategies: collectivism and family involvement' },
      { source: 'MSJCC (Ratts et al., 2016)', detail: 'Counseling and advocacy interventions: integrating client worldview into counseling' },
    ],
  },
  {
    id: 'nce-s-trt-040',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'easy',
    stem: 'A group practice announces that it is adopting measurement-based care. Which practice BEST describes this approach?',
    options: [
      { id: 'a', text: 'Giving a symptom inventory at intake and again at discharge only', isCorrect: false, rationale: 'Pre-post measurement evaluates results after the fact but cannot guide treatment while it is happening.' },
      { id: 'b', text: 'Routinely scoring brief measures and using them to guide treatment', isCorrect: true, rationale: 'Measurement-based care means regular standardized measurement whose results are reviewed with the client and used to adjust treatment.' },
      { id: 'c', text: 'Basing progress notes on the counselor\'s sense of client improvement', isCorrect: false, rationale: 'Clinical judgment alone tends to miss clients who are not improving or are getting worse.' },
      { id: 'd', text: 'Sending yearly satisfaction surveys to all of the practice\'s clients', isCorrect: false, rationale: 'Satisfaction surveys are program evaluation; they do not track an individual client\'s symptoms over time.' },
    ],
    rationale: 'Measurement-based care is the systematic administration of brief, validated measures (for example, the PHQ-9 or GAD-7) at regular intervals, with results reviewed with the client and used to inform clinical decisions. It improves detection of clients who are not responding.',
    references: [{ source: 'Hays (Assessment)', detail: 'Use of assessment in counseling: monitoring client progress with standardized measures' }],
  },
  {
    id: 'nce-s-trt-041',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'hard',
    stem: 'A counseling center begins giving the Outcome Questionnaire-45 (OQ-45) before every session and sends counselors color-coded alerts based on expected recovery curves. According to research on this kind of routine outcome monitoring with feedback, which clients benefit MOST?',
    options: [
      { id: 'a', text: 'Clients who are improving faster than their expected recovery curve', isCorrect: false, rationale: 'On-track clients do about as well with or without feedback; they are not where the largest gains appear.' },
      { id: 'b', text: 'Clients whose intake scores fell within the normal, nonclinical range', isCorrect: false, rationale: 'Clients starting in the functional range have little room to improve, so feedback adds little for them.' },
      { id: 'c', text: 'Clients in brief treatment who are seen for only one or two sessions', isCorrect: false, rationale: 'Feedback needs repeated measurement over time to identify a trajectory and prompt a change in course.' },
      { id: 'd', text: 'Clients flagged as not on track, who are at risk of deteriorating', isCorrect: true, rationale: 'Feedback alerts help counselors notice and respond to not-on-track clients, improving their outcomes and reducing deterioration.' },
    ],
    rationale: 'The OQ-45 measures symptom distress, interpersonal relations and social role functioning. Lambert and colleagues found that giving counselors feedback on clients predicted to be not on track, especially paired with clinical support tools that review alliance, motivation and supports, improved outcomes and reduced deterioration. Counselors on their own tend to underestimate which clients are getting worse.',
    references: [{ source: 'Lambert (Outcome Monitoring)', detail: 'OQ-45 feedback and alerts for clients not on track' }, { source: 'Hays (Assessment)', detail: 'Outcome assessment and routine outcome monitoring' }],
  },
  {
    id: 'nce-s-trt-042',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'medium',
    stem: 'A 56-year-old client\'s scores on a weekly anxiety measure have risen by more than the measure\'s reliable change index since intake, and she arrives at session five looking tense. How should the counselor respond to this deterioration?',
    options: [
      { id: 'a', text: 'Keep the current plan, since symptoms often worsen before improving', isCorrect: false, rationale: 'Assuming early worsening is expected ignores the warning sign; reliable deterioration predicts poor outcome if unaddressed.' },
      { id: 'b', text: 'Discharge her and refer elsewhere because treatment is not working', isCorrect: false, rationale: 'Abrupt discharge without exploring the cause is premature and risks abandonment.' },
      { id: 'c', text: 'Review scores with her, explore causes and revise the plan together', isCorrect: true, rationale: 'Sharing the data, checking the alliance, stressors and fit of the plan, and adjusting collaboratively is the recommended response.' },
      { id: 'd', text: 'Stop giving the measure, because her rising scores may upset her more', isCorrect: false, rationale: 'Dropping measurement removes the information needed to respond; the scores should be discussed openly.' },
    ],
    rationale: 'Reliable deterioration on an outcome measure is a signal to act, not to wait. The counselor discusses the change with the client, assesses risk, explores the alliance, life events and treatment fit, and adjusts the plan, consulting or referring for added services if needed. Documenting the change and the response is part of good practice.',
    references: [
      { source: 'Hays (Assessment)', detail: 'Monitoring progress: reliable change and responding to nonresponse' },
      { source: 'Wiger (Documentation)', detail: 'Progress notes and treatment plan updates when progress stalls or reverses' },
    ],
  },
  {
    id: 'nce-s-trt-043',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'safety planning',
    difficulty: 'medium',
    stem: 'A 28-year-old client had a suicidal crisis over the weekend. He did not use his safety plan, saying it "didn\'t feel real" and that he had forgotten where he put it. He is now safe and engaged. What should the counselor do with the plan?',
    options: [
      { id: 'a', text: 'Revise it with him, find the barriers and make each step more usable', isCorrect: true, rationale: 'Safety plans are living documents; reviewing what got in the way and rewriting steps in his words makes the plan more usable.' },
      { id: 'b', text: 'Replace it with a written no-suicide contract that he agrees to sign', isCorrect: false, rationale: 'No-suicide contracts lack evidence of preventing suicide and do not give the client coping steps.' },
      { id: 'c', text: 'Set the plan aside, since he has shown that safety planning fails him', isCorrect: false, rationale: 'One unused plan points to barriers to fix, not a reason to abandon an evidence-supported intervention.' },
      { id: 'd', text: 'Keep the original plan but tell him to read it once a day as homework', isCorrect: false, rationale: 'Repeating an unchanged plan ignores why it failed; it needs collaborative revision first.' },
    ],
    rationale: 'The Stanley-Brown Safety Planning Intervention is developed collaboratively, written in the client\'s own words, kept somewhere easy to reach (such as a phone), and reviewed and revised after crises. Asking what got in the way of using each step lets the counselor and client make the plan realistic.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Reviewing and revising the safety plan; identifying barriers to using each step' }],
  },
  {
    id: 'nce-s-trt-044',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'safety planning',
    difficulty: 'easy',
    stem: 'While adding crisis resources to a safety plan, a 17-year-old client asks what happens if she contacts 988. Which description is accurate?',
    options: [
      { id: 'a', text: 'It is a line that sends police to the caller\'s location on every contact', isCorrect: false, rationale: 'Most 988 contacts are resolved by phone, text or chat; emergency dispatch is reserved for imminent danger.' },
      { id: 'b', text: 'It connects her by call, text or chat to trained crisis counselors 24/7', isCorrect: true, rationale: '988 Suicide and Crisis Lifeline offers call, text and chat access to trained crisis counselors at any hour.' },
      { id: 'c', text: 'It is reserved for people who are in the middle of a suicide attempt', isCorrect: false, rationale: '988 serves anyone in suicidal, mental health or substance use crisis, or worried about someone else.' },
      { id: 'd', text: 'It is a text-only service that answers messages during business hours', isCorrect: false, rationale: '988 is available by phone, text and chat around the clock.' },
    ],
    rationale: 'The 988 Suicide and Crisis Lifeline became the national three-digit number in the United States in July 2022. It routes calls, texts and chats to trained crisis counselors 24 hours a day. In a Stanley-Brown safety plan it belongs in the step listing professionals and agencies to contact in a crisis.',
    references: [{ source: 'SAMHSA 988 Lifeline', detail: '988 by call, text or chat, 24/7' }, { source: 'Stanley-Brown SPI', detail: 'Step 5: professionals and agencies to contact in a crisis' }],
  },
  {
    id: 'nce-s-trt-045',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'easy',
    stem: 'A counselor writes this objective for a client with panic disorder: "Client will reduce panic attacks from four per week to one or fewer per week, as recorded in a daily panic log." Which SMART element is missing?',
    options: [
      { id: 'a', text: 'A specific behavior that is targeted for change', isCorrect: false, rationale: 'The objective names a specific behavior: the frequency of panic attacks.' },
      { id: 'b', text: 'A way to measure progress toward the objective', isCorrect: false, rationale: 'The daily panic log and the counts per week make the objective measurable.' },
      { id: 'c', text: 'A target that is realistic for this client', isCorrect: false, rationale: 'Reducing attacks to one or fewer per week is a reasonable, attainable target for treated panic disorder.' },
      { id: 'd', text: 'A time frame for reaching the stated target', isCorrect: true, rationale: 'The objective gives no date or number of weeks, so it is not time-bound.' },
    ],
    rationale: 'SMART objectives are specific, measurable, achievable (attainable), relevant and time-bound. Adding a time frame, such as "within 10 weeks," tells the client and counselor when to judge whether the objective was met and supports documentation of medical necessity and progress.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plans: writing behaviorally measurable, time-bound objectives' }],
  },
  {
    id: 'nce-s-trt-046',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'matching level of care to need',
    difficulty: 'hard',
    stem: 'A 34-year-old client with severe depression has worsened despite three weeks in an intensive outpatient program (three hours, three days a week). He is not suicidal, lives with a supportive spouse, and can stay safe at night, but he needs structured treatment most of each weekday. Which level of care BEST fits?',
    options: [
      { id: 'a', text: 'Weekly individual outpatient counseling plus a medication review', isCorrect: false, rationale: 'This is less intensive than the IOP he is already failing in, so it would be a step down when he needs a step up.' },
      { id: 'b', text: 'Continued IOP at the same schedule for another three weeks', isCorrect: false, rationale: 'He is worsening at this intensity; continuing unchanged does not match his increased need.' },
      { id: 'c', text: 'A partial hospitalization program attended most of each weekday', isCorrect: true, rationale: 'PHP offers several hours of daily structured treatment while he returns home at night, matching his need without 24-hour care.' },
      { id: 'd', text: 'Admission to a locked inpatient psychiatric unit for stabilization', isCorrect: false, rationale: 'He has no imminent risk and can stay safe at home, so 24-hour inpatient care would be more restrictive than needed.' },
    ],
    rationale: 'Levels of care run from outpatient to intensive outpatient (about 9 or more hours a week for adults), partial hospitalization (about 20 or more hours a week, usually most of each weekday), and 24-hour residential or inpatient care. The best match is the least restrictive level that meets current need; worsening in IOP without imminent danger points to PHP.',
    references: [{ source: 'LOCUS (AACP)', detail: 'Level-of-care intensity: intensive outpatient versus partial hospitalization' }],
  },
  {
    id: 'nce-s-trt-047',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'Which client presentation MOST clearly meets criteria for inpatient psychiatric hospitalization rather than a less restrictive level of care?',
    options: [
      { id: 'a', text: 'A man with chronic passive death wishes, no plan, and strong supports', isCorrect: false, rationale: 'Passive ideation without plan or intent, with supports, can usually be managed in outpatient care with safety planning.' },
      { id: 'b', text: 'A woman with a plan, intent and access to means who cannot stay safe', isCorrect: true, rationale: 'Imminent risk with a plan, intent, access to means and inability to maintain safety requires 24-hour protective care.' },
      { id: 'c', text: 'A teen with worsening grades and conflict who refuses to go to school', isCorrect: false, rationale: 'Functional decline without imminent danger calls for outpatient or intensive outpatient services, not hospitalization.' },
      { id: 'd', text: 'A man with panic attacks who missed work twice this month from fear', isCorrect: false, rationale: 'Panic with some missed work is treated effectively on an outpatient basis.' },
    ],
    rationale: 'Inpatient hospitalization is reserved for clients who are an imminent danger to themselves or others, or who are so impaired they cannot care for themselves, and who cannot be kept safe at a less restrictive level. Suicidal ideation with a plan, intent, access to means and an inability to engage in safety planning is the classic indication.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Crisis counseling: suicide risk and the decision to hospitalize' }],
  },
  {
    id: 'nce-s-trt-048',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'medium',
    stem: 'A 20-year-old client in counseling for perfectionism mentions that she has been vomiting after most meals, has lost 15 pounds in two months, and feels dizzy when she stands up. The counselor has no eating disorder training. What is the BEST course of action?',
    options: [
      { id: 'a', text: 'Continue the current work and add eating concerns to future goals', isCorrect: false, rationale: 'Purging with rapid weight loss and dizziness signals possible medical danger that cannot wait for future sessions.' },
      { id: 'b', text: 'End counseling now and give her a list of eating disorder programs', isCorrect: false, rationale: 'Abruptly ending services without a coordinated transition risks abandonment.' },
      { id: 'c', text: 'Read about eating disorders and begin treating them in next session', isCorrect: false, rationale: 'Reading alone does not provide the training and supervision needed to practice within competence.' },
      { id: 'd', text: 'Arrange a prompt medical exam and specialist referral with a release', isCorrect: true, rationale: 'Her symptoms need urgent medical evaluation, and care should be coordinated with a qualified specialist with her consent.' },
    ],
    rationale: 'Purging, rapid weight loss and dizziness can indicate electrolyte imbalance or other medical instability, so a prompt medical evaluation comes first. Because eating disorder treatment falls outside this counselor\'s competence, the counselor coordinates a referral to a qualified provider with a signed release, supporting the transition rather than abandoning the client.',
    references: [{ source: 'ACA Code of Ethics', detail: 'C.2.a Boundaries of Competence; A.11.a Competence Within Termination and Referral' }],
  },
  {
    id: 'nce-s-trt-049',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'easy',
    stem: 'A 42-year-old client is completing an intensive outpatient program for depression and will step down to weekly counseling. Which aftercare step does the MOST to reduce the risk that he drops out after discharge?',
    options: [
      { id: 'a', text: 'Book his first outpatient visit with a named counselor before he leaves', isCorrect: true, rationale: 'A confirmed appointment with a named provider, made before discharge, is a warm handoff that improves follow-through.' },
      { id: 'b', text: 'Give him a list of local counselors to call once he feels he needs one', isCorrect: false, rationale: 'Leaving the client to make contact on his own increases the chance that no follow-up happens.' },
      { id: 'c', text: 'Tell him to return to the program if symptoms come back after discharge', isCorrect: false, rationale: 'This plans only for relapse and leaves a gap in continuing care.' },
      { id: 'd', text: 'Mail a copy of his discharge summary to his home address after he leaves', isCorrect: false, rationale: 'A summary sent to the client does not connect him to the next provider.' },
    ],
    rationale: 'The period right after leaving a more intensive level of care carries elevated risk of disengagement and relapse. Effective aftercare planning schedules the next appointment before discharge, shares records with the receiving provider with consent, and updates the safety and relapse prevention plans.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Discharge summaries and aftercare recommendations' }],
    reviewNote: 'Warm-handoff and pre-discharge scheduling are standard continuity-of-care practice; confirm Wiger is the best fit or cite a SAMHSA continuity-of-care source.',
  },
  {
    id: 'nce-s-trt-050',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'easy',
    stem: 'A 50-year-old client was referred by his physician for heavy cannabis use. He says, "It helps me relax. I don\'t see what the problem is." Which intervention BEST matches his stage of change?',
    options: [
      { id: 'a', text: 'Help him set a quit date and list strategies for handling cravings', isCorrect: false, rationale: 'Quit dates and coping plans are action-stage tasks; pushing them now tends to raise resistance.' },
      { id: 'b', text: 'Teach relapse prevention skills for high-risk situations he may face', isCorrect: false, rationale: 'Relapse prevention fits the action and maintenance stages, after change has begun.' },
      { id: 'c', text: 'Build rapport and offer nonjudgmental feedback to raise awareness', isCorrect: true, rationale: 'In precontemplation, consciousness raising and nonconfrontational feedback help the client begin to consider change.' },
      { id: 'd', text: 'Confront his denial firmly so that he accepts that he has a problem', isCorrect: false, rationale: 'Confrontation increases defensiveness and is not supported for clients in precontemplation.' },
    ],
    rationale: 'A client who sees no problem is in precontemplation. Stage-matched work at this point builds the relationship, raises awareness through information and personalized feedback, and explores the client\'s own view of the behavior. Action-oriented tasks fit later stages.',
    references: [
      { source: 'Transtheoretical Model', detail: 'Precontemplation: consciousness raising and stage-matched processes of change' },
      { source: 'Miller & Rollnick (MI)', detail: 'Avoiding the righting reflex and reducing discord' },
    ],
  },
  {
    id: 'nce-s-trt-051',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'hard',
    stem: 'A counselor uses a decisional balance exercise with a client who is weighing whether to stop gambling. According to research on the Transtheoretical Model, how does decisional balance typically shift as people move from precontemplation toward action?',
    options: [
      { id: 'a', text: 'The cons of changing rise steadily until they overtake the pros', isCorrect: false, rationale: 'This reverses the pattern; perceived cons of change tend to decrease as people progress.' },
      { id: 'b', text: 'The pros of changing increase until they come to outweigh the cons', isCorrect: true, rationale: 'Pros of change rise across stages and typically cross over the cons before the action stage.' },
      { id: 'c', text: 'Pros and cons both stay stable, and only self-efficacy shifts', isCorrect: false, rationale: 'Self-efficacy does rise, but decisional balance also shifts in a predictable way across stages.' },
      { id: 'd', text: 'Pros and cons drop together as the client stops thinking about it', isCorrect: false, rationale: 'Movement toward action involves more, not less, weighing of the pros of change.' },
    ],
    rationale: 'Decisional balance is the weighing of the pros and cons of changing. In precontemplation the cons outweigh the pros; the two are roughly balanced in contemplation, which feeds ambivalence; and the pros come to outweigh the cons before action. Prochaska described the pros as rising more steeply than the cons fall (the strong and weak principles).',
    references: [{ source: 'Transtheoretical Model', detail: 'Decisional balance across the stages of change; strong and weak principles of progress' }],
  },
];
