// tools/nce/seed/treatment-1.js — Treatment Planning (incl. research & program evaluation)
module.exports = [
  {
    id: 'nce-s-trt-001',
    reviewNote: 'Wiger reference detail describes the concept, not an exact chapter title.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'easy',
    stem: 'A counselor is writing a treatment plan for a 34-year-old client with social anxiety. Which objective is BEST written according to SMART criteria?',
    options: [
      { id: 'a', text: 'Client will feel much more confident in social settings by the end of treatment.', isCorrect: false, rationale: 'Feeling "more confident" is not observable or measurable, and "end of treatment" is not a specific time frame.' },
      { id: 'b', text: 'Client will start one conversation with a coworker at least 3 days a week within 6 weeks.', isCorrect: true, rationale: 'This is specific, measurable (frequency count), achievable, relevant to social anxiety, and time-bound (6 weeks).' },
      { id: 'c', text: 'Client will understand the cognitive roots of social anxiety and work through them fully.', isCorrect: false, rationale: '"Understand" and "work through" are vague internal processes with no measurable criterion or deadline.' },
      { id: 'd', text: 'Client will attend weekly counseling sessions and complete homework as the counselor assigns.', isCorrect: false, rationale: 'Attendance and compliance describe the treatment process, not a measurable change in the presenting problem.' },
    ],
    rationale: 'SMART objectives are Specific, Measurable, Achievable, Relevant and Time-bound. A good objective names an observable behavior, a criterion for success, and a deadline, so progress can be tracked and the plan revised. Vague feeling states and process statements (attendance) do not meet the standard.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plans: behaviorally measurable goals and objectives' }],
  },
  {
    id: 'nce-s-trt-002',
    reviewNote: 'ASAM Criteria 4th ed. (2023) renamed some levels; confirm the level-of-care wording is current.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A 41-year-old client with an alcohol use disorder has relapsed twice while attending weekly outpatient sessions. There is no withdrawal risk, no acute medical or psychiatric concern, and the client has stable housing and a supportive partner. Which level of care is MOST appropriate?',
    options: [
      { id: 'a', text: 'Medically managed intensive inpatient treatment in a hospital setting', isCorrect: false, rationale: 'Hospital-level care is for severe, unstable withdrawal or acute medical/psychiatric needs, none of which are present.' },
      { id: 'b', text: 'Long-term residential treatment with 24-hour structure and support', isCorrect: false, rationale: 'Residential care is more restrictive than needed for a client with stable housing and a supportive recovery environment.' },
      { id: 'c', text: 'An intensive outpatient program with several sessions per week', isCorrect: true, rationale: 'Repeated relapse despite weekly outpatient care, with no withdrawal, medical or housing barriers, points to a step up to the next more intensive outpatient level.' },
      { id: 'd', text: 'Continue weekly outpatient sessions with no change to the treatment plan', isCorrect: false, rationale: 'Repeated relapse at the current intensity signals that the present level is not meeting the client\'s needs.' },
    ],
    rationale: 'Placement criteria such as the ASAM Criteria match clients to the least restrictive level of care that safely meets their needs across multiple dimensions (withdrawal, medical, emotional, readiness, relapse potential, recovery environment). When a client is not progressing at one level and has no acute risks, the usual step is to the next more intensive level, not a jump to residential or hospital care.',
    references: [{ source: 'ASAM Criteria', detail: 'Multidimensional assessment and least restrictive level of care; outpatient vs intensive outpatient' }],
  },
  {
    id: 'nce-s-trt-003',
    reviewNote: 'VA/DoD 2023 reference detail is paraphrased; confirm wording.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'medium',
    stem: 'A 29-year-old veteran meets criteria for posttraumatic stress disorder after a combat deployment. According to major clinical practice guidelines, which psychotherapy approach has the strongest research support as a first-line treatment?',
    options: [
      { id: 'a', text: 'Trauma-focused therapy such as cognitive processing therapy or prolonged exposure', isCorrect: true, rationale: 'APA and VA/DoD guidelines give their strongest recommendations to trauma-focused therapies such as CPT and PE.' },
      { id: 'b', text: 'A single session of psychological debriefing held soon after returning home', isCorrect: false, rationale: 'Single-session debriefing is not recommended; it has not been shown to prevent or treat PTSD and may be harmful.' },
      { id: 'c', text: 'Open-ended nondirective supportive counseling focused on current life stressors', isCorrect: false, rationale: 'Nondirective supportive counseling is often used as a control condition and is not a first-line PTSD treatment.' },
      { id: 'd', text: 'Progressive muscle relaxation training used alone as the primary treatment', isCorrect: false, rationale: 'Relaxation may help with arousal, but used alone it lacks the support of trauma-focused treatments for PTSD.' },
    ],
    rationale: 'Evidence-based treatment selection integrates the best research evidence with clinical expertise and client preferences. For PTSD, the APA (2017) and VA/DoD guidelines recommend trauma-focused psychotherapies such as cognitive processing therapy and prolonged exposure as first-line treatments.',
    references: [
      { source: 'APA CPG', detail: 'Clinical Practice Guideline for the Treatment of PTSD (2017): CPT, PE, CBT and CT strongly recommended' },
      { source: 'VA/DoD CPG', detail: 'Management of PTSD and Acute Stress Disorder: trauma-focused psychotherapy as first-line treatment' },
    ],
  },
  {
    id: 'nce-s-trt-004',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'easy',
    stem: 'A counselor has completed an intake with a 52-year-old Korean American client who reports grief and insomnia after her husband\'s death. What is the BEST way for the counselor to develop the treatment plan?',
    options: [
      { id: 'a', text: 'Write the plan alone based on the diagnosis, then review it with the client next week', isCorrect: false, rationale: 'Presenting a finished plan treats the client as a recipient rather than a partner and misses her priorities.' },
      { id: 'b', text: 'Use a standard grief protocol so the client receives the same plan as other clients', isCorrect: false, rationale: 'A one-size-fits-all plan ignores individual goals, cultural values and preferences.' },
      { id: 'c', text: 'Ask the client\'s adult children what goals they would like their mother to work on', isCorrect: false, rationale: 'Family input may be welcome with consent, but the client herself is the primary partner in setting her goals.' },
      { id: 'd', text: 'Work with the client to identify her goals and the methods she finds acceptable', isCorrect: true, rationale: 'Collaborative planning engages the client in choosing goals and methods, respecting her values and culture.' },
    ],
    rationale: 'Treatment plans should be developed jointly with the client. Collaboration respects autonomy, incorporates cultural values and preferences, and increases engagement and follow-through. The ACA Code directs counselors and clients to work jointly in devising counseling plans that offer reasonable promise of success.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.1.c Counseling Plans' }],
  },
  {
    id: 'nce-s-trt-005',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'medium',
    stem: 'A counselor gives a 23-year-old client the PHQ-9 at every session. After eight sessions of treatment for depression, the client\'s scores have not meaningfully changed from intake. What should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Stop giving the PHQ-9, since repeated testing seems to be discouraging the client', isCorrect: false, rationale: 'Dropping the measure removes the very data that revealed the lack of progress.' },
      { id: 'b', text: 'Review the scores with the client and revise the treatment plan together', isCorrect: true, rationale: 'Measurement-based care uses nonresponse as a signal to discuss progress with the client and adjust the plan.' },
      { id: 'c', text: 'Continue the same approach unchanged, since depression often improves slowly', isCorrect: false, rationale: 'Ignoring eight sessions of flat scores delays a needed change in treatment.' },
      { id: 'd', text: 'Refer the client out at once, since the lack of change shows a poor counselor fit', isCorrect: false, rationale: 'Flat scores call for review and adjustment first; immediate referral is premature.' },
    ],
    rationale: 'Routine outcome monitoring with a standardized measure lets the counselor detect clients who are not responding. Feedback on scores should be shared with the client and used to revisit goals, interventions or level of care. Measurement-based care has been shown to improve outcomes, especially for clients at risk of treatment failure.',
    references: [{ source: 'Hays (Assessment)', detail: 'Outcome assessment and progress monitoring with standardized measures' }],
  },
  {
    id: 'nce-s-trt-006',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'medium',
    stem: 'During a first session, a 47-year-old client mentions that she also sees a psychiatrist who prescribes her antidepressant. What should the counselor do to coordinate care?',
    options: [
      { id: 'a', text: 'Call the psychiatrist right away to share the intake findings and diagnosis', isCorrect: false, rationale: 'Sharing information without the client\'s authorization breaches confidentiality.' },
      { id: 'b', text: 'Ask the client to stop seeing the psychiatrist to avoid conflicting treatment', isCorrect: false, rationale: 'Medication management and counseling are complementary; there is no basis for asking her to stop.' },
      { id: 'c', text: 'Request the client\'s written consent to inform and consult with the psychiatrist', isCorrect: true, rationale: 'The ACA Code directs counselors to request a release so they can inform the other professional and collaborate.' },
      { id: 'd', text: 'Note the psychiatrist in the file and leave all contact entirely up to the client', isCorrect: false, rationale: 'This is passive; counselors are expected to seek permission to coordinate with other providers.' },
    ],
    rationale: 'When counselors learn that a client is in a professional relationship with another mental health professional, they request a release to inform that professional and work toward a collaborative relationship. Coordination improves safety and consistency of care, while written consent protects confidentiality.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.3 Clients Served by Others' }],
  },
  {
    id: 'nce-s-trt-007',
    reviewNote: 'Wiger reference detail describes the concept, not an exact chapter title.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'medium',
    stem: 'A program director is training new counselors at a community mental health agency. When should discharge and aftercare planning ideally begin for a new client?',
    options: [
      { id: 'a', text: 'At intake, revisiting the plan throughout the course of treatment', isCorrect: true, rationale: 'Planning for discharge from the start keeps treatment goal-directed and prepares the client for transition.' },
      { id: 'b', text: 'In the final session, once the client has met every treatment goal', isCorrect: false, rationale: 'Waiting until the last session leaves too little time to arrange supports and aftercare.' },
      { id: 'c', text: 'When the insurer signals that authorized sessions are running out', isCorrect: false, rationale: 'Letting payer limits drive discharge timing is reactive and can leave gaps in care.' },
      { id: 'd', text: 'Only after the client asks to end treatment or stops attending', isCorrect: false, rationale: 'This leaves aftercare to chance and misses the chance to plan termination together.' },
    ],
    rationale: 'Discharge and aftercare planning should begin at admission and be updated as treatment progresses. Early planning defines what successful completion looks like, identifies community supports and step-down services, and reduces the risk of relapse or abrupt termination.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Discharge planning and the discharge summary' }],
  },
  {
    id: 'nce-s-trt-008',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'safety planning',
    difficulty: 'medium',
    stem: 'A counselor is completing a Stanley-Brown Safety Planning Intervention with a 19-year-old college student who has recent suicidal ideation. Which step does the safety plan address FIRST?',
    options: [
      { id: 'a', text: 'Listing professionals and crisis lines to contact in an emergency', isCorrect: false, rationale: 'Professional and crisis contacts come later in the plan, after self-directed and social steps.' },
      { id: 'b', text: 'Making the environment safe by limiting access to lethal means', isCorrect: false, rationale: 'Means safety is a key part of the plan but is addressed as the final step.' },
      { id: 'c', text: 'Naming people the student can ask directly for help in a crisis', isCorrect: false, rationale: 'Reaching out to trusted people for help follows warning signs and internal coping.' },
      { id: 'd', text: 'Recognizing personal warning signs that a crisis may be developing', isCorrect: true, rationale: 'The plan begins with identifying warning signs so the client knows when to use the plan.' },
    ],
    rationale: 'The Stanley-Brown Safety Plan proceeds in order: (1) warning signs, (2) internal coping strategies, (3) people and social settings that provide distraction, (4) people to ask for help, (5) professionals and agencies to contact, and (6) making the environment safe. Recognizing warning signs comes first because it tells the client when to begin using the plan.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Six-step safety plan: Step 1, recognizing warning signs' }],
  },
  {
    id: 'nce-s-trt-009',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'easy',
    stem: 'A 38-year-old client says, "I know my drinking is hurting my marriage, and part of me wants to cut back, but I\'m just not sure I\'m ready to give it up." Which stage of change does this statement BEST reflect?',
    options: [
      { id: 'a', text: 'Precontemplation', isCorrect: false, rationale: 'In precontemplation the person does not see a problem or intend to change; this client recognizes the problem.' },
      { id: 'b', text: 'Contemplation', isCorrect: true, rationale: 'Acknowledging the problem while feeling ambivalent about changing is the hallmark of contemplation.' },
      { id: 'c', text: 'Preparation', isCorrect: false, rationale: 'Preparation involves a commitment to act soon and small steps toward change, which are absent here.' },
      { id: 'd', text: 'Action', isCorrect: false, rationale: 'Action involves actively modifying the behavior, which this client has not begun.' },
    ],
    rationale: 'In the Transtheoretical Model, contemplation is marked by awareness that a problem exists and serious thought about change, combined with ambivalence and no firm commitment. Counselors often use motivational interviewing to explore and resolve that ambivalence.',
    references: [{ source: 'Transtheoretical Model', detail: 'Stages of change: contemplation and ambivalence' }],
  },
  {
    id: 'nce-s-trt-010',
    reviewNote: 'Action vs. maintenance rests on the conventional ~6-month line in the Transtheoretical Model.',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'hard',
    stem: 'A 60-year-old client stopped smoking four months ago. He uses nicotine gum, avoids places where he used to smoke, and calls a friend when cravings hit. According to Prochaska and DiClemente, which stage is he in?',
    options: [
      { id: 'a', text: 'Preparation', isCorrect: false, rationale: 'Preparation precedes the behavior change; this client has already quit.' },
      { id: 'b', text: 'Maintenance', isCorrect: false, rationale: 'Maintenance generally begins after about six months of sustained change; he is at four months.' },
      { id: 'c', text: 'Action', isCorrect: true, rationale: 'He has changed the behavior within the past six months and is actively using change strategies.' },
      { id: 'd', text: 'Contemplation', isCorrect: false, rationale: 'Contemplation involves thinking about change without acting; he has already acted.' },
    ],
    rationale: 'The action stage covers roughly the first six months after a person has made an overt change in behavior, when effort and relapse risk are highest. Maintenance begins once the change has been sustained for more than about six months and focuses on preventing relapse.',
    references: [{ source: 'Transtheoretical Model', detail: 'Action vs maintenance: the six-month criterion' }],
  },
  {
    id: 'nce-s-trt-011',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'medium',
    stem: 'Three months into a new school-based anger management group, a counselor gathers feedback from students and teachers so she can refine the sessions while the program is still running. This is an example of which type of evaluation?',
    options: [
      { id: 'a', text: 'Formative evaluation', isCorrect: true, rationale: 'Formative evaluation occurs during implementation to improve the program as it runs.' },
      { id: 'b', text: 'Summative evaluation', isCorrect: false, rationale: 'Summative evaluation judges overall effectiveness or outcomes after the program is completed.' },
      { id: 'c', text: 'Needs assessment', isCorrect: false, rationale: 'A needs assessment happens before a program is designed, to identify gaps and priorities.' },
      { id: 'd', text: 'Cost-benefit analysis', isCorrect: false, rationale: 'Cost-benefit analysis compares program costs with monetary value of outcomes, not process feedback.' },
    ],
    rationale: 'Formative evaluation is conducted while a program is under way to give feedback for improvement. Summative evaluation is conducted at the end to judge whether the program achieved its goals and should be continued, expanded or ended.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Program evaluation: formative vs summative evaluation' }],
  },
  {
    id: 'nce-s-trt-012',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'easy',
    stem: 'Before creating any new services, a rural counseling center surveys residents, local physicians and school staff to find out which mental health concerns are most common and which services are missing. What is the center conducting?',
    options: [
      { id: 'a', text: 'An outcome evaluation', isCorrect: false, rationale: 'Outcome evaluation measures the effects of an existing program; no program exists yet.' },
      { id: 'b', text: 'A process evaluation', isCorrect: false, rationale: 'Process evaluation examines how an existing program is being delivered.' },
      { id: 'c', text: 'A fidelity review', isCorrect: false, rationale: 'A fidelity review checks whether a program is delivered as designed, which requires a program in place.' },
      { id: 'd', text: 'A needs assessment', isCorrect: true, rationale: 'Gathering data on community problems and service gaps before planning services is a needs assessment.' },
    ],
    rationale: 'A needs assessment systematically identifies the gap between current conditions and desired conditions in a population, using surveys, key informants, focus groups or existing data. It is typically the first step in program planning and guides which services to develop.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Needs assessment as the first phase of program evaluation' }],
  },
  {
    id: 'nce-s-trt-013',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'easy',
    stem: 'A school counselor records a student\'s disruptive outbursts during baseline, introduces a token system, removes it, and then reintroduces it (an ABAB design). What is the main purpose of the withdrawal phase?',
    options: [
      { id: 'a', text: 'To let the student rest so the token system does not lose its appeal', isCorrect: false, rationale: 'Withdrawal is not about preventing satiation; it is a test of experimental control.' },
      { id: 'b', text: 'To show that behavior changes when and only when the treatment changes', isCorrect: true, rationale: 'A return toward baseline when treatment is removed, and improvement when it returns, supports a causal link.' },
      { id: 'c', text: 'To compare the student\'s behavior with a randomly assigned control group', isCorrect: false, rationale: 'Single-subject designs use the person as his or her own control; there is no separate group.' },
      { id: 'd', text: 'To produce enough data points to compute a reliable correlation value', isCorrect: false, rationale: 'The goal of the reversal is to demonstrate experimental control, not to compute a correlation.' },
    ],
    rationale: 'In an ABAB (reversal or withdrawal) single-subject design, behavior is measured at baseline (A), during treatment (B), after treatment is withdrawn (A), and after it is reinstated (B). If behavior worsens on withdrawal and improves again on reinstatement, the counselor has stronger evidence that the intervention, not some other factor, caused the change.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Single-subject designs: AB and ABAB (withdrawal) designs' }],
  },
  {
    id: 'nce-s-trt-014',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'medium',
    stem: 'A researcher delivers a new career-readiness curriculum to one intact ninth-grade class and uses a second existing class at the same school as a comparison. Both classes complete pretests and posttests. Which design is this?',
    options: [
      { id: 'a', text: 'A true experimental pretest-posttest control group design', isCorrect: false, rationale: 'A true experiment requires random assignment of participants to conditions, which did not occur.' },
      { id: 'b', text: 'A single-subject multiple-baseline design across settings', isCorrect: false, rationale: 'Single-subject designs track individuals over repeated phases, not two classes compared once.' },
      { id: 'c', text: 'A quasi-experimental nonequivalent control group design', isCorrect: true, rationale: 'Using intact groups without random assignment, with pre- and posttests, is a nonequivalent group quasi-experiment.' },
      { id: 'd', text: 'A correlational design examining two naturally linked variables', isCorrect: false, rationale: 'The researcher manipulated an independent variable (the curriculum), so this is not correlational.' },
    ],
    rationale: 'The defining feature of a true experiment is random assignment to conditions. When a researcher manipulates an independent variable but uses pre-existing groups, the design is quasi-experimental. Pretests help assess initial group differences, but selection remains a threat to internal validity.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Experimental vs quasi-experimental designs; random assignment' }],
  },
  {
    id: 'nce-s-trt-015',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'hard',
    stem: 'A counselor selects the 15 students with the highest scores on a test anxiety scale for a six-week group. There is no comparison group, all students complete the group, and nothing notable happens at school during that time. Posttest scores are lower. Which threat to internal validity MOST likely accounts for part of this drop?',
    options: [
      { id: 'a', text: 'Experimental mortality, or attrition of group members', isCorrect: false, rationale: 'All students completed the group, so loss of participants cannot explain the change.' },
      { id: 'b', text: 'History, or outside events occurring during the study period', isCorrect: false, rationale: 'The stem rules out notable outside events during the six weeks.' },
      { id: 'c', text: 'Diffusion of treatment between groups being compared', isCorrect: false, rationale: 'Diffusion requires a comparison group that is exposed to the treatment; there is none.' },
      { id: 'd', text: 'Statistical regression of extreme scores toward the mean', isCorrect: true, rationale: 'Participants selected for extreme scores tend to score closer to the mean on retest even without treatment.' },
    ],
    rationale: 'Statistical regression is a threat to internal validity whenever participants are chosen because of extreme scores. Because no measure is perfectly reliable, extreme scorers tend to move toward the mean on retesting, which can be mistaken for a treatment effect. A comparison group selected the same way helps rule this out.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Threats to internal validity: statistical regression' }],
  },
  {
    id: 'nce-s-trt-016',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'hard',
    stem: 'A researcher sets alpha at .05 and finds p = .03 when comparing a new intervention with treatment as usual, so she rejects the null hypothesis. If the intervention in fact has no real effect, what has occurred?',
    options: [
      { id: 'a', text: 'A Type I error, a false positive finding', isCorrect: true, rationale: 'Rejecting a null hypothesis that is actually true is a Type I error; its probability is set by alpha.' },
      { id: 'b', text: 'A Type II error, a false negative finding', isCorrect: false, rationale: 'A Type II error is failing to reject a false null, missing a real effect; here the null was rejected.' },
      { id: 'c', text: 'A correct decision, since p fell below alpha', isCorrect: false, rationale: 'A p-value below alpha does not guarantee a true effect; if there is none, rejecting the null was an error.' },
      { id: 'd', text: 'A power failure caused by too small a sample', isCorrect: false, rationale: 'Low power raises the risk of Type II errors, not of falsely detecting an effect that does not exist.' },
    ],
    rationale: 'A Type I error (alpha) is rejecting a true null hypothesis, concluding an effect exists when it does not. A Type II error (beta) is failing to reject a false null. The p-value is the probability of results at least this extreme if the null is true; it is not the probability that the null is true, so a significant p can still be a false positive.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Hypothesis testing: Type I and Type II errors, alpha and p-values' }],
  },
  {
    id: 'nce-s-trt-017',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'A study of 4,000 clients finds that a brief online module reduces anxiety scores compared with a waitlist, p < .001, with Cohen\'s d = 0.08. How should a counselor BEST interpret these results?',
    options: [
      { id: 'a', text: 'The module has a large effect, as shown by the very small p-value', isCorrect: false, rationale: 'The p-value reflects sample size as well as effect; it does not indicate magnitude.' },
      { id: 'b', text: 'The difference is statistically significant but practically trivial', isCorrect: true, rationale: 'With a very large sample, tiny effects reach significance; d = 0.08 is well below even a small effect (0.2).' },
      { id: 'c', text: 'The result is likely a Type II error because the sample was so large', isCorrect: false, rationale: 'A Type II error is missing a real effect; here an effect was detected, and large samples reduce Type II risk.' },
      { id: 'd', text: 'The module causes anxiety to drop by about 8 percent for most clients', isCorrect: false, rationale: 'Cohen\'s d is a difference in standard deviation units, not a percentage reduction.' },
    ],
    rationale: 'Statistical significance tells whether an effect is unlikely under the null hypothesis; effect size tells how large it is. Cohen\'s guidelines for d are about 0.2 small, 0.5 medium and 0.8 large. Large samples can make trivial differences significant, so counselors should look at effect size to judge clinical or practical importance.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Effect size (Cohen\'s d) vs statistical significance' }],
  },
];
