// tools/nce/seed/treatment-7.js — Treatment Planning, batch 7
// Hand-authored original items (nce-s-trt-103 … nce-s-trt-119).
module.exports = [
  {
    id: 'nce-s-trt-103',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'medium',
    stem: 'A 40-year-old Filipino American client and his counselor agree on this objective: "Client will cut arguments with his wife by half within eight weeks." Neither of them knows how often the couple argues now. What should the counselor do FIRST so that progress on this objective can be measured?',
    options: [
      { id: 'a', text: 'Have the client log each argument for a week or two to set a baseline', isCorrect: true, rationale: 'A reduction "by half" can only be judged against a known starting rate, so a baseline count is needed first.' },
      { id: 'b', text: 'Change the deadline to twelve weeks so the goal is easier to reach in time', isCorrect: false, rationale: 'A longer timeframe may help attainability, but progress still cannot be measured without a starting point.' },
      { id: 'c', text: 'Replace the objective with a broader goal of building a closer, warmer marriage', isCorrect: false, rationale: 'A broad goal is less measurable than the original objective and does not solve the missing baseline.' },
      { id: 'd', text: 'Ask his wife to rate their marriage at the final session to judge the outcome', isCorrect: false, rationale: 'A single rating at the end gives no starting value to compare against and does not track the stated behavior.' },
    ],
    rationale: 'A measurable objective that names a change, such as cutting a behavior in half, depends on a baseline: a record of how often the behavior happens before treatment. Self-monitoring logs are a simple way to gather that baseline and then keep tracking the same behavior over time. Without a baseline, neither the counselor nor the client can tell whether the target has been met.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plan objectives: measurable behaviors with baseline and target frequencies' }],
  },
  {
    id: 'nce-s-trt-104',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A community mental health center begins using the Level of Care Utilization System (LOCUS) to decide how intensive each adult client\'s services should be. Which of these is one of the dimensions the counselor rates when completing the LOCUS?',
    options: [
      { id: 'a', text: 'Type of insurance and benefit limits', isCorrect: false, rationale: 'Payer coverage is not a LOCUS dimension; the tool rates clinical need, not what a plan will pay for.' },
      { id: 'b', text: 'Intelligence and academic achievement', isCorrect: false, rationale: 'Cognitive and academic testing is not part of the LOCUS rating dimensions.' },
      { id: 'c', text: 'Recovery environment: stress and support', isCorrect: true, rationale: 'The LOCUS rates the recovery environment, scoring both the level of stress and the level of support around the client.' },
      { id: 'd', text: 'The DSM-5-TR diagnostic category by itself', isCorrect: false, rationale: 'The LOCUS is deliberately not driven by diagnosis; it rates risk, functioning and other needs across dimensions.' },
    ],
    rationale: 'The LOCUS rates six dimensions: risk of harm; functional status; medical, addictive and psychiatric co-morbidity; recovery environment (stress and support); treatment and recovery history; and engagement and recovery status. The combined ratings point to a level of care from recovery maintenance up to medically managed residential services. Because placement rests on these dimensions rather than on diagnosis or payer, clients with the same diagnosis can need very different levels of care.',
    references: [{ source: 'LOCUS (AACP)', detail: 'Six evaluation dimensions, including Dimension IV, Recovery Environment (Level of Stress and Level of Support)' }],
  },
  {
    id: 'nce-s-trt-105',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'evidence-based treatment selection',
    difficulty: 'easy',
    stem: 'A counselor tells a colleague, "Evidence-based practice just means I pick whatever manual has the most clinical trials behind it." Which description of evidence-based practice is MOST accurate?',
    options: [
      { id: 'a', text: 'Following a research-tested treatment manual exactly, with no changes for any client', isCorrect: false, rationale: 'Rigid adherence without regard to the client ignores the clinical expertise and client factors that are part of the definition.' },
      { id: 'b', text: 'Combining the best research with clinical expertise and the client\'s culture and wishes', isCorrect: true, rationale: 'Evidence-based practice integrates research evidence, clinical expertise and client characteristics, culture and preferences.' },
      { id: 'c', text: 'Choosing the approach the counselor knows best, as long as clients report satisfaction', isCorrect: false, rationale: 'Familiarity and satisfaction alone leave out the research base, which is one of the three parts of the model.' },
      { id: 'd', text: 'Using only treatments that insurers list as approved for the client\'s current diagnosis', isCorrect: false, rationale: 'Payer approval lists are an administrative matter and are not how evidence-based practice is defined.' },
    ],
    rationale: 'Evidence-based practice is commonly defined as the integration of the best available research with clinical expertise in the context of the client\'s characteristics, culture and preferences. Research support is one leg of the model, not the whole of it. The counselor selects and adapts treatments by weighing all three sources together.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Evidence-based practice: integrating best research evidence, clinical expertise and client characteristics and preferences' }],
  },
  {
    id: 'nce-s-trt-106',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'medium',
    stem: 'A 15-year-old girl has been diagnosed with anorexia nervosa. Her pediatrician reports that she is medically stable for outpatient care, and she lives with both parents, who are eager to help. Which treatment has the strongest support as a first-line approach for her?',
    options: [
      { id: 'a', text: 'Inpatient hospital care until she reaches a healthy weight for her height', isCorrect: false, rationale: 'Inpatient care is reserved for medical instability or failure of outpatient care; she is medically stable.' },
      { id: 'b', text: 'Weekly individual insight-oriented therapy with her parents kept out of it', isCorrect: false, rationale: 'Excluding involved parents goes against guideline advice for young people, where family involvement is central.' },
      { id: 'c', text: 'Nutrition classes alone, with therapy added later if her weight keeps falling', isCorrect: false, rationale: 'Nutrition education alone is not an adequate treatment for anorexia nervosa in adolescents.' },
      { id: 'd', text: 'Family-based treatment in which her parents take charge of restoring her weight', isCorrect: true, rationale: 'Eating-disorder-focused family therapy, in which parents lead refeeding at first, is the first-line treatment for young people.' },
    ],
    rationale: 'For children and adolescents with anorexia nervosa, guidelines such as NICE recommend anorexia-nervosa-focused family therapy as the first-line treatment. In family-based treatment, parents first take charge of refeeding, then gradually hand control of eating back to the teen, and later sessions address normal adolescent development. Higher levels of care are kept for medical instability or when outpatient treatment does not work.',
    references: [{ source: 'NICE guidelines', detail: 'Eating disorders (NG69): anorexia nervosa-focused family therapy as first-line treatment for children and young people' }],
  },
  {
    id: 'nce-s-trt-107',
    domain: 'treatment',
    cacrep: 'professional_orientation',
    topic: 'collaborative treatment planning',
    difficulty: 'easy',
    stem: 'After working out a treatment plan together, a counselor asks a 58-year-old client to read and sign it. The client asks why his signature is needed. What is the MAIN purpose of the client\'s signature on a treatment plan?',
    options: [
      { id: 'a', text: 'It shows that the client took part in the plan and agrees with its goals', isCorrect: true, rationale: 'The signature documents that the client helped shape the plan and agrees with its goals and methods.' },
      { id: 'b', text: 'It binds the client legally to attend each of the sessions in the plan', isCorrect: false, rationale: 'A treatment plan is not a binding contract; clients may change or end treatment.' },
      { id: 'c', text: 'It takes the place of the informed consent form signed at the intake', isCorrect: false, rationale: 'Informed consent is a separate process and document; the plan signature does not replace it.' },
      { id: 'd', text: 'It gives the counselor permission to share the plan with his employer', isCorrect: false, rationale: 'Releasing information to third parties requires a separate, specific authorization.' },
    ],
    rationale: 'Treatment plans are meant to be developed with the client, and the client\'s signature is the usual record that this happened and that the client agrees with the goals, objectives and methods. Payers and auditors often look for it as evidence of collaboration. The signature does not create a legal duty to attend, replace informed consent or authorize disclosures.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plan: client participation and signature documenting agreement' }],
  },
  {
    id: 'nce-s-trt-108',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'medium',
    stem: 'A counselor and a 27-year-old client use goal attainment scaling (GAS) to track progress. For each goal they write five possible outcomes, scored from -2 to +2. At the end of treatment, the client\'s score on one goal is 0. What does this score mean?',
    options: [
      { id: 'a', text: 'There was no change from where the client started', isCorrect: false, rationale: 'A score of 0 is not tied to the starting point; the client\'s level at intake is usually rated below 0.' },
      { id: 'b', text: 'The client gave up on this goal during treatment', isCorrect: false, rationale: 'GAS scores describe levels of outcome; they do not code whether a goal was abandoned.' },
      { id: 'c', text: 'The client reached the expected level of outcome', isCorrect: true, rationale: 'In GAS, 0 is the expected level; -1 and -2 are less than expected and +1 and +2 are more than expected.' },
      { id: 'd', text: 'The client did much better than anyone expected', isCorrect: false, rationale: 'Much better than expected is scored +2, the top of the scale.' },
    ],
    rationale: 'Goal attainment scaling, developed by Kiresuk and Sherman, builds an individual scale for each client goal. The expected outcome is defined as 0, with two levels below (somewhat and much less than expected) and two levels above (somewhat and much more than expected). Because the scales are written for each client, GAS captures individual goals while still producing scores that can be compared and combined.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Outcome evaluation: goal attainment scaling (Kiresuk and Sherman) and its five-point -2 to +2 scale' }],
  },
  {
    id: 'nce-s-trt-109',
    domain: 'treatment',
    cacrep: 'professional_orientation',
    topic: 'coordination of care and referral',
    difficulty: 'hard',
    stem: 'A 34-year-old client asks her counselor at a HIPAA-covered agency to send a summary of her treatment to a state vocational rehabilitation counselor who is helping her find work. The disclosure is not for treatment, payment or health care operations. Which element must the client\'s written authorization include?',
    options: [
      { id: 'a', text: 'A signature by the client that has been notarized and witnessed', isCorrect: false, rationale: 'HIPAA requires the client\'s signature and date but not notarization or a witness.' },
      { id: 'b', text: 'An expiration date or an event that ends the authorization', isCorrect: true, rationale: 'A valid HIPAA authorization must state an expiration date or expiration event, among other core elements.' },
      { id: 'c', text: 'A full list of the client\'s diagnoses and current medications', isCorrect: false, rationale: 'The form must describe the information to be disclosed, but it does not need to list her diagnoses or medications.' },
      { id: 'd', text: 'A statement by the counselor that the disclosure is advisable', isCorrect: false, rationale: 'The counselor\'s endorsement is not a required element; the authorization reflects the client\'s own decision.' },
    ],
    rationale: 'Disclosures outside treatment, payment and health care operations generally need a written authorization from the client. Under the Privacy Rule, a valid authorization describes the information, names who may disclose and who will receive it, states the purpose, gives an expiration date or event, and is signed and dated by the client. It must also tell the client of the right to revoke it in writing and that the recipient may redisclose the information.',
    references: [{ source: 'HIPAA', detail: '45 CFR 164.508(c): core elements and required statements of a valid authorization' }],
  },
  {
    id: 'nce-s-trt-110',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'easy',
    stem: 'A 44-year-old client has met her goals for managing anxiety. She and her counselor agree to move from weekly sessions to every other week, then to one session a month, before ending treatment. What is the MAIN purpose of spacing out the final sessions this way?',
    options: [
      { id: 'a', text: 'To leave room in the schedule for new clients on the agency waitlist', isCorrect: false, rationale: 'Freeing up time may be a side effect, but it is not the clinical reason for fading sessions.' },
      { id: 'b', text: 'To meet insurance limits on the number of sessions allowed each year', isCorrect: false, rationale: 'Payer limits are not mentioned and are not the purpose of a planned taper.' },
      { id: 'c', text: 'To give the counselor more time to write a complete discharge summary', isCorrect: false, rationale: 'Documentation is done regardless of session spacing and does not explain the taper.' },
      { id: 'd', text: 'To let her use her skills on her own while support is still available', isCorrect: true, rationale: 'Tapering lets the client practice independently and bring back any setbacks before services end.' },
    ],
    rationale: 'Gradually spacing out sessions near termination is a common way to prepare for ending. The client gets longer stretches to apply her skills without weekly support, and any difficulties can be worked through in the remaining sessions. This builds confidence and helps keep gains after discharge.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Termination: preparing clients for ending by gradually spacing sessions' }],
  },
  {
    id: 'nce-s-trt-111',
    domain: 'treatment',
    cacrep: 'social_cultural',
    topic: 'safety planning',
    difficulty: 'medium',
    stem: 'A 31-year-old client says her partner has shoved her twice in recent months and is drinking more. She loves him, shares a lease with him and says she is not ready to leave. She worries that things could get worse. What should the counselor do NEXT?',
    options: [
      { id: 'a', text: 'Build a safety plan with her for staying, such as exits, a go-bag and a code word', isCorrect: true, rationale: 'Safety planning that fits her current choice reduces risk and respects her autonomy while violence is ongoing.' },
      { id: 'b', text: 'Tell her that counseling can continue only if she agrees to move to a shelter', isCorrect: false, rationale: 'Making services depend on leaving is coercive and may cut her off from support when risk is rising.' },
      { id: 'c', text: 'Invite her partner to joint sessions so that the couple can learn to argue less', isCorrect: false, rationale: 'Couples work while violence is active can raise danger and frames abuse as a mutual communication problem.' },
      { id: 'd', text: 'Call the police for her so that there is an official record of the shoving', isCorrect: false, rationale: 'Contacting police without her consent breaches confidentiality and can increase danger if the partner learns of it.' },
    ],
    rationale: 'Many survivors of intimate partner violence are not ready or able to leave, and leaving can itself be a time of high danger. The counselor respects her choice and works with her on a safety plan for staying: noting warning signs, planning exits, keeping documents, money and keys ready, and setting up a signal with trusted people. Support continues, and the plan is updated as her situation changes.',
    references: [{ source: 'Kanel (A Guide to Crisis Intervention)', detail: 'Partner violence: safety planning with survivors who remain in the relationship' }],
  },
  {
    id: 'nce-s-trt-112',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'hard',
    stem: 'A 55-year-old client who has smoked since his teens says, "I\'ve tried to quit a dozen times and nothing ever sticks. Some people just can\'t do it, and I\'m one of them, so why bother?" Using DiClemente\'s description of precontemplation, which type of precontemplator does he MOST resemble?',
    options: [
      { id: 'a', text: 'Reluctant', isCorrect: false, rationale: 'Reluctant precontemplators lack knowledge or inertia keeps them from thinking about change; they do not describe repeated failed attempts.' },
      { id: 'b', text: 'Rebellious', isCorrect: false, rationale: 'Rebellious precontemplators resist being told what to do and are invested in their behavior, not hopeless about change.' },
      { id: 'c', text: 'Resigned', isCorrect: true, rationale: 'Resigned precontemplators feel overwhelmed and hopeless after past failures and have given up on the idea of change.' },
      { id: 'd', text: 'Rationalizing', isCorrect: false, rationale: 'Rationalizing precontemplators have reasons why the behavior is not a problem; he accepts it is a problem but feels unable to change.' },
    ],
    rationale: 'DiClemente described four types of precontemplators, often called the four Rs: reluctant, rebellious, resigned and rationalizing. The resigned client has lost hope after many attempts and believes change is out of reach. Counseling for this client focuses on instilling hope, exploring what worked during past attempts and building self-efficacy rather than on persuading him that smoking is harmful.',
    references: [{ source: 'Transtheoretical Model', detail: 'Precontemplation subtypes (DiClemente): reluctant, rebellious, resigned and rationalizing' }],
  },
  {
    id: 'nce-s-trt-113',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'medium',
    stem: 'A 62-year-old client stopped drinking seven years ago. She says she no longer feels any urge to drink, even at family parties or under stress, and is completely confident she will not go back to it. According to Prochaska and DiClemente, which stage does this describe?',
    options: [
      { id: 'a', text: 'Maintenance', isCorrect: false, rationale: 'In maintenance, the person still works to prevent relapse and still has some temptation in high-risk situations.' },
      { id: 'b', text: 'Termination', isCorrect: true, rationale: 'Termination is defined by zero temptation and full self-efficacy across situations, so no effort is needed to avoid relapse.' },
      { id: 'c', text: 'Action', isCorrect: false, rationale: 'Action covers roughly the first six months of changed behavior, when effort and risk of relapse are highest.' },
      { id: 'd', text: 'Preparation', isCorrect: false, rationale: 'Preparation comes before change, when the person intends to act soon and may be taking small steps.' },
    ],
    rationale: 'In the Transtheoretical Model, termination is the stage in which the person has no temptation to return to the old behavior and complete confidence in all situations. Maintenance, which can last for years, still involves active effort to prevent relapse. Many people with addictive behaviors stay in maintenance long-term rather than reaching termination.',
    references: [{ source: 'Transtheoretical Model', detail: 'Termination stage: zero temptation and 100% self-efficacy, contrasted with maintenance' }],
  },
  {
    id: 'nce-s-trt-114',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'easy',
    stem: 'To plan new services, a counseling agency interviews a small number of people well placed to know local needs: the police chief, two school principals, a pastor and a pediatrician. Which needs assessment approach is the agency using?',
    options: [
      { id: 'a', text: 'Community forum', isCorrect: false, rationale: 'A community forum is an open public meeting where any resident may speak, not chosen interviews.' },
      { id: 'b', text: 'Rates under treatment', isCorrect: false, rationale: 'This approach counts people already served by agencies, using service records rather than interviews.' },
      { id: 'c', text: 'Field survey', isCorrect: false, rationale: 'A field survey gathers data directly from a sample of the general population, not selected leaders.' },
      { id: 'd', text: 'Key informant', isCorrect: true, rationale: 'The key informant approach gathers views from people whose roles give them broad knowledge of community needs.' },
    ],
    rationale: 'Needs assessment approaches include key informant, community forum, rates under treatment, social indicators and field survey methods. The key informant approach is quick and inexpensive, drawing on leaders and professionals who see many community members. Its main weakness is that informants may reflect their own roles and biases, so it is often combined with other methods.',
    references: [{ source: 'Warheit et al. (Needs Assessment)', detail: 'Key informant approach compared with community forum, rates-under-treatment, social indicators and field survey' }],
  },
  {
    id: 'nce-s-trt-115',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'hard',
    stem: 'A researcher randomly assigns clients to four groups. Two groups take a pretest on self-esteem and two do not; within each pair, one group receives a new intervention and one does not. All four groups take the posttest. What is the MAIN purpose of this design?',
    options: [
      { id: 'a', text: 'To find out if taking the pretest itself changes how people do on the posttest', isCorrect: true, rationale: 'The Solomon four-group design adds unpretested groups so pretest sensitization and its interaction with treatment can be checked.' },
      { id: 'b', text: 'To let each client serve as his or her own control across several conditions', isCorrect: false, rationale: 'That describes a within-subjects or crossover design, where each participant receives every condition.' },
      { id: 'c', text: 'To compare the effects of four different interventions within a single study', isCorrect: false, rationale: 'Only one intervention is tested; the four groups vary pretesting and treatment, not four treatments.' },
      { id: 'd', text: 'To follow up clients over time to learn how long the treatment gains will last', isCorrect: false, rationale: 'Durability of effects is studied with follow-up assessments, not by varying who takes a pretest.' },
    ],
    rationale: 'The Solomon four-group design combines a pretest-posttest control group design with a posttest-only control group design. Comparing pretested and unpretested groups shows whether the pretest itself sensitized participants or interacted with the treatment, a threat to external validity. It is a strong design, but it needs twice as many groups and participants.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Experimental designs: Solomon four-group design and control of pretest sensitization' }],
  },
  {
    id: 'nce-s-trt-116',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'research design basics',
    difficulty: 'medium',
    stem: 'In a study at one middle school, students in some homerooms receive a new conflict resolution curriculum while other homerooms serve as controls. Midway through, control-group teachers begin using the lessons after hearing about them in the staff lounge. Which threat to internal validity has occurred?',
    options: [
      { id: 'a', text: 'Statistical regression', isCorrect: false, rationale: 'Regression is the drift of extreme scores toward the mean on retesting, which is not described here.' },
      { id: 'b', text: 'Maturation', isCorrect: false, rationale: 'Maturation is natural change in participants over time, not a spread of the intervention.' },
      { id: 'c', text: 'Diffusion of treatment', isCorrect: true, rationale: 'The control group received parts of the treatment, which shrinks the difference between groups.' },
      { id: 'd', text: 'Instrumentation', isCorrect: false, rationale: 'Instrumentation is a change in the measures or raters, not in what the control group received.' },
    ],
    rationale: 'Diffusion (or contamination) of treatment occurs when people in the control condition are exposed to the intervention, often because groups are in the same setting and share information. It makes the groups more alike and can hide a real effect. Researchers limit it by separating groups, for example by assigning whole schools rather than homerooms.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Threats to internal validity: diffusion of treatment' }],
  },
  {
    id: 'nce-s-trt-117',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'easy',
    stem: 'A counselor gives an interval-scale anxiety measure to the same 25 clients at intake and again after ten sessions. She wants to know whether the average score changed significantly. Which statistical test is MOST appropriate?',
    options: [
      { id: 'a', text: 'Independent-samples t test', isCorrect: false, rationale: 'This test compares two separate groups of people, not the same people measured twice.' },
      { id: 'b', text: 'Paired-samples t test', isCorrect: true, rationale: 'A paired (dependent) t test compares two means from the same participants, such as pretest and posttest.' },
      { id: 'c', text: 'Chi-square test', isCorrect: false, rationale: 'Chi-square tests frequencies in categories, not means of interval-scale scores.' },
      { id: 'd', text: 'Pearson correlation', isCorrect: false, rationale: 'A correlation shows how two variables relate, not whether the mean changed from pretest to posttest.' },
    ],
    rationale: 'When the same participants are measured twice on an interval or ratio variable, the scores are related, and a paired-samples (dependent) t test is used to compare the two means. An independent-samples t test would wrongly treat the pretest and posttest scores as coming from different people. With three or more time points, a repeated-measures ANOVA would be used instead.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Inferential statistics: dependent (paired) samples t test for pretest-posttest comparisons' }],
  },
  {
    id: 'nce-s-trt-118',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'statistics used in outcome research',
    difficulty: 'medium',
    stem: 'An agency wants to know whether the share of clients who complete treatment (completed or dropped out) differs across its three outpatient programs. Each client is counted once, in one program. Which statistical test is MOST appropriate?',
    options: [
      { id: 'a', text: 'Paired-samples t test', isCorrect: false, rationale: 'A paired t test compares two means from the same people, and the outcome here is a category, not a score.' },
      { id: 'b', text: 'One-way ANOVA', isCorrect: false, rationale: 'ANOVA compares group means on an interval or ratio variable; completion is a yes or no category.' },
      { id: 'c', text: 'Pearson correlation', isCorrect: false, rationale: 'Pearson r requires two continuous variables, but both program and completion are categorical.' },
      { id: 'd', text: 'Chi-square test of independence', isCorrect: true, rationale: 'Chi-square tests whether frequencies in one categorical variable differ across levels of another.' },
    ],
    rationale: 'When both variables are categorical, here program (three levels) and completion status (two levels), the data are counts in a contingency table. The chi-square test of independence compares the observed counts with those expected if the variables were unrelated. It is a nonparametric test and requires each person to appear in only one cell.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Nonparametric statistics: chi-square test of independence for nominal data' }],
  },
  {
    id: 'nce-s-trt-119',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'medium',
    stem: 'A 26-year-old Deaf client has been seeing a counselor fluent in American Sign Language for social anxiety. Her plan is due for review in two months. This week her father died suddenly, and she is now barely sleeping and missing work. What should the counselor do?',
    options: [
      { id: 'a', text: 'Revise the treatment plan with her now so it addresses her grief and new needs', isCorrect: true, rationale: 'A significant change in the client\'s life is a reason to update the plan with her, rather than waiting for the scheduled review.' },
      { id: 'b', text: 'Keep to the current plan and take up her grief at the review in two months', isCorrect: false, rationale: 'Waiting leaves the plan out of step with her current needs during a time of acute distress.' },
      { id: 'c', text: 'Talk about her grief in sessions but leave the plan and the notes as they are', isCorrect: false, rationale: 'Treating new problems without updating the plan leaves the record inaccurate and the work unguided by goals.' },
      { id: 'd', text: 'Refer her to a grief counselor and pause the anxiety work until she feels better', isCorrect: false, rationale: 'An abrupt referral can disrupt a working alliance; the current counselor can address her grief within a revised plan.' },
    ],
    rationale: 'A treatment plan is a living document. It is reviewed on a set schedule and also whenever the client\'s situation changes in an important way, such as a death, a crisis or a new diagnosis. Revising the plan together keeps the goals relevant to what the client needs now and keeps the record accurate.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plan updates: revising goals and objectives when the client\'s needs change significantly' }],
  },
];
