// tools/nce/seed/treatment-5.js — Treatment Planning, batch 5
// Hand-authored original items (nce-s-trt-069 … nce-s-trt-085).
module.exports = [
  {
    id: 'nce-s-trt-069',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A 52-year-old client drinks about a fifth of vodka daily and wants to stop. The last time he quit on his own, he had a withdrawal seizure and was taken to an emergency department. He has stable housing and a supportive sister. Which recommendation is MOST appropriate as the first step?',
    options: [
      { id: 'a', text: 'Begin weekly outpatient counseling with a goal of stopping alcohol use within two weeks', isCorrect: false, rationale: 'Weekly outpatient care offers no medical monitoring; stopping abruptly with his seizure history puts him at serious risk.' },
      { id: 'b', text: 'Enroll him in an intensive outpatient program and have him taper his drinking on his own', isCorrect: false, rationale: 'A self-directed taper is unreliable and unsupervised; IOP does not provide the medical management his withdrawal risk requires.' },
      { id: 'c', text: 'Refer him for medically monitored withdrawal management before planning ongoing treatment', isCorrect: true, rationale: 'A history of withdrawal seizures signals high withdrawal risk, so medically supervised withdrawal management is the safe first step.' },
      { id: 'd', text: 'Arrange a stay in a sober living home so he can stop drinking in an alcohol-free setting', isCorrect: false, rationale: 'Sober living provides a substance-free environment but no medical care; it does not address dangerous withdrawal.' },
    ],
    rationale: 'Level-of-care decisions in addiction treatment consider several dimensions, and acute intoxication and withdrawal potential is assessed first because it can be life-threatening. A prior withdrawal seizure with heavy daily drinking signals high risk for complicated alcohol withdrawal. He should first receive medically monitored withdrawal management; his supportive environment can then help him step into an appropriate ongoing level of care.',
    references: [{ source: 'ASAM Criteria', detail: 'Withdrawal potential dimension: history of withdrawal seizures and medically monitored withdrawal management' }],
  },
  {
    id: 'nce-s-trt-070',
    domain: 'treatment',
    cacrep: 'assessment',
    topic: 'matching level of care to need',
    difficulty: 'medium',
    stem: 'A 36-year-old teacher meets criteria for mild alcohol use disorder. She has no withdrawal symptoms or medical problems, is motivated to cut back, and lives with a supportive partner. Her counselor recommends a 28-day residential program "just to be safe." What is the MAIN concern with this recommendation?',
    options: [
      { id: 'a', text: 'It places her at a more intensive level than needed and may disrupt her work and supports', isCorrect: true, rationale: 'Care should be the least intensive level that safely meets her needs; residential care would pull her from her job and partner without clinical need.' },
      { id: 'b', text: 'Residential programs are designed only for clients who have already failed outpatient care', isCorrect: false, rationale: 'Placement is based on current multidimensional need, not on a required sequence of failed lower levels.' },
      { id: 'c', text: 'A 28-day stay is too short to change a drinking pattern that has lasted for several years', isCorrect: false, rationale: 'The problem is not the length of the stay but that residential care is not indicated for her at all.' },
      { id: 'd', text: 'Her motivation shows she does not need any formal treatment for her alcohol use at this time', isCorrect: false, rationale: 'Motivation is a strength, but she still meets criteria for a disorder and can benefit from outpatient treatment.' },
    ],
    rationale: 'Placement criteria aim to match clients to the least intensive level of care that is safe and effective, based on a multidimensional assessment. Over-placement wastes resources and can harm clients by disrupting protective factors such as employment, family and community ties. With no withdrawal risk, no medical or psychiatric complications and a supportive home, outpatient treatment fits this client.',
    references: [{ source: 'ASAM Criteria', detail: 'Multidimensional assessment and placement in the least intensive level of care that is safe and effective' }],
  },
  {
    id: 'nce-s-trt-071',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'medium',
    stem: 'A 58-year-old retired nurse has had trouble falling and staying asleep at least four nights a week for over a year. Medical and substance-related causes have been ruled out, and she would prefer not to take sleep medication. Which psychological treatment has the strongest evidence as a first-line approach?',
    options: [
      { id: 'a', text: 'Sleep hygiene education given on its own, such as limiting caffeine and keeping a dark room', isCorrect: false, rationale: 'Sleep hygiene is a useful component, but guidelines advise against using it alone because it is not effective as a single therapy.' },
      { id: 'b', text: 'Psychodynamic therapy aimed at uncovering the early conflicts that are keeping her awake', isCorrect: false, rationale: 'Psychodynamic therapy is not an established first-line treatment for chronic insomnia.' },
      { id: 'c', text: 'Progressive muscle relaxation practiced in session, with no change to her sleep schedule', isCorrect: false, rationale: 'Relaxation can help, but alone it lacks the support of the multicomponent package that restructures sleep behavior.' },
      { id: 'd', text: 'Cognitive behavioral therapy for insomnia, including stimulus control and sleep restriction', isCorrect: true, rationale: 'CBT-I is the recommended first-line treatment for chronic insomnia in adults, with strong research support.' },
    ],
    rationale: 'Cognitive behavioral therapy for insomnia (CBT-I) is a multicomponent treatment that combines stimulus control, sleep restriction, cognitive work on sleep-related beliefs and sleep hygiene education. Clinical practice guidelines strongly recommend it as the first-line treatment for chronic insomnia in adults. Sleep hygiene education is helpful as part of the package but is not recommended as a stand-alone therapy.',
    references: [{ source: 'AASM Clinical Practice Guideline (Insomnia)', detail: 'Behavioral and psychological treatments for chronic insomnia: strong recommendation for multicomponent CBT-I; sleep hygiene not recommended as a single therapy' }],
  },
  {
    id: 'nce-s-trt-072',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'evidence-based treatment selection',
    difficulty: 'hard',
    stem: 'A 33-year-old client with bipolar I disorder takes lithium as prescribed. Her mood episodes tend to follow disruptions such as overnight shifts, travel across time zones and conflicts with her partner. Her psychiatrist asks the counselor to provide an adjunctive psychotherapy suited to this pattern. Which approach BEST fits?',
    options: [
      { id: 'a', text: 'Exposure and response prevention focused on reducing her worry about future mood swings', isCorrect: false, rationale: 'ERP is a treatment for obsessive-compulsive disorder and does not target the rhythm disruptions linked to her episodes.' },
      { id: 'b', text: 'Interpersonal and social rhythm therapy to stabilize daily routines and address conflicts', isCorrect: true, rationale: 'IPSRT was developed for bipolar disorder; it regularizes sleep and daily routines and addresses interpersonal problems that trigger episodes.' },
      { id: 'c', text: 'Person-centered therapy alone, letting her choose the focus of each session as it unfolds', isCorrect: false, rationale: 'A supportive nondirective approach does not provide the structured rhythm and interpersonal work her pattern calls for.' },
      { id: 'd', text: 'Psychoanalytic therapy several times weekly to explore unconscious roots of her moods', isCorrect: false, rationale: 'Intensive psychoanalytic therapy is not an evidence-based adjunct for bipolar disorder and does not target rhythm stability.' },
    ],
    rationale: 'Interpersonal and social rhythm therapy (IPSRT), developed by Ellen Frank, combines interpersonal psychotherapy with behavioral work on stabilizing daily routines and sleep-wake cycles. It rests on the idea that disrupted social rhythms destabilize circadian functioning and can trigger mood episodes in bipolar disorder. It is used as an adjunct to medication, which fits a client whose episodes follow schedule disruptions and relationship conflicts.',
    references: [{ source: 'IPSRT', detail: 'Social rhythm stabilization and interpersonal problem areas as an adjunct to medication in bipolar disorder' }],
  },
  {
    id: 'nce-s-trt-073',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'hard',
    stem: 'An experienced counselor declines to use session-by-session outcome measures, saying, "After 20 years, I can tell when a client is getting worse." Which research finding MOST directly challenges this view?',
    options: [
      { id: 'a', text: 'Clinicians rarely predict which clients will deteriorate; measure-based alerts flag most', isCorrect: true, rationale: 'Studies comparing clinician predictions with actuarial alerts found that therapists identified very few deteriorating clients, while measures flagged most of them.' },
      { id: 'b', text: 'Experienced clinicians tend to underestimate how much progress their clients are making', isCorrect: false, rationale: 'Research suggests the opposite bias: clinicians tend to overestimate client improvement.' },
      { id: 'c', text: 'Most clients who get worse in counseling say so openly to their counselor within a session', isCorrect: false, rationale: 'Clients often do not voice deterioration directly, which is one reason structured measures are useful.' },
      { id: 'd', text: 'Standardized measures are accurate only when they are given at intake and at the final session', isCorrect: false, rationale: 'Pre-post measurement cannot detect deterioration while there is still time to respond; frequent monitoring is the point.' },
    ],
    rationale: 'Research on routine outcome monitoring found that clinicians, including experienced ones, are poor at predicting which clients will deteriorate, while statistical early-warning systems based on expected recovery curves identify most of them. Clinicians also tend to overrate their own effectiveness. Feedback from frequent standardized measures helps counselors catch clients who are not on track and change course before dropout or treatment failure.',
    references: [{ source: 'Lambert (Outcome Monitoring)', detail: 'Clinician judgment versus actuarial prediction in detecting client deterioration' }],
  },
  {
    id: 'nce-s-trt-074',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'progress monitoring and outcome measures',
    difficulty: 'easy',
    stem: 'A counselor plans to track a client\'s anxiety with a brief standardized self-report measure over the course of treatment. When should the counselor give the measure for the FIRST time?',
    options: [
      { id: 'a', text: 'Once the client has learned the coping skills, so the scores show what they have gained', isCorrect: false, rationale: 'Waiting until skills are learned removes the starting point needed to show how much the client has changed.' },
      { id: 'b', text: 'At the midpoint of treatment, when the counselor is deciding whether to change approaches', isCorrect: false, rationale: 'A midpoint score has nothing to be compared against unless an earlier baseline was taken.' },
      { id: 'c', text: 'At intake or before treatment starts, to set a baseline for comparing later scores', isCorrect: true, rationale: 'A pretreatment score is the baseline against which every later score is compared.' },
      { id: 'd', text: 'At the final session, so the counselor can document the client\'s status at discharge', isCorrect: false, rationale: 'A discharge score alone cannot show change; it needs a baseline taken before treatment.' },
    ],
    rationale: 'Progress monitoring depends on a baseline: a measurement taken at intake or before treatment begins. Later scores are interpreted relative to that starting point, which allows the counselor to judge whether change is meaningful. Without a baseline, improvement or deterioration cannot be shown.',
    references: [{ source: 'Hays (Assessment)', detail: 'Outcome assessment: establishing a baseline before treatment for progress monitoring' }],
  },
  {
    id: 'nce-s-trt-075',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'discharge and aftercare planning',
    difficulty: 'medium',
    stem: 'A 41-year-old client has met all the goals in her treatment plan for depression, and her scores have stayed in the nonclinical range for two months. She says she feels ready to stop. Her counselor would like to keep meeting weekly to "work on deeper issues." What should the counselor do?',
    options: [
      { id: 'a', text: 'Continue weekly sessions, since further personal growth is still possible for the client', isCorrect: false, rationale: 'Continuing when goals are met and the client wants to stop serves the counselor\'s agenda, not a clinical need.' },
      { id: 'b', text: 'Review her gains, plan for maintaining them, and discharge her with an option to return', isCorrect: true, rationale: 'When the client no longer needs counseling, the counselor ends it with a planned discharge and aftercare guidance.' },
      { id: 'c', text: 'End services at this session without further discussion, since the treatment goals are met', isCorrect: false, rationale: 'Ending abruptly skips the review, relapse-prevention planning and aftercare that a planned discharge includes.' },
      { id: 'd', text: 'Write new long-term goals in the plan so that continued weekly sessions are justified', isCorrect: false, rationale: 'Adding goals the client did not ask for to justify services is not collaborative and is ethically questionable.' },
    ],
    rationale: 'Counselors end counseling when it is reasonably apparent that the client no longer needs assistance, is unlikely to benefit or is being harmed. A planned discharge reviews progress toward goals, consolidates gains, identifies early warning signs and coping strategies, and tells the client how to return if needed. The client\'s readiness and goal attainment, not the counselor\'s wish to continue, guide the decision.',
    references: [
      { source: 'ACA Code of Ethics', detail: 'A.11.c Appropriate Termination' },
      { source: 'Wiger (Documentation)', detail: 'Discharge summary: progress toward goals and aftercare recommendations' },
    ],
  },
  {
    id: 'nce-s-trt-076',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'safety planning',
    difficulty: 'easy',
    stem: 'A new counselor asks why the agency uses a written safety plan with clients at risk of suicide instead of asking them to sign a "no-suicide contract." Which explanation is MOST accurate?',
    options: [
      { id: 'a', text: 'A signed contract legally shields the counselor, but it is too formal for most clients', isCorrect: false, rationale: 'No-suicide contracts offer no reliable legal protection, and formality is not the main problem with them.' },
      { id: 'b', text: 'A contract is the better tool, but a safety plan takes less session time to complete', isCorrect: false, rationale: 'Contracts are not the better tool, and a good safety plan takes time to build collaboratively.' },
      { id: 'c', text: 'A safety plan replaces the need for any further suicide risk assessment of the client', isCorrect: false, rationale: 'A safety plan supplements ongoing risk assessment; it does not replace it.' },
      { id: 'd', text: 'A safety plan builds specific coping steps, while a contract lacks evidence of benefit', isCorrect: true, rationale: 'Safety plans give clients concrete steps and resources for a crisis; no-suicide contracts lack research support and can give false reassurance.' },
    ],
    rationale: 'No-suicide contracts ask a client to promise not to harm themselves but give them nothing to do in a crisis, lack evidence of effectiveness and may give counselors false reassurance. A safety plan, such as the Stanley-Brown Safety Planning Intervention, is developed collaboratively and lists warning signs, internal coping strategies, social contacts, people to ask for help, professional and crisis resources, and steps to make the environment safer.',
    references: [{ source: 'Stanley-Brown SPI', detail: 'Safety planning as an alternative to no-suicide contracts' }],
  },
  {
    id: 'nce-s-trt-077',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'medium',
    stem: 'A 47-year-old client who has smoked for 30 years tells his counselor that he has picked a quit date two weeks from now, bought nicotine patches and told his family. Which counselor response BEST matches his current stage of change?',
    options: [
      { id: 'a', text: 'Help him build a specific quit plan that anticipates triggers and names his coping steps', isCorrect: true, rationale: 'He is in preparation, so the task is to firm up a concrete, workable action plan.' },
      { id: 'b', text: 'Give him information about the health risks of smoking to raise his awareness of them', isCorrect: false, rationale: 'Consciousness raising fits precontemplation; he is already convinced and taking steps.' },
      { id: 'c', text: 'Explore his mixed feelings by listing the pros and cons of smoking and of quitting', isCorrect: false, rationale: 'A decisional balance exercise suits contemplation, when the client is still ambivalent about changing.' },
      { id: 'd', text: 'Focus on preventing relapse in the months after he has stayed smoke-free for a while', isCorrect: false, rationale: 'Relapse prevention for sustained change belongs to the maintenance stage, which he has not reached.' },
    ],
    rationale: 'In the Transtheoretical Model, the preparation stage describes people who intend to act within about the next month and have already taken small steps, such as setting a date or buying supplies. Stage-matched interventions in preparation help the client turn intention into a concrete plan, anticipate obstacles and strengthen commitment. Interventions suited to earlier stages can feel redundant to a client who has already decided.',
    references: [{ source: 'Transtheoretical Model', detail: 'Preparation stage: intention to act within 30 days and stage-matched action planning' }],
  },
  {
    id: 'nce-s-trt-078',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'stages of change and treatment readiness',
    difficulty: 'hard',
    stem: 'A 29-year-old client stopped using methamphetamine eight months ago but used again for three days after a breakup. She tells her counselor, "I\'m back at square one." According to Prochaska and DiClemente\'s model, which statement BEST reflects how relapse is understood?',
    options: [
      { id: 'a', text: 'Relapse sends most people back to precontemplation, so change must restart from the start', isCorrect: false, rationale: 'Only a small share of people who relapse regress to precontemplation; most do not start over.' },
      { id: 'b', text: 'Relapse after six months shows the client had not truly reached the maintenance stage', isCorrect: false, rationale: 'Relapse can occur from maintenance; it does not mean the earlier progress was not real.' },
      { id: 'c', text: 'Relapse is common, and most people recycle to contemplation or preparation and try again', isCorrect: true, rationale: 'The spiral model shows that most people who relapse recycle to contemplation or preparation and draw on what they learned.' },
      { id: 'd', text: 'Relapse shows that the stages of change model does not apply to stimulant use disorders', isCorrect: false, rationale: 'The model has been applied across many addictive behaviors, including stimulant use, and expects relapse.' },
    ],
    rationale: 'Prochaska, DiClemente and Norcross described change as a spiral rather than a straight line. Relapse is common, and most people who relapse do not regress all the way to precontemplation; they recycle to contemplation or preparation and try again, often with lessons from earlier attempts. Framing relapse this way helps counselors counter the client\'s "square one" thinking and reduce shame.',
    references: [{ source: 'Transtheoretical Model', detail: 'Spiral model of change: relapse and recycling through the stages' }],
  },
  {
    id: 'nce-s-trt-079',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'hard',
    stem: 'A client\'s primary care physician calls the counselor to coordinate care and asks for "everything you have," including the private process notes the counselor keeps separate from the client\'s clinical record. Under HIPAA, which statement is accurate?',
    options: [
      { id: 'a', text: 'HIPAA bars the counselor from sharing any client information with a physician without consent', isCorrect: false, rationale: 'HIPAA allows disclosure of protected health information to another provider for treatment; it does not bar all sharing.' },
      { id: 'b', text: 'The physician may obtain the process notes because they are part of the client\'s medical record', isCorrect: false, rationale: 'Psychotherapy notes kept separate from the record are not part of the general medical record and receive extra protection.' },
      { id: 'c', text: 'All records, process notes included, may be sent because disclosure for treatment is permitted', isCorrect: false, rationale: 'The treatment exception does not cover psychotherapy notes, which need specific authorization.' },
      { id: 'd', text: 'The process notes need the client\'s specific authorization; record information may be shared', isCorrect: true, rationale: 'Psychotherapy notes generally need a separate authorization, while information in the clinical record may be shared for treatment.' },
    ],
    rationale: 'HIPAA gives psychotherapy notes, the counselor\'s separate notes analyzing session content, special protection: most disclosures, including to other providers, require the client\'s specific authorization. Information in the clinical record, such as diagnosis, treatment plan, symptoms and progress summaries, may be disclosed to another provider for treatment purposes. Many counselors still obtain a release before coordinating care, and state law or ethics codes may require stricter consent.',
    references: [
      { source: 'HIPAA', detail: 'Privacy Rule 45 CFR 164.508(a)(2): authorization required for psychotherapy notes; 164.506 disclosures for treatment' },
    ],
  },
  {
    id: 'nce-s-trt-080',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'SMART goals and measurable objectives',
    difficulty: 'easy',
    stem: 'A 30-year-old client seeks counseling because panic attacks keep her from driving on the highway to work. Her counselor adds this objective: "Client will walk 30 minutes three times a week for the next eight weeks, as recorded in an exercise log." Which SMART criterion is this objective MOST likely to fail?',
    options: [
      { id: 'a', text: 'Measurable, because walking cannot be counted or recorded in any reliable way', isCorrect: false, rationale: 'Walking time and frequency are easy to record in a log, so the objective is measurable.' },
      { id: 'b', text: 'Relevant, because it is not clearly tied to the problem the client came in for', isCorrect: true, rationale: 'Nothing links walking to her highway-driving panic, so the objective does not fit her presenting concern.' },
      { id: 'c', text: 'Time-bound, because the objective does not give any time period for the change', isCorrect: false, rationale: 'The objective states an eight-week period, so it is time-bound.' },
      { id: 'd', text: 'Specific, because the objective does not state how often or how long she will walk', isCorrect: false, rationale: 'The objective names the activity, duration and frequency, so it is specific.' },
    ],
    rationale: 'SMART objectives are Specific, Measurable, Achievable, Relevant and Time-bound. This objective is precise, countable and time-limited, but it does not connect to the client\'s stated problem of panic while driving on highways. Relevant objectives flow from the presenting concern and the goal, such as graded driving exposure tracked in a log.',
    references: [{ source: 'Wiger (Documentation)', detail: 'Treatment plans: objectives linked to the presenting problem and long-term goals' }],
  },
  {
    id: 'nce-s-trt-081',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'collaborative treatment planning',
    difficulty: 'medium',
    stem: 'A 30-year-old man with a mild intellectual disability lives in a group home and is starting counseling for anger after conflicts with a housemate. The group home manager offers to write his treatment goals for him to save time. What is the BEST approach?',
    options: [
      { id: 'a', text: 'Build goals with him in plain words with visual aids, inviting staff input if he agrees', isCorrect: true, rationale: 'Adapting the process to his abilities keeps him at the center of planning, with staff involved only with his consent.' },
      { id: 'b', text: 'Accept the manager\'s goals, since staff observe his daily behavior more than he can report', isCorrect: false, rationale: 'Staff observations are useful input, but letting staff set his goals removes him from his own treatment planning.' },
      { id: 'c', text: 'Write the goals in standard clinical language and read them aloud to him for his signature', isCorrect: false, rationale: 'Having him sign a plan he did not shape, in language he may not understand, is not meaningful collaboration.' },
      { id: 'd', text: 'Delay planning until a court-appointed guardian can be found to decide on his goals', isCorrect: false, rationale: 'Nothing indicates he lacks capacity or has a guardian; a disability alone does not remove his right to participate.' },
    ],
    rationale: 'Counselors and clients work jointly to devise counseling plans that fit the client\'s abilities, developmental level and circumstances. For a client with an intellectual disability, collaboration means adapting the process, using plain language, concrete examples and visual supports, rather than handing planning to others. Support staff can contribute valuable information when the client agrees.',
    references: [{ source: 'ACA Code of Ethics', detail: 'A.1.c Counseling Plans: plans consistent with the abilities, developmental level and circumstances of clients' }],
  },
  {
    id: 'nce-s-trt-082',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'easy',
    stem: 'At the end of its first full year, a middle school\'s peer mediation program is evaluated so the school board can decide whether to continue funding it. Which type of evaluation is this?',
    options: [
      { id: 'a', text: 'Formative evaluation', isCorrect: false, rationale: 'Formative evaluation gathers feedback during a program to improve it, not to judge it for a funding decision.' },
      { id: 'b', text: 'Needs assessment', isCorrect: false, rationale: 'A needs assessment identifies gaps before a program is designed; it does not judge an existing program.' },
      { id: 'c', text: 'Single-subject design', isCorrect: false, rationale: 'A single-subject design tracks one person\'s behavior across phases, not a whole program\'s worth.' },
      { id: 'd', text: 'Summative evaluation', isCorrect: true, rationale: 'Summative evaluation judges a program\'s overall effectiveness at the end of a cycle to inform decisions such as continuing funding.' },
    ],
    rationale: 'Summative evaluation takes place at the end of a program or program cycle and judges its overall merit or effectiveness, often to inform decisions about continuing, expanding or ending it. Formative evaluation, by contrast, happens while a program is running and is used to improve it. A board deciding on future funding needs a summative judgment.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Program evaluation: formative vs summative evaluation' }],
  },
  {
    id: 'nce-s-trt-083',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'medium',
    stem: 'To estimate the need for youth mental health services in a county, an agency analyzes existing census data, school dropout rates, juvenile arrest records and emergency department visits for self-harm. No residents or providers are contacted directly. Which needs assessment method is the agency using?',
    options: [
      { id: 'a', text: 'Key informant approach', isCorrect: false, rationale: 'This method gathers views from knowledgeable people such as clinicians or community leaders, who were not contacted here.' },
      { id: 'b', text: 'Community forum approach', isCorrect: false, rationale: 'A community forum invites residents to public meetings to voice needs; no residents were involved.' },
      { id: 'c', text: 'Social indicators approach', isCorrect: true, rationale: 'This method infers need from existing public statistics such as census, school and health records.' },
      { id: 'd', text: 'Field survey of residents', isCorrect: false, rationale: 'A field survey collects new data directly from a sample of residents, which the agency did not do.' },
    ],
    rationale: 'Needs assessments can draw on several methods. The social indicators approach infers community need from existing public data, such as census figures, health statistics and school or court records. Key informant interviews, community forums and field surveys all collect new information directly from people. Many needs assessments combine methods because existing data alone may miss what residents and providers see.',
    references: [{ source: 'Warheit et al. (Needs Assessment)', detail: 'Social indicators approach: inferring need from existing public statistics' }, { source: 'Erford (Research and Evaluation in Counseling)', detail: 'Needs assessment methods in program evaluation' }],
  },
  {
    id: 'nce-s-trt-084',
    domain: 'treatment',
    cacrep: 'research',
    topic: 'program evaluation and needs assessment',
    difficulty: 'medium',
    stem: 'An evaluator of a new parenting program at a community center records how many sessions are offered, who attends, whether the target families of toddlers are being reached and whether facilitators cover each planned module. She does not yet measure changes in parenting. Which type of evaluation is she conducting?',
    options: [
      { id: 'a', text: 'Outcome evaluation', isCorrect: false, rationale: 'An outcome evaluation measures changes in participants, such as parenting skills, which she is not yet doing.' },
      { id: 'b', text: 'Process evaluation', isCorrect: true, rationale: 'Process evaluation examines how a program is delivered: reach, attendance and whether it runs as planned.' },
      { id: 'c', text: 'Needs assessment', isCorrect: false, rationale: 'A needs assessment identifies gaps before a program is built; this program is already running.' },
      { id: 'd', text: 'Cost-benefit study', isCorrect: false, rationale: 'A cost-benefit study compares program costs with outcomes converted to dollars; no costs are examined here.' },
    ],
    rationale: 'Process (implementation) evaluation asks whether a program is being delivered as intended and to the intended population, tracking things like attendance, reach and coverage of planned content. Outcome evaluation asks whether participants changed as a result. Process data also help interpret outcomes, because a program that is not delivered as planned cannot fairly be judged ineffective.',
    references: [{ source: 'Erford (Research and Evaluation in Counseling)', detail: 'Program evaluation: process vs outcome evaluation' }],
  },
  {
    id: 'nce-s-trt-085',
    domain: 'treatment',
    cacrep: 'helping_relationships',
    topic: 'coordination of care and referral',
    difficulty: 'medium',
    stem: 'A counselor in a rural clinic refers a 66-year-old client with worsening depression to a telepsychiatry service for a medication evaluation. The client signs a release so the two providers can share information. What should the counselor do to BEST complete the referral?',
    options: [
      { id: 'a', text: 'Follow up to confirm the appointment took place and share relevant information as agreed', isCorrect: true, rationale: 'Closing the loop confirms the client connected with care and lets both providers coordinate treatment.' },
      { id: 'b', text: 'Give the client the service\'s phone number and leave the scheduling and follow-up to him', isCorrect: false, rationale: 'Passing on a number without follow-up is a passive referral and raises the risk that the client never connects.' },
      { id: 'c', text: 'End counseling once the referral is made, since the psychiatrist now manages his depression', isCorrect: false, rationale: 'A medication evaluation adds to counseling; ending services would leave the client without psychotherapy.' },
      { id: 'd', text: 'Wait to discuss the referral until his next monthly session in case he brings it up himself', isCorrect: false, rationale: 'Waiting passively for the client to raise it can leave a worsening depression without timely follow-up.' },
    ],
    rationale: 'A referral is complete only when the client actually connects with the new service. Good care coordination includes helping the client schedule, confirming the appointment occurred, and, with consent, sharing information so both providers work from the same plan. Active follow-up matters especially for older or rural clients, who may face transportation, technology or access barriers.',
    references: [{ source: 'Gladding (Counseling: A Comprehensive Profession)', detail: 'Clinical mental health counseling settings: referral, follow-up and coordination with medical providers' }],
  },
];
